### ISSUE TITLE
Return statements clip into the bottom of other statements

### ISSUE THREAD

**Issue by ProjectHSI** [microsoft/pxt#10013]
**Describe the bug**
The return statement clips into the bottom of other statements when it is inside of those statements.

**To Reproduce**
1. Create a function.
2. Put a if statement in that function.
3. Grab a return statement in that block. This might happen with other ending blocks, although this is not tested.
4. The return statement now intersects the bottom of the if statement.

Note that this happens with the return statement by itself, it appears to clip into the function block slightly.

**Expected behavior**
The return statement terminates the if statement cleanly. That being there isn't any clipping going on.

**Screenshots**
<img width="377" alt="Screenshot 2023-05-16 095558" src="https://github.com/microsoft/pxt-microbit/assets/57279339/0b4f9a82-096f-478a-98e4-d0d5775e2eef">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 
 - Version: 113.0.1 (64-bit) (Original Bug Report Version - Confirmed broken on 125.0.3 (64-bit))

**Additional context**
I'm not entirely sure about the [Issues Policy](https://github.com/microsoft/pxt/blob/master/CONTRIBUTING.md#issue-tracker-guidance).

**This issue was ignored in https://github.com/microsoft/pxt-microbit and has been posted here as a result of that. The original issue can be found at https://github.com/microsoft/pxt-microbit/issues/5142 and has not been closed.**

**Comment by ProjectHSI** [comment]
Issue Clarification: Return statement visuals are buggy in general, and don't just occur with if statements.

**Comment by abchatra** [comment]
Bug is tracked in pxt-microbit repo.
