### ISSUE TITLE
Blockly variable name encoding causes error

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt#1005]
This Blockly:
<img width="246" alt="screen shot 2016-12-29 at 2 14 28 pm" src="https://cloud.githubusercontent.com/assets/6453828/21555895/293919fc-cdd1-11e6-9710-2b6c0b0e7c89.png">

Converts to this Typescript:
<img width="188" alt="screen shot 2016-12-29 at 2 12 48 pm" src="https://cloud.githubusercontent.com/assets/6453828/21555899/316f5d5c-cdd1-11e6-92a6-f36613eca426.png">

And my program won't build or run.

**Comment by pelikhan** [comment]
Related to https://github.com/Microsoft/pxt/issues/1001

**Comment by riknoll** [comment]
This reproduces with any variable name that starts with a number

**Comment by darzu** [comment]
Note that my program won't build even if I don't convert to Typescript. Staying in Blockly isn't a workaround.
