### ISSUE TITLE
The "Getting Started" page doesn't lead users to the code editor

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt#1007]
Starting from this page: [https://pxt.microbit.org/getting-started]( https://pxt.microbit.org/getting-started), I can find no obvious way to navigate to the code editor.

**The story:**
A friend of mine had a micro:bit and wanted to know how to program it. I told them to look up "microbit pxt" and they landed on the "getting started" page which seemed promising to them. However, they spent a while looking through the document and loading sample programs onto their micro:bit, but at no point could they figure out how to write programs themselves. They asked me "Is this how I program the micro:bit? Just downloading examples?"

Starting from the "Getting Started" page, it really isn't clear to new users that they should open a second tab and find the actual programming editor.

**Comment by OwenBrotherwood** [comment]
There is no real indication that one should click on the micro:bit "eyes" logo, but a second tab is not necessary.

![image](https://cloud.githubusercontent.com/assets/866122/21556908/41cd86c0-ce25-11e6-95f3-b742f91e181d.png)

**Comment by pelikhan** [comment]
Related to https://github.com/Microsoft/pxt/issues/887

**Comment by abchatra** [comment]
Fixed with the new getting started experience.
