### ISSUE TITLE
forever should be treated as statement, not event

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1011]
"Forever" is not an event and should be treated as a statement. To match Scratch, it should have 
- [ ] previous statement connector
- [ ] no next statement connector
 
Included in the ``on start`` function.

**Comment by riknoll** [comment]
The semantics of the scratch forever are different than ours. The scratch one is basically a `while(true)` loop.

For example, this code:

![scratch_forever](https://cloud.githubusercontent.com/assets/13754588/21570748/d8f2f0c8-ce7d-11e6-8b23-e86b0dcbe6f0.PNG)

will never reach the "Say hello" block. I don't think that making it a statement is a good idea in the blocks, most the time it is likely a bug.
