### ISSUE TITLE
Blog Post - Micro:bit 2024 update

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#10125]
Hi Galen, can you please prep this blog post?  Would like to go out next Tuesday.  Files are all here:  https://1drv.ms/f/s!AmMIW5Hxi0Rtgac1yTqJ9Q7XABQJCQ?e=eo8Zk7

There may be some changes/edits coming back from the micro:bit Foundation...

Thanks!
Jaq.

**Comment by Jaqster** [comment]
Hey @ganicke - not sure if you've started working on this, but hold tight.  There are a few changes coming down the pipe.  Will let you know when we've finalized changes.

**Comment by ganicke** [comment]
Ok, standing by...

**Comment by Jaqster** [comment]
Hi Galen.  Okay, should be good to start getting it prepped - the only thing that's missing is an updated gif of the Version History feature.  Should have that later today.  Let's plan on posting tomorrow.  Thanks!

**Comment by Jaqster** [comment]
@ganicke - the Version History demo is ready to go.  There's a .gif and .mp4 version of it in the OneDrive share.  Will plan to publish tomorrow (Friday).  Thanks!
