### ISSUE TITLE
Bluetooth services and characteristics missing from hex file

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt#1014]
The following simple application should result in the three specified Bluetooth services being included in the resultant binary:

![image](https://cloud.githubusercontent.com/assets/8341666/21572117/b07bc7f0-cecd-11e6-8e06-e7ceeda9cec6.png)

The corresponding hex file is attached in the zip file.

[microbit-Bitty-Logger-fie.zip](https://github.com/Microsoft/pxt/files/679180/microbit-Bitty-Logger-fie.zip)

After installing, pairing and resetting, examining the Bluetooth services on the micro:bit using nRF Connect we see we have:

![services-missing-magnet-and-temp](https://cloud.githubusercontent.com/assets/8341666/21572134/e322db94-cecd-11e6-8e5b-23af06d660de.png)

which includes the accelerometer service but does not include the magnetometer or temperature services.

Looking at the characteristics in the accelerometer service:

![accelerometer_service_missing_characteristic](https://cloud.githubusercontent.com/assets/8341666/21572147/fb630bb6-cecd-11e6-8d70-b2b8e2a5c2fe.png)

we can see that it only contains the Accelerometer Data characteristic. It is missing the Accelerometer Period characteristic.

See https://lancaster-university.github.io/microbit-docs/resources/bluetooth/bluetooth_profile.html 

This is may be due to insufficient memory being reserved via the gatt_table_size property in config.json

Recommended setting is:  
```
"gatt_table_size": "0x700" 
```

**Comment by pelikhan** [comment]
We already have this setting specified in the bluetooth project.

**Comment by pelikhan** [comment]
This is the yotta config generated by PXT:
```
{
  "config": {
    "microbit-dal": {
      "bluetooth": {
        "enabled": 1,
        "private_addressing": 0,
        "advertising_timeout": 0,
        "tx_power": 6,
        "dfu_service": 1,
        "event_service": 1,
        "device_info_service": 1,
        "eddystone_url": 1,
        "eddystone_uid": 1,
        "open": 0,
        "pairing_mode": 1,
        "whitelist": 1,
        "security_level": "SECURITY_MODE_ENCRYPTION_NO_MITM"
      }
    },
    "gatt_table_size": "0x700"
  },
  "dependencies": {
    "microbit": "lancaster-university/microbit#v2.0.0-rc7"
  }
}
```

**Comment by bluetooth-mdw** [comment]
gatt_table_size looks good. Something else must be pushing GATT memory use over the edge. No need for eddystone_url or eddystone_uid to be enabled unless the corresponding block is used. Maybe that's the issue. I can check with C/C++ tomorrow if I get time but that's all I can think of right now. It's easy to test though... use nRF Connect to discover the services on the micro:bit. Use the "Refresh Services" function to ensure you're looking at data from the micro:bit as opposed to cached GATT data from earlier access to the same micro:bit.

If we can't see the issue between us, we'll have to consult LU. Good be unrelated to config.... other changes in the DAL might be a factor (theoretically).

**Comment by bluetooth-mdw** [comment]
I think I see the problem. The gatt_table_size attribute is misplaced. It should be at the same level as the "bluetooth" object like this:

```
{
    "microbit-dal": {
      "bluetooth": {
        "enabled": 1,
        "private_addressing": 0,
        "advertising_timeout": 0,
        "tx_power": 6,
        "dfu_service": 1,
        "event_service": 1,
        "device_info_service": 1,
        "eddystone_url": 1,
        "eddystone_uid": 1,
        "open": 0,
        "pairing_mode": 1,
        "whitelist": 1,
        "security_level": "SECURITY_MODE_ENCRYPTION_NO_MITM"
    },
    "gatt_table_size": "0x700"
  },
  "dependencies": {
    "microbit": "lancaster-university/microbit#v2.0.0-rc7"
  }
}
```

I tested with the original config.json posted above and recreated the problem. I guess the effect is that the gatt_table_size property is ignored and the default of 0x300 applied instead.

**Comment by pelikhan** [comment]
The fix is in beta.

**Comment by bluetooth-mdw** [comment]
Tested and working. Thanks @pelikhan
