### ISSUE TITLE
block search shows unexpected behaviour

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1018]
search for led, see result.
access search again, return and search icon do not create a search again

![search](https://cloud.githubusercontent.com/assets/866122/21576890/faee7470-cf42-11e6-9c40-2ac08495bafe.gif)

**Comment by microsoftsam** [comment]
When you complete a search, a toolbox category with your search results appears (where you dragged the block from). When you select a block result, the category disappears (just like any other blockly category), and just like other categories to access the same search term, the Search category can be selected. 

One thing we can do here, is when the focus is back on the search box, we can show the search results flyout.

**Comment by OwenBrotherwood** [comment]
Example of expected behaviour: 
search for "le" : select and place in canvas "show leds" block and also note that the next element one may want is "clear screen" which also appeared in search results.
The search still contains "le", press search icon (or return) and the search result appears and one can select "clear screen" and place in canvas.

The issue is that pressing search icon (or return) does not show search result again and one has to delete "e" and then re-enter "e"

**Comment by microsoftsam** [comment]
Yep, you can click on the Search category to see the previous results in that scenario, but I agree clicking on the search box is more intuitive. 

https://github.com/Microsoft/pxt/pull/1019 should fix this
