### ISSUE TITLE
Change the order of Ok / Cancel buttons 

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#102]
This might seem minor but the standard is "Ok" is first (left) and "Cancel" is second (on right). All browsers follow that standard. All of our dialogs, have Cancel first (on the left). That could ask for trouble by going against what people are used to.

Places that I saw need switched:
- [x] Import Hex File (Open Project -> Import Hex)
- [x] More -> About
- [x] Confirmation Dialog for when delete project (More -> Project Settings -> Delete Project)
- [ ] Report Abuse (Embed -> Publish -> Go to published URL -> Report Abuse)
- [x] Remove a package (More-> Add Package; More -> Show Files; Go to files and delete Radio package)
- [x] User Settings dialog (Got it should be on left and Delete Acct on far right) -- (Sign in -> Click on button with person icon)

**Comment by mmoskal** [comment]
Note that there are different conventions on Windows and macOS. https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/

But given platform usage in schools we should probably go the Windows way.
