### ISSUE TITLE
wait until manifest is processed before removing spinner

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1021]
Given html5 rocks and manifest for cache, allow spinner to remain on screen until no-updates or updates installed.
Optional, information for the delay in updates installing with updates installing message (although this could be "too much information")

Background:
In the event of the a manifest change, and a class of 10 pupils, it is perceivable that some will have started their project work before updates installed and will have a restart.

Also, an optional updates available: install now latter etc may not be wished for
Pupils/teachers would have to deceide on something that is probably allways install now

**Comment by pelikhan** [comment]
Please clarify your request.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by OwenBrotherwood** [comment]
The spinner should remain on screen so the user does not start working at the risk of having to restart their work.
The following two events may be the only two events that are needed to act on before allowing the user access.

// Fired after the first download of the manifest.
appCache.addEventListener('noupdate', handleCacheEvent, false);

// Fired when the manifest resources have been newly redownloaded.
appCache.addEventListener('updateready', handleCacheEvent, false);

**Comment by pelikhan** [comment]
Work will not be lost in the event of an update post-beta.

**Comment by OwenBrotherwood** [comment]
I think this was the html5 rocks I used as information in the early 2010's
https://www.html5rocks.com/en/tutorials/appcache/beginner/

Beginner was really the word for me :)
