### ISSUE TITLE
I'd like to be able to choose how the docs are rendered (blocks/JS)

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1024]
The current 'reference' docs are great but I'd like to be able to explicitly see them in javascript or blocks - otherwise it isn't so clear that the JS and the blocks use exactly the same API.

Could we have a toggle or slider at the top of the docs page please?

**Comment by jaustin** [comment]
Any progress on this? It doesn't look like the docs render in the same way as the editor these days?

With the new docs layout, a tab like in the editor to switch mode at the top of the page would be really nice.

**Comment by abchatra** [comment]
You can toggle and see javascript with a button on the editor. Fixed
