### ISSUE TITLE
on Start and 'Forever' seem more natural at the top of the blocks list

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1025]
Logically, 'on start' feels like it belongs at the top of the 'Basic' list (at least considering top-to-bottom left-to-right reading systems).

Instead it's near the bottom.

![image](https://cloud.githubusercontent.com/assets/147113/21616942/9caade12-d1db-11e6-91f3-f82e12d27d8b.png)

Could we sort the 'Basic' blocks differently please?
I think to me the most logical order is
On Start
Forever
Show LEDs
Show Number
Show String
Clear Screen
Pause

**Comment by jaustin** [comment]
Given that the 'On Start' block is always present, I'm comfortable with the current order in beta. Happy for you to close @abchatra if you'd like to...

**Comment by abchatra** [comment]
Thanks
