### ISSUE TITLE
sidebar in docs for quick navigation

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1026]
Many documentation systems have a sidebar to help users navigate around the documentation, as well as helping understand hierarchy:
For example, the mbed API documentation:
![image](https://cloud.githubusercontent.com/assets/147113/21617062/434c57f0-d1dc-11e6-8f9c-200494775254.png)

This nav helps anchor people in the docs.

Could pxt docs page generate similar sidebar?

**Comment by microsoftsam** [comment]
Fixed with new TOC in docs.
