### ISSUE TITLE
Versioning of docs

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1027]
With versioning of APIs it is also important to be able to version the documentation associated with particular APIs. 

Currently despite there being both pxt.microbit.org/beta and pxt.microbit.org there's only one source for docs.

There are two typical implementations for this, one is including a 'version' dropdown somewhere in the documentation site itself, as in the bottom-left of this image:
![image](https://cloud.githubusercontent.com/assets/147113/21617122/98075114-d1dc-11e6-8bf8-cb6da9840f6f.png)

The other would be to make non-default docs versions only available via the 'Help' menu in a different editor version, and use the URL to get the different docs version.

**Comment by abchatra** [comment]
Docs are versioned as per GitHub commits.
