### ISSUE TITLE
Minor issue - the opaque level of the block flyout needs to be changed as blocks behind show through too much

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#103]
This isn't major but I have stumbled on it a bit when I had a project that had a lot of blocks. If you have a lot of blocks then click on the block list, the fly out comes out and the blocks to choose from aren't that more visible than the blocks already on the canvas.

Repro:
* Open project with a lot of blocks
* Open "Loops" 
** Notice the While Loop - "true" almost looks like the underlying blocks already on canvas
** Those underlying blocks need to be more "invisible" or something

**Comment by pelikhan** [comment]
This is the default rendering options of Blockly. Won't fix.
