### ISSUE TITLE
Saving file failed, on Lumia 950XL

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1035]
microbit.org-ticket: 593

I'm using the pxt.microbit.org block editor.  If I save the file it says "saving file failed" or if I click the download button it also says "saving file failed" in a small red box on the center of the screen.  I can download all kinds of other files on my phone; pdfs, word docs, zip files from other websites.  

I think if the download link was normal it would allow me to download it to a location I specify, just as with other files, it just needs to not have a java-script error or whatever it is doing.  I have a USB-c to USB-a adaptor and my phone, a Lumia 950XL, sees the micro:bit as a drive so I should be able to use the file explorer to copy the hex file to it

![wp_ss_20161228_0005](https://cloud.githubusercontent.com/assets/4086785/21676331/21ef7342-d32d-11e6-9eb6-139b070d89cc.png)

**Comment by whaleygeek** [comment]
Has anyone been able to reproduce this issue yet, do you know? Thanks!

**Comment by whaleygeek** [comment]
Hi, Im being chased for a resolution to this by the customer who uses a windows phone - is there any progress on this ticket do you know?

**Comment by DavidWhaleMEF** [comment]
Thanks for bumping to P2.

Any thoughts about how this one might be resolved yet??

**Comment by tballmsft** [comment]
We don't support windows phone, @whaleygeek.

**Comment by DavidWhaleMEF** [comment]
Thanks @tballmsft - oh dear, ok!

**Comment by microsoftsam** [comment]
Closing this as won't fix.
