### ISSUE TITLE
centering of blocky items 

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1036]
The bottom right "cross hair" does not seem to center blocky items.
I would expect that in some way, the view was change to center the items such that +/- icons could be used without further use of scroll bars.

![target](https://cloud.githubusercontent.com/assets/866122/21687662/7a5e86fc-d36a-11e6-8620-48b2c5fd0619.gif)

**Comment by microsoftsam** [comment]
Looks like a Blockly bug.

**Comment by OwenBrotherwood** [comment]
I there an upstream bug to track?

**Comment by samelhusseini** [comment]
This is no longer relevant as we removed that feature by removing the Blockly zoom buttons :)

**Comment by microsoftsam** [comment]
This is no longer relevant as we've removed that feature when we removed the Blockly zoom buttons, in favour for the editor toolbar.
