### ISSUE TITLE
jack icon doesn't show in Firefox/OS X

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1039]
On both /beta and pxt.microbit.org at the moment, I don't get a jack icon when using the audio blocks

**Comment by jaustin** [comment]
For the record, here's what I see 
<img width="309" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21701163/06b48094-d39c-11e6-9695-bf6fde4dade7.png">

**Comment by abchatra** [comment]
I can repro this.
