### ISSUE TITLE
Math block section has duplicate blocks for integer

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#104]
In the "Math" section, there is a duplicate block for integer. The only difference is that one integer defaults to 0 and one defaults to 1. Not that big of deal to have duplicate blocks.

Repro:
* New Project
* Select Math blocks
** Notice near the bottom below "Absolute" there is an integer block for 0 and one for 1.

**Comment by thomasdenney** [comment]
[This pull request](https://github.com/Microsoft/pxt/pull/116) resolves the issue.
