### ISSUE TITLE
Confusion about Arrays (documentation mismatch)

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1040]
Microbit.org-ticket: 647

I am confused about what array methods I can use with the PXT editor. The pop() method appears on the pop up box when I type 'array.', however if I try to use it I get an error saying 'helpers.arrayPop not found'. Also I can use array.length as the index for a for loop, however if I try to set array.length = 0 (e.g. to empty an array) I get a compilation error.

Note the docs here about Array do not detail these extra methods or how to use them:

https://pxt.microbit.org/js/types (under heading Array, the docs seem pretty terse compared to the additional features available in the code completion)

**Comment by abchatra** [comment]
_I try to use it I get an error saying 'helpers.arrayPop not found'_ this bug is fixed in beta. Pop and various array methods are available now.

We don't have a way to set the array.length yet. I will look into this. 

Documentation definitely requires a overhaul. I will keep this issue open for the documentation.

**Comment by whaleygeek** [comment]
@abchatra Just checking, is there any progress on the docs on this yet, the customer has been chasing me for a resolution on this, thanks!

**Comment by whaleygeek** [comment]
P.S. @abchatra if you could briefly describe in this ticket how it is supposed to work, that would be a good first step to us helping the customer move forward on this issue. I appreciate it takes time to update docs, but a quick 'brain dump' in this ticket would be really helpful, in absence of updated docs, as the customer could then progress with developing their resources. Thanks!

**Comment by abchatra** [comment]
@whaleygeek following issue reported by the customer is fixed and you can ask him to try it out.
-however if I try to use it I get an error saying 'helpers.arrayPop not found'_

What is not fixed: 
- Docs 
-  Array length set: array.length = 0

I don't know if he is blocked on the above. Can you ask him? Original issue was about arrapPop.

**Comment by DavidWhaleMEF** [comment]
Hi, are the docs fixed for this one now @abchatra ?

I have asked the customer but have not heard back.

**Comment by abchatra** [comment]
@DavidWhaleMEF Docs are not complete yet (it doesn't say the list of methods supported on arrays). We are in the process of the defining a proper subset of typescript. I will update the docs once that is done.

**Comment by abchatra** [comment]
Also this shouldn't block the customer in any way though

**Comment by ganicke** [comment]
Documentation support for **Arrays** added in #2777, #2781, and #2841.
