### ISSUE TITLE
tutorial issues

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1041]
- [ ] when the markdown fails to load, the UI is stuck on loading screen.

To repro, simply run the tutorial using ``http://localhost:3232/index.html?nolocalhost=1``

- [x] ``blocks`` macro should not be rendered with buttons
- [x] tutorial projects should be temporary and destroyed as needed
- [x] ``on start`` overlays with toolbox
- [x] step numbering list are too large and won't scale for longer tutorials. Use dots + tooltip and expand number on selected step only.
- [x] move tutorial to its own module.

**Comment by microsoftsam** [comment]
Transferring markdown issue to its own bug: #1169
