### ISSUE TITLE
toolbox issues

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1042]
- [x] flyout is too transparent and it gets confusing when blocks are under
- [x] search should be hidden in icon mode
- [x] advanced should use ... icon instead of gearwheel
- [x] category name should be used in tooltip in collapsed mode

**Comment by microsoftsam** [comment]
Can't do tooltip since I only have access to editing the icon class name in the blockly tree, but I found a way to only show the labels on hover, making it look like a tooltip.
