### ISSUE TITLE
Unable to paste text into PXT javascript on iPhone/Safari

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1047]
microbit.org-ticket: 651

When using the Pxt editor in JavaScript mode on an iPhone using the Safari browser, it's not possible to paste text into the JavaScript editor window. This means it's impossible to import code from anywhere else unless you retype it by hand

**Comment by whaleygeek** [comment]
Note: Is this a limitation of the Safari browser on iPhone (not allowing text to be pasted into a window), or is it due to how the editor surfaces the edit window in that browser. i.e. is this likely to be fixable by a code change in PXT, or is this a limitation of how the Safari browser works on the iPhone, I'm not sure?

**Comment by pelikhan** [comment]
Our rich editor does not officially support mobile coding yet. Authoring JavaScript on mobile is not generally supported. Even if it was, typing JavaScript on a softkeyboard is a terrible experience not suitable for beginners.

**Comment by whaleygeek** [comment]
Some additional feedback from the customer, that they asked to be passed on to the dev team:


 Thanks for the reply to my bug report regarding copy and paste not working properly on iOS devices.

I'm afraid that in my view this limitation is a significant drawback of the software and not a mere long-term feature request. It's also a problem easily fixed.

 The issue:

 I agree that typing on soft keyboards is not always fun. But that's missing the point.

The BBC micro:bit is targeted at children. Kids today live around mobile devices - phones and tablets. They view personal computers as antiquated office machines. Failing to support the expectations of this youthful audience is, in my view, an error.

Many people code on iPads with Bluetooth keyboards, and they should be fully supported as well. (They could use command-C and V but may not know this)

 Resolving the problem:

If the custom popup (help, save, run, etc) were to be disabled on mobile devices, and its functions moved to an icon, copy and paste using the OS-supplied tools would be possible. This simple expedient would make Javascript editing possible on iOS devices.

Right now the infrastructure to code in JavaScript is there, but you just can't get code in or out easily.

Please reconsider this suggestion. Thank you!

**Comment by abchatra** [comment]
This is fixed.
