### ISSUE TITLE
An error in the .ts code pops an error that doesn't fit in the left pane 

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#105]
If you have an error in your .ts script, the error is not showing completely as the error message doesn't fit in the left pane. It might be a left pane size issue as it is covering up some of the files from the "Show Files"

Repro:
* Make sure "More -> Show Files" is on
* Change .ts file to have incorrect syntax
** Notice - error message doesn't fully show unless put focus on it
** Notice - other parts of left pane are covered

![errormsgoverlap](https://cloud.githubusercontent.com/assets/3943962/16503357/8e92d502-3ec7-11e6-8800-4c1115e9fbfa.jpg)

**Comment by thomasdenney** [comment]
The same bug can appear if you have anything in the left pane that doesn't fit, for example if you use the serial library to log a long string:

![sizingissue](https://cloud.githubusercontent.com/assets/20356546/16805285/4d9b43f0-4907-11e6-8760-672be5dcf0c6.PNG)

As shown, this over sizes the simulator, and also has the effect that you can't drag blocks around.

**Comment by microsoftsam** [comment]
Fixed by issue #176
