### ISSUE TITLE
crash on OOB array access

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#1054]
The following program crashes on microbit and in the simulator, even though it's perfectly legal JavaScript:

```
let arr: number[] =[]
for (let i = 0; i < 32; ++i) {
    if (!arr[i])
        arr[i] = i
}
```

cc @pelikhan @tballmsft - comments?

Related issue: #1053

**Comment by abchatra** [comment]
Adding default values to arrays should solve these issues.

**Comment by abchatra** [comment]
Also a[I] access above is beyond the length of the array. Do we want to support default values for these as well?

**Comment by pelikhan** [comment]
Yes we should have a runtime that is resilient to invalid input.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mmoskal** [comment]
I think the primary goal should be to stay true to JavaScript semantics, which also happens to be resilient to invalid input.

Of course we're still gonna crash (OOM) if someone does `arr[100000] = 1`...

**Comment by abchatra** [comment]
Fixed
