### ISSUE TITLE
Neopixel package broken

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#1059]
Not sure if it's the OO stuff, but the following script breaks the simulator with the neopixel package: 

```
let item: neopixel.Strip = null
basic.forever(() => {
    item.rotate(1)
    item.show()
})
item = neopixel.create(DigitalPin.P0, 24, NeoPixelMode.RGB)
item.showRainbow(1, 360)
```

**Comment by pelikhan** [comment]
This is a compiler issue related to capturing variables.

**Comment by abchatra** [comment]
This is not a compiler issue. If you see the code, _item_ is initialized after the forever loop. Its value is _null_ at the point of forever loop. This is regression from on start work.

![image](https://cloud.githubusercontent.com/assets/6107272/21830743/b92a36dc-d753-11e6-909c-758f560c8986.png)

While compiling to typescript, on start code should come first before the forever loop.

**Comment by pelikhan** [comment]
Forever is considered an event. It always gets executed before "on start" - so this might be a forever issue.

**Comment by abchatra** [comment]
setPin which is invoked during neopixel.create has a pause in it, which transfers the control back to the basic.forever
```js
        setPin(pin: DigitalPin): void {
            this.pin = pin;
            pins.digitalWritePin(this.pin, 0)
            basic.pause(50)
        }
```
@pelikhan do you know if this pause is required? If required, one option is to move basic.forever at the end of the startup code as it was before.

**Comment by pelikhan** [comment]
I do need a pause in"show" but I am not sure about setpin. Will test without it.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt-neopixel/commit/04255f876e4e67909dcc8dcf5556854500d01311
