### ISSUE TITLE
canvas size changes when explore files in JavaScript

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1062]
![target](https://cloud.githubusercontent.com/assets/866122/21790145/7d448d76-d6da-11e6-8e14-a05cc763ef1d.gif)

**Comment by pelikhan** [comment]
Opening readme.md also opens the preview pane. The file is empty so the preview pane is empty too. Reseting has no effect on that.

I guess the pane should close when you leave readme.md.

**Comment by OwenBrotherwood** [comment]
@pelikhan The canvas remains affected after reviewing readme and other javascript files such as pxt.json and also when returning to blocks: it's a bug

![image](https://cloud.githubusercontent.com/assets/866122/21796668/81fe2f72-d70a-11e6-843a-49be41785511.png)

**Comment by pelikhan** [comment]
Click on the collapse button in the upper right of that view to collapse it.
