### ISSUE TITLE
toolbox issues

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1064]
- [x]  no more download button on desktop collapsed
- [x] not enough space for collapse expand. Start/stop can be used instead.
![image](https://cloud.githubusercontent.com/assets/4175913/21794956/ad1da590-d6b3-11e6-8c6e-ccec95269578.png)
- [ ] zoom icons in mobile should be removed in favor on pinch gesture.
- [ ] breadboard mode needs to be disabled in tablet mode
![image](https://cloud.githubusercontent.com/assets/4175913/21795063/715a5822-d6b4-11e6-9f2c-5d502b0d0acf.png)

**Comment by jaustin** [comment]
Not sure if you want issues added here?
[] no way to restart the simulator easily now that 'stop' hides it.

^ This is most prevalent when you have a program that does something and then completes. You might want to restart it, but that's onerous now.
