### ISSUE TITLE
PXT Micro:bit, serial, JS

### ISSUE THREAD

**Issue by githubhero** [Microsoft/pxt#1066]
Hi, I have two questions, no issues:

1. I could not find it in the docs, but in the PXT Microbit editor I found an interesting event handler (`onLineReceived`): does it currently work? I tried but I could not get it working;

2. How is the serial communication supposed to work? I try to explain better: I write text to the serial and I read it in PXT-Microbit in a `while(true)` loop. Is this the right way to read from the serial?

Thanks.

**Comment by pelikhan** [comment]
That event is not wired up yet. Shouldn't be too hard to add.

Yes. You can use serial.readUntil to block the fiber until a specific character is matched in the serial stream.

**Comment by githubhero** [comment]
@pelikhan First of all thanks for your kind reply. 

A further question (sorry for abusing of your time): let's suppose that event is wired up, added and working. Should I still use `while(true)`? It's a crucial thing for me, because the loop is causing me lots of issues and if _onLineReceived_ would work the way I'm supposing it should, I could code anything in a more efficient way.

**Comment by pelikhan** [comment]
For now, simply do

while(true) {
   let s = serial.readUntil(“,”)   // blocking until data arrives
}

**Comment by githubhero** [comment]
@pelikhan This is exactly what I was doing before posting. I hope you can add the event handler feature soon. Keep up the good work   :-)

**Comment by pelikhan** [comment]
Please try again in beta using https://pxt.microbit.org/reference/serial/on-data-received

**Comment by githubhero** [comment]
@pelikhan: hi, at the moment, when I paste this code at pxt.microbit.org:

```
serial.onDataReceived(serial.delimiters(Delimiters.Comma), () => {
    basic.showString(serial.readUntil(serial.delimiters(Delimiters.Comma)))
})
```

I receive:

_Property 'onDataReceived' does not exist on type 'typeof serial'._

**Comment by pelikhan** [comment]
Forgot to mention, please try https://pxt.microbit.org/beta .

**Comment by githubhero** [comment]
@pelikhan It works, thanks   :-)
