### ISSUE TITLE
Feedback for users trying to delete 'On Start' block

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1067]
When a user tries to delete the 'on start' block, they (rightly) can't do this.

It would be better if there was some feedback to them about why - Peli suggested either showing the trash with a cross on it, I wondered about a non-modal dialog or message at the bottom of the editor.

Without a bit of a warning, it is easy to think that the blocks not being deleted is a bug

**Comment by pelikhan** [comment]
Detect that ON_START block is being dragged and do not show trash in toolbar.

**Comment by riknoll** [comment]
@pelikhan can this issue be closed now that onStart is deletable?
