### ISSUE TITLE
Could the simulator LEDs glow a bit please?

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1069]
We've found that when making images of the micro:bit, it looks nice to make the LEDs glow

<img width="462" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21815856/fa7ffc64-d755-11e6-865a-3d535a5cac33.png">

Could we have a similar effect for the LEDs on the simulator, please?

(I wondered if this might be a nice introductory task for a community member looking to do a tractable first task and get to grips with the codebase.)

**Comment by microsoftsam** [comment]
Tried adding a glow to the simulator, but it doesn't look very good. Almost looks blurred more than glowed: 

<img width="381" alt="screen_shot_2017-01-10_at_11 05 50_pm 1" src="https://cloud.githubusercontent.com/assets/16690124/21872126/a5f6d066-d81b-11e6-87c8-ab8b1b75061a.png">

**Comment by jaustin** [comment]
Doesn't have to be such a simple blur though?
https://jsfiddle.net/6gu43e3v/
<img width="56" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21873209/fd5ac8c8-d864-11e6-9671-df47fe1944f4.png">

**Comment by pelikhan** [comment]
People can reopen issues if they feel it needs to be addressed or, better, provide a PR. The LEDs are svg elements and css filters don't work well with them.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment]
Thanks, that last bit of information about SVG vs CSS is really useful to
log.

**Comment by microsoftsam** [comment]
@jaustin thoughts on this glow?
https://jsfiddle.net/hmbg4t1h/
