### ISSUE TITLE
Making a >2-frame 'big image' in JS and then switching back to blocks destroys the image

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1073]
Steps to reproduce
http://pxt.microbit.org/beta
1) Add a 'forever' block, with a 'display image' block inside
2) add a 'Create big image' block instead of 'item'

Your script will look like this:
<img width="733" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21830374/25663392-d794-11e6-943a-10c384e49d98.png">

3) Switch to JS
4) Add a 'frame' to the image (easiest using Monaco vertical block select, alt+shift on OS X)
5) Modify the code to show the image at this offset
Verify that this does work on the simulator
<img width="1295" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21830446/a70d8918-d794-11e6-91fd-46488323f88f.png">
6) Switch back to blocks
7) Note that the 'big image' block now renders a different pattern
<img width="754" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21830466/c579f468-d794-11e6-8c6d-1a75bba307d7.png">
8) Switch back to JS, notice that the code is different too.

So, this violates the rule that switching between JS and blocks should never lose work.

**Comment by jaustin** [comment]
I'm wondering again if we can have some 'belt and braces' stuff to ensure we're not clobbering people's JS/blocks when we switch? Given that (I think) both the blocks and JS are kept, can't we do a compare at the right point in the conversion to be sure this is 'all okay'

For example
- User clicks Blocks
- Autoformat current JS, refer to this as 'prev'
- Convert prev to blocks (including merging back in deactivated blocks from the blocks file).
- Convert the resultant blocks back to JS, call this 'conv'
- compare 'conv' and 'prev'. If they're not the same, something's wrong.

Does the JS--> blocks transform legitimately lose any information? Because if so that would kill the above plan.

**Comment by abchatra** [comment]
@pelikhan  Fixed?

**Comment by pelikhan** [comment]
We need a negative conversion test.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Add the same test here: https://github.com/Microsoft/pxt/tree/master/tests/decompile-test
