### ISSUE TITLE
Monaco Block/Column selection is awesome for making images, but hard to find

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1075]
When making images, the ability to hold alt+shift and select columns (including multiple columns) makes duplicating frames in large images really easy. However, it's hard to discover unless you know about the feature already.

Are there ways to hint to users about the possible useful features when their cursor is inside certain functions? 

Are there other ways to expose some of the Monaco block/column select behaviour?

Here's an example of Monaco being awesome: (holding ctrl+alt while dragging, then just typing '.' or '#')
![microbit monaco columns](https://cloud.githubusercontent.com/assets/147113/21830881/d2909014-d797-11e6-8b11-c63c37008e1f.gif)

**Comment by pelikhan** [comment]
We used to automatically fill the pattern when we ran our own code pretification algo. We've gone away from that. Teaching the keyboard shortcut is IMO the way to go.
