### ISSUE TITLE
High CPU usage in Firefox when PXT is foreground tab

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1076]
I find CPU usage in Firefox is really high when the simulator is enabled. Even for a simple program (say, this, which makes it worse by bringing a second micro:bit in even though the radio is never 'used') 
<img width="281" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21827737/d63ef3c6-d784-11e6-9f9a-0339ef826bc1.png">

It does seem to intelligently know when it's no longer the frontmost tab in Firefox, and calm down a bit, but it doesn't detect when Firefox is no longer the focussed window.

For example, I get Firefox Web Content eating 80-90% of a core when I have PXT visible or the frontmost tab, and ~10% otherwise. Chrome seems to be better.

**Comment by pelikhan** [comment]
There is an API to be notified when the browser switches between tab, we use that to turn off the simulator. Unfortunately, we don't get notication when the process looses focus. Chrome is better at shutting things down.

**Comment by abchatra** [comment]
Can't repro. Seems to be fixed
