### ISSUE TITLE
beta clobbered script when loading it

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1106]
I just loaded a script (the hex attached, I think - I loaded it from my local projects and now it's clobbered so I can't be sure that this is the exact version that I loaded)

When it first loaded, the simulator ran but there were no visible blocks
<img width="1436" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21929542/f0dcd648-d988-11e6-82d4-b9b4934d7d7c.png">

I tried panning around the screen but couldn't see the blocks.

When I switched back to JS, there was some code (but not all the code!) and when I switched back to blocks again, I got the following
<img width="733" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21929562/20f0784e-d989-11e6-95ab-e64d6399fcdc.png">

This therefore looks like a side effect of importing an older PXT script and the code for fixing #1068.

I *think* this might be because the script got loaded in blocks mode (I loaded it from my 'Projects') but blocks mode is no longer able to display this script?

**Comment by jaustin** [comment]
[microbit-Radio-bridge (20).hex.zip](https://github.com/Microsoft/pxt/files/704226/microbit-Radio-bridge.20.hex.zip)

**Comment by jaustin** [comment]
Reliable way to reproduce this:
go to http://pxt.microbit.org
Drop the hex file on, view it in blocks
visit http://pxt.microbit.org/beta
simply loading the beta will destroy the script (as far as I can see?) 
When revisiting pxt.microbit.org the script is now much smaller

**Comment by pelikhan** [comment]
This fix makes sure that if we fail to load the blocks (in this case because forever cannot be attached anymore), then we open the javascript untouched.

https://github.com/Microsoft/pxt/commit/ee7ace674e42bc63691ec262187740969f0c0a25
