### ISSUE TITLE
Script that could previously be shown in blocks can no longer be

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1107]
[microbit-Radio-bridge (20).hex.zip](https://github.com/Microsoft/pxt/files/704227/microbit-Radio-bridge.20.hex.zip)
in pxt.microbit.org I can import this script and display it in blocks.

In pxt.microbit.org/beta this script can only be shown in javascript. It isn't possible to switch back to blocks once importing it.

Furthermore, as per #1106 if you leave the script in blocks mode on pxt.microbit.org and then try beta, it will destroy the script.

**Comment by riknoll** [comment]
Looking at the example code, I believe the issue is that you have a forever loop nested in a `control.inBackground()` handler. We no longer support that in the blocks as of https://github.com/Microsoft/pxt/pull/925
