### ISSUE TITLE
two-up simulator overflows the box, hiding stop/restart buttons

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1108]
When you add a radio command and there's a second microbit visible in the simulator, by default on a 1440x900 display with a fullscreen browser, the simulator overflows the space adding a scrollbar:
<img width="1435" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21929879/05c5c13a-d98b-11e6-8928-641803896100.png">

This has two downsides
1) it looks a bit clumsy, especially on Chrome where the bottom of the second microbit is quite hidden
2) The stop/reload buttons slide off the bottom of the screen, making them very undiscoverable.

The good thing is that when I shrink the window slightly in the horizontal direction, the simulators rescale and can both be seen alongside the buttons:
<img width="1198" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21929908/25927274-d98b-11e6-9f23-7b6b89ad1fbb.png">

It would be desireable for the overflow in the first case to be detected and the simulator scale to adjust accordingly.

**Comment by pelikhan** [comment]
Is your screen resolution common in schools?

**Comment by jaustin** [comment]
I think this is less about any particular screen resolution and more about the fact that it can and does overflow. 
As I drop my resolution to be closer to common resolutions I still see the issue and it gets worse

<img width="1271" alt="1280x800" src="https://cloud.githubusercontent.com/assets/147113/21936933/0a80d378-d9ad-11e6-924b-8639b8e5267c.png">

Again, with that resolution, just shrinking the window horizontally fixes it.

**Comment by abchatra** [comment]
I do see a scroll bar when I try to use this. You don't see one?

**Comment by jaustin** [comment]
Yes, I have a scroll bar. The issue is that the trackpad scroll, IE 'two
finger scroll" works in the vertical but not the horizontal direction.

**Comment by abchatra** [comment]
Wont' fix
