### ISSUE TITLE
Vertical scroll works in the blocks canvas but horizontal does not

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1109]
On Chrome/Firefox on OS X, using beta.
When placing the cursor on the blocks canvas, scrolling using the mouse (two-finger on touchpad):
Vertical scrolling works
Horizontal scrolling does not

The horizontal scroll bars do work, but it seems strange for the mouse scroll to work in one direction and not the other?

**Comment by pelikhan** [comment]
Please include screengrabs.

**Comment by pelikhan** [comment]
Screencasts work wonderfully.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment]
Okay, here you go!
Here's the behaviour on PXT
![scrolling horizontally](https://cloud.githubusercontent.com/assets/147113/21938343/dc2fccee-d9b2-11e6-87f4-4b25afb5ae24.gif)
(the small up/down movements when scrolling horizontally are the slight vertical motion my fingers make)

Here's a video to prove I can/my browser can do this
![scrolling horizontally npm](https://cloud.githubusercontent.com/assets/147113/21938347/e1fff536-d9b2-11e6-95d1-8952e026c7fd.gif)

**Comment by jaustin** [comment]
Also, I think it's worth adding that the main reason I noticed this is that Chrome often interprets my attempts to scroll sideways as a 'back' gesture and I end up going back! In fact, perhaps because there is no horizontal scroll, I actually end up with my gentle scroll up being considered 'back' too.

**Comment by abchatra** [comment]
@jaustin Does this still repro?
