### ISSUE TITLE
Feedback for users trying to return to blocks when that's not possible

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1110]
The following message 
<img width="919" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21931415/307e00d8-d993-11e6-8de7-7e44a367bb5f.png">

Can be somewhat frustrating for someone trying to return their script from JS to blocks.

Instead, it would be good if the dialogue did some of the following:

- Presented information about things that can't be translated back into blocks, and suggestions about how to replace common non-translatable things with translatable ones
- Highlight parts of the script that are causing the translation problem, so that if the user wants to transfer back, they can
- Let the user compare what the javascript that the converstion would generate looked like with their own javascript, side-by-side, so they could choose with confidence whether the things they care about will still be in the program.

**Comment by jaustin** [comment]
I guess another point to make here is that this is current presented somewhat as an 'error'
"Oops, there's a problem". In many cases it's actually "Your JavaScript code can't be expressed as blocks anymore" ... 

IE in many cases it's a feature not a bug - we've helped the user migrate beyond simple programs :)

**Comment by smartyw** [comment]
![image](https://user-images.githubusercontent.com/1387793/34320680-8c3040c6-e7f7-11e7-934a-04a9d3dd03f9.png)

+1

It's "tricky" trying to figure out what is causing problems sometimes.... a process of elimination generally works but some kind of log with the raw, potentially horrible error message(s) in it would be great. I'm actually converting from C/C++ to JavaScript, hence the occasional problem.
