### ISSUE TITLE
Variable definition proliferation during blocks/JS switch (beta)

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1111]
When switching between blocks/JS on beta and editing lines near variables, the block definitions of the variables proliferate each switch:

![variable proliferation](https://cloud.githubusercontent.com/assets/147113/21933482/80348296-d99d-11e6-94fa-71ac2281a497.gif)

I don't think this is the expected behaviour - it certainly makes sharing complex programs in blocks complicated if you want people to be able to tinker with the JS

**Comment by jaustin** [comment]
II think this one's more bug than enhancement? To me it's a ~P2, as it can mean programs get really large once you have a few variables and it's also confusing - your code changes 'under your feet' (IE you didn't deliberately change it, but it got changed)

**Comment by HelenFoster** [comment]
Looks like this is fixed now.
