### ISSUE TITLE
Alignment of elements in bottom toolbar

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1112]
The elements in the bottom toolbar seem oddly aligned
<img width="826" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21934012/b52d1b1e-d99f-11e6-89b9-966dadef5148.png">

The download button seems to be vertically centred, but that other buttons seem to be nearer the top.
In general, I'd be happy with this bar being flatter/shorter than it is with a slightly smaller (flatter) download button.

**Comment by microsoftsam** [comment]
The second option works, but it makes the download button smaller, which I think currently is a differentiator and makes it stand out as the most important button there.

**Comment by jaustin** [comment]
@microsoftsam any chance you can share a screenshot? Isn't the fact that it's still much longer also quite differentiating?

**Comment by pelikhan** [comment]
We haven't seen anyone complaining about this.
