### ISSUE TITLE
Pinch gesture not working on mobile

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1113]
With the beta, the pinch gesture isn't usable on mobile. 

#1064  had a placeholder for this, but that's now closed, so entering an issue to track.

(iOS 10.2, Safari)

**Comment by pelikhan** [comment]
Pinch gesture on what? Blockly does not support that feature, please post this feature request upstream.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment]
Yea, I mean blockly. I assumed you (pxt) already saw the event loop even for things that went on in the blockly canvas. Currently you can pinch on the toolbox and it zooms the whole UI.

I'm happy to raise this upstream, but it might be more useful for whoever tracks blockly in PXT to raise it?

**Comment by abchatra** [comment]
This is blockly issue.
