### ISSUE TITLE
Simulator obscures download button and zoom buttons on iOS 10 iPhone SE

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1114]
On iPhone SE (probably the same on iPhone 5), with the new toolbox the simulator obscures the download button when it is present.
![image](https://cloud.githubusercontent.com/assets/147113/21934813/cc15339a-d9a2-11e6-9295-0fa43ae17a5f.png)

I think it'd be preferable to use the compact download button that's shown then the toolbar is collapsed, and put it in the bottom right hand corner?

On other possible mitigation would be to start the simulator paused so that the button isn't obscured from the beginning, this means people will also see the whole button before it is partially obscured.

**Comment by abchatra** [comment]
There is a way to minimize the simulator.

**Comment by abchatra** [comment]
Fixed
