### ISSUE TITLE
iOS: Hide Safari Chrome/UI when possible

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1116]
While it seems it's not trivial to hide the Safari chrome/browser UI when the user visits pxt.microbit.org, Apple does publicise ways to hide the UI when the page is loaded from a homescreen shortcut.

https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

It seems at the moment that PXT will always show chrome even when loaded from the home screen. Could some of these optimisations be made to have better iOS experience?

**Comment by microsoftsam** [comment]
This has been fixed.
