### ISSUE TITLE
Sometimes see half a window after delete project

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1117]
sitever: pxt.microbit.org version: 0.6.36
platform: mac OSX 10.10.5
browser: chrome Version 55.0.2883.95 (64-bit)

I pressed on DELETE PROJECT then this is what the window looked like. I had to restart the browser to recover a working window of the correct size.

![screen shot 2017-01-13 at 15 33 52](https://cloud.githubusercontent.com/assets/4086785/21935515/bf6e9732-d9a5-11e6-9926-48744aa2f9bf.png)

**Comment by pelikhan** [comment]
Please that this behavior is still present in beta as we have made lots of changes in the UI.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Likely fixed in Beta

**Comment by pelikhan** [comment]
Reopen if it reoccurs.
