### ISSUE TITLE
Third party packages not shown in add package.

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#1124]
Server returning 502 error. 

![screen shot 2017-01-13 at 2 40 26 pm](https://cloud.githubusercontent.com/assets/16690124/21948414/f8895f4e-d99f-11e6-84a5-af238f5dcabd.png)

**Comment by abchatra** [comment]
Adding neopixel package gives network error.

**Comment by pelikhan** [comment]
This is a backend issue, not blocking for a client release.

**Comment by abchatra** [comment]
Curious @mmoskal what was the cause?

**Comment by mmoskal** [comment]
Bug in the server. It was caching the error response forever
