### ISSUE TITLE
Open. hex file dialog (performance issue)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1127]
On edge, open a hex file via the "Open hex file" dialog:
* clicking on the "browse" button to open a file dialog
* it takes 3 seconds for the file dialog to appear

**Comment by pelikhan** [comment]
Seems like an issue with your computer. The Open File Dialog is a native component. Does it repro in other applications.
(screen capture of such issue helps)

**Comment by abchatra** [comment]
I can easily repro on edge

**Comment by abchatra** [comment]
I don't repro this anymore.
