### ISSUE TITLE
Edge - Zoom

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1129]
After zooming in/out, can't get to JavaScript.  Repro: Click zoom in/out button on toolbar, click JavaScript toggle.

**Comment by abchatra** [comment]
Unable to go to typescript. Blocking bug in beta

**Comment by pelikhan** [comment]
Screencast?

**Comment by pelikhan** [comment]
Is this a zooming issue? I've fixed the bug to return to javascript.

**Comment by abchatra** [comment]
It is the same issue. not a zooming issue.
