### ISSUE TITLE
load a hex file with a nice name, get Untitled

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1130]
1. Create a blocks program and change its name to "fun with with buttons" in the UI.
2. click save button
3. reset 
4. load the file "microbit-fun-with-buttons.hex"
5. Notice that the name is "Untitled".

**Comment by pelikhan** [comment]
Specify browser/OS.

**Comment by microsoftsam** [comment]
Save doesn't save the project before downloading. 
Fixed in ec25698c6425274f1ec5cae83e0198b8a3af05f9
