### ISSUE TITLE
Edge - Download dialog

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1133]
Download instructions on Edge should be "Save As" to save directly onto micro:bit drive - will eliminate 1 step.  Also the "Click here if the download hasn't started." link doesn't seem to do anything…
![downloaddialog](https://cloud.githubusercontent.com/assets/22108954/21949234/5706f464-d9a5-11e6-8f00-89c7b93c2d6c.png)

**Comment by pelikhan** [comment]
This is not a P1.

**Comment by pelikhan** [comment]
Yes "save as" directly into the drive is a nice trick. Works in Firefox too.

**Comment by pelikhan** [comment]
Download dialog has been dramatically simplified and auto-dissapears.
![image](https://cloud.githubusercontent.com/assets/4175913/22514765/39a91352-e855-11e6-8f36-02148c358cc4.png)
