### ISSUE TITLE
on page reload, blocks are cropped

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1134]
In Edge:

1. Create a blocks program and reload in edge.
2. See that the "on start" block is hidden under the menu bar.

![image](https://cloud.githubusercontent.com/assets/10767146/21949282/b6262316-d9a5-11e6-94c8-0204d6c5493a.png)

**Comment by pelikhan** [comment]
No repro. Please add screencast.

**Comment by tballmsft** [comment]
You need to add an another disconnected block. Try making the following program (see the disconnected pause block) and then reload.

![image](https://cloud.githubusercontent.com/assets/10767146/21949402/f186afec-d9a6-11e6-8141-c9fade5f9331.png)

**Comment by pelikhan** [comment]
We do not store the view info in the script. Looks like a blockly issue.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
@tballmsft fixed?

**Comment by riknoll** [comment]
I fixed this a while back
