### ISSUE TITLE
DEL key on Edge doesn't delete selected block

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1135]
The title says it all.  DEL works in Blockly on chrome.

**Comment by abchatra** [comment]
Dragging is the most used way to delete.

**Comment by tballmsft** [comment]
I like keys. None of them seem to work in Edge - Ctrl-C/Ctrl-X also don't work.

**Comment by tballmsft** [comment]
Keys also not working in Monaco on Edge.

**Comment by pelikhan** [comment]
Keyboard stuff is always tricky. I suspect that Monaco is stealing keystrokes. It also sometimes does not work in chrome.

Block editor is mostly a mouse interaction model.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
This is fixed
