### ISSUE TITLE
Importing older hex files - on Start nesting?

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1136]
For importing older scripts, should we help the user by throwing their blocks under On Start automatically?
Otherwise they show up greyed out, and may be confusing.  Also, why do we default into JavaScript view?

**Comment by pelikhan** [comment]
We default into the JavaScript view because we failed to load the blocks.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
@Jaqster Can you add the script in question?

**Comment by pelikhan** [comment]
We do nest old blocks within ``on start``. Please share the script.

**Comment by pelikhan** [comment]
This is by design and due to the breaking change of introducing onstart. Nothing we can do about this.
