### ISSUE TITLE
JavaScript <-> Blocks problem

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1141]
1. Add "show number" to start block 
2. Change to Monaco
3. Delete code and type "xyz" (creating a JS error)
4. switch back to Blockly (agree to switch back)
5. see error icon in "show number" block (click on it to see the JS error message!)
6. error icon does go away eventually.

**Comment by pelikhan** [comment]
Screengrab?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
@riknoll  Fixed?

**Comment by abchatra** [comment]
Fixed
