### ISSUE TITLE
Open File dialog

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1144]
File name is centered instead of left-justified.
![openfile](https://cloud.githubusercontent.com/assets/22108954/21950078/4d533d86-d9ac-11e6-9404-3d68f2833220.PNG)

**Comment by abchatra** [comment]
This is edge specific and not controlled by us. @microsoftsam can't fix right?

**Comment by microsoftsam** [comment]
Yes, browser specific UI component.

**Comment by microsoftsam** [comment]
I'll take a look to see if there's a way around it.

**Comment by abchatra** [comment]
Won't fix for now.
