### ISSUE TITLE
Custom images to associate with the project.

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1153]
All of the tutorial project has an image (like below). My kid was wondering how he could associate a custom image for his project? There was no option in the ‘settings’ of the project that allows for renaming, adding description, etc.

![image](https://cloud.githubusercontent.com/assets/6107272/21951795/a19999b6-d9c1-11e6-96cc-83d9a6dcf003.png)

**Comment by pelikhan** [comment]
All user generated images would have to be scanned before being displayed in the editor.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Won't fix for now as we need to scan the images.
