### ISSUE TITLE
on start should contain initialised values

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1154]
javascript contains:
`let url = ""
`
for blocks -> code maybe on start should clearly show initialised value 
![image](https://cloud.githubusercontent.com/assets/866122/21953479/d9936afa-da38-11e6-8859-c5bf6ba46c56.png)

**Comment by OwenBrotherwood** [comment]
consider the use of a cog icon in on start to do the same stuff as the Variables 
And really, get rid of the Variables item ...

**Comment by OwenBrotherwood** [comment]
The Variables item is not present in JavaScript choices (of course)
Allowing variables in on start makes for the same structure blocks and javascript

**Comment by OwenBrotherwood** [comment]
The use of string in the example should not be taken as string is a must: the same point is for non-string

> Strings are not a core scenario in blocks - use JS

**Comment by abchatra** [comment]
![image](https://cloud.githubusercontent.com/assets/6107272/21965340/e47828c2-db12-11e6-98d9-f13918e13454.png)
let url = "" does the right thing for me. Share the full js. Closing till then.

**Comment by OwenBrotherwood** [comment]
If I ask a student, what will the following show, there is no immediate answer as the student needs to know that the value would be 0 if not set.
This is in contradiction to javascript, where the same exercise would give a response as it can be seen in the javascript
An awareness of initialised values is not built up in blocks
![image](https://cloud.githubusercontent.com/assets/866122/21965602/9a26b2a6-db63-11e6-97c1-d11a7710e7fa.png)

let item = 0
basic.forever(() => {
    basic.showNumber(item)
})
