### ISSUE TITLE
on start could contain initialisation of new variables

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1155]
on start has now appeared on canvas as a container.
if on start contained a cog to create variables (rename etc) then its use would be extended to the clear definition of variables at the start of a program (javascript scoping)
it would also make the Variables menu obsolete

**Comment by pelikhan** [comment]
Interesting.

**Comment by OwenBrotherwood** [comment]
One should probably take a look at https://github.com/Microsoft/pxt/issues/1154#issuecomment-272718745 as it is related.
I divided my initial issue (with comments) to two issues (and deleted comments in 1154)

**Comment by abchatra** [comment]
Won't fix for now. Feel free to give pull request.
