### ISSUE TITLE
Published package not shown on pxt.microbit.org

### ISSUE THREAD

**Issue by chevyng** [Microsoft/pxt#1157]
Hi PXT team,

I have followed the instruction from [](https://www.pxt.io/packages) on publishing my own package for use in pxt but my package isn't showing when I search for it on "Add Package".

May I know if there are any other steps that are required in order for my package to be shown on the pxt.microbit.org website??

Also, the "Contact Us" link (https://www.pxt.io/contact) is broken and there are no other ways that I can contact the PXT team except from here.

Thank you,
Chevy Ng

**Comment by pelikhan** [comment]
Only approved packages are listed in the search result. Please open a ticket at support.microbit.org to request a review of your package by the Microbit Foundation. Where is the repo?

Thank you for pointing out the broken contact page...

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
See updated docs: https://github.com/Microsoft/pxt-microbit/pull/344

**Comment by chevyng** [comment]
Hi Peli,

Thank you for the fast reply. 
My repo is located here : https://github.com/chevyng/pxt-ucl-junkrobot
However my package isn't fully ready to be published yet as I might add more functionalities to the package. 

Thanks for also adding the approval process on the tutorial page!

**Comment by pelikhan** [comment]
Are we all good here?
