### ISSUE TITLE
Disk icon / project name

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1164]
There is no indication of a change of project name is actually "done": return is often what one does to complete a rename, no movement (indication) in the field one has "returned" in.

As one is typing, the window/tab is changed but when has multi tabs, this is hard to see and is not immediate obvious.

I have seen a tendency to click on the disk icon (save) which actually starts a download: sometimes spoiling what one is doing.

The possibility of "save as" contra overwrite is another possible issue but placed here

![image](https://cloud.githubusercontent.com/assets/866122/22035338/e0348600-dcef-11e6-8702-dc12681ce7c3.png)

**Comment by abchatra** [comment]
+1 for this feature request.
