### ISSUE TITLE
format code: on start and forever

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1166]
Prefered position of on start and forever after format code
![image](https://cloud.githubusercontent.com/assets/866122/22039105/35399178-dcfe-11e6-9b98-27dabdf987e5.png)

Actual position after format code

![image](https://cloud.githubusercontent.com/assets/866122/22039133/569f157c-dcfe-11e6-9a32-1dd13bace639.png)

**Comment by abchatra** [comment]
Won't fix for now.
