### ISSUE TITLE
Radio signal strength returns values outside the range 0-255

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1167]
Documentation writes that the `signal` value is `from 255 (weak) to 0 (strong)` but I'm getting values around -55 to -70 when holding two microbits close together (0-30cm). That looks more like dB values to me?

![microbit-screenshot](https://cloud.githubusercontent.com/assets/5718354/22039633/56f01fc4-dd00-11e6-834a-b6afc44dddb9.png)

**Comment by riknoll** [comment]
It is indeed decibels. @pelikhan what is the correct range so that I can update the documentation?

**Comment by riknoll** [comment]
Or, should we just scale it to 0-255 because decibels are not easy for kids to use?

**Comment by riknoll** [comment]
Looks like the typical range is -42 to -128 according to the DAL
