### ISSUE TITLE
forever with empty lambda should be no-op

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1172]
We should optimize away forever calls with empty lambdas.

**Comment by abchatra** [comment]
@pelikhan during conversion from blocks to typescript?

**Comment by pelikhan** [comment]
We need to keep it in typescript for backward conversion. It should happen in TS -> IR compilation.

**Comment by abchatra** [comment]
Ok cool this needs a dead code elimination for the lamda. Can be done.

**Comment by abchatra** [comment]
Won't fix for now
