### ISSUE TITLE
crowdin subdomain

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1173]
Setup a CNAME redirect to crowdin.com to support a https://translate.pxt.io subdomain for translations.

![image](https://cloud.githubusercontent.com/assets/4175913/22082703/a5294b5c-dd7d-11e6-8dc7-eb00d53f8428.png)

**Comment by mmoskal** [comment]
See my email.

**Comment by mmoskal** [comment]
SSL is not supported.
