### ISSUE TITLE
neopixel hsl cannot be used

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1178]
`item.setPixelColor(0, neopixel.rgb(255,255,0))`
works but
`item.setPixelColor(0, neopixel.hsl(360, 100, 50))`
throws the error
`Argument of type 'HSL' is not assignable to parameter of type 'number'.`

(In the block editor you can't connect the hsl block)

Am I using it wrong or is this a bug? The help reference pages don't exist so I can't look it up. (is that another bug?)

**Comment by nielsswinkels** [comment]
And of course I right after discover another block for converting to rgb.
`item.setPixelColor(0, neopixel.hsl(Math.random(361), 100, 50).toRGB())` this works.

Was this added very recently or did I just not see it? Anyway, why is this conversion even needed?

**Comment by abchatra** [comment]
setPixelColor expects the second argument as RGB (number). neopixel.hsl is an object to store the a HSL (hue, saturation, luminosity) format color. This is as expected.

**Comment by pelikhan** [comment]
We should get rid of that HSL class.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Ok I will keep this open. Request to remove HSL from neopixel package.

**Comment by nielsswinkels** [comment]
I would like to argue for keeping the hsl function but make it return a number instead of an object. In other words the hsl function should have the convert built in.

I think it is great for kids to learn that there are multiple ways of defining colors. And in some cases hsl is easier than rgb. (For example I wanted to have something run through different bright colors. A random hue is perfect for that. Random rgb gives a very different result.)

**Comment by pelikhan** [comment]
Exactly what we planned.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by nielsswinkels** [comment]
So why did this still get removed? Now the hsl function is gone?

**Comment by abchatra** [comment]
The microbit issues have moved to https://github.com/Microsoft/pxt-microbit repo. 
If this is still an issue please open the issue in that repo or let us know, we will reopen in that repo.
