### ISSUE TITLE
PXT titled "Recommended browser for linux" on Google search

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt#1179]
<img width="800" alt="screen shot 2017-01-19 at 9 09 31 am" src="https://cloud.githubusercontent.com/assets/6453828/22117031/49f27a74-de27-11e6-84cc-3e72bb470fa2.png">

Looks like the search crawlers are getting confused with the browser recommendation popup.

**Comment by abchatra** [comment]
Peli fixed this. Fix needs changes to be merged in master. I will close this once that happens.
