### ISSUE TITLE
Neopixel strip doesn't return to previous state after hover out on Safari

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#1182]
![firefoxsafari](https://cloud.githubusercontent.com/assets/16690124/22129811/266252c4-de5d-11e6-9c4a-94eaec0b9b00.gif)

**Comment by abchatra** [comment]
The microbit issues have moved to https://github.com/Microsoft/pxt-microbit repo. 
If this is still an issue please open the issue in that repo or let us know, we will reopen in that repo.
