### ISSUE TITLE
Typo in error message: "Oops, there is a 'program' converting your code"

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/pxt#119]
**program** should be **problem** in error message when code cannot convert to blocks

![converterror](https://cloud.githubusercontent.com/assets/12022944/16812804/9935ecc6-48e3-11e6-8f28-03d526d6c8c2.PNG)

**Comment by thomasdenney** [comment]
This is a duplicate of [issue 98](https://github.com/Microsoft/pxt/issues/98), which has been fixed. This issue can be closed.

**Comment by eric-camplin** [comment]
still have repo on codethemicrobit.com though
