### ISSUE TITLE
IE11 controls for blocks examples in docs are invisible

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#1191]
In our rendered blocks samples, the controls (download, play, etc.) are invisible but can still be clicked.

**Comment by microsoftsam** [comment]
Can't repro locally. 
I'm getting this error on the docs page: 
CSS3111: @font-face encountered unknown error.

@mmoskal any idea what could be going on here? We're using woff, and are having no issues with icons on the main page. Just docs and just IE.

**Comment by riknoll** [comment]
This no longer repros on my local box; I don't see the font face error either.

**Comment by pelikhan** [comment]
The font-face issue could be CORS related. Is the repro local or from the cloud hosted web site?

**Comment by microsoftsam** [comment]
The repro is from the Cloud hosted website

**Comment by abchatra** [comment]
Fixed
