### ISSUE TITLE
Documentation Windows 10 for pxt-microbit local install does not include prerequisite installation of VS C++ toolchain

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt#1202]
Hello,

Installed pxt on windows 10 using instructions here: https://www.pxt.io/cli

Error: TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. 

Error resolved by installing VS and creating a C++ project which, in turn, leads to an installation dialogue for the toolchain.

local install created successfully after that.

Rae

**Comment by riknoll** [comment]
Fixed in https://github.com/Microsoft/pxt/commit/ab42c9c8590ec5f846364e761b8553af3993844a
