### ISSUE TITLE
Need pin edge event for sensing water flow

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt#1208]
Hello,

Please can you add more pin events to mirror the C++ API more closely? I would like to use MICROBIT_PIN_EVENT_ON_EDGE in the first instance.

I am using a flow meter which will produce a prolonged pulse when water is flowing through it. I need to be able to set an event when the pin goes to HIGH or, conversely, when the pin goes LOW. 

This is urgent for me as I am running a project for students to measure water usage in the toilets here. They are first year Arts and Science students with no Computer Science background so cannot go straight to C. They are having great fun with PXT and the microbit and more of them are engaged in the coding this year because they feel it's something they can do. The PXT programming environment has made a huge difference.

Rae

**Comment by pelikhan** [comment]
Under control, you can register to custom events. Find the numerical value in the C++ DAL if needed.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rharbird** [comment]
Thanks Peli,

I am looking forward to trying this out.


Rae
