### ISSUE TITLE
Arrow key movement in the code editor on iPad with an external keyboard

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#121]
The arrow keys on an external iPad keyboard do not move the cursor or allow you to interact with IntelliSense. From what I can gather it is [difficult if not impossible](http://stackoverflow.com/questions/30221024/how-to-detect-arrow-keys-using-javascript-on-ipad-with-bluetooth-keyboard) to get this working, but it may be possible in the future.

**Comment by thomasdenney** [comment]
I've looked into this a little more and it may be possible to hijack the scroll event when an unknown key (i.e. possibly an arrow key) is pressed and wait for a scrolling motion in an invisible div.

**Comment by thomasdenney** [comment]
This issue was specifically related to ACE, but Monaco doesn't support mobile browsers anyway.

**Comment by jaustin** [comment]
@abchatra could we re-open this please and look again at the cursors on iPad in Monaco, as we've had a user report this as a problem as well.

**Comment by abchatra** [comment]
@jaustin Can you elaborate on the issue? Older issue was for ACE editor. Is this with external keyboard as well?

**Comment by MattFielding** [comment]
@abchatra Hi I reported the problem. I am trying to use the JS code editor at https://makecode.microbit.org/ using the new Apple iPad Pro 10.5 with Apple Smart Keyboard. The cursor keys don't work in the code view making it pretty tedious to move around using touch gestures only.

**Comment by abchatra** [comment]
Thanks @MattFielding Can you also test beta https://makecode.microbit.org/beta ? 
Just to make sure we haven't fixed this yet.

**Comment by thomasdenney** [comment]
I reported the issue (of not getting arrow key events) to Apple last summer as occurring on both iOS 9 and what was the iOS 10 beta at the time. On the iOS 11 beta it still occurs (as far as I know) and they are yet to comment/fix the issue.

**Comment by MattFielding** [comment]
@abchatra I just tested the beta and the issue is unchanged
