### ISSUE TITLE
control.onEvent(..) does not work with pin0

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt#1215]
Hello,

This is related to #1208 and support call ticket 764  https://support.microbit.org/helpdesk/tickets/764 which was raised by Prof. Stephen Hailes.

control.onEvent(EventBusSource.MICROBIT_ID_IO_P0, EventBusValue.MICROBIT_EVT_ANY) does not work. No event is raised. 

Note: I also tried creating a variable for my own event value, corresponding to an existing event MICROBIT_PIN_EVENT_ON_EDGE. This    

After a little investigation, I can see that:

1. Detecting an event with the button works well: 
control.onEvent(EventBusSource.MICROBIT_ID_BUTTON_A, EventBusValue.MICROBIT_EVT_ANY, () ...

2. Using the pin as a button works well (possibly pxt reuses the button code? )
input.onPinPressed(TouchPin.P0, () => {

I need to detect an edge on a digital pin ( flow sensor, sound detector etc.) and cannot do this with on.PinPressed.

This is urgent for me. I have students on a course who will be measuring water flow, sound and presence detection next week.

Regards,

Rae

**Comment by riknoll** [comment]
This code:
```
control.onEvent(EventBusSource.MICROBIT_ID_IO_P0, EventBusValue.MICROBIT_EVT_ANY, () => {
    basic.showNumber(1)
})
```

works fine for me. I haven't tested the "edge" event but I'm able to trigger pin pressed events that way. Can you share more of your code?

**Comment by rharbird** [comment]
Hello Richard,

Thank you for your reply.

I hope this is a bit more specific, happy to provide more information if needed:

**Preliminary test**: tested 2 micro:bits using this code to check that the devices are working:
Result: both devices are working

let count = 0
basic.forever(() => {
    basic.showNumber(count)
    basic.pause(100)
})
input.onPinPressed(TouchPin.P0, () => {
    count += 1
})




**1. Trigger event on PIN0 with event MICROBIT_BUTTON_EVT_CLICK**
a) simulator - works
b) tested 2 micro:bits - doesn't work 


let count = 0
basic.forever(() => {
    basic.showNumber(count)
    basic.pause(100)
})
control.onEvent(EventBusSource.MICROBIT_ID_IO_P0, EventBusValue.MICROBIT_BUTTON_EVT_CLICK, () => {
    count += 1
})


**2. Trigger event on PIN0 with event MICROBIT_BUTTON_EVT_ANY**
a) simulator - doesn't work
b) tested 2 micro:bits - doesn't work 

let count = 0
basic.forever(() => {
    basic.showNumber(count)
    basic.pause(100)
})
control.onEvent(EventBusSource.MICROBIT_ID_IO_P0, EventBusValue.MICROBIT_EVT_ANY, () => {
    count += 1
})

**3. Trigger event on PIN0 with MICROBIT_PIN_EVENT_ON_EDGE **
I didn't get this right. I haven't understood Peli correctly. I tried a couple of things. Firstly, I tried to use the edge event which is present in the underlying cpp code, secondly, I tried to use a variable set to the value of MICROBIT_PIN_EVENT_ON_EDGE (1). Both attempts just gave a syntax error.

**Comment by riknoll** [comment]
Ah, I just took a look at the C++. Try calling `input.pinIsPressed(TouchPin.P0);` like so:

```typescript
let count = 0
input.pinIsPressed(TouchPin.P0);

basic.forever(() => {
    basic.showNumber(count)
    basic.pause(100)
})
control.onEvent(EventBusSource.MICROBIT_ID_IO_P0, EventBusValue.MICROBIT_BUTTON_EVT_CLICK, () => {
    count += 1;
})

````

That will force the pin to switch over to the makey-makey style detection that we use for `input.onPinPressed`.

**Comment by rharbird** [comment]
Hello Richard,

Thank you for your help. Do you know whether "makey-makey style detection" involves code for debouncing? That is the right thing to do for buttons and checking if the pin is pressed. 

It won't give sensible data when you are using other sensors though. I'll get back to you if I may.


Regards,


Rae

**Comment by riknoll** [comment]
Yep, it should have the same results as `input.onPinPressed()`.

I did some more digging and to get the pin to emit edge events I think you want to try something more like this:

```typescript
// Just call this function to configure the pin, no need to do anything in the callback
pins.onPulsed(DigitalPin.P0, PulseValue.High, () => {})

// These are defined in the DAL
const MICROBIT_PIN_EVT_RISE = 2;
const MICROBIT_PIN_EVT_FALL = 3;

control.onEvent(EventBusSource.MICROBIT_ID_IO_P0, MICROBIT_PIN_EVT_RISE, () => {
    // RISE event handler
})

control.onEvent(EventBusSource.MICROBIT_ID_IO_P0, MICROBIT_PIN_EVT_FALL, () => {
    // FALL event handler
})
```

Calling `pins.onPulsed` should configure the pin to emit edge events. Those rise and fall event handler values are taken from the C++.

 Sorry for the roundabout way of configuring that, we should really expose more of the pin events in our API. @pelikhan what do you think about just surfacing the `pin.eventOn` method?

**Comment by rharbird** [comment]
Hello,

I've tested with the  code you suggested. It doesn't work with a microbit (works with the simulator). 

This could be because 'onPulsed' configures the pin to generate pulse events rather than edge events. This is what looks like it's doing in libs/core/pins.cpp. You can't test for edge events if the pin is configured for pulse events. If you want the pin to detect edge events then you have to use: 

pin->eventOn(MICROBIT_PIN_EVENT_ON_EDGE); 

I have done some other testing using the c++ api which may help. This code will generate an edge event:

        // Initialise the micro:bit runtime.
        uBit.init();

        // Start up
        uBit.io.P0.setPull(PullUp);
        uBit.io.P0.eventOn(MICROBIT_PIN_EVENT_ON_EDGE);
        uBit.messageBus.listen(MICROBIT_ID_IO_P0, MICROBIT_PIN_EVT_FALL, onFall);

        while (1) {
                uBit.sleep(1000);
                uBit.display.print(ManagedString(counter));
        }

See: [pinEvent.txt](https://github.com/Microsoft/pxt/files/736810/pinEvent.txt)

Please can you expose this in the javaScript API?

FYI: I have been testing this using an mbit, edge connector and a sparkfun sound detector which gives a 1 if a sound is detected.

We really appreciate your help so anything you can suggest as a workaround in lieu of a permanent solution is welcome.

**Comment by riknoll** [comment]
Ah, you're right. I don't think there is a good workaround for this. I've opened a PR exposing the API
