### ISSUE TITLE
Can't select from list of standard event IDs/values in IF blocks

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt#1225]
It used to be possible to include predefined event IDs/Values in IF blocks but that capability seems to have vanished. Here's an example of what used to be possible:

![image](https://cloud.githubusercontent.com/assets/8341666/22365792/52f06118-e471-11e6-8943-2486a49f90df.png)

**Comment by riknoll** [comment]
Yep, it doesn't make sense to have the "Event Value" block if we don't also make the ID block available in the toolbox

**Comment by riknoll** [comment]
This is actually a bug that has been fixed in the develop branch. When that gets merged into master and released, that block should show back up.

**Comment by bluetooth-mdw** [comment]
Great, thank you :-)
