### ISSUE TITLE
Compass code

### ISSUE THREAD

**Issue by githubhero** [Microsoft/pxt#1233]
Hello, not exactly an "issue" but, please, if you can, let me understand better a thing.   :-)

I found this example here:
https://www.microbit.co.uk/functions/compass-heading

In particular the following lines:
```

while true do
degrees := input → compass heading
if degrees < 45 then
basic → show string("N", 100)
else if degrees < 135 then
basic → show string("E", 100)
else if degrees < 225 then
basic → show string("S", 100)
else
basic → show string("W", 100)
end if
end while 
```

I converted this code to PXT this way:

```
basic.forever(() => {
    var degrees = input.compassHeading();
    //
    if (degrees < 45) {
        basic.showString("N");
    } else if (degrees < 135) {
        basic.showString("E");
    } else if (degrees < 225) {
        basic.showString("S");
    } else {
        basic.showString("W");
    }
})
```

This code "works" but for one reasons I don't like it. 

Correct me if I'm wrong but:
- N should be shown when degrees is an integer > 315 or < 45
- E should be shown when degrees is an integer > 45 and < 135
- S should be shown when degrees is an integer > 135 and < 225
- W should be shown when degrees is an integer > 225 and < 315 

Is there any reason why they coded it this way?

**Comment by microsoftsam** [comment]
I would say the reason they went with the former approach was to keep the program simple.
The more "accurate" approach would be: 

```
basic.forever(() => {
    if (input.compassHeading() >= 315 || input.compassHeading() < 45) {
        basic.showString("N")
    }
    if (input.compassHeading() >= 45 && input.compassHeading() < 135) {
        basic.showString("E")
    }
    if (input.compassHeading() >= 135 && input.compassHeading() < 225) {
        basic.showString("S")
    }
    if (input.compassHeading() >= 225 && input.compassHeading() < 315) {
        basic.showString("W")
    }
})
```

In the future, please post questions regarding content on the micro:bit support page: 
https://support.microbit.org/support/home
