### ISSUE TITLE
add "import project from URL" option

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#124]
We should be able to paste URLs like:
```
https://codethemicrobit.com/api/oembed?url=https%3A%2F%2Fcodethemicrobit.com%2Fbisxdnsllg&format=json
https://codethemicrobit.com/bisxdnsllg
```
and possibly others. This is useful when:
* you're running from localhost
* you're running from an app (Electron, Windows Hosted app etc)
* you don't want to close your current pxt instance to import project

**Comment by mmoskal** [comment]
Another one to support:

```
https://github.com/mmoskal/pxt-i2c-fram
```

This should be also exposed as `https://codethemicrobit.com/#clone:<URL>` so that people can add such links to their pages. I guess it should ask for confirmation of import.

**Comment by microsoftsam** [comment]
Spoke to Peli, and we're cutting the second feature request to support cloning of github packages.
