### ISSUE TITLE
Multi-select support in Blocks editor

### ISSUE THREAD

**Issue by nevilh** [Microsoft/pxt#1245]
Is there a way to cut-and-paste a group of Blocks from one program into another? (A work-around would be to convert to Java Script, then cut-and-past, then converting back to Block but it would be nice to do it without going via Java Script)

**Comment by microsoftsam** [comment]
As of yet, Blockly doesn't support Multi-select.
Although, you are able to copy a block to your clipboard and paste it in another editor.
