### ISSUE TITLE
Giving new programs an automatic name rather than 'Untitled'

### ISSUE THREAD

**Issue by nevilh** [Microsoft/pxt#1246]
Could you give new programs an automatic name e.g."fantastic script" like the regular Block Editor does rather than "Untitled"? Student are sometime lazy and don't rename their programs so end up with multiple programs called "Untitled". The way the regular "Block" Editor automatically assigns a new random name does it works well in the Classroom.

**Comment by pelikhan** [comment]
What about generating a name based on the current date? It a way that it gets sorted to the bottom. The random names are random and after a while as confusing as "untitled".

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by riknoll** [comment]
I think date is a good idea

**Comment by nevilh** [comment]
Using the date seems a reasonable idea.
If you use date could I suggest that you put PXT at the front of the date. Then when in your hex files directory it is easy to see which hex files are generated from PXT.
Also note that the American date for today is 02-03-17 (MM-DD-YY) whereas the British use 03-02-17 (DD-MM-YY). You could use the universal way to write date 17-02-03 (YY-MM-DD). This has the advantage that if you sort by file name they also get sorted in chronological order. The only down side is that most 10 year olds in the UK wouldn't recognise this way of writing the date! The other alternative would be to use 03-FEB-17. I quite like the use of 'FEB' because it makes it obvious that it is a date rather than appearing like a random jumble of numbers. So with PXT in front, the file name would become PXT-03-FEB-17, maybe with a sequence number to cope with multiple programs written on the same day e.g. PXT-03-FEB-17-PROG1, or if it is easier for you, the time of day. And maybe use the full 4 digit year as it makes it more obvious at a glance that it is the 'year' field. e.g. PXT-03-FEB-2017-15-45 if the program was written at 3:45pm. This is a much more 'human' readable way of representing the Date and Time which I quite like and I'm sure most 10 year olds would understand.
Cheers,
Nevil

**Comment by abchatra** [comment]
Fixed by popping up a dialog for a name if the default name is untitled when save is clicked
