### ISSUE TITLE
A short "Getting Started" guide doc to using the user interface

### ISSUE THREAD

**Issue by nevilh** [Microsoft/pxt#1247]
Could you create a short "Getting Started" guide doc to using the user interface, etc pointing out what everything on the screen does and add it as a menu item under the "help" drop down menu. E.g I've only just spotted the Undo/Redo Buttons in the bottom right corner - (I've been after an 'undo' in Block for over a year so I'm really pleased you have it in PXT, including being able to use <Ctrl Z> )

**Comment by ganicke** [comment]
Editor feature overview page added in #4130
