### ISSUE TITLE
Creating a function in blocks that can be saved into a "User" package

### ISSUE THREAD

**Issue by nevilh** [Microsoft/pxt#1249]
One feature which I'd like to see would be the ability to create a function in blocks, save into a "User" package so that the function becomes a single Block that can be dragged into a program. And then be able to import this "User" package so these User Defined Blocks can be used in other PXT scripts. This would be fantastic if it could be done!

**Comment by pelikhan** [comment]
Available in beta. https://pxt.microbit.org/blocks/custom
