### ISSUE TITLE
codethemicrobit can't save/import JS code?

### ISSUE THREAD

**Issue by martincottrell** [Microsoft/pxt#125]
Hi,  really enjoying this interface. It's got everything I want but...when I code in JS and not blocks, and add say classes etc I can't seem to save anything anyway? I thought I could compile to hex and open a project using the jex file but when I do that it's blank? If I use the blocks it's all ok but when I go outside the reference blocks coding in JS nothing seems to be able to be saved/recoverable between sessions? Am I doing this wrong??  Thanks, Martin

**Comment by thomasdenney** [comment]
@martincottrell Please could you provide a code samples that you can't get to save?

**Comment by martincottrell** [comment]
Hi,
 
just this is an example below. 
 
I think it might have something to do with going to the block editor when you try opening/loading the project? The block editor does not know what to do with this so resets without warning? Seems to do the same thing when importing the hex. I'm more of a C# programmer so hope this is ok code!
 
class Motor {
    PinPMW:AnalogPin;
}
var RightFront:Motor = new Motor();
 
Thanks, Martin
 
Date: Wed, 20 Jul 2016 01:36:23 -0700

**Comment by martincottrell** [comment]
Is it possible to have a hard/profile/project switch to say project javascript only? Could get prompted for when trying to switch to block view/or block view raises error loading?

**Comment by pelikhan** [comment]
Currently, the only way to get a JavaScript only project is to go in the File List and delete the ,main.blocks file.

**Comment by microsoftsam** [comment]
I believe this has been fixed when we added the option to remove the blocks file in the popup. #189
