### ISSUE TITLE
acceleration dimensions X/Y do not correspond physically

### ISSUE THREAD

**Issue by kepsi** [Microsoft/pxt#1250]
`input.acceleration(Dimension.Y)` 
detects movement on horizontal axis on calliope mini, while the simulator reacts on vertical movement.
In comparison: 
`LedSpriteProperty.X` "moves the LED" horizontally (which is correct)

editor: mini.pxt.io

**Comment by pelikhan** [comment]
@thinkberg can you take a look?

**Comment by abchatra** [comment]
This issue is tracked externally. Closing in pxt.
