### ISSUE TITLE
Strange blanking effect on palettes

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1254]
This issue was raised by one of our digital leaders in our school computer club today. I am pasting the image here of the effects, but once I find out his github handle, I'll tag him into this ticket and get him to explain the steps to reproduce the issue.

![pxt_bug](https://cloud.githubusercontent.com/assets/4086785/22481035/82f36f9a-e7eb-11e6-8503-29c2d0f18144.jpeg)

**Comment by whaleygeek** [comment]
@STEMGeek is our digital leader in the school club that spotted this problem. Hopefully he should be able to comment on this ticket and list the steps that he went through to get the screen you see above into this condition.

**Comment by pelikhan** [comment]
This issue is fixed in /beta. Could you try again using that release?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by whaleygeek** [comment]
Great, thanks @pelikhan I'll get @STEMGeek to try that for you - thanks for speedy reply!

The URL, for reference, is: https://pxt.microbit.org/beta

**Comment by pelikhan** [comment]
Reopen if it reappears in beta.
