### ISSUE TITLE
Blockly layout issue in Edge And IE11 

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#1257]
Very noticeable layout bleeding issue in IE11 and Edge in beta:

![bleeding_issue2](https://cloud.githubusercontent.com/assets/13754588/22492460/c93f0d5e-e7de-11e6-8e7b-9f56e56d889a.PNG)
![spacing_issue](https://cloud.githubusercontent.com/assets/13754588/22492462/cba57c2c-e7de-11e6-9df6-ceb60db7e60f.PNG)

**Comment by riknoll** [comment]
@microsoftsam any ideas?

**Comment by microsoftsam** [comment]
This is a font size issue. 
It might be only reproing on Edge / IE because of a CSS issue, or there's more to it with Blockly rendering, but I suspect its the former. Will take a look.

**Comment by pelikhan** [comment]
I think blockly has a bug on text size computation in Edge.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microsoftsam** [comment]
Yep looks like blockly bug

**Comment by pelikhan** [comment]
Maybe this one: https://github.com/google/blockly/pull/878

**Comment by pelikhan** [comment]
Upstream blockly bug, degrading P2.

**Comment by microsoftsam** [comment]
Fixed.

**Comment by rachel-fenichel** [comment]
Hey there--you're probably going to get hit by this followup bug: https://github.com/google/blockly/issues/969

We're actively debugging.  The bug is currently on develop but not master.

**Comment by microsoftsam** [comment]
Thanks @rachel-fenichel
