### ISSUE TITLE
Loss of disabled blocks when roundtripping

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#126]
Steps to reproduce:

1. Add a block
2. Disable it via the block's context menu
3. Go to the code
4. Make a modification to the code
5. Go back to the blocks
6. The disabled block is missing

Expected behaviour: The disabled block is still present, disabled blocks show up as comments in JS, or disabling blocks isn't an option.

**Comment by pelikhan** [comment]
I propose to remove "disable blocks" option. @tballmsft @mmoskal thoughts?

**Comment by abchatra** [comment]
May be option is to disallow the disabling of blocks. (Code.org doesn't have this).
