### ISSUE TITLE
test.cs variables are picked up in VS Code

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1263]
VS Code picks up all the code in pxt-modules, including the ones in test.cs files which should be ignored. Is there a way to tell typescript to ignore those?

**Comment by riknoll** [comment]
In what repo? The answer is yes, just include a tsconfig.json that has an exclude pattern:

```json
{
    "compilerOptions": {},
    "include": [],
    "exclude": [ "**/test.ts" ]
}
```
Put it in some directory above the tests. https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by pelikhan** [comment]
In PXT-neopixel, we should also add that to generated projects.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by riknoll** [comment]
We could just add it to the tsconfig we already generate in new projects:
`"exclude": "pxt_modules/**/test.ts"`
