### ISSUE TITLE
Versioned package references

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1264]
Package references will be automatically updated if there is a semver compatible new version available. 

- [ ] when adding a package, the editor will use MAJOR.* to allow automatic update to a new MAJOR compatible release • a power user can hardbound a package by in-lining a MAJOR.MINOR version number
- [ ] to force update packages, users can go into the explorer and click on the Update button 
- [ ] when trying to add a package with incompatible semver, the user is prompted that the highest version will be used

**Comment by abchatra** [comment]
This is for version 2. Moving it away from RC.

**Comment by abchatra** [comment]
Won't fix for now.
