### ISSUE TITLE
.hex/.uf2 files contains versions of the editor

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1265]
- [x] .hex/uf2 file contain the target version
- [x] .hex/uf2 files contain the pxt version (also useful)

**Comment by jaustin** [comment]
We should (could) use the UICR for this

**Comment by pelikhan** [comment]
Don't know what UICR is. The "TargetVersions" info is embedded in the .hex file, and in shared projects as well.
https://github.com/Microsoft/pxt/blob/ae7439985e7ff7c81123182c44653163d64da1c5/localtypings/pxtpackage.d.ts#L6
