### ISSUE TITLE
versioned documentation

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1266]
Documentation is versioned by maintaining several branches in the target repo.  
- [x] These would typically be named ``v0``, ``v1``, etc. corresponding to MAJOR versions of the target.  
- [x] These branches are mapped according to MAJOR: ``docs/foo/bar.md`` on ``v1`` branch for example would be served under ``/v1/foo/bar``.  
- [x] Additionally, ``docs/index-ref.json`` in the “master” branch specifies the version of the target served at ``/``, 
- [x] and ``docs/index-ref.json`` on branch ``v1`` specifies target version at ``/v1``.

**Comment by abchatra** [comment]
@peli I am moving this to you as there are bunch of issues on versioning on Guillaume. Let us discuss if we need this for RC as all the docs now are in v0.

**Comment by pelikhan** [comment]
@mmoskal let's sync on this. i've gone through the backend docs, just want to be sure about this.

@abchatra I don't think we need this for RC since we only have 1 major release in flight.

**Comment by mmoskal** [comment]
@pelikhan - this all looks right; once we have two branches we can test it out

**Comment by mmoskal** [comment]
@pelikhan - with a few more lines of code we should be able to pull docs from 'core package' repo and overlay the docs on the target on top - this would let us share docs for the core package between targets
