### ISSUE TITLE
versioned shared urls

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1267]
The URL for a published script can contain the target-version that was used to create that project, and the service will obey this URL.

**Comment by pelikhan** [comment]
Should be covered by https://github.com/Microsoft/pxt/issues/1269.

**Comment by mmoskal** [comment]
The link https://pxt.microbit.org/v0/76163-68307-61679-20354 now works. It sets `@versionsuff@` variable to `v0`. I have added it to the default script.html template, but will take some bumps to get to production. 

See https://github.com/Microsoft/pxt/pull/1308

We still don't do anything smart there - just following what's in the link.

**Comment by pelikhan** [comment]
The shared script contains the TargetVersions information which allows to precisly redirect if needed.
https://github.com/Microsoft/pxt/blob/ae7439985e7ff7c81123182c44653163d64da1c5/localtypings/pxtpackage.d.ts#L6

**Comment by mmoskal** [comment]
Note: https://adafruit.pxt.io/13627-55304-21214-50658 contains a JSON representation of the script towards the end. This can be used for redirect.
