### ISSUE TITLE
Adding parentheses in code fails to produce blocks

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#127]
Steps to reproduce:

1. https://codethemicrobit.com/ddhdmcdvvg
2. Go to the code
3. Change the code from `let item = 0 * 0 + 0 / 0` to `let item = (0 * 0) + (0 / 0)`
4. Attempting to go back to blocks fails conversion because when it compiles the blocks back to JS to check for equality, the source is compared rather than the AST 

This bug occurs in both `master` and `notd`

**Comment by riknoll** [comment]
Closing this, because it is equivalent to #316
