### ISSUE TITLE
When a typescript construct is not understand, bundle in read-only block

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1271]
When the decompiler detects that a typescript construct cannot be represented in blocks, generate special block that contains raw code.

- [ ] support for encapsulating statements

Support for sub-expression is not planned in this version.

**Comment by pelikhan** [comment]
Currently, the editor flags which line has an issue with conversion to blocks. This might be good enough.

**Comment by riknoll** [comment]
Why not make it editable in Blockly?

**Comment by pelikhan** [comment]
That works too.

**Comment by pelikhan** [comment]
You could also investigate supporting this at the expression level.

**Comment by pelikhan** [comment]
Enlightening experience today where a kid would not read the dialog and consistently click on the green (stay in js) experience. He was trapped.
