### ISSUE TITLE
BuildDalConst called before yotta dependencies installed

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1279]
We have a bootstrapping issue with building dal.d.ts. BuildDalConst gets called before "yotta update" and the enum value resolution may fail in that case.

**Comment by tballmsft** [comment]
Hmm... this seems more like one for @mmoskal

**Comment by abchatra** [comment]
Won't fix

**Comment by mmoskal** [comment]
I didn't look into that. I understand you guys did and decided it wasn't worth fixing?

**Comment by abchatra** [comment]
I will reopen it. We didn't look into this, I closed bulk of old stale issue which had no traction.

**Comment by mmoskal** [comment]
I don't think this is really an issue when using pxt-common-packages anymore, so let's close it until we have a clear scenario.
