### ISSUE TITLE
String comparison in blocks

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#128]
In the blocks editor it is not possible to use the logic blocks to compare two strings. If you drag a string onto a new `logic_compare` block, one of the (shadow) zeroes will pop out, but you can't attach the string still. This is related to [issue 112](https://github.com/Microsoft/pxt/issues/112), [issue 18](https://github.com/Microsoft/pxt/issues/18), and [issue 111](https://github.com/Microsoft/pxt/issues/111).

**Comment by abchatra** [comment]
This is going to be addressed as part of working with strings. https://github.com/Microsoft/pxt/issues/531
