### ISSUE TITLE
neopixels and bluetooth are incompatible

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1280]
microbit.org-ticket: 857

When trying to add both the bluetooth and neopixel libraries I get a conflict error. Is this really correct? furthermore the editor seems to be acting funky after this, since the simulator disappears and the error message "conflict on yotta setting microbit-dal.bluetooth.enabled between packages neopixel and bluetooth" keep popping up even though the library never got added.

![screen shot 2017-02-02 at 14 16 35](https://cloud.githubusercontent.com/assets/4086785/22552813/57c1aa22-e952-11e6-9fd8-3d052c1264d2.png)

**Comment by pelikhan** [comment]
By design, neopixels requires to send impulses at a precise timing which require to disable interrupts. The BLE stack gets really unhappy about that and may crash -- or interfere and generate invalid colors on the pixels.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by whaleygeek** [comment]
Ok great, thanks for the good info. I'll add this to our knowledge-base so that people know about this interaction. Thanks for your help.
