### ISSUE TITLE
Discrepancy between simulator and micro:bit with images

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1287]
Microbit.org-ticket: 722

In the code below the delay in the shake call needs an additional delay to show the image, whilst the manual reads that an automatic delay of 400ms is included for this object function. Also the microbits actual hardware needs this additional delay. 
In firefox on windows10 it is impossible to create this code without refreshing the browsertab, since the simulator stucks when the on action shake is created.

Groetjes uit Nederland 

```
 let mannetjeL = images.createImage(`
  . . . . .
  . # . . .
  # # # . .
  . # . . .
  # . # . .
  `)
let mannetjeM = images.createImage(`
  . . . . .
  . . # . .
  . # # # .
  . . # . .
  . # . # .
  `)
let mannetjeR = images.createImage(`
  . . . . .
  . . . # .
  . . # # #
  . . . # .
  . . # . #
  `)
input.onGesture(Gesture.Shake, () => {  
mannetjeL.showImage(0)  
basic.pause(400)  
mannetjeM.showImage(0)  
basic.pause(400)  
mannetjeR.showImage(0)
})
```

**Comment by pelikhan** [comment]
PR: https://github.com/Microsoft/pxt-microbit/pull/351

**Comment by pelikhan** [comment]
Fixed in PR.
