### ISSUE TITLE
Blockly "file append line" block is translated to function appendString

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt#1294]
This bug relates to the new File blocks.

Blockly  "file append line" translates to the typescript function "appendString" but should translate to the function "appendLine".

We're using this in class right now so a fix would be very much appreciated.

Kind Regards,

Rae

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/pxt-filesystem/commit/569780f4873de83de9346bc9a5c1ec60e1a18740.

You'll need to upgrade your reference by going in the Explorer view and click the update button.

**Comment by rharbird** [comment]
Thank you very much.


Rae
