### ISSUE TITLE
Build status badge broken

### ISSUE THREAD

**Issue by paked** [Microsoft/pxt#13]
When going through the README I noticed that your repositories "build status badge" from Travis CI is broken.

![screenshot 2016-03-20 19 14 25](https://cloud.githubusercontent.com/assets/8407370/13903451/1435787e-eed0-11e5-97ee-3d0a67d29bc8.png)

Looks like it is linking to the old name of the repo? Either way, it doesn't look like CI has been set up for the project under this name.

**Comment by pelikhan** [comment]
Fixed..
