### ISSUE TITLE
@name@ and @title@ not set in script.html rendering

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1303]
Notice the "undefined" title in the toolbar. Seems that the backend is not setting those constants.

* repro:  https://pxt.microbit.org/76163-68307-61679-20354

![image](https://cloud.githubusercontent.com/assets/4175913/22674354/6bc13372-ec94-11e6-97e5-fc1b3ddec0d1.png)

**Comment by mmoskal** [comment]
fixed now
