### ISSUE TITLE
Help in menu is missing

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1313]
![image](https://cloud.githubusercontent.com/assets/6107272/22707745/a53fdda8-ed28-11e6-8a43-8a432bc0cbd4.png)

@pelikhan Is this regression from your change?

**Comment by pelikhan** [comment]
I think it arrived here: https://github.com/Microsoft/pxt/commit/0f91eb016eb49231b9fc76aecdd01c7d7ec9e67f . Cleanup of app.tsx was overdue.

**Comment by pelikhan** [comment]
Fixed.
