### ISSUE TITLE
led.PlotBarGraph - compiler error

### ISSUE THREAD

**Issue by redjbishop** [Microsoft/pxt#1314]
Hi Peli, Program below does not compile. Pretty sure that it should. Error is "Compiler Error: c is undefined" and the line bins[n]++ appears in yellow. Thanks! Judith

```
// Declare bins
let bin: number[]
// Generate numbers, counting in bins
let run = 200
let limit = 5

led.plotBarGraph(0, 0)
for (let i = 0; i < run; i++) {
    let n = Math.random(limit)
    bin[n]++
}

// Show plot
for (let c = 0; c < limit; c++) {
    led.plotBarGraph(c, bin[c] / 40)
}
```

**Comment by pelikhan** [comment]
@abchatra array issue?

**Comment by pelikhan** [comment]
Not sure that the visualization you are trying to get will work. Plotbargraph renders the entire screen without pause. You could use pixel brightness to show a 2D histogram

**Comment by redjbishop** [comment]
Thanks!!

**Comment by abchatra** [comment]
There is a bug in the above code. You need to create the array, something like below. It is just defining a variable and not assigning anything.
```javascript
let bin: number[] = [];
```

**Comment by redjbishop** [comment]
Hi Abhijith – Thanks a lot. I realize now you had told me about how to declare arrays in JavaScript before. Would it be possible to have a better error message?
Judith

**Comment by abchatra** [comment]
@redjbishop Yes agree, error message we should improve. I will look into this.

**Comment by pelikhan** [comment]
Keeping it open to track error message

**Comment by abchatra** [comment]
We are tracking the error message improvement by collecting data. Closing issue.
