### ISSUE TITLE
API listing - Capital letters

### ISSUE THREAD

**Issue by redjbishop** [Microsoft/pxt#1315]
In the simulator, the API listing shows the packages with capital letters. In Javascript when you write them, they have to have small letters. This can be confusing. It would be better to show the API listing with the names starting with small letters, e.g. basic not Basic, led not Led

**Comment by pelikhan** [comment]
In blocks or typescript?

**Comment by redjbishop** [comment]
In both. But it only matters in Typescript, because in blocks, the namespace is encoded in color.

**Comment by tballmsft** [comment]
@riknoll: didn't we decide to switch JavaScript APIs in the toolbox to lowercase to match the program text?

**Comment by tballmsft** [comment]
We have decided to keep Uppercase everywhere.  Unfortunately, namespaces on the TypeScript side are a mix of both  Upper and lower case, and it didn't look good to have a mix, or all in lower case.

**Comment by redjbishop** [comment]
Thanks, Tom.
