### ISSUE TITLE
Bad hex file generation

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#132]
As of [this commit](https://github.com/Microsoft/pxt/commit/db94ba489a105342375b9028aafbd36478adda86) the hex files generated do not run successfully on the device. Note that this commit is only present in the `master` branch, and doesn't affect the `notd` branch.

**Comment by thomasdenney** [comment]
I can replicate this on both Windows and OS X. The hex file runs on the micro:bit fine when using the [previous commit](https://github.com/Microsoft/pxt/commit/587e93c273c68a10e8e5539208733083fea33f2c), but as of [Fix detection of the end of the .hex file (nrf51dk target)](https://github.com/Microsoft/pxt/commit/db94ba489a105342375b9028aafbd36478adda86) it fails  to run.

**Comment by mmoskal** [comment]
I’m looking into this.

**Comment by mmoskal** [comment]
Thank you, pinpointing the exact commit was very helpful!
