### ISSUE TITLE
caching of simulator is disabled when CSP is enabled

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1322]
When 3rd party cookies and app cache are disabled in browser, the simulator iframe is not allowed to create an appcache.

Investigate if it is possible to configure the CSP directive to allow app cache in simulator iframe.

**Comment by abchatra** [comment]
What is the impact on the simulator?

**Comment by pelikhan** [comment]
It would not work offline as the app cache is refused.
