### ISSUE TITLE
generalize lambdas

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#133]
to allow multiple parameters and return value.

**Comment by mmoskal** [comment]
This isn't very useful without generics #122

**Comment by thomasdenney** [comment]
The error message for `lambda functions cannot yet return values` shows in the calling location, but not on the `return` statement in the lambda, e.g. the error message shows on the second line for the following:

```typescript
let f = () => { return 0 }
basic.showNumber(f())
```

**Comment by mmoskal** [comment]
This is duplicate of #39
