### ISSUE TITLE
Add block for MIDI 

### ISSUE THREAD

**Issue by Steph77** [Microsoft/pxt#1330]
Hello,
 just a suggestion, why not add the possibility of adding midi blocks in the music category?

I realized a project based on arduino connected to an ipad to play music. It would be nice, with my students, to realize the project with a micro: [bit.](https://www.youtube.com/watch?v=863ZyF6u4nA)
It seems quite simple, in python, to produce notes in midi [format.](http://www.multiwingspan.co.uk/micro.php?page=midi)
thank you.

Regards,

Stéphane

**Comment by pelikhan** [comment]
See https://github.com/microsoft/pxt-midi
