### ISSUE TITLE
Negative servo values

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1332]
Microbit.org-ticket: 884

I'm using a micro:bit, and I have the TowerPro microservo 9g.

Can I use a negative value to get it to spin the opposite direction? It seems to only go in one direction and then I can get it back to "0" position.  

Your emulator works as I expect the Servo to work with the exception that it moves position measured from the "0" mark, not from the current position.

![servonegvalue](https://cloud.githubusercontent.com/assets/4086785/22834443/0df41216-efad-11e6-8f83-a62c84ba5e91.png)

**Comment by whaleygeek** [comment]
http://www.micropik.com/PDF/SG90Servo.pdf

![screen shot 2017-02-10 at 16 23 37](https://cloud.githubusercontent.com/assets/4086785/22834511/4ed1a582-efad-11e6-983b-9f7be7bd912d.png)

![screen shot 2017-02-10 at 16 23 44](https://cloud.githubusercontent.com/assets/4086785/22834513/51471e64-efad-11e6-8715-0d87f4220725.png)

**Comment by whaleygeek** [comment]
@pelikhan Do you have any info as to the mapping from servo degrees to pulse width that is used by PXT? Your docs state 0 to 180 degrees but I can't see any 'self help' info there about what this equates to in terms of ms of pulse width: https://pxt.microbit.org/reference/pins/servo-write-pin

I recall a while ago that you re-calibrated this based on some feedback I provided you from one of our content writers, but I never saw what the actual mapping from degrees to pulse width was. Any ideas?

**Comment by pelikhan** [comment]
It calls into the DAL servo APIs. The angle is absolute, not a difference, and has to be between 0...180.

-180 is out of bounds and ignored.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by whaleygeek** [comment]
Ok thanks.

**Comment by whaleygeek** [comment]
My bad, it was microbit.org-ticket:834.

Reporting back to customer now, thanks for your help.
