### ISSUE TITLE
No documentation for MES Events?

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1340]
microbit.org-ticket: 620
related dal ticket: https://github.com/lancaster-university/microbit-dal/issues/272

I cannot find any documentation for any of the MES events available in PXT.

The hover help when you click on the MES EVENT dropdown is greyed out:

![screen shot 2017-02-12 at 14 39 32](https://cloud.githubusercontent.com/assets/4086785/22863089/3fdcffaa-f132-11e6-9fe0-787020d6a3b7.png)

I cannot find any help on the ON EVENT (hover help is greyed out)

![screen shot 2017-02-12 at 14 48 53](https://cloud.githubusercontent.com/assets/4086785/22863107/7449d1b4-f132-11e6-942f-50690ac9aa68.png)

There is no help on the docs pages in the control section for on event

![screen shot 2017-02-12 at 14 40 49](https://cloud.githubusercontent.com/assets/4086785/22863117/8a1d8e86-f132-11e6-8381-26f1b94bf4e9.png)

**Comment by DavidWhaleMEF** [comment]
Hi guys, just wondering if there is any progress on the documentation of this one at all?

**Comment by DavidWhaleMEF** [comment]
I've created a placeholder here for now. If you have additional information you would like me to copy/contribute into the article, let me know and I can do the heavy lifting here.

https://support.microbit.org/solution/articles/19000054469-mbtn3-mes-event-registry

**Comment by ganicke** [comment]
Paged added to list MES events: https://github.com/Microsoft/pxt-microbit/pull/535.

Not sure if help linking in general for enum values is enabled at this point.
