### ISSUE TITLE
There is no way to search the PXT docs

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1341]
I can't find a way to search the PXT docs for something specific, would it be possible to add a search feature in the future?

![screen shot 2017-02-12 at 14 40 00](https://cloud.githubusercontent.com/assets/4086785/22863142/e43e0b5c-f132-11e6-9b93-2f13e9ff1154.png)

**Comment by microsoftsam** [comment]
Fixed with new docs.
