### ISSUE TITLE
Transition from microbit.co.uk/app blocks to PXT is more complex for camera triggering

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1342]
I am attempting to transition a large number of users from the BBC hosted blocks experience over to PXT. However, the camera trigger features seem to be much more complex and not well documented in PXT, and this is making the transition much harder to convince users that it is the right thing to do.

Here is a blocks script that children can understand:

![screen shot 2017-02-12 at 14 53 30](https://cloud.githubusercontent.com/assets/4086785/22863171/5bba62b6-f133-11e6-8074-5671f50c7911.png)

Here is the equivalent script in PXT:

![screen shot 2017-02-12 at 14 54 27](https://cloud.githubusercontent.com/assets/4086785/22863176/63805bd6-f133-11e6-9b76-f53836e86bc9.png)

There appears to be no documentation on the RAISE EVENT block in the docs.

There appears to be no documentation on the MES_EVENTS in the docs.

I'm not sure what the from_source is, and what it should be set to in this case:

![screen shot 2017-02-12 at 14 54 32](https://cloud.githubusercontent.com/assets/4086785/22863187/7fa3fd90-f133-11e6-9c65-c4e4e51c50f0.png)

Just a suggestion - put back in the 'devices' palette that microbit.co.uk/app blocks had in it? It was very child friendly and very obvious to use. It'll only be a wrapper around this more complex event semantics, so presumably we could surface this as a pxt-package?

![screen shot 2017-02-12 at 14 57 44](https://cloud.githubusercontent.com/assets/4086785/22863200/af89f708-f133-11e6-85c5-cd8c8a99bf30.png)

**Comment by pelikhan** [comment]
Did you try adding the "devices" package?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by whaleygeek** [comment]
Ooo no, I didn't see that. Thanks very much, that's exactly what I wanted. Thank you!
