### ISSUE TITLE
PXT micro:bit emulation in editor

### ISSUE THREAD

**Issue by d-f-booth** [Microsoft/pxt#1349]
The following PXT script works when flashed to a micro:bit but does not work in the editor's emulation.

The script causes a base 6 count using LED's in column x = 1 to increase downward every time pin P0 is connected to 3V.  When all 5 LEDs are lit the next P0 pulse causes all 5 LEDs in column x=1 to extinguish and LED in column x=0 y=0 to light. Then another 5 LEDs are lit one by one in column x =1. On the real micro:bit this is achieved by the transistor part of a proximity sensor shorting +3V to P0 and it works well.
A flag "P0 ON Flag" is used to prevent continued illumination of the transistor triggering any further counts until P0 has gone back to zero.

On the emulation the first pulse is recorded with LED at (1, 0) coming on when the P0 tab is clicked.  The Tab shows 0 then goes to 1 and turns orange.  No other clicks on P0 cause the count to progress presumably because the emulation never sees the P0 pin drop to zero as it does in the real set up.

So you could argue that the emulation is not at fault but there is a need for P0 in the emulation to be pulled down to zero.  I tried using pull up and pull down blocks which were not strictly needed for the real micro:bit but these did not work.

Is there a case for a left click on the pin to be a +3V applied and a right click on the pin to be a zero level applied to the pin?  Or is there a fault in the emulation because it does not fall back to zero after the left click?  Or is there some other procedure?

I have attached a zipped version of the script which is an extract from the original code.
Extract

![image](https://cloud.githubusercontent.com/assets/24459314/22940279/408917ec-f2d9-11e6-9207-81a66445dcbe.png)

[microbit-LapCounterExtractToShowEmulatorError.zip](https://github.com/Microsoft/pxt/files/774816/microbit-LapCounterExtractToShowEmulatorError.zip)

**Comment by d-f-booth** [comment]
Sorry the bottom of the script was obscured by a comment here it is again without the comment

![image](https://cloud.githubusercontent.com/assets/24459314/22940512/061ae580-f2da-11e6-83b1-742a45c08587.png)

**Comment by pelikhan** [comment]
Please share the javascript.

**Comment by abchatra** [comment]
Repro shared in the zip of the original comment

**Comment by abchatra** [comment]
The microbit issues have moved to https://github.com/Microsoft/pxt-microbit repo. 
If this is still an issue please open the issue in that repo or let us know, we will reopen in that repo.
