### ISSUE TITLE
Show icon enhancement

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1361]
This is an enhancement, but would love to have a way to cycle through Tom's awesome pre-built icons.
![show_icon](https://cloud.githubusercontent.com/assets/22108954/23080809/1c12f452-f507-11e6-9d88-0e46bdcb5a47.PNG)

**Comment by microsoftsam** [comment]
You can do it easily through javascript, as the enum is just a number.

**Comment by microsoftsam** [comment]
```
let item = 0;
input.onButtonPressed(Button.A, () => {
    basic.showIcon(item)
    item++;
})
```

**Comment by pelikhan** [comment]
Should be added to "code snippet" doc page

**Comment by abchatra** [comment]
This is doable in Javascript. Won't fix in Javascript
