### ISSUE TITLE
Sim toolbar - muting icons

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1363]
Are a bit confusing... I would expect the mute button to have a slash through it or something.
Mute: 
![mute](https://cloud.githubusercontent.com/assets/22108954/23081059/1b8d54fe-f508-11e6-979b-f2bff5329f22.PNG)
Unmute: 
![unmute](https://cloud.githubusercontent.com/assets/22108954/23081070/24dfc5c8-f508-11e6-8666-85ef828d3e7d.PNG)

**Comment by microsoftsam** [comment]
Fixed.
