### ISSUE TITLE
Fat Copy button

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1366]
The copy button for embed doesn't look great.  Can we make it the same size as the URL Copy button?
![copybutton](https://cloud.githubusercontent.com/assets/22108954/23081229/bad6c630-f508-11e6-9989-c46d2caffb65.PNG)

**Comment by microsoftsam** [comment]
The button is attached to the text area next to it, if we remove that attachment I'm afraid it would look weird and not connected. The button takes the same height as the attached content.

**Comment by abchatra** [comment]
Embed view is hidden. Won't fix for now.
