### ISSUE TITLE
Share dialogs: Missing close X

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1367]
No close dialog button in top right corner of the Share dialogs.
![sharedialog1](https://cloud.githubusercontent.com/assets/22108954/23081461/c048dda0-f509-11e6-8ea0-4b61537df47a.PNG)

![sharedialog2](https://cloud.githubusercontent.com/assets/22108954/23081466/c5cb235a-f509-11e6-886a-e9c36a86a3cd.PNG)

**Comment by microsoftsam** [comment]
Fixed by projects dialog change. #1373
