### ISSUE TITLE
Search results change after going through getting started tutorial

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#1368]
If you do the getting started tutorial and then return to the main editor, searching causes the toolbox to temporarily revert to the toolbox of the last tutorial step and display fewer results.

**Comment by microsoftsam** [comment]
Can't repro locally. Could you check if this is still an issue?

**Comment by microsoftsam** [comment]
@riknoll does this still repro?

**Comment by riknoll** [comment]
Still repros for me in Edge and Chrome. You need to go through the whole tutorial (every step and click finish)

**Comment by microsoftsam** [comment]
I see, I'll give that a go.
