### ISSUE TITLE
Pin 5 appears in analog read pin twice

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1374]
microbit.org-ticket: 1129
site: pxt.microbit.org/beta

pin 5 appears twice - should the second entry be pin7??

![screen shot 2017-02-20 at 00 03 30](https://cloud.githubusercontent.com/assets/4086785/23108112/2df787a0-f700-11e6-8803-3f947a73823d.png)

**Comment by riknoll** [comment]
Fixed in master
