### ISSUE TITLE
Launch PXT with javascript instead of Blocks

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1376]
We see that some teachers want to start with text-based coding not blocks (for example, for older children) and a way to launch PXT directly to the Javascript Editor would be great.

**Comment by microsoftsam** [comment]
We could add another card in the projects dialog: "New Javascript Project"

**Comment by OwenBrotherwood** [comment]
https://pxt.microbit.org/75837-34664-43430-24077 shows that if one shares when in javascript mode, it is indeed shared in javascript with edit also going into javascript.
Not a solution as such, just an observation.

**Comment by jaustin** [comment]
@microsoftsam @pelikhan we're looking at our 'code' page to align with upcoming RC and would like to know if there's an entrypoint straight to 'new project in JS' yet or whether we should publish an empty JS script and go from there (would prefer not to do that as it's a bit of a hack!)
J

**Comment by pelikhan** [comment]
- Are you looking at opening a JS-only project?
- Do you want to force create a new project or just open an existing one?

**Comment by jaustin** [comment]
Good question: I think the equivalent behaviour to visiting pxt.microbit.org and then clicking 'js' as soon as I arrive

**Comment by pelikhan** [comment]
I guess we could have a "#javascript" route that handles that.

**Comment by abchatra** [comment]
This is won't fix for now.
