### ISSUE TITLE
Error messages for unsupported JavaScript features

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#138]
Currently if you attempt to use an unsupported JavaScript feature you'll see an error message like 'Unsupported syntax node: ForOfStatement'. Ideally these error messages would give slightly friendlier descriptions, e.g. 'for (let ... of ...) loops are not supported'.

**Comment by mmoskal** [comment]
I believe @thomasdenney has fixed this

**Comment by pelikhan** [comment]
Needs to be tested with Monaco integration

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________
