### ISSUE TITLE
Packages doc on pxt.microbit.org/packages points to 404

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1382]
On https://pxt.microbit.org/packages there's a link to a CPP example 
https://github.com/Microsoft/pxt-microbit-cppsample

This 404s

**Comment by microsoftsam** [comment]
Link is fine, repro is private.

**Comment by jaustin** [comment]
Well, I guess then either we should change the link to a public repo or make the existing repo pubic :). To all intents and purposes it's still a 404!

**Comment by microsoftsam** [comment]
Sorry @jaustin that response wasn't really pointed at you :) I was more trying to add more info to the bug (for @abchatra and @pelikhan).

**Comment by jaustin** [comment]
Any news on this? It's still 404 for me.

**Comment by microsoftsam** [comment]
@abchatra @pelikhan can we make this public: 
https://github.com/Microsoft/deprecated-pxt-microbit-cppsample
or remove the reference to it from the docs.

**Comment by pelikhan** [comment]
Removed reference.
