### ISSUE TITLE
Variable capture in inner lambda

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#140]
The following function fails to compile, with the error message `cannot find captured value: a`. 

```typescript
function f() {
    let a = 0
    let g = () => {
        let h = () => {
            basic.showNumber(a)
        }
        h()
    }
    g()
}
```

I believe that the when creating the lambda `g` it ought to recursively check any lambdas inside `g` to determine if they capture any variables in the scope of `f`, but I suspect this could lead to leaks if not handled correctly.

**Comment by mmoskal** [comment]
Need a loop `getEnclosingFunction` and for every one use `getFunctionInfo` to add `v` to `capturedVars` in `recordUse()`
