### ISSUE TITLE
pxt after a few days tries to 'phone home' to Microsoft and wont load

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1404]
I was using pxt in a workshop on Thursday and it worked fine from the browser cache without any internet access.

Saturday morning at a computer club I tried it again with no internet turned on, it started to load the window then a black window with a micro:bit logo appeared saying 'loading' and I could not get into the editor. We have no internet access here, so the workshop failed.

Can someone look at why PXT is sometimes trying to 'phone home' back to Microsoft, which makes it completely non functional as an offline experience. The duration between 'it worked before' and 'it now no longer works' is not known, but It seems to be about 5-7 days.

Can someone look into this? Thanks!

**Comment by pelikhan** [comment]
Did the user clear the browser cache?
Could you collect the javascript console output and network log in that browser?

**Comment by DavidWhaleMEF** [comment]
I've not seen this since that particular event. Let's close this for now, and I'll re-report it if I see it again.
