### ISSUE TITLE
some strings for hover help not localizable

### ISSUE THREAD

**Issue by ukkari** [Microsoft/pxt#1415]
The following UI strings for the hover help don't seem to be localizable. 

![image](https://cloud.githubusercontent.com/assets/922729/23346867/7ba30bb4-fce1-11e6-935c-920de28ba0d4.png)
![image](https://cloud.githubusercontent.com/assets/922729/23346874/87433b1a-fce1-11e6-88a1-fe246c7ef364.png)
![image](https://cloud.githubusercontent.com/assets/922729/23346879/9639da3e-fce1-11e6-9dae-9078484f3e90.png)
![image](https://cloud.githubusercontent.com/assets/922729/23346886/a23e245c-fce1-11e6-9676-9b7a1f4f68c9.png)
![image](https://cloud.githubusercontent.com/assets/922729/23346894/bc43ab38-fce1-11e6-9acf-92afe6dde291.png)
![image](https://cloud.githubusercontent.com/assets/922729/23346899/c707fc9a-fce1-11e6-8ce4-814c7093242c.png)
![image](https://cloud.githubusercontent.com/assets/922729/23346902/cca68a5e-fce1-11e6-84a2-2a15327df59a.png)
![image](https://cloud.githubusercontent.com/assets/922729/23346911/d795a224-fce1-11e6-963f-7aee946c5bb3.png)

**Comment by pelikhan** [comment]
The strings are there, it's a bug on our side. Fix coming up.

**Comment by abchatra** [comment]
fixed
