### ISSUE TITLE
branched releseases

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1418]
We need the ability to support branches releases for PXT and PXT targets.

- [ ] uploading PXT releases for non-master branches
- [ ] uploading target releases for non-master branches
- [ ] versioned crowdin translation files

**Comment by tballmsft** [comment]
Importance, given we are getting close to needing pxt branch (Michal's floating point work)?

**Comment by abchatra** [comment]
We have release branches for Microbit. This is fixed.
