### ISSUE TITLE
Safari downloads hex files without extension, upload is not detected as hex

### ISSUE THREAD

**Issue by thinkberg** [Microsoft/pxt#1421]
Maybe infer the file format from the header of the file?

https://calliope-mini.myjetbrains.com/youtrack/issue/MINI-37

**Comment by abchatra** [comment]
This is fixed.

**Comment by martinwork** [comment]
@abchatra What is fixed? I tried Safari on macOS: the file is still saved as Unknown with no extension and PXT Import file won't load it, unless the hex extension is added manually.

The dialogue that shows as the file is downloaded doesn't seem to do anything useful, except for the Help button. The help linked to is quite confusing as it has references to PC and .hex file - even on the page linked via "Mac - Safari" - without any reference I could find to the file naming issue.

**Comment by abchatra** [comment]
I got confused with a different bug fix with respect to extension. I will revalidate.

**Comment by martinwork** [comment]
I am also confused now @abchatra !

I thought this was a Safari limitation as @pelikhan states in #1855.

But, having logged out of microbit.co.uk and cleared the browser history, I just created new scripts in macOS Safari 10.1 with Block Editor and Touch Develop. Both were saved with filename matching the script title and extension .hex.

**Comment by pelikhan** [comment]
Things are bit more complicated on iPhone. We noticed that use the file download redirect, Safari had the bad habit of closing the indexeddb database so any editing would fail upon returning to the page. Currently, we use another technique (open the datauri in an iframe) to trigger the download in safari. This technique does not support the "download" attribute.
Probably worth reinvestigating as these things tend to change.

**Comment by martinwork** [comment]
macOS - not iPhone.

**Comment by abchatra** [comment]
I can repro this on Safari. I will take a look.

**Comment by jaustin** [comment]
I think this is still an issue, safari doesn't append .hex to the file in MakeCode and as a result the micro:bit times out when it's being flashed. In most cases this does actually work but the fail.txt message is confusing. This should be addressed in future DAPLink but given the number of deployed devices that won't be updated, it'd be really great to have ".hex" appended by Safari

**Comment by microsoftsam** [comment]
Safari v10.1 now supports the download attribute.
