### ISSUE TITLE
IE 11 - Tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1431]
Last step of Tutorial doesn't show the Toolbox, and doesn't enable the Back or Finish buttons.
![tutorial](https://cloud.githubusercontent.com/assets/22108954/23383962/9f4ee7e2-fcfd-11e6-83f8-718b4bf69a19.PNG)

**Comment by abchatra** [comment]
Works fine for me on Firefox. I assume this is IE11 specific
