### ISSUE TITLE
Enhancement: inline blocks in Tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1433]
Just looks a bit strange... small text with lots of whitespace below.  Can we make this bigger or centered to fill out the space?
![tutorial inline blocks](https://cloud.githubusercontent.com/assets/22108954/23384007/d66c8662-fcfd-11e6-8745-98c5e32bbb01.PNG)

**Comment by pelikhan** [comment]
A little animated gif would fit nicely

**Comment by abchatra** [comment]
This is fixed with the new getting started feature.
