### ISSUE TITLE
Full screen simulator cutoff

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1436]
In full-screen, the simulator gets cut off on the top and bottom on shake.
![fullscreensim](https://cloud.githubusercontent.com/assets/22108954/23384421/beae28e4-fcff-11e6-897c-f4fce7494985.png)

**Comment by pelikhan** [comment]
Fixed.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/commit/c26a81dee9c67c61edf4aa73dcc20d43de319155
