### ISSUE TITLE
Code projects need to have description.

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1437]
![image](https://cloud.githubusercontent.com/assets/6107272/23384926/d3a70494-fd01-11e6-81e5-8bf90edb83ec.png)

**Comment by pelikhan** [comment]
Fixed by https://github.com/Microsoft/pxt-microbit/commit/b2282b1a81ec880770e93b8bb7af2501c6a40756

**Comment by pelikhan** [comment]
Note: animated .gif / images would be best
