### ISSUE TITLE
Allow oembed object to show simulator if I use the right URL

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1447]
(this may already be implemented but I couldn't find it playing with URLs)

I'd like to be able to generate a link that oembeds with a simulator image (animated?) rather than just a pxt picture.

For example I'd like pasting in:
https://pxt.microbit.org/---run?id=03010-16341-03311-22810

I'd like the oembed or other preview to be a full page simulator.

**Comment by pelikhan** [comment]
The oEmbed preview contains a full editor, including the simulator.

**Comment by pelikhan** [comment]
Screenshot of simulator is probably doable, animation is just tricky. It's not a gif cannot be generated, but it is not obvious when to start recording.

**Comment by pelikhan** [comment]
@jaustin not sure exactly what you want now...

**Comment by abchatra** [comment]
We have full OEmbed support. This issue is fixed.
