### ISSUE TITLE
projects dialog issues

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1449]
- [ ] "Create New" is rather useless. IMO should be scraped.
![image](https://cloud.githubusercontent.com/assets/4175913/23406032/d76b4eb2-fd71-11e6-86f3-66d9b305bb94.png)

- [x] spacing between categories is uneven and almost overlaps.
![image](https://cloud.githubusercontent.com/assets/4175913/23406056/f0f86fea-fd71-11e6-803a-02d4ac2c6b80.png)

- [x] no minimal hight defined on the dialog. When loading, the gearwheel overlaps the menu.

- [x] still a box in a box
![image](https://cloud.githubusercontent.com/assets/4175913/23406102/2e5acb76-fd72-11e6-80f6-1824031fa80e.png)

- [ ] does "blur" work on low-end machine/browsers?

**Comment by abchatra** [comment]
@pelikhan  Did you try beta? I don't see a box in a box nor the spacing issue

**Comment by pelikhan** [comment]
my bad... checked the ones that are already fixed.

**Comment by microsoftsam** [comment]
Same.

**Comment by microsoftsam** [comment]
we can disable blur in light mode.

**Comment by microsoftsam** [comment]
I do have a min height set, let me know if that's not the case with what you're seeing.

**Comment by microsoftsam** [comment]
Can remove Create New.

**Comment by pelikhan** [comment]
Ooops, minimal height ok too. Must have been the damn half compiled CSS.
