### ISSUE TITLE
support for multiple boards in same target

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#145]
To avoid code duplication, a user should be able to swap between micro:bit / arduino at will.

**Comment by tballmsft** [comment]
It is not clear that this is the best user experience. We may want to have a different URL for Arduino. We can still avoid code duplication. Adding more ways for users to get confused in codethemicrobit.com should be avoided, especially if the experience strays from the micro:bit.

That said, I could see how you might argue that the current Arduino support is very much a micro:bit experience.   Let's discuss more before implementing.
