### ISSUE TITLE
micro:bit "standalone" is cut with full screen 

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1452]
https://pxt.microbit.org/---run?id=03010-16341-03311-22810

chrome full screen laptop

![image](https://cloud.githubusercontent.com/assets/866122/23407585/f8e81306-fdc4-11e6-8775-06ba328c09ae.png)

chrome window

![image](https://cloud.githubusercontent.com/assets/866122/23407623/24a7edb8-fdc5-11e6-8192-60e0ae548178.png)

**Comment by pelikhan** [comment]
This is because the embedded iframe have a given aspect ratio and do not automatically rescale to the container.

**Comment by pelikhan** [comment]
We should probably generate the HTML code to generate a resizable iframe.

**Comment by pelikhan** [comment]
There is no easy fix for this. iframe are notoriously hard to autoscale. Won't fix.

**Comment by OwenBrotherwood** [comment]
Yep: I agree.
