### ISSUE TITLE
add package button does not respond

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1459]
I don't know what the reason is, so it is hard to describe exactly how to reproduce, but I sometime get that clicking on the add package button does not do anything (except for the color flash of the button itself). Reloading the page does not fix it. Starting a new project does not fix it. I don't see anything the in the browser console. I'm using a recent version of Firefox on windows. 

It's an annoying enough bug that I feel I have to report it. I'll come back with more details if I figure out more how to reproduce it.

**Comment by nielsswinkels** [comment]
Seems like it only happens when you use swedish as language:
https://pxt.microbit.org/?lang=sv-SE

I don't get the bug in other languages.

**Comment by abchatra** [comment]
I can repro this.

**Comment by microsoftsam** [comment]
Also no icon in the monaco toolbox: 

![screen shot 2017-02-28 at 2 37 55 pm](https://cloud.githubusercontent.com/assets/16690124/23437604/899a77f6-fdc3-11e6-9ec7-b644b0fb7e56.png)
