### ISSUE TITLE
add package dialog removes parts of the interface

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1461]
after opening and closing the add package dialog, the drawer/menu and block editor field are completely blank. Refreshing the page fixes it. See this video:

https://www.youtube.com/watch?v=YnQ4VeeobFE&feature=youtu.be

Firefox on windows.

**Comment by pelikhan** [comment]
Could it be that blurr is messing up FF?

**Comment by abchatra** [comment]
I can repro this on firefox as well

**Comment by pelikhan** [comment]
Fails in all browsers for me.
