### ISSUE TITLE
Deleting a project doesn't do anything

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1466]
•	Navigate to https://pxt.microbit.org/beta 
•	Create a new project and named “test1”
•	Click ‘Delete Project’ in setting
•	A pop up window shows and click Delete
•	New project page pops up and click Close.

Expected result:
The ‘test1’ project should be deleted and show the default page

Actual result:
The ‘test1’ project couldn’t be deleted except you click another project on the New 
Project page

**Comment by microsoftsam** [comment]
What browser? Works on chrome, it pops up a dialog and lets you select what you want to do next.

**Comment by Helen09** [comment]
Not repro anymore and after you delete the project the default page shows up
