### ISSUE TITLE
add `for ... of` statements

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#147]
another good one to add for students.

**Comment by thomasdenney** [comment]
I'm experimentally adding support for this, see work in progress https://github.com/Microsoft/pxt/compare/for-of-statements?expand=1

**Comment by thomasdenney** [comment]
The branch linked above now supports for...of statements, although I need to do much more testing (e.g. for memory leaks)

**Comment by mmoskal** [comment]
Good work! A couple comments:

* `refSuff` is for `refSuffix` not `refStuff` ;)
* for the uniqueName() use a global counter, something like:

```
+        constructor(public index: number, public owningProc: Procedure) {
+            super(index, null, null)
+            this.uid = globalCounter++
+        }
+
+        getName() {
+            return "tmp" + this.uid
+        }
+
+        uniqueName() {
+             // 'T' makes sure it doesn't clash with real cells
+            return this.getName() + "___T" + this.uid
+        }
```

**Comment by thomasdenney** [comment]
@mmoskal Thanks :). I'll make these changes shortly.
