### ISSUE TITLE
Can't Import Files in PXT for Micro:bit

### ISSUE THREAD

**Issue by harveytwyman** [Microsoft/pxt#1470]
Selecting **Projects/Import File** should open the file browser to select your hex file. IT DOESN'T ANYMORE on this Latest Version! Previous versions were fine. I've tried with Chrome and Edge browsers. Both are BROKEN. I've cleared the browser's cache, but no different.

PLEASE FIX ASAP as package is UNUSABLE as it is.

Thanks.

**Comment by abchatra** [comment]
We looking it right now

**Comment by abchatra** [comment]
As a workaround, you can drag & drop the hex file into the editor. (Until we fix the issue)

**Comment by microsoftsam** [comment]
Fixed in beta.
