### ISSUE TITLE
Can't use Sonar and Radio packages together! 

### ISSUE THREAD

**Issue by harveytwyman** [Microsoft/pxt#1475]
Incorporating "radio" with "sonar functions" in the PXT micro:bit  package causes the sonar to stop working.  Both work independently. 

Could they be using shared timing functions?

**Comment by pelikhan** [comment]
Could you share a repro?

**Comment by harveytwyman** [comment]
Sorry,  what's a "repro"?

**Comment by pelikhan** [comment]
An example of code that **repro**duces the issue. (JavaScript sources best).

**Comment by pelikhan** [comment]
You might also have more luck at https://support.microbit.org/support/home

**Comment by harveytwyman** [comment]
If you try using the sonar and radio functions the sonar stops working. 

All I want to know has anyone tried doing this. 

I spotted this problem on my buggy.  The remote micro:bit controls the motion of the buggy wheels successfully. However the buggy also has 2 sonar sensors which work as "collision avoidance " on it's own.  However the sonar doesn't work when combined with the radio remote control. 

Has anyone had this problem? 

Comments please.

**Comment by abchatra** [comment]
Please share the repro if you see this. Closing till then
