### ISSUE TITLE
Filesystem Functions Not Working In the Block Editor

### ISSUE THREAD

**Issue by harveytwyman** [Microsoft/pxt#1476]
No files are created on the Micro:bit. The examples simply don't work. 

These files should be viewable on Windows 10, right?

**Comment by pelikhan** [comment]
In order to view files on Windows 10, you will need a special bootloader that is not currently publicly available. You should be able to read the files from the micro:bit itself.

**Comment by pelikhan** [comment]
You will also find a great FAQ at https://support.microbit.org/support/home

**Comment by harveytwyman** [comment]
Until this "special bootloader" is available how can I get data off the micro:bit's files created? 

Sending the files via serial is possible but would be simpler to read them directly. 

How can I access this "special bootloader"?

**Comment by tballmsft** [comment]
Contact Joe Finney from Lancaster University: @finneyj
