### ISSUE TITLE
Vertical scroll bars on Project dialog

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1487]
In 1280 x 768, on IE11, Project dialog doesn't have a way to scroll down to see all the projects.

**Comment by pelikhan** [comment]
Screenshot?

**Comment by Jaqster** [comment]
<img width="640" alt="scrollbars" src="https://cloud.githubusercontent.com/assets/22108954/23484464/f4834e9e-fe8b-11e6-8a07-388a70b0ce28.PNG">

**Comment by abchatra** [comment]
I can repro this.

**Comment by abchatra** [comment]
fixed
