### ISSUE TITLE
Filesystem Functions Not Working

### ISSUE THREAD

**Issue by harveytwyman** [Microsoft/pxt#1495]
The filesystem functions on "https://pxt.microbit.org/beta" NOW WORKS CORRECTLY. 

I tested it on a single file with 5000 values stored - No Errors! 

I tested it with 2 files open at the same time - No Errors! 

It now retains all the data correctly AFTER the micro:bit's power is removed, turned on again and reset. 

This filesystem bug in my opinion has now been corrected. 

Please schedule the modifications for upgrade into the main version ASAP. 

Thank you. 

Harvey

The only way to know if you're saving a file on the micro:bit is by sending it to the serial.

Nothing is transmitted! Other serial strings are seen from the code but NOTHING from filesystem. 

The BETA version also produces nothing. 

Has anyone got it working? 

You MUST have this function operational, otherwise you can't use the micro:bit as a "data logger" which is what most schools will use the micro:bit for.

**Comment by pelikhan** [comment]
Please use support.mocrobit.org to voice this concern.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by harveytwyman** [comment]
In the code below "Hi" is seen in TeraTerm on the PC but nothing from the "filesystem" functions.

input.onButtonPressed(Button.A, () => {
    files.appendLine(
        "output.txt",
        "hello"
    )
})
input.onButtonPressed(Button.B, () => {
    basic.showString("H")
    files.readToSerial("output.txt")
    serial.writeString("Hi")
})

**Comment by abchatra** [comment]
Fixed. Please use the new filesystem package. Not it is still in beta.

**Comment by DavidWhaleMEF** [comment]
microbit.org-ticket: 1229

**Comment by DavidWhaleMEF** [comment]
The Filesystem Functions work better but are not totally reliable.

The file does now get created in the micro:bit and data can be read back out. However there are random corruptions of the data being read out.

e.g. A Decrementing Number Sequence stored would output via the "File Read to Serial Function" as

211 
ÿÿ-ÿ209 
208

the number 210 is replaced by ÿÿ-ÿ

Sometimes you get this:

127 
MICROBIT_FS_1_0@ÿ121 
120

which has corrupted several data points.

The files can be read out many times BUT a Reset or Power Down will clear the data.

I seem to remember reading that the data file was kept in EEPROM and NOT destroyed by a Reset or Power Down. Can someone please confirm that this statement is true?

**Comment by DavidWhaleMEF** [comment]
repro code has been requested from customer

**Comment by finneyj** [comment]
Tried to repro in C but seems ok. See details here:
https://github.com/lancaster-university/microbit-dal/issues/286

**Comment by finneyj** [comment]
p.s. for information, the ```MICROBIT_FS_1_0``` is a bit of MAGIC used to identify the root file system directory. Hard to imagine how that could end up in a user data stream.

**Comment by DavidWhaleMEF** [comment]
repro case from user:

The code below corrupts around every 50 numbers. However by playing with the For Loop Count, the corruption changes randomly.

Also for some reason it HAS TO HAVE a DELAY just before it starts writing to the file the first time ( As commented in the code below ). 

I use TeraTerm to view the serial data.

```
let ay = 0
let file = ""
input.onButtonPressed(Button.A, () => {
    // NEEDS A DELAY HERE!
    //
    // EVEN CORRUPTS THE SMILEY FACE AND THEN CRASHES WITHOUT IT!
    basic.pause(1000)
    basic.showIcon(IconNames.Happy)
    for (let i = 0; i < 250; i++) {
        files.appendNumber(
            file,
            ay
        )
        ay += -1
        files.appendLine(
            file,
            ""
        )
    }
    basic.showIcon(IconNames.Yes)
})
input.onButtonPressed(Button.B, () => {
    file = "data.csv"
    files.readToSerial(file)
})
file = "data.csv"
ay = 250
```

**Comment by DavidWhaleMEF** [comment]
We suspect customer is trying this on live and not on beta. Although to be clear, I had though that this fix had already surfaced to live myself, it wasn't overly clear from the discussion chain.

I have asked customer to re-test on beta.

Is this fix tagged to go out to live yet do we know, and when do you think it will surface, just in case someone else reports the same issue? Thanks!

**Comment by pelikhan** [comment]
We are waiting on the doctor who show before pushing a new release.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DavidWhaleMEF** [comment]
@pelikhan ah, great - thanks for looking out for us :)

I think there are 3 planned releases, weekly, from Monday 24th - one new activity each week. All content is web based this time from what I understand.

**Comment by DavidWhaleMEF** [comment]
from customer:

attached is my .hex file that STILL produces the errors. As suggested I drag and dropped my .hex and "Downloaded" to recreate it.

I used the BETA compiler AND the BETA version of the FileSystem. I also tested it on the Release version of the FileSystem as well but the same.

I have noticed that the Smiley Face displayed "Flickers" during the storing process.

**Comment by DavidWhaleMEF** [comment]
[microbit-Send-Data-to-File-Latest.hex.zip](https://github.com/Microsoft/pxt/files/949845/microbit-Send-Data-to-File-Latest.hex.zip)

**Comment by DavidWhaleMEF** [comment]
@abchatra can you re-open this ticket again please, it is still unresolved in the eyes of the customer. Thanks

**Comment by DavidWhaleMEF** [comment]
Definitely broken still. I rebuilt in beta and ran, and this is what I get when I press B after running the press A process...

![whaley](https://cloud.githubusercontent.com/assets/25079586/25315689/35ba0f1c-2851-11e7-9d39-482f72e75e12.png)
[microbit-defo-beta.hex.zip](https://github.com/Microsoft/pxt/files/949874/microbit-defo-beta.hex.zip)

**Comment by DavidWhaleMEF** [comment]
ping - do we know yet if this is a DAL issue or a PXT issue? Ta!

**Comment by DavidWhaleMEF** [comment]
ping - is there any progress on diagnosing this issue yet? Is it a DAL issue, or is it a PXT issue, have we narrowed that down yet do you know? Thanks!

**Comment by pelikhan** [comment]
I beleive this is a DAL issue (with potentially feature interaction issue as well with PXT).

Has there been progress in provide a bootloader that exposes the files in the MSD interface? Both features go hand in hand.

**Comment by DavidWhaleMEF** [comment]
@pelikhan Is there a ticket in lancaster microbit-dal for 'provide a bootloader that exposes the files in the MSD interface'? If not, then there is no way it can progress. If there is one that you know of, can you link it here please? @finneyj any visibility on Peli's request from your end?

**Comment by pelikhan** [comment]
David, the foundation should be driving this kind of end to end scenario. Without MSC access to the file generates on the device, the kids would not be able to read back the data.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DavidWhaleMEF** [comment]
Sure, agreed. @finneyj polled in same request, as it's on his shoulders to make that bit work I think! If there is not an appropriate ticket logged for the task, then I will make sure it gets logged so that it is kept on the radar.

**Comment by finneyj** [comment]
Folks, think I've found this issue, as cited above.

As an aside, the way PXT currently uses the FS is pretty intense - every write operation is a create/append/close operation... and the sample above does this three times for each file entry (once for the value, once for a null string, once for a CRLF. e.g. the sample code above causes about a dozen write/erase cycles. Not terrible given a micro:bit is rated to about 20k cycles, but an optimal use of the APIs that experiences developers would write would cause no erase cycles at all...

I like the stateless nature of this for kids, but I wonder if there's something we could do to reduce overhead? If not, I'll  make a note to see if we can optimize the file system a bit more for this kind of pattern. The hotspot is on the directory entries - which need to record file length etc, so get churned each time you close a file.

**Comment by pelikhan** [comment]
Happy to chat about a more sustainable API.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DavidWhaleMEF** [comment]
Confirming with customer whether this patch in beta works for them: https://github.com/lancaster-university/microbit-dal/pull/293

**Comment by DavidWhaleMEF** [comment]
@harveytwyman can you try pxt.microbit.org/beta with your script and see if the problem is fixed, and report back here? Thanks

**Comment by harveytwyman** [comment]
The filesystem functions on "https://pxt.microbit.org/beta" NOW WORKS CORRECTLY. 

I tested it on a single file with 5000 values stored - No Errors! 

I tested it with 2 files open at the same time - No Errors! 

It now retains all the data correctly AFTER the micro:bit's power is removed, turned on again and reset. 

This filesystem bug in my opinion has now been corrected. 

Please schedule the modifications for upgrade into the main version ASAP. 

Thank you. 

Harvey

**Comment by finneyj** [comment]
That's great - thanks for confirming and feeding back @harveytwyman.
