### ISSUE TITLE
Closing setting-tabs

### ISSUE THREAD

**Issue by Carlborg** [Microsoft/pxt#1498]
Hi,
For the microbit block editor there are multiple "cog-wheel" settings that open a new window.
Intuitively I always want to close these windows by clicking outside of the settings window, but this doesn't work and keeps causing some level of frustration.

It is probably a minor thing to fix =)
Thank you!

**Comment by abchatra** [comment]
I can't repro this. Can you please share a screenshot?

**Comment by Carlborg** [comment]
What I mean is that I would like to be able to close this window by pressing anywhere outside of the window, rather than having to exactly press the small cogwheel again.

![screen shot 2017-03-02 at 21 51 59](https://cloud.githubusercontent.com/assets/3727690/23546432/d50adbde-ffff-11e6-9c97-2bd3f0ee6155.png)

**Comment by abchatra** [comment]
@Carlborg Thanks! Got it.

Though this is blockly feature (or bug, depends on how one sees it). Blockly is the open source framework we use from our end. Can't fix from our end.

**Comment by pelikhan** [comment]
We should fix it. This is really annoying.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Assigned to you @pelikhan

**Comment by pelikhan** [comment]
Yup I've been bugged by that one too.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Won't fix for now as we at rethinking if\else blog in a different way.
