### ISSUE TITLE
PXT enhancements and bug fixes

### ISSUE THREAD

**Issue by kenyoncoder** [Microsoft/pxt#1499]
Would it be possible for the main screen of PXT to include the current version and release date, together with a link to some easily understood (for ordinary users like me!) release notes detailing fixes and enhancements?

**Comment by pelikhan** [comment]
If you go to the "about" page,
![image](https://cloud.githubusercontent.com/assets/4175913/23511982/f2974cf6-ff13-11e6-960c-6c361e26e227.png)
you'll find the link to the releases
![image](https://cloud.githubusercontent.com/assets/4175913/23511995/fa346d5e-ff13-11e6-9265-8b956be1f70e.png)

**Comment by kenyoncoder** [comment]
Thanks @pelikhan . I was aware of that; perhaps  release dates could be added? It would be very useful to know how current one's collection of PXT compiled .Hex file is. 

I await the introduction of a "release blog" with anticipation

**Comment by abchatra** [comment]
if you click on the version you can go to tag where you can see the date.

**Comment by kenyoncoder** [comment]
Thanks @abchatra. I wasn't aware of the github release and tagging mechanisms.

Very useful.
