### ISSUE TITLE
Cross-snippet scope for variables in documentation

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#150]
There are several documentation pages that have snippets that refer to variables that are defined in earlier snippets (for example, [the answers to the spinner quiz](https://codethemicrobit.com/lessons/spinner/quiz-answers)). This makes sense when a block is being introduced that is expected to be used as part of a larger program. However, the TypeScript compiler fails on these, and therefore blocks don't show for them.

This could be solved by:

* Declaring variables in every snippet (verbose, potentially confusing for students)
* Concatenating earlier snippets when compiling later ones
* Adding support for an invisible prefix snippet that declares variables, allowing it to compile

@tballmsft  @pelikhan I think this falls into either of your domains depending on the solution.

**Comment by pelikhan** [comment]
The documentation renderer currently treats all snippets as independent so option #3 would be the best solution. Some kind of region in TS to make code as "hidden".
