### ISSUE TITLE
integration with embed.ly

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1500]
Embed.ly is used by many content provider, including medium.com, to provide a unified way to include 3rd party iframes.

* http://embed.ly/providers/new

We already meet most of the requirements, the responsiveness has to be investiated.
![image](https://cloud.githubusercontent.com/assets/4175913/23512312/0bea31c2-ff15-11e6-8955-8fcc8b3c34fd.png)

**Comment by microsoftsam** [comment]
@pelikhan what are our oembed endpoints?

<img width="990" alt="screen shot 2017-08-18 at 9 19 30 am" src="https://user-images.githubusercontent.com/16690124/29467736-64a5eab6-83f6-11e7-8e6e-7cc51b65f954.png">

**Comment by microsoftsam** [comment]
Filed a request. Waiting to hear back from the embedly team.

**Comment by microsoftsam** [comment]
Response from the embedly team: 

```
We will need a few small updates to support this:

* add width, height attributes to oEmbed response
* remove div wrapper around iframe in "html" attribute 
* set width and height attributes on iframe to match oEmbed response

e.g. 
html:'<iframe src="https://makecode.microbit.org/#sandbox:05526-49228-18219-71208" width="800" height="600">'</iframe>
width:800
height: 600


```

@pelikhan do you think these changes would interfere with OneNote oembed support?

**Comment by samelhusseini** [comment]
This is complete: http://embed.ly/provider/makecode

**Comment by samelhusseini** [comment]
Here's a sample on medium: 
https://medium.com/@samel/sample-microbit-embedly-7e04558b0fad

@Jaqster @abchatra

**Comment by samelhusseini** [comment]
and here's a list of all embedly consumers: http://embed.ly/customers
