### ISSUE TITLE
Corruption when loading old micro:bit PXT script to new PXT release

### ISSUE THREAD

**Issue by DFBREB** [Microsoft/pxt#1502]
Hi
I have strange results while testing  PWM features on new PXT release
[microbit-Radio-Tx-P0M2.zip](https://github.com/Microsoft/pxt/files/814646/microbit-Radio-Tx-P0M2.zip)
.

I have loaded to the new PXT, three hex files created on 28 Dec 2016.

1. The first Receiver script loaded into PXT editor correctly.  It had an analogue out pin 1 that I really wanted to be pin 8 so I edited the change. It compiled and was flashed to the 1st micro:bit correctly and its LEDs behaved as expected.  Testing pin 8 with a LED it is certainly variable in brightness so without using a scope I would say PWM is working on pin 8. (I have no Kitronik Breakout board until next week to test properly using the 'scope).

2.  The problems occurred when I tried to load the two 28/12/16 transmitter hex files to the PXT editor.  In both cases the JavaScript was highly corrupted  see image of screen below when I converted to block code.  When loaded as block code the group and power blocks were missing.  It seemed like the On Start block had been dropped. I was about to report this as a serious error when I decided to close the PXT editor and start a fresh instance of it.  To my surprise the main block code appeared correctly (it was not visible on the old now closed instance of PXT)  However there was some greyed out code that obviously was missing an On Start block.  I pulled out  an On Start block and slotted the start detail blocks into it.  The script then compiled and was flashed to a second micro:bit where it started interacting correctly with the previous flashed receiver script micro:bit.  

So I repeated this sequence with the second (slightly different) transmitter 28/12/16 hex file and got the same corruption using the new PXT editor.  I closed this editor down and opened a new editor and the block script appeared but with the grayed out start sequence. So I added its On Start block and it compiled, was flashed and worked as expected.

I have attached one of the original 28/12/16 transmitter hex files for you to try.  And below is the first screen after loading the same hex file.  The second image was taken immediately after the first but from a new instance of the PXT editor.

David Booth
Inline images 1

Inline images 2

**Comment by abchatra** [comment]
@pelikhan  any update on this P1 issue?

**Comment by abchatra** [comment]
The microbit issues have moved to https://github.com/Microsoft/pxt-microbit repo. 
If this is still an issue please open the issue in that repo or let us know, we will reopen in that repo.
