### ISSUE TITLE
close gear options dialog by clicking outside of it

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1507]
Please add that you can close the popup dialog that comes when you click on the blue gear icon, for example on an if block, by clicking outside the dialogbox. It is rather annoying that you have to find the tiny icon to be able to close it again. It would be the same behaviour as the "add package" dialogbox which you can close by clicking outside of it.

**Comment by abchatra** [comment]
@nielsswinkels  Can you provide a screenshot? For settings icon I do see it going away by clicking outside the editor. Also which browser are you trying this?

**Comment by abchatra** [comment]
Ok this seems to be request for changing built-in blockly feature. This is by design for us now.
