### ISSUE TITLE
Blocks cannot be used for variables declared inside lambdas

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#151]
Related to https://github.com/Microsoft/pxt-microbit/issues/149. Several examples in the documentation cannot be represented in blocks because local variables are declared inside a lambda, however are then moved to global scope by the blockly -> JS compiler.

**Comment by mmoskal** [comment]
Here are some samples:
```
input.onGesture(Gesture.Shake, () => {
    let weapon = Math.random(3)
    if (weapon == 0) {
        basic.showLeds(`
            # # # # #
            # . . . #
            # . . . #
            # . . . #
            # # # # #
            `)

    } else if (weapon == 1) {
        basic.showLeds(`
            . . . . .
            . # # # .
            . # # # .
            . # # # .
            . . . . .
            `)
    } else {
        basic.showLeds(`
            # # . . #
            # # . # .
            . . # . .
            # # . # .
            # # . . #
            `)
    }
})
```

```
basic.forever(() => {
    let degrees = input.compassHeading();
    if (degrees < 45) {
        basic.showString("N");
    } else if (degrees < 135) {
        basic.showString("E");
    } else if (degrees < 225) {
        basic.showString("S");
    } else {
        basic.showString("W");
    }
});
```

**Comment by mmoskal** [comment]
And one more:
```
while (true) {
    let x = 0
}
```

**Comment by riknoll** [comment]
I ran into this as well in #283. Compiling should probably move declarations to the lowest scope that encompasses all references.  That would take care of all the above examples, but something like this would be a decompilation error:
```typescript
// x is not declared in the lowest common scope (should be in the while block)
let x: number = 0

while (true) {
    if (something) {
        x = 7
    }
    else {
        x = 5
    }
}
```
If we want to maintain the user's declaration locations across the decompile -> compile bridge, then we will probably either have to define a "local var" block or add some metadata to the existing one.

**Comment by mmoskal** [comment]
I think we should drop the round trip test.

If the conversion to blocks succeeds, then the compilation should yield equivalent, but not necessarily identical, TypeScript. We should have some tests where it is indeed identical, but also some where it isn't.

For that to work, the decompiler should flag as error everything it cannot understand, but I think it's (almost?) there. 

CC @pelikhan

**Comment by mmoskal** [comment]
OK, I guess the 'emit errors on unknown stuff' needs some review - for example `emitForStatement()` will not flag conditions.

**Comment by riknoll** [comment]
So, most the decompiler issues are resolved and I think this is the only one that is really blocking us from removing the roundtrip. The decompiler now emits scoped declarations, but it doesn't check for colliding names. For example, this TypeScript:
```typescript
let x = 7;
{
    let x = 8;
}
let y = x;
```
will decompile to these blocks:
![bad_scope](https://cloud.githubusercontent.com/assets/13754588/19053257/f370e724-896e-11e6-9efd-a6fe8a8f863a.PNG)

That gets caught by the roundtrip right now. We should either error out on name collisions or change the local variable name

**Comment by mmoskal** [comment]
I would vote for a rename

**Comment by riknoll** [comment]
Rename should be easy enough, just need to pass the TS language service to the decompiler. I'll look into it
