### ISSUE TITLE
Error message for lambdas not returning values should be on return, not call

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#152]
Related to https://github.com/Microsoft/pxt/issues/39

```typescript
let square = (x: number) => {
    return x * x
}

let a = square(10)
```

The error message `lambda functions cannot yet return values` shows at line 5 on the call. It would make more sense for it to be on the return statement in the lambda.

Alternatively, if you declare a lambda with a return type but no return statement the TypeScript compiler complains with `A function whose declared type is neither 'void' nor 'any' must return a value`, which conflicts with the capabilities of the compiler.

```typescript
let nothing = (): number => {}
```

**Comment by mmoskal** [comment]
There is no error message anymore, as the feature is supported
