### ISSUE TITLE
file not deleted from filesystem

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt#1522]
Hello,

Files are not (reliably) deleted from the filesystem. Sometimes it works but mostly it doesn't. 

I'm guessing that the underlying c++ method is returning an error code which is not trapped by the typescript.

I think that finer grained control, like the python api is required  so that file opening and closing can be done.

It would be really nice to have that utility to manipulate the files on the microbit.

Kind Regards,

Rae

**Comment by pelikhan** [comment]
Could you share a sample?

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-filesystem/releases/tag/v0.5.1 has a fix for this issue. Currently enabled for /beta only.
