### ISSUE TITLE
firefox on ipad not supported, documentation unclear

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1524]
Today a teacher went in to pxt via firefox on a recent model ipad. We were then forwarded to a documentation page which stated that this browser was not supported. On that page it listed which browsers are support on which platform, but ipad (/ios) is not in that list. And under mac it shows firefox as supported, which is confusing as a user.

Please add "iOS (iPad & iPhone)" as a platform and list which browsers are supported on them.

**Comment by nielsswinkels** [comment]
Related issue: https://github.com/Microsoft/pxt/issues/342

**Comment by abchatra** [comment]
This if fixed. Validated in the ipad
