### ISSUE TITLE
switch blocks to javascript does not work when offline

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1525]
when offline switch from blocks canvas to javascript canvas results in the micro:bit logo "spinner" and no javascript canvas.

replication
start pxt beta with blocks canvas (online or with pxt in cache) then in offline, switch to javascript canvas

**Comment by pelikhan** [comment]
![image](https://cloud.githubusercontent.com/assets/4175913/23572630/40c6da92-0025-11e7-9357-bc2dc307e5a3.png)

**Comment by pelikhan** [comment]
![image](https://cloud.githubusercontent.com/assets/4175913/23572640/4acb2930-0025-11e7-86c9-692c2a52611e.png)

**Comment by pelikhan** [comment]
The manifest has this location which is different from the /vs/loader.js location.

https://pxt.azureedge.net/blob/507449a9a60b19c6d5e09cddcf15e0ec1d272ee4/vs/loader.js

**Comment by pelikhan** [comment]
According to the template, all these links should be @pxtCdnUrl@ but it seems that they go to blob or commit.

```
# blockly
https://pxt.azureedge.net/blob/795f940a16402bb1aa9d32a68483c51c6826b3d3/blockly/blockly_compressed.js
https://pxt.azureedge.net/blob/a5f64b871a40ce57415aa4a1963a7c124daefacb/blockly/blocks_compressed.js
https://pxt.azureedge.net/blob/d7b1fd97be5fc0aace4a10bb662ce6c4ec581da1/blockly/msg/js/en.js
https://pxt.azureedge.net/commit/431a6aa23d82d76afc8a1128bf924d129691ce00/blockly/media/sprites.png
https://pxt.azureedge.net/commit/431a6aa23d82d76afc8a1128bf924d129691ce00/blockly/media/click.mp3
https://pxt.azureedge.net/commit/431a6aa23d82d76afc8a1128bf924d129691ce00/blockly/media/disconnect.wav
https://pxt.azureedge.net/commit/431a6aa23d82d76afc8a1128bf924d129691ce00/blockly/media/delete.mp3
```

**Comment by mmoskal** [comment]
@pelikhan is it fixed with https://github.com/Microsoft/pxt-backend/commit/4040613675e8f8ffe225811dc6733e4c94e388fd ?

**Comment by OwenBrotherwood** [comment]
start pxt (had blocks program in progress) 
airplane mode
switch 2 javascript
"Works for me"
```
A Blocks / JavaScript code editor for the micro:bit.

pxt.microbit.org version: 0.9.46

PXT version: 0.11.71

C++ runtime version: v2.0.0-rc8
```

**Comment by mmoskal** [comment]
Appears fixed, closing. Thanks @OwenBrotherwood for confirmation!
