### ISSUE TITLE
pxt editor does not load completly on firefox android

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1526]
On android using the firefox browser the pxt editor gave a popup message saying it completed downloading something (update?) and needed to reload, which it did. But now the editor does not load fully, even after refresh and app restart. (It does work on chrome)

![screenshot_20170303-174701](https://cloud.githubusercontent.com/assets/5718354/23561725/bdb42cde-003f-11e7-90da-cf57a8b4ae00.png)

**Comment by nielsswinkels** [comment]
(Can still reproduce this)

**Comment by microsoftsam** [comment]
Fixed in /beta
