### ISSUE TITLE
Toolbox Parity between Blocks & TypeScript

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1536]
As discussed, let's try and get as close to parity between the Blocks toolbox and the TypeScript toolbox (and keep the order the same).
![microbit_blocks](https://cloud.githubusercontent.com/assets/22108954/23582707/ea7ccbfe-00e4-11e7-85f6-c62e461a85f3.PNG)

![microbit_ts](https://cloud.githubusercontent.com/assets/22108954/23582709/f0255b8e-00e4-11e7-8700-212d87721187.PNG)

**Comment by abchatra** [comment]
Fixed
