### ISSUE TITLE
Change default variable name

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1539]
From "item" to "myvariable".  This has been confusing for some users, so let's make the default variable name super clear.  

Longer term, we should think through a better workflow for creating, assigning, and using variables.  Right now, it's not intuitive.

**Comment by samelhusseini** [comment]
Bringing this back, I've investigated having no default variable and Blockly is completely fine with that. 
There's no need to create one for any of the other blocks that we're using. 

I think the best default is no variable. You only see a "Make a variable" button and then when you create it you choose the name and it's your own.
@pelikhan @Jaqster what are your thoughts on that proposal?

**Comment by pelikhan** [comment]
Ship it.

________________________________

**Comment by Jaqster** [comment]
Can we make that "Make a Variable" button stand out a bit more then?  I've seen a lot of users just miss it completely.  
And then would the Set and Change blocks just have an empty slot?  Or do we just not show those blocks until a user makes a variable (like in Function)?
Also, assuming we keep the default "strip", "num", "index", "list/value" variable names in other blocks?

**Comment by samelhusseini** [comment]
Nope you won't see anything but that button.. 

Not sure how to make it stand out more, perhaps being on it's own?
<img width="223" alt="screen shot 2018-04-10 at 1 05 09 pm" src="https://user-images.githubusercontent.com/16690124/38580820-d7e013b2-3cbf-11e8-84e4-d4418df570d9.png">

**Comment by pelikhan** [comment]
I would say the same: being on it’s own it will stand out naturally.

________________________________
