### ISSUE TITLE
icons in show_icon are not caching properly

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1542]
I used PXT on friday, and pressed the RESET button to get the latest editor.

I am now offline, and when I use the editor from the browser cache, the little icons in the show icon block are not cached correctly.

![screen shot 2017-03-05 at 13 50 00](https://cloud.githubusercontent.com/assets/25079586/23587778/0e8c2b4a-01ab-11e7-9d5a-94cf63cc6875.png)

I connected to the internet briefly and used the heart icon, then disconnected.

Now when I go to the show icon dropdown, only the heart image is visible and all the others are broken images

![screen shot 2017-03-05 at 13 51 48](https://cloud.githubusercontent.com/assets/25079586/23587781/1f56979e-01ab-11e7-956d-dfb77aa23ca5.png)

**Comment by abchatra** [comment]
Fixed
