### ISSUE TITLE
icons in show_icon are not self describing

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1543]
The icons in the show_icon block are really useful, but it's not obvious what some of them are. In the previous beta you had just the icon names but no visuals. I think what we need here is *both* the visual representation of the icon *and* it's name, to get the best of both worlds.

**Comment by pelikhan** [comment]
David, have you tried the "show icon" UI in /beta? It provides a tooltip with the name.
![image](https://cloud.githubusercontent.com/assets/4175913/23589090/235bc212-017c-11e7-8039-8aa5cf93ff5f.png)

**Comment by abchatra** [comment]
fixed in beta and will be ported to release
