### ISSUE TITLE
Attribution of new images added to PXT

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1544]
Please note that the new images added to PXT recently need to be correctly attributed.

A lot of these were designed by an 11 year old girl from my computer club, and added into the MicroPython by an agreement that I specifically organised with her parents. The licensing inside MicroPython does allow you to use these contributions, but I'd like to see them properly attributed somewhere - in particular, attributing them to the MicroPython build and pointing at the following file would be effective and mean that you don't have to specifically attribute to all the different individual authors of those images.

https://github.com/bbcmicrobit/micropython/blob/a20fbe82c919cea9519ce5a1140103f518b51caa/source/microbit/microbitconstimage.cpp#L454

and...

https://github.com/bbcmicrobit/micropython/blob/a20fbe82c919cea9519ce5a1140103f518b51caa/source/microbit/modthis.cpp#L58

**Comment by ntoll** [comment]
+1

**Comment by abchatra** [comment]
Attributions are given to micropython at the source file where the icons are re-used (See the file https://github.com/Microsoft/pxt-microbit/blob/master/libs/core/icons.ts ) and the third party notice at the root of the repo (https://github.com/Microsoft/pxt-microbit/blob/master/THIRD-PARTY-NOTICES.txt).  Source file also contains all the original comments and attributions. 

We use many third party MIT source code and this is standard way to attribute as per the legal guidance. Do let us know if there are any other additional legal attributions we need to do. We will be happy to oblige.

We love your icons. Thank you very for designing them and sharing.

**Comment by DavidWhaleMEF** [comment]
Thanks @abchatra I have noted that the MIT licence (and the reference to the appropriate MicroPython cpp file in github) is linked in the source code that appears inside the PXT user editor (in file icons.ts and melodies.ts). Thank you for being thorough with this. // @ntoll
