### ISSUE TITLE
creating 2 game sprites causes null error

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1556]
If you create 2 sprites in the on start block, and try to use them in the forever loop, it causes a "using null value" error. I think it is because in javascript form, the variables are initiated as null, and the part where you create sprites in them is placed after the forever loop. (It seems the pause block is needed to get the error to occur. But it could be other blocks that take up that time.)

![microbit-screenshot sprite bug](https://cloud.githubusercontent.com/assets/5718354/23646171/f0275b28-030f-11e7-8e44-a739708504fa.png)

```
let p2: game.LedSprite = null
let p1: game.LedSprite = null
basic.forever(() => {
    p1.change(LedSpriteProperty.X, 1)
    p2.change(LedSpriteProperty.X, 1)
})
basic.pause(1000)
p1 = game.createSprite(0, 0)
p2 = game.createSprite(2, 2)
```

One way around it is to place a while(true) loop in the onstart, and use that instead of the forever loop.

![microbit-screenshot sprite bug2](https://cloud.githubusercontent.com/assets/5718354/23646175/f45baf64-030f-11e7-97a4-46ce1499444c.png)

```
let p2: game.LedSprite = null
let p1: game.LedSprite = null
basic.forever(() => {

})
basic.pause(1000)
p1 = game.createSprite(0, 0)
p2 = game.createSprite(2, 2)
while (true) {
    p1.change(LedSpriteProperty.X, 1)
    p2.change(LedSpriteProperty.X, 1)
}
```

**Comment by pelikhan** [comment]
This is expected and maybe a bit surprising. ``pause`` allows the forever loop to run.

**Comment by nielsswinkels** [comment]
But if you do anything else than pause, you still dont want it to cause an error. for example:

![microbit-screenshot sprite bug3](https://cloud.githubusercontent.com/assets/5718354/23663334/916fbef2-0352-11e7-97c4-e72160e66e35.png)
