### ISSUE TITLE
simulator slider on firefox

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1557]
The simulator sliders (temperature, lightlevel, etc) don't work as smooth in firefox as they do in chrome. It happens often in firefox that you manage to drag the actual picture instead of that the slider moves. And then when you release, the slider starts moving and is "stuck" to your mousemovements because you have already released..

A bit hard to put in words, try it yourself and you will see. It's really frustrating, and it is the sole reason why I usually make people use chrome instead of firefox in microbit workshops.

**Comment by pelikhan** [comment]
@nielsswinkels if you could record an animated gif of the issue, that would help a lot.

**Comment by microsoftsam** [comment]
@pelikhan I think @nielsswinkels is referring to the simulator sliders, not the Blockly sliders.

**Comment by nielsswinkels** [comment]
yes the simulator, where you simulate changing temperature and light levels. It's a bit tricky to record it because you need to know when I click and release the mouse..

**Comment by pelikhan** [comment]
Oh those...

**Comment by abchatra** [comment]
I can still repro this.

**Comment by nielsswinkels** [comment]
![image](https://cloud.githubusercontent.com/assets/5718354/26193275/1242d22c-3bb5-11e7-92b9-51595b803811.png)

This is in the beta, I can still manage to drag the image of the circle instead of changing the slider value.

**Comment by nielsswinkels** [comment]
Should this be fixed in the beta now? I can still reproduce it:

![pxt slider bug](https://user-images.githubusercontent.com/5718354/29486704-e6626358-84ec-11e7-8408-7f71aa236815.gif)

**Comment by microsoftsam** [comment]
@caitlin-hennessy maybe this isnt just a user select issue?

**Comment by microsoftsam** [comment]
We weren't able to repro this anymore on Firefox for Mac or Windows. @nielsswinkels please check again with the latest /beta. Make sure you're running Makecode version 0.12.125. (Check in Settings -> About).
If this still repro's for you, please share what version of Firefox you are running. Thanks!
