### ISSUE TITLE
Oops cant load help

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1559]
I keep getting this error when trying to use the javascript help in PXT.
I definitely have an internet connection (proved by opening a web page in another tab)

![screen shot 2017-03-07 at 08 13 00](https://cloud.githubusercontent.com/assets/25079586/23647496/fd103276-030d-11e7-8a81-d5b5817dea25.png)

**Comment by DavidWhaleMEF** [comment]
![screen shot 2017-03-07 at 08 14 33](https://cloud.githubusercontent.com/assets/25079586/23647518/1d64c47e-030e-11e7-9bcd-eae42a0ff5c3.png)

**Comment by pelikhan** [comment]
Indeed, docs are at https://pxt.microbit.org/javascript

**Comment by abchatra** [comment]
Fixed
