### ISSUE TITLE
Error messages don't appear for long enough to digest

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1561]
When a program error appears on the screen, it does not appear for long enough to read and digest it.

![screen shot 2017-03-07 at 08 18 08](https://cloud.githubusercontent.com/assets/25079586/23647640/ba7bc136-030e-11e7-84f3-79610f2a9278.png)

When it disappears, the error text stays orange, but I can't see any way to then get PXT to tell me again what the error is on that line. If I remove the line, the screen starts to jump all over the place and the code panel jumps off the bottom of the screen. Then I put the line back in again and the error pops up for a second or two then dissapears before I have chance to read and engage with it.

![screen shot 2017-03-07 at 08 19 16](https://cloud.githubusercontent.com/assets/25079586/23647672/e7a23082-030e-11e7-97f4-a63d9f733a3e.png)

**Comment by abchatra** [comment]
Closing old issues. If this is still relevant please reopen in the https://github.com/Microsoft/pxt-microbit repo.
