### ISSUE TITLE
There is no way to get help on an error message

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1562]
I have an error message on the screen. How do I get help on what this error message means, and some helpful hints and tips on how to correct it? Is there a master list of error messages anywhere in the help that tells me what this specific error means (and a search feature at least so I could search for it and understand what it is trying to tell me?)

![screen shot 2017-03-07 at 08 18 08](https://cloud.githubusercontent.com/assets/25079586/23647687/0444fa6c-030f-11e7-9d23-77df49d789ca.png)

**Comment by abchatra** [comment]
@DavidWhaleMEF We will work on improving the error messages.

This program has a bug. It is not initializing the history variable with the array
```javascript
let history: number[] = [];
```
