### ISSUE TITLE
Program Error: cannot read property 'isValidIndex' of undefined - confusing message

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1563]
I have no idea what this error message means, and how it relates to the error that is in my user program. It looks more like an error message within the PXT system rather than within my user program. What does it mean and how do I correct it?

![screen shot 2017-03-07 at 08 18 08](https://cloud.githubusercontent.com/assets/25079586/23647726/3d17c586-030f-11e7-9028-29d60b6d4b9c.png)

**Comment by pelikhan** [comment]
You declare but do not allocate history. Try
```
let history: number[] = []
...
```
