### ISSUE TITLE
Error message truncated at edge of screen, no way to scroll

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1564]
When an error message is longer than the screen, there is no way to scroll the editor pane to the right to see what the rest of the error message says.

![screen shot 2017-03-07 at 08 31 46](https://cloud.githubusercontent.com/assets/25079586/23647993/99e7de94-0310-11e7-9efa-d0909e3c4f72.png)

**Comment by abchatra** [comment]
@microsoftsam Is this fixed with your change?

**Comment by microsoftsam** [comment]
Yup.
