### ISSUE TITLE
Operators help page requires internet access

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1567]
The help in the operators page is not integral to the page, but goes off to some on the web typescript developer documentation. This means that this help is not cached or running locally, and thus will not be accessible when there is no internet connection.

Please can you provide all PXT help as static pages within the PXT system itself, so that PXT can be cached or run locally and therefore used successfully without an internet connection.

![screen shot 2017-03-07 at 08 47 10](https://cloud.githubusercontent.com/assets/25079586/23648490/d994faa2-0312-11e7-89cb-7f0c3a748d4c.png)

**Comment by DavidWhaleMEF** [comment]
The same is true of the statements page - it goes off to developer documentation elsewhere on the web, it will not work when there is no internet connection. 

![screen shot 2017-03-07 at 08 49 08](https://cloud.githubusercontent.com/assets/25079586/23648523/02d65190-0313-11e7-88e6-271bafaea270.png)

**Comment by abchatra** [comment]
Documentations won't work when it is not live. We don't want to download all the documentation and keep it just for offline.

**Comment by abchatra** [comment]
Current solution won't scale for offline. We will work on a solution where teachers will have to download separately the documentation

**Comment by abchatra** [comment]
Won't fix from our end

**Comment by DavidWhaleMEF** [comment]
![screen shot 2017-03-13 at 14 38 47](https://cloud.githubusercontent.com/assets/25079586/23872324/c6352b90-0825-11e7-8311-39ab53dd24e3.png)

Ok, thanks. Screen dump above shows that the UX of this is pretty abrupt if there is no internet connectivity - the functionality of the application appears degraded when internet disappears.

**Comment by DavidWhaleMEF** [comment]
i.e. normal users will not know the difference between what is part of the editor, and what is not part of the editor. So as far as they are concerned, it's broken (this is what users tell me).

When you get a longer term story on this, could you refer to this github ticket, as I have references to this particular ticket in our support system and I will need a way of updating the users that reported this issue and this is my only point of reference at the moment. Thanks. (Just refer to this ticket in any new ticket that you create, and I will get notified and can then follow up with the appropriate users).
