### ISSUE TITLE
javascript help FAQs don't look like FAQs

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1568]
I'm not convinced that any of the (two) FAQ's provided on the javascript help pages are actually 'frequently asked questions' submitted by users or from real user research using the target audience and target age group:

![screen shot 2017-03-07 at 08 51 06](https://cloud.githubusercontent.com/assets/25079586/23648619/5ba868ee-0313-11e7-8609-5eb711e9f02a.png)

![screen shot 2017-03-07 at 08 51 12](https://cloud.githubusercontent.com/assets/25079586/23648622/60927ed0-0313-11e7-8af1-d4be1cfd1de9.png)

**Comment by ganicke** [comment]
??? Are we talking about the _/faq_ page? Where are the 'Q's collected? Are we maintain this page?

The JS info was moved in https://github.com/Microsoft/pxt-microbit/pull/368.
