### ISSUE TITLE
No reference to null and undefined in javascript docs?

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1569]
I can't find any reference to 'null' and 'undefined' in any of the provided PXT javascript docs.

Python supports the 'None' type (and we often use it with children of the target age group). Typescript supports both null and undefined, but I can't find any reference in it in the PXT docs (I would do a search, but there is no search feature, but I have looked through all the pages I can see and can't find it on any of them)

Here is some official documentation, for reference.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

**Comment by ganicke** [comment]
Section for 'null' and 'undefined' added to JS types page.

https://github.com/Microsoft/pxt/pull/2893
