### ISSUE TITLE
Comments get stripped on round-trip from javascript to blocks

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1570]
I have noticed that since the addition of the grey 'javascript' block, it is now possible to take a complex javascript program and round trip it back into blocks.

However, if you have a region of code that can correctly render in blocks, all of the comments at the end of that region get stripped (i.e. presumably because comments are associated with the next block, not the previous block). This means that, because it is now possible to press the BLOCKS button on any arbitrary javascript code and it *will* round trip, it is now a breaking experience to press that button where comment markers appear in validly rendering code that does not have at least one block after comments, and those user comments get removed from the user program with no warning, there is no undo, and there is no way of getting them back again.

Because there is no history in the cached version in the browser cache, you have now just stripped about a page of useful comments from my program - lost forever!

Can you take a look and see if you can make this a non-damaging experience for users? Thanks!

**Comment by DavidWhaleMEF** [comment]
I would provide an example here for you, but as above, you stripped all my comments so my example vaporised in the process!

**Comment by abchatra** [comment]
This looks fixed. 

The microbit issues have moved to github.com/Microsoft/pxt-microbit repo. 
If this is still an issue please open the issue in that repo or let us know, we will reopen in that repo.
