### ISSUE TITLE
In the “?help”, the javascript document can’t be displayed correctly when turn back from one item such as “Calling”

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#1571]
Repro steps:
•	Navigate to https://pxt.microbit.org/beta
•	Click “?help” , choose “JavaScript”
•	Click one item of the JavaScript list, such as “Calling”
•	Click the “js” of “js > call”
![capture](https://cloud.githubusercontent.com/assets/23497626/23650700/dda1793a-02d7-11e7-8d99-b0452a34896d.PNG)

Expect result :
The display should turn back to the page of JavaScript list
Actual result :
The display could not  turn back to the page of JavaScript list
![1](https://cloud.githubusercontent.com/assets/23497626/23650782/2d163de8-02d8-11e7-9fdf-d95cd0bfc0f6.PNG)

**Comment by abchatra** [comment]
Fixed
