### ISSUE TITLE
Odd data in exported CSV file

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1572]
I'm not sure I completely understand how the DOWNLOAD csv file is being generated? Can you link me to some documentation that says how it should work, as I couldn't find anything about it in the official docs here: https://pxt.microbit.org/docs

My code outputs two csv values (a number and a boolean string). When I download the CSV file, I only see the boolean flag in the first line, not in any of the other lines. Am I doing something wrong in the data generation? What format do you expect the serial data to appear in, in order to create multiple columns in the exported CSV data?

![screen shot 2017-03-07 at 09 47 38](https://cloud.githubusercontent.com/assets/25079586/23651244/d33356f4-031c-11e7-8342-4209d8665afa.png)

**Comment by DavidWhaleMEF** [comment]
P.S. I tried spaces too, and the boolean only seems to come out on the first line only, not on all other lines?

![screen shot 2017-03-07 at 10 01 27](https://cloud.githubusercontent.com/assets/25079586/23651329/21d9a948-031d-11e7-977b-61a4235d839b.png)

Code is essentially this, in a loop, where n is a 'number' and b is a 'boolean'. Tried both a comma and a space as a separator, and it doesn't seem to generate the right CSV when hitting the download button?

    serial.writeNumber(n)
    serial.writeString(' ')
    serial.writeLine(b.toString())

**Comment by pelikhan** [comment]
Try using serial.writeValue, it will spit up one value per line and the editor will accumulate it for you.

**Comment by ganicke** [comment]
Hi @DavidWhaleMEF,

Finally got into this issue. I'd tried a couple of scenarios and here are the results:

[1] Use **serial.writeValue()** for each data item
---
```typescript
input.onButtonPressed(Button.B, () => {
    let b = false
    for (let i = 0; i <= 5 - 1; i++) {
        b = !(b)
        serial.writeValue("id", i)
        serial.writeValue("boolean", b ? 1 : 0)
    }
})
```
The resulting rows:
```csv
green time, green id, green time, green boolean, log time, log source, log message
0, 0, 0, 1, 0, green-510114904642037914280.844254157024829, id:4
0.005, 1, 0.003, 0, 0.003, green-510114904642037914280.844254157024829, boolean:1
0.007, 2, 0.005, 1
0.008, 3, 0.006, 0
0.009, 4, 0.006, 1
```
![image](https://user-images.githubusercontent.com/27789908/30400558-1e0f6096-988c-11e7-9347-5abe534cb196.png)

[2] Use **serial.writeString()** once for all data items
---
```typescript
input.onButtonPressed(Button.A, () => {
    let b = false
    for (let i = 0; i <= 5 - 1; i++) {
        b = !(b)
        serial.writeLine("id:" + i + "\nboolean:" + (b ? 1 : 0))
    }
})
```
The resulting rows:
```csv
green time, green id, green time, green boolean, log time, log source, log message
0, 0, 0, 1, 0, green-63082368222271698440.6258763773097633, id:4
0.003, 1, 0.002, 0, 0.001, green-63082368222271698440.6258763773097633, boolean:1
0.004, 2, 0.003, 1
0.004, 3, 0.003, 0
0.005, 4, 0.004, 1

```

![image](https://user-images.githubusercontent.com/27789908/30401270-7c6e032a-988e-11e7-9aaa-bbbff955d8bf.png)

Maybe @pelikhan can comment on whether or not this is the expected/proper csv format. I'm not sure why ``log time``, ``log source``, and ``log message`` are on the first data rows (and why does ``log message`` end up being the last instance of the data value?).

**Comment by DavidWhaleMEF** [comment]
Thanks! The output format looks very odd to me. If this is expected behaviour, is it possible you could document it somewhere so that users have a chance of knowing what to expect from it, and they can then use this to design an appropriate parser for it? Thanks!

**Comment by ganicke** [comment]
The situation is that the values are aggregated in arrays based on a name. These name-to-value arrays are then formatted by code that makes the csv. This is in [logs.ts](https://github.com/Microsoft/pxt/blob/master/pxtsim/logs.ts) which I haven't studied enough yet to see why the format is the way it is. My guess is that comes from a JSON layout used for streaming to Azure. I'll get some notes on the format into the reference somewhere, Likely in _/reference/serial/serial-write-value_.

**Comment by ganicke** [comment]
@riknoll, would you have any comments on why the format is like this?

**Comment by pelikhan** [comment]
Columns ABCD are preprocessed rows containing the data stream displayed on streams. You can select those in Excel and do a scatter plot. Columns E,F,G are the row log messages.

**Comment by ganicke** [comment]
Page added to describe logging and using the log files.

https://github.com/Microsoft/pxt-microbit/pull/540.
