### ISSUE TITLE
Some methods in JavaScript don’t have corresponding blocks in Blocks

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#1575]
**Repro step:**
•	Navigate to https://pxt.microbit.org/beta
•	Switch to “JavaScript”
•	choose "Basic" and select the method “basic.showAnimation(...)”
•	Switch to block and observe content panel

**Expect result:**
The “basic.showAnimation(...)” should have the corresponding blocks.

**Actual result:**
“basic.showAnimation()” still display which show in JavaScript
![1](https://cloud.githubusercontent.com/assets/17866936/23652474/11fe674c-0364-11e7-933c-0879c4584449.png)

**Comment by pelikhan** [comment]
By design, JavaScript is more expressive and also has more APIs.

**Comment by abchatra** [comment]
This is as expected. We have a always decompile feature. Which means if there is no block corresponding to the javascript code, then the javascript is shown
