### ISSUE TITLE
File append string and File append line flipped on pxt.microbit.org?

### ISSUE THREAD

**Issue by finneyj** [Microsoft/pxt#1576]
Hi Guys,

just writing a simple data logger using PXT blocks via pxt.microbit.org, and am using the File system package to create a csv file.

It *seems*  like the append string() and append line(0 blocks have been flipped? i.e. append string adds a CRLF but append line doesn't?

Seems to be the behaviour of this script:
![image](https://cloud.githubusercontent.com/assets/11539567/23661897/d67ad714-0345-11e7-8b69-29557329c9b5.png)

**Comment by pelikhan** [comment]
Did you reuse an old script? Make sure to use https://github.com/Microsoft/pxt-filesystem/releases/tag/v0.2.1

You can go to JavaScript, Explorer, click on the Update button of the file system reference.

**Comment by pelikhan** [comment]
It was swapped: https://github.com/Microsoft/pxt-filesystem/commit/f58da43cc3351e64d89ff8d1b70742d940367463

**Comment by finneyj** [comment]
nope - this was a new created today...

Just teaching now, so will check versions later and report back.

**Comment by harveytwyman** [comment]
I have a totally different code for using "Filesystem Functions" which requires defining a variable as a "File pointer". Here's my ticket:

[https://github.com/Microsoft/pxt/issues/1577](url)

**Comment by finneyj** [comment]
Sorry for delay guys. Just updated the FileSystem package, verified version through explorer and compiled via JavaScript interface. The blocks still seem to be flipped. Here's the File System pxt.json:

```

**Comment by pelikhan** [comment]
Could you share the project? (share button)

**Comment by pelikhan** [comment]
@harveytwyman broken link

**Comment by finneyj** [comment]
sure: https://pxt.microbit.org/23573-75266-92266-99248

**Comment by pelikhan** [comment]
I had forgotten to update the ``shims.d.ts`` file. Please try to update again.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-filesystem/commit/b019f4f05a9a4bb3e42e036a55811f56cedaf4fd

**Comment by finneyj** [comment]
@pelikhan 

Yup - Now works perfectly. Thanks Peli!

p.s. This script also highlights a bug in the simulator - will raise a separate issue.
