### ISSUE TITLE
"Filesystem" Documents are WRONG! - This Example WORKS!

### ISSUE THREAD

**Issue by harveytwyman** [Microsoft/pxt#1577]
I tried ALL the examples for "Filesystem" in various documents and NONE worked!

I then found one example that did and it requires a "Variable" assigned as a "File Pointer". This is similar to using files in "C".

NONE of the official documents mentioned this fact!

Also as mentioned before the "files.appendString" and "files.appendLine" ARE SWAPPED!

Observe the "Blocks" and "JavaScript Code" Working Example below which creates incrementing numbers, one on each line:
 
![filesystem example code](https://cloud.githubusercontent.com/assets/12800293/23667660/7fd8365c-0356-11e7-9d4b-c0973377200f.jpg)

![filesystem javascript example](https://cloud.githubusercontent.com/assets/12800293/23667681/986df594-0356-11e7-9725-aaab4c87a81a.jpg)**

**Comment by pelikhan** [comment]
Swap fixed in https://github.com/Microsoft/pxt-filesystem/commit/b019f4f05a9a4bb3e42e036a55811f56cedaf4fd

**Comment by pelikhan** [comment]
@harveytwyman please update the reference in your project and try again.
