### ISSUE TITLE
converting from record to class yields internal error

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1584]
https://pxt.microbit.org/58475-75333-83785-95823

Program Error: r.isRef is not a function

**Comment by tballmsft** [comment]
The problem here is that r is a RefMap that is being treated as a RefRecord. RefMap doesn't implement isRef, which should be implemented.

**Comment by tballmsft** [comment]
Fixed with new type checker.

**Comment by yratof** [comment]
Did this get fixed? Still showing up with NEOPIXEL & forever loops

**Comment by yratof** [comment]
https://makecode.microbit.org/_ACwfq3VctT0A
