### ISSUE TITLE
Clone project

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1589]
When people want to keep a 'safe' working copy of a program but try something more adventurous, those in the block editor used 'clone'
<img width="923" alt="image" src="https://cloud.githubusercontent.com/assets/147113/23217343/cb45cc76-f910-11e6-852b-40070f402d11.png">

In PXT there doesn't appear to be such a clear 'cone' or 'duplicate' or 'save as' option. Have I missed it?

**Comment by pelikhan** [comment]
Save as .hex, drag and drop back will create a new copy.

**Comment by tballmsft** [comment]
i disagree. it's useful to be able to easily make a copy to experiment.

**Comment by pelikhan** [comment]
What is the usage of the "clone" button in microbit?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment]
I don't have those stats, do you? Discussion between @whaleygeek and @finneyj confirms anecdotally that a 'clone' or 'save as' feature would be valuable, especially if there are some save UI/features changing anyway.

**Comment by jaustin** [comment]
Here's a couple of possible user stories for this:

1) Teacher:
A teacher has built a program that works perfectly. They want to pare it back to create a skeleton to share with their class. In order to do this, they want to 'cone' the existing project and make a copy to start deleting things from. They want to be able to go back to the complete program using the 'Projects' dialogue that shows the programs cached in the browser.

This is equivalent to doing 'File->Save As' in a desktop application, and a common operation that many people expect.

2) Student:
A student is experimenting with an algorithm . They have something that works, but they want to try a different structure. They want to be able to get back to the working script easily because it is good enough to submit at the end of the class, but they are hoping they can do something better in the remaining 15minutes.

In this case it's possible, even likely, that the student isn't aware of the ability to drag/drop a new program into the browser because they normally create programs from scratch during lessons.

Hope those help,
Jonny

**Comment by HelenFoster** [comment]
I expected a "clone" option to be there, and spent a few minutes looking for it before deciding it wasn't.

Saving and reloading a hex file is a rather roundabout way of doing it - especially as it's not obvious that the clone has happened, and that I haven't just opened the same file again.

**Comment by Geoffree3** [comment]
Please can we have a clone function as on the old Blocks editor!  It's not straightforward or intuitive to save as .hex and then import again.
