### ISSUE TITLE
Unsupported Syntax Node message

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#159]
We need a better error message than this. Too confusing for non-CS types.

**Comment by thomasdenney** [comment]
I've been working on improving error messages in general, but I won't be ready to commit all the changes until tomorrow.

**Comment by tballmsft** [comment]
Thanks, @thomasdenney !

**Comment by thomasdenney** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/165

**Comment by pelikhan** [comment]
Make sure all messages are localizable.
