### ISSUE TITLE
FileSystem package "readToSerial" block causes simulator panic

### ISSUE THREAD

**Issue by finneyj** [Microsoft/pxt#1594]
Script: https://pxt.microbit.org/23573-75266-92266-99248

Clicking A+B on the simulator for this script gives a panic, and JS error box citing that the function does not exist:

![image](https://cloud.githubusercontent.com/assets/11539567/23762600/5d9db802-04ee-11e7-80c5-4adb0b37ecb0.png)

**Comment by pelikhan** [comment]
It's typical when a C++ version does not have a TS counterpart.

**Comment by finneyj** [comment]
OK - I confess that it made me smile when the simulator panic mirrored the micro:bit panic . :-)

I'll leave it with you guys to ponder / schedule if you want to plug this hole.

If you decide to take this forward at any point, I guess one approach would be to provide a download in the browser containing the relevant file data.  Just an idea..

**Comment by pelikhan** [comment]
This issue is fixed in 0.11.9 and up.
