### ISSUE TITLE
Note frequency value block mising from Music Toolbox

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1605]
Where did it go?
![noteblock](https://cloud.githubusercontent.com/assets/22108954/23826301/a80344a0-064e-11e7-8b78-1ad91606c7ed.PNG)

**Comment by pelikhan** [comment]
Is it in advanced?

**Comment by Jaqster** [comment]
You mean, "...More"?  We don't have that for the Music category...

**Comment by pelikhan** [comment]
It's probably hidden with the "blockHidden" flag.
