### ISSUE TITLE
TOC extraction logic should be moved to the backend

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1607]
The TOC generation from SUMMARY.md should be run on the fly by the backend to keep in sync with any changes to the .md. Currently, it is hard-coded in the compiled pxtarget.json, thus tied to the ``/`` of the application.

**Comment by mmoskal** [comment]
Fixed in https://github.com/Microsoft/pxt-backend/commit/eb2bf5bb54d096e6591eff084d39c2f4f9e17e74
