### ISSUE TITLE
draw a circle 

### ISSUE THREAD

**Issue by karisantos** [Microsoft/pxt#1608]
I have written a few programs on pxt-microbit  where "Draw A Circle" will display on the screen after my program starts. Here is a small program that causes it consistently on 2 different microbits.  I believe it has happened with other programs not using BLE too.
![screen shot 2017-03-12 at 8 50 59 pm](https://cloud.githubusercontent.com/assets/6976121/23840125/2c2eba60-0768-11e7-9afb-d99219d1a2bf.png)

**Comment by karisantos** [comment]
here is another program where I get "draw a circle" on button A press
![screen shot 2017-03-12 at 10 15 57 pm](https://cloud.githubusercontent.com/assets/6976121/23841310/ed78808a-0771-11e7-8b2d-5a605f91ee08.png)

**Comment by pelikhan** [comment]
Draw a circle is the calibration step for the magnetometer sensor.

**Comment by karisantos** [comment]
OK - that makes sense (since I just started playing with the compass), but it is not obvious.
