### ISSUE TITLE
support Tuple types

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#161]
just adding this for completeness

**Comment by abchatra** [comment]
@tballmsft Can you please give an example here?

**Comment by thomasdenney** [comment]
Typescript supports tuples, see [here](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple). I imagine the most straightforward way to implement it would be via unnamed classes.

**Comment by mmoskal** [comment]
IMHO this is overkill though...

**Comment by abchatra** [comment]
No immediate plans. Closing.
