### ISSUE TITLE
Round tripping between javascript and blocks changes JOIN code

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1613]
When I round-trip to javascript and back to blocks, it changes my code by inserting a "" at the start of a join statement.
![screen shot 2017-03-13 at 20 08 28](https://cloud.githubusercontent.com/assets/25079586/23873159/f26ada5e-0828-11e7-9550-530070c3767c.png)

![screen shot 2017-03-13 at 20 08 18](https://cloud.githubusercontent.com/assets/25079586/23873168/f51b9d6a-0828-11e7-9eef-b150baa18455.png)

**Comment by DavidWhaleMEF** [comment]
When I entered it in blocks in the first place, it was just joining app_id with "START" and the blocks editor accepted that. Round tripping to javascript and back to blocks inserts the extra "" at the start, which makes the blocks code look more complex to read.

**Comment by abchatra** [comment]
It might be good idea to remove the leading empty string.

**Comment by Jaqster** [comment]
yup.  I just ran into this too.  It's in Douglas' curriculum.

**Comment by DavidWhaleMEF** [comment]
Is there an ETA for a fix on this one yet do you know? It's been open for over 2 and a half months now. Thanks!

**Comment by abchatra** [comment]
Moved https://github.com/Microsoft/pxt-microbit/issues/901
