### ISSUE TITLE
Slider not available on touch device

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1614]

**Comment by microsoftsam** [comment]
This is what I see on a touch device. We should either show the popup dialog or the slider but not both.
![screen shot 2017-03-22 at 1 31 21 pm](https://cloud.githubusercontent.com/assets/16690124/24219404/ea75c9bc-0f03-11e7-959c-230a9d24a970.png)

**Comment by pelikhan** [comment]
On a touch device, a slider would allow to avoid the soft keyboard to popup --> much better experience.

**Comment by microsoftsam** [comment]
Fixed, we decided to show the slider on touch devices.
