### ISSUE TITLE
Avatar not working in /docs

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#1615]
Loads fine in localhost.

<img width="554" alt="screen shot 2017-03-14 at 9 39 37 am" src="https://cloud.githubusercontent.com/assets/16690124/23878217/3a69df5a-089a-11e7-840b-d563f2c809ef.png">

**Comment by mmoskal** [comment]
Fixed by https://github.com/Microsoft/pxt-deployment-config/commit/6eea813d2ca34c2c0ea25cf01cdd497e3631307a 

This most likely needs to be updated since these files are common for all targets.
