### ISSUE TITLE
Project Settings page dead-ends

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1620]
Repro - Select Settings menu, Project Settings, rename, click Save.
Page just hangs.  Have to select Blocks/JavaScript to get out.

**Comment by abchatra** [comment]
This should be dialog.

**Comment by microsoftsam** [comment]
What is the expected behaviour here? Page is not hanging, saving will save the settings, and reload the project if a reload is required, but it does not redirect you to the previous editing experience (blocks / JS). Do we want to do that?

**Comment by Jaqster** [comment]
Yeah, I thought this was a dialog...  I expected it to be a dialog box that closes when I click Save or X and brings me back to my project.  It's weird, unexpected behavior the way it is today.

**Comment by pelikhan** [comment]
Make save go back to blocks sounds easy enough.

**Comment by abchatra** [comment]
Can we just get rid of Project Settings? You already have rename in the editor.  You can always reach here from explorer window for advanced users.

**Comment by pelikhan** [comment]
There are options in there when using Bluetooth.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microsoftsam** [comment]
Okay. Save going back to previous editor sounds like a plan.

________________________________
