### ISSUE TITLE
Firefox embed arrow misplaced in share dialog

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#1621]
![embed_share_firefox](https://cloud.githubusercontent.com/assets/13754588/23879103/53271c5c-0808-11e7-95c7-0ec370b7a79d.PNG)

**Comment by Mofell** [comment]
This issue is not repro in FireFox now

**Comment by Mofell** [comment]
Checked my Firefox version is 52.0, this issue doesn't issue.
Using low version firefox: 51.0.***, this issue repro.

**Comment by abchatra** [comment]
Fixed in latest version of Firefox.
