### ISSUE TITLE
Make Projects not loading

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1623]
Edge, Display: 1024 x 768
Repro - Projects menu, Make menu, Click on a project to open
Result - docs sidebar doesn't open

**Comment by microsoftsam** [comment]
Docs sidebar doesn't appear in anything less than 99em. 
Ideally we should have a way to display docs in every view. Some proposals: 
- In Wide screen: show on the right (as it is today)
- In computer view: show on top / bottom of Blocks / JS editor. 
- In mobile / tablet: Have a toggle in the menu, that shows it as a popup

**Comment by Jaqster** [comment]
We can also just open it as a full page in a new tab for Computer View.  We should just have something happen.  The more I think about it, I'm liking the idea of a popup overlay for mobile/tablet...

**Comment by pelikhan** [comment]
We should probably handle mobile and table separately. 

In mobile, opening a new page is probably the best experience to leverage the full screen space for reading.

In other view, we could still use the 3rd column system but it would compress the editor view and thus resize it to the smaller screen size configuration. Ultimately, we could for example, render a phone mode with docs side by side. (Maybe the docs columns should really be pushing the entire editor to the right.

**Comment by microsoftsam** [comment]
Fixed with new sidedocs.
