### ISSUE TITLE
Getting Started - real estate

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1624]
Edge, Display: 1024 x 768
We need to think more about how to more efficiently use screen real estate for the Getting Started experience.  On 1024x768, when you have the simulator shown, there's no space.

Also, the cursor shows up at the top bar in level 7.
<img width="509" alt="gettingstarted" src="https://cloud.githubusercontent.com/assets/22108954/23879521/01f1f174-080b-11e7-9472-6d856741be0f.PNG">

**Comment by pelikhan** [comment]
As it is, the tutorial experience is unusable on 1024x768.

**Comment by pelikhan** [comment]
I think we should not have the special single column mode and instead disable blocks.

**Comment by microsoftsam** [comment]
Fixed with new getting started experience.
