### ISSUE TITLE
When download again in download pop up window, it jumps to a Blank page without prompt message.

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#1627]
•	Navigate to https://pxt.microbit.org/beta
•	Click download
•	Click download again

Expect reault: download prompt message should appear again.
Actual result: No download prompt message and it jumps to blank page

This issue only repro on IE11 and Edge

**Comment by abchatra** [comment]
I can't repro this. @microsoftsam Can you repro?

**Comment by Mofell** [comment]
Share repro gif

![repro](https://cloud.githubusercontent.com/assets/23447632/24031389/55ec3f72-0b1d-11e7-9224-f0c8c4cd066b.gif)

**Comment by abchatra** [comment]
Yes repros for me on Edge & IE11

**Comment by pelikhan** [comment]
Navigation to data uri not supported in IE/Edge. Button will be hidden for those browsers.

https://github.com/Microsoft/pxt/issues/1686

**Comment by pelikhan** [comment]
Not supported
