### ISSUE TITLE
after remove the “core” and “radio", the Editor and Simulator display not normally

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#1629]
**repro steps:**
•	Navigate to https://pxt.microbit.org/beta
•	Click “JavaScript” and click the “Explore” which under the simulator
•	Choose “core” and remove it, the “core” can’t be moved
•	Then choose “radio” and remove it
•	The “radio” and “core” both be removed.

**Expect result :**
The Editor and Simulator display normally:
![pxttest1](https://cloud.githubusercontent.com/assets/11880996/23891151/e177532e-08cf-11e7-986d-a27eb60575a3.png)

**Actual result :**
The Editor and Simulator display like the picture:
![pxttest2](https://cloud.githubusercontent.com/assets/11880996/23891273/7237ce3e-08d0-11e7-91ad-27afac052533.png)

**Comment by pelikhan** [comment]
Core should not be allowed to be removed.

**Comment by pelikhan** [comment]
Fixed by 06032373bbc71f0b077e973d88e5c0b717dd7027
