### ISSUE TITLE
treatment of undefined/any

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#163]
Appears to be different than TS. Comments?

# Null and Undefined

In TypeScript, both `undefined` and `null` actually have their own types named `undefined` and `null` respectively.
Much like `void`, they're not extremely useful on their own:

```ts
// Not much else we can assign to these variables!
let u: undefined = undefined;
let n: null = null;
```

By default `null` and `undefined` are subtypes of all other types.
That means you can assign `null` and `undefined` to something like `number`.

**Comment by mmoskal** [comment]
We will not distinguish between `undefined` and `null`. For numbers, `null` will be treated as `0` (see #244).
