### ISSUE TITLE
The “undo” and “redo” button under “JavaScript” don’t display the state of disable when there is no steps could be redo or undo

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#1630]
**Repro Steps:**
•	Navigate to https://pxt.microbit.org/beta
•	Click “JavaScript” and choose "Basic" and select the method “basic.showNumber(0)”
•	Click the button “undo”, the method “basic.showNumber(0)” which was added in the last step would be undone

**Expect result :**
The button “undo” should be on the state of disable
**Actual result :**
The button “undo” was not on the state of disable

**Comment by microsoftsam** [comment]
Known issue. Can't access the undo stack in the monaco editor. Won't fix.
