### ISSUE TITLE
After choose the “Support” or “Buy” under “?help”, The browser will open a new tab, but it didn’t go to the new tab

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#1631]
**repro steps:**
•	Navigate to https://pxt.microbit.org/beta
•	Click “?help” , choose “Support” or “Buy”

**Expect result :**
The browser will open a new tab and go to the new tab
**Actual result :**
The browser will open a new tab, but it didn’t go to the new tab, it still on the page of https://pxt.microbit.org/beta

**Only repro on FireFox on Mac**

**Comment by microsoftsam** [comment]
Can't repro on Firefox 50.1.0 on Mac 10.12.23.
The link has target=_blank. 

What Firefox version are you using?

**Comment by yanlxu** [comment]
we test on firefox 52.0 on Mac 10.11.6, but it didn't repro when test today

**Comment by microsoftsam** [comment]
Okay. Closing as No Repro.
