### ISSUE TITLE
Block colour changes when there's an error inside

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1632]
Before pushing button A in the Sim:

![image](https://cloud.githubusercontent.com/assets/147113/23907899/5521ff78-08ca-11e7-8de5-1b4946bc34e6.png)

After:
![image](https://cloud.githubusercontent.com/assets/147113/23907920/662facfc-08ca-11e7-9652-641b025aaf70.png)

**Comment by abchatra** [comment]
@jaustin Can you explain more here? I believe black color change is intentional on error. What is the impact here?

**Comment by pelikhan** [comment]
We should see a warning triangle that explains the problem.

**Comment by jaustin** [comment]
The only way to get the block to 'go back' to the normal colour is to reload, too. As far as I could see.

**Comment by tballmsft** [comment]
This is a runtime error surfaced by the simulator.

**Comment by microsoftsam** [comment]
We no longer change the color when highlighting, but instead outline the block.
