### ISSUE TITLE
Docs TOC and sidebar not initialized correctly. 

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#1636]
Error with initializing the sidebar is stopping the TOC dropdowns from initializing.

<img width="482" alt="screen shot 2017-03-15 at 8 42 48 am" src="https://cloud.githubusercontent.com/assets/16690124/23923606/6416e35e-095b-11e7-913b-a38db80d324d.png">

**Comment by microsoftsam** [comment]
This is due to sidebar logic (semantic) not being included in the generated semantic.js under docscdn. 
Why are the two versions different? @mmoskal

**Comment by microsoftsam** [comment]
<img width="766" alt="screen shot 2017-03-15 at 8 47 49 am" src="https://cloud.githubusercontent.com/assets/16690124/23923766/19bbc4d6-095c-11e7-9dfa-e6f48cceb9d6.png">

**Comment by microsoftsam** [comment]
Also why do we include two versions of semantic.js in the docs. 
<img width="896" alt="screen shot 2017-03-15 at 8 49 41 am" src="https://cloud.githubusercontent.com/assets/16690124/23923833/5c4b06ae-095c-11e7-8105-44a78c7b34c7.png">

I'm guessing the docs renders one and then embed slurps in another. Can we be smarter about this?

**Comment by microsoftsam** [comment]
Could this be because we haven't yet released, and so the semantic.js version attached to the docs has sidebar logic, but the semantic.js version attached to --embed does not. That makes sense to me.

**Comment by pelikhan** [comment]
We have released, it's still an issue.

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/pxt/commit/cc925c59a5f98b8d1b0b5d5d4a6fa8c905afef29

**Comment by mmoskal** [comment]
Do I need to look in the built repo?
