### ISSUE TITLE
support get/set accessors for classes

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#164]
a nice feature to have

**Comment by mmoskal** [comment]
We do have fields

**Comment by tballmsft** [comment]
get/set for teaching a better way than fields...

**Comment by mmoskal** [comment]
IMHO field is a core concept that you need to implement anything in a class. get/set is syntactic sugar that most languages happily miss and is arguably confusing for beginners (when should I use getter and when a method?).

But I guess we should add them for the sake of TS compat and pros who miss it.

**Comment by pelikhan** [comment]
We need instrumentation that detect which features pro try to use and prioritize accordingly.

I'd rather have a message saying use fields instead for this one.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by thomasdenney** [comment]
My perspective, as a CS undergrad:

1. Our OO course introduced fields and getters/setters around the same time - possibly even the same lecture. Meanwhile, the TypeScript handbook introduces them [mid-way through the section on classes](http://www.typescriptlang.org/docs/handbook/classes.html#accessors)
2. Students keen to use the JS side will probably take advantage of TypeScript teaching resources, so having strong support for TS features is very important. Copying and pasting code from the Internet is not an uncommon method used by students keen to explore functionality quickly. 
3. On the other hand, I don't see getters and setters used much in TS code. The PXT code base uses them sporadically, for example

**Comment by tballmsft** [comment]
It's low priority, I agree.  But I would like us to have a complete TypeScript OO story eventually, that has a nice mapping to C#.
