### ISSUE TITLE
Core is removed when delete it in title edit page

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#1643]
repro steps: 
•	Navigate to https://pxt.microbit.org/beta
•	Click button “More…”->”Project Setting”
•	Click “Edit Settings As text”
•	remove "core": "*", "radio": "*" 
{
    "name": "test",
    "dependencies": {},
    "description": "",
    "files": [
        "main.blocks",
        "main.ts",
        "README.md"
    ]
}
•	Click Blocks

Expect result: core should not be deleted
Actual result: core is deleted and simulator disappear

**Comment by Mofell** [comment]
Shared script page: https://pxt.microbit.org/61648-03705-46752-45529

**Comment by pelikhan** [comment]
@gujenkin when applying the logic about adding missing packages, we should always ensure that the core package of the target is present first.

**Comment by abchatra** [comment]
We have decided to not fix any explorer bugs for now as they are not used by students. Closing as Won't Fix.

**Comment by abchatra** [comment]
Even though this is project settings, it is related to explorer
