### ISSUE TITLE
Simple parsing of integer to string is unclear

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1644]
...or at least it is to me!...

If I want to stringify numbers, I'm currently using the 'join' block - for example I resolve this error (this is an artificial example, I know 'show number' exists):
![image](https://cloud.githubusercontent.com/assets/147113/23949597/c24e230a-097f-11e7-8235-0813169955f3.png)

By modifying join to take only one argument:
![image](https://cloud.githubusercontent.com/assets/147113/23949618/d3ea25d2-097f-11e7-99b1-c56d811e9eac.png)

...but join isn't a very natural way to do that! 

Is there a 'convert to string' block I'm missing somewhere? I see the handy 'parse to integer' to go the other way, but what about 'convert to string' in the 'Text' menu?

**Comment by jaustin** [comment]
...the other thing is that someone who wasn't aware 'join' could be easily configured might not even think to grab the 'two input' version of it to use for stringification.

**Comment by abchatra** [comment]
Looks like toString block is what  is needed here.

**Comment by abchatra** [comment]
Moved to pxt-microbit
