### ISSUE TITLE
PXT on Windows fails to import hex files created by PXT on an iPhone

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt#1645]
Using "Import file" at "https://pxt.microbit.org/" from Windows IE 11. For (any?) HEX file created by PXT on an iPhone, the error message is "Sorry, we could not recognize this file."

Import also fails in Safari on macOS. I haven't tried it on iOS or Android. I think the problem is in the script part of the file generated on iOS.

ZIP with example files attached: one created on PC, one on phone. The scripts are "Forever show string "PC"" and "Forever show string "Hello!"".

[example files.zip](https://github.com/Microsoft/pxt/files/844530/example.files.zip)

This might be a clue... After decoding the example files into binary, the bit with the script looks to be encoded differently in the two files - see pictures:

![bin-phone](https://cloud.githubusercontent.com/assets/989126/23949649/fd0c3b1c-097f-11e7-8bc5-37071782969a.JPG)

![bin-pc](https://cloud.githubusercontent.com/assets/989126/23949727/59960ade-0980-11e7-8738-13c240ae9e69.JPG)

**Comment by martinwork** [comment]
@pelikhan @abchatra 
I have now tested the round trip on iOS. Scripts saved to HEX files on iOS cannot be reloaded into PXT, which means users could lose their work. Should this issue be P1?

**Comment by martinwork** [comment]
After further testing
- HEX files downloaded on iOS 10.2.1 are OK
- HEX files download on iOS 9.3.5 have this problem

**Comment by abchatra** [comment]
This is fixed.
