### ISSUE TITLE
PXT loses string when importing Block Editor HEX

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt#1646]
Created "Forever Show string "Blocks"" in Block Editor on Windows IE 11 and compiled it to HEX.

On using PXT "Import file" the string "Blocks" is missing. See picture:

![blockstopxt](https://cloud.githubusercontent.com/assets/989126/23951628/86615dc4-0986-11e7-9fbc-99285b946a66.JPG)

**Comment by pelikhan** [comment]
It reproes without the forever.

**Comment by pelikhan** [comment]
[microbit-supernatural-script (3).zip](https://github.com/Microsoft/pxt/files/844906/microbit-supernatural-script.3.zip)
Unzip and d&d this file

**Comment by pelikhan** [comment]
microbit.co.uk xml payload
```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="device_print_message" x="90" y="47">
    <value name="message">
      <shadow type="text">
        <field name="TEXT">Hello!</field>
      </shadow>
      <block type="text">
        <field name="TEXT">Blocks</field>
      </block>
    </value>
  </block>
</xml>
```

equivalent PXT payload
```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="pxt-on-start" id="4S)%yl[MR*wzXu-(lrCs" x="0" y="0">
    <statement name="HANDLER">
      <block type="device_print_message" id="IKv0~FS.(enL}_=!11_I">
        <value name="text">
          <block type="text" id="!c;QWc6-_gBbUON2U+xa">
            <field name="TEXT">Blocks</field>
          </block>
        </value>
      </block>
    </statement>
  </block>
</xml>
```

**Comment by pelikhan** [comment]
The parameter is called "message" in microbit.co.uk.

**Comment by pelikhan** [comment]
I have a fix for this one.

**Comment by pelikhan** [comment]
Fixed in beta.
