### ISSUE TITLE
Search in documentation doesn't work in Edge

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1652]
Enable searching by clicking on the search icon.

**Comment by abchatra** [comment]
Works on IE11\Firefox & chrome

**Comment by microsoftsam** [comment]
Works for me. Can you try the latest? or perhaps it's a different repro.

**Comment by pelikhan** [comment]
Works for me.

**Comment by microsoftsam** [comment]
@abchatra still repro'ing?

**Comment by martinwork** [comment]
Does nothing in Safari on my iPhone and iPad with iOS 9. Works for me on macOS.

**Comment by abchatra** [comment]
Repros for me. Not for Richard. I could not create a small repro. May be I have weird settings in edge

**Comment by microsoftsam** [comment]
Repros for me on IOS. @abchatra are you using the sidebar TOC for this? I.e: did you have to pull out the TOC using the hamburger icon or not?

________________________________

**Comment by pelikhan** [comment]
Richard is on Android.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
Chrome on iOS treats the form submission as a pop up.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microsoftsam** [comment]
Yeah it seems IOS Safari doesn't like that it's target _blank. Removed that for the sidebar TOC.

**Comment by pelikhan** [comment]
Fixed.

**Comment by Helen09** [comment]
It looks still repro on Edge,Firefox,IE & Chrome,that search in documentation doesn't work.
![5](https://cloud.githubusercontent.com/assets/23466737/24179296/3e909664-0ee9-11e7-8036-036191120aef.gif)

**Comment by microsoftsam** [comment]
Clicking on the search icon isn't how that search works. Although come to think of it maybe it should. 
Search works on ENTER.

**Comment by abchatra** [comment]
Bing & google work on clicking search icon

**Comment by microsoftsam** [comment]
Yeah I agree @abchatra, we should enable that option.

**Comment by microsoftsam** [comment]
I shall use this issue to track that work.
