### ISSUE TITLE
Switch to JavaScript functions' explanation can't be read clearly 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1653]
Repro steps:
• Navigate to https://pxt.microbit.org/beta
• switch to JavaScript and then type "Math." on content pane
• A series of math functions will show and click "!"  on one of the functions right 
• Observe the function explanation

Expect result: Function explanation should be read clearly

Actual result: 
![1](https://cloud.githubusercontent.com/assets/23466737/23980001/f5d7b2f0-0a37-11e7-841d-6d7bf973a39a.png)

**Comment by microsoftsam** [comment]
Fixed in latest editor.
