### ISSUE TITLE
Microsoft logo incorrect in makecode

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1654]
![image](https://cloud.githubusercontent.com/assets/6107272/24004892/c672fc4e-0a24-11e7-8148-97a4a7c84f90.png)

The MakeCode homepage doen't show up right n IE and Firefox, see below. It’s better in Chrome and Edge but even then the ‘MakeCode’ part is not in the right font or size-matched to ‘Microsoft’.

**Comment by microsoftsam** [comment]
Fixed by e9411933adae8682ac01f78eda6cd721115941ff
