### ISSUE TITLE
pacakges: mechanism for giving users tips or details when adding pacakge

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1655]
When a user adds a new package, like filesystem, it would be good to be able to tell them "This pacakge requires this firmware" or "this package works with this sensor here"

Could we have a mechanism for communicating things to the users of packages, please?

**Comment by tballmsft** [comment]
We already have some messaging available when there is a conflict between packages. Should be able to leverage this for other purposes.

**Comment by pelikhan** [comment]
@jaustin, user story please?

**Comment by abchatra** [comment]
Won't fix for now.
