### ISSUE TITLE
packages: add package by URL?

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1657]
This is more a point for discussion than a direct feature request.

In a conversation with @carlosperate this week we talked about getting access to packages that weren't yet whitelisted.

Is there any mechanism to add a package directly to a project by putting the URL to the package.json in somewhere? This would help people test packages before they're whitelisted. 

It certainly subverts the point of a whitelist to some extent, but it also adds flexibility.

What do people think?

**Comment by pelikhan** [comment]
If you can circumvent whitelisting, then whitelisting is useless. We should revisit this feature. I agree, it is darn too hard to do packages right now.

**Comment by carlosperate** [comment]
Thanks for posting this Jonny, I almost forgot.
From my point of view, the whitelisting is most useful for discoverability (only whitelisted packages show in the "add package" menu/search) and as "stamp of approval" for the package quality.
If there was a way to add external packages by pointing to the json file directly, and perhaps block sharing the project, would then be any real disadvantages?

**Comment by abchatra** [comment]
I do want to solve this problem for package developer. 
One proposed solution:
 - User types the entire GitHub URL in the search box (which is not easy for kids to type in, but provides an workaround for package developers)
 - Display a warning message that it is unverified package.
 - Load the package and let the user try out the program. Though disallow publishing projects with the unverified package.

@jaustin, @pelikhan  any comments

**Comment by pelikhan** [comment]
"Though disallow publishing projects with the unverified package." Any script is potentially an unverified package. I don't think that makes sense.

**Comment by abchatra** [comment]
@pelikhan, yes sorry we can skip the last step.

**Comment by abchatra** [comment]
Fixed. We have add package by URL
