### ISSUE TITLE
Support for emitting warnings in the compiler

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#166]

**Comment by tballmsft** [comment]
@thomasdenney - do you have a progress report on this?

**Comment by tballmsft** [comment]
not quite clear what this is about - giving better error messages - or having warnings in addition to error messages?

**Comment by thomasdenney** [comment]
@tballmsft Having warnings and information messages in addition to error messages. For example, it would be nice if we could indicate when the user uses a JS feature that compiles but isn't available in blocks.

**Comment by mmoskal** [comment]
It's unclear how useful warning are for beginners. Should there even be a distinction between warnings and errors.

@tballmsft @pelikhan thoughts?

**Comment by pelikhan** [comment]
Correct warnings are useless - kids don't understand or read them. We should filter them out. I think the issue right now is that we were treating all warning/errors from TS as errors.

**Comment by mmoskal** [comment]
I don't believe TS generates warnings. It just treats stuff as errors that you wouldn't normally think are errors. If there are specific issues with errors, please file a separate issue.
