### ISSUE TITLE
Block "Custom" will not show in editor immediately and some code shows in content pane

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1664]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Click "JavaScript" and click "Explorer"
• Click "+" on the top right
• A diglog pops up and click "Go ahead" to add custom.ts

**Expect result:** 
Block "Custom" should show in editor immediately like other packages

**Actual result:** 
Block "Custom" will not show in editor immediately except I refresh the page and some code occurs in content pane
![2](https://cloud.githubusercontent.com/assets/23466737/24026117/eea536c0-0af9-11e7-98e5-f2192934d9a3.PNG)

**Comment by pelikhan** [comment]
This is the expected behavior. We should probably disable the JS toolbox for this kind of files.

**Comment by microsoftsam** [comment]
JS toolbox should be disabled in readonly views. It's a bug if not.

**Comment by pelikhan** [comment]
custom.js is not read only but there is no custom.blocks.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
Could we hide the monaco toolbar for .ts files that do not have a .blocks equivalent?

**Comment by tballmsft** [comment]
This is an advanced feature. I don't see the necessity for hiding the monaco toolbar. It's perfectly fine for the custom code to invoke other TS code.
