### ISSUE TITLE
Switch to JavaScript when I add a function in another function there is no function explanation and argument

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1667]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Click "JavaScript" and type "Math." in content pane
• Type "basic.showNumber( )" then add "Math." in "basic.showNumber( )"

**Except result:**
When I type "Math." in "basic.showNumber" there should show function explanations and argument

**Actual result:**
When I type "Math." in "basic.showNumber" there didn't show function explanations and function argument
![repro](https://cloud.githubusercontent.com/assets/23466737/24035714/a0662996-0b31-11e7-9fea-4137438e7980.gif)

**Comment by abchatra** [comment]
I think a bigger bug here is when you click on the information it shows white text in white background
![typescriptblocksnotworking](https://cloud.githubusercontent.com/assets/6107272/24065527/053aecac-0b29-11e7-93fe-a4b991421ca9.gif)

**Comment by microsoftsam** [comment]
@abchatra #1653 tracking the second issue you're seeing
