### ISSUE TITLE
share code/embed feature not working

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1669]
microbit.org-ticket: 1347

I had a ticket logged by Kitronik, saying that they had used the EMBED feature to embed their robot buggy code onto their resource page.

When I looked at it a day later, all I saw was an ON START and a FOREVER in a frame, with no code.

Unfortunately they have had to take this away as customers were complaining that they could not get access to the code, and they have now replaced it with a link to a download zip to get access to the buggy code (which was actually published in codethemicrobit.com - but that disappeared and we could not find any way to access the original code). 

Please could someone test out the embed feature thoroughly, and let us know if this works properly yet and is ready to be used by the users - thanks!

Here is the kitronik web page fyi

https://www.kitronik.co.uk/blog/part-6-coding-with-the-pxt-editor/

I could link you up privately with the person at Kitronik that was having this problem if you wanted to follow it up with them directly.

**Comment by pelikhan** [comment]
https://codethemicrobit.com is NOT in operation anymore.
