### ISSUE TITLE
finish github package intergration

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#167]
* [x] add search button in 'add package' - otherwise GH throttles us too hard
* [x] support pasting URLs in search: `https://github.com/mmoskal/pxt-i2c-fram`, `mmoskal/pxt-i2c-fram`, `mmoskal/pxt-i2c-fram#v0.2.1`
* [x] remove 'developer login' option
* [x] remove 'pxt publish' setting `ptr-pkg-...`; should still have anon publishing from command line
* [x] document no-forks-in-search
* [x] move over pxt-i2c-fram
* [ ] render package docs somewhere
* [x] preferred list of packages display in "add package"

There is related issue #124 about importing project

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/cb1d2d0f33986e0e85dbc1166df46e82a5099386

**Comment by tballmsft** [comment]
Where are we with this?

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/fa250da213da8e7f7e8b9a41c739152c3429f79f

**Comment by mmoskal** [comment]
I've split the docs issue into #230, as this seems slightly more complex than the other things in the list

**Comment by mmoskal** [comment]
ptr-pkg- thing fixed d926a2b928da3021f300507bc2fcf8f6d5f85052
