### ISSUE TITLE
Embed feature not working

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1670]
microbit.org-ticket: 1347

I had a ticket logged by Kitronik, saying that they had used the EMBED feature to embed their robot buggy code onto their resource page.

When I looked at it a day later, all I saw was an ON START and a FOREVER in a frame, with no code.

Unfortunately they have had to take this away as customers were complaining that they could not get access to the code, and they have now replaced it with a link to a download zip to get access to the buggy code (which was actually published in codethemicrobit.com - but that disappeared and we could not find any way to access the original code). 

Please could someone test out the embed feature thoroughly, and let us know if this works properly yet and is ready to be used by the users - thanks!

Here is the kitronik web page fyi

https://www.kitronik.co.uk/blog/part-6-coding-with-the-pxt-editor/

I could link you up privately with the person at Kitronik that was having this problem if you wanted to follow it up with them directly.

**Comment by pelikhan** [comment]
codethemicrobit.com got dropped from the certificate chain last week by accident. It is operational again. Please work with Kitronik to upgrade their links to https://makecode.microbit.org .

**Comment by pelikhan** [comment]
@guillaumejenkins codethemicrobit.com needs fixiing.

**Comment by DavidWhaleMEF** [comment]
Jonny has notified me that the embedded code on the kitronik website is now working again - did you guys fix it? Thanks if you did!

Would you be able to monitor the codethemicrobit.com domain stats and tell us if anyone is still hitting it with links? If we had the HTTP_REFERRER from your logs we could pro-actively go to people and ask them to update their links. Thanks

**Comment by pelikhan** [comment]
@mmoskal can we log those referrers?
