### ISSUE TITLE
embed feature keeps asking for cookie acceptance

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1673]
![screen shot 2017-03-17 at 19 00 44](https://cloud.githubusercontent.com/assets/25079586/24058728/338a74ea-0b44-11e7-91a6-1d1cf3f96524.png)

Every time I go to a web page that uses the pxt embed feature, it asks for cookie consent. Even though I have previously accepted the cookies

https://www.kitronik.co.uk/blog/part-6-coding-with-the-pxt-editor

**Comment by pelikhan** [comment]
If you dissallow cookies from 3rd party web sites, the iframe is not allowed to store any cookies or local storage. Thus, it thinks it displayed the first time on each page load.
