### ISSUE TITLE
Embed feature has unusual focus and scale

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1674]
How can customers focus and scale the embedded pxt code, so that it goes to a sensible zoom level and point on the page? If you look at the example from Kitronik below, it zooms and pans to an unusual position on the page...

https://www.kitronik.co.uk/blog/part-6-coding-with-the-pxt-editor

**Comment by DavidWhaleMEF** [comment]
![screen shot 2017-03-17 at 19 00 44](https://cloud.githubusercontent.com/assets/25079586/24058903/c6becc02-0b44-11e7-8c81-888f0e56b7e6.png)

**Comment by pelikhan** [comment]
The embed view currently uses the default initial zoom level and centering from blockly.
