### ISSUE TITLE
compiler problem (optional param)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1678]
https://pxt.microbit.org/60934-62272-98034-15353

works fine in browser. Generates panic (03) on micro:bit
```
interface Foo {
    a: number;
    b?: string;
    c?: boolean;
}

let x: Foo = { a: 2 }
basic.showString(x.b)
x.b = "foo"
basic.showString(x.b)
```

**Comment by tballmsft** [comment]
The problem above is that we generate a mapGet on b, but no mapSet has been done. We need to handle this case properly via a runtime check when a property is optional.

**Comment by pelikhan** [comment]
@tballmsft use fenced code section to improve bug readability...

**Comment by tballmsft** [comment]
The problem here is not with optional parameter. The DAL doesn't like null sent to showString.

**Comment by tballmsft** [comment]
OK. This is traced to a DAL issue. Let's leave our wrappers alone.

**Comment by abchatra** [comment]
Issue in DAL? Closing our issue
