### ISSUE TITLE
please add edit button for doc snippet

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1680]
It would be great if there is a button to take you to the editor (See below). Also have hover tips on the various icons.

![image](https://cloud.githubusercontent.com/assets/10767146/24065631/e2b6590e-0b29-11e7-8077-ce7b0881ffdd.png)

**Comment by tballmsft** [comment]
As discussed, only do this when doc is NOT inside iframe of web app.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/1758
