### ISSUE TITLE
The page couldn't display normally, it said that the page is missing

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#1684]
Repro steps:
Navigate to https://pxt.microbit.org/javascript-blocks or https://pxt.microbit.org/custom

**Expect result:**
The page could display normally
**Actual result:**
The page couldn't display normally, it said that the page is missing

![pxttest](https://cloud.githubusercontent.com/assets/11880996/24089706/7f40182c-0d74-11e7-9f52-3ae6951215b5.png)

**Comment by pelikhan** [comment]
These pages have moved to:

https://pxt.microbit.org/blocks/javascript-blocks
 https://pxt.microbit.org/blocks/custom

Where did you get the links?

**Comment by tballmsft** [comment]
@pelikhan - can we put in some redirects?

**Comment by yanlxu** [comment]
you can get the links follow these steps:
1. Navigate to https://pxt.microbit.org/reference 
2. click the "JavaScript blocks" or "Custom blocks" under "Blocks", then you will get the page https://pxt.microbit.org/javascript-blocks or https://pxt.microbit.org/custom

**Comment by WendyFeng01** [comment]
not repro on all browsers, you can close this bug.
