### ISSUE TITLE
Right-clicking 'Download' button does not save .hex file

### ISSUE THREAD

**Issue by rik-cross** [Microsoft/pxt#1686]
We're currently updating the [Code Club micro:bit projects](https://codeclubprojects.org/en-GB/microbit/) to use the PXT editor.

The automatic uploader is great, but it might not work for all clubs (for example schools with a non-standard Download directory location) so we need to cover alternatives.

It seems as though you should just be able to right-click on the ‘Download’ button and choose 'Save As' and select the micro:bit drive. This would be consistent across OSs and browsers. At the moment choosing 'Save As' downloads the web page and not the .hex file.

At the moment you can actually do this via the 'Download Again' link in the popup, but that's a weird workflow for us to recommend.

![screen shot 2017-03-16 at 16 48 35](https://cloud.githubusercontent.com/assets/18461167/24102889/49f6ae0a-0d75-11e7-804d-f5e62dedcc7f.png)

Is it possible that the first “Download’ button could have the same functionality as the ‘Download Again’ button, and allow users to right-click to save the .hex file?

**Comment by pelikhan** [comment]
Unfortunately, no. The download button triggers the download sequence and we do not have the binary yet at this point. We could rename the "download again" button to something like "Try again"?

**Comment by rik-cross** [comment]
Hi @pelikhan - thanks for the fast response!

No problem, we're just trying to come up with universal saving workflow, and the best we have currently is:

- Click 'Download'
- Right-click 'Download again', and choose 'Save as...'
- Choose your micro:bit drive and click 'Save'

I guess this is only for those clubs who can't use the standard download functionality, so not a problem if this is the best we can do.

I'm not sure renaming the 'Download again' button will help, so feel free to close the issue if there's nothing that can be done! :)

Thanks,
Rik.

**Comment by pelikhan** [comment]
Further investigation reveals that "Download Again" won't work on IE/Edge browsers (navigation to data-uri not supported  https://msdn.microsoft.com/en-us/library/cc848897.aspx
). We are going to hide the button for those browser as it just does not work there.

**Comment by pelikhan** [comment]
PR: https://github.com/Microsoft/pxt/issues/1686
