### ISSUE TITLE
Projects / Import file / Choose File may be using an incorrect mime type on iOS

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt#1689]
iOS console message is "Passed in type public.item doesn't conform to either public.content or public.data. If you are exporting a new type, please ensure that it conforms to an appropriate parent type."

I guess this means public.data should be used.

**Comment by pelikhan** [comment]
I am not sure what you are referring to...

**Comment by martinwork** [comment]
Using iOS Safari, choose "Projects", then "Import file", then "Choose File". At this point the iOS console shows the quoted message, which seems to suggest there's a problem. Maybe the links below help explain the console message... 

In the first link Apple says "A UTI in a functional hierarchy should conform through inheritance to a base UTI that is not public.item. For example, public.content, public.executable and public.archive are all examples of functional base UTIs."

The top answer in the second link says "You need to specify both a UTI for the functional as well as the physical hierarchy. For all files (but excluding bundles) you can use public.data + public.content. For really everything (including symlinks and folders) you would use public.item + public.content."

Uniform Type Identifier Concepts
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html

iOS Document/File type associations - wildcard UTI?
http://stackoverflow.com/questions/8017468/ios-document-file-type-associations-wildcard-uti

System-Declared Uniform Type Identifiers
https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html

**Comment by abchatra** [comment]
Closing this old issue. If the issue still persists please reopen in pxt-microbit repo
