### ISSUE TITLE
Crash caused by 'infinite' regular expression

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#169]
On the master branch, the editor crashes if you enter the following (type it, rather than pasting):

```typescript
let s = "supermassive long string that seems to go on forever but actually doesn't"
```
I found that in Chrome (Windows, OS X), and Edge the browser crashed when entering the apostrophe in `doesn't` to the point that I had to use Task Manager to close the browser. Safari on OS X didn't crash, but input handling slowed until there was significant lag. Firefox on Windows was a little more helpful and suggested that the browser was hanging on [this line](https://github.com/Microsoft/pxt/blob/master/webapp/src/ace.tsx#L422) in the Ace editor support:

```typescript
let textPos = editor.getCursorPosition();
let line = editor.session.getLine(textPos.row);
let linepref = line.slice(0, textPos.column)
let m = /((\w+\s*)*)$/.exec(linepref) //Offending line
```

According to [regexr](http://regexr.com/3dsr9) this regular expression 'can match 0 characters, and therefore infinitely many':

![infinitely-many](https://cloud.githubusercontent.com/assets/20356546/17172175/c30be4fc-53eb-11e6-8173-8b16138ad8cc.PNG)

I'm struggling to identify what the purpose of this regex is, so I'm not sure what the fix is.

**Comment by thomasdenney** [comment]
I've looked over every other regex in the code based and I couldn't find any others that are likely to cause the same bug.

**Comment by mmoskal** [comment]
The idea here was to get the list of space-separated words at the end of the line that should be used to filter the completion list results. I think it only works with fuzzy matching.

I changed the regexp to simpler.
