### ISSUE TITLE
 Search in docs gives Sandboxed error when "expand" used

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1692]
Search gives the following in debug console:

`"Blocked form submission to 'https://www.bing.com/search' because the form's frame is sandboxed and the 'allow-forms' permission is not set."`

This seems to come from "expand"

![image](https://cloud.githubusercontent.com/assets/866122/24121610/2fce0c82-0db9-11e7-92b6-bad0b0e82b81.png)

![image](https://cloud.githubusercontent.com/assets/866122/24121454/962a93e8-0db8-11e7-88a8-3f6a3b97f4e2.png)

**Comment by abchatra** [comment]
Can you please let us know the browser? I can't repro this.

**Comment by OwenBrotherwood** [comment]
Chrome on Microsoft.
Also edge
Question mark icon, for reference, then use expand (open documentation in new tab), then search for some text
