### ISSUE TITLE
JS runtime leaking implementation details on error

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1693]
We need to instrument code/runtime to ensure that user sees runtime error messages about their code, not about our runtime implementation. Classic example:
```
let a: number[] = null
basic.showNumber(a[0])
```
yields the lovely error message:

* Program Error: c.getAt is not a function

**Comment by tballmsft** [comment]
Fixed by https://github.com/Microsoft/pxt/commit/2506425c61e7ee1c56cae2e719566d09c179dc4d

**Comment by CenTdemeern1** [comment]
This has appeared again in makecode for micro:bit!!!
