### ISSUE TITLE
Switch to JavaScript, the Block's explanation still shows up on content pane

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1694]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta on Edge
• Click "Basic" and the Basic blocks dialog pops up
• Select "show number" and move to the block right space to wait the block explanation shows up
• Click "JavaScript" to observe the content pane

**Except result:**
 Block explanation shouldn't show up on JavaScript content pane

**Actual result:**
Block explanation still shows up on JavaScript content pane and couldn't be closed
(repro browser:Edge)
![1](https://cloud.githubusercontent.com/assets/23466737/24135891/3951ec9a-0e47-11e7-98df-a91cd06fd0ef.gif)

**Comment by microsoftsam** [comment]
Doesn't repro on Chrome, Firefox or Safari on mac. As everytime I hover out from a block, the popout pane disappears. Labeling as browser compat.

**Comment by Helen09** [comment]
Yes, it only repro on Edge.
