### ISSUE TITLE
There lack a back button on "? -->Projects","? -->Reference" and "? -->Blocks" 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1695]
**Repro steps:**
 •Navigate to https://pxt.microbit.org/beta
•Click ? --> Blocks --> Logic -- > if

**Expect result:**
 There should add a back button that I can return to the previous level
**Actual result:**
I couldn't return to the previous level to check other blocks' usage
![22](https://cloud.githubusercontent.com/assets/23466737/24137310/2934f3e6-0e4e-11e7-96b7-ebfb50e8227b.PNG)

**Comment by microsoftsam** [comment]
No longer showing references in the side menu.
