### ISSUE TITLE
The description of block Examples don’t match with blocks in Reference

### ISSUE THREAD

**Issue by charmian01** [Microsoft/pxt#1696]
1 .**Repro steps**:
•	Navigate to https://pxt.microbit.org/reference/devices/signal-strength
•	Observe the Examples

 **Expect reault:**
 The content should show the "signal strength" block examples
 **Actual result:**
 Shows "on signal strength changed" block examples
 ![p2](https://cloud.githubusercontent.com/assets/23711238/24137991/53c3a398-0e51-11e7-80b3-61c99cd986be.PNG)

2 .**Repro steps**:
•	Navigate to https://pxt.microbit.org/reference/devices/raise-alert-to
•	Observe the Examples 

 **Expect result**: 
 The different description should match with different blocks content.
 **Actual result**: 
 ![p5](https://cloud.githubusercontent.com/assets/23711238/24138153/0bf1bb9e-0e52-11e7-8481-bfe19e2e5bc3.PNG)

**Comment by abchatra** [comment]
First one seems like a decompiler bug.

**Comment by riknoll** [comment]
@abchatra Nope, not a bug. We don't support optional parameters in the blocks so it won't decompile if you pass the second argument. The second one is strange. The API looks like it takes in a string, so I don't know why it's being rendered as a dropdown. Decompiler doesn't know what to do with it so it always decompiles to the first entry.

**Comment by charmian01** [comment]
These two bugs seem like fixed.
The first one now shows: 
![capture1](https://cloud.githubusercontent.com/assets/23711238/24386132/7e7d7916-13a0-11e7-898e-e1cff7662e45.PNG)
The second one now shows :
![capture2](https://cloud.githubusercontent.com/assets/23711238/24386153/9d325e3a-13a0-11e7-93b4-fc2eb3888bb1.PNG)

**Comment by pelikhan** [comment]
I am looking into the Bluetooth stuff. Fixed those docs.
