### ISSUE TITLE
The blocks picture displays incompletely in "?"-->"Blocks"

### ISSUE THREAD

**Issue by charmian01** [Microsoft/pxt#1697]
**Repro steps:**
•	Navigate to https://pxt.microbit.org/blocks
•	Observe the blocks picture

**Expect result:**
![p4](https://cloud.githubusercontent.com/assets/23711238/24138502/64de964a-0e53-11e7-84cd-2b10c356b0a0.PNG)

**Actual result:**
![p3](https://cloud.githubusercontent.com/assets/23711238/24138515/6ff8b858-0e53-11e7-971a-3f9992a2003d.PNG)

**Comment by abchatra** [comment]
This is not a bug, we don't show shadow variable in documentation. As far as I know this is intentional.
