### ISSUE TITLE
When click  “pulseln” block in reference, it’s not responsive.

### ISSUE THREAD

**Issue by charmian01** [Microsoft/pxt#1698]
**Repro steps:**
•	Navigate to https://pxt.microbit.org/reference/pins
•	Click “pulseln” block
![p8](https://cloud.githubusercontent.com/assets/23711238/24138783/91bc9b48-0e54-11e7-8ce3-ee141037834c.PNG)

**Expect result :**
There is a hyperlink to response.
**Actual result :**
There is no responsive.

**Comment by ganicke** [comment]
Enabled doc link for API.

https://github.com/Microsoft/pxt-microbit/pull/457
