### ISSUE TITLE
After clicking "Documentation" the page will back to https://pxt.microbit.org/

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1699]
**Repro steps:**
• Navigate to https://pxt.microbit.org/reference
• Click “Documentation”

**Expect result:**
 The page shouldn't back to https://pxt.microbit.org/
**Actual result:**
 After clicking "Documentation" the page will back to https://pxt.microbit.org/
![3](https://cloud.githubusercontent.com/assets/23466737/24139864/bc77c8a4-0e58-11e7-9ee2-345c3de3c2c0.gif)

**Comment by abchatra** [comment]
I do see why the behavior is confusing, though it is intentional.

**Comment by pelikhan** [comment]
Good point. We should have a button "Editor"...

**Comment by microsoftsam** [comment]
I think the fix here is to only have the editor Icon go back to the editor (with a title "Go to editor"). The Documentation heading is for the sidebar / page.

**Comment by microsoftsam** [comment]
Fixing as part of https://github.com/Microsoft/pxt/pull/2770
