### ISSUE TITLE
The garbage in Editor is in a absolute position

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1700]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Zoom out the page until the Editor shows up a scrollbar
• Drag the "On Start" block to Editor and a garbage will show up
• Pull down the scrollbar and darg one block to Editor again 

**Expect result:**
 The garbage should show up with the scrollbar
**Actual result:**
 The garbage didn't show up
![4](https://cloud.githubusercontent.com/assets/23466737/24142863/e21f65d0-0e62-11e7-9d31-9c6d86e27cd0.gif)

**Comment by abchatra** [comment]
Won't fix
