### ISSUE TITLE
Import Project loses project name

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1701]
Repro: Projects - Import Project, choose a .hex file with a custom name (not Untitled)
Result: Project loads as Untitled
Expected behavior: Project loads with the saved custom name

**Comment by abchatra** [comment]
@Jaqster Doesn't repro for me. Please provide the hex file. Note if you have manually renamed the hex file it won't show up in the name, it needs to be in hex file.

**Comment by Jaqster** [comment]
Repros pretty consistently for me - found this when I was running through my demo today, but just realized I was using production.  Looks like it's fixed in Beta.  We should do a release... but maybe after my last session on Thurs..,
