### ISSUE TITLE
Download screenshot doesn't capture images

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1704]
![image](https://cloud.githubusercontent.com/assets/6107272/24170643/bde64216-0e3e-11e7-80a8-ceff2c887409.png)
Right click on blocks editor->Download screenshot

**Comment by pelikhan** [comment]
We need to fix the background color too.

**Comment by pelikhan** [comment]
The image need to be imported as data-uri instead of linked image urls.

**Comment by abchatra** [comment]
@Jaqster -fyi
@pelikhan, @microsoftsam is there a easy way to fix this? Partners need this for documentation.

**Comment by Jaqster** [comment]
This is super important for Minecraft where we have images all over the place.

**Comment by pelikhan** [comment]
The fix is: scan for images in svg, download any linked image and replace URL with data-uri encoded image.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/1898

**Comment by pelikhan** [comment]
![microbit-screenshot 6](https://cloud.githubusercontent.com/assets/4175913/25010129/fe31fb26-201d-11e7-805a-e777c48640d9.png)

**Comment by pelikhan** [comment]
We are also rendering at a 4x higher resolution for better quality.

**Comment by abchatra** [comment]
Thanks @pelikhan  Pretty cool!
