### ISSUE TITLE
Only part of Bluetooth block is selected and Number type's help could be clicked

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1708]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Drag Bluetooth block like the below picture and put it under Block "forever"
• Click the block to observe
• Click on the right of the block to look "help" 

**Expect result:**
1、When click the block the entire block should be selected
2、The Number type should have reference like Boolean type or the "help" button should be disabled
**Actual result:**
1、Just a part of the block is selected 
2、The Number type didn't have reference but the "help" button can be clicked
![6](https://cloud.githubusercontent.com/assets/23466737/24187471/09a17de0-0f18-11e7-9df6-5da94abfab75.gif)

**Comment by ganicke** [comment]
Help for 'number' needs correct help path set in built-in block definitions. Fixed in https://github.com/Microsoft/pxt/pull/2695.
