### ISSUE TITLE
Search issue in package search box

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1709]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Click "+ Add Package" to search some packages

**Expect result:**
The search reasult should match the search content
**Actual result:**
![7](https://cloud.githubusercontent.com/assets/23466737/24188903/004edf3e-0f1e-11e7-9e4b-b78e01261ce0.gif)

**Comment by pelikhan** [comment]
We use the GitHub search feature. We do not control their relevance.
