### ISSUE TITLE
unhandled() should be localized and have error numbers

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#171]
I think it will need to look something like this:

```
unhandled(node, 9123, lf("only one foobar supported"))
```

Error codes are allocated sequentially, based on comment on `userError()` in `emitter.ts`.

**Comment by thomasdenney** [comment]
OK, I'll start making changes in https://github.com/Microsoft/pxt/pull/165

**Comment by abchatra** [comment]
This is fixed
