### ISSUE TITLE
pxt init does not appear to include line for PXT/TARGET

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1713]
https://pxt.microbit.org/packages

> Make sure you keep the line for PXT/TARGET (where TARGET is the target id) in README.md. Otherwise the package will not show up in search.

after following doc, pxt init README.md is empty

**Comment by pelikhan** [comment]
Oh, that's silly. Need to fix this.

**Comment by OwenBrotherwood** [comment]
I cannot confirm that the fix works: I need to double check my installation 
(I pulled latest pxt from github and followed doc for github prep and usage)

**Comment by pelikhan** [comment]
Fixed in beta. Run "pxt update" and try again

**Comment by OwenBrotherwood** [comment]
(aarg: I was on exploreraddfile branch)
