### ISSUE TITLE
Download to micro:bit - Usability

### ISSUE THREAD

**Issue by tracygardner** [Microsoft/pxt#1728]
Related issues have been raised before:
https://github.com/Microsoft/pxt/issues/1686 
 https://github.com/Microsoft/pxt/issues/888 

But downloading to the micro:bit from PXT is our biggest pain point. 

I'm using it in a Code Club and with upper Key Stage 2. Downloading becomes the main focus of the lesson!

Would it be possible to use a 'Save As' approach like most online editors do? Are there any issues with saving direct to the micro:bit?

I know you also download to the Downloads directory. But that's our other pain point. Downloads and local browser storage are wiped every session. Children have to copy their files somewhere else to keep them. A "Save As" dialog would mean they could just save somewhere else.

**Comment by pelikhan** [comment]
The only fix available in IE/Edge is to remove that button.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tracygardner** [comment]
@pelikhan Check the full issue. (My fault, randomly did something that caused a premature submit and then editted.)

Is 'Save As' an option?

**Comment by pelikhan** [comment]
We tried that as well to no avail. IE/Egde will not allow to open or save as a data:... file. At least in our testing it didn't.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tracygardner** [comment]
Not sure I understand. Are you saying you can't use a standard browser 'Save As' dialog (like you would in Scratch) with the hex file? 

In Edge things aren't too bad, you can just click 'Save As' in the dialog that pops up. The issue here is that the instructions tell you to save and then send the file: https://pxt.microbit.org/device/usb/windows-edge which is much more complex!

In Explorer you can change the option from 'Save' to 'Save As' - a bit less straightforward. But again the instructions make it seem much harder. 

In Chrome there's no option to choose where you save (well you can click 'Show All' and then right-click on the link there.) It works nicely with the uploader once you have it running. But the children find this tricky, they forget to run it, or they cancel the Agreement Window, or close the Window once they've gone through process, or don't see the message telling them the board can't be detected ...

The overall issue is that behaviour is different in every browser! Having a 'Save As' option just for Chrome (and Firefox?) might make the overall behaviour a bit more consistent.

**Comment by pelikhan** [comment]
The "download again" button is there on the case where the first download got blocked.

Unfortunately (or fortunately), a web page cannot control how browsers handle downloads.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tracygardner** [comment]
Just checking that we're talking about the same thing. When I say a 'Save As' dialog, I mean what you get in scratch.mit.edu or pixlr.com/editor when the OS Save As dialog pops up in pretty much the same way regardless of which browser you are using. 

From those editors I can save a file to the micro:bit (not that it does me any good!) Does this not work with .hex files?

**Comment by pelikhan** [comment]
MakeCode produces .hex in memory and encodes them into a data-uri. Edge/IE block the "Save As" of such files. Scratch and pixlr.com/editor use Flash which we do not support.

**Comment by pelikhan** [comment]
- pxt.makecode.org provides a "share" functionality that stores the project in the cloud.
- try https://www.touchdevelop.com/microbituploader which automatically downloads the file to any attached microbits

**Comment by pelikhan** [comment]
Agreed it's a mess.

**Comment by tracygardner** [comment]
OK, a few things then:

1. Yes, I've been using the uploader (see above and once I got the non-standard download directory changed ...). It's surprisingly turned out to be harder (and less useful to learn) than teaching the children the other approaches. According to children a little pop up box like that is just asking to be closed ... And they never remember to run it. It's another moving part. 

2. A short-term solution would be to have browser-specific help (and possibly a link to the uploader?) in the Download pop-up. Then the help is available where it's needed. (Please don't say ask your teacher, we've got other things to be doing!) As I mentioned above the current help pages make things seem much more complex than they actually are. Am I missing something? E.g. in Edge I can just click 'Save As' and choose the micro:bit drive, but the instructions given are much more complicated: https://pxt.microbit.org/device/usb/windows-edge (similarly for IE.)

Just offering the 'Download Again' link where it does work and calling it 'yourfile.hex' and giving help to explain that you can right-click and save as and choose your micro:bit would help. 

Then you'd have a solution that works in a reasonably similar way across browsers and the user would be guided through the differences.

(In Chrome there's a setting to force a dialog for saving but it's not the default behaviour any more and the settings often aren't available in schools. On Windows with Chrome I find the easiest thing is to just grab the file from the bottom of the browser and Alt-Tab to the File Manager Window that opens for the micro:bit and let go, but that's a tricky manoeuver for kids. FYI in Ubuntu it's trivial as I just drag the .hex slightly the the left and onto the USB drive in the sidebar. In Windows pinning the drive to the task bar isn't quite as smooth and doesn't happen automatically.)

3. A single button cross-browser solution would be even better. Yes there are technical issues, but surely it's worth working out what the best solution would be and pushing for fixes wherever they're needed?

**Comment by tracygardner** [comment]
BTW PXT is looking awesome which is why I'm so keen to have a workable solution for this bit of the process.

**Comment by pelikhan** [comment]
I have updated the docs for i.e./edge/ff + callout on the documentation page. I will see about special casing the download dialog for those browsers

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/commit/684646d3de8d8fcb3f6bf3fa55f1071db944bfe0

**Comment by tracygardner** [comment]
Thanks, that should make the experience a bit smoother.

**Comment by pelikhan** [comment]
I'll close this for now. Feel free to reopen if more fixes need to be added.
