### ISSUE TITLE
Visual accessibility options

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1732]
microbit.org-ticket: 1416

How can we change the colour scheme of the PXT editor to use high-contrast settings for visually impaired users, like we can do with the TouchDevelop editor?

**Comment by pelikhan** [comment]
Not supported yet.

**Comment by DavidWhaleMEF** [comment]
Ok, thanks.

We have some visually impaired students that are struggling to use the editor without a high contrast version - is there anything quick we might be able to do with a css hack or something perhaps?

**Comment by pelikhan** [comment]
@microsoftsam @abchatra we had a color-blind scheme for the simulator that we should bring back. we need a button to toggle it on/off

**Comment by pelikhan** [comment]
@DavidWhaleMEF  In beta, you will find a "High Contrast On/off" menu item to load the accessible theme in the simulator.

**Comment by DavidWhaleMEF** [comment]
Great, thanks! The customer will be very pleased with this!

**Comment by jaustin** [comment]
Anyone visiting this issue might also like to see https://github.com/Microsoft/pxt/issues/2407
