### ISSUE TITLE
when use the blocks "serial write string" and "serial write number" independently,  the serial port didn't display under the simulator

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1737]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Drag “serial write string” block and put it into "forever" 

**Expect result:**
when use the blocks "serial write string" and "serial write number" independently,  the serial port should display under the simulator
**Actual result:**
when use the blocks "serial write string" and "serial write number" independently,  the serial port didn't display under the simulator
![8](https://cloud.githubusercontent.com/assets/23466737/24278072/7cec4590-107c-11e7-88b4-3f18a177d934.gif)

**Comment by pelikhan** [comment]
Serial entries are pushed to the UI on new line characters so this is expected.

**Comment by Helen09** [comment]
So if it is expected only put "serial write string" under "forever", nothing shows below simulator?

**Comment by pelikhan** [comment]
Currently yes. Could probably be better and flush after a certain amount of chars.

**Comment by Helen09** [comment]
![9](https://cloud.githubusercontent.com/assets/23466737/24279396/9cde106a-1084-11e7-9396-068dfc7db23c.gif)
Yes, it will be better when put "serial write string" under "forever" then the result shows.

**Comment by abchatra** [comment]
@pelikhan  is this fixed?
