### ISSUE TITLE
This program didn't write the word BOFFO to the serial port repeatedly on reference

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1739]
**Repro steps:**
• Navigate to https://pxt.microbit.org/reference/serial/write-line to run the example

**Except result:**
 This program should write the word BOFFO to the serial port repeatedly.

**Actual result:**
I can't see this program writes the word BOFFO to the serial port repeatedly.
![11](https://cloud.githubusercontent.com/assets/23466737/24285044/42bf8f1c-10a9-11e7-8002-bd8ed5960b68.gif)

**Comment by pelikhan** [comment]
Serial only supported in IDE

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/1748
