### ISSUE TITLE
TD Import: Can we make the 'function' blocks collapsable 

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1741]
As we're looking at importing large TD scripts, we see many of them are quite sensible in blocks except for the size of the functions.

If functions were collapsable, then we could have some slightly cleaner experession in blocks for kids:

For example:
Original TD script: microbit.co.uk/riotng
Published PXT script: https://pxt.microbit.org/69553-47064-95594-46003

If there was, for example a standard block syntax we could add to the functions when importing from TD to show them simply in the block editor, that would be ideal.

**Comment by pelikhan** [comment]
You should import TD script into the JavaScript view.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jaustin** [comment]
We did import it into JS view, but then switching to blocks could be really great if we had something a little cleaner.

Lots of TD resources make use of the fact that the child facing code is very simple because of the functions, so something to help migrate that property over would be great - for example it could be that TD functions end up in a custom.ts by default.

We currently have something that looks like this
```
Simple-------------------------------------------------------------------Powerful but more complex

    <----Blocks----------------->-------TD-------------------->
    
<-------MakeCode-Blocks----------------->(The Whale Gap)<-------Javascript--------------->    
            
```

We want to fill the Whale Gap

**Comment by pelikhan** [comment]
@riknoll , could you detect that an unsupported block contains a function and simply hide the body?

**Comment by DavidWhaleMEF** [comment]
The 'whale gap' here refers to the code that would be written in javascript (and doesn't necessarily have to have a good round trip to blocks), but provides a lot of functions that support the application script that is in blocks.

Perfect Pancakes, for example, has a top level app that would be great in blocks, but a whole load of support functions that just need to be in the project enabling the main app to work. 

We would probably then auto-import, and any functions would go into a .ts in the explorer, and calls to those functions would be peppered as grey blocks around the main app script in blocks.

Perfect Pancakes is http://microbit.co.uk/riotng (as a good working reference).

A key point here is that people start with just blocks. At some point they need some snippets of more advanced code to make things work, but still want to work in blocks (but the more complex things are fine in just javascript and you don't want lots of large grey function blocks all over your script).

So, step 1... write a block script
Step 2, write some supporting bits of javascript to make bigger things work, but stay generally in blocks 
Step 3 - eventually migrate your working method to all javascript.

Step 3 ("the whale gap") actually covers a lot of use cases. The move from all blocks to all javascript is a big step, having step 2 in the middle is really enabling.

**Comment by riknoll** [comment]
Might be able to make it toggleable, we could have a dropdown that lets you show or hide the body. Thoughts?

**Comment by pelikhan** [comment]
I would keep it simple: {...}

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tballmsft** [comment]
Using Peli's new feature to expose TypeScript functions as blocks, you can get much close to what you want. See this:

https://pxt.microbit.org/05242-79661-72045-97908

**Comment by tballmsft** [comment]
Fixed up a minor error:

https://pxt.microbit.org/90234-73318-05675-33831

I think this feature will address what you want. Use the custom feature to create your library code and expose the functions you want as blocks.

**Comment by DavidWhaleMEF** [comment]
Thanks Tom. 

I had it in my mind that would be one way to do it. 

However, we have a number of scripts (and users will too) where functions have been used in TD - I was sort of hoping that there would be a simple visual and automated way to hide-away those function definitions that would be pulled in as part of an automated migrate, so that no manual user intervention would be required when users later mass migrate all their TD scripts into MakeCode?

As a thought, If visual collapsing of functions is hard to do, would it be possible for the migrate process to pick out any function definitions that come in from the user script and stuff them in a custom.ts automatically for us? The visual result would be identical to what you show above, but it would then be automatic and not require the user to manually cut and paste all their functions?

Thanks!

**Comment by tballmsft** [comment]
If there is a library, we could try and hide it in custom. That would be the easiest to automate.

**Comment by tballmsft** [comment]
The other thing to do (easiest) would be to keep just the main function in blocks and hide away all other functions. Then, we could allow the user to "unhide" a block and bring it into main.ts.

**Comment by pelikhan** [comment]
Functions in main.ts are considered chunks of typescript and show up as greyed out area. We could simply render the signature only and keep the full source internally.
