### ISSUE TITLE
Set brightness crashes micro:bit

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1743]
microbit.org-ticket:1430

I run this code on my microbit and it crashes the micro:bit

It displays a heart then it displays this pattern

.....
.....
.x...
.xxx.
.....

[microbit-brightness.hex.zip](https://github.com/Microsoft/pxt/files/867873/microbit-brightness.hex.zip)

**Comment by DavidWhaleMEF** [comment]
pxt.microbit.org version: 0.9.55
Microsoft MakeCode version: 0.12.1
C++ runtime version: v2.0.0-rc8

**Comment by pelikhan** [comment]
This is a DAL issue: the PXT setBrightness is merely a call to the DAL.
```
    void setBrightness(int value) {
       uBit.display.setBrightness(value);
    }
```

**Comment by finneyj** [comment]
Just for audit - not actually a crash, but some poor behaviour in the display driver did leave some LEDs illuminated when brightness was set to 0. Now fixed in microbit-dal master branch,

**Comment by DavidWhaleMEF** [comment]
Jo says on the DAL ticket that this fix made it into DAL rc9.

rc9 is in beta, rc8 is on live. So it's not specifically fixed for the user yet, but I'll get them to try it in beta and make sure it fixes the problem in their script. This will eventually bubble out to pxt live
