### ISSUE TITLE
Script got corrupted without user interaction, but not sure how

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1744]
Hi all,

I'm afraid this is a slightly frustrating one because I don't have the the exact reproducing case, but I saw this happen so know it's real.

One of the micro:bit foundation team previously copy/pasted David's fun script into PXT to try it out:
```
let p =[
    DigitalPin.P0, DigitalPin.P4, DigitalPin.P5, DigitalPin.P6,
    DigitalPin.P7, DigitalPin.P1, DigitalPin.P8, DigitalPin.P9,
    DigitalPin.P10, DigitalPin.P11, DigitalPin.P12, DigitalPin.P2,
    DigitalPin.P13, DigitalPin.P14, DigitalPin.P15, DigitalPin.P16
]
let d = 50
basic.forever(() => {
    for (let index = 0; index <= p.length; index++) {
        pins.digitalWritePin(p[index], 1)
        basic.pause(d)
        pins.digitalWritePin(p[index], 0)
        basic.pause(d)
    }
    for (let index = p.length - 1; index >= 0; index--) {
        pins.digitalWritePin(p[index], 1)
        basic.pause(d)
        pins.digitalWritePin(p[index], 0)
        basic.pause(d)
    }
})
```

It definitely worked at the point it was pasted in 1 month ago. It had not been changed since. 

At some point today, *without* the suer editing the script, it had become:
```
let d = 0
basic.forever(() => {
    for (let index = 0; index <= p.length; index++) {
        pins.digitalWritePin(DigitalPin.P0, 1)
        basic.pause(d)
        pins.digitalWritePin(DigitalPin.P0, 0)
        basic.pause(d)
    }
    for (let index2 = p.length - 1; index2 >= 0; index2--) {
        pins.digitalWritePin(p[index2], 1)
        basic.pause(d)
        pins.digitalWritePin(p[index2], 0)
        basic.pause(d)
    }
})
let p = [
    DigitalPin.P0, DigitalPin.P4, DigitalPin.P5, DigitalPin.P6,
    DigitalPin.P7, DigitalPin.P1, DigitalPin.P8, DigitalPin.P9,
    DigitalPin.P10, DigitalPin.P11, DigitalPin.P12, DigitalPin.P2,
    DigitalPin.P13, DigitalPin.P14, DigitalPin.P15, DigitalPin.P16
]
d = 50
```

I think there was an editor upgrade involved as when they first 'arrived' there was a message about being unable to convert to blocks, then the editor reloaded. There was also a switch to blocs and back to javascript. We do not know exactly when the corruption happened.

Is this a known issue somewhere? Should we do some work to try and make it happen again?

**Comment by pelikhan** [comment]
Events always move to the top of the function when roundtripping. The ``p`` declaration is not understood in blocks so it becomes a javascript blocks. @riknoll the p declaration is not hoisted to the head of the function as a side effect.

![microbit-screenshot](https://cloud.githubusercontent.com/assets/4175913/24298190/7bb88248-1062-11e7-958b-5ec539560bed.png)

**Comment by jaustin** [comment]
So I've just noticed this still happens on live!

I'm really concerned that we're still knocking into these javascript conversion issues one at a time...

@riknoll - Is there really no correctness tests we can make after converting to be sure we didn't break things?

**Comment by jaustin** [comment]
Should bugs that damage a users's program be P0?

**Comment by pelikhan** [comment]
@jaustin this issue is fixed in beta.

**Comment by abchatra** [comment]
_Should bugs that damage a users's program be P0?_
P0 are for the bugs where a important feature is completely broken for majority of users. Here not all the scripts are broken. This is P1 from my perspective. Do let me know if it is ok.

**Comment by jaustin** [comment]
Yep. Based on that description I concur this is P1.

Good to see it fixed in beta :)

J
