### ISSUE TITLE
report abuse link in share code looks like it does nothing

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1749]
If I click on the REPORT ABUSE link in a user shared page, it feels like the link is doing nothing.

Perhaps it is sending you a report behind the scenes, but it would be nice to have some user feedback to say that the page has been reported and that a person will review it. Otherwise, it just feels like a broken link.

**Comment by pelikhan** [comment]
It does send a report. We should have a popup saying the report was sent.

**Comment by pelikhan** [comment]
Dialog fixed.
