### ISSUE TITLE
getting a high resolution screen shot

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1750]
microbit.org-ticket: 1391

The new screenshot feature is very useful. However the image comes out at quite a low resolution, and the customer wants to use them in print media.

Presumably the rendering is from a vector graphics source, would it be possible to optionally generate a SVG or some other vector graphics format that could be scaled infinitely for print use?

**Comment by pelikhan** [comment]
Fonts are not packaged in the SVG so there is no guarantee that the editor will eventually see the same image.

**Comment by abchatra** [comment]
This is fixed.
