### ISSUE TITLE
The Navigation bar(such as Docs>Reference>Basic) shows error.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#1766]
**Repro steps:**
•	Navigate to https://pxt.microbit.org/reference 
•	click “packages” (“FAQ, Translate”, “Sharing project”, “Offline support”, Streaming, Packages, “Command Line interface”, “Visual Studio Code support” , “Coding on Raspberry Pi” )
•	Observe the upper-left corner navigation bar of the page

**Expected result:**
The navigation bar should show normal, such like:
![1](https://cloud.githubusercontent.com/assets/17866936/24396027/6219426c-13d4-11e7-8498-a29bd864df24.PNG)

**Actual result:**
The upper-left corner navigation bar show like follows:
![2](https://cloud.githubusercontent.com/assets/17866936/24396017/5a10eee4-13d4-11e7-83c7-6bd8ff9afbb2.PNG)

**Comment by ganicke** [comment]
Reference SUMMARY entries updated for current APIs.

See: https://github.com/Microsoft/pxt-microbit/pull/507.
