### ISSUE TITLE
The reference page of Block “analog set pitch pin p0”  has error.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#1767]
**Repro steps:**
•	Navigate to https://pxt.microbit.org/reference/pins 
•	Click “analog set pitch pin p0” 

**Expected result:**
It should show the block’s reference page normal.

**Actual result:**
![3](https://cloud.githubusercontent.com/assets/17866936/24396262/1d3cd3e2-13d5-11e7-88dd-d29ed603d5b7.PNG)

**Comment by ganicke** [comment]
Enabled doc link for API.

https://github.com/Microsoft/pxt-microbit/pull/457
