### ISSUE TITLE
When add the "devices","radio" and "bluetooth" packages, the added package will disapper in the packages pop up window

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#1768]
**Repro steps:**

- Navigate to https://pxt.microbit.org/beta
- Click "Add Package" and choose the "radio"
- Then click the "Add Package" again

![package1](https://cloud.githubusercontent.com/assets/23497626/24396182/280cf582-1357-11e7-96fd-48919a5f58e2.gif)

**Comment by pelikhan** [comment]
By design.
