### ISSUE TITLE
The description of block Examples don’t match with blocks in Reference

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#1769]
Repro steps:

- Navigate to https://pxt.microbit.org/reference/devices/tell-camera-to 
- Observe the description

![image](https://cloud.githubusercontent.com/assets/23497626/24396695/eae374f4-1358-11e7-80f6-2991fbf83683.png)

**Comment by microsoftsam** [comment]
Description doesn't always have to match word to word.
By design.
