### ISSUE TITLE
HW Feature Request - reset button to wipe current program

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1774]
Request from a teacher who uses a classroom set of devices with multiple classes.  He wants an easy way to 'reset' all devices, wiping the previous class's code, so the new class won't have the final project already loaded.

**Comment by abchatra** [comment]
@Jaqster I don't understand this request. We already have "Reset" as the config options. Also we in the browser and don't know who belongs to which class.

**Comment by pelikhan** [comment]
I can see the pain point of the teacher but this gets us into device management solutions which is beyond the scope of this project IMO.

**Comment by abchatra** [comment]
Out of scope

**Comment by Jaqster** [comment]
I think we should at least bubble this feedback up to the Foundation.  CP reset button is a nice feature that the micro:bit should look to emulate...
