### ISSUE TITLE
"Cannot find name 'document'" message(program is legal)

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1778]
![1](https://cloud.githubusercontent.com/assets/23466737/24437116/e984bc2a-1471-11e7-8df2-57661c68fca4.png)

**Comment by Helen09** [comment]
This is the Share Project:
https://pxt.microbit.org/36243-93093-79930-75480

**Comment by microsoftsam** [comment]
document is not an object we support. (This isn't browser javascript)
The micro:bit can output something to the user through LEDS, pin OUTs, or serial.
