### ISSUE TITLE
Compass lesson is not labelled as a compass lesson, and it has a bug

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1782]
microbit.org-ticket: 1459

I'm trying to migrate a blocks user who has found a bug in the blocks compass lesson over to PXT, but the PXT compass lesson that I found in the pxt/lessons page doesn't seem to be described as a compass lesson? It refers to 'creating a die on the micro:bit'.

https://pxt.microbit.org/lessons/compass

![screen shot 2017-03-29 at 14 20 35](https://cloud.githubusercontent.com/assets/25079586/24456430/e4c86240-148a-11e7-8a1f-5b1471e2a5a8.png)

It *is* a compass lesson, but also note that it suffers from the same bug as the original compass lesson in blocks that the user is complaining is wrong

https://www.microbit.co.uk/blocks/lessons/compass

![screen shot 2017-03-29 at 14 21 47](https://cloud.githubusercontent.com/assets/25079586/24456531/33680a86-148b-11e7-9910-31786ce96fb7.png)

Is it possible for someone to fix this lesson please, so that we can at least try to migrate this user over to the new editor?

Thanks

**Comment by pelikhan** [comment]
Fixed.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/commit/a2a28391d0f17bdb37adaa5780aaef7ecb9aba8e
https://github.com/Microsoft/pxt-microbit/commit/b3ad4e5b4dd9499dd988b438952858e49f34b394
