### ISSUE TITLE
basic.plotLeds doesn't convert to blocks

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1788]
Put the following code into JavaScript and then move to Blocks editor:
```
basic.plotLeds(`
    . . . . .
    . . . . .
    . . # . .
    . . . . .
    . . . . .
    `)
```

**Comment by pelikhan** [comment]
There is no block for it. We could easily add one under the "led" category. Is that what we want?

**Comment by tballmsft** [comment]
No. I think that, instead, we should consider what code we want to show in the Monaco toolbox.

**Comment by tballmsft** [comment]
@riknoll, as discussed, let's only show the code snippets in Monaco toolbox for which there are blocks. Please make sure that they appear in the same order as in Blockly.

**Comment by tballmsft** [comment]
Closing, as richard has made above mod.
