### ISSUE TITLE
Switch from JavaScript->Blocks->JavaScript, the second commented code disapper

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1793]
**Repro steps:**
![88](https://cloud.githubusercontent.com/assets/23466737/24499007/e43c65fe-1572-11e7-85a4-150d1caa4a38.gif)

**Comment by pelikhan** [comment]
Comments are tied to blocks and there is no block to attach this one. Won't fix IMO.

**Comment by Helen09** [comment]
But if comment the first line code and switch from JavaScript-->Blocks-->JavaScript, the commented line will not disappear
![90](https://cloud.githubusercontent.com/assets/23466737/24532971/0f162556-15f7-11e7-9e0e-5bbdeaf3409a.gif)

**Comment by pelikhan** [comment]
The problem is that there is no "comment" block so if the last line is a comment - there is nothing to attach it to.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
