### ISSUE TITLE
Getting Started Download Hint

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1800]
Can we include that full instruction steps (plug in micro:bit via USB cable, ....) in the Download Hint for the Getting Started guide?  Right now, it's the same as the instruction...

<img width="219" alt="downloadhint" src="https://cloud.githubusercontent.com/assets/22108954/24527070/8091479e-1555-11e7-83cc-2018bc990e66.PNG">

**Comment by pelikhan** [comment]
The download dialog has custom logic based on which browser/OS to display to the user so I'm trying to keep the hint small here.

**Comment by ganicke** [comment]
Addressed in https://github.com/Microsoft/pxt-microbit/pull/505.
