### ISSUE TITLE
Cosmetic - Hint button placement in Getting Started

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1801]
On Edge, in 1024 x 768, the Hint button overlays text and scrollbar (in Lesson 3)

<img width="325" alt="hintbutton" src="https://cloud.githubusercontent.com/assets/22108954/24527182/eefde232-1555-11e7-9ee0-a0a6e5211802.PNG">

**Comment by microsoftsam** [comment]
This has been fixed.
