### ISSUE TITLE
Copy button doesn't work in share feature on IE11

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1802]
![image](https://cloud.githubusercontent.com/assets/6107272/24527270/3ccfd236-1556-11e7-8de9-20cf6cb1112f.png)

**Comment by pelikhan** [comment]
IE11 prompts the user if copy should be allowed. It's very easy to make a mistake and click on the wrong button there.

**Comment by pelikhan** [comment]
Works for me on IE11.
