### ISSUE TITLE
Getting Started light-box effect blacking out screen

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1803]
Edge, 1024 x 768, not sure how to repro this... but sometimes tutorial gets into a state where the screen is completely blacked out (instead of the transparent grey).

<img width="510" alt="blackout" src="https://cloud.githubusercontent.com/assets/22108954/24527426/efeb5016-1556-11e7-90d6-23024dc04a0a.PNG">

**Comment by Jaqster** [comment]
I think this happens after I download the .hex file onto my microbit

**Comment by abchatra** [comment]
Likely dupe of https://github.com/Microsoft/pxt/issues/1804

**Comment by microsoftsam** [comment]
Please see if this still repro's on latest.

**Comment by Jaqster** [comment]
Still doing this...

**Comment by microsoftsam** [comment]
@Jaqster please verify you no longer repro this.
