### ISSUE TITLE
Editor greyed out after Getting Started tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1805]
Edge, 1024 x 768, when I click Finish at the end of the Getting Started Tutorial, or Exiting out, the screen is greyed out and I can't do anything.  I have to reload the page.

<img width="511" alt="afterfinish" src="https://cloud.githubusercontent.com/assets/22108954/24527687/236b29ec-1558-11e7-889d-706c4b24307f.PNG">

**Comment by microsoftsam** [comment]
Fixed in PXT
