### ISSUE TITLE
Monaco toolbox titles should be lowercase

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1809]
To match the API namespace in the editor

**Comment by microsoftsam** [comment]
thats an interesting thought, if were trying to match the Blockly toolbox to make the transition easier we go for uppercase, if we match namespaces we go lowercase.

**Comment by tballmsft** [comment]
As we discussed, we should make Monaco match blockly by having only the code for the blocks in Blockly.  Other typescript functions can be discovered by intellisense, which the user learns how to do by typing the namespace, in lower case. So I vote for lower-case.

**Comment by pelikhan** [comment]
Sounds good

**Comment by abchatra** [comment]
I vote for lower case as well.

**Comment by pelikhan** [comment]
The toolbox should match the typescript notation so lower case. We match the name, colors and ordering but the rendering of code is TS specific.
