### ISSUE TITLE
Migrate to monaco editor

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#181]
Replace and ACE and potentially completion engine with Monaco editor.

- [x] loading of Monaco in page
- [x] open TypeScript code in Monaco
- [x] typescript language used to check code
- [x] errors and squiggles visible
- [x] auto-completion
- [x] typescript worker stops when tab is idle
- [x] remove ace.tsx editor
- [x] update app.manifest with monaco files
- [x] fix CORS issues. https://github.com/Microsoft/pxt/issues/219
- [x] auto-insertion of parenthesis, arguments when inserting call
- [x] proper sizing of intellisense menu
- [ ] debugger stepping support

**Comment by tballmsft** [comment]
Assigning to @mmoskal for now.

@pelikhan: as I recall, we were waiting for Monaco to be available open source as a separate distributable, right?

**Comment by thomasdenney** [comment]
@tballmsft Monaco is [now open sourced and separate from VS Code](https://github.com/Microsoft/monaco-editor)

**Comment by tballmsft** [comment]
Thanks, @thomasdenney

**Comment by pelikhan** [comment]
@microsoftsam working on it

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by abchatra** [comment]
This is done apart from debugger
