### ISSUE TITLE
Certificate not signed by trusted CA Authority

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1816]
microbit.org-ticket: 1449

The user is seeing this error - do you know what the cause is? Is it a problem at your end?

![screen shot 2017-04-01 at 06 44 54](https://cloud.githubusercontent.com/assets/25079586/24575782/e501c986-16a6-11e7-899d-aac0a5f0ceea.png)

**Comment by mmoskal** [comment]
Can the user reach https://makecode.com ?

The certificate the Foundation provided is issues by Go Daddy, maybe the IT admin didn't like the sound of it? We're happy to use a different certificate if you so wish.

**Comment by abchatra** [comment]
@DavidWhaleMEF This is on your end. If you want us to use a different certificate let us know.
