### ISSUE TITLE
Statically determine which components may be used in the code

### ISSUE THREAD

**Issue by Darzu** [Microsoft/pxt#182]
I'd like a way to know *statically* if the display, buttons, thermometer, etc. are referenced in the users code. My scenario is the Arduino editor experience: if the user uses the accelerometer somewhere in there code, I need to add the accelerometer to the breadboard; if the user's code can't possibly use the LED matrix anywhere, I want to know that I can leave it off the breadboard; etc.

Currently, the thermometer, light meter, etc. are displayed if, at simulator runtime, a code path makes use of these components. This isn't sufficient for my purposes because I need to statically generate a parts list and can't count on the user to explore all code paths in the simulator.

* [ ] add a "part" property on APIs that specify the require hardware piece - "display", "buttons", ....
* [x] collect list of parts when computing reachability, add computed set in compilation results
* [ ] communicate part list to simulator when launching the code

**Comment by pelikhan** [comment]
Proposed plan:

- [ ] add a "part" property on APIs that specify the require hardware piece - "display", "buttons", ....
- [ ] collect list of parts when computing reachability, add computed set in compilation results


Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by mmoskal** [comment]
I now collect the list of used APIs. The compile call in `runSimulator` will have access to that in compilation result.

@Darzu you need to add a field to `CommentAttrs` in `emitter.ts`

**Comment by Darzu** [comment]
Awesome, thanks @mmoskal, I'll take a look!

**Comment by abchatra** [comment]
This is done
