### ISSUE TITLE
Toolbox should scroll on touch devices

### ISSUE THREAD

**Issue by carlosperate** [Microsoft/pxt#1820]
On mobile, or at least Android Chrome, the toolbox scroll bar is not increased to the same size as the normal blockly workspace. This makes it quite difficult (or at least for me, impossible on my 4.6" phone) to drag in a touch screen.

**Comment by carlosperate** [comment]
![screenshot_20170402-121327](https://cloud.githubusercontent.com/assets/4189262/24586681/523fda36-179e-11e7-9c25-93725f64dd35.png)

**Comment by microsoftsam** [comment]
Increasing scrollbar thickness wouldnt be the right approach here, given were already tight on space on these screens. I would suggest on touch devices and small screen sizes, we add two carets to scroll up and down the toolbox.

**Comment by pelikhan** [comment]
On touch devices, we should support pin and pan gestures.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by carlosperate** [comment]
> On touch devices, we should support pin and pan gestures.

This was my initial reaction when I first tried to scroll the toolbox, but I do believe that having the scroll bar in the first place was the main indication that this area can be scrolled.

Having carets would probably work, but I assume it'd be a redundant to have both carets and the bar, and if the scrollbar was removed I would worry that the carets alone might not be a clear enough visual clue to indicate there is more toolbar to be scrolled.

**Comment by pelikhan** [comment]
Kids are pretty good at trying the usual pan &a pitch on a canvas that looks like a map. We should support that mode of interaction because it is what mobile users expect on touch.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by carlosperate** [comment]
I completely agree for the blockly workspace, which does have a very similar feeling than navigating maps, but I wouldn't say the same applies to the toolbox.
Chrome and android apps do momentarily show a very thin translucent scrollbar (which is just a visual clue and cannot be interacted with directly) when there is an area that can be scrolled. The point I was trying to make is that there needs to be some type of clear indication that we can pan around the toolbox, rather than relaying on the user to recognise a caret or to innately start touch dragging the area.

**Comment by pelikhan** [comment]
Right the toolbox is a different beast

**Comment by microsoftsam** [comment]
Fixed by @guillaumejenkins
