### ISSUE TITLE
save button does not always update the filename

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1821]
microbit.org-ticket: 1431

If you change the name of a script in the script name box next to the save button, then press save or download, the name of the script is not updated the first time round. You have to do it twice for it to work.

I have seen this myself too, it looks like focus from the text entry box has to be lost for the internal script name to be updated.

This has caused much confusion with users saving a script that is then the wrong name.

**Comment by abchatra** [comment]
This repros in Chrome.
