### ISSUE TITLE
Support for Neopixels and BLE ie both packages in same solution

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1824]
Neopixels and BLE(bluetooth and not radio) are mutually exclusive at this point in time on the micro:bit

The support of both types of package in the same solution should be given consideration in terms of play and learn as the kids enjoy Neopixels, and are learning BLE in connection with measurements and the like where by a fun display that is not confided to the 5x5 red display allows for a feeling of real achievement as their progression in coding is made.

**Comment by tballmsft** [comment]
As Peli pointed out, possible with radio.

**Comment by abchatra** [comment]
Neopixels and BLE in same solution is a DAL limitation as there are issues with timings. Please follow up with DAL.
