### ISSUE TITLE
pxt.microbit.org variable initialisation -> control.onEvent problem

### ISSUE THREAD

**Issue by Mattrich007** [Microsoft/pxt#1830]
I've created variable DelayServiceID initialised to 9200 and added a control event in Blocks as follows:-
 
![image](https://cloud.githubusercontent.com/assets/26895651/24650061/f36d42b2-1920-11e7-9c13-fc48d636dfd5.png)

The Javascript shows this:-
![image](https://cloud.githubusercontent.com/assets/26895651/24650133/2df834aa-1921-11e7-9a1c-e4b47c662b91.png)

This code fails, I'm assume the control.onEvent is being registered with the variable initialised to zero due to the ordering of the code and not the value as specified in the "on start" block. If I change the first line "let DelayServiceID = 9200" in the javascript the code now works but I can't switch back to block editing mode. I've tried switching around the order of the code but this also fails to switch back to Blocks. Is this a bug or is there a different way this can be achieved?

**Comment by abchatra** [comment]
Events are registered first. This is avoid the case where they get never a chance to register due to a infinite loop. This bug can't be fixed in the current design. There is a workaround of setting the id directly in the event handlers.
