### ISSUE TITLE
Hex file restoration

### ISSUE THREAD

**Issue by jamesadevine** [Microsoft/pxt#1831]
Hi guys,

Just encountered an issue with the attached hex files, this requires two micro:bits.

One hex file sends commands (`controller.hex`) to another micro:bit residing in our monster truck which controls the momentum and steering of the truck.

It seems like some aspect of the block reconstruction was broken when restoring from the hex file (dragging and dropping into the editor). For some reason `monster-bit[1].hex` was missing variable definitions for two images, so when the controller was shaken, these undefined images would displayed, at which point error code 030 (microbit heap error) would be shown.

A minimal test case would be to flash both micro:bits with the attached hex files, one with the `controller.hex`, the other with `monster-bit.hex` and shake the controller.

[bad-bug.zip](https://github.com/Microsoft/pxt/files/892833/bad-bug.zip)

**Comment by jamesadevine** [comment]
I believe this is related to this issue: https://github.com/lancaster-university/microbit-dal/issues/283

**Comment by abchatra** [comment]
Closing this issue as there is a tracking issue is fixed.
