### ISSUE TITLE
Not possible to simulate accelerometer when music module is also used

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1832]
In the simulator, it seems that it is not possible to use the accelerometer (tilt) simulation if the music module is in use.

**Comment by tballmsft** [comment]
@microsoftsam - I repro'd the problem. Once the breadboard comes out, the tilt simulation of the micro:bit is disable. Here's a program to demonstrate:
```
basic.forever(() => {
    led.plotBarGraph(
        input.acceleration(Dimension.X),
        0
    )
    music.playTone(262, music.beat(BeatFraction.Whole))
})
```

**Comment by pelikhan** [comment]
It's a unfortunate feature interaction since the tilting is currently applied to the entire simulator iframe - not just the simulator.

**Comment by tballmsft** [comment]
Ok. Sounds like a won't fix to me.
