### ISSUE TITLE
Simulator has some non-blocking aspects when the real device blocks for showString()

### ISSUE THREAD

**Issue by ShawnHymel** [Microsoft/pxt#1833]
Apologies if this is a known issue. I could not find a duplicate in the issues.

It seems that when using the "forever" loop, the simulator attempts to execute that even during a showString() function executed by an event elsewhere. On a real micro:bit, showString() is a blocking call, so that forever() does not execute until showString() has completed. Here is a video showing the behavior: [https://youtu.be/sZ5QYsEWaW0](https://youtu.be/sZ5QYsEWaW0)

**Comment by tballmsft** [comment]
Known problem.

**Comment by mmoskal** [comment]
I believe it should replicate the C++ behavior.

**Comment by tballmsft** [comment]
agreed. didnt mean to close

**Comment by tballmsft** [comment]
here is the code from the video:
```
basic.forever(() => {
    basic.showIcon(IconNames.Heart)
})
input.onButtonPressed(Button.A, () => {
    basic.showString("Goodbye, and thanks!")
})
basic.showString("Hello!")
```

**Comment by tballmsft** [comment]
I'd like to take this one, as we discussed.

**Comment by tballmsft** [comment]
@riknoll - you have this one diagnosed, correct?

**Comment by riknoll** [comment]
Yep, I'll push a fix

**Comment by tballmsft** [comment]
Thanks!

**Comment by pelikhan** [comment]
@riknoll is this fixed?

**Comment by riknoll** [comment]
Yep
