### ISSUE TITLE
Is it possible to put spaces in package names

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1844]
Is there an annotation override for the name of a package name?

I have a package name, that for brand ruling reasons, needs two words, capitalised, with a space between them. I know it's not possible to have a space in a 'namespace' name, but given there are annotations applied to the namespaces in the custom.ts, do you have any tags I can apply there to set my own printable name with a space in it that will be displayed in the left hand palette? 

I'm happy that the actual namespace name could be abbreviated, without spaces, and appear like that in the code. It's just that I would like the name that appears in the palette to fit within the brand guidelines of a partner organisation I am currently working with.

**Comment by pelikhan** [comment]
@DavidWhaleMEF  Could you provide an annontated screenshot where you expect package names to be "wordified"?

**Comment by DavidWhaleMEF** [comment]
![screen shot 2017-04-21 at 17 42 51](https://cloud.githubusercontent.com/assets/25079586/25287620/fc281c50-26b9-11e7-858f-5b6e26aea18d.png)

**Comment by DavidWhaleMEF** [comment]
DoctorWho should really be Doctor Who, but in the code it needs to have a name that is syntactically usable by the javascript (presumably with a specific capitalisation and spacing).

perhaps something like...

//% displayName="Doctor Who"
namespace drwho {

**Comment by tballmsft** [comment]
https://github.com/Microsoft/pxt/pull/1990 fixes this. Use
```
//% block="Doctor Who"
namespace drwho {
```

**Comment by DavidWhaleMEF** [comment]
Super, thanks!
