### ISSUE TITLE
"Download Screenshot" doesn't work on IE

### ISSUE THREAD

**Issue by charmian01** [Microsoft/pxt#1852]
**Repro step:**

- Navigate to https://pxt.microbit.org/beta on IE
- Right click on Blocks editor->Download Screenshot

 **Expect result:**
"Download Screenshot" can capture images
**Actual result:**
There is not responding

**Comment by tballmsft** [comment]
cannot repro. Please give more detailed instructions.

**Comment by microsoftsam** [comment]
I believe this is a known issue. Right click in Blockly -> Download screenshot doesn't work in IE.
This is because there isn't SVG to PNG support in IE. We should not show that option in IE.

**Comment by microsoftsam** [comment]
Dupe of #557
