### ISSUE TITLE
"Help" of JavaScript function doesn't work on IE

### ISSUE THREAD

**Issue by charmian01** [Microsoft/pxt#1853]
**Repro steps:**

- Navigate to https://pxt.microbit.org/beta on IE 
- Switch to Javascript
- Right click on Javascript function
- Click "Help"

**Expect result:**
There is the function reference on the right of page
**Actual result:**
There is not responding

**Comment by tballmsft** [comment]
What do you mean by "Right click on JavaScript function"?

**Comment by charmian01** [comment]
**IE:**
![2](https://cloud.githubusercontent.com/assets/23711238/24781916/c0c32560-1af7-11e7-9b61-0b98fb51970c.gif)

**Expect result:**
![1](https://cloud.githubusercontent.com/assets/23711238/24781926/d2f5e696-1af7-11e7-971f-8ab0a1ec2b37.gif)

**Comment by tballmsft** [comment]
Thanks.

**Comment by WendyFeng01** [comment]
not repro on IE now.
