### ISSUE TITLE
Block comment content can't be shown normally

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1854]
**repro steps:**
Navigate to https://pxt.microbit.org/beta on Safari&Chrome
Choose Logic and drag block "if...else" to block "forever"
Right click on block "if...else" and add comment for it
Zoom out the comment box until the drop-down bar occurs
Drag the drop-down bar

**Expect result:**
The drop-down bar should work normally
**Actual result:**
**Safari:**
![apr-06-2017 15-38-35](https://cloud.githubusercontent.com/assets/23466737/24744557/04541b44-1ae5-11e7-8804-f7d6ba57b66b.gif)
**Chrome:**
![apr-06-2017 15-46-07](https://cloud.githubusercontent.com/assets/23466737/24744616/375c5b78-1ae5-11e7-9567-92181bfbf5d9.gif)

**Comment by tballmsft** [comment]
blockly bug, it appears.

**Comment by microsoftsam** [comment]
Can't repro on Chrome 57 on Mac.

**Comment by microsoftsam** [comment]
Can't repro on Chrome on Windows.

**Comment by Helen09** [comment]
It still repro on Chrome(57.0.2987.133) & Safari on Mac and not repro on Chrome on Windows

**Comment by WendyFeng01** [comment]
not repro on Chrome and Safari now, you can close this bug.
