### ISSUE TITLE
The download file format is not right on Safari

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1855]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta on **Safari**
• Drag any block form editor and put it in block "forever"
• Type a name on the bottom text box and click  "Download" to save this project

**Expect result:**
 The project should be downloaded normally
**Actual result:**
 The download file name changes to "Unknown" and file format is not right

**Comment by tballmsft** [comment]
@pelikhan - the name problem has always been there, correct?

**Comment by pelikhan** [comment]
Yes, Safari limitation.

**Comment by Helen09** [comment]
The version of Safari: 10.1(11603.1.30.0.34)
