### ISSUE TITLE
neopixels: initialise variable may be out of scope in forever

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1857]
https://pxt.microbit.org/39849-16350-37684-05329
- adding item.rotate gives null

Start with this:
```
let item: neopixel.Strip = null
basic.showIcon(IconNames.Heart)
item = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
item.showRainbow(1, 360)

```
Add this:
```
basic.forever(() => {
    item.rotate(1)
})
```

**Comment by tballmsft** [comment]
Hmm... this works
```
let item = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
item.showRainbow(1, 360)

basic.forever(() => {
    item.rotate(1)
    item.show()
})
```

**Comment by tballmsft** [comment]
This works too:
```

let item: neopixel.Strip = null
item = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
item.showRainbow(1, 360)

basic.forever(() => {
    item.rotate(1)
    item.show()
})
```

**Comment by tballmsft** [comment]
I've narrowed it down. It's not to do with the neopixel:
```
let item: neopixel.Strip = null
basic.showIcon(IconNames.Heart)
item = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
```
causes the runtime error:
```
Program Error: sim error: getResume() not called
```

**Comment by OwenBrotherwood** [comment]
It was a bit funny y used show heart: one test was exactly with  show heart :)

**Comment by tballmsft** [comment]
Bug repros with this code
```
let item: string = null
basic.showIcon(IconNames.Heart)
item = null
```

**Comment by tballmsft** [comment]
Actually, this one looks like it depends on neopixel package. some runtime weirdness.

**Comment by tballmsft** [comment]
Oh, this is weird. I tried again and it didn't repro!

**Comment by OwenBrotherwood** [comment]
Yep: this is a tricky one to keep you up at night

**Comment by tballmsft** [comment]
It's likely a race condition between the main fiber and the fiber running the forever loop. Here is what is going on. The call to "basic.showIcon" introduces a preemption point, so the forever loop gets scheduled. It's a bug in your code! But we should give a better error message. This code should be fine:
```
let item = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
basic.showIcon(IconNames.Heart)
item.showRainbow(1, 360)

basic.forever(() => {
    item.rotate(1)
    item.show()
})
```

**Comment by tballmsft** [comment]
We should give better error message. Downgrading priority.

**Comment by OwenBrotherwood** [comment]
![image](https://cloud.githubusercontent.com/assets/866122/24777298/0372f67e-1b25-11e7-8ea6-1bb8f61b2b70.png)

**Comment by OwenBrotherwood** [comment]
So basically, init neopixel as soon in the code as possible?

```
let item: neopixel.Strip = null
basic.forever(() => {
    item.rotate(1)
})
item = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
basic.showIcon(IconNames.Heart)
item.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))

```

**Comment by tballmsft** [comment]
Yes. Even better, don't use null.
```
let item = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
basic.forever(() => {
    item.rotate(1)
    item.show()
})
basic.showIcon(IconNames.Heart)
item.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))

```

**Comment by tballmsft** [comment]
![image](https://cloud.githubusercontent.com/assets/10767146/24778530/e19d160a-1adf-11e7-969c-56959f6bf238.png)

**Comment by pelikhan** [comment]
To be fair, we introduce null when converting blocks to JS.

**Comment by OwenBrotherwood** [comment]
jep: the kids use blocks, and neopixels are fun
