### ISSUE TITLE
Unclear how to resolve pxt definition files when developing package

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#186]
When developing a custom package, the typescript definition files for dependencies are not properly resolved -- at least with the current instructions.

Repro: open the microsoft/pxt-neopixel package and open neopixel.ts. You'll see that TypeScript complains unknown APIs like basic...

**Comment by mmoskal** [comment]
Did you try pxt install?

**Comment by pelikhan** [comment]
Yes it worked! I've updated the docs with this step at https://www.pxt.io/packages .
