### ISSUE TITLE
unfriendly error messages

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1867]
With this code
```
interface Foo {
    a?: string;
}

let bar: Foo = { a: "hi" }

bar[0] = 2 
```
we get
```
Index signature of object type implicitly has an 'any' type.
```
when we basically want to say
```
Index access not permitted
```

**Comment by pelikhan** [comment]
We should collect the frequency of errors surfaced to the user and systematically rewritte the TS error messages into friendly sentences based on those frequencies.

**Comment by tballmsft** [comment]
good idea
