### ISSUE TITLE
Buttons not rendering on Edge/Windows 10

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1872]
See attached photos - the buttons are not rendering properly and we can't see what they are supposed to be. The run/etc buttons under the micro:bit are light grey on white with no icons on them, and the buttons at the bottom right are blue with no icons on them. When we hover over them the tool tip text pops up fine.

![img_20170408_115358](https://cloud.githubusercontent.com/assets/25079586/24828361/16d853a6-1c53-11e7-957f-dfd83fe02c6e.jpg)
![img_20170408_115404](https://cloud.githubusercontent.com/assets/25079586/24828362/1aa8c5b0-1c53-11e7-8cc3-34e87866f914.jpg)

**Comment by DavidWhaleMEF** [comment]
Microsoft Edge: 20.10240.17146.0
Windows 10 Home 64 bit
PC: Acer Aspire One Cloudbook 14

**Comment by abchatra** [comment]
This seems really old build of windows. Edge on my box, there is no repro.

**Comment by abchatra** [comment]
Doesn't repro for us.

**Comment by DavidWhaleMEF** [comment]
I have another user that is reporting the same problem, I will log it as a new ticket. Can we think about how we are reproducing this issue, it clearly is an issue as users are reporting it.

**Comment by abchatra** [comment]
Microsoft Edge: 20.10240.17146.0  This edge version is really old. I believe it is Edge browser problem.
Either one should update windows (which will update Edge) or move to a different browser.

**Comment by DavidWhaleMEF** [comment]
Ok thanks @abchatra I will update the users.

**Comment by DavidWhaleMEF** [comment]
I have suggested to the users on this ticket that they update their Edge. The other ticket (linked) I have asked the user to supply Edge version to us so we can confirm if this is the issue.
