### ISSUE TITLE
Switch Browser profile to "windows phone", the page shows abnormally

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1874]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta on **Edge**
• Open F12 and switch Browser profile to "windows phone"
• Observe the web page
• Drag the slider on the bottom and observe the reloading page

**Expect result:**
 The page shows abnormally
**Actual result:**
 The page should show normal as on windows phone
![3](https://cloud.githubusercontent.com/assets/23466737/24844788/c528e14a-1ddf-11e7-8ae9-028f46c1f502.gif)

**Comment by tballmsft** [comment]
We have not supported windows phone for quite some time.

**Comment by tballmsft** [comment]
@abchatra - we should have a list of unsupported platforms/browsers.

**Comment by pelikhan** [comment]
We do in our docs. See /browsers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tballmsft** [comment]
Any action item then? Check that user agent agrees with this list?

**Comment by pelikhan** [comment]
We need to detect that we are on WP and redirect to /browsers + update docs.
