### ISSUE TITLE
On data packet received runtime error

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#1875]
The following code crashes the runtime: 

```
radio.onDataPacketReceived(({receivedString}) => {

})
let y = 1
let x = "10001"
radio.sendString(y + x);
```

Had a quick look and it looks like it's something to do with the code emitted by the onDataPacketReceived event

**Comment by tballmsft** [comment]
I investigated a bit. It looks to me like a bad interaction between VMs and reference counting on strings.

**Comment by tballmsft** [comment]
Here's what I see in the debugger and what appears to be unique to this situation:
1. we concat two strings and create a new one, which then is ref-counted to 1 (argument to sendString)
2. sendString completes and ref-count of arg is decremented to zero.
However, this string was sent over the "air" and is received later by the handler. There is no record of the string anymore (see steps 1 and 2).  The simulator code expects that every string literal has one reference (the global reference to it) it appears, but this string literal is new, and the following check fails because k=1:
```
        else if (stringLiterals && typeof v == "string" && !stringLiterals.hasOwnProperty(v)) {
            var k = stringRefDelta(v, 1);
            check(k > 1);
```

**Comment by abchatra** [comment]
Following works fine.
```javascript
radio.onDataPacketReceived(({receivedString}) => {
    basic.showString(receivedString)
})
let y = "20002"
let x = "10001"
let z = x + y
radio.sendString(z);
```
I do think we need to increment the refcount before sending the string.
```assembly
    r0 = s.tmp_1;
    pxtrt.decr(r0);
    r0 = s.tmp_2;
//THIS IS MISSING HERE ->    pxtrt.incr(r0);
    s.tmp_3 = r0;
    r0 = pxsim.radio.sendString(s.tmp_3);
    s.tmp_4 = r0;
```

**Comment by tballmsft** [comment]
Thanks, @abchatra. I'm not sure this is the correct fix. I think that there is a bug in the way our JS runtime does ref counting on string. It seems to assume that every string gets created via
```
    export function initString(v: string) {
        if (!v || !stringLiterals) return v
        if (typeof v == "string" && !stringLiterals.hasOwnProperty(v))
            stringRefDelta(v, 1)
        return v
    }
```
However, some strings get passed around behind our backs and then pop into our runtime. I can explain more tomorrow.

**Comment by tballmsft** [comment]
As I suspected, this wasn't a codegen problem (Michal's too good). It's a bug in the JS implementation of radio. Here's the code before the fix, just sending back a raw JS string to the simulator:
```
    export function receivedString(): string {
        return board().radioState.bus.datagram.lastReceived.payload.stringData || "";
    }
```
Here's the code after:
```
    export function receivedString(): string {
        return initString(board().radioState.bus.datagram.lastReceived.payload.stringData || "");
    }
```
All this makes me wonder if we really need the reference counting simulation on strings. @mmoskal ?

**Comment by tballmsft** [comment]
We could automate the generate of the reference count based on the API signature.

**Comment by tballmsft** [comment]
bug fixed by https://github.com/Microsoft/pxt-microbit/commit/d3ff1a689ac0621f7bf7eac11e57687a6e5185af

**Comment by mmoskal** [comment]
The idea was to debug memory problems in the simulator, not on the device. However, I didn't implement simulator reference counting for boxed number yet anyway, and it may be more effort than it's worth.

I think we should leave it for user-defined types and collections (which are unbounded in size) and turn it off for primitives like strings - this should still allow users to debug memory leaks in their code (cycles, etc) and reference counts of primitives should be always correctly handled by the runtime.

**Comment by tballmsft** [comment]
Makes sense. I'll take care of that and close this issue.

**Comment by tballmsft** [comment]
https://github.com/Microsoft/pxt/commit/26917828bd06115d341ef4fb1f9b323602d51cde
