### ISSUE TITLE
Support higher order array functions

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#188]
JavaScript arrays have methods for [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter), and [reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce). It would be nice to add support for these.

**Comment by tballmsft** [comment]
Agreed - we should support the expected functions on arrays.

**Comment by mmoskal** [comment]
Depends on #39

**Comment by mmoskal** [comment]
I've added the mentioned functions. Feel free to add more. They are not compiled in unless used, so we can include all of them.
