### ISSUE TITLE
Block "else" explanation covers the right block

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1889]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta 
• Drag block "if...then" from Logic to contnet pane
• Click "setting" button to show it sub-block and move  cursor mouse to show its explanation

**Expect result:**
 The sub-block's explanation should not cover the right block
**Actual result:**
![1](https://cloud.githubusercontent.com/assets/23466737/25077946/f0c4c072-2360-11e7-8a2b-35c8f135caa3.png)

**Comment by abchatra** [comment]
@Helen09 Help explanation looks ok for me. What is your expectation?

**Comment by Helen09** [comment]
The explanation words cover the right block and it looks not clear

**Comment by abchatra** [comment]
This is won't fix from our end for now.
