### ISSUE TITLE
when TS->Blocks conversation fails, suggest remove blocks file

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#189]
Big red button + confirmation message that "main.blocks" should be removed.

**Comment by tballmsft** [comment]
so, we have separate files for blocks and TS?

**Comment by pelikhan** [comment]
Yes we do. Removing the .blocks file effectively makes it a TS project.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by microsoftsam** [comment]
Fixed in issue #189
