### ISSUE TITLE
"Flashing Heart" project shows abnormally

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1890]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Click "Projects" ->Projects ->"Flashing Heart"

**Actual result:**
![1](https://cloud.githubusercontent.com/assets/23466737/24944881/8e82334c-1f8f-11e7-8c18-81869dd9a27a.png)

**Comment by tballmsft** [comment]
@pelikhan - it seems flashing heart is appearing as a tutorial rather than as a project in the sidebar.

**Comment by tballmsft** [comment]
I found the problem.

**Comment by tballmsft** [comment]
Fixed.
