### ISSUE TITLE
Project "Watch" doesn't have code about teaching kids to show time on microbit

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#1891]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta 
• Click Projects -> Projects -> Watch to watch the tutorial

**Expect result:**
There should have code about teaching kids to show time on microbit like other project

![1](https://cloud.githubusercontent.com/assets/23466737/24945268/202f6714-1f91-11e7-9d71-dd88f9e2b7da.png)

**Actual result:**
There doesn't have any code about teaching kids to show time on microbit

**Comment by tballmsft** [comment]
This is a pure making project. @pelikhan , your thoughts?

**Comment by pelikhan** [comment]
We should align the watch project to the format of other lessons. So yes, we need a "code" section - probably a stop watch.

**Comment by ganicke** [comment]
A coding activity is added to the **Watch** project: https://github.com/Microsoft/pxt-microbit/pull/526.
