### ISSUE TITLE
For running MIDI via serial: please add 31250 to the list of baud rates

### ISSUE THREAD

**Issue by ens-lg4** [Microsoft/pxt#1902]
Dear developers,

I am using your environment for MicroBit programming. It is GREAT that you provide serial port support back to the computer via the same USB that is already on board! Thank you so much for it!

I'd like to ask you for a feature, and I hope it would only be a small change: in the "Serial" category of blocks you have a "Serial redirect to TX/RX/baud_rate" block. The baud rate is currently selectable from a fixed drop-down list, and it is missing one important value: 31250, which is the speed of MIDI over a serial port. Could you add this value, please?

My hope is that if the USB port on MicroBit is truly an OTG port, it could serve as a host to MIDI devices that could be plugged into it via a standard micro-USB adaptor. We could use "serial write"/"serial read" to exchange MIDI messages with the connected device. Or do you think another block may be needed for switching the MicroBit's USB port to OTG mode and back?

Many thanks in advance!

**Comment by abchatra** [comment]
@ens-lg4  You can specify the exact value in javascript editor and give it a try. 

@pelikhan Any concerns adding value 31250?

**Comment by pelikhan** [comment]
We need to rev the minor version but no issue otherwise.

**Comment by ens-lg4** [comment]
@abchatra  Thanks very much for the idea to switch over to Javascript.
I attached an external DIN5 port to pin0 and managed to send a packet to press and release a note on my piano. It worked!!!

**Comment by tballmsft** [comment]
Good to close?

**Comment by pelikhan** [comment]
Fix in beta.

**Comment by ens-lg4** [comment]
Thanks very much for the fix, I can see the branch has been merged.
Sorry for the dumb question, but how can I get that fix?
I've tried reloading the page in my browser, but could see no change.

If beta is deployed separately at another web address, could you share the link to it?
Many thanks in advance!

**Comment by pelikhan** [comment]
Try https://pxt.microbit.org/beta .

**Comment by ens-lg4** [comment]
@pelikhan  Thanks a lot!
