### ISSUE TITLE
Sidedocs loads straight into the JS view (on load only)

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#1904]
The side docs assumes on first load that the file is going to be a Javascript file when it loads.

![screen shot 2017-04-14 at 4 35 53 pm](https://cloud.githubusercontent.com/assets/16690124/25058620/8090993e-2130-11e7-9aac-7afb3f5734dd.png)

**Comment by pelikhan** [comment]
The editor is supposed to communicate the current editor to the docs view.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
Yeah, but our initial state is to start in the text Editor, and we start the docs too early, before we've switched over. Going to change the logic up a little bit.
