### ISSUE TITLE
Chrome extension does not show data on Windows 10

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#1908]
Expected, serial write "hello" shows "hello" in the editor 
(could be misunderstood)
No joy.

Note that it has been possible to obtain serial contact with micro:bit with a program

![image](https://cloud.githubusercontent.com/assets/866122/25071322/46ea591a-22b4-11e7-9edd-be391791f317.png)

**Comment by tballmsft** [comment]
Known bug. Chrome extensions needs to be updated.

**Comment by samelhusseini** [comment]
The Chrome extension has been deprecated. Closing bug.
