### ISSUE TITLE
when publishing a package, force conversion to blocks

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#191]
Always ensure that the Blocks and TS are in sync before publishing for embed.

**Comment by tballmsft** [comment]
What if the user has created a JS program that has no corresponding block program?

**Comment by pelikhan** [comment]
We should ask to drop the .blocks file.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by abchatra** [comment]
Closing as we don't have publish feature.
