### ISSUE TITLE
bug: String.fromCharCode(0) characters are ignored by length function

### ISSUE THREAD

**Issue by ens-lg4** [Microsoft/pxt#1910]
In MultiBit's code development environment String.fromCharCode(0).length equals 0.
In standard Javascript (for example, in Safari browser's console) the same expression gives me 1.

This affects any string that you put together using "join" block (or "+" operation in Javascript), where some of the parts being joined are zero bytes ( String.fromCharCode(0) ) - they are all ignored by .length method.

It seems that because of this or a similar bug the "serial write string" method is also unable to send packets that contain zero bytes correctly (they are not received on the other side).

I can see the bug both in Blocks mode and Javascript mode.

**Comment by tballmsft** [comment]
This may be another issue with the DAL. Needs further investigation.

**Comment by tballmsft** [comment]
To clarify, this is a problem with our C++ backend, not the JavaScript. The following code works correctly in the simulator:
```
let x = String.fromCharCode(0).length
basic.showNumber(x) 
```

**Comment by tballmsft** [comment]
This looks like a DAL issue, as our C++ wrapper is:
```
   StringData *fromCharCode(int code)
    {
      return ManagedString((char)code).leakData();
    }
```

**Comment by tballmsft** [comment]
This is a bug in the DAL https://github.com/lancaster-university/microbit-dal/issues/284

**Comment by abchatra** [comment]
Closing this issue as the correponding bug is tracked in DAL
