### ISSUE TITLE
Array Block

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1912]
Please enable the Array block.  We want to use it in a lesson about Music and Lists.

**Comment by tballmsft** [comment]
Is it ready?

**Comment by riknoll** [comment]
Currently pretty broken because the type inference stuff in the blockly compiler can't handle generics. I'll take a look.

**Comment by tballmsft** [comment]
@riknoll - this is another reason for generating typescript and letting the typescript language service do inference for us - we should have just one way of inferring types rather than the two-way broken scheme we have now, IMO.

**Comment by tballmsft** [comment]
@riknoll - this is done, correct?

**Comment by riknoll** [comment]
Yep
