### ISSUE TITLE
Javascript: Compilation errors

### ISSUE THREAD

**Issue by redjbishop** [Microsoft/pxt#1914]
1. Compilation errors do not have explanations. I see red squigglies, which come and go and start in the middle of a word or line.
2. If I press run, an orange "Oops" box appears saying there are compilation errors, but even the reg squigglies aren't there.
3. If I press save, the whole screen switches to a black modal saying there are compilation errors. I assume my program was saved.

Desired behavior:
1,2: Sort out the red squigglies and have corresponding compilation error messages that appear either under the line or on hover. The orange message in 2. could mention hovering.
3. Do not switch screens. Mimic the behavior of 2 with an orange box, and assure the user the file was indeed saved.

Thanks!

**Comment by tballmsft** [comment]
Thanks, Judith. This experience is definitely suboptimal.
