### ISSUE TITLE
Buy Details missed

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#1916]
Repro Step:
•	Navigate to https://pxt.microbit.org/beta
•	Click “?” 
•	Click Buy

Repro on windows: IE11, Chrome, Firefox, Edge
Mac: Safari, Firefox, Chrome

Expect result: Buy details can display
Actual result:
![111](https://cloud.githubusercontent.com/assets/23447632/25119007/211c39b8-244b-11e7-8598-54b72719154f.gif)

**Comment by pelikhan** [comment]
Fixed.
