### ISSUE TITLE
“Slow-Mo” is selected when switch between editor page and "Getting Started" page

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#1918]
Repro steps:
•	Navigate to https://pxt.microbit.org/beta
•	Click “Slow-Mo” 
•	Click “Getting Started”
•	Click “OK” button

Expect result: “Slow-Mo” shouldn’t be selected
Actual result: “Slow-Mo” is selected
![selected](https://cloud.githubusercontent.com/assets/23447632/25119961/d601e65e-244e-11e7-9e28-4094818aa0fa.PNG)

**Comment by microsoftsam** [comment]
@riknoll is this enabled by default in tutorial mode?

**Comment by riknoll** [comment]
Nope. It was enabled in this case because it was enabled in the editor before navigating to tutorial mode.

**Comment by microsoftsam** [comment]
Maybe clear that state when switching between the two?
