### ISSUE TITLE
Explanation of Bluetooth-temperature-sensor is out of the border and the bottom color is not right

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#1919]
Repro steps:
• Navigate to https://pxt.microbit.org/beta
• Click “Add Package”
• Such as taping “bluetooth” on search box
• Press “Search”

Expect result: Explanation of Bluetooth-temperature-sensor should be in the border
Actual result: 1. the explanation is out of the border 
                      2. the bottom color is not grey.
![box](https://cloud.githubusercontent.com/assets/23447632/25120922/6f50dc22-2452-11e7-8c13-6060c2debbf0.PNG)

**Comment by Mofell** [comment]
This issue only repro on Chrome on windows, chrome version: 57.0.2987.133

**Comment by Mofell** [comment]
Repro on mac Chrome, Chrome version 57.0.2987.133

**Comment by abchatra** [comment]
fixed
