### ISSUE TITLE
Unicode characters stripped out from the project name when generate .hex file

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#192]
Repro: try some non-latin character in the project name. They all get stripped out from the .hex file.

Fix: allow valid character for file names.

**Comment by mmoskal** [comment]
This is easy to remove the check but it needs to be tested across browsers, devices, oses

**Comment by mmoskal** [comment]
Tested on macOS/Chrome and macOS/Safari. 

To test, please go to https://codethemicrobit.com/beta?someRandomString, create a project, name it something like `żółw/你好`, and compile. See if special characters are retained. `/` should be replaced with `-`. 

Try it in different browsers/OSes. 

Try dragging the resulting file to the microbit.

**Comment by darrenge** [comment]
Tested on:
* Win 10 Anniv / Chrome
* Win 10 Anniv / Firefox
* Win 10 Anniv / IE
* Win 10 Anniv / Edge
* Win 7 - IE
* Win 7 - Chrome
