### ISSUE TITLE
Details about additional panic codes

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1920]
microbit.org-ticket: 1482

We sometimes see panic code 042

This is not listed in our official panic code reference, which is here:

https://support.microbit.org/solution/articles/19000016969-what-does-the-number-after-the-sad-face-micro-bit-mean-

Joe Finney from Lancaster tells me that Microsoft sometimes add on small constants to the panic codes to make them more specific.

Can you send me a list of the additional small constants and their meanings, so that I can update the official documentation to make it complete? Thanks!

**Comment by pelikhan** [comment]
We should add them to our docs.

**Comment by tballmsft** [comment]
Where?

**Comment by DavidWhaleMEF** [comment]
We have some official docs on panic codes here:

https://support.microbit.org/solution/articles/19000016969-what-does-the-number-after-the-sad-face-micro-bit-mean-

I'll add your additional codes to an editor specific list on that page.

Thanks for your help in finding these.

**Comment by ganicke** [comment]
Remaining 'known' codes are added to the error list - https://github.com/Microsoft/pxt-microbit/pull/525.
