### ISSUE TITLE
A game over cannot be reset

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1922]
microbit.org-ticket: 1268

- a game over cannot be reset

**Comment by pelikhan** [comment]
reset is not implemented in the simulator.

**Comment by tballmsft** [comment]
Does this need to be documented?

**Comment by pelikhan** [comment]
We should fix the simulator really.

**Comment by abchatra** [comment]
Won't fix. Simulator there is a work around to reset by reloading the simulator.
