### ISSUE TITLE
Projects come and go

### ISSUE THREAD

**Issue by redjbishop** [Microsoft/pxt#1929]
Yesterday (4/17) I noticed that all my projects from last week had disappeared except the one that had been on the screen last time I logged in.
Today the reverse has happened. My projects are back except the one I was working on yesterday. Although I had saved it, it does not appear, either in the project list or on the screen.

Desired behavior:
Projects should not disappear once they are saved. 
Perhaps projects that are on the screen and not saved can disappear :-)

**Comment by abchatra** [comment]
@redjbishop Did you change the browser? These projects are stored in the browser cache.

**Comment by abchatra** [comment]
We don't have a login system and projects won't stay forever unless you explicitly share it or save it on the disk.
