### ISSUE TITLE
radio payload comments not consistent with reality

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1935]
The comments in file radio.cpp do not seem to match with what actually happens on-air?

This is what is in radio.cpp

```
Defaults in the DAL

  MICROBIT_RADIO_DEFAULT_FREQUENCY  (7)
  RADIO_MODE_MODE_Nrf_1Mbit
  MICROBIT_RADIO_BASE_ADDRESS       0x75626974

// Packet Spec:
// | 0              | 1 ... 4       | 5 ... 8           | 9 ... 28
// ----------------------------------------------------------------
// | packet type    | system time   | serial number     | payload
//
// Serial number defaults to 0 unless enabled by user

#define MAX_FIELD_NAME_LENGTH 12
#define MAX_PAYLOAD_LENGTH 20
#define PACKET_PREFIX_LENGTH 9
#define VALUE_PACKET_NAME_LEN_OFFSET 13

// payload: number (9 ... 12)
#define PACKET_TYPE_NUMBER 0

// payload: number (9 ... 12), name length (13), name (14 ... 26)
#define PACKET_TYPE_VALUE 1

// payload: string length (9), string (10 ... 28)
#define PACKET_TYPE_STRING 2
```

Here is my analysis of a payload transmitted by PXT, that is received as a raw byte string by Python:

```
01|00 01 02 1E 01 01|00 00 00 00 00|(05)44 41 4C 45 4B 
01                string
00 01 02 1E 01 01 time
00 00 00 00 00    serial number disabled
05                length
44 41 4C 45 4B    DALEK


01|00 01 02 80 AF 03|00 00 00 00 00|(05) 44 41 4C 45 4B
01                string
00 01 02 80 AF 03 time
00 00 00 00 00    serial number disabled
05                length
44 41 4C 45 4B    DALEK
```

PXT file that sends this:

```
basic.forever(() => {
    radio.sendString("DALEK")
    basic.pause(500)
}
radio.setGroup(132)
```

Python that receives and decodes it:

```
from microbit import *
import radio

radio.config(channel=7, address=0x75626974, group=132, data_rate=radio.RATE_1MBIT)
radio.on()

while True:
    sleep(500)
    try:
        msg = radio.receive_bytes()
        if msg is not None:
            line = ""
            for b in msg:
                line += str.format("%02X " % b)
            print(line)
    except Exception as e:
        # reset the radio if it crashes
        print("  RESET:%s" % str(e))
        radio.off()
        radio.on()
```

It looks like your documented field widths in the comments don't match what is actually sent on air? Timestamp is two bytes longer than you document, and serial number is 1 byte longer than documented.

**Comment by DavidWhaleMEF** [comment]
Also note that in your comments in that file, you say that type 01 is a value consisting of a number followed by a name length followed by a name. But my tests above show that sending a string sends type 01 (not type 02 as the documentation suggests)

**Comment by DavidWhaleMEF** [comment]
I have started to document how to share data between PXT and MicroPython in this k-base article, but given that the documentation in the radio.cpp file is incorrect, I'd like to wait until you verify/correct the actual payload format, before completing this documentation:

https://support.microbit.org/solution/articles/19000053168-receiving-radio-data-from-pxt-within-python

**Comment by abchatra** [comment]
Our comment is exactly same as the packets we send. See 
https://github.com/Microsoft/pxt-microbit/blob/master/libs/radio/radio.cpp#L197

I do think there is a bug in python receiver side or the python program which appends a extra null (00).

**Comment by DavidWhaleMEF** [comment]
Sorry @abchatra but could you open this ticket again please, its not resolved.

Could you also try the repro case above that I have provided?

The PXT code example asks to send a string, but the type field that you see in the received packet trace is set to 01 (value) not 02 (string) - also the size of the fields in the received payload does not seem to match what your documentation states, time and serial number are both wider than your documentation specifies. The comments state that the time field is 4 bytes, but in reality it is 6 bytes. The comments state the serial number is 4 bytes but in reality it is 5 bytes. Regardless of whether an extra null is appended or not (unlikely), the type field does not match the documentation, and the width of the time field does not match the documentation.

Thanks very much.

**Comment by DavidWhaleMEF** [comment]
I see what you say about the code - but can you confirm that this is actually the code that is deployed in the live editor? It makes no sense to me that the type field is wrong and the field widths are different (this is clearly more than just appending a null) - which makes me suspect that the code you have linked me to is not actually deployed.

Also, could you try the repro code attached and let me know if you see the same effects as me.

Thanks

**Comment by DavidWhaleMEF** [comment]
@abchatra Ah, I think I have worked it out. There is an extra 01 00 01 prepended to the start of the whole payload as received by Python. If I 'ignore' those three bytes, then the type field is 02 for a string and the time and serial number fields are indeed 4 bytes long.

I have a very vague memory of reading about this somewhere on the python mailing list but I can't remember what the 01 00 01 at the start is for. I'll dig into it, thanks for the clarification.

**Comment by DavidWhaleMEF** [comment]
So really, this payload as received by MicroPython should be interpreted thus:

```
01 00 01|02 80 AF 03|00 00 00 00 00|(05) 44 41 4C 45 4B
01 00 01      prefix added by MicroPython
02                string
80 AF 03 00 time
00 00 00 00 serial number disabled
05                length
44 41 4C 45 4B    DALEK
```

**Comment by DavidWhaleMEF** [comment]
Might have been a breaking change in the DAL a while ago, following up with both the DAL team and the MicroPython team at the moment:

https://github.com/lancaster-university/microbit-dal/issues/285

**Comment by dpgeorge** [comment]
@DavidWhaleMEF I think what you are seeing here is that the prefix of 01 00 01 is added by the *DAL*.  PXT is creating the buffer with the 02 for the string etc, but then passing it down to the DAL the DAL adds the first 3 bytes.  MicroPython's receive_bytes function doesn't add anything, it just returns the exact bytes that were found in the payload from the air.

So if you instead used MicroPython's receive() function, it would automatically strip the 01 00 01 prefix (we did it that way so it would interoperate easily).

I guess the real issue here is that the exact on-air format of the packets sent from PXT are not fully documented.

**Comment by abchatra** [comment]
@DavidWhaleMEF  fascinating! If you want us to document the extra bytes added by the DAL or point to DAL documentation let us know. Happy to do so.
