### ISSUE TITLE
Typescript compiler confused

### ISSUE THREAD

**Issue by redjbishop** [Microsoft/pxt#1939]
My program at https://pxt.microbit.org/_0XyFXji2LA8Y is rejected by the compiler, but there are no red lines and no compilation errors that I can spot. I have looked hard. Any help welcome.

**Comment by tballmsft** [comment]
Nice catch Judith. You have to put a let clause inside {}. Don't know why the compiler missed this. 

Use this program to get unblocked (don't put handlers inside forever loops):

https://pxt.microbit.org/50683-04560-08919-63013

You have a runtime error (file more bugs on us, the error message is bad).

**Comment by tballmsft** [comment]
You forget to initialize the array. See here:

https://pxt.microbit.org/08213-36035-30249-04312

**Comment by tballmsft** [comment]
OK. Back to your original program. The let clause error didn't show because of another error in your code. You are missing a closing ") for the basic.forever call:
```
basic.forever(() => {
    input.onButtonPressed(Button.A, () => {

        if (!chairs.empty())
            let patient = chairs.remove();

    })
    input.onButtonPressed(Button.B, () => {
        chairs.add(visitor);
        visitor++;
    })
    display(chairs);
}
```
Once I correct that error, then the let error is discovered. Progress, of sorts!

**Comment by tballmsft** [comment]
OK. I got a smaller program to repro in the TypeScript playground, so this is a bug in their code, not ours:

http://www.typescriptlang.org/play/index.html#src=function%20foo(x%3A%20any)%20%7B%0D%0A%20%20%20%20%0D%0A%7D%0D%0A%0D%0Afoo(()%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(true)%0D%0A%20%20%20%20%20%20%20%20let%20patient%20%3D%203%3B%0D%0A%7D%0D%0A

**Comment by redjbishop** [comment]
The brackets always get ya!

Many thanks for casting new eyes and light on this, Tom.
Glad we found some bugs for someone.
I’ll be able to perfect the program now (logically and semantically).

**Comment by abchatra** [comment]
@tballmsft  any bug on our side?

**Comment by tballmsft** [comment]
no. should file against ts

**Comment by abchatra** [comment]
Closing this bug.
