### ISSUE TITLE
Monaco editor is quite broken on Android.

### ISSUE THREAD

**Issue by dragonx** [Microsoft/pxt#1944]
It's so broken, it's hard to describe.

Android keyboard inputs seem to show two characters; if I type 'a', I see 'aa'.  Then sometimes both characters will disappear.  Backspace sometimes doesn't appear to work.

Currently testing on a Nexus 5X running Android 7.1.1, but this seems reproducible on a variety of devices.

**Comment by dragonx** [comment]
@abchatra This is a high priority bug for us, can you guys check with the Monaco team to see if they can make any progress on this in the next 2 months?  We'd like to get this at least to a working state.

**Comment by abchatra** [comment]
Sure I will follow up. @Jaqster FYI

**Comment by tballmsft** [comment]
@microsoftsam - do you have an update on this?

**Comment by microsoftsam** [comment]
This has been fixed.
