### ISSUE TITLE
Help for Set Brightness is not rendering properly

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1947]
https://pxt.microbit.org/reference/led/set-brightness

Get a blank mauve screen with no text on it....

![screen shot 2017-04-21 at 12 35 54](https://cloud.githubusercontent.com/assets/25079586/25275842/3ba7d8e6-268f-11e7-951f-194589e51c7b.png)

OSX: 10.10.5
chrome: 57.0.2987.133 (64-bit)

**Comment by pelikhan** [comment]
Fixed.
