### ISSUE TITLE
Update docs for Set Brightness (not in simulation)

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1948]
microbit.org-ticket: 1589

See also #1947 but I wanted to check if you say anything in the docs about Set Brightness (intentionally) not working in the on screen emulator.

Users are logging tickets telling us that it's not working, but I remember a discussion in some other ticket with @pelikhan a while ago saying that it was not possible to get a consistent set of intensities with a web experience, so it was not implemented.

Could we make sure that the docs (when you fix the broken page!) do actually say that, so that users don't keep logging tickets about it? Ta!

**Comment by pelikhan** [comment]
Fixed.
