### ISSUE TITLE
Adding a new processor (AVR)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#195]
- [x] instruction encoding via a separate class
- [x] thumb.ts -> assembler.ts + thumb.ts
- [x] need special handling of 32-bit instructions (jmp, call) with immediate
- [x] handling of labels for relative jumps
- [x] test avr.ts
- [x] move peephole optimization to thumb.ts (processor-specific)
- [x] remove other ARM-specific functions from assembler.ts to thumb.ts
- [x] create backbase.ts ,skeleton for both backthumb and backavr
- [x] redo backthumb.ts using backbase.ts
- [x] abstract calling convention and SP code
- [x] identify essential core elements of pxt-microbit-core needed 
- [x] refactor for presence of uBit in pxt
- [x] implement backavr.ts using backbase.ts
- [x] create hexfile.ts, skeleton for both hexthumb and hexavr
- [x] update emitter.ts and hexfile.ts to support what's needed for AVR binary format 
- [x] backjs.ts - need to add support for 16-bit word - confirm that @mmoskal did this.
- [x] needs support for deployment using avrdude (or similar).
- [x] make pass over assembler.ts and backbase.ts for assumptions about word size
  - @args, @locals
- [x] relative calls vs. absolute calls (bug)

**Comment by tballmsft** [comment]
@mmoskal - I'd like to get your thoughts about ARM-specific code/assumptions throughout the code base before going much further. I've done a pretty minimal refactoring to allow me to play with defining a new processor instruction encoding, but there's clearly much more needed to get from TS to a new processor.  As you can see, I've been working on AVR, which is 8-bit.

**Comment by mmoskal** [comment]
The IR doesn't really have the concept of a register. You will need some place to store the result of the last computation, just like the js implementation does with the variable R0, but you don't need any other registers. (It will be 4 registers on avr)  
As for back thumb refactoring, I think it's easiest to just clone it and modify. Later we can see if there are some common parts, but we don't really expect more than say 3 CPUs I guess. 
Peep hole optimizations are usually done at the assembler level. You essentially want to look at generated code and see what can you fix easily. They are likely to be different for different cpus. We do some opt in the IR. In general the peep hole is the last thing I would worry about. 
I don't think we should expose sub 32 bit numbers at this point. You can call into the C++ runtime to do the arithmetic operations.

**Comment by tballmsft** [comment]
sounds good to me.

**Comment by tballmsft** [comment]
I updated the TODO list.

**Comment by pelikhan** [comment]
Also needs support for deployment using avrdude (or similar).

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by mmoskal** [comment]
Probably 16 bit ints make most sense, as the pointers are also 16 bit (unless they are code pointers, which may be 17 or 18; gotta love this thing).

**Comment by tballmsft** [comment]
Yes - I am going to focus on getting numbers as 16 bit ints working first.

**Comment by mmoskal** [comment]
I don't think my 16 bit support in backjs is complete enough for this. It only applies to globals right now...
