### ISSUE TITLE
In UK, we call it 'maths' not 'math'

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1950]
UK teachers and children are finding the 'math' palette confusing. Teachers report to us that children are saying 'they spelt maths wrong' or 'what does math mean'.

How could we deal with the country specific terminology differences like this in the PXT editor?

**Comment by pelikhan** [comment]
You could localize that category for "en-uk" locales (and other discrepancies).

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
Note that in JavaScript, Math is singular so it is probably best to keep it singular.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DavidWhaleMEF** [comment]
Ah yes, I see your point...

![screen shot 2017-04-22 at 22 45 51](https://cloud.githubusercontent.com/assets/25079586/25308504/a71784e0-27ad-11e7-8091-ca5d24f17dc3.png)

![screen shot 2017-04-22 at 22 45 45](https://cloud.githubusercontent.com/assets/25079586/25308505/a939f9c4-27ad-11e7-92f4-ab5388cbfe19.png)

So, the same reason that if an API has a setColor() method, it should not be renamed to setColour() as it would break the API. Point taken.

**Comment by DavidWhaleMEF** [comment]
For completeness, the same issue appears on other visual API's so I think you are right, we'll have to live with it.

![screen shot 2017-04-22 at 22 53 01](https://cloud.githubusercontent.com/assets/25079586/25308542/a237e6da-27ae-11e7-933b-76b8e26a1f97.png)

(although e.g. for the German translation, the german word for Math will appear in the palette, but the word Math will appear in the generated javascript code).

It's a tricky balance. Treat it as general user feedback, but I'm not sure we can do anything about this.
