### ISSUE TITLE
Slomo mode looks backwards!

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#1958]
In the following program
https://pxt.microbit.org/_W6ECcWK1TD7c

On Chrome 57, I get the order of steps appearing weirdly when using slowmo mode:
![step through](https://cloud.githubusercontent.com/assets/147113/25346831/b2502aba-2910-11e7-9985-3770569b7fdf.gif)

**Comment by riknoll** [comment]
The issue here is with the source maps; correct behavior is for the "if" block to be highlighted instead of the forever block. I think the presence of the "else if" clause is the problem. I'll take a look.

**Comment by riknoll** [comment]
What I mean to say is that the program isn't executing weirdly, it's just the highlighting in the blocks that's off. Highlighting should work fine in the JS.
