### ISSUE TITLE
Start Melody on IE11

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1968]
microbit.org-ticket: 1611

I don't have IE11 on any of my machines, could you confirm whether you expect this to work or not? Thanks

We did an example for school kids with goolge chrome and the "start melody" function. Now we want to teach 80 school kids on thursday how to use microbit, but only IE11 is available on their laptops. 
Is it possible to use "start melody" with IE11 ?

**Comment by whaleygeek** [comment]
Update from customer:

And we have also the problem, that there is no sound in simulator with IE .

With chrome it works fine.

**Comment by pelikhan** [comment]
Web Audio is not supported in IE11 so this is by design.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by whaleygeek** [comment]
Thanks, this extra info is really useful. I'll make up a k-base article explaining the limitations of using IE11.
