### ISSUE TITLE
Documentation not properly indexed by search engines

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#197]
Because of the dynamic menu generation in /reference and so forth - the search engine are unable to properly index the docs.

**Comment by mmoskal** [comment]
I'm afraid that for now you will have to add a list of links manually at the bottom of the page.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/0bbee119f6e4bd08cf45547d010cc55f7f5a79c4

**Comment by pelikhan** [comment]
Add urls https://github.com/Microsoft/pxt-microbit/commit/b3edb81d3c3c926d73f01b5a6acceb14e053f399
