### ISSUE TITLE
Screen shot feature does not render IconImage

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1970]
Here is a screenshot using the right-click save screenshot feature:

![teleporting-duck-pxt](https://cloud.githubusercontent.com/assets/4086785/25377360/2523c2ca-299f-11e7-9ed5-0cd0a6bba829.png)

This is what was on my screen when I used the feature:

![screen shot 2017-04-25 at 10 07 12](https://cloud.githubusercontent.com/assets/4086785/25377374/305c1a2a-299f-11e7-93a9-c14134289a10.png)

Here is the code
```
input.onGesture(Gesture.Shake, () => {
    basic.clearScreen()
    radio.sendString("DUCK")
})
radio.onDataPacketReceived(({receivedString}) => {
    basic.showIcon(IconNames.Duck)
})
radio.setGroup(5)
```

Please can you help me find my lost duck??!!

**Comment by whaleygeek** [comment]
A Blocks / JavaScript code editor for the micro:bit.

pxt.microbit.org version: 0.9.77

Microsoft MakeCode version: 0.12.25

C++ runtime version: v2.0.0-rc8

**Comment by pelikhan** [comment]
Did you try /beta?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
Fixed in Beta

**Comment by whaleygeek** [comment]
Confirmed, fixed in this build of beta. Thanks.

pxt.microbit.org version: 0.11.12
Microsoft MakeCode version: 0.12.55
C++ runtime version: v2.0.0-rc9
