### ISSUE TITLE
Chrome on Mac can’t load the Editor panel successfully, it said that: ”cannot load package:Version spec mismatch on neopixel”

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#1971]
Repro steps:
• Navigate to https://pxt.microbit.org/beta on Chrome on Mac(OS Version: 10.11.6)
chrome version: 58.0.3029.81

Expect result: the website can display successfully
Actual result: the content panel can't be loaded successfully
![chrome](https://cloud.githubusercontent.com/assets/11880996/25377272/ab8fbf64-29d9-11e7-8ddb-03a8b9f6f43d.gif)

**Comment by abchatra** [comment]
@microsoftsam Seems like a bad bug. Can you repro on Chrome on Mac?

**Comment by abchatra** [comment]
I have seen it happen sometimes. Don't have the consistent repro yet.

**Comment by abchatra** [comment]
We can't repro this here. Can you try for a consistent repro and ask to reopen this?

**Comment by yanlxu** [comment]
we can repro on Chrome on Mac(OS Version: 10.11.6) on consistent, please reopen this.

**Comment by pelikhan** [comment]
Add ?dbg=1 to the URL and copy the console output to the bug report please :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yanlxu** [comment]
The console output please see the attachment.
Only Error Information:
[pxt.microbit.org-ErrorInformation.txt](https://github.com/Microsoft/pxt/files/957763/pxt.microbit.org-ErrorInformation.txt)

All Information:
[pxt.microbit.org-AllInformation.txt](https://github.com/Microsoft/pxt/files/957765/pxt.microbit.org-AllInformation.txt)

**Comment by yanlxu** [comment]
not repro on the Chrome: 58.0.3029.110 and so close it.
