### ISSUE TITLE
Better picker for piano notes in block editor

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#198]
We should be able to display a piano board to pick the notes in the block editor -- rather than a drop down.

uservoice: https://touchdevelop.uservoice.com/forums/402381-code-the-micro-bit/suggestions/15547950-allow-music-notes-to-be-selected-using-a-piano-key

```
Allow music notes to be selected using a piano keyboard. Unless you understand scales properly and what C2, etc means its tricky to write some music. Most children can however play notes of a song given a piano keyboard without knowing what the notes actually are
```

**Comment by abchatra** [comment]
Fixed
