### ISSUE TITLE
prevent decimal numbers in blocks

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#2]
When not supported (like microbit), floating point numbers should not be allowed.

![image](https://cloud.githubusercontent.com/assets/4175913/13857592/ce699c3e-ec37-11e5-9f48-83fb76df041d.png)

**Comment by pelikhan** [comment]
Numberical field support coming up in Blockly.

**Comment by abchatra** [comment]
This impacts kids and a type checker issue.
