### ISSUE TITLE
On beta site, languages other than English have two Maths entries on the toolbox

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt#2001]
Go to https://pxt.microbit.org/beta and choose French from the Language menu.

![capture](https://cloud.githubusercontent.com/assets/989126/25555835/626bae44-2ce8-11e7-8a6e-7586a66104ef.JPG)

**Comment by abchatra** [comment]
@martinwork nice catch

**Comment by abchatra** [comment]
![image](https://cloud.githubusercontent.com/assets/6107272/25599688/01ae1c70-2e93-11e7-82a0-b8e7b25bca2c.png)

Also on-start block is missing.
