### ISSUE TITLE
How do we find errors in javascript?

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2002]
I have a (very large) java script module that I am writing.

Inside pxt I get 13 errors against the filename.

Apart from scrolling up and down the (huge) file trying to find those, is there any way I can just get a list of line numbers, and click on those line numbers to go to the error?

Even better, given that usually it's advisable to fix the first error in the lowest line number first, could we have a button or some workflow that makes it possible to jump to the first error (next error, prev error) perhaps?

Fixing errors in javascript is going to be very hard without something like this, unfortunately.

**Comment by DavidWhaleMEF** [comment]
![screen shot 2017-04-29 at 14 47 44](https://cloud.githubusercontent.com/assets/25079586/25555952/19e8693e-2ceb-11e7-94db-242709408800.png)

**Comment by DavidWhaleMEF** [comment]
As an idea that reuses existing facilities, when I do a search for something I get lovely orange markers in the scroll bar. It would be great if when we click on the red '13' in the ts explorer, that it put red tell-tales in the scroll bar and initiated the same search feature as when searching for text. That way the UX would be identical and obvious. It would also give the necessary 'find next, find prev' and 'total count' feature.

![screen shot 2017-04-29 at 14 52 01](https://cloud.githubusercontent.com/assets/25079586/25555974/9eaf9f70-2ceb-11e7-9415-225324966951.png)

There's a user interface here that is perfect, if only we could get it to search for lines that have an error in them?
![screen shot 2017-04-29 at 14 53 41](https://cloud.githubusercontent.com/assets/25079586/25555981/d41f2752-2ceb-11e7-9f38-07d67dff9999.png)

**Comment by pelikhan** [comment]
Meanwhile, have you taught about using vscode? We have excellent support for large programs there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DavidWhaleMEF** [comment]
Yes, I considered it, but ruled it out actually. I want to get as much experience as possible using the system that our users are using. This means I have the most likelyhood of finding and reporting issues that we can then investigate and fix, so that users don't have to find those issues. Thanks anyway!

I think in this case, a really really simple fix might be to just make the 'oops we could not compile this program, please find and fix those errors' message to then auto focus the edit window in javascript mode to the *first* error in the script. That will be enough to find and fix the error, and the first error is usually the cause of following errors anyway.

My script is now 958 lines long, and scrolling up and down to find out which line has a wavey red line under it is pretty difficult now!

Thanks for your suggestions though. A tiny bit of extra help from the editor would actually solve this problem really nicely I think.

**Comment by pelikhan** [comment]
@sam does Monaco have any command to move to the next error?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tballmsft** [comment]
@DavidWhaleMEF - we can definitely do something like you suggest, but please keep in mind that the web app is not designed for creating very large programs.  We are making a conscious decision to separate "programming in the small" via the web app from "programming in the large" with the VS code extension. For example, VS Code has a full-fledged debugger, which the web app will never have. VS code has support for organizing your solution via directories and many files.  VS Code also has support for C++ and other languages, whereas the web app will just be blocky and JavaScript. 

So, we can do minor things to improve the experience in the web app, but once we start thinking about features that are in VS Code, our solution is going to be to direct users to the VS Code extension.

**Comment by microsoftsam** [comment]
F8 moves to the next error. (in the monaco editor)

**Comment by tballmsft** [comment]
Thanks, Sam. @abchatra - we should document useful Monaco shortcuts for users.

**Comment by pelikhan** [comment]
Can we add those to the context menu?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
Yes.
________________________________
