### ISSUE TITLE
readonly modifier does not work

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2004]
Docs here say you can use readonly:

https://pxt.microbit.org/javascript/classes

When I try this example in pxt, I get errors

```
class Octopus {
    readonly name: string;
    readonly numberOfLegs: number = 8;
    constructor(theName: string) {
        this.name = theName;
    }
}
```

![screen shot 2017-04-29 at 23 40 21](https://cloud.githubusercontent.com/assets/25079586/25559569/48bc9010-2d35-11e7-96da-7a1ee9df0808.png)

**Comment by tballmsft** [comment]
readonly was introduced in TypeScript 2.0. We currently are on TypeScript 1.8.

**Comment by tballmsft** [comment]
I've removed the following doc until we move up to Typescript 2.x:
```
# Readonly modifier

You can make properties readonly by using the `readonly` keyword.
Readonly properties must be initialized at their declaration or in the constructor.

```typescript-ignore
class Octopus {
    readonly name: string;
    readonly numberOfLegs: number = 8;
    constructor (theName: string) {
        this.name = theName;
    }
}
let dad = new Octopus("Man with the 8 strong legs");
dad.name = "Man with the 3-piece suit"; // error! name is readonly.
```

## Parameter properties

In our last example, we had to declare a readonly member `name` and a constructor parameter `theName` in the `Octopus` class, and we then immediately set `name` to `theName`.
This turns out to be a very common practice.
*Parameter properties* let you create and initialize a member in one place.
Here's a further revision of the previous `Octopus` class using a parameter property:

```typescript-ignore
class Octopus {
    readonly numberOfLegs: number = 8;
    constructor(readonly name: string) {
    }
}
```

Notice how we dropped `theName` altogether and just use the shortened `readonly name: string` parameter on the constructor to create and initialize the `name` member.
We've consolidated the declarations and assignment into one location.

Parameter properties are declared by prefixing a constructor parameter with an accessibility modifier or `readonly`, or both.
Using `private` for a parameter property declares and initializes a private member; likewise, the same is done for `public`, `protected`, and `readonly`.
```

**Comment by tballmsft** [comment]
@DavidWhaleMEF  - keep the JavaScript issues coming - we need to make pass over the doc to get it in sync with the state of current implementation.

**Comment by tballmsft** [comment]
@DavidWhaleMEF - I've made a pass over the docs and updated. Will work to keep improving.
