### ISSUE TITLE
AssertionFailed message when hover over red underline in editor

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2006]
I get a red underline in the last line of this TypeScript. When I hover over it to see what the error is in my code, it pops up a tooltip with the text 'AssertionFailed' in it. I suspect your compiler is crashing?

How do I find out what the actual error is in my code, rather than the error that your compiler seems to be getting?? More to the point, if an assertion has failed, how would I find out what the assertion is that has failed so I can give you a more meaningful bug report?!

As a wider question, despite your editor syntax highlighting the word 'map' I can't find a map class in the language implementation for the micro:bit anywhere and no reference to it in the docs. Am I missing something? This is sort of why I was writing this 'dumb' map implementation so I can port my large Python program into TypeScript on the micro:bit (as Python is running out of memory with my script so I thought I would try TypeScript instead).

However I note that looking at some of your micro:bit TypeScript modules, you use a function that has a case statement in it to effectively implement a map. I can't do that in this case, as I want my initial static structure to be extensible, so it needs to be a dynamic data structure.

```
class MyMap<K, V> {

    keys: K[]
    values: V[]

    constructor() {
    }

    push(key: K, value: V) {
        this.keys.push(key)
        this.values.push(value)
    }

    search_array(a: Object[], item: Object): number {
        for (let i = 0; i < a.length; i++) {
            if (a[i] == item) {
                return i
            }
        }
        return -1 // NOT FOUND
    }

    value_for(key: K): V {
        let i = this.search_array(this.keys, key)
        if (i == -1) {
            return null
        }
        return this.values[i]
    }

    key_for(value: V): K {
        let i = this.search_array(this.values, value)
        if (i == -1) {
            return null
        }
        return this.keys[i]
    }

    set(key: K, value: V): void {
        let i = this.search_array(this.keys, key)
        if (i == -1) {
            this.keys.push(key)
            this.values.push(value)
        } else {
            this.values[i] = value
        }
    }

    has_key(key: K): boolean {
        return this.search_array(this.keys, key) != -1
    }

    has_value(value: V): boolean {
        return this.search_array(this.values, value) != -1
    }
}

let z: MyMap<number, string> = new MyMap<number, string>()
```

**Comment by DavidWhaleMEF** [comment]
I'm reading the docs here, but it's not clear if this is for the version of TypeScript that is baked into PXT for the micro:bit or not, as that URL doesn't seem to have any versioning information in it, so it could be for any arbitrary version of TypeScript (probably the latest, but that's not obvious)

https://www.typescriptlang.org/docs/handbook/generics.html

How would I get access to the specific version of TypeScript docs for the version of TypeScript that is baked into the micro:bit PXT build? The pxt docs are not complete in this respect, and in some places in the docs (already reported in another ticket), the docs link out to generic TypeScript docs rather than the docs all being in one place.

Just as a friendly observation: If I'm struggling, I think our target audience will struggle even more, without a definitive set of documentation for the language they are learning. I'm happy to be part of the process that fixes that problem, but I need to know the baseline of where you are starting from to be able to help you in this process.

Thanks

**Comment by tballmsft** [comment]
@DavidWhaleMEF - thanks for the observation. We indeed need to bring our docs up-to-date.

**Comment by tballmsft** [comment]
We do have an internal failure that I will need to debug further.  Here is an improved version of the code, still showing the bug
```
function search_array<T>(a: T[], item: T): number {
    for (let i = 0; i < a.length; i++) {
        if (a[i] == item) {
            return i
        }
    }
    return -1 // NOT FOUND
}

class MyMap<K, V> {

    keys: K[]
    values: V[]

    constructor() {
    }

    push(key: K, value: V) {
        this.keys.push(key)
        this.values.push(value)
    }

    value_for(key: K): V {
        let i = search_array(this.keys, key)
        if (i == -1) {
            return null
        }
        return this.values[i]
    }

    key_for(value: V): K {
        let i = search_array(this.values, value)
        if (i == -1) {
            return null
        }
        return this.keys[i]
    }

    set(key: K, value: V): void {
        let i = search_array(this.keys, key)
        if (i == -1) {
            this.keys.push(key)
            this.values.push(value)
        } else {
            this.values[i] = value
        }
    }

    has_key(key: K): boolean {
        return search_array(this.keys, key) != -1
    }

    has_value(value: V): boolean {
        return search_array(this.values, value) != -1
    }

}

let z = new MyMap<number,string>()
```

**Comment by tballmsft** [comment]
Fixed. Should be in beta tomorrow. Please see https://pxt.microbit.org/_PwraKdfWqg6t for debugged program.
