### ISSUE TITLE
Switching into any language, the project name text box always show the English name "Untitled" unless you reset this project

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2015]
**Repro steps:**

- Navigate to https://pxt.microbit.org/beta
- Click "More..." and choose Language
- Such as French

**Results:**
![may-02-2017 15-46-46](https://cloud.githubusercontent.com/assets/23497626/25608702/a68293fa-2f4e-11e7-9e22-8dc80ccb70e6.gif)

**After I Reset the project:**
![may-02-2017 15-51-21](https://cloud.githubusercontent.com/assets/23497626/25608888/4c5d0f4e-2f4f-11e7-8a48-dcbb37484822.gif)

**Comment by abchatra** [comment]
Note we don't want to change the existing name of the project. If you do a new project after changing the language, name will be localized

**Comment by WendyFeng01** [comment]
But when I changed the language from "Sri Lanka" to "English", the project name still is Sri Lanka, not English name 'untitled',  unless you reset this project.

![3](https://cloud.githubusercontent.com/assets/23497626/25646708/e0e48f14-2f6f-11e7-94bd-e788461b431a.gif)

**Comment by abchatra** [comment]
Yes we don't change the name of the project unless you do a new project. There might be unsaved code and we don't to change the name
