### ISSUE TITLE
The new project also has the previous project setting

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2017]
**Repro steps:**

- Navigate to https://pxt.microbit.org/beta
- Click "Slow-Mo" on the Simulator, or choose "More..."-->"High Contrast on"
- Then delete the project

**Results:**  (the "Slow-Mo" and "High Contrast on" still checked)
![may-02-2017 17-16-28](https://cloud.githubusercontent.com/assets/23497626/25611838/2573844c-2f5b-11e7-8e88-fb8fd55c9216.gif)

**Comment by pelikhan** [comment]
By design, these flags are editor specific - not tied to the project.

**Comment by abchatra** [comment]
Yes by design
