### ISSUE TITLE
Strange artefacts when reloading pages

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2018]
When I reload a page I get strange artefacts on the back of the 'code' area:
They seem to clear up when the simulator runs. 
Chrome 57 on OS X. 
![reload artefacts](https://cloud.githubusercontent.com/assets/147113/25626326/1a6f5ebc-2f57-11e7-8344-d43fd8fd3db0.gif)

**Comment by jaustin** [comment]
PS this remains an issue after an update and restart of Chrome. But I think it's gotta be a Chrome bug?

**Comment by abchatra** [comment]
This is seems like either a Chrome bug or OS X bug

**Comment by abchatra** [comment]
I am closing this issue but if we see in any other box, we will investigate.
