### ISSUE TITLE
The content of the Hint which under "USB connection" is out of its border

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2023]
- Navigate to [https://pxt.microbit.org/beta ](url) (IE, Edge & Chrome)
- Click "?" and choose "Hardware"
- Observe the "Hint" under USB connection

Actual result:
It should show as follows:
![capture2](https://cloud.githubusercontent.com/assets/17866936/25646086/3eb211da-2fe7-11e7-89ec-d4d283023c70.PNG)

Expected result:
![capture3](https://cloud.githubusercontent.com/assets/17866936/25646083/39f244e4-2fe7-11e7-9247-ee44a49f784f.PNG)

**Comment by microsoftsam** [comment]
This is weird and doesn't happen for the Hint in other parts of the documentation. I wonder if it's an authoring issue.
