### ISSUE TITLE
When disable the "Slow-Mo" on IE, the blocks in Content pane still checked.

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2025]
**Repro steps:**

- Navigate to https://pxt.microbit.org/beta on IE
- Drag some blocks of Basic under forever, such as "show leds" and "show icon"
- Enable the "Slow-Mo", and zoom in the Simulator
- Disable the "Slow-Mo", and zoom out the Simulator
- Observing the Content pane

**Results:**
![2](https://cloud.githubusercontent.com/assets/23497626/25646438/424e3f8c-2f6d-11e7-855c-6492cb56016b.gif)
**

**Comment by abchatra** [comment]
@WendyFeng01 What is the bug here?

**Comment by WendyFeng01** [comment]
When I disabled the "Slow-Mo", the block still was checked with yellow border.

This gif will gave you a clear show:
![11](https://cloud.githubusercontent.com/assets/23497626/25687832/600b896e-302e-11e7-8575-d78295a2b8aa.gif)
