### ISSUE TITLE
Supported and unsupported browsers and their minver

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2035]
related ticket: https://github.com/Microsoft/pxt/issues/2026

Do you have any documentation anywhere as to the browsers that are supported by the PXT experience? If there is, could you link me to it and I will update our knowledge-base. If there is no such information, could you consult with your team and make a list of browsers (IE, chrome, firefox, opera), platforms (e.g windows, OSX, linux...) and the minimum version number of each that we would reliably expect the PXT editor experience to work on, I can update our knowledge base. I will also add a workflow when capturing data from users to get this information from them before we log a github ticket with you in future.

**Comment by tballmsft** [comment]
https://pxt.microbit.org/browsers

**Comment by DavidWhaleMEF** [comment]
Fab thanks, I didn't know about that page. That's great!
