### ISSUE TITLE
List of supported phones, browsers and minvers

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2036]
related-ticket: https://github.com/Microsoft/pxt/issues/1035#issuecomment-299099684

Do you have, or could you create, a list of phone platforms, browsers and minvers that are supported by the PXT experience?

Once we have this information, I can update our knowledge-base, and if I see tickets come in on an unsupported platform, I can bounce directly back to the user to say that it is an unsupported platform, rather than logging a github ticket with you.

**Comment by pelikhan** [comment]
We have the /browsers page.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
https://pxt.microbit.org/browsers

**Comment by DavidWhaleMEF** [comment]
Great thanks, I didn't realise that was there. Thanks!
