### ISSUE TITLE
There needs a long time to load page tutorial when click "README.md"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2039]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta 
• Click "JavaScript" --> "Explorer"--> "README.md"
• Observe the page right, this page need a long time to load

**Results:**
![1](https://cloud.githubusercontent.com/assets/23466737/25731756/d6fbfed4-317b-11e7-9f4d-9a8074c57f8d.gif)

**Comment by abchatra** [comment]
We have decided to not fix any explorer bugs for now as they are not used by students. Closing as Won't Fix.
