### ISSUE TITLE
Code card should be clickable (not just header)

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#204]
Currently, only the header is clickable and it is not obvious for users that this can happen. We should make the entire code card clickable.

![image](https://cloud.githubusercontent.com/assets/4175913/17446193/e6485f6e-5afc-11e6-9975-87a23bbc0694.png)

**Comment by microsoftsam** [comment]
Fixed in commit b2362299a72859703edb7371232c53f58c406d17
