### ISSUE TITLE
The page display abnormally when the type of parameter is not right in the block "show string"

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2049]
**Repro steps:**
- Navigate to https://pxt.microbit.org/beta
- Drag block "show string" and "show number" into forever
- Refresh the page

**Results:**
![may-09-2017 14-47-12 chrome](https://cloud.githubusercontent.com/assets/23497626/25841312/2d8fdf00-34d2-11e7-970a-1803c01431b7.gif)

**Comment by samelhusseini** [comment]
No repro. Please provide better repro steps and browser / os configuration if this is still repro'ing for you.
