### ISSUE TITLE
There is no "copy" feature in JavaScript when i want to copy the code

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2051]
**Repro steps:**

- Navigate to https://pxt.microbit.org/beta
- Switch to the "JavaScript" and select the code
- Then right click and choose "copy"

**Except Results ( **IE** ):**
![copy](https://cloud.githubusercontent.com/assets/23497626/25843059/f5a64e52-345a-11e7-8c81-07387a83b6ce.gif)

**Actual Results:**
![othercopy](https://cloud.githubusercontent.com/assets/23497626/25843146/417bb5f6-345b-11e7-882d-7346b9838275.gif)

**Comment by microsoftsam** [comment]
Either by design or a monaco editor issue. But I see the same behavior in the monaco editor playground.

**Comment by pelikhan** [comment]
Copy paste is such a basic keyboard shortcut that Monaco assumes everyone knows (my guess).

**Comment by microsoftsam** [comment]
Fixed in /beta
