### ISSUE TITLE
A trash can in the blockly view that users can drag a block onto to delete it

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#206]
Right clicking a block and delete it / dragging the block onto the toolbar seems unintuitive. Perhaps having a trash can that they can drag a block onto would stand out as the way to delete a block.

**Comment by tballmsft** [comment]
blockly used to have this. not sure if still available.

**Comment by pelikhan** [comment]
code.org<http://code.org>editors don't have the trash can. However they do overlay an image of trashcab over the category list when dragging a block. We should do that instead.

The contextual help for a help is right over the trashcan so there are deeper UI consequences.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by microsoftsam** [comment]
Yeah, if we add the Blockly trash can, our help card is shown over it when a block is selected. 
If we wanted to use the Blockly trash can, we would have to show the help card somewhere else, perhaps top right.

**Comment by pelikhan** [comment]
IMO, we should mimic what code.org<http://code.org> does: the toolbox become a trashcan when a block is dragged.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by pelikhan** [comment]
A trashcan is now displayed.
