### ISSUE TITLE
Negative scrollspeed breaks basic.showNumber

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2060]
The tooltip (help when you hover over) suggest that for `basic.showNumber()` the second parameter can be a negative number, but when I try `basic.showNumber(1234, -100)` it throws the error:

`Program Error: sim error: getResume() not called`

**Comment by tballmsft** [comment]
Good catch. I am working on this.

**Comment by tballmsft** [comment]
Fixed in master and v0.
