### ISSUE TITLE
javascript documentation not found for some functions

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2061]
For some javascript functions, for example `while`-loop, when you right click and select help it shows:

`Oops
We could not load the documentation, please check your internet connection.`

Trying to open the help into a new tab will try to load the url `https://pxt.microbit.org/reference//while` which is missing. I think there were some more functions where this happens, but I haven't made a list of them.

**Comment by pelikhan** [comment]
The double // is suspicious.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nielsswinkels** [comment]
The while only has documentation under the category /blocks/ in the docs, not under /reference/. This url works, but only describes it as a block:
`https://pxt.microbit.org/blocks/loops/while`

**Comment by tballmsft** [comment]
@ganicke, can you look into this?

**Comment by ganicke** [comment]
Sure, I'll take a look.

**Comment by ganicke** [comment]
Are you talking about the context help from the block in the editor not opening the **_while_** topic?

With a quick check it seems to work both on https://pxt.microbit.org and in https://pxt.microbit.org/beta.  Look at the capture here and see if I'm doing the repro correctly:


![while-help](https://cloud.githubusercontent.com/assets/27789908/26175955/56741d54-3b09-11e7-8de3-212a78619ba3.gif)

**Comment by nielsswinkels** [comment]
No I'm talking about doing this while in javascript text mode, not blocks. (btw what do you use to make these gifs?)

**Comment by ganicke** [comment]
Hi, I use ScreenToGif (get it at http://www.screentogif.com). Post your repro if you can. You frame the recorder over the area you want captured so you don't need to grab the entire window if you don't want to.

**Comment by ganicke** [comment]
Will look into this again when a repro is provided. Loop docs are rooted under _/blocks_ as are conditionals and variables.

**Comment by nielsswinkels** [comment]
![pxt doc bug](https://user-images.githubusercontent.com/5718354/29486661-ce41d3ea-84eb-11e7-8c2c-4a4f0ffcce9a.gif)

**Comment by nielsswinkels** [comment]
The problem is that it works for blocks but not for javascript
