### ISSUE TITLE
Unclear error message on undefined variable

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2062]
Example code:
```
let item: number
basic.showNumber(item)
```

Resulting error:
`Program Error: x is undefined`

Why does it say x and not the name of the variable?

**Comment by tballmsft** [comment]
good question. @riknoll?

**Comment by tballmsft** [comment]
Actually, this doesn't repro in pxt.microbit.org. The error message I get is
```
Program Error: Cannot read property 'toString' of undefined
```

**Comment by nielsswinkels** [comment]
I still get the same, both in normal and beta version. 
![image](https://cloud.githubusercontent.com/assets/5718354/26193145/9869ec56-3bb4-11e7-9d14-7df92a35f6af.png)

**Comment by tballmsft** [comment]
I can't repro on chrome. I get this. What browser are you using.

![image](https://cloud.githubusercontent.com/assets/10767146/26790753/b7542942-49c9-11e7-893e-b2ad7ad1b8f9.png)
