### ISSUE TITLE
No visual clue as to whether a block is type compatible or not

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2068]
Teacher reported children struggling with this issue:

Digital read pin’ doesn’t attach to the conditional but it looks like it does.

(There are no visual clues that the digital read pin, which returns an integer, will not fit into an 'if' conditional, because the jigsaw puzzle pieces look like they should fit).

![screen shot 2017-05-10 at 00 16 25](https://cloud.githubusercontent.com/assets/25079586/25876564/e97fa568-3515-11e7-9438-b261a5fbae03.png)

(for reference, scratch has 3 shapes to show type compatibility, circles for numbers, boxes for strings,  diamonds for booleans).

**Comment by pelikhan** [comment]
This is a general issue with blockly which does not support different connectors.

**Comment by tballmsft** [comment]
Closing. Known issue. Won't fix until sometime down the road....
