### ISSUE TITLE
Automatically stop the simulator when a change is detected in Blockly 

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#207]
I find it hard to tell when the simulator has saved my latest change, compiled and is showing it. 
It might be good to invalidate the simulator's run (ie: stop it), if we detect that the user has made a change. Once that change is compiled and ready to run, it can automatically run it. 

Alternatively, we could add a status bar somewhere to indicate that we're re-compiling.

**Comment by tballmsft** [comment]
Currently, the behavior is to restart the simulator after a change has been made, with a small delay in case the user is still editing.  Re-compiling happens instantaneously.  We could pause and gray out the simulator when a change is detected, until the restart happens.

**Comment by pelikhan** [comment]
Turning to sepia while waiting for reload.

**Comment by pelikhan** [comment]
Fixed. Reopen if needed.
