### ISSUE TITLE
MakeCode window rendering is 'odd' on chromebook

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2083]
Chromebook device: http://www.pcworld.co.uk/gbuk/computing/laptops/laptops/asus-c300-13-3-chromebook-red-10017498-pdt.html
Version: Version 57.0.2987.146 (64-bit)
1366 x 768 res I think

screenshot:

![screen shot 2017-05-11 at 20 31 50](https://cloud.githubusercontent.com/assets/25079586/25968435/60c659c2-3689-11e7-9940-7b1e3eb00677.png)

Note how MakeCode does not use the full width of the browser window, and as a result it changes into a 'compact' rendering, loosing the packages pallette in the process.

Script URL is in the URL bar for repro case.

**Comment by microsoftsam** [comment]
This isn't a device specific thing. You're looking at the sharing view of the editor. 
You'll see the same behaviour on any device (not just chrome book). 

In the sharing view, we render a sandboxed view of the editor. Where everything is readonly, and the editor is embedded in an iframe.

**Comment by DavidWhaleMEF** [comment]
Ah yes, well spotted. Thanks!
