### ISSUE TITLE
Adding Devices block "on notified (incoming call)" causes "Program Error" message

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt#2093]
Although the generated hex does seem to work...

![onnotified](https://cloud.githubusercontent.com/assets/989126/26026928/e5965e76-37fc-11e7-943c-fa665b2c50a4.png)

**Comment by pelikhan** [comment]
Are you adding support for those events in iOS?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
Missing simulator support here. Should be easy to add.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
Fixed in beta 0.12.15
