### ISSUE TITLE
Suggested change to package approval process

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2094]
microbit.org-ticket: 1703

This page...
https://github.com/Microsoft/pxt-microbit/blob/master/docs/packages/approval.md

Could you instead of describing the process, just link through to our knowledge-base article here:

https://support.microbit.org/solution/articles/19000054952-package-approval

Thanks

**Comment by tballmsft** [comment]
Fixed by https://github.com/Microsoft/pxt-microbit/commit/5a99315177a5c2ac313c62eae4dbd4e1c61cf087

**Comment by DavidWhaleMEF** [comment]
Great, thanks @tballmsft
