### ISSUE TITLE
The highlight icons are out of High Contrast area when High Contrast is on

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#2099]
Repro steps:
•	Navigate to https://pxt.microbit.org/beta
•	Drag the "show icons" into "forever"
•	Right More…->High Contrast On
Expected result: The highlight icons should be in Whiter area
Actual result: The highlight icons are out of Whiter area
![border](https://cloud.githubusercontent.com/assets/23447632/26094684/7d7e00c0-3a4d-11e7-9f14-27f3f90f9242.PNG)

**Comment by abchatra** [comment]
Won't fix. This is very minor issue and we don't intend to fix this.
