### ISSUE TITLE
Firefox shows different pop up style with safari and Chrome when import file

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#2100]
Repro steps:
• Navigate to https://pxt.microbit.org/beta
• Click Projects->Import File

Expect result: Safari, chrome and Firefox should have same pop up style
![chrome](https://cloud.githubusercontent.com/assets/23447632/26095110/144e6fac-3a4f-11e7-817c-d1d36620ac19.png)
Actual result: Firefox shows different with others
![firefox](https://cloud.githubusercontent.com/assets/23447632/26095125/24284e8e-3a4f-11e7-99a0-0d9831951e86.png)

**Comment by abchatra** [comment]
This is as expected and control is exposed through the browser api
