### ISSUE TITLE
radio simulation does not honour radio group

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2104]
I appreciate this might be a 'nice to have' but when you are using two micro:bits in simulation with the radio (specifically to test software before loading onto real micro:bits) the simulation does not honour the radio group - i.e. all messages are broadcast and received, regardless of the group that is set.

It would be nice if the simulated micro:bit's honoured their set radio group, so that group-changing code can be tested first in simulation.

repro case:
```
let sniff_group = 0
let message = ""
input.onButtonPressed(Button.A, () => {
    sniff_group = (sniff_group + 1) % 10
    radio.setGroup(sniff_group)
    basic.showNumber(sniff_group)
})
input.onGesture(Gesture.Shake, () => {
    radio.sendString("ABC")
})
radio.onDataPacketReceived(({receivedString}) => {
    message = receivedString
    basic.clearScreen()
    basic.showString(message)
    basic.showNumber(sniff_group)
})
input.onButtonPressed(Button.B, () => {
    basic.clearScreen()
    basic.showString(message)
    basic.showNumber(sniff_group)
})
message = ""
sniff_group = 0
radio.setGroup(sniff_group)
basic.showNumber(sniff_group)
```

**Comment by tballmsft** [comment]
@DavidWhaleMEF - as you know, the simulator is not intended to be completely accurate.  This is pretty low priority.

**Comment by tballmsft** [comment]
Well, it's an opportunity for me to learn a new part of the code base...

**Comment by DavidWhaleMEF** [comment]
Thanks @tballmsft - this is not an official request and I know it's low priority. But I was testing this code today and it was one of those 'wouldn't it be nice if' moments - thanks!

**Comment by tballmsft** [comment]
Fixed by https://github.com/Microsoft/pxt-microbit/pull/399

**Comment by DavidWhaleMEF** [comment]
Super, thanks @tballmsft you are a star, sir!
