### ISSUE TITLE
Start Melody (music.beginMelody) with "forever" looping crashes after short time on Micro:bit

### ISSUE THREAD

**Issue by BK303** [Microsoft/pxt#2107]
Playing music using music.beginMelody (aka the "Start Melody" block) with a built-in melody and either MelodyOptions.Forever or MelodyOptions.ForeverInBackground  (the "forever" looping options) causes a run-time crash of Micro:bit after short time, which then displays error 020, 042, or hangs (halt but no error message, no self-reboot).  The length of time until crash depends on the tempo, with default 120 bpm the melody plays for only about 65 seconds, at 360 bpm melody only runs for about 23 seconds.  Issue is not appear dependent on specific melody used, and was reproducible with multiple built-in melodies including shortest and longest, and doesn't seem to be correlated to other activity in foreground.  I first encountered the issue with lots of simultaneous foreground activity, but can reproduce with nothing else running.  Issue observed with both the repeating "Forever" option and the "Forever in background" option.   Simple test case provided below. 

Test case ("On Start" block, "Set Tempo" , "Start Melody" with builtin <any> repeating "forever")
Expected behavior, music plays continuously.
Actual behavior (consistent every run), at tempo 360 bpm music stops after about 25 seconds and displays run-time error 042 or 030.   
JavaScript below was sufficient to reproduce issue by creating new project, clearing JavaScript template, copying two lines below into JavaScript panel, downloading .hex, and copying file to Micro:bit target.  Issue not observed in PXT simulator environment. 
`music.setTempo(360)`
`music.beginMelody(music.builtInMelody(Melodies.Nyan), MelodyOptions.Forever)`

_Sanity Hint: When this code is loaded in https://pxt.microbit.org/ , you may need to scroll down in left simulator panel to access the "mute" or "stop" controls.  With my screen size, the simulator controls were not visible without (non-obvious) scrolling (just off page bottom) because a graphic representing electrical connection for sounds is being displayed above the simulator controls._ 

Version information for observations above: 
> About pxt.microbit.org
> A Blocks / JavaScript code editor for the micro:bit.
> pxt.microbit.org version: 0.9.77
> Microsoft MakeCode version: 0.12.25
> C++ runtime version: v2.0.0-rc8

**Comment by riknoll** [comment]
Just tried this out on a microbit and got the pxt error code over serial (7). Looks like a ref counting issues.

**Comment by kamar535** [comment]
Just tried to put start melody inside forever which results in no sound is played at all and the simulation immediately stops.

**Comment by microbit-mark** [comment]
microbit-support:4684

I have another report of this issue. I can recreate by placing melody in onStart running forever. This results in 042 error on micro:bit after approx 6 seconds. 

https://makecode.microbit.org/_CTmdeziCaVy1

Also makecode docs are unclear on 'forever' and 'forever in background' processes. https://makecode.microbit.org/reference/music/begin-melody

@riknoll @abchatra has any work been undertaken on this bug?

**Comment by mmoskal** [comment]
Fixed in https://github.com/Microsoft/pxt/pull/3623
This will take a while to get to the website though

**Comment by abchatra** [comment]
This is fixed
