### ISSUE TITLE
There should add a comment for ASCII character code for block "text from char code"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2111]
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta
• Drag block "show string" and "text from char code" and simulator is nothing
• Right click on "text from char code" and look help, there also can't find any helpful info

![88](https://cloud.githubusercontent.com/assets/23466737/26136010/fab01f9e-3aeb-11e7-97b9-b5282fb1da83.gif)

**Except result:**
There should add a comment for ASCII character code: for example 65-90 is A-Z and 97-122 is a-z,
so the kids can understand it easily

**Comment by ganicke** [comment]
The page for `fromCharCode` is added in #2846.
