### ISSUE TITLE
Pairing: difference between modes when using Bluetooth and when using Radio

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2113]
At the moment, if you use the Bluetooth package, we use a pairing mode that doesn't require any pin code. If using the default setup (with radio) then when entering pairing mode we *do* require a pin. This is confusing.

Could we configure the two setups the same way, ideally with no pin code?

The yotta config used for Bluetooth is here
https://github.com/Microsoft/pxt-microbit/blob/master/libs/bluetooth/pxt.json#L43

and I think that line is the key one to specify the pairing type

**Comment by martinwork** [comment]
Perhaps Project Settings should expose the pairing mode option for both setups?

Does anyone know what is the effect of using a mixture of hexes with different pairing modes?

My brief tests on iOS seemed to show that flashing and using services from a PassKey hex after pairing with a JustWorks one could be problematic, while the reverse is OK. If so then changing the non-BLE hex mode to JustWorks could create more problems for users who want to use PassKey than the current situation does for users who stick with JustWorks - including all the users with existing PassKey hexes from Touch Develop and BlockEditor.

Slightly off topic... it just struck me as odd that the radio button choice for pairing mode doesn't have a title, like "Bluetooth pairing mode" for instance. Perhaps it would also be good to have a sentence or two of explanation or a link to a help topic?

**Comment by pelikhan** [comment]
Jonny opened a bug on this. We are moving those settings to the core package.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
> Slightly off topic... it just struck me as odd that the radio button choice for pairing mode doesn't have a title, like "Bluetooth pairing mode" for instance. Perhaps it would also be good to have a sentence or two of explanation or a link to a help topic?

There is not radio pairing more, do you have a screenshot of the feature you are referring to?

**Comment by pelikhan** [comment]
Another disaster scenario:
* pair with the phone over BLE
* flash device from desktop
* cannot pair anymore as the pairing information as been erased by DAPLink.

**Comment by pelikhan** [comment]
This dialog in particular should suggest to the user to enter pairing mode when the connection fails:
![image](https://cloud.githubusercontent.com/assets/4175913/26249817/d2389c40-3c5c-11e7-909d-d06f2256ec23.png)

**Comment by pelikhan** [comment]
@jaustin please try the /beta (v0.12.13) . You will see that bluetooth pairing options are always available.

**Comment by martinwork** [comment]
@pelikhan Above, I was referring to the choice of Bluetooth pairing modes we were discussing. This choice is provided by three radio button controls, but there is no title to group them and suggest what choice is being made.

**Comment by martinwork** [comment]
This radio button choice:

![image](https://cloud.githubusercontent.com/assets/989126/26265895/e800365e-3cda-11e7-81d9-7d3ffbe115ec.png)

**Comment by pelikhan** [comment]
They are called "Bluetooth..." with my update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LaurenceRogers** [comment]
I don’t recognise the "disaster scenario".
The Help notes in iOS app 2.0.2 (and previous release) give plenty of advice on how to avoid or recover from pairing and flashing failures.  The suggested strategies have not failed me yet.  If reports suggest otherwise, I will revise the Help notes.

**Comment by LaurenceRogers** [comment]
Pairing mode is unnecessary for flashing if the resident hex file contains the Bluetooth or device package.  The pairing mode nuisance comes about when the file contains the Radio package.
