### ISSUE TITLE
control characters in serial.writestring don't round trip properly

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2114]
microbit.org-ticket: 1815

User is trying to send control codes via serial to control a receiving end terminal emulator.

I tried this, and it seems that every time I switch from javascript to blocks mode, PXT rewrites the code to something different.

Here are successive switches back and forth between javascript and blocks and back again, see how the round-tripping rewrites it to something different every time. This is non terminating I think (i.e. every time I switch back and forth, it rewrites it to something different)

```
input.onButtonPressed(Button.A, () => {
    serial.writeString("\r")
})


input.onButtonPressed(Button.A, () => {
    serial.writeString("\n")
})


input.onButtonPressed(Button.A, () => {
    serial.writeString("\n\n            ")
})


input.onButtonPressed(Button.A, () => {
    serial.writeString(`

            
            `)
})


input.onButtonPressed(Button.A, () => {
    serial.writeString(`

            
            
            `)
})
```

**Comment by DavidWhaleMEF** [comment]
Above, there are 5 separate round-trips between blocks and javascript. The first button handler is what I typed into javascript in a blank palette. Each successive button handler is what I see having then pressed BLOCKS then JAVASCRIPT tabs.

**Comment by DavidWhaleMEF** [comment]
Is this on the list to be fixed do you think? Or is there a workaround we could give to the customer so that they can finish writing their application? Thanks!

**Comment by riknoll** [comment]
I don't think we have a workaround right now. I'll take a quick look into this but I am slightly afraid it's going to be all tied up in Blockly and might be non-trivial to fix. I'll update in a bit.

**Comment by riknoll** [comment]
Okay, looks like blockly does not support escape characters. I agree with that behavior, so I'm going to make the change so that any whitespace character other than a space decompiles to a grey block.
