### ISSUE TITLE
while(true){} yields in JS (probably due to maybeYield)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#2118]
The handler should never be executed, due to the while (true) loop.:
```
input.onButtonPressed(Button.A, () => {
    basic.showIcon(IconNames.Heart)
})


while (true) {

}
```

**Comment by tballmsft** [comment]
@mmoskal - I am working under the assumption (for now) that is due to the maybeYield that is used for making sure animations get run. You mentioned a "lock" to prevent queued handlers from getting run during maybeYield... pointers?

**Comment by mmoskal** [comment]
I will have to dig, but maybe there wasn't one. I remember one but it might have been in TD.

**Comment by tballmsft** [comment]
OK. I found the "lock".

**Comment by tballmsft** [comment]
So the problem is that during a maybeYield during the while(true){} loop, we can react to a buttonpush, queue an event, and start executing it immediately:
```
Runtime.runFiberAsync (pxtsim.js:4231)
EventQueue.poke (pxtsim.js:3941)
EventQueue.push (pxtsim.js:3936)
EventBus.queue (pxtsim.js:4668)
(anonymous) (sim.js:2384)
```

**Comment by tballmsft** [comment]
Well, the basic problem here is whether we want to replicate non-terminating, non-yielding computations in JavaScript. Right now, we give a freer semantics than single-threaded JavaScript.

**Comment by tballmsft** [comment]
So, the basic fix here is to have our runtime's event bus drop events if we are in a maybe yield.

**Comment by tballmsft** [comment]
Fixed in https://github.com/Microsoft/pxt/tree/fixMaybeYield

**Comment by mmoskal** [comment]
@tballmsft thanks for the fix and sorry for the confusion about the lock!
