### ISSUE TITLE
Sometimes some unrelated blocks were found when search in search box

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2119]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Try to enter some character in search box to find related blocks

 **Expected result:** 
 Actual result: Sometimes some unrelated blocks were found
![1](https://cloud.githubusercontent.com/assets/23466737/26230806/308ac2a2-3c7e-11e7-90be-608d925a1d0d.png)

**Comment by pelikhan** [comment]
By design, the search is fuzzy.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Helen09** [comment]
Ok, I will close it.
