### ISSUE TITLE
Failed to exit tutorial when clicked the "More tutorials" button of "Getting Started"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2120]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Choose the "Getting Started" and click one by one
• Click "Finish", choose "More Tutorials"-->"Examples"-->"Spin it"

**Actual result:**
![11](https://cloud.githubusercontent.com/assets/23466737/26231485/22189a10-3c82-11e7-860c-d5a246bdda0f.gif)

**Comment by pelikhan** [comment]
Great find. We should clear the tutorial field before opening the project dialog. @sam

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
