### ISSUE TITLE
The "Hint" icon covers the scrollbar  on tutorial "Getting started"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2121]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Choose the "Getting Started" and click one by one

**Actual result:**
isssue1:
The "Hint" icon covers the scrollbar
![2](https://cloud.githubusercontent.com/assets/23466737/26235020/26ee2f5a-3c9b-11e7-8cc4-27733869a155.gif)

issue2:
The scrollbar's color on browser Chrome is black, it's so strange
![1](https://cloud.githubusercontent.com/assets/23466737/26235215/35be5a7c-3c9c-11e7-9c5e-d9511f55562f.png)

**Comment by Helen09** [comment]
My computer's resolution is 1280 * 1024

**Comment by Helen09** [comment]
This issue also occurs when zoom out screen.

**Comment by microsoftsam** [comment]
Fixed by #2146
