### ISSUE TITLE
Have to be in pairing mode to be able to flash over bluetooth

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2122]
This bug has been around for a while and I see it as really important. I just don't get why I haven't reported it before (sort of assumed it was known..)

To produce the problem:
1. Flash a program using the radio package (can be empty) to the microbit from the pxt editor using a usb cable.
2. Pair the microbit to a mobile device (android or ios doesn't matter).
3. Write code on the mobile device.
4. Now if you try to flash it over bluetooth according to the instructions, the app will not find the microbit (GATT ERROR, or just timeout).

We found out that you (every time!) have to set the microbit in pairing mode before flashing it over bluetooth. This is super unclear, and not how it should be.

But if you in step 1 add the bluetooth package and set it to unsecure bluetooth mode (only this mode), the problem is not there, and you can flash over bluetooth without having to get into pairing mode.

**Comment by pelikhan** [comment]
The issue is that "radio" and "bluetooth" are incompatible. So radio effectively turns off bluetooth which creates the issue.
If you put the device in pairing mode by doing the reset + press AB button you'll be able to pair again from a radio program. The app needs to communicate that.

**Comment by pelikhan** [comment]
See https://github.com/Microsoft/pxt/issues/2122

**Comment by nielsswinkels** [comment]
You are referring to this issue. Which one did you mean to refer to?

**Comment by LaurenceRogers** [comment]
In iOS app 2.0.2, when flashing fails, the flash progress page prompts the user to try again after setting the micro:bit in pairing mode.  This is also explained in the Flash page help notes.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/issues/2113

**Comment by pelikhan** [comment]
@nielsswinkels could you try beta again, we have changed the settings so that the program compiled with radio are also setup in "JustWorks"mode.

**Comment by pelikhan** [comment]
"In iOS app 2.0.2, when flashing fails, the flash progress page prompts the user to try again after setting the micro:bit in pairing mode. This is also explained in the Flash page help notes."
@LaurenceRogers this is not the case on my iphone using microbit 2.0.2.

**Comment by martinwork** [comment]
In 2.0.2 there is a "Help with Flashing" button which opens help notes that include an explanation of the pairing mode problem. However, although we have a development version of the code in which the flashing error page suggests pairing mode, this did not make it into the 2.0.2 release.

**Comment by pelikhan** [comment]
@martinwork "However, although we have a development version of the code in which the flashing error page suggests pairing mode, this did not make it into the 2.0.2 release."

When do you plan to release this fix?

**Comment by LaurenceRogers** [comment]
@pelikhan Version 2.0.3 with updated flashing error message is now released.

**Comment by libraria** [comment]
Who is in charge of updating the Google Play Store so that Android devices can benefit from your ongoing work?  The only thing available there seems to be v2.0 from about 10 months ago and lacks this fix (and presumably many others).

https://play.google.com/store/apps/details?id=com.samsung.microbit

**Comment by libraria** [comment]
Has this fix made its way into an Android app available anywhere yet?

**Comment by abchatra** [comment]
This was fixed. If not let us know.
