### ISSUE TITLE
Devices package: on gamepad button - 1 down and 1 up events are reversed

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt#2129]
Seems to be due to the values of _1Down and _1Up.
The reversal occurs in devices\devices.cpp and devices\enums.d.ts.
Related definitions in core look OK.

```
devices\devices.cpp
    //% block="1 down"
    _1Down = MES_DPAD_BUTTON_1_UP,
    //% block="1 up"
    _1Up = MES_DPAD_BUTTON_1_DOWN,

devices\enums.d.ts
    //% block="1 down"
    _1Down = 10,  // MES_DPAD_BUTTON_1_UP
    //% block="1 up"
    _1Up = 9,  // MES_DPAD_BUTTON_1_DOWN

```

**Comment by pelikhan** [comment]
Fix in 0.12.15

**Comment by martinwork** [comment]
@pelikhan thanks for lightening quick fix, but I can't seem to get it to work.

I'm trying it on beta (pxt.microbit.org version: 0.12.15, Microsoft MakeCode version: 0.12.77, C++ runtime version: v2.0.0-rc9).

I had a look in Project Settings / Explorer and it looks like devices.cpp has the assignments right now but enums.d.ts is still wrong and wasn't changed by commit "swap 1 down / 1 up".

Or is there something I'm not doing when I import my hex?

**Comment by martinwork** [comment]
Thanks @pelikhan . It works now.
