### ISSUE TITLE
slow-mo mode doesn't highlight conditional in loop

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#2130]
For the following code:
```
let x = 0
input.onButtonPressed(Button.A, () => {
    basic.showIcon(IconNames.SmallHeart)
})
x = 1
while (x > 0) {
    x = x + 1
    basic.pause(100)
}
```
You'll see that the two statements in the while loop are highlighted during slow-mode (snail) execution but the loop expression never is:

![image](https://cloud.githubusercontent.com/assets/10767146/26288614/9f8752a6-3e4a-11e7-98d7-4c8f517a2369.png)

**Comment by riknoll** [comment]
Same problem with for-loops
