### ISSUE TITLE
No multi-frame image editor

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2132]
Touch Develop has a multi frame image editor. Children use this all the time to create interesting animations on the micro:bit (as scrolling text is pretty un engaging).

It's not possible to do more than two frames at a time for an animation in PXT.

Would it be possible to add this to the list to put back in, it is a much used feature of TouchDevelop and something that is sorely missed in PXT.

**Comment by DavidWhaleMEF** [comment]
Related ticket: https://github.com/Microsoft/pxt/issues/2131

**Comment by tballmsft** [comment]
@DavidWhaleMEF  - you can sequence things, like below, to get more than two frames.  Sequencing is not a bad thing for kids to learn.

![image](https://cloud.githubusercontent.com/assets/10767146/26422797/1bd4b3e4-4080-11e7-806c-356bce4b462d.png)

**Comment by DavidWhaleMEF** [comment]
Thanks @tballmsft yes that is what a lot of users do. However see the linked ticket, there is a bug in the multi frame sequencing use case where it clears the screen at the end of each double frame - everyone I see doing multi frame work sequences in two frame chunks, because it fits on the screen more easily where there are a lot of frames.

LInked issue: #2131
