### ISSUE TITLE
Discrepancy between simulator/microbit with start semantics

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2133]
microbit.org-ticket: 1842

The following program works fine in the simulator, but does not get past the 'P' screen on the real micro:bit. 

```
let StartFlag = false
basic.forever(() => {
    while (!(StartFlag)) {

    }
    led.plot(2, 2)
    basic.pause(100)
    led.unplot(2, 2)
    led.plot(1, 1)
    if (input.buttonIsPressed(Button.A)) {
        basic.pause(400)
    } else {
        basic.pause(100)
    }
    led.unplot(1, 1)
})
basic.showString("P")
basic.pause(1000)
basic.showLeds(`
    . . . . .
    . . . . .
    . . . . .
    . . . . .
    . . . . .
    `)
StartFlag = true
```

**Comment by DavidWhaleMEF** [comment]
A Blocks / JavaScript code editor for the micro:bit.

pxt.microbit.org version: 0.9.77

Microsoft MakeCode version: 0.12.25

C++ runtime version: v2.0.0-rc8

**Comment by DavidWhaleMEF** [comment]
Also tried on /beta, same problem

**Comment by riknoll** [comment]
Looks like the while loop is the issue here because it shouldn't be yielding the fiber. @tballmsft weren't you looking into something similar?

**Comment by tballmsft** [comment]
@DavidWhaleMEF  - there are race conditions here, that could explain this. Your main thread has several async calls, each of which is implicitly a call.   In the DAL, probably the forever loop is getting executed before the StartFlag is set true by the main thread.

**Comment by DavidWhaleMEF** [comment]
Ok thanks @tballmsft this was a customer script and they were trying to find a workaround themselves. Thanks for the suggested fix, will pass over to customer.
