### ISSUE TITLE
Variables declared in other blocks in documentation

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#214]
If a block uses a variable declared in an earlier block then it will not compile. This is an issue when have multiple blocks explaining a larger program, such as [in this case](https://codethemicrobit.com/device/reactive).

**Comment by tballmsft** [comment]
@thomasdenney  - language issues to @mmoskal, please.

**Comment by pelikhan** [comment]
This is a decompilation/documentation issue, for me.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by pelikhan** [comment]
I don't think this is a P1. The workaround is to redeclare the variable in snippets.
