### ISSUE TITLE
Two icons overlapped on "Getting Started" tutorial

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2140]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Click "Getting Started"

**Actual result:**
These two icons overlapped
<img width="1021" alt="screen shot 2017-05-23 at 11 01 38 am" src="https://cloud.githubusercontent.com/assets/23466737/26343222/9d8ec054-3fcd-11e7-8f3d-640762d00ad1.png">

**Comment by microsoftsam** [comment]
Fixed by #2146
