### ISSUE TITLE
invalid variable name

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2142]
If you create a variable with the name "input" it gives this error when you try to set a value to it:
> invalid left-hand side of assignment expression

The reason is that the name `input` is already used by a category. But that is not clear from the error message.

**Comment by riknoll** [comment]
Also an issue for reserved words like "let"

**Comment by nielsswinkels** [comment]
Is this supposed to be fixed? I'm still having this issue, even in beta.

**Comment by riknoll** [comment]
Needs to be moved over to V0. I'll take care of it.
