### ISSUE TITLE
The icon "Open documentation in new tab" and the text in the document overlapped

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2148]
Repro steps:
• Navigate to https://makecode.adafruit.com/
• click the help "?" and then choose the "JavaScript"
• click the "Sequencing"

Expect result:
the icon "Open documentation in new tab" should display on the upper left of the document and didn't overlap with the text in the document
Actual result:
the icon "Open documentation in new tab" and the text in the document overlapped, the details please see the gif1

gif1:
![test9](https://cloud.githubusercontent.com/assets/11880996/26397452/fc3f7f36-40a8-11e7-85d2-fddfeb0d6932.gif)

**Comment by abchatra** [comment]
We don't intend to fix this. This is a minor issue to address. Wont' Fix.
