### ISSUE TITLE
maybeYield semantics doesn't agree with DAL semantics

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#2149]
The maybeYield feature allows two things to happen:
1. the JavaScript runtime to get a chance to run event handlers
2. permit other (user-level) runtime fibers to run

(1) above corresponds to the DAL periodically interrupting to poll sensors/buttons

(2) does NOT correspond to the DAL, which only allows a user-level fiber to run when an explicit yield has taken place.

**Comment by microsoftsam** [comment]
Moving up to P1 as this is something we really need to fix to match (init and loop) semantics that our users may be used to.

**Comment by abchatra** [comment]
Closing old issues. If this is still relevant please let me know. I will reopen in pxt-microbit.
