### ISSUE TITLE
Spelling error in neopixel setBrightness in javascript view

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2153]
microbit.org-ticket: 1868

In blocks:
![screen shot 2017-05-25 at 17 06 00](https://cloud.githubusercontent.com/assets/25079586/26458905/9586039a-416c-11e7-9ecf-b2e7f8274975.png)

in javascript (not the mis-spelling of setBrightness)
![screen shot 2017-05-25 at 17 06 10](https://cloud.githubusercontent.com/assets/25079586/26458911/9c9d7ff0-416c-11e7-93dd-1bc2cb1c56cf.png)

**Comment by abchatra** [comment]
fixed by https://github.com/Microsoft/pxt-neopixel/pull/12
