### ISSUE TITLE
Can you surface additional SPI methods, to make it usable in PXT?

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2158]
microbit.org-ticket: 1862

It doesn't see possible in PXT at the moment to use the SPI in anything other than it's default configuration.

Could you surface additional configuration methods for the SPI peripheral.

The DAL reference information is here:

https://lancaster-university.github.io/microbit-docs/extras/spi/

The SPI object must be constructed at the start of the program, if the SPI peripheral is used anywhere in the program. Examples are in the above lancaster dal page.

The SPI on the micro:bit is just the mbed 2 SPI driver, documented here:

https://developer.mbed.org/handbook/SPI

We need to be able to change the following parameters:

clock frequency (using spi.frequency)
bits and mode (using spi.format(bits, mode) - specifically so that we can set CPOL and CPHA

To be consistent with the MicroPython implementation, it would be desirable, but not mandatory, to also make it possible to reconfigure the pins used for SCLK MOSI and MISO - although this is not strictly necessary, only for consistency.

Also, we will need associated docs pages for all those new blocks.

Once these new methods are surfaced, let me know, and I can write and test an example using the new methods, and write a small example for the docs for you.

**Comment by pelikhan** [comment]
I've pushed those APIs in the pxt repo. Can you send a PR with the updated docs?

**Comment by abchatra** [comment]
@pelikhan is this fixed?

**Comment by pelikhan** [comment]
Needs testing from David.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DavidWhaleMEF** [comment]
Thanks. We're on a holiday at the moment in UK but will test next week. Thanks for the fast work on this.

**Comment by pelikhan** [comment]
Closing, please send PR for additional examples in docs.
