### ISSUE TITLE
QA for data streaming

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#216]
I'm currently unable to successfully stream data to Azure from a micro:bit. I see `HTTP 400` responses, possibly because of a [bad key coming from the micro:bit](https://github.com/Microsoft/pxt-microbit/issues/200):

![azure-1](https://cloud.githubusercontent.com/assets/20356546/17555570/ea0b8c16-5f07-11e6-8c19-74d6fff755e2.png)

After sending correct JSON data to Azure using the [pxt-windowsiot demo](https://github.com/microsoft/pxt-windowsiot) I found that I was rate limited after 67 requests, which for some (reasonable) scenarios will be too low. Even after sending correct data, I found that the [generated CSV and JSON files](https://codethemicrobit.com/fcbzuonchztp) contain no data.

The generated CSV is malformed due to unescaped characters (the JSON spreads over multiple columns):

![data-stream](https://cloud.githubusercontent.com/assets/20356546/17555809/db5700be-5f08-11e6-990b-aca0dcadafea.PNG)

@darrenge, @tballmsft Can you replicate this?

**Comment by mmoskal** [comment]
The rate limit is a bit more than 1 per minute, however you can do up to an hour worth of burst requests. The IOT demo should batch send data at the rate of 1 request per minute. It can send many samples in a single request (up to 32KB per request).

**Comment by abchatra** [comment]
Closing this as won't fix.
