### ISSUE TITLE
setDisplayMode(DisplayModel.Greyscale) is useless

### ISSUE THREAD

**Issue by Spongman** [Microsoft/pxt#2167]
it is possible to call `setDisplayMode(DisplayModel.Greyscale)` from javascript, but it seems as though this is useless since there's no way to call setPixelValue (outside of plot()) from javascript.

please expose setPixelValue so we can use per-pixel brightness.

**Comment by pelikhan** [comment]
Greyscale is available through sprite brightness but there are no APIs yet to manipulate directly.
