### ISSUE TITLE
iPad: Repeated taps on undo, redo and zoom buttons cause zoom of whole page

### ISSUE THREAD

**Issue by martinwork** [Microsoft/pxt#2173]
Trying to zoom in with multiple taps, Safari sees a double-tap and tries to zoom the whole page to the button, which doesn't seem like something I would ever want. The same applies to undo and redo.

![img_0059](https://cloud.githubusercontent.com/assets/989126/26521657/82c9d126-42e5-11e7-891a-8960a1a6a6aa.PNG)

**Comment by microsoftsam** [comment]
```
From the iOS 10 release notes:
To improve accessibility on websites in Safari, users can now pinch-to-zoom even when a website sets user-scalable=no in the viewport.
```
Looks like our current solution setting user-scalable=no no longer works on IOS 10.

**Comment by microsoftsam** [comment]
We'll have to look into a JS solution to disable that feature in Safari.

**Comment by martinwork** [comment]
The last couple of posts on this page have suggestions for applying to individual controls.

https://stackoverflow.com/questions/37808180/disable-viewport-zooming-ios-10-safari

**Comment by abchatra** [comment]
Does this bug still exist? We made number of improvements to touch specifically for ipad. Do let us know if this still repros. Closing for now.

**Comment by martinwork** [comment]
Still repros on iOS 11 Safari.

**Comment by abchatra** [comment]
Yes I can repro this too. ported https://github.com/Microsoft/pxt-microbit/issues/909

**Comment by martinwork** [comment]
This happens on other makecode variations too.
