### ISSUE TITLE
microbit missing functions

### ISSUE THREAD

**Issue by Spongman** [Microsoft/pxt#2175]
where are:
- floor
- round
- sin/cos/tan
- unplotAll (there's a plotAll)

**Comment by abchatra** [comment]
Microbit is integer only math.  I am not sure the use of trigonometric functions here.

**Comment by pelikhan** [comment]
`unplotAll` is `basic.clear`.

**Comment by abchatra** [comment]
Please provide additional information why you need them.

**Comment by rharbird** [comment]
Please consider reopening this.

In our microbit summer schools we use trig functions. To give a specific example: students are asked to transform the motion of an 180 degree servo motor to a mimic a Central Pattern Generator. The servo motors are used in a caterpillar robot. A CPG is basically a sine wave.  My colleague Stephen Hailes wrote the function below. It would be good if this and other trig functions were included in the Math library for robotics applications. We understand the floating point limitations.

/**
     * Calculate sin(angle) * 10000 from a table.
     * @param angle the angle of which to calculate the sine
     * @returns sin(angle)*10000
     */
    //% block
    export function sinx10000(angle: number): number {
        let sintab = [
            0, 174, 348, 523, 697, 871, 1045, 1218, 1391, 1564,
            1736, 1908, 2079, 2249, 2419, 2588, 2756, 2923, 3090, 3255,
            3420, 3583, 3746, 3907, 4067, 4226, 4383, 4539, 4694, 4848,
            5000, 5150, 5299, 5446, 5591, 5735, 5877, 6018, 6156, 6293,
            6427, 6560, 6691, 6819, 6946, 7071, 7193, 7313, 7431, 7547,
            7660, 7771, 7880, 7986, 8090, 8191, 8290, 8386, 8480, 8571,
            8660, 8746, 8829, 8910, 8987, 9063, 9135, 9205, 9271, 9335,
            9396, 9455, 9510, 9563, 9612, 9659, 9702, 9743, 9781, 9816,
            9848, 9876, 9902, 9925, 9945, 9961, 9975, 9986, 9993, 9998, 10000]

        angle = angle % 360;
        if (angle <= 90)
            return (sintab[angle])
        else if (angle < 180)
            return (sintab[180 - angle])
        else if (angle < 270)
            return (-sintab[angle - 180])
        else
            return (-sintab[360 - angle])
    }

 





/**
     * Calculate sin(angle) * 10000 from a table.
     * @param angle the angle of which to calculate the sine
     * @returns sin(angle)*10000
     */
    //% block
    export function sinx10000(angle: number): number {
        let sintab = [
            0, 174, 348, 523, 697, 871, 1045, 1218, 1391, 1564,
            1736, 1908, 2079, 2249, 2419, 2588, 2756, 2923, 3090, 3255,
            3420, 3583, 3746, 3907, 4067, 4226, 4383, 4539, 4694, 4848,
            5000, 5150, 5299, 5446, 5591, 5735, 5877, 6018, 6156, 6293,
            6427, 6560, 6691, 6819, 6946, 7071, 7193, 7313, 7431, 7547,
            7660, 7771, 7880, 7986, 8090, 8191, 8290, 8386, 8480, 8571,
            8660, 8746, 8829, 8910, 8987, 9063, 9135, 9205, 9271, 9335,
            9396, 9455, 9510, 9563, 9612, 9659, 9702, 9743, 9781, 9816,
            9848, 9876, 9902, 9925, 9945, 9961, 9975, 9986, 9993, 9998, 10000]

        angle = angle % 360;
        if (angle <= 90)
            return (sintab[angle])
        else if (angle < 180)
            return (sintab[180 - angle])
        else if (angle < 270)
            return (-sintab[angle - 180])
        else
            return (-sintab[360 - angle])
    }

**Comment by edrandall** [comment]
Absolutely agree, for robotics purposes polar/cartesian conversion is essential.
Fortunately in the latest version these functions are now available under the Math/square root block
- square root
- sin
- cos
- tan
- atan2
- integer divide
- integer multiply
