### ISSUE TITLE
Device Serial Number and transmitted Bluetooth Serial Number differ

### ISSUE THREAD

**Issue by EdNutting** [Microsoft/pxt#2177]
Hi!

Referring to Micro:bit Code editor on https://pxt.microbit.org/:

```
pxt.microbit.org version: 0.9.77
Microsoft MakeCode version: 0.12.25
C++ runtime version: v2.0.0-rc8
```

The serial number transmitted via Bluetooth is different from the one reported using the control block "device serial number". I'm not sure if that's supposed to be the case or not but it'd be useful if they were the same - otherwise, how can code know a device's own Bluetooth serial number? 

Not been able to test this with two physical devices yet (so I don't know if it's intentional functionality or a simulator error). 

Cheers,
Ed

**Comment by pelikhan** [comment]
Could you post a repro? We have fixed a similar issue in the simulator related to radio.

**Comment by EdNutting** [comment]
No problem - see attached.
[Simulator-Serial-Simplest-Repro.zip](https://github.com/Microsoft/pxt/files/1040851/Simulator-Serial-Simplest-Repro.zip)

**Comment by pelikhan** [comment]
This issue is fixed in https://pxt.microbit.org/beta .
