### ISSUE TITLE
cleanup docs.js

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#218]

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/a2acfe17ee22914acaa90699fca2f1f36865bca4

**Comment by thomasdenney** [comment]
@pelikhan This was added to resolve https://github.com/Microsoft/pxt/issues/92. Do you want the functionality removed completely or moved to a separate script?

**Comment by thomasdenney** [comment]
Leaving this for now.
