### ISSUE TITLE
For Loops

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#2184]
In Edge,

1.) For Loops in Blocks and Typescript not matching (stay consistent with either "i" or "index" variable name, use the same max value "4" or "5", and use "<=" or "<")

2.) Changing For Loop values in Typescript not decompiling to blocks correctly.  Repro steps:
- In Monaco, drag out a For Loop, and write the following...
let start = 2
for (let i = start; i < 5; i++) {
    basic.showNumber(i)
}
- Covert to blocks
<img width="185" alt="forloop" src="https://cloud.githubusercontent.com/assets/22108954/26605631/96f01a06-4543-11e7-9422-d6d23d738384.PNG">

**Comment by riknoll** [comment]
#2 is fixed in master. That scenario will now decompile to a grey block.

**Comment by riknoll** [comment]
1 is referring to the Monaco toolbox snippets

**Comment by abchatra** [comment]
This is fixed
