### ISSUE TITLE
Bluetooth settings in the project settings is confusing

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#2185]
![bluetooth settings](https://cloud.githubusercontent.com/assets/6107272/26606753/105e06c4-4548-11e7-9ad2-7d8ea28e8fef.gif)

As soon as an option is selected it moves editor, giving no indication that options is enabled.
Please wait till save is clicked.

**Comment by pelikhan** [comment]
Using JustWorks as default, moving options back to bluetooth project

**Comment by martinwork** [comment]
@pelikhan Why make this change? This has nothing to do with the UI problem @abchatra identifies.

Why deny this option to users who want to use pass key pairing?

**Comment by pelikhan** [comment]
The users get the options when they reference the bluetooth package. The current UI is confusing and needs work to be brought into the "mainstream" experience.

**Comment by pelikhan** [comment]
@martinwork when will the app suggest to the user to go into pairing mode upon a failed flash? this is still a critical step in the flow.

**Comment by martinwork** [comment]
In the next release.

This UI is confusing because setting the pairing mode causes the dialogue to disappear immediately.

It is appropriate for users to have control over the pairing mode even if not using the Bluetooth package.

**Comment by martinwork** [comment]
The UI issue is still there when you have the Bluetooth package.

It would be better if projects had the Bluetooth package by default, so that the problem of having to select pairing mode in order to flash didn't occur for novice users and only became an issue for more advanced users deciding to use radio or other package incompatible with Bluetooth.

**Comment by martinwork** [comment]
Should this be reopened until the original issue is fixed?

**Comment by pelikhan** [comment]
You can reopen, we can discuss this after this release.

**Comment by martinwork** [comment]
I don't think I can, can I @abchatra ?

**Comment by abchatra** [comment]
Moved to https://github.com/Microsoft/pxt-microbit/issues/903
