### ISSUE TITLE
Some melodies are not musically correct

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2186]
At least two of the melodies are incorrectly played back.

DaDaDum and Birthday both have duff notes in them - please listen to them and you will hear that they are wrong. Could you correct them please? I think it would be worth checking all melodies against the original Python source, to see if some transcription errors have occurred in the process. Some of the notes are wrong, and also some of the phrasing is wrong.

```
input.onButtonPressed(Button.A, () => {
    music.beginMelody(music.builtInMelody(Melodies.Birthday), MelodyOptions.Once)
})
```

**Comment by microsoftsam** [comment]
I think this has been fixed. @DavidWhaleMEF ?

**Comment by abchatra** [comment]
Fixed
