### ISSUE TITLE
The "On Pin Pulsed High/Low" Function Doesn't Work

### ISSUE THREAD

**Issue by harveytwyman** [Microsoft/pxt#2188]
The example in your documents ( shown below ) doesn't respond to any pin high or low.

It doesn't work in the Beta Version either.

basic.forever(() => {
})
pins.onPulsed(DigitalPin.P11, PulseValue.High, () => {
    basic.showString("Hi")
})

**Comment by ganicke** [comment]
I can't find the particular example you cited in the current docs. What's the title or page url you're referring to?

**Comment by ganicke** [comment]
This example is no longer in the docs.
