### ISSUE TITLE
Tutorial - instruction clarification

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#2189]
Step 5 on the Getting Started Tutorial - add "in an On Shake block" to the instruction text.

<img width="498" alt="gettingstarted" src="https://cloud.githubusercontent.com/assets/22108954/26607919/a22627ee-454d-11e7-8392-6d58832218d2.PNG">

**Comment by pelikhan** [comment]
All steps should have an animated gif. We've seen that it really helps the students.

**Comment by microsoftsam** [comment]
There seems to be a bug in the tutorial parsing where it's cutting off the message that gets shown. I'll investigate.
