### ISSUE TITLE
When I deleted package in EXPLORER under {}javascript, it still display after refreshing page

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2196]
Repro Steps:
1.  Navigate to https://makecode.adafruit.com/
2.  Switch to {}JAVASCRIPT and expand EXPLORER
3.  Delete package like "MUSIC"

Results:
![explorer](https://cloud.githubusercontent.com/assets/23497626/26626039/7f99f17a-4628-11e7-9329-7a771c483bca.gif)

**Comment by abchatra** [comment]
@WendyFeng01 Explorer is an advanced scenario which we don't expect kids to use. We are planning to not to address any bugs on this as well. So won't fix from our side. Even though this is a valid bug, won't fix from our side.
