### ISSUE TITLE
Project's example "Egg game" have an error.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2197]
**Repro step:**
- Navigate to https://makecode.adafruit.com/
- Click "Project->EXAMPLE->Egg game"

**Expected Result:**
1. Simulator should display normal.
2. It shouldn’t have error in following example of Project. And it could switch JavaScript to Blocks successfully.

**Actual result:**
1. Simulator disappeared.
2. There are some errors in example's code which result in can’t switch JavaScript to Blocks successfully.
![example](https://cloud.githubusercontent.com/assets/17866936/26625651/5b7fe0b6-4627-11e7-9c62-82c026e7c864.PNG)

**Comment by tballmsft** [comment]
Fixed.
