### ISSUE TITLE
The color gap is too big

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2198]
Repro Steps:
1.Navigate to https://makecode.adafruit.com/
2.Drag "show ring" under forever
3.Choose Pink color to color the light

Results:
![color](https://cloud.githubusercontent.com/assets/23497626/26626396/b8047b56-4629-11e7-8f48-7ef40db4f802.PNG)

**Comment by abchatra** [comment]
Won't fix
