### ISSUE TITLE
Accessibility: Labels or Instructions (WCAG 3.3.2)

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#2209]
Standard:
When user input is required, provide instructions or labels describing necessary input and expected data formats to prevent validation errors.

https://www.webaccessibility.com/best_practices.php?best_practice_id=494

Currently: 
Share has a form without labels. 
Settings looks good. 
Add package has a search field without a label.

**Comment by veler** [comment]
Those points are part of [https://github.com/Microsoft/pxt/pull/2446](https://github.com/Microsoft/pxt/pull/2446)
