### ISSUE TITLE
Chrome extension doesn't see serial data on Chromebook

### ISSUE THREAD

**Issue by abjectio** [Microsoft/pxt#2212]
Related to isse #977 
Testing extension on a chromebook and it does not write data back from the microbit.
Test code :  
`let item = 0
input.onButtonPressed(Button.A, () => {
    item = input.lightLevel()
    serial.writeValue("lightlevel", item)
})
serial.writeLine("Start")
`
Where is the code to the Chrome Extension ?

**Comment by samelhusseini** [comment]
Chrome extension has been retired. Closing.
