### ISSUE TITLE
compass project is technically wrong

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2214]
This tutorial is technically wrong - the 'N' is not calculated correctly

![screen shot 2017-06-04 at 14 25 12](https://cloud.githubusercontent.com/assets/25079586/26761996/b59cb8dc-4931-11e7-9eba-1ac34c193799.png)
![screen shot 2017-06-04 at 14 26 42](https://cloud.githubusercontent.com/assets/25079586/26762004/d95d94f8-4931-11e7-94a0-8b47a9df9b97.png)

**Comment by tballmsft** [comment]
Fixed at https://pxt.microbit.org/projects/compass. Please confirm fix is correct.

**Comment by DavidWhaleMEF** [comment]
LGTM
