### ISSUE TITLE
micro:bit incomplete package page

### ISSUE THREAD

**Issue by carlosperate** [Microsoft/pxt#2219]
The micro:bit documentation page for the packages (https://github.com/Microsoft/pxt-microbit/blob/master/docs/packages.md) should have all the packages listed in the navigation menu (https://github.com/Microsoft/pxt-microbit/blob/master/docs/SUMMARY.md).

**Comment by caitlin-hennessy** [comment]
Fixed by https://github.com/Microsoft/pxt-microbit/pull/465

**Comment by carlosperate** [comment]
Thanks @caitlin-hennessy !
