### ISSUE TITLE
Block "show ring" download screenshot is not consistent with the block in content pane 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2222]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Drag block "show ring" and put it under "forever"
• Right click content pane to download Screenshot

**Expect result:**
 ![expect](https://cloud.githubusercontent.com/assets/23466737/26817036/57d9cd24-4ac7-11e7-8026-ccb1df8c2f72.PNG)
**Actual result:**
![actual01](https://cloud.githubusercontent.com/assets/23466737/26817148/f71b39d6-4ac7-11e7-8056-fbd6fb57c89d.png)

**Comment by microsoftsam** [comment]
Fixed in /beta
