### ISSUE TITLE
Function Math.clamp's parameter requirements can't be seen completely

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2223]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Click "JAVASCRIPT" 
• Type "Math." then look the function Math.clamp

**Expect result:**
This function should can be seen the complete parameter requirements
**Actual result:**
There is no way to look this function's parameter requirements
![actual01](https://cloud.githubusercontent.com/assets/23466737/26818373/fc21a406-4acc-11e7-8e6a-48f1b07bd7e3.png)

**Comment by abchatra** [comment]
This is won't fix for us. Preview is supposed to be minimal and should fit the window
