### ISSUE TITLE
After adding comment for a block, in "Slow-Mo" mode this block will not be selected

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2224]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Drag two "show string" and put them under "forever"
• Click "Slow-Mo" and observe the contemt pane
• Add comment for one block "show string" and observe the content pane again

**Actual result:**
![4](https://cloud.githubusercontent.com/assets/23466737/26820123/4dcd4038-4ad4-11e7-8184-129a34a33b3e.gif)

**Comment by abchatra** [comment]
Comments seems to mess up the highlighted blocks.

**Comment by riknoll** [comment]
Also messes with highlighted text in Monaco
