### ISSUE TITLE
The function "import File" should limit the type of file which was selected to import

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2225]
Repro steps:
• Navigate to https://makecode.adafruit.com/
• click "PROJECT" and select the function "import File"
• click the "Choose File" to select the file

Expected result:
 It should limit the type of file which was selected to import
Actual result:
 It could import the all types of files, such as the "exe" file
![importfile](https://cloud.githubusercontent.com/assets/11880996/26820473/872d4926-4ad5-11e7-9cd8-697549ef52d6.gif)

**Comment by abchatra** [comment]
This is a corner case and Won't fix from us.
