### ISSUE TITLE
Serial data transfer to browser failing

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2230]
microbit.org-ticket: 1949

I had a fidget spinner meter set up today at code club. My intention was to use the serial interface to read out the RPM (inspired by the micromonsters YouTube channel). 

The serial interface readout worked perfectly when I prototyped this at home, i.e. the RPM was updated pxt.microbit.org webpage every second with a graph showing previous values. On the school laptops though, the serial interface was completely unresponsive. I could not see any issues in the Chrome console (we are using Chrome). When I switched in my personal laptop it worked again. 

It seems to me that something in the schools network security is blocking the serial communication. In order to get this fixed, it would really help me if I could understand how the serial communication is working, i.e. how is the website reading from the serial port. Ideally I would be able to give the school a clear instruction (i.e. please unblock 'X') to get this resolved quickly. I want to do a pulse meter with the serial interface next week!

Any thoughts would be gratefully received.

**Comment by philgolden** [comment]
Hi, reading up on the serial port documentation, I notice that I may need to have the mbed Windows serial port driver installed. I actually installed this on my personal laptop a while ago (which may be why it worked) but it won't be on the school's computers. If this is indeed accurate, then I need to have this installed in school and I apologise for wasting your time. Let me know if this sounds like the issue.

**Comment by tballmsft** [comment]
@philgolden: On Windows, this is correct.

**Comment by pelikhan** [comment]
Is it the micromonster fidget lesson? Otherwise please share!

**Comment by philgolden** [comment]
Peli,

Yes, it is that lesson tailored for code club. I can't believe I only
discovered the micromonster channel last week, it is literally
inspirational!

Phil
