### ISSUE TITLE
 Can't  switch code from "JAVASCRIPT" to "BLOCKS" on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2245]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ on IE
• Click "PROJECT" -> "EXAMPLES" -> "Blinky"
• Click "BLOCKS" 

**Expect result:**
Project "Blinky" can switch from "JAVASCRIPT" to "BLOCKS"

**Actual result:**
Project "Blinky" can't switch from "JAVASCRIPT" to "BLOCKS"
(Project "power glove" and "Level" can't switch from "JAVASCRIPT" to "BLOCKS")
![4](https://user-images.githubusercontent.com/23466737/26917062-52c664ca-4c5f-11e7-9572-ee5377943d28.gif)

**Comment by abchatra** [comment]
This is a good find. Thanks @Helen09. @microsoftsam please prioritize.

**Comment by microsoftsam** [comment]
I believe this is another sideeffect of #2244

**Comment by microsoftsam** [comment]
which I fixed last night https://github.com/Microsoft/pxt-adafruit/commit/7f15423f941e24f951956e103f8d6e09b141db6b

**Comment by microsoftsam** [comment]
Verified this has been fixed by my fix.

**Comment by abchatra** [comment]
Awesome thanks!
