### ISSUE TITLE
Click the block, the comments expand at the same time

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2246]
**Repro step:**
• Navigate to https://makecode.adafruit.com/
• Drag the "show ring" into "forever"
• Right click "show ring" and add comments
• Click the blank space
• Then click the "show ring"

**Expected Result:**
Only choose the block
**Actual result:**
Click the block, the comments expand at the same time
![comments](https://user-images.githubusercontent.com/23497626/26917588-76c82be0-4c61-11e7-80bc-3f59d5a531b0.gif)

**Comment by microsoftsam** [comment]
Blockly feature, won't fix.
