### ISSUE TITLE
There is an extra scrollbar on block "on light dark" explanation

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2247]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ on Chrome
• Click "INPUT"
• Move cursor mouse on block "on light dark"

**Expect result:**
 Block "on light dark" explanation can show completely, so there shouldn't have a black scrollbar

**Actual result:**
![actual01](https://user-images.githubusercontent.com/23466737/26918448-aa87c46a-4c64-11e7-9709-eed40f39d7e9.png)

**Comment by microsoftsam** [comment]
This isn't trivial to fix, and I think we need to think hard about how valuable the on hover show js text feature is.

**Comment by pelikhan** [comment]
Cut it out.

**Comment by microsoftsam** [comment]
I've actually already fixed the issue, it wasn't as difficult as I thought, but happy to talk about cutting the feature.

**Comment by pelikhan** [comment]
It was a nice experiment but it's more noisy than anything else.
