### ISSUE TITLE
Link is missed at the bottom of the Reference 

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2248]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Click "?" then choose "Reference"
• Click "blocks" in "See Also" at the bottom of the Reference
• Then click on any one in "See Also", such as "loops"

**Expected Result:**
Link is there and can be clicked 
**Actual result:**
Link is missed.

![reference](https://user-images.githubusercontent.com/23497626/26919025-cf1f2e6a-4c66-11e7-9384-42de86d59cc7.gif)

**Comment by ganicke** [comment]
Added 'See also' linking for base block pages.

* https://github.com/Microsoft/pxt-adafruit/pull/252
* https://github.com/Microsoft/pxt/pull/2482
