### ISSUE TITLE
When stopped the simulator, the power indicator is on

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2249]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ on IE
• Click the "stop the simulator" button

**Expected Result:**
![edge01](https://user-images.githubusercontent.com/23497626/26922202-03e6a3c6-4c71-11e7-9c5b-4887da0e9a51.PNG)
**Actual result:**
![ie](https://user-images.githubusercontent.com/23497626/26922214-0d0ab9c4-4c71-11e7-8656-bf48233a4aa6.PNG)

**Comment by microsoftsam** [comment]
Grayscale filter not supported in IE11. won't fix.
