### ISSUE TITLE
SEO optimizations

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#225]
Various optimization to improve indexing

- [ ] render the target description field in the <meta description tag.
- [ ] generate a sitemap.xml from the target menu options.

**Comment by mmoskal** [comment]
As for `<meta description>`, you can use:
```
### @description The description goes here.
```
Otherwise, we take the first paragraph of the content. There is currently a bug that disallows new lines there. Will fix.

I don't think using the same description on all pages will do us any good for search engines.

**Comment by mmoskal** [comment]
Sitemaps are now implemented, and the description bug is fixed.
