### ISSUE TITLE
The reference of block "setAll" lack of "See Also"

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2253]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/ ](url)
- Click "_?_" and choose "_Reference_"
- Choose "_light_" in "_See also_"
- Then click "_setAll_"

**Expected Result:**
![seealso](https://user-images.githubusercontent.com/17866936/26962910-09041efa-4d1c-11e7-8a7c-80baa5603d1c.PNG)

**Actual Result:**
[additional information: click "_rgb_" and it have the same issue ]
![seealso1](https://user-images.githubusercontent.com/17866936/26962927-2734019c-4d1c-11e7-80c2-7b9e1464d337.PNG)

**Comment by ganicke** [comment]
https://github.com/Microsoft/pxt-common-packages/pull/99
