### ISSUE TITLE
The reference of Block “graph” can’t be opened.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2254]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/](url)
- Click “_?_” and choose “_Reference_”
- Choose “_light_” in “_See also_”
- Then click "_graph_"

**Expected result:**
It should be open and work normally.

**Actual result:**
![referenced1](https://user-images.githubusercontent.com/17866936/26963325-91858096-4d1e-11e7-8a57-3c43e52b4faf.gif)

**Comment by ganicke** [comment]
https://github.com/Microsoft/pxt-common-packages/pull/99
