### ISSUE TITLE
when click on other places or blocks, the setting of the block can’t be closed automatically.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2255]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/](url)  
- Drag “_if-then-else_” in “_forever_”
- Click “_setting_” on the left bottom of “_if-then-else_” 
- Then click on other places or blocks

**Expected Result:**
The setting of block should be closed automatically when click on other places or blocks.

**Actual Result:**
[_Additional information_: click on other places or blocks, it can't be closed, but it will close when click the "setting" in the upper-left corner of the block.]
![settting](https://user-images.githubusercontent.com/17866936/26963548-b2b10690-4d1f-11e7-8588-d412ad4adfc2.gif)

**Comment by microsoftsam** [comment]
Blockly functionality, we can consider fixing that in the future. won't fix for now.
