### ISSUE TITLE
Under JAVASCRIPT, it shows error and prompts "Cannot find name 'forever'" after chose the code of block “forever” from "LOOPS".

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2256]
**Repro step:**
- Navigate to  [https://makecode.adafruit.com/](url)
- Switch to “_JAVASCRIPT_”
- Click “_LOOPS_” and choose “_forever_”

**Expected Result:**
it should display “_loops. forever(()=>{})”_ on content panel.
![forever1](https://user-images.githubusercontent.com/17866936/26964130-bf097758-4d22-11e7-94ce-ba5c436e14e7.PNG)

**Actual Result:**
It displays “_forever(()=>{})”_ on content panel and prompt “_Cannot find name ‘forever’_“.
![forever](https://user-images.githubusercontent.com/17866936/26964096-986d3418-4d22-11e7-9a47-4523d33bdf92.PNG)

**Comment by microsoftsam** [comment]
Monaco toolbox bug, the Loops category is a special, and it's output text isn't including the namespace. @riknoll mind looking into this?
