### ISSUE TITLE
isRef: is not a function

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2262]
microbit.org-ticket: 1981

This program repro case:
```
basic.forever(() => {

})
music.beginMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
```

Get this screen after a few seconds

![screen shot 2017-06-09 at 22 38 39](https://user-images.githubusercontent.com/25079586/26995417-6cd2bdae-4d64-11e7-8c8e-9e6aff4c99c5.png)

A Blocks / JavaScript code editor for the micro:bit.

pxt.microbit.org version: 0.12.23

Microsoft MakeCode version: 0.12.81

C++ runtime version: v2.0.0-rc11

**Comment by tballmsft** [comment]
Also manifests with
```
music.beginMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
```

**Comment by tballmsft** [comment]
Looks like this is the bug:
```
                currentMelody = null;
                control.raiseEvent(MICROBIT_MELODY_ID, currentMelody.background ? MusicEvent.BackgroundMelodyEnded : MusicEvent.MelodyEnded);
```

**Comment by tballmsft** [comment]
Fixed: https://github.com/Microsoft/pxt-microbit/commit/07380d7c0726abe211f4f2af312a5981d2f55d8b
