### ISSUE TITLE
Project can't be loaded successfully on Edge

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2264]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ on Edge
• Click PROJECT -> MAKE ->Magic Wand

**Expected Result:**
The project could be loaded successfully
**Actual Result:**
The project can't be loaded successfully
![5](https://user-images.githubusercontent.com/23466737/27020947-9f390dba-4f77-11e7-8932-145dfb63acb4.gif)

**Comment by abchatra** [comment]
I can't repro this.

**Comment by Helen09** [comment]
Yes, it not repro for me too.
