### ISSUE TITLE
incorrect monaco toolbox fragment (onDataPacketReceived)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#2266]
selecting  radio.onDataPacketReceived((packet: Packet) results in the incorrect code.
```
radio.onDataPacketReceived((packet: Packet) => { })
```
but it should be
```
radio.onDataPacketReceived((packet: radio.Packet) => { })
```

**Comment by abchatra** [comment]
Moved to microbit https://github.com/Microsoft/pxt-microbit/issues/908
