### ISSUE TITLE
Lack of block "show ring" on Getting Started step1

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2273]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ on Safari
• Click "Getting Started"

**Expected Result:**
There should show block "show ring"
**Actual Result:**
The step1 refers block "show ring", but there is no this block
![jun-13-2017 11-18-45](https://user-images.githubusercontent.com/23466737/27064594-bb87af90-502a-11e7-8958-bb7702bc576a.gif)

**Comment by abchatra** [comment]
@microsoftsam Repro on Safari?

**Comment by Helen09** [comment]
Close as fixed
