### ISSUE TITLE
After change "red" to others on "light.showRing()", it can't be converted back to the responding block.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2274]
**Repro step:**
- Navigate to [https://makecode.adafruit.com/](url)
- Drag “_show ring_” on “_On buttons A+B_” and then switch to "_JAVASCRIPT_"
- Change " _light.showRing('red red red red red red red red red red')_ " to " _light.showRing('red red yellow red red blue red red green red')_"
- Then switch to "BLOCKS"

**Expected result:**
Convert code from block "_show ring_". After changed the color of the code, it should be converted back  to the responding blocks.

**Actual result:**
![show-ring](https://user-images.githubusercontent.com/17866936/27067355-2f162484-503d-11e7-8f70-a5961dec6f9a.png)

**Comment by riknoll** [comment]
Whoops, I knew I forgot to put the decompileLiterals flag on something....
