### ISSUE TITLE
On TemperatureCondition.hot, reduce temperature, event is triggered

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2276]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ 
• Drag block as below .gif and click "Slow-Mo"
• Drag down the temperature 

**Expected Result:**
On TemperatureCondition.hot, reduce temperature, event should not be triggered
**Actual Result:**
On TemperatureCondition.hot, reduce temperature, event is triggered. But drag down again it will not be triggered
![jun-13-2017 14-35-19](https://user-images.githubusercontent.com/23466737/27069631-45a42948-5048-11e7-97c9-b1ebb9b606fb.gif)

**Comment by riknoll** [comment]
This is a bug in the pxt-adafruit repo
