### ISSUE TITLE
Importing Touch Develop .hex file does not produce expected results on compliation

### ISSUE THREAD

**Issue by DaveAtKitronik** [Microsoft/pxt#2277]
A working Touch Develop script for a line following buggy imports into PTX ok. (attached as original.hex in zip, also available from: https://www.microbit.co.uk/app/#list:installed-scripts:script:a675de82-204a-4076-0ad4-8731b56b483f:overview:id=lapexp)
The generated JavaScript code looks plausible. 
Exporting this back out from the javaScript tab give a .hex file that replicates the original functionality. (attached as PXT_JavaScript_Import.hex in zip)
However once the view has been switched to Blocks the exported hex, from either the Blocks or JavaScript views no longer works as expected. (attached as PXT_Block_Export.hex in zip)
I initially suspected that the initial import/export of the hex had not re compiled the hex. To test this I added a change to the LED displays to verify that the hex had been recompiled. (PXT_JavaScript_Modified in zip file). This .hex performs as expected, with the buggy following the line, and the additional LEDs lit. 
I also noticed that the simulator initially flashes P12 and P16 rapidly, but after the switch to the blocks view it flashes them much slower. This is consistent with the symptoms seen on the actual buggy.
[PXT_TD_Import_hexes.zip](https://github.com/Microsoft/pxt/files/1070591/PXT_TD_Import_hexes.zip)

**Comment by pelikhan** [comment]
@riknoll showString(..., 0) becomes showString(...) after round trip.

**Comment by riknoll** [comment]
I believe that bug is fixed in master

**Comment by pelikhan** [comment]
Needs to be cherry-picked in v0

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
@riknoll can you cherry pick to v0?

**Comment by riknoll** [comment]
Yep
