### ISSUE TITLE
Other block is selected when click "Slow-Mo"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2278]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Drag block as below .gif and click "Slow-Mo"

**Expected Result:**
Block "on shake" shouldn't be selected
**Actual Result:**
Block "on shake" is selected
![jun-13-2017 15-46-02](https://user-images.githubusercontent.com/23466737/27071494-d547f30c-504f-11e7-8208-8db8b37a84f1.gif)

**Comment by tballmsft** [comment]
You appeared to shake the board, c

**Comment by riknoll** [comment]
This is the intended behavior.
