### ISSUE TITLE
After opened the project of “Metronome”, there is no responses.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2279]
**Repro step:**
- Navigate to https://makecode.adafruit.com/
- Click “_PROJECT_” then choose “_EXAMPLES_”
- Open project “_Metronome_”

**Expected result:**
It should be opened like other projects such as "_Blinky_"
![metro](https://user-images.githubusercontent.com/17866936/27071771-c7a951e0-5050-11e7-8897-28695d8a5289.gif)

**Actual result:**
**IE**: Keep loading
**Edge, Chrome & Firefox**: The page doesn't have any change. No reloading.

**Comment by abchatra** [comment]
Fixed
