### ISSUE TITLE
game.addScore requires pause to showNumber 

### ISSUE THREAD

**Issue by abalone23** [Microsoft/pxt#2280]
The following code will not display number:
input.onButtonPressed(Button.A, () => {
    game.addScore(1)
    //basic.pause(1)
    basic.showNumber(game.score())
})

The following code will display number:
input.onButtonPressed(Button.A, () => {
    game.addScore(1)
    basic.pause(1)
    basic.showNumber(game.score())
})

It should not be necessary to have a pause for showNumber to display.

**Comment by abchatra** [comment]
@pelikhan Is this by design? Looks like addScore is done in a fiber in the background and showNumber output gets lost if there is no pause

**Comment by pelikhan** [comment]
Yes it is by design. It should be non-blocking as it may be called without a game loop.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
By Design
