### ISSUE TITLE
Guide for creating new targets is ambiguous

### ISSUE THREAD

**Issue by adamthegameguy** [Microsoft/pxt#2281]
[This guide](https://makecode.com/target-creation) is ambiguous and doesn't provide good information for developers to create their own targets.

Things that are missing/broken:

- [x] an outline of available properties for pxtarget.json
- [ ] outline of how a pxt.json file is structured and how it functions
- [ ] a guide for adding and removing api's in their own directories in ```/libs```
- [ ] docs for creating a simulator?
- [ ] docs about project (templates)
- [ ] docs about upgrading
- [x] Instructions in the guide don't correspond to how [sample target sources](https://github.com/microsoft/pxt-sample) is structured (there's no ```libs/sample``` project)
- [x] [Static File Drops](https://makecode.com/staticpkg) page is missing

**Comment by tballmsft** [comment]
Some progress here: https://makecode.com/targets/pxtarget
