### ISSUE TITLE
New MakeCode URL causing issues for teachers in UK

### ISSUE THREAD

**Issue by PragmaticPhil** [Microsoft/pxt#2283]
REF: microbit.org-ticket: 2027

NB:  we have had reports from teachers in the UK that the new makecode url is being blocked.
We suspect firewalls need updating.

Please can you provide a full and updated list of what domains need to be unblocked for it to work.

**Comment by PragmaticPhil** [comment]
I have just been sent the blog:
https://makecode.com/blog/microbit/v0.12.35
This appears to have the answer I need.

I will keep this ticket open while I wait for confirmation that this has worked for the people affected.

NO ACTION atm - I will add another comment if further actions are required.
Thanks

**Comment by abchatra** [comment]
Feel free to reopen if you need anything for us to address

**Comment by PragmaticPhil** [comment]
Zach has corresponded directly with Jacqui on this.
The request we've made is to not auto-redirect from pxt. to makecode.  
The auto-redirect should be disabled until the end of school term.  We will still link to makecode. but we will have to put a link to the pxt. domain too.
This is high priority - there are teachers in the UK (and most likely elsewhere) who are abandoning lessons because they can't access the editor.
Thanks

**Comment by PragmaticPhil** [comment]
@abchatra - UI is not letting me reopen this ticket - please can you do so

**Comment by abchatra** [comment]
We are working on a alternative solution for blocked folks. Please hold on.

**Comment by abchatra** [comment]
Only known workaround is to add makecode.microbit.org to the list of domains to unlock.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/2297

**Comment by abchatra** [comment]
Update: We have couple of things setup and testing it works. 
- Redirect changes are on code review:
- Notification change is on code review:
Testing in progress, will at least take rest of the day.

**Comment by abchatra** [comment]
This is fixed.  Blog post updated with the information for the special old url

https://makecode.com/blog/microbit/v0.12.35
