### ISSUE TITLE
Apparent discrepancy between simulator and real world behaviour

### ISSUE THREAD

**Issue by PragmaticPhil** [Microsoft/pxt#2284]
microbit.org-ticket: 2028

Michael S investigated a query we had today, and his conclusions are below:

Works properly in browser/simulator. Fails after you shoot something actually on the device.
This is likely a subtle issue with a difference between the simulator and the device.

Seems worth bringing to your attention - the hex Michael referred to is:
https://makecode.microbit.org/_Wp6hiYfEkVr1

**Comment by abchatra** [comment]
I don't have access to the ticket. Can you add additional information? What is this program trying to do? Smaller repro is greatly appreciated.

**Comment by PragmaticPhil** [comment]
Its an internal ref (I formatted it incorrectly - have updated now)

App is a game - space invaders
... with two ships. 
... If you shoot to one ship it will change score by 1

Appreciate its a large repo - sorry - without having an idea about source of issue distilling down to essence of what is causing the discrepancy is tough.

**Comment by PragmaticPhil** [comment]
@abchatra - thanks - I will approach customer for more info, but please can you specify what info will be helpful?  Rem that customer on this one is a child so sophisticated reporting might be tricky.

**Comment by abchatra** [comment]
I would ask for a reduced repro. Like what API is not working? I tried by flashing the code to Micro:bit and it worked for a while until I shot one of the sprites.

**Comment by PragmaticPhil** [comment]
@abchatra sounds like you've replicated the issue.  Customer is a child so unlikely to be able to help (sorry)

**Comment by pelikhan** [comment]
Fix deployed to v0.13.23.
