### ISSUE TITLE
javascript doc colorizing not working online

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#2288]
It works from "pxt serve".

**Comment by tballmsft** [comment]
Documentation must look good!

**Comment by tballmsft** [comment]
@pelikhan - @riknoll debugged. The issue is that embed.js is not getting include for the PXT docs. It only gets include when target is defined, it appears.

**Comment by pelikhan** [comment]
We currently do not colorize typescript snippets in docs. We should do this on the client rather than the server. We should also add copy/edit buttons to match blocks.

**Comment by tballmsft** [comment]
Peli, it works in localhost just fine.

**Comment by pelikhan** [comment]
Not really: no simulator, no edit button. We can fix this right by rendering on the client always.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
What about this? https://makecode.adafruit.com/javascript/call

**Comment by tballmsft** [comment]
Peli, I am just looking for colorizing in the basic markdown, not the simulator:
https://makecode.com/targets/pxtarget

**Comment by tballmsft** [comment]
@pelikhan, see my comment above. Richard debugged this:

> @pelikhan - @riknoll debugged. The issue is that embed.js is not getting include for the PXT docs. It only gets include when target is defined, it appears.

**Comment by pelikhan** [comment]
Right, that pxt "target" is a bit special.
