### ISSUE TITLE
decompilation issue with for loops

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#229]
add a repeat 4 times block in blocks 
if converts to for (let i = 0; i < 4; i++) {

make any change to trigger the decompilation in javascript, switch back to blocks. 
decompilation issue. 

Reason being, the roundtrip converts the loop into: for (let i = 0; i <= 3; i++) {
which is different from i<4, hence can't convert.

**Comment by riknoll** [comment]
I think the only way to deal with this is to define something like `basic.repeat()`. Otherwise, we can't differentiate between what is supposed to be a "for" block and what is a "repeat" block.

**Comment by riknoll** [comment]
If we do away with the round trip check (which I believe is currently the plan). Then this issue should be resolved.

**Comment by pelikhan** [comment]
Richard, you can open an issue on getting rid of the roundtrip and get started on it?


-          [ ] build test suite of programs that successfully roundtrip

-          [ ] build test suite of programs that should not roundtrip

-          [ ] integrate test suite in build

-          [ ] integrate docs test suite in build

-          [ ] remove rountrip

**Comment by riknoll** [comment]
@pelikhan sure thing

**Comment by gingemonster** [comment]
will this fix the issue you get when you add a repeat block, switch to javascript and make a change and then back to blocks and it converts them into a for block like this:
![image](https://cloud.githubusercontent.com/assets/703352/21620541/ba86f4e6-d1ec-11e6-9a39-ef1f9bc047ae.png)

**Comment by microsoftsam** [comment]
Always decompile fixes this.
