### ISSUE TITLE
Render github package docs somewhere

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#230]
split out from #167 

The docs are already present in the `readme.md`
- [ ] detect that docs are requested for a github package, request the markdown content from github and render it

**Comment by pelikhan** [comment]
Unfortunately, the packages do not benefit from our snippet rendering, also it is not possible to document individual blocks.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by pelikhan** [comment]
One solution is to rely on GitHub pages. We could have a PXT command that generates a static web site with pre-rendered markdown files.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by tballmsft** [comment]
@peli - does the recent doc change handle this now?

**Comment by pelikhan** [comment]
Not yet for 3rd party packages.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
