### ISSUE TITLE
Block can't be deleted when dragging it to leftmost of delete area

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#2302]
Repro steps:
• Navigate to https://makecode.adafruit.com/
• Drag block to leftmost of delete area
• Release left mouse, move your mouse

Expect result: Block should be deleted
Actual result: Block is not deleted, and it can move without mouse selected.
![drag](https://user-images.githubusercontent.com/23447632/27215908-0462731c-52a6-11e7-92be-fcfb4b2c969c.gif)

**Comment by abchatra** [comment]
Won't fix, if the mouse moves beyond the toolbox then it is not considered as a delete action
