### ISSUE TITLE
Failed to load README.MD

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#2303]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ on Edge
• Click More…->Project Settings
• Expand EXPLORER
• Click README.MD

**Expect result**: README.MD detail should show up
**Actual result**: It keeps loading README.MD
![2](https://user-images.githubusercontent.com/23447632/27217118-21bb060e-52ab-11e7-8ef4-aff8846ea48e.PNG)

**Comment by abchatra** [comment]
Please don't' file issues Explorer, we don't fix issues in explorer unless it is crashing the site somehow.  Reason for this is, students don't click on it and we use it mostly for debugging.
