### ISSUE TITLE
There is no rule to name the variable, it allows to input any char 

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2304]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Click the "VARIABLES"
• Click the "make a Variable"
• input the variable name

**Expected result:**
1. the variable should be named by some rules
2. the variable could be deleted 

**Actual result:**
1. there is no rule to name the variable, it allows to input any char 
2. the variable could not be deleted except to reset the page

![variable](https://user-images.githubusercontent.com/11880996/27217953-a27e7908-52ae-11e7-8b48-93f3473a1e47.gif)

**Comment by abchatra** [comment]
Won't Fix from our end
