### ISSUE TITLE
The import file name was not display correctly in the editor box

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2306]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Click "PROJECTS" and select the function "import File..."
• Choose the file "reaction(1).uf2" to load

**Expected result:**
 the file name should be "reaction(1)" in the editor box which was used to input the name of saved file
 **Actual result:**
 the file name display in the editor box is "reaction"

![filename](https://user-images.githubusercontent.com/11880996/27219602-d9ebe2e4-52b4-11e7-8a63-9ce591dd40b4.gif)

**Comment by abchatra** [comment]
This is by design. File name has no relation to project name. Project name is the one given by the user while editing the file.
