### ISSUE TITLE
error numbers in inline messages?

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#231]
Should we put the error numbers somewhere in error messages? It may make it easier to refer to errors or to google them. They could be very greyed out.

@pelikhan @microsoftsam @tballmsft - thoughts?

**Comment by thomasjball** [comment]
Can we have the number link to the error page?

**Comment by pelikhan** [comment]
Interrestingly, VSCode does not show any error number neither links to a doc page.

![image](https://cloud.githubusercontent.com/assets/4175913/17709660/f01522de-639e-11e6-9641-461947e7cfbd.png)

**Comment by mmoskal** [comment]
I like the idea with the link. VS Code doesn't have help pages for errors I think because pros are supposed to understand them.

**Comment by pelikhan** [comment]
I don't think this brings value to learned. Clickable error message would be better.

**Comment by mmoskal** [comment]
I shall not fight for them ;)

**Comment by abchatra** [comment]
Closing as per Peli comments _don't think this brings value to learned_.
