### ISSUE TITLE
Program error: reset not implemented in simulator yet

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2314]
When I use game.gameOver() a A+B button target appears on the simulator. If I press this I get a ProgramError: Reset not implemented in simulator yet.

We have a number of users who have logged tickets asking how they could restart the game without pressing the reset button on the back of the simulator, mainly because they want to implement a high score table. So we don't want the micro:bit or the simulator actually resetting, what we want is a way to return from the game.gameOver() function call, so that high score functionality and game re-run functionality could be implemented.

For an example of this, please see this game that I wrote in TouchDevelop that implements a high score - I would want to be able to do the same thing using the game library please: https://www.microbit.co.uk/nmnbiw (Challenge 3 add high score) - see how when the main game finishes it comes back to some code that will run, which in this case would compare the players current score to the stored high score, if it is higher, it would increase the high score variable, then display HI SCORE and the new value.

It's currently not possible to do this with the game library, because game.gameOver() never returns.

**Comment by DavidWhaleMEF** [comment]
This is the TouchDevelop script with the high-score challenge completed:

https://www.microbit.co.uk/xolqgf

**Comment by abchatra** [comment]
Good feature request
