### ISSUE TITLE
edits to custom.ts not reflected in toolbox

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#2317]
If you edit custom.ts and change the signature of functions then switch back to monaco toolbox, the old bindings are still there. Need to rerun the shim compiler upon user edits.

**Comment by riknoll** [comment]
You also get some weird cases where the block definitions change and the old blocks mutate into garbage in the workspace. I don't know how deep we want to go into supporting this scenario but it could certainly use some work.

**Comment by samelhusseini** [comment]
We need to keep refreshing the toolbox whenever the custom.ts file changes. Reason being you could have made a block change, so we must scan that file for any block definition changes.
