### ISSUE TITLE
Page can't load successfully on Edge

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2319]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ on Edge

**Expected result:**
 This site can load successfully
**Actual result:**
 This site can't load successfully
![1](https://user-images.githubusercontent.com/23466737/27273534-0ac973be-5502-11e7-8023-c17f496fadf4.gif)

**Comment by abchatra** [comment]
Can't repro. What version of edge?

**Comment by Helen09** [comment]
Close as not repro
