### ISSUE TITLE
codethemicrobit broken on IE

### ISSUE THREAD

**Issue by thomasjball** [Microsoft/pxt#232]
Blocks not loading. Screen blank. Badness. Message:

	Cannot load package: version not specified for *

Console output:

Cannot load package: version not specified for *
SCRIPT5007: Unable to get property 'dependencies' of undefined or null reference
main.js (5457,28)

![image](https://cloud.githubusercontent.com/assets/7671657/17709008/348159c2-639c-11e6-801b-d379e3114bb8.png)

**Comment by pelikhan** [comment]
OS and browser version please.

**Comment by pelikhan** [comment]
Unable to repro on IE11, Edge.
