### ISSUE TITLE
Cannot re-add the "on start" block as of v1.6.3

### ISSUE THREAD

**Issue by adamthegameguy** [Microsoft/pxt#2323]
If a user deletes the "on start" block from their project they can't add it back. The "on start" block is missing from the loops menu as of v1.6.3. If you checkout at tag v1.6.2 the "on start" block is there. Users should be able to add the "on start" block back OR not be able to delete the "on start" block.

*Repro:*
1. delete the on start block from the workspace
2. open the loops menu

*Expected:*
An "on start" block 

*Actual behaviour:*
"on start" block is missing from the menu, causing editing in block mode to be broken

*Workaround:*
Add some valid code in JavaScript mode and the "on start" block will be regenerated in the workspace

**Comment by tballmsft** [comment]
Reverted change that broke on-start. @riknoll - my bad - no need to investigate further.
