### ISSUE TITLE
Recycle bin - fixed position on iPhone

### ISSUE THREAD

**Issue by PragmaticPhil** [Microsoft/pxt#2328]
microbit.org-ticket: 1251

One of the customers who reported an issue that led to 
https://github.com/Microsoft/pxt/issues/1828
Has got back in contact to confirm the fix in that ticket worked.  Thanks :)

He's now reported the following:

The rubbish bin (trash can) icon that shows up in place of the same block categories list when you drag blocks back to it (to delete them) had a position that is fixed in the block category list, as opposed to the screen position (or alternatively, does not take the list scroll/start relative position into account), meaning when using blocks from categories further down the newly scrolled list, the rubbish bin cannot be seen as it's off the top of the screen. 

This has no effect on the delete behaviour, it's purely cosmetic, but still incorrect behaviour. I would suggest the bin icon should always appear on the same fixed location relative to the top and bottom of the VISIBLE part of the block categories list.

**Comment by microsoftsam** [comment]
Please check makecode.microbit.org/beta to very the issue has been fixed. 
This will make it out to the public on the next release.
