### ISSUE TITLE
Support contact in packages

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2329]
As the number of packages and their complexity increases, it would be great to be able to have package owners support their users directly.

I think there are a few options for making this possible, but I propose the following as a starting point
1) All packages must have a support-url in them, this can be standard link, for example to GitHub issue tracker, or a `mailto:` link. If there is no link, we assume the GitHub issue tracker for the project
2) When a package is added, the 'help' menu changes as follows
 * the 'Support' option becomes "micro:bit support"
 * MakeCode injects an item for the package support
![image](https://user-images.githubusercontent.com/147113/27382276-1e0ae228-567e-11e7-817c-c15a2f856012.png)

**Comment by abchatra** [comment]
Note supporting arbitrary URL is a security risk.

**Comment by carlosperate** [comment]
It could be added to the menu only if package is in the whitelist, which should reduce the risk.
And it's not all that different than having links in the README file, which the users would also trust as it's delivered from the microbit.org domain.

**Comment by tballmsft** [comment]
Packages allow a list of authors.
