### ISSUE TITLE
Download Screenshot not working for large projects in Chrome

### ISSUE THREAD

**Issue by PragmaticPhil** [Microsoft/pxt#2330]
microbit.org: ticket: 1971

Report from customer:
Seems for large projects Download Screenshot doesn't work in Google Chrome but works in Microsoft Edge.
I'm referring to the "Download Screeshot" option in the code editor

Customer has confirmed that this issue was present before last week's update and is still present on new editor.  
Attached is the hex that he was using when he encountered this issue as well as screen grab.
Note that he is in the Dutch version of the site.

[microbit-BalOverHordeMoeilijk.zip](https://github.com/Microsoft/pxt/files/1091732/microbit-BalOverHordeMoeilijk.zip)

**Comment by DavidWhaleMEF** [comment]
Any analysis of this issue yet? Thanks!

**Comment by pelikhan** [comment]
We must be hitting some URI size limitations that are vendor specific. We'll be a bit more careful about boosting pixel density but eventually it'll fail for large programs.

**Comment by pelikhan** [comment]
This issue is fixed. We turn off oversampling for large projects, it will eventually fail again for massive projects.
