### ISSUE TITLE
Fix french translation

### ISSUE THREAD

**Issue by gquintana** [Microsoft/pxt#2331]
* Basic
  * "Show icon": "Montrer l'icône"
  * "Show arrow": "Montrer la flèche"
* Input
  * "On button ... pressed" : "Lorsque le *bouton* ... est pressé"
  * "On pin ... pressed": "Lorsque la broche ... est pressée
  * "button ... is pressed": "le *bouton* ... est pressé"
  * "calibrate compass": "Calibrer la boussole"
  * LED
    * "led enable ...": "allumer LED ..."
  * Radio
    * "radio send number ...": "envoyer le nombre ... par radio"
    * "radio send value ...": "envoyer la valeur ... par radio"
    * "radio send string ...": "envoyer le texte ... par radio"
    * "on radio received ..receivednumber..": "lorsque on reçoit ..nombreRecu.. par radio"
    * "on radio received ..name..value..": "lorsque on reçoit ..nom..valeur.. par radio"
    * "on radio received ..receivedString..": "lorsque on reçoit ..texte.. par radio"
    * "radio set group ...": "affecter le groupe radio ..."
  * Loop
    * "while ..true.. do": "tant que ..vrai.. faire"
    * " for element ..value.. of ..list.. do": "pour tous les élements ..valeur.. de ..liste.. faire"
  * Variables
    * "item": "variable"
    * "change ..item.. by ..1..": "changer ..variable.. *de* ..1.."
  * Pins
    * "analog read pin ..P0..": "lire en analogique la broche ..P0.."
    * "analog write pin ..P0.. to ..1023..": "écrire en analogique la broche ..P0.. à ..1023.."

**Comment by pelikhan** [comment]
Did you register an account with Crowdin?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gquintana** [comment]
Each time we submit a translation with Crowdin it gets overwritten after a while, and the translation never lasts

**Comment by pelikhan** [comment]
Can you give me an example? Translations are pulled out of crowdin.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by titimoby** [comment]
Gérald is on the same non profit organization as I am.
He knows that sometimes translations on PXT were crashed in the past by God knows who.
If it is stabilized and no external company is going to translate back once more, we can have a new try at crowdin

**Comment by pelikhan** [comment]
There is probably a history of the translations. If you can point me to one, i can take a peek. Remember that submitted a translation does not mean it gets validated unless you are a proof reader.

**Comment by titimoby** [comment]
Let's have a try and we'll see.

**Comment by titimoby** [comment]
Gérald is on the same non profit organization as I am.
He knows that sometimes translations on PXT were crashed in the past by God knows who.
If it is stabilized and no external company is going to translate back once more, we can have a new try at crowdin
