### ISSUE TITLE
Cancel button sometimes doesn't work in New Variable dialog

### ISSUE THREAD

**Issue by bviglietta** [Microsoft/pxt#2332]
In the online code editor at makecode.adafruit.com:

1. Click Make a Variable and create a new variable called foo.
2. Click Make a Variable and try to create a second variable called foo. This will fail, correctly, with the error, "A variable named 'foo' already exists."
3. Try to dismiss the New Variable dialog by pressing the Cancel button or by clicking outside the dialog box. This will again produce the error, "A variable named 'foo' already exists." The only way to dismiss the dialog box now is, bizarrely, by clicking OK.

**Comment by abchatra** [comment]
Thanks @bviglietta for filing the bug.
