### ISSUE TITLE
custom block crashes the categories

### ISSUE THREAD

**Issue by myjeeed** [Microsoft/pxt#2338]
The categories in pxt-adafruit (or makecode.adafruit.com) crash when I try to create a new custom block using the add button in the custom.ts with the following code:

```
namespace gesture {

    //% block
    function asdf() {

    }

}
```

**Comment by pelikhan** [comment]
Try adding export on that function declaration.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by myjeeed** [comment]
Yep, it worked.
Thanks
