### ISSUE TITLE
custom.ts bug with statement handlers

### ISSUE THREAD

**Issue by myjeeed** [Microsoft/pxt#2339]
in makecode.adafruit.com the block that is created from this code:
```

/**
 * Gesture blocks
 */
//% weight=100 color=#d3a226 icon=""
namespace custom {
    let is_initialized: boolean = false;
    let MY_EVENT_SRC: number = 8137;

    //% block
    export function onGestureRecognized(a: () => {}) {

        if (!is_initialized) initialize_predictor();
        control.onEvent(MY_EVENT_SRC, 1, a);
    }

    function initialize_predictor() {
        is_initialized = true;

        control.runInBackground(() => {
            if (input.acceleration(Dimension.Strength) > 500) {
                control.raiseEvent(MY_EVENT_SRC, 1);
            }

            loops.pause(33);    //almost 30fps
        });
    }
}
```

looks like this:
![image](https://user-images.githubusercontent.com/9346800/27455319-c3f825aa-5751-11e7-9bd1-d0fb2c8e1fdb.png)

which should probably look like one of the event blocks, similar to this:
![image](https://user-images.githubusercontent.com/9346800/27455352-d8ab8280-5751-11e7-8a54-a9c95ea11b16.png)

**Comment by pelikhan** [comment]
Use () => void

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by myjeeed** [comment]
it will look like this using `a: () => void`:
![image](https://user-images.githubusercontent.com/9346800/27460990-6b3fb642-576c-11e7-80b3-c2945b1852cc.png)

**Comment by riknoll** [comment]
Found a workaround. Change your comment attributes to something like this:
```typescript
//% blockId=something_descriptive block="on gesture recognized" 
```

The bug is with the "block" comment attribute.

**Comment by abchatra** [comment]
Workaround exists
