### ISSUE TITLE
Defining block icons

### ISSUE THREAD

**Issue by carlosperate** [Microsoft/pxt#2347]
From the "Defining blocks" documentation in https://makecode.com/defining-blocks:

> ```
>/**
> * Provides access to basic micro:bit functionality.
> */
>//% color=190 weight=100 icon="\uf1ec" block="Basic Blocks"
>namespace basic {
>```
>
>icon icon character from the icon font to display. You can browse the full list of icons at https://semantic-ui.com/elements/icon.html

But in the link provided all we get are the class names for the icons, how do we go from `<i class="calculator icon"></i>` to `\uf1ec`.

Also, what is `\uf1ec`? A unicode character?

**Comment by pelikhan** [comment]
Yes that is the Unicode character in the font awesome font.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by carlosperate** [comment]
There doesn't seem to be a way to look up the unicode character from the given link. Should we also link to the original font awesome website, which does contain that information? http://fontawesome.io/icons/

**Comment by tballmsft** [comment]
feel free to send us a PR, @carlosperate

**Comment by pelikhan** [comment]
Right we just use the debugger but if you have a user friendlier way, we'll take it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by carlosperate** [comment]
PR submited: https://github.com/Microsoft/pxt/pull/2348
