### ISSUE TITLE
Invalid type inference with arrays

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#2349]
Try this program. The inference engine tries to force players to be a string, it should be a number[].

https://makecode.microbit.org/_1TKKu575rbJd

**Comment by tballmsft** [comment]
another reason to use TypeScript type inference rather than rolling our own.

**Comment by riknoll** [comment]
Duplicate of https://github.com/Microsoft/pxt/issues/2349

**Comment by riknoll** [comment]
@tballmsft the issue is that we can't generate typescript without first doing the type inference. We need to declare types for the variables in the generated code.
