### ISSUE TITLE
PXT goes to the Javascript view on load before switching to blocks

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#235]
This experience looks clunky. We should just go to the blocks view, do the round trip, and if we find errors in that, switch to the Javascript view as a result of that.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/commit/5d9f85828d31942a54995d86c0506f42bfe5c696

**Comment by pelikhan** [comment]
On a first load in a browser, it should have some blocks in it.

**Comment by microsoftsam** [comment]
On first load, we decompile the JS, if it's all good, then we stay in blocks, otherwise we switch to JS: 
Commit: f7682e83cb2c53e88c09543eedff011ca0940567

**Comment by pelikhan** [comment]
Is the monaco worker spinned up at that point?
