### ISSUE TITLE
Content pane's background changes to black when click on Edge

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2366]
**Repro steps:**
• Navigate to https://makecode.microbit.org/ on Edge
• Drag blocks as below picture 
• Click few times on content pane until the background become white
• Click any block

**Expected result:**
 The content pane's background shouldn't change
**Actual result:**
 The content pane's background change to black
![2](https://user-images.githubusercontent.com/23466737/27624360-fc9757a8-5c12-11e7-8831-e9e125882c9c.gif)

**Comment by abchatra** [comment]
What is the version of Edge. I can't repro this.
