### ISSUE TITLE
Useless variable can't be deleted unless refresh the page

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2367]
**Repro steps:**
• Navigate to https://makecode.microbit.org/ 
• Drag blocks as below picture
• Create a new variable named "test" and try to delete it

**Expected result:**
 Variable "test" could be deleted
**Actual result:**
 Variable "test" can't be deleted unless refresh the page
![1](https://user-images.githubusercontent.com/23466737/27624854-0c88382e-5c15-11e7-9559-67512d4ca142.gif)

**Comment by abchatra** [comment]
Won't fix. This is by design in blockly.
