### ISSUE TITLE
[UI] Weird location of the slow mode button in portrait mode

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt#2376]
Not sure if it is wanted or not. Is it normal that in portait mode, the "slow-mo" button is on the right?

![capture](https://user-images.githubusercontent.com/3747805/27694810-0fff3ede-5ca2-11e7-87b8-e4573886edb5.PNG)

Reproduce:
1. Go to https://makecode.microbit.org/
2. Set the web browser's window in portait.

**Comment by riknoll** [comment]
We did this intentionally but it is confusing. There just isn't any room over by the simulator; might be worth revisiting.

**Comment by veler** [comment]
I see. As a new user of MakeCode, it looks confusing, I agree. If a consumer consider it as a bug it could give him a bad opinion of the product. Is not possible to make the footer a bit taller and having a small white space at the bottom of the microbit board?

**Comment by riknoll** [comment]
Making the footer taller might be problematic on mobile. I guess they can always just collapse it but it already takes up a lot of real estate.

**Comment by abchatra** [comment]
This is intentional. We will revisit this later if we hear back from more users. Closing this for now.
