### ISSUE TITLE
per-browser "download" instructions

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#238]
When user hits download and see download screen, add per-browser pictures of the "SAVE" bar.

* [ ] IE 11
* [ ] Edge
* [ ] Firefox
* [ ] Safari
* [ ] Chrome

* [x] fix doc page https://codethemicrobit.com/device/usb

**Comment by thomasdenney** [comment]
The screenshots on this page are also of microbit.co.uk opposed to codethemicrobit.com

**Comment by thomasdenney** [comment]
https://github.com/Microsoft/pxt-microbit/pull/239 fixes the documentation page.
