### ISSUE TITLE
TS enum lost when converted to blocks

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#2380]
microbit.org-ticket: 2160

When converting the following code into blocks, it finishes the conversion without any indication of errors, but it edits the user code and removes the righ-hand-side of the asignment:

I understand it might be a design decisions to not expose these enums as blocks, but the conversion should at least display a "grey block" rather than remove that portion of the code.

**From:**
```js
let foo = 0
foo = DigitalPin.P14
```

**Expected:**
```js
let foo = 0
foo = DigitalPin.P14
```
![image](https://user-images.githubusercontent.com/29712657/27744750-aeb2884e-5db8-11e7-9914-6065ac646331.png)

**Result:**
```js
let foo = 0
foo = 0
```
![image](https://user-images.githubusercontent.com/29712657/27744713-7eb06ba2-5db8-11e7-8a99-6e64f2e155fd.png)

**Comment by riknoll** [comment]
This is fixed in master, I'll cherry-pick it over to Microbit

**Comment by microbit-carlos** [comment]
Thanks for the quick response @riknoll, if this still needs to be cherry picked for the microbit, could we keep the issue open until it is done?

**Comment by microbit-carlos** [comment]
Thanks @riknoll !
