### ISSUE TITLE
Translate Arrow Names in micro:bit target

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#2384]
Arrow names (North, NorthEast etc) cannot be translated.

**Comment by abchatra** [comment]
Update from #2502 

--------------
Some strings in "libs/core" are not in "core-strings.json" and also not on Crowdin.
game.ts: all strings
icons.ts: some strings; ex. "arrow image"
images.cpp: some strings; ex. "scroll image"

**Comment by abchatra** [comment]
This is fixed
