### ISSUE TITLE
There is no sound on Edge and IE

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2389]
**Repro steps:**
• Navigate to https://makecode.microbit.org/
• Use a 'while' block with a nested 'repeat' block like this:
![sound](https://user-images.githubusercontent.com/23497626/27822535-7fc747b8-60d8-11e7-9e19-4b5c1957cf4f.PNG)
https://makecode.microbit.org/_4MY9bh9ju1za

**Expected result:**
 The alarm should to sound
**Actual result:**
 There is no sound 

**Notes:** 
not repro on Chrome and firefox

**Comment by microsoftsam** [comment]
Also, why aren't the icons in that screenshot white?

**Comment by abchatra** [comment]
I can't repro this.

**Comment by yanlxu** [comment]
not repro on Edge(RS_ONECORE_WEBPLAT_STAGE_DEV3\16236.1003.170707-1700) , but still repro on IE

**Comment by riknoll** [comment]
Sound on IE isn't supported and I don't think we have plans to add it.
