### ISSUE TITLE
Can't rename the variable name in 'for' block

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2390]
**Repro step:**
- Navigate to [https://makecode.microbit.org](url) on safari
- Click "_Loop_" and choose "_for_" block
- Drag "_for_" block and put it under "_on start_"
- choose "_index_" in "_for_" block, then rename the "index", such as "_xindex, yindex..._"

**Expected result:**
The "_index_" in "_for_" block should be renamed successfully.

**Actual result:**
Can't renamed "_index_" successfully and it is recognized as "_index_" automatically.

![jul-04-2017 17-10-05](https://user-images.githubusercontent.com/17866936/27823695-9f50376c-60dc-11e7-9e89-a2f5ff7ade89.gif)

**Comment by microsoftsam** [comment]
If you look closely, what's happening here is the autocorrect in Safari is changing it back to "index" before you hit enter, hence why it's not renaming. 

Try to click (x) on the auto correct, then hit enter.

**Comment by microsoftsam** [comment]
Alternately, if you want to be sure, try renaming it to something completely different like "myvar"

**Comment by Emma-sunny** [comment]
Closed as Safari's autocorrection
