### ISSUE TITLE
"Pink" and "white" show same color on simulator

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2395]
**Repro step:**
• Navigate to https://makecode.adafruit.com/
• Drag two blcoks as below picture and choose "pink" and "white"

**Expected result:**
 "Pink" and "white" should be different colors show on simulator
**Actual result:**
![pic1](https://user-images.githubusercontent.com/23466737/27857618-fa02bcac-61a4-11e7-93b4-b5f9d813df8d.png)

**Comment by microsoftsam** [comment]
Note quite the same color, but I see the issue. They are very close.
