### ISSUE TITLE
There is no difference when use block "show" or not

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2396]
**Repro step:**
• Navigate to https://makecode.adafruit.com/
• Drag two blcoks as below picture and drag block "show"

**Expected result:**
 There should have some difference when use block "show" or not
**Actual result:**
There is no difference when use block "show" or not
![1](https://user-images.githubusercontent.com/23466737/27857903-f44cb668-61a5-11e7-8ccc-e18b238d9007.gif)

**Comment by riknoll** [comment]
We should probably remove the show block. I don't think it does anything anymore.

**Comment by abchatra** [comment]
These blocks don't need show block anymore. This is not a bug.
