### ISSUE TITLE
inline error description for first error only

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#240]
In most cases, the first error reported in a program is worth investigating, the other are a unfortunate side effect. We should only inline the error description of the 1st error to avoid overloading the screen with purple boxes.

![image](https://cloud.githubusercontent.com/assets/4175913/17774810/437b529c-650a-11e6-9036-8f166b111bda.png)

**Comment by microsoftsam** [comment]
Fixed in Commit:
