### ISSUE TITLE
There is no sound on Edge&IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2404]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/ on Edge & IE
• Drag block "play tone..." and put it under forever
• Click the key as below picture

**Expected result:**
 The block should have sound
**Actual result:**
 There is no sound
![pic1](https://user-images.githubusercontent.com/23466737/27903913-921f65d0-626d-11e7-8655-bdc8cb16a522.png)

**Comment by riknoll** [comment]
This isn't a bug. IE Doesn't support AudioContextManager so we can't produce tones.

**Comment by Helen09** [comment]
So how about Edge?
