### ISSUE TITLE
Holding emulator button in iOS

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#2405]
microbit.org-ticket: 2191

When a program like the one below is used on a desktop browser, the user can press and hold the button and the "tick" image will be shown in the LED display for as long as the button is pressed. However, in iOS the "tick" image is never displayed. 
Just as additional info, the `on button [a] pressed` block works as expected.

![microbit-screenshot](https://user-images.githubusercontent.com/29712657/27907419-7c67fb5e-623f-11e7-8a61-2f74ddd002ad.png)

**Comment by microbit-carlos** [comment]
Is there any ETA on this one?

**Comment by pelikhan** [comment]
@microbit-carlos  Would it be more efficient in the simulator and microbit to have the "button WAS pressed" variant?

**Comment by microbit-carlos** [comment]
@pelikhan are we talking about adding a new block? That might be useful, but this long press would still be a problem on touch screen devices, no?

**Comment by pelikhan** [comment]
There is a hold event triggered by the hardware so having a hold gesture to lock in the button would introduce another discrepancy.

**Comment by microbit-carlos** [comment]
Could the browser long press event on touch devices be capture to simply maintain the button pressed as happens on desktop?

**Comment by microbit-mark** [comment]
Just nudging this one. Is there an update @microsoftsam?

**Comment by microsoftsam** [comment]
A couple of issues going on here:
- IOS shows the a touch callout by default when you press and hold. 
- We are registering on mousedown and on touch devices that's triggered way too late in the chain: 
```
touchstart
touchmove
touchend
mouseover
mousemove
mousedown
mouseup
click
```

Will prepare fixes

**Comment by microsoftsam** [comment]
Fixed in beta.
