### ISSUE TITLE
Feature request: Enable a way to hold down a button without locking the mouse click

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#2408]
microbit.org-ticket: 1976

This is a feature request to allow simulation of a button pressed down without having to maintain the mouse clicked on the button. Freeing up the mouse while maintaining the button pressed would allow interaction with other input features of the micro:bit (momentarily pressing the other button, changing tilt, changing orientation, etc).

As an example, the following if statement cannot be triggered in the emulator:

![microbit-screenshot](https://user-images.githubusercontent.com/29712657/27932684-96dc6e0a-6296-11e7-9b17-e0c6fa2cc09d.png)

**Comment by tballmsft** [comment]
By design, the simulator only supports a subset of functionality available on the hardware.  I don't see a natural way to support simultaneous inputs to the simulator.

**Comment by microbit-carlos** [comment]
Perhaps on long press there could be a small "pop-up" in the DOM (like a tick box?) to maintain the button pressed down? It could then be "unticked" (and the pop-up removed) to deactivate it.

**Comment by jpiay** [comment]
Hi,
When I submitted this feature request, my suggested solution was to allow two "clickable" areas: one would work as a button and the other one would work as a switch.
Thanks.

**Comment by HelenFoster** [comment]
How about keyboard controls for the simulator?

I have games where you might need to press e.g. A and then B within a very short time, which is a similar problem.

**Comment by pelikhan** [comment]
@veler did the accessibility work add keyboard shortcuts for the simulator?

**Comment by veler** [comment]
As Microbit doesn't support a long press, but just the state "pressed" (push the button down then back, and only at this moment an event fire), this feature is actually not available in Microbit.

But it is available for Adafruit as the board supports a long press feature. You can already do it with the mouse and it will be soon available with the keyboard.

**Comment by microbit-carlos** [comment]
The micro:bit DAL does support a long press event, which is why the event is fired on release rather than on pressed down.

**Comment by microbit-carlos** [comment]
I would have to check again, but if memory serves me right MakeCode at the moment does not differentiate between short and long press (please somebody correct me here if I'm wrong!). So not sure if that is something that would have be discussed if we want to add it as a new block, or how that difference would affect the accessibility assessment.

**Comment by HelenFoster** [comment]
MakeCode for the micro:bit does already differentiate between short and long press, it's just not implemented in the simulator #2445

**Comment by pelikhan** [comment]
@microbit-carlos the micro:bit does differenciate hold, click, double-click, etc... If we introduce a hold gesture, we would not be able to support these events in the future.

**Comment by microbit-carlos** [comment]
Okay, so MakeCode does currently differentiate between click and long click events? But it is not implemented in the emulator? Why would introducing a "hold gesture" block the ability to support these events in the future?

The original ticket was about enabling a way within for the emulator UI to be able to "physically" press the button without locking the mouse in a click action, so that the user could trigger more than one thing at the same time. How that gets "gesture" is interpreted by the simulated code underneath was not really within the scope of the original request.

Just to have a more concrete example for the sake of argument, let's say if a DOM "on mouse down" event happens on the emulator button, and then "on mouse up" happens outside of the button, this could be interpreted as the user still pressing down the micro:bit button until a new "click" or "mouse up" happens on top of the button. With something like that the emulator can still differentiate between a short click, long click, or other DAL events, no?

**Comment by jpiay** [comment]
What about a "KEEP PRESSED" check button?
