### ISSUE TITLE
update release.manifest for new monaco files

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#241]
The release.manifest needs to be updated with the correct Monaco file paths

![image](https://cloud.githubusercontent.com/assets/4175913/17780462/3c46ba6e-6520-11e6-9f07-fb8e8cb7e12a.png)

**Comment by microsoftsam** [comment]
This was a separate issue with not updating the package.json and cli bump commands with the new path for the monaco typescript files. Has been resolved.
