### ISSUE TITLE
microbit-docs: some blocks in microbit Reference section are 'dead'

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2416]
https://makecode.microbit.org/reference/basic

Has the following 'dead' blocks:
![image](https://user-images.githubusercontent.com/147113/27965657-732b65da-6334-11e7-93a8-94c5fb8316b6.png)

Similarly, there are some in 'input'
![image](https://user-images.githubusercontent.com/147113/27965723-a241e8a8-6334-11e7-8197-c0075116d811.png)
 in LED
![image](https://user-images.githubusercontent.com/147113/27965764-bc25b114-6334-11e7-9aea-666fdb4b9661.png)

I suspect this just a case of removing the offending entries from the  cards block in the MD, and I can do that if necessary, but wondered if these reference markdown files were generated from the same thing that generates the toolbox?

**Comment by abchatra** [comment]
@ganicke Can you take a look?

**Comment by alennie1993** [comment]
Hey guys, I've made a review on the inconsistencies for the new docs...
[microbit makecode all blocks a4_REVIEWED.pdf](https://github.com/Microsoft/pxt/files/1135340/microbit.makecode.all.blocks.a4_REVIEWED.pdf)

**Comment by finneyj** [comment]
thanks @alennie1993!

@abchatra This review was undertaken against the beta version of MakeCode on microbit.org. Maybe this could help ensure MakeCode has consistent docs?

**Comment by abchatra** [comment]
Thanks a ton @alennie1993 and @finneyj 

@ganicke FYI

**Comment by jaustin** [comment]
As well as the comments from @alennie1993 (thanks!) there are also a number of blocks not documented or included, like some from 'game'

![image](https://user-images.githubusercontent.com/147113/28114694-cc5aee5a-66f9-11e7-94fb-e0f67211481e.png)

versus:
![image](https://user-images.githubusercontent.com/147113/28114699-d31e7978-66f9-11e7-9842-6d5ed9987567.png)

**Comment by alennie1993** [comment]
No problem :) Also I included all (unless I missed a couple) of the ones not documented from the UI. They're attached as a comment in the sub heading of their category.

**Comment by ganicke** [comment]
Addressed most of the review items in these PR's. Some things like variable declaration without initialization don't render in blocks. The onDataPacketReceived argument forms will get addressed in an edit of the topic page.

It's good to have a periodic review to check for holes in the coverage for what's in the editor.

https://github.com/Microsoft/pxt-microbit/pull/451
https://github.com/Microsoft/pxt-microbit/pull/453
https://github.com/Microsoft/pxt-microbit/pull/454
https://github.com/Microsoft/pxt/pull/2478
