### ISSUE TITLE
Focus on element is broken on Mac

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt#2418]
The tab index/keyboard navigation is implemented ([see the PR](https://github.com/Microsoft/pxt/pull/2377)) but the focus is broken on Mac.

The reason why is that on Mac, by default, the accessibility settings that allow us to do Tab on element such like `<a>`, `<button>`, is disabled. This impact at least the logo button and simulator toolbar. This problem appears in Safari, Firefox, but not on Chrome.

**There is a workaround for Safari and Firefox :** 
- Safari : https://stackoverflow.com/questions/1848390/safari-ignoring-tabindex
- Firefox : https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox

But we want to avoid the user to do this.
A way to fix it "could" be to replace things like `<a>` and `<button>` by a `<div>` tag, like we did for the Projects and Share menu.

**Comment by microsoftsam** [comment]
Non issue. Turns out Safari mac requires certain settings to be enabled in order to capture tabbing focus on all elements.
