### ISSUE TITLE
[Accessibility] Dropdown menu issues

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#2420]
- [x] Dropdown menu is broken when a screen reader is attached (tested with Voice Over mac)
- [x] Dropdown menu options (Terms & Conditions) and (Privacy) open two tabs on Safari Mac

**Comment by veler** [comment]
Fixed submitted here : [https://github.com/Microsoft/pxt/pull/2446](https://github.com/Microsoft/pxt/pull/2446)
