### ISSUE TITLE
Some extra codes were added

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2424]
**Repro steps:**
• Navigate to https://makecode.microbit.org/ 
• Drag blocks as below project and switch to "JavaScript"
https://makecode.microbit.org/_1v9TMR3eAM47

**Expected result:**
 The code should as below picture 
![test11](https://user-images.githubusercontent.com/23466737/28005738-d4e9edfe-657e-11e7-9883-5ff216cd14a2.PNG)

**Actual result:**
Some extra codes were added
 ![12](https://user-images.githubusercontent.com/23466737/28005863-5923d51c-657f-11e7-9d9b-87a79177cd43.png)

**Comment by abchatra** [comment]
This is the limitation of compiler as it is not 1-1. We can definitely improve it but not a priority at this point of time. Resolving as Won't Fix
