### ISSUE TITLE
Move blockly XML definition out of index.html

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#243]
It confuses crawlers who then consider the blockly terms (like PLUS, MINUS, ....) as keywords for the page.

**Comment by thomasdenney** [comment]
The following code is dependent on that node being in index.html:

* https://github.com/Microsoft/pxt/blob/master/pxtblocks/blocklyloader.ts#L505
* https://github.com/Microsoft/pxt/blob/master/webapp/src/blocks.tsx#L59
* https://github.com/Microsoft/pxt/blob/master/webapp/src/blocks.tsx#L190

First option would be to have `toolbox.xml` and lazily request it in these three places (with local caching). Second option would be to just include it as a string constant in a `toolbox.ts` file and import it. The former approach would be better if it is likely to get modified (I'm not sure if @sgk's work on localisation is likely to affect it) but the second would be easier.

**Comment by riknoll** [comment]
I'm working on a PFR for the second approach mentioned (just putting it into a string constant)
