### ISSUE TITLE
Color gray(#969696) is similar to color white(#FFFFFF)

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2430]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Drag blocks as below shared project
https://makecode.com/_9jgXg7bUHVWL

**Expected result:**
 Color1(#969696) should be gray and there should be a document help children learn to make more colors
**Actual result:**
 Color1(#969696) is similar to Color2(#FFFFFF)
![pic1](https://user-images.githubusercontent.com/23466737/28055101-176e690e-664a-11e7-8854-22bb68575dec.png)

**Comment by microsoftsam** [comment]
These are not predefined colors. The limitations of the simulator is that it's trying to show the color with a certain brightness and simulate what the color would look like on the device. Sometime similar colors will look alike more in the simulator than on the real hardware. 
Won't fix for now.
