### ISSUE TITLE
Block "show animation frame" doesn't show "a wave of color" 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2431]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Drag block “show animation frame” and put it under block "forever"
https://makecode.com/_CjuaTe2EmDcv

**Expected result:**
As the document say: color wipe: a wave of color
**Actual result:**
There is not a wave of color
![1](https://user-images.githubusercontent.com/23466737/28061706-10374fc0-665e-11e7-92a1-793b4f63effc.gif)

**Comment by riknoll** [comment]
This is the correct behavior. You need to call it in a loop
