### ISSUE TITLE
docs: Radio examples don't get two micro:bits when 'played' in docs

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2432]
The ability to immediately run an example inside the docs is amazing.

For example in this doc:
https://makecode.microbit.org/projects/smiley-buttons

The user can experiment with the simulator as they work, however, at the moment it doesn't seem to work for radio docs because you don't get a second micro:bit when you interact with the first like you do in the main editor
![image](https://user-images.githubusercontent.com/147113/28079060-df8179b8-665e-11e7-8b31-e1436561bd1a.png)

**Comment by tballmsft** [comment]
I believe that this is by design.

**Comment by riknoll** [comment]
Maybe we could add a fullscreen button that makes both of them show up. Similar to tablet/mobile view.
