### ISSUE TITLE
"item set brightness" in Game could have better 'gamma' curve

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2439]
If you run the following program side-by-side on a real micro:bit and the simulator
https://makecode.microbit.org/_aRFRRHMaWW5p

It becomes clear that the brightness mapping for low brightnesses is visually incorrect compared to the real micro:bit

Even with the understanding that all displays will differ, it still feels like there could be a good advantage to a simple gamma curve on the brightness so that the mapping can be improved.

Another option would be to show the LED as a bar graph, or show a small bar graph alongside the LED:

![fade in](https://user-images.githubusercontent.com/147113/28115417-cf3fdfd8-66fc-11e7-887d-6cac2ef28721.gif)
![fade with bar](https://user-images.githubusercontent.com/147113/28115424-d422e54a-66fc-11e7-87b8-c0b01cde9f50.gif)

**Comment by HelenFoster** [comment]
(I'm the one who emailed about this.)

Using size to represent brightness makes sense - it's likely to look more consistent than actual brightness across differing displays, and also, on the real micro:bit it does actually kind of look like the size is changing.

2D size changes could allow more distinct brightness levels to be displayed.

Maybe something to look at together with #1069 ?

**Comment by HelenFoster** [comment]
On the real micro:bit, even a brightness of 1 is clearly "on", while 0 is clearly "off". So in a good solution, a brightness of 1 would be clearly visible in the simulator too.

Also, the eye sees brightness logarithmically. If we draw an exponential increase like in the following code, this looks close to linear on the real micro:bit.

(If using area to represent brightness, there's a question of how the eye sees area. Probably not linear either, but closer to linear than for brightness?)

```
let item: game.LedSprite = null
let x = 0
let y = 0
//Python [int(round(255/(1.185**(24-i)))) for i in range(25)]
let bs = [4, 5, 6, 7, 9, 10, 12, 14, 17, 20, 24, 28, 33, 39, 47, 55, 66, 78, 92, 109, 129, 153, 182, 215, 255]
for (let i = 0; i <= 24; i++) {
    y = i / 5
    x = i % 5
    item = game.createSprite(x, y)
    item.set(LedSpriteProperty.Brightness, bs[i])
}
```

**Comment by microsoftsam** [comment]
Here's something I put together: 

![brightnes](https://user-images.githubusercontent.com/16690124/28743174-2f72eadc-73f8-11e7-8124-3e1d5a0946b9.gif)

Changing both the opacity and scale of an led based on the brightness set. Let me know your thoughts @jaustin

**Comment by microsoftsam** [comment]
@HelenFoster's project before / after: 
<img width="406" alt="screen shot 2017-07-29 at 12 58 41 am" src="https://user-images.githubusercontent.com/16690124/28743213-26b7e978-73f9-11e7-8429-2f52fa597b8b.png">

<img width="376" alt="screen shot 2017-07-29 at 12 57 52 am" src="https://user-images.githubusercontent.com/16690124/28743216-29ecf246-73f9-11e7-9711-7807ba0ee5dc.png">

**Comment by HelenFoster** [comment]
That's pretty much what I was thinking, but it doesn't quite do it for the low brightnesses.

On the real micro:bit, it looks like there's a point of light in the middle of each LED. So if the middles were brighter, there could be more contrast at the lower end (e.g. to see the difference in 4 vs 10, or 10 vs 20).

I finally got a good photo! Could it look something like this? Basically we've got 2 colours, both glowing, with the outer one growing faster than the inner one at low brightnesses. The "4" brightness is small but still has the bright point in the middle.

![20170729_105424_crop](https://user-images.githubusercontent.com/5677614/28743986-fb01bb46-744e-11e7-80ec-775276dc6c1f.jpg)

**Comment by HelenFoster** [comment]
My previous test program didn't go down to 1, and had more levels than I could see clearly on the real micro:bit - here I've changed it to just 10 levels with doubling.
```
let item: game.LedSprite = null
let x = 0
let y = 0
let bs = [0, 1, 2, 4, 8, 16, 32, 64, 128, 255]

for (let i = 0; i < 10; i++) {
    y = i / 5
    x = i % 5
    item = game.createSprite(x, y)
    item.set(LedSpriteProperty.Brightness, bs[i])
}
```

And a similar photo of that:

![20170729_123655_crop_ok](https://user-images.githubusercontent.com/5677614/28744631-dca0759e-745c-11e7-880d-03e080896ce2.jpg)

**Comment by microsoftsam** [comment]
Fixed in /beta
