### ISSUE TITLE
Determine component pin locations

### ISSUE THREAD

**Issue by Darzu** [Microsoft/pxt#244]
In many cases, we should be able to statically determine on which pin a component, like a NeoPixel strip, is added. This information is critical for the PXT-Arduino project where I need to generate a list of step-by-step assembly instructions statically.

<img width="692" alt="pins" src="https://cloud.githubusercontent.com/assets/6453828/17788170/305c7d26-6541-11e6-95f7-fd60928cf429.png">

**Comment by mmoskal** [comment]
I need more context. Is there a piece of code that renders the neopixel?

**Comment by Darzu** [comment]
There is code in the simulator that renders the neopixel. Importantly, we draw wires between the neopixel and the board output pin. So the challenge from my side is figuring out which pin to draw the wire to.

At first glance, it seems like we could look at the call sites to certain key functions like: `neopixel.create(pin: DigitalPin, numleds: number, mode: NeoPixelMode)` and record any parameters that can be easily determined (like `P0` in the screenshot above) or "unknown" if they can't be determined. Peli and I are guessing that most of the time when the user is creating a NeoPixel they'll specify directly the pin they want (instead of computing the pin).

The issue I'm facing right now has to do with NeoPixels but in the future we'd like to support other hardware components as well like motors, various analog input sensors, etc.

**Comment by Darzu** [comment]
But actually the more I'm thinking about it, the more I feel like we have a fundamental design decision to make here. Notice how we have three different ways of specifying hardware in blocks, some are implicit some are explicit:

1. LED matrix:
<img width="215" alt="led-matrix" src="https://cloud.githubusercontent.com/assets/6453828/17819633/9ed481b0-65fd-11e6-9d79-b40b9ceb6a77.png">

2. buttons:
<img width="266" alt="button" src="https://cloud.githubusercontent.com/assets/6453828/17819635/a469105a-65fd-11e6-8c64-0b9dc4a7d983.png">

3. NeoPixels:

1. **LED matrix**: the user *implicitly* specifies the one and only LED matrix, and the PXT-Arduino wiring system figures out which GPIO pins to use for the LED matrix.
<img width="215" alt="led-matrix" src="https://cloud.githubusercontent.com/assets/6453828/17819633/9ed481b0-65fd-11e6-9d79-b40b9ceb6a77.png">

2. **buttons**: the user *explicitly* specifies hardware button A or B, and the PXT-Arduino wiring system figures out which GPIO pins to use for the button components.
<img width="266" alt="button" src="https://cloud.githubusercontent.com/assets/6453828/17819635/a469105a-65fd-11e6-8c64-0b9dc4a7d983.png">

3. **NeoPixels**: the user *explicitly* specifies they want a NeoPixel strip driver and they also explicitly select the GPIO pin PXT-Arduino has to use for the strip.
<img width="539" alt="neopixel" src="https://cloud.githubusercontent.com/assets/6453828/17819639/a97f9848-65fd-11e6-9235-70938426b69e.png">

The advantages of 1 & 2 are that the total amount of hardware ever allocated is predetermined: 1 LED matrix and 2 buttons. This makes things very simple for the user as they don't need to think about which pin they want something connected to, they just think in terms of "I want to display this to some LEDs". The problem with 1 & 2 is that it isn't as flexible. What if the user wants 3 buttons? Or to display two numbers across 2 different LED matrices?

The advantage of approach 3 is that the user can theoretically create as many NeoPixel drivers as they want. The disadvantage is that the user has to explicitly specify the pin they want which is a complex decision depending on their familiarity; furthermore, it's technically undecidable for our system to know exactly which pin they wanted, and since the user specifies the pin they want, the PXT-Arduino system has to respect that choice and is more limited in how it allocates GPIO pins. Specifically, the PXT-Arduino system has to hold pins open in reserve in case the user wants to put something there.

All of this is to say that there's actually a fundamental and complex issue at stake here. I'm going to do some thinking about this, and I'll chat with Peli and potentially Joe and James might need to be involved to make sure the DAL supports our scenarios.

**Comment by Darzu** [comment]
@mmoskal , would it be possible to collect the the call sites of all functions that have a DigitalPin parameter and the value of the DigitalPin parameter if it's "easily" determinable? This would cover my use case with the NeoPixels and would allow us to do new things like detecting when code is sending audio signals to a pin so we could draw a speaker.

What do you think of this approach? Is it feasible? Does it seem to brittle or specialized?

cc: @pelikhan

**Comment by pelikhan** [comment]
Maybe a property on the enum type definition that forces the typecheck er to report the call? There is also AnalogPin...

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by mmoskal** [comment]
I believe all the call sites are already returned, with the debug info. You can try to see if you can make use of that.

**Comment by Darzu** [comment]
@mmoskal, where is this debug info collected? `procDebugInfo` ?
If so, it seems `procDebugInfo` is only set by `thumbEmit()` which is only called if `opts.target.isNative` is set.
Or is this information somewhere else? I've been digging but can't seem to find it yet.

**Comment by mmoskal** [comment]
I think you are right. Maybe you can emit it always? Otherwise I Will try to look at this today or tomorrow.

**Comment by mmoskal** [comment]
You will want to add `//% trackArgs=0` to `neopixel.create`. You could also add `trackArgs=0,2` to get pairs of `DigitalPin,NeoPixelMode` - 0 and 2 are argument indices, if the mode is of any use.

After that, you will have `neopixel.create = ["DigitalPin.P0", ...]` in `resp.usedArguments`. Note that you can also have `"*"` there, meaning unknown.

**Comment by Darzu** [comment]
This is perfect, thanks @mmoskal !!
