### ISSUE TITLE
micro:bit blocks - can't create empty sprite array

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2451]
It seems this isn't allowed when using blocks:

![empty_array_1](https://user-images.githubusercontent.com/5677614/28218837-b3e08c4a-68b1-11e7-8cd3-6ce9ad941868.png)

Having to add a sprite at the start can make some messy code, e.g. if the sprites appear and disappear in the "forever" loop.

We can write in JavaScript:
`let list: game.LedSprite[] = []`
but converting to blocks and back breaks it.

**Comment by riknoll** [comment]
Looks like a bug with the "create empty array" version of the block; the sprite block is unrelated (you can get the same behavior with a string).
