### ISSUE TITLE
more subtle error message

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#246]
The current error message is a bit over the top:
![image](https://cloud.githubusercontent.com/assets/4175913/17793338/5898dacc-655b-11e6-93be-4d491cbfee59.png)

Here are suggestion:

- [x] bump down the font
- [x] do not show when intellisense menu is present

**Comment by microsoftsam** [comment]
I bumped down the font size to be 3 less than the editor font size, and made it only show the errors if the intellisense menu is not present. Let me know what you think @pelikhan

**Comment by tballmsft** [comment]
@microsoftsam - I find that the error message updates too frequently - while I am typing, I see different error messages appear. Should the worker pause longer while I am typing?

**Comment by microsoftsam** [comment]
Yeah @tballmsft, I fixed that recently with issue #246. Let me know if you're still not getting the desired behaviour there.

**Comment by mmoskal** [comment]
I think the problem is that the layout of text changes when we show the error messages. In VSCode you get squiglies but they are not moving mode around. Could we maybe have some bubbles?

**Comment by mmoskal** [comment]
It seems we already have squigglies and hover errors.
