### ISSUE TITLE
"Oops! Can't run..."  Why not?

### ISSUE THREAD

**Issue by HyperDuino** [Microsoft/pxt#2460]
In the program at this link: https://makecode.microbit.org/_XW4J3pLPzAwj

If I click on the "play" button for the simulator, it displays the "Oops, can't run" error.

The reason for the error is not obvious, and how would a student or teacher debug this?  I'm pretty sure it has to do with the "serial write line [point]" block, because if that is replaced with "serial write number [point]", then the simulator works, although it doesn't immediate display the serial output.  If the answer is, "serial write line only works with text", then why does "serial write" work with a number?

![game one error](https://user-images.githubusercontent.com/13832091/28241287-833f16e8-6946-11e7-80ef-a72a43eda7e8.png)
![game one](https://user-images.githubusercontent.com/13832091/28241288-83406a52-6946-11e7-934a-0c5ee95c8957.png)

**Comment by HelenFoster** [comment]
I've also been having some trouble with "oops can't run - why not?".

Sometimes it adds a warning triangle onto the relevant block, and if you click this it tells you what's up. But in a big program, how do you find it?

Sometimes, like in this case, there isn't any warning triangle (unless I just haven't seen it yet).

**Comment by HelenFoster** [comment]
OK I think there's something wrong with the triangle. I made a tiny incorrect program. One moment the triangle is there:

![warning_triangle_1_there](https://user-images.githubusercontent.com/5677614/28250271-201824e4-6a5c-11e7-9486-d2dcc4decdd0.png)

And the next it's not:

![warning_triangle_2_not](https://user-images.githubusercontent.com/5677614/28250272-21d6745c-6a5c-11e7-8506-f507bc5da8e4.png)

Using Chrome 59.0.3071.115 on Fedora.

**Comment by HyperDuino** [comment]
Couldn't the editor have signaled the user at the moment they tried to attach a non-compatible block to another? I get it that there are a small number of block-connecting shapes that mean there will be things with matching shapes, but not matching data types, but couldn't the editor know that at the moment of the attempted block placement?

**Comment by abchatra** [comment]
Bug here is serial write line block accepts number

**Comment by HyperDuino** [comment]
Wouldn't the bug be that serial write line apparently can't write a number? If serial write can write a number, why can't serial write line?

**Comment by HyperDuino** [comment]
(how would I explain that to a student?)

**Comment by abchatra** [comment]
Static typescript is a strongly typed language. We don't support multiple different types to the same input.

**Comment by HyperDuino** [comment]
Sorry, but that doesn't make sense. :(

**Comment by abchatra** [comment]
For the same field there cannot be either String or Number input. Type needs to be well defined. This is by design of the language chosen. I understand it is sub-par for students.

**Comment by HyperDuino** [comment]
What do you mean by "same field"? Same as what?  Do you mean that for serial write line that there can't be either strings nor numbers?   Is there a block for make string-from-number?  Could the block-to-typescript engine change the underlying code of the serial write line block? How would a user know about these limitations?

**Comment by abchatra** [comment]
``
 Do you mean that for serial write line that there can't be either strings nor numbers?
``
Yes
``
 Is there a block for make string-from-number?
``
You could use "Join" block in Text category which compiles down to "+" operator. Probably we should have a first class tostring block for number.

``
Could the block-to-typescript engine change the underlying code of the serial write line block?
``
Yes we could design something specific for blocks. But needs de-compilation support for the same.
Feel free to give pull requests.

**Comment by HelenFoster** [comment]
So is my disappearing triangle a different bug? Should I make a new issue for that?
