### ISSUE TITLE
Make blocks<==>typescript conversions undoable?

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2464]
Converting from blocks to TypeScript or vice versa:

* is currently an irreversible one-click action.
* has had a series of bugs which cause breakage or data loss (and these probably won't stop coming anytime soon).
* makes some code changes that aren't really bugs but might be annoying.
* clears the undo stack, so mistakes from just before are also committed.

My suggestion is to save the whole program before conversion, and add it to the undo stack. So if the user converts and later clicks undo, things end up back exactly where they were before (including any remaining undo steps).

**Comment by HelenFoster** [comment]
I just saw on another ticket that if you convert from blocks to script, and then provoke the "can't convert to blocks" error, it offers to restore the previous block program. So it must already be saving the block program for that case.

**Comment by HelenFoster** [comment]
With what I'm asking about here, we'd need to able to undo at least 2 conversions. The most common situation is popping over to the other side briefly, then noticing some unwanted change on the round-trip.

**Comment by abchatra** [comment]
We already save the program if there are no changes and restore it back. A program which has been modified needs to be either compiled or decompiled. It is hard problem to accurately transition to the original user code from an AST tree.

**Comment by riknoll** [comment]
It's a trade off between converting to blocks cleanly and preserving the user's TypeScript code. We have favored the blocks side of that for the most part since it is what impacts most users.

**Comment by HelenFoster** [comment]
Right, the conversion is a hard problem, and has trade-offs which make it impossible to satisfy everyone. That's mainly why I suggested this ;)

**Comment by HelenFoster** [comment]
> We already save the program if there are no changes and restore it back. 

If so, this would solve the first point in my OP ("irreversible one-click action"). But I don't think it's working. I guess I'll test that some more.

**Comment by HelenFoster** [comment]
> We already save the program if there are no changes and restore it back.

"Blocks to script to blocks" normally does the right thing, so it's hard to find an example that proves it one way or the other. I have a feeling I've seen my blocks change before, but couldn't reproduce it. In #2632, if there are no changes to the script, the original blocks are automatically restored (but that might just be because there's an error).

With "script to blocks to script", it's easy enough to show the original script is not restored even if there are no changes.
Short example: `let x = 0`
Becomes:
```
let x = 0
x = 0
```

That would help. But as I said, it's not the whole story, since it would still be easy to get caught by "convert, change one little thing, convert back, and be unhappy with the other things that changed".
