### ISSUE TITLE
micro:bit hex download instructions (Chrome)

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2465]
In Chrome, there's an advanced setting called "Ask where to save each file before downloading". I think it would be useful for people to know about that. I made sure all the computers had that setting switched on before the kids arrived, and then they didn't have any trouble sending the hex file to the micro:bit.

----

The download "help" link https://makecode.microbit.org/device/usb says:

> In Edge, Internet Explorer and Firefox, you can click on the Save As button on the bottom bar and save the .hex file directly into the MICROBIT drive!

Indeed, saving directly into the MICROBIT drive is much easier and quicker than dragging the file from the file manager (especially when the Downloads folder has a lot of similar-looking ones that you have to pick from).

**Comment by abchatra** [comment]
Please feel free to give a pull request for the documentation.

**Comment by abchatra** [comment]
Or you can use edge browser where you get this behavior by default

**Comment by abchatra** [comment]
fixed
