### ISSUE TITLE
micro:bit deleted sprite can still touch things

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2466]
Here we deleted `item`, but `item.isTouching(item2)` and `item2.isTouching(item)` are both still true. If the sprite is pretending not to exist, these should be false. Tested on the simulator and real micro:bit.
```
let item = game.createSprite(2, 2)
let item2 = game.createSprite(2, 2)
item.delete()
if (item.isTouching(item2)) {
    basic.showNumber(1)
}
basic.pause(1000)
if (item2.isTouching(item)) {
    basic.showNumber(2)
}
```

**Comment by HelenFoster** [comment]
It could be fixed like this:
https://github.com/HelenFoster/pxt-microbit/commit/cf31e87c3d4a67b7915af9335eab135c188e15a3

I think isTouching is the only function that causes a problem.

There's a question of whether isTouchingEdge should also return false (and if so, ifOnEdgeBounce should do nothing for consistency). But I'm inclined to say leave it alone, since x and y still exist and can be read, and there's no reasonable alternative to that.

What would I need to do about tests?

**Comment by riknoll** [comment]
@HelenFoster We don't have tests for the game library. I know we support tests on libs, but let me double-check how those are authored. Feel free to open the PR for now!

**Comment by HelenFoster** [comment]
I don't really know what I'm doing, so I'm probably not the right person for adding tests where there aren't any ;)
