### ISSUE TITLE
micro:bit sim - scrolling fills screen in greyscale mode

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2467]
(Updated) On the real micro:bit, the 0 and the 99 are both visible. The simulator, when it gets to the 99, turns on all the LEDs so we can't see anything.

```
led.setDisplayMode(DisplayMode.Greyscale)
basic.showNumber(0)
basic.pause(1000)
basic.showNumber(99)
```

----

Original post (this no longer happens):

The real micro:bit does something reasonable with this code. The simulator, when it gets to the 99, turns on all the LEDs so we can't see anything.

```
let item = game.createSprite(2, 2)
basic.showNumber(9)
basic.pause(1000)
basic.showNumber(99)
```

**Comment by abchatra** [comment]
Game category is pretty buggy. Probably we should get rid of that. Only reason for its existence is due to backward compatibility with older editors.

**Comment by abchatra** [comment]
Another repo---------------
Expected: The number should stay on the screen, as if we never created any sprite.
Actual: The number disappears after a short time, as if the sprite was still there. (Same for the real micro:bit and simulator.)
let item = game.createSprite(2, 2)
item.delete()
basic.showNumber(0)

**Comment by HelenFoster** [comment]
Why do you say #2468 is a duplicate? I'm pretty sure it's not.

**Comment by HelenFoster** [comment]
> Game category is pretty buggy. Probably we should get rid of that. Only reason for its existence is due to backward compatibility with older editors.

I really hope not. I might even have have reported most of the important bugs by now.

**Comment by jaustin** [comment]
> Game category is pretty buggy. Probably we should get rid of that. Only reason for its existence is due to backward compatibility with older editors.

We do see this being picked up in guides and other printed material, and it seems popular, so I think it's far better to fix it up than remove it!

**Comment by pelikhan** [comment]
The "game" engine takes over the screen rendering so typically you would not want to use the "show..." functions in parralel with that library. Is there a list of bugs associated to the game library? It is very useful to create small games.

**Comment by HelenFoster** [comment]
> The "game" engine takes over the screen rendering so typically you would not want to use the "show..." functions in parralel with that library. 

It's useful for debugging the game. So it's OK if the result is a bit messy. But the numbers need to be legible (which they are on the real hardware, but not on the simulator).

> Is there a list of bugs associated to the game library?

I opened a bunch of issues about it recently, and they're getting fixed.

**Comment by DavidWhaleMEF** [comment]
Please don't remove the game tab and please don't change any of the API's - I've just completed editing two books that will surface later this year that use the game features quite extensively, and those books will break if you remove the features.

**Comment by pelikhan** [comment]
We are keeping the game category and fixing obvious bugs.  No breaking change here.

**Comment by abchatra** [comment]
Micro:bit is in RC and there is no change to existing categories other than critical bug fixes.

**Comment by HelenFoster** [comment]
This one isn't the game library. Rather, the simulator gets confused by scrolling in greyscale mode.

```
led.setDisplayMode(DisplayMode.Greyscale)
basic.showNumber(0)
basic.pause(1000)
basic.showNumber(99)
```

**Comment by jaustin** [comment]
@abchatra just checking in on this one as it's also referenced in support tickets:
microbit.org-ticket: 2028

Now that Sam's done the nice fading LEDs and some other simulator updates, is this something that's in a better position to be fixed? I tested your short reproducer (that doesn't include the game library) on the acc branch this morning and it's still failing in the same way as you described here https://github.com/Microsoft/pxt/issues/2467#issuecomment-315783797

**Comment by pelikhan** [comment]
```
let item = game.createSprite(2, 2)
item.delete()
basic.showNumber(0)
```

The expected behavior is that the game engine is constantly rendering to the screen so ``0`` will go away.

**Comment by pelikhan** [comment]
There is a mix up of 2 issues here: game engine and greyscale mode. It seems that the greyscale is fixed.

**Comment by pelikhan** [comment]
Documentation updated. Please reopen as needed.

**Comment by HelenFoster** [comment]
>There is a mix up of 2 issues here: game engine and greyscale mode. It seems that the greyscale is fixed.

No mix up: the game engine was previously triggering the greyscale issue. But indeed it seems to be fixed.
