### ISSUE TITLE
micro:bit deleted sprite still interferes with other display commands

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2468]
Expected: The number should stay on the screen, as if we never created any sprite.
Actual: The number disappears after a short time, as if the sprite was still there. (Same for the real micro:bit and simulator.)

```
let item = game.createSprite(2, 2)
item.delete()
basic.showNumber(0)
```

**Comment by abchatra** [comment]
Duplicate of https://github.com/Microsoft/pxt/issues/2467

**Comment by HelenFoster** [comment]
To expand on this: After making some sprites, the game engine deliberately interrupts other display commands and re-displays the sprites after a short time. The point was that it shouldn't do this when all the sprites have been deleted.

**Comment by abchatra** [comment]
Sorry I miss understood.

**Comment by HelenFoster** [comment]
My first thought was to avoid plotting when there are no sprites. This does work.
https://github.com/HelenFoster/pxt-microbit/commit/384e8afec8c45d80fb5da178c8e74e595939402a

The remaining issue is that the game library sets the display to greyscale mode.

The game library initializes implicitly when the user creates the first sprite. So it makes sense to be able to "exit" the game library by deleting the last sprite. (And then it needs to work again if another sprite is created later.)

Would it be a good idea to save what mode the display was in when entering game state, and then restore it when the last sprite is deleted?

**Comment by HelenFoster** [comment]
> Would it be a good idea to save what mode the display was in when entering game state, and then restore it when the last sprite is deleted?

Would have to add a getDisplayMode function to do that.

**Comment by HelenFoster** [comment]
Was fixed instead with manual pause and resume of game engine, in https://github.com/Microsoft/pxt-microbit/pull/476
