### ISSUE TITLE
search "one level deeper" in intellisense

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#247]
When typing ``clear``, the intellisense should find ``basic.clearScreen`` by searching one level deeper for symbols.

**Comment by pelikhan** [comment]
@microsoftsam any noticeable impact in smoothness of completion?

**Comment by microsoftsam** [comment]
A slight (non noticeable IMO) performance hit when getNavigateToItems is called, but it's indexed from then on out so the performance is the same from there.
