### ISSUE TITLE
Example Insertion Sort shows some error

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2479]
**Repro steps:**
• Navigate to https://makecode.microbit.org/
• Try the document example: 11.Arrays->Unplugged:Different Sorts of People->Insertion Sort
• Shared project:https://makecode.microbit.org/_grfYrhczkU5e

**Expected result:**
There shouldn't have any error
**Actual result:**
There shows some error

**Comment by abchatra** [comment]
Looks like in your example `element` is defined as
```javascript
let element: [] = []
```
instead of this in the example
```javascript
let element = 0
```
There is no error when `element` is correctly defined
