### ISSUE TITLE
micro:bit makecode website / example code licensing

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2486]
It seems from the git repos that it's all MIT-licensed (including docs). But the most obvious "Terms Of Use" link at the bottom suggests to people just using the website that it's for personal use only. And what was the intention for example code?

Main case: Student works through one of the project worksheets or loads an example, and wants to extend it and share the result. What are they allowed to do, and do they need to do anything in return?

**Comment by abchatra** [comment]
All our examples are MIT license, so you are free to modify and distribute.

Can you point to which "Terms of Use" you are referring to?

**Comment by HelenFoster** [comment]
It's in the footer if you open up the full page, e.g. https://makecode.microbit.org/projects/reaction-time/code

Those "Terms of Use" do say "Unless otherwise specified", and it is otherwise specified if you look closely (click through onto "Edit this page on GitHub" and then look in the repo's root directory) but I was thinking it could be confusing.

**Comment by abchatra** [comment]
Terms of use here refers to website itself. Even that says it is ok to extend it if you are using if for non-commercial purpose.
