### ISSUE TITLE
Simple string/integer type mismatch causes oops...

### ISSUE THREAD

**Issue by finneyj** [Microsoft/pxt#2487]
Hi Guys - seen a few folks come across this... essentially no type checking of string/int variable types in the block editor, which is only picked up when you hit download.  Corresponding TypeScript picks up the type mismatch.

very simple repro:

![image](https://user-images.githubusercontent.com/11539567/28418590-21f34bd6-6d54-11e7-98d7-e58788389338.png)

Do we have a policy on what we want to happen in these cases?

**Comment by abchatra** [comment]
@riknoll - FYI We should  have propagated the typescript error to blocks. (Variables don't get their type propagated in blockly).

**Comment by riknoll** [comment]
I've fixed this in master and am about to cherry-pick it into V0. Variables will still be able to be attached to any input but now you'll get an error icon on the block with an explanation. We should do a release soon.

**Comment by riknoll** [comment]
Fixed in V0, will show up once we do a release

**Comment by finneyj** [comment]
thanks guys!
