### ISSUE TITLE
oembed HTML code should point to code iframe rather simulator

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#249]
The oembed API is currently displaying the simulator and should be displaying the code instead.

**Comment by mmoskal** [comment]
Do we have an URL that displays the code? Right now we send them to --run.

**Comment by mmoskal** [comment]
@pelikhan I need a function that given `blocksWidth` and `blocksHeight` provided when publishing script, and also maxwidth/maxheight from the oembed call (if given by the user)  gives me HTML that starts with `<iframe...>` ? 

If you really want to embed it in foreign websites it shouldn't have `<div class="ui card sim"><div class="ui content">`

**Comment by pelikhan** [comment]
See in docsrender

```
    export function embedUrl(rootUrl: string, id: string, height?: number): string {
```

**Comment by pelikhan** [comment]
This is fixed.
