### ISSUE TITLE
game: sprite simulator doesn't work with 'show string' or 'show icon'

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2490]
Using the sprites alongside the 'basic' functions gives odd behaviour on the simulator:

![bug game showstring](https://user-images.githubusercontent.com/147113/28460964-64b97c84-6e0c-11e7-8fd5-f735a3cd8e47.gif)

This is the simplest program I can recreate this with.

May have implications for #2284

**Comment by jaustin** [comment]
Sorry, I should have said, this works 'properly' on the micro:bit

**Comment by HelenFoster** [comment]
This is what I was getting at in #2467, though I didn't post a picture.

**Comment by abchatra** [comment]
Duplicate of #2467
