### ISSUE TITLE
docs: could these also available offline, please?

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2491]
Hi all,

We've had a few requests come in recently for the MakeCode docs to be cached in the browser in the same way as the editor is.

This would be a really nice way to help people on shaky internet connections. 

If that approach doesn't work, perhaps we could look at building/publishing a nice archive of the documentation for use offline?

**Comment by abchatra** [comment]
@pelikhan ideas?

**Comment by pelikhan** [comment]
What kind of scenarios do we want to enable here? Downloading all docs on every client is potentially costly in bandwidth and in most cases useless. We have lots of docs that includes images etc..

Offline drops of the docs will go stale so they need an update mechanism.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jaustin** [comment]
We have two different groups making use of the cacheing feature for MakeCode in offline scenarios, but they can't access the docs. We also had someone asking if they could print the docs to a PDF.

I did an experiment with wget to see what I (w)got, and it's basically fine except for the odd bit where we use JS to render nice block views...

I think some of the following
* Cache the reference section but not the lessons
* Make a way to download a PDF of the docs or a web archive

You're right that offline drops of docs will go stale, but at no greater rate than a book will, and we're *definitely* going to have people using books, so I'm not sure that's a huge concern in many ways.

**Comment by abchatra** [comment]
Print to PDF works even today. Look for the following icon
![image](https://user-images.githubusercontent.com/6107272/28471554-66a9c450-6df2-11e7-86ca-15cb9c842e10.png)

**Comment by pelikhan** [comment]
> I did an experiment with wget to see what I (w)got, and it's basically fine except for the odd bit where we use JS to render nice block views...

Building a crawler to download the docs is not something we would recommend.

**Comment by pelikhan** [comment]
The best solution would be to load the markdown in the client, render all the code snippets and they use the browser print to PDF feature. It would take a little time but most of the computation would be client side. We need to implement this so that it does not pollute our analytics.

**Comment by jaustin** [comment]
So, the print to PDF works fine on a single page, but I couldn't see a way to print multiple levels of hierarchy? For the large blocks PDF I made, I concatenated all the references pages into one large page that took ages to render, then printed a PDF - it was a hack but it did prove the concept.

Am I missing the way to do a print of more than a single page, @abchatra ?

**Comment by abchatra** [comment]
You can only print one page at a time.

**Comment by pelikhan** [comment]
It is not supported yet but the client page could request multiple pages, concat the markdown and render it in 1 pass.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jaustin** [comment]
I think the thing Peli suggests of the client page that pulls in some sections (maybe user selectable checkboxes for the hierarchy?) and then gives good UX feedback while it renders.

I'm really happy for this to be a foundation-facing tool that we use and then publish the docs monthly for example.
