### ISSUE TITLE
Problem downloading on local micro:bit editor

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2492]
Running pxt-microbit on Fedora 24, when I click Save or Download it says "There was a problem, please try again".

The shell says:
```
Error: ENOENT: no such file or directory, scandir '/media/helen'
    at Error (native)
```
I guess it's looking for /run/media/helen .

Is it trying to put the hex file directly onto the micro:bit? If so, clicking Save shouldn't do that. #2485

**Comment by abchatra** [comment]
@HelenFoster can you add more information? 

- What is the browser? 
- Is this website or are you doing `pxt serve`?

**Comment by HelenFoster** [comment]
`pxt serve` with Chrome or Firefox.

Can I work around this by making it act as website?

**Comment by abchatra** [comment]
`?forceHexDownload=1` try this to the URL. 

I don't have Fedora to repro this issue. Feel free to give pull request if you able to fix this.

**Comment by HelenFoster** [comment]
> ?forceHexDownload=1 try this to the URL.

Thanks, that works.

> I don't have Fedora to repro this issue. Feel free to give pull request if you able to fix this.

Looks like there are 2 bugs:
* Where it's looking for the micro:bit (maybe Fedora-specific)
* When using `pxt serve` the Save button should download the hex file, as currently happens with both buttons when forceHexDownload=1 (probably not Fedora-specific)
Should I open another issue to separate them?

**Comment by abchatra** [comment]
This issue is good enough to track. 

By the way thanks for all the bugs. Really appreciate it.

**Comment by riknoll** [comment]
The second one is by design. We do auto-flashing which is much friendlier with local development.

**Comment by HelenFoster** [comment]
> The second one is by design. We do auto-flashing which is much friendlier with local development.

The "Download" button does auto-flash, but the "Save" button should let people save the hex file to the computer.
