### ISSUE TITLE
bluetooth/sim: Program Error: pxsim.bluetooth.onUartDataReceived is not a function

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2493]
When using the Bluetooth package and the "on data received" block, you get the following error:

![image](https://user-images.githubusercontent.com/147113/28471118-ee882146-6e33-11e7-8fcc-96615b36fda0.png)

This does actually work, though - putting the program below on a micro:bit and using the UART app listed in the code does work:
https://makecode.microbit.org/_g8VWUU1JsaMV

So the bug is sim related, I think

**Comment by tballmsft** [comment]
There is no support for bluetooth in the simulator. We need a better error message.

**Comment by jaustin** [comment]
Yes, that's interesting - I guess I "knew that" because none of the other functions did anything, but they also didn't throw errors so it didn't bother me!

Now you've made me realise that it'd be nice to be able to simulate Bluetooth connections and events, or even use web-bluetooth to actually *be* the Bluetooth device that MakeCode is describing - but that's for another day ;)

**Comment by abchatra** [comment]
This is  fixed.
