### ISSUE TITLE
Pins pressed/released confusion

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2495]
There are two blocks for pin-touch-related events: `onPinPressed` is CLICK and `onPinReleased` is UP.

As there are two blocks, and "pressed" and "released" can be opposites in natural language, there's a strong implication that these blocks have opposite actions. In reality, they do almost the same thing.

Adding the DOWN block would help with this, but naming it is a problem (as the other two have painted it into a corner).

The sprite here normally doesn't go anywhere, but we can make it move to the right with a long click:
```
let item: game.LedSprite = null
input.onPinPressed(TouchPin.P0, () => {
    item.change(LedSpriteProperty.X, -1)
})
input.onPinReleased(TouchPin.P0, () => {
    item.change(LedSpriteProperty.X, 1)
})
item = game.createSprite(2, 2)

**Comment by HelenFoster** [comment]
In the spirit of a minimal number of blocks: rather than add a block, maybe deprecate `onPinReleased` and implement #2463 to replace the removed functionality.

Something like this but with UP instead of CLICKED:

![button_pressed](https://user-images.githubusercontent.com/5677614/28473426-6484de72-6e3c-11e7-9338-d8e91b058a1a.png)

**Comment by riknoll** [comment]
Yep, that is very confusing. We don't remove blocks very often though. Maybe we should hide `onPinReleased` from the toolbox but still allow it in the editor so that we don't break any scripts.

**Comment by pelikhan** [comment]
We cannot remove or change existing blocks, we can move them to advanced.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HelenFoster** [comment]
Looks like `onPinReleased` is already in advanced. That makes it go onto the second page of Input blocks after the "more", right? (As a user, I didn't notice there was a difference between the two pages.)

If adding the other one, `onPinTouched` might be an OK name for it.
