### ISSUE TITLE
Need ability to set height of simulator area

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/pxt#25]
For my pxt target (bot framework), the intention is to host a chat control in the simulator area for interfacing with the bot. The simulator area is a fixed size, but currently too small vertically to host a usable chat control. One solution would be to provide the ability to change the height of the simulator.

**Comment by pelikhan** [comment]
How about a custom .css file that would allow you to override the style?

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by eanders-MS** [comment]
That should work. I think the width is ok as-is.

**Comment by RobJellinghaus** [comment]
For my purposes I would love to be able to make it wider as well, and also would love to be able to scale down the blocks and the width of the block toolbar.

**Comment by pelikhan** [comment]
With custom CSS, you'll be able to override everything on the page. You will have to deal with the various screen sizes though.

**Comment by RobJellinghaus** [comment]
That's fine, pxt-phaser is really optimized for a desktop Scratch-like experience, at least in my initial optimization target.

**Comment by pelikhan** [comment]
You can specify the aspectRatio in the runtime field in pxtarget.json. See the pxt-samples.
