### ISSUE TITLE
Undo/redo buttons only show their status in Blocks

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2501]
In the Blocks section, the undo/redo buttons helpfully change colour to show whether they can do anything or not. In the JavaScript section, they always look like they can do something.

![undo_buttons](https://user-images.githubusercontent.com/5677614/28489811-fbd712fe-6ec3-11e7-9b8d-04ad1f45f861.png)

**Comment by abchatra** [comment]
I do think this is limitation of Monaco editor. @microsoftsam?

**Comment by microsoftsam** [comment]
Limitation in the monaco editor.

**Comment by abchatra** [comment]
Closing as Dependency issue on external Monaco editor
