### ISSUE TITLE
(micro:bit target) some strings are not in core-strings.json

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#2502]
Some strings in "libs/core" are not in "core-strings.json" and also not on Crowdin.

game.ts: all strings
icons.ts: some strings; ex. "arrow image"
images.cpp: some strings; ex. "scroll image"

**Comment by abchatra** [comment]
Dupe of https://github.com/Microsoft/pxt/issues/2384

**Comment by sgk** [comment]
These are not duplicate issues. #2502 means that the strings "arrow image" are correctly marked up as `block="..."` but the strings do not appear in the "core-strings.json" file. #2384 means that arrow names like "NorthEast" are not marked up as `block="..."`.

**Comment by sgk** [comment]
This seems already fixed and can be closed.

**Comment by abchatra** [comment]
Fixed
