### ISSUE TITLE
Hack Your Headphones Error

### ISSUE THREAD

**Issue by gbowman85** [Microsoft/pxt#2516]
On the final image at https://makecode.microbit.org/projects/hack-your-headphones/code all of the "ring tone" blocks are showing Middle C, where in fact the code view shows C,D,E,F,G,A.

This could be confusing for children who are recreating the code for themselves.

**Comment by abchatra** [comment]
Looks like de-compilation is failing. @riknoll  any clue?
```
music.ringTone(music.noteFrequency(Note.D));
```

**Comment by abchatra** [comment]
Thanks @gbowman85 for the issue.

**Comment by riknoll** [comment]
I believe this is fixed in master and V0, but I'll double check

**Comment by riknoll** [comment]
Nope, looks like this regressed at some point

**Comment by caitlin-hennessy** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/2592 and https://github.com/Microsoft/pxt/pull/2590.
