### ISSUE TITLE
The documentation can't be opened in a new tab

### ISSUE THREAD

**Issue by WendyFeng01** [microsoft/pxt#2517]
**Repro steps:**
• Navigate to https://makecode.microbit.org/ on firefox(Mac & VM), Edge and IE
• Click Reference in "?help"
• Open the documentation in a new tab

**Expected result:**
The documentation can be opened in a new tab
**Actual result:**
The documentation can't be opened in a new tab

**Notes:** If you can't repro this, you can reset the project and try again
![firefoxreference](https://user-images.githubusercontent.com/23497626/28600708-51b9c4b2-71e6-11e7-893d-e777b1c716e1.gif)

**Comment by microsoftsam** [comment]
Popup blocker on?

**Comment by WendyFeng01** [comment]
Edge & IE will pop up as follows, and after clicking "Allow once", it still can't navigate to a new tab.
![untitled](https://user-images.githubusercontent.com/23497626/28957608-27f10e1a-7925-11e7-9264-a53683fa207a.png)

**Comment by Helen09** [comment]
The issue still repro and I opened it on https://github.com/Microsoft/pxt-microbit
