### ISSUE TITLE
Hosting art assets for targets?

### ISSUE THREAD

**Issue by Darzu** [Microsoft/pxt#252]
I have a few art assets for the Arduino Zero and some hardware components that are necessary for the [pxt-arduino](https://github.com/microsoft/pxt-arduino) target. What's the appropraite way to host these? Currently, I have them checked into a branch of PXT [(arduino-assets)](https://github.com/Microsoft/pxt/tree/arduino-assets) but this doesn't seem like the best solution.

**Comment by pelikhan** [comment]
Try putting them under /docs/static

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by Darzu** [comment]
Perfect, thanks!
