### ISSUE TITLE
The background of content panel changes to black when click or move the blocks on the content panel

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2521]
Repro steps:
• Navigate to https://pxt.microbit.org/beta on Edge (only repro on Edge)
• Move or click the blocks on the content panel

Expect result: 
The background of content panel doesn't change
Actual result: 
The background of content panel changes to black
 
![background](https://user-images.githubusercontent.com/11880996/28610444-f74005d4-721a-11e7-88b5-ba8b31cca600.gif)

**Comment by abchatra** [comment]
@yanlxu What build of edge is this? I can't repro on my edge

**Comment by yanlxu** [comment]
@abchatra, we use the latest build: RS_ONECORE_WEBPLAT_STAGE_DEV3\16248.1003.170723-1730

**Comment by yanlxu** [comment]
close this issue as not repro on the latest build
