### ISSUE TITLE
Custom buttons for targets?

### ISSUE THREAD

**Issue by Darzu** [Microsoft/pxt#253]
In the pxt-arduino target, we want to have a custom button in PXT that generates assembly instructions and a complete parts list for the user. Would it be possible to let targets extend PXT with custom buttons? Here's a branch on PXT that adds the buttons that I need directly to PXT: [arduino-btns](https://github.com/Microsoft/pxt/tree/arduino-btns).

![image](https://cloud.githubusercontent.com/assets/6453828/17839334/77336e12-6799-11e6-8bee-625b03562f49.png)

**Comment by pelikhan** [comment]
Is this still relevant? Seems that it will be built-in soon.

**Comment by Darzu** [comment]
Well it'll soon be desirable for the microbit target as well, but it's really a PXT architectural question: is it okay to have a parts button for all PXT targets?

**Comment by Darzu** [comment]
Perhaps the best thing to just to provide a "hack" flag usesPartsList or something that is false by default but on for pxt-microbit and pxt-arduino. If enough of these hack flags appear would could try to find a more general mechanism for targets to use.

**Comment by pelikhan** [comment]
Parts list button should only appear if part/breadboard are needed.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by tballmsft** [comment]
Yes, but we should have the option to hide it.

Tom Ball | Microsoft Research | Microsoft
Email: tball@microsoft.com<mailto:tball@microsoft.com>

**Comment by pelikhan** [comment]
The parts button only appears when parts are needed.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/a5627dce2d92491b3ce5e996c0a63f59b1f358b5
