### ISSUE TITLE
custom.ts regression in master

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#2532]
There's a regression in the creation of custom.ts in master where it's creating the file but saving it's contents to the contents of main.ts

**Comment by microsoftsam** [comment]
@pelikhan perhaps related to https://github.com/Microsoft/pxt/pull/2518 ?

**Comment by pelikhan** [comment]
Most likely. Will look into it after seeing a whale.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
Not enough information to reproduce the issue. Closing.
