### ISSUE TITLE
"Download Screenshot" broken in Edge

### ISSUE THREAD

**Issue by cait1inhennessy** [Microsoft/pxt#2572]
**Test environment**
Edge 40.15063.0.0 running on Windows 10

**Steps to reproduce**
- Navigate to any MakeCode editor, e.g., https://makecode.microbit.org/
- Right click in the editor and select "Download Screenshot"

**Actual result**
Screenshot is not downloaded

**Expected result**
Screenshot is downloaded

**Comment by abchatra** [comment]
Moved https://github.com/Microsoft/pxt-microbit/issues/912
