### ISSUE TITLE
When deleting a block in the editor by doing drap-drop, the Tash icon does not appear

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt#2577]
**Environment**

Windows 10 Creator Update
Microsoft Edge 40.15063.0.0
[https://makecode.microbit.org/beta](https://makecode.microbit.org/beta)

**Reproduce**

- Open [https://makecode.microbit.org/beta](https://makecode.microbit.org/beta)
- Take a block in the block editor (forever for example)
- Drag it to the toolbox to delete it.

**Expected result**

A large Trash icon must appear in the toolbox to significate that the block will be deleted.

**Actual result**

On MS Edge only, the trash does not appear.

**Comment by microsoftsam** [comment]
Could you please check if this still repros? @veler

**Comment by microsoftsam** [comment]
Fixed. please re-open if you are still repro'ing
