### ISSUE TITLE
Toolbox hides menu items in JavaScript mode

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#2582]
See the picture below. The toolbox hides the left most part of the menu items. This happens to the translated languages which the toolbox width changes if "Advanced" is open.

Try as follows:
1. Change the language to Japanese or Sinhala.
1. Click "Advanced" to open it.
1. Click "Basic" or any other toolbox item.

![image](https://user-images.githubusercontent.com/485416/28752239-696d4fe4-7555-11e7-85f8-3c79a7191a1c.png)

**Comment by microsoftsam** [comment]
Fixed in /beta
