### ISSUE TITLE
Remove unused / disabled commands from the all command list

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#259]
Folding is disabled. 
![image](https://cloud.githubusercontent.com/assets/16690124/17988735/05e6192a-6add-11e6-8aac-7ed830957078.png)

Note: I believe this is a bug on the monaco editor

**Comment by microsoftsam** [comment]
Microsoft/monaco-editor#135

**Comment by abchatra** [comment]
@microsoftsam Is this still a issue? How do I repro this?

**Comment by microsoftsam** [comment]
Yes it still is, and will be until we update Monaco.

F1 or right click and hit "Command Pallets" in the JavaScript editor, you'll find folding commands and a bunch of other commands that are disabled features, but are in the list.

________________________________

**Comment by microsoftsam** [comment]
Won't fix.
