### ISSUE TITLE
The icons "Edit" and "Play" couldn't work in document "JavaScript"->"Sequencing"

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2599]
Repro steps:
• Navigate to https://makecode.microbit.org/
• Click "JavaScript" under "?"
• Click the "Sequencing"
• Click the icons "Edit" and "Play"

Expected result:
The icon "Edit" can work and the vide can be loaded when click the icon "Play"
Actual result:
The icon "Edit" couldn't work and the video couldn't be loaded when click the icon "Play"

![edit](https://user-images.githubusercontent.com/11880996/28814775-89d29500-76d1-11e7-886d-a538f4cc28c5.gif)

**Comment by Helen09** [comment]
I have moved this issue to https://github.com/Microsoft/pxt-microbit/issues
Please help close it.
