### ISSUE TITLE
support for break / continue in blocks

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#260]
[uservoice](https://touchdevelop.uservoice.com/forums/402381-code-the-micro-
bit/suggestions/15725448-add-the-ability-to-break-from-for-loops)

- [ ] add "break" and "continue" block under loops
- [ ] support blocks -> JS conversion
- [ ] support JS -> blocks conversion
- [ ] add help pages

**Comment by tballmsft** [comment]
It is not clear to me that this is an improvement. I'd like to have a discussion around criteria for what sort of language constructs we support in blocks. Before we do this stuff, I'd like to discuss simple functions.

**Comment by abchatra** [comment]
I don't see lot of value in this either. This seems to be similar to ask for functions in blocks. I am closing this for now as we don't have any immediate plan.
