### ISSUE TITLE
The corresponding simulator of Projects "infection" loads blank on Edge & IE

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2601]
**Repro step:**
- Navigate to [https://makecode.microbit.org/projects/infection](url)
- Click the button "_Start the simulator_" at the bottom right corner of "_JavaScript code_" on this page.

**Expected result:**
![chrome_firefox](https://user-images.githubusercontent.com/17866936/28815299-7cf918ac-76d3-11e7-9b6e-c86dc2d1dfac.gif)

**Actual result:**
![edge_ie](https://user-images.githubusercontent.com/17866936/28815334-999dae00-76d3-11e7-82bb-72920177c9d7.gif)

**Comment by joannazheng** [comment]
This issue still repro with on Edge, but when clicking the "Start the simulator" button on the bottom, page jumps to the next project 'Fireflies' directly.

**Comment by Helen09** [comment]
This page can't show completely on IE and the "Edit" button and "Run" button can't be clicked
![issue1](https://user-images.githubusercontent.com/23466737/38916448-f995e690-42d6-11e8-8245-a216482a3eed.PNG)
