### ISSUE TITLE
The file name couldn't be display in the edit box after selecting one .hex file when importing file

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2603]
Repro steps:
• Navigate to https://makecode.microbit.org/ on Safari & Chrome(not repro on FireFox, Edge and IE)
• Click "Projects" in the Menu bar
• Click the "Import File..."
• Select one .hex file to open

Expected result:
The file name can be display in the edit box after selecting one .hex file, just like display in browser FireFox
Actual result:
The file name couldn't be display in the edit box if the mouse doesn't move to the edit box after selecting one .hex file

Safari:
![safari](https://user-images.githubusercontent.com/11880996/28815490-2189c948-76d4-11e7-9ef9-a46697c8feca.gif)

FireFox:
![firefox](https://user-images.githubusercontent.com/11880996/28815431-f6d33e32-76d3-11e7-85e3-24a032151d9c.gif)

**Comment by Helen09** [comment]
Repro on Chrome 60.0.3112.101

**Comment by joannazheng** [comment]
This problem is not reproducible on Safari any more, only repro on Google Chrome on Mac - Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by abchatra** [comment]
@helen09 Can you try alpha and let me know? I will reopen if it still reproes in Alpha. This doesn't repro in windows.

**Comment by Helen09** [comment]
@abchatra I verified this issue and it doesn't repro in Alpha both on Mac&Windows
