### ISSUE TITLE
Music tempo block has no argument in dutch

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2617]
The argument is missing in dutch and the argument is silently deleted when switching back to blocks from javascript

![dutch set tempo](https://user-images.githubusercontent.com/147113/28851345-c37c89e4-7719-11e7-8079-3ce1d5bf853b.gif)

**Comment by ChrisDorna** [comment]
The same hapens with the **_digital write pin_** block

**Comment by pelikhan** [comment]
Fixed the issues in crowdin. Will add checks in MakeCode to avoid loading those.

**Comment by pelikhan** [comment]
Detecting and ignoring invalid loc strings: https://github.com/Microsoft/pxt/pull/2640

**Comment by abchatra** [comment]
This is fixed
