### ISSUE TITLE
investigate flashing with debug interface

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#263]
it could possibly be faster with just flashing the code section

**Comment by mmoskal** [comment]
pyOCD puts flashing program in RAM and executes it. We could probably do the same.

**Comment by mmoskal** [comment]
This now works, on localhost with ?quickflash flag (don't forget npm install)

Needs some testing

**Comment by abchatra** [comment]
@mmoskal Is this work completed?

**Comment by mmoskal** [comment]
nope
