### ISSUE TITLE
"Projects" links have different meanings

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2630]
Clicking "Projects" in the top-left opens "My Stuff". From there, clicking "Projects" in the top-left opens the list of worksheets. So the same label in the same area does two different things. ("Projects" in the "?" menu opens the list of worksheets, in the help tab.)

![projects1](https://user-images.githubusercontent.com/5677614/28873875-4c974904-7787-11e7-99e7-a1335516555a.png)
![projects2](https://user-images.githubusercontent.com/5677614/28873878-4e52f90a-7787-11e7-80aa-d04b917d3216.png)

**Comment by HelenFoster** [comment]
The word "Projects" is used for worksheets in a lot of places, so the single one that goes to "My Stuff" would be much simpler to change. Could just change that one to say "My Stuff". It's then not obvious that we can get to the worksheets that way, but since there are two other ways to get to them from the editor page, that might not matter.

**Comment by Jaqster** [comment]
Thanks for the feedback Helen.  We're looking into this, but won't be able to make UI changes to micro:bit until next summer.
