### ISSUE TITLE
[Screen Reader - Makecode - Microbit Simulator] Narrator focus is not synchronized with keyboard focus after selecting 'Enter full screen' button.

### ISSUE THREAD

**Issue by v-mesala** [Microsoft/pxt#2631]
**User Experience:**
If Narrator focus is not synchronized with keyboard focus after selecting 'Enter full screen' button then user with visual disabilities might confuse whether the action is performed or not.
page in item mode and verify the issue.

**Test Environment:**
OS: RS2 Version 1703(OS Build 15063.2)
Platform: Edge.

**Repro Steps:-**
1-Navigate to url:- https://makecode.com/
2-Navigate to the Microbit section element and select Code control given on it.
3-Navigate to the Simulator tool bar and select Enter full screen button.
4-Verify that narrator focus and keyboard focus is synchronized.

**Actual Result:-**
Narrator focus is not synchronized with keyboard focus after selecting 'Enter full screen' button.

**Expected Result:-**
Narrator focus should synchronize with keyboard focus after selecting 'Enter full screen' button.

**MAS Reference -**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b24201d1-2276-4471-8183-e1e5353031ad}&action=default

**Refer Attachment**
[MAS 4.2.10_MakeCode_Narrator focus synchronize.zip](https://github.com/Microsoft/pxt/files/1193814/MAS.4.2.10_MakeCode_Narrator.focus.synchronize.zip)

**Comment by veler** [comment]
External issue with Narrator and react interacting together. Narrator issue, can't fix.

**Comment by abchatra** [comment]
This is an external bug with Narrator. Closing
