### ISSUE TITLE
Type definition in object literal does not work

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#2634]
microbit.org-ticket: 2416

We can have object literals:

```typescript
let foo = {
    bar: "hello",
    xxx: "world!"
}
serial.writeString(foo.bar + " " + foo.xxx + "\n");
```

But if we want to specify type it doesn't work:

```typescript
let foo: { [key: string]: string } = {
    bar: "hello",
    xxx: "world!"
}
serial.writeString(foo.bar + " " + foo.xxx + "\n");
```

Or if we try to set it via an previously declared interface:

```typescript
interface Fooface { [key: string]: string }

let foo: Fooface = {
    bar: "hello",
    xxx: "world!"
}

serial.writeString(foo.bar + " " + foo.xxx + "\n");
```

With the error indicating that the properties do not exists:

![image](https://user-images.githubusercontent.com/29712657/28883445-663c072c-77a6-11e7-8ce5-542ece5c64f8.png)

Is this type declaration unsupported? Is there a way to declare the property types for an object?

**Comment by abchatra** [comment]
This is not supported yet.

**Comment by microbit-carlos** [comment]
Thanks for the quick response @abchatra. I noticed you said "yet",  so it is in the roadmap?

**Comment by riknoll** [comment]
No, I don't think it is. Static Typescript (the subset of Typescript that we support) does not allow computed property accesses. Right @tballmsft? We should definitely throw an error on that declaration.

**Comment by pelikhan** [comment]
@tballmsft ping

**Comment by pelikhan** [comment]
@mmoskal ping

**Comment by mmoskal** [comment]
Probably won't be supported unless there's a good reason.

**Comment by pelikhan** [comment]
It's quite common in JavaScript to use objects as hashtables to do lookups and stuff.

**Comment by abchatra** [comment]
Closing old issues
