### ISSUE TITLE
Changing a text comparison after JS usage crashes MakeCode and browser tab, appears to destroy code

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2637]
The following sequence of events crashes MakeCode on both Safari and Chrome.

1) Create a variable, set the contents to some text
2) Drag in an 'if' block and then a "0 == 0" block
3) Drag the variable into one of the comparison slots
4) Drag some text into the other slot
5) Switch to JS, edit the text for comparison
6) Switch back to blocks
7) Remove the variable from the comparison
... The browser will hang for a little bit - Safari shoes a beach ball and becomes unresponsive. After some time, the blocks get scattered over the canvas with some missing.
... Chrome shows the "this tab has stopped responding" dialogue

On reloading the browser, the code is restored to the previous state (IE before the crash).

I notice that the 'text' inside the comparison changes colour slightly after returning to blocks, and isn't a block itself anymore, perhaps this is part of the problem?

Here's a short example of the failure in Safari:
(in these examples the sudden jump where blocks disappear is not an artefact, it's the real thing!)
![text break safari very short](https://user-images.githubusercontent.com/147113/28887814-6c80575e-77b6-11e7-8067-973efd97a714.gif)
And a similar case in Chrome:
![text break chrome very short](https://user-images.githubusercontent.com/147113/28887823-72a0ea68-77b6-11e7-9a39-f189ed33901d.gif)

And here's a complete repro from scratch (LICECap doesn't seem to capture the beachball, so this is a bit uneventful, but you can see that things aren't responding)
![text confusion safari](https://user-images.githubusercontent.com/147113/28888009-0089a536-77b7-11e7-8536-f23966d1be5f.gif)

**Comment by riknoll** [comment]
This is an upstream blockly bug, but we should change the decompiler so that we don't hit it

**Comment by riknoll** [comment]
This is fixed in master but needs to be cherry-picked to V0
