### ISSUE TITLE
String comparisons are hard to discover/use

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2638]
If a user wants to check a variable containing a string matches another string (a common case after, say, "Radio send string" or receiving over serial), it's quite hard to work out how to do it.

Inside the 'Text' category there's a string compare block, but that will do almost the opposite of what people expect, because for two identical strings it returns 0, not a boolean operation (I understand this is basically strcmp, but that's not ideal for kids!)

If you instead try to use the normal comparison operators in "Logic" (which seems sane, given that's how you do all the other comparison stuff) you *can* make it work but only if you perform a very specific set of actions in the right order.

Here's a gif of me playing with some things that sort of make sense but don't work as expected... (a lot of the first half comes down to "0 should be false, not true"
The second half shows using a variable to trick the block into accepting strings. But if you put the string in before the variable it refuses.

![string comparison](https://user-images.githubusercontent.com/147113/28888678-6ca89b6c-77b9-11e7-839a-3ef47194a711.gif)

![string compare order](https://user-images.githubusercontent.com/147113/28888682-6f1f4ae4-77b9-11e7-9553-a3686b4f6178.gif)

Some possible suggestions: Include a string-like comparison inside "Logic", include a comparison block more like the logic ones inside "Text"

See also #2637 for a bug relating to switching to/from JS with this kind of problem

**Comment by rharbird** [comment]
I'm supporting this enhancement. We've had problems with this too.

Rae
