### ISSUE TITLE
[Accessibility] Keep in the cookies whether the High Contrast is enabled or not.

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt#2639]
There is no reason why a user who enable the high contrast mode would leave it the next time he connects to the website. We could use a cookie to save the user's preferences.

**Comment by abchatra** [comment]
Multiple students use the same computer in the school. I wouldn't save high contrast setting as a cookie unless we have more data. Good idea though. Only thing we save in the cookie today is language setting which is unlikely to change in the schools.
