### ISSUE TITLE
Uncaught TypeError: Cannot read property 'typescriptDefaults' of undefined

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#266]
There is a race on startup when Monaco gets loaded.

![image](https://cloud.githubusercontent.com/assets/4175913/18018047/97d68aca-6b89-11e6-80fd-e86207bd1edf.png)

**Comment by microsoftsam** [comment]
Fixed by 0b83034977983b5cb08f33e3bdd109d9df9630c2
