### ISSUE TITLE
Some blocks help breaks in Firefox

### ISSUE THREAD

**Issue by carlosperate** [Microsoft/pxt#2661]
I'm not quite sure if this happens only with specific blocks, or if there are any other factors. On Firefox (tested v54 on Windows 10), the bluetooth advertise UID help doesn't work, and it breaks the help sidebar for all other blocks as well:

![makecode gif](https://user-images.githubusercontent.com/4189262/28995220-534d1ffc-79db-11e7-9346-08086d0a938c.gif)

**Comment by abchatra** [comment]
First time you try to load, it takes a long time to download the help documentation. In alpha we have a donut showing it is working. I am closing this bug as wont' fix.

**Comment by microbit-carlos** [comment]
@abchatra this is still an issue in alpha that can be replicated by following the steps shown in the GIF. Doesn't matter how much you wait it gets stuck like this:

![image](https://user-images.githubusercontent.com/4189262/42274127-74db4ff0-7f83-11e8-92d6-a94836245272.png)

Firefox 60.2
makecode.microbit.org version:  1.1.32
Microsoft MakeCode version:  3.20.11

**Comment by abchatra** [comment]
I can't repro this in firefox 60.2. Are you able to reach this URL https://makecode.microbit.org/reference/bluetooth/advertise-uid?

**Comment by microbit-carlos** [comment]
Yes, I can reach that URL without problems.
The original issue was opened using Firefox 54 in Windows 10, and I can still reproduce in Firefox 60 in macOS.

I've created this video that shows a bit more info (it was too large for a gif): [makecode_help.zip](https://github.com/Microsoft/pxt/files/2167601/makecode_help.zip)

**Comment by abchatra** [comment]
Is this on Mac?

**Comment by abchatra** [comment]
Moved https://github.com/Microsoft/pxt-microbit/issues/924

**Comment by microbit-carlos** [comment]
Thanks @abchatra!
