### ISSUE TITLE
MakeCode and DAL don't agree about offset of images and clearing 'undefined' areas

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2673]
See also https://github.com/lancaster-university/microbit-dal/issues/307

In the DAL, when printing an image with an offset, such that the contents of some area of the screen are not defined, the DAL uses the *previous* contents of the display for that areas.

In the simulator, images appear to be 'zero padded' and when an image is shown with an offset the display appears to be cleared for undefined areas.

@finneyj up to you to declare what's "correct" here and then we can agree to fix DAL or simulator.

So, for example the following program behaves differently on simulator to the micro:bit

On simulator it looks like this:
![image offsets](https://user-images.githubusercontent.com/147113/29068558-33576a9e-7c2f-11e7-96bc-93d2bdbf05c0.gif)

The micro:bit does this:
![image offsets microbit](https://user-images.githubusercontent.com/147113/29068559-36149a40-7c2f-11e7-958a-4f10167a0dc0.gif)

**Comment by jaustin** [comment]
@abchatra what info do you need on this one?

**Comment by abchatra** [comment]
Wherther to fix in dal or pxt

**Comment by finneyj** [comment]
@jaustin @abchatra 

Thanks guys. I think i'd go with the dal implementation, as we built this behaviour in by design. The idea being that people can create sprite overlays and such like - which would be impossible if the screen autocleared (but the programmer could easily explicitly call clear() if that's the behaviour they wanted).

**Comment by jaustin** [comment]
@abchatra  Do we need to migrate this to pxt-microbit?

**Comment by abchatra** [comment]
Yes that would be great.

**Comment by abchatra** [comment]
Please move it to v0 if not done already.
