### ISSUE TITLE
Emulator infinite loop in fibre is non-blocking

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#2674]
When there is an infinite loop in a micro:bit fibre it blocks execution of other fibres/events, however this does not happen in the emulator, so there is a discrepancy between what the user sees on the emulator vs the device.

**Example program:**
https://makecode.microbit.org/_FsfTuH8DWXLM
![microbit-screenshot](https://user-images.githubusercontent.com/29712657/29069998-1d29cf9a-7c35-11e7-9ad3-cdc929c43b03.png)

**Expected Behavior:**
Emulator and micro:bit behaving the same way.

**Actual Behavior:**
Emulator: Pressing the button momentarily shows the smiley face.
micro:bit: Pressing the button does nothing.

**Comment by pelikhan** [comment]
It's the maybeYield issue again. Maybe our device "while" implementation should have a maybeYield as well to prevent this kind of busy loop issues.
