### ISSUE TITLE
Tutorial mode: Hint blocks are orange not the colour they really are

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2675]
(This is feedback from a teacher)

In the tutorials mode, the suggestion from the 'hint' bar has blocks in orange
![image](https://user-images.githubusercontent.com/147113/29070342-dbcba288-7c36-11e7-8c08-352901b45f3c.png)

But we use block colour commonly to help people find them. Is there a reason the blocks in 'hint' don't look right?

**Comment by abchatra** [comment]
These strings come from the documentation. There is no blockly loaded render to get the right color. Do agree that we can do something better here.
