### ISSUE TITLE
The items in "My Stuff" of "Projects" don't include item "Import old programs" in Chrome & FireFox

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2677]
Repro steps:
• Navigate to https://makecode.microbit.org/ on Chrome & FireFox
• Click "Projects" 
• Check the items in "My Stuff"

Expected result:
The items should include item "Import old programs" just like Safari
Actual result:
The items don't include item "Import old programs" in Chrome & FireFox

Safari:
<img width="1076" alt="safari" src="https://user-images.githubusercontent.com/11880996/29102142-ae3410ae-7ce9-11e7-8059-38169ac11cc3.png">

Chrome & FireFox:
<img width="897" alt="chrome firefox" src="https://user-images.githubusercontent.com/11880996/29102170-d83f1466-7ce9-11e7-8fb0-22bd0e70d3a5.png">

**Comment by microsoftsam** [comment]
This is by design, import old programs is only needed for Safari.
