### ISSUE TITLE
Javascript failed to convert to block with no error message

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#2678]
Repro Steps:
•	Navigate to https://makecode.microbit.org/beta
•	Copy below code to {}JavaScript
let Y = 0
let X = 0
function plus() {
    X = 8
    Y = 1
    basic.showNumber(X + Y)
}
plus()
•	Switch to Blocks to see simulator, it shows correct result
•	Switch to {}JavaScript, Add “return X+Y” after basic.showNumber…
•	Switch to Blocks 
Expect Result: Javascript changes to block or there is error message when switch from javascript to block
Actual Result:
	
![1](https://user-images.githubusercontent.com/23447632/29102747-d4e3347e-7ced-11e7-97c9-1aacdfd40450.gif)

**Comment by abchatra** [comment]
This is as expected. There is no support for the return statements in the blocks (No equivalent block). You would see grey blocks in that case.
