### ISSUE TITLE
The name of file in "Downloads" is not same with the name you named and the program could not be imported successfully

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2679]
Repro steps:
• Navigate to https://makecode.microbit.org/ on Safari
• Drag some blocks to form a program
• Input one name in the "input box" to save the program
• Check the name which you named for the program in the file of "Downloads"
• Click the "Import File..." in "Projects" to import the program which you saved

Expected result:
 The name of file in "Downloads" is same with the name which you input in the "input box" (just like the Chrome gif) and the program could be imported successfully
 Actual result:
 The name of file in "Downloads" is not same with the name which you input in the "input box" and the program could not be imported successfully

Safari:
![safari-saveprograme](https://user-images.githubusercontent.com/11880996/29104106-362ffa84-7cf6-11e7-874e-8403037bd818.gif)

Chrome:
![chrome-saveprogramename](https://user-images.githubusercontent.com/11880996/29104119-4cede11e-7cf6-11e7-993f-3e579b34e28f.gif)

**Comment by microsoftsam** [comment]
What version of Safari are you using? 
Prior to Safari 10.1, Safari didn't support the download attribute, and so we were unable to indicate to the browser the name it should use for the file downloaded. http://caniuse.com/#feat=download

**Comment by yanlxu** [comment]
@microsoftsam , The version of Safari is 10.1.2(11603.3.8)
