### ISSUE TITLE
Screenshot shadows are inconsistent based on canvas location/size

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#2689]
microbit.org-ticket: 2417

When using right click-->Download Screenshot the last pixels of the rightmost block are cropped off the downloaded image. Perhaps the calculation of the canvas/image size doesn't take into account the shadow that appears to be added in the image but isn't present in the browser?

For example, look at the ends of the orange block and purple block here:

![image](https://user-images.githubusercontent.com/147113/29169150-6f76fff2-7dca-11e7-98cb-1c035bd7c448.png)

Versus here:
![image](https://user-images.githubusercontent.com/147113/29169167-853855de-7dca-11e7-96c6-0b501138ce92.png)

**Comment by microsoftsam** [comment]
Fixed in /beta
