### ISSUE TITLE
Led light shrinks when led brightness block is used in Firefox

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#2700]
Set the brightness low value. Take look at the simulator. Leds appear to be shrunk. 
![image](https://user-images.githubusercontent.com/6107272/29227257-11d52278-7e8a-11e7-90da-0b9d61e85f37.png)

**Comment by HelenFoster** [comment]
This was deliberate #2439

**Comment by abchatra** [comment]
This is not deliberate. You can see the lit up leds doesn't fit into the led positions. Look at the edges.

**Comment by HelenFoster** [comment]
Sorry, I see now. It happens for me in Firefox, but Chrome looks OK.

**Comment by microbit-mark** [comment]
Nudging this issue as it now appears to be a bug in Chrome 64. The error is not present in Chrome 63
<img width="1137" alt="screen shot 2018-01-31 at 07 03 57" src="https://user-images.githubusercontent.com/31242877/35609636-f4dd0fd8-0655-11e8-9592-3c27b792c8a4.png">

**Comment by microbit-mark** [comment]
@abchatra @samelhusseini Should this be re-prioritised and renamed as it affects more than one browser

**Comment by microbit-carlos** [comment]
This issue for Edge might be related as well: https://github.com/Microsoft/pxt/issues/3702

**Comment by samelhusseini** [comment]
Fixed in Microsoft/pxt-microbit#651
