### ISSUE TITLE
How to create original block with multi-lang

### ISSUE THREAD

**Issue by matsujirushi** [Microsoft/pxt#2707]
How to create original block with multi-lang block name?
(Do I have to pull request a core-strings.json and regist crowdin?)

Ref.
[Defining blocks](https://makecode.com/defining-blocks)
[Translate](https://makecode.com/translate)

**Comment by pelikhan** [comment]
@matsujirushi is this to add your own blocks via packages or to localize a "builtin" block that ships out of the box?

**Comment by sgk** [comment]
@pelikhan He wants to learn a method to provide international strings for his own custom blocks via packages.

**Comment by matsujirushi** [comment]
@pelikhan @sgk Yes. I want to add international strings for my custom block.

**Comment by pelikhan** [comment]
Ok, I'll beef up the docs. Meanwhile, you'll need to add localization files to the package itself just like in 
https://github.com/Microsoft/pxt-microbit/tree/master/libs/bluetooth/_locales

You need to update pxt.json to include the .json loc file and include the localized json files. Docs coming.

**Comment by matsujirushi** [comment]
@pelikhan 

I tried adding Japanese, But did not work.
1. Add _locales/ja/bluetooth-strings.json file.
```
{
  "bluetooth.startUartService|block": "bluetooth service日本語サービス",
  "{id:category}Bluetooth": "Bluetooth"
}
```

2. Update pxt.json.
3. Git push. ([here](https://github.com/matsujirushi/bluetooth))


Result:
![image](https://user-images.githubusercontent.com/8079404/29483628-4f521348-84e5-11e7-8292-a845ae7d24c1.png)

**Comment by pelikhan** [comment]
Are you trying to completely clone the Bluetooth library?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by matsujirushi** [comment]
I copied from [bluetooth](https://github.com/Microsoft/pxt-microbit/tree/master/libs/bluetooth) folder.
Please look [here](https://github.com/matsujirushi/bluetooth).

Add package from https://github.com/matsujirushi/bluetooth on MakeCode.

![image](https://user-images.githubusercontent.com/8079404/29488060-63f19900-853e-11e7-899c-bf6e3be18fc4.png)

**Comment by matsujirushi** [comment]
I can add Japanese strings. It's fine.
https://github.com/Seeed-Studio/pxt-grove

Thank you.
