### ISSUE TITLE
The pull-down bar can't be dragged sometimes

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2713]
**Repro Steps:**
•   Navigate to https://makecode.microbit.org/beta
•   Zoom out the window then drag the pull-down bar on content pane

**Expect Result:** 
The pull-down bar should be dragged smoothly
**Actual Result:**
The pull-down bar can't be dragged sometimes
![aug-15-2017 10-25-40](https://user-images.githubusercontent.com/23466737/29299980-0fb7a8da-81a5-11e7-9984-aa8e95db12ae.gif)

**Comment by microsoftsam** [comment]
Can't repro. What OS / Browser is this on?

**Comment by Helen09** [comment]
It repros on every browser and it needs to zoom out the browser firstly.

**Comment by Helen09** [comment]
Closed as not repro
