### ISSUE TITLE
Versioned upgrades

### ISSUE THREAD

**Issue by cait1inhennessy** [Microsoft/pxt#2742]
- [ ] Versioned upgrades
- [ ] Based on script target version, select and apply upgrades
- [ ] Handle missing target version scenario
- [ ] Logging and analytics

**Comment by abchatra** [comment]
@caitlin-hennessy I don't understand this issue. Can you add more information? What is the scenario?

**Comment by pelikhan** [comment]
Changing the photon setPhotonColor semantics is a breaking change, so we need version specific patches to handle it.

**Comment by abchatra** [comment]
This editor is still in beta. It is ok to make breaking changes.

**Comment by pelikhan** [comment]
We need to ensure that none of the resources posted on learn.adafruit.com get broken

**Comment by abchatra** [comment]
I see old API being used in https://learn.adafruit.com/makecode/blinky?view=all 
I agree with Peli we need to be careful not to break them.

**Comment by pelikhan** [comment]
I can patch that one once the fix is in circulation.
