### ISSUE TITLE
How to integrated into my expressjs project

### ISSUE THREAD

**Issue by LuHugo** [Microsoft/pxt#2746]
I had a blockly project and just want to use pxt editor feature (like code decompile to blockly). but don't know how to do this?

**Comment by LuHugo** [comment]
How to split the blockly editor from pxt ？

**Comment by pelikhan** [comment]
I'm afraid it is not designed to be split currently.

**Comment by abchatra** [comment]
PXT is not designed for this scenario. Feel free to fork and extra what you need. Also let us know how easy\hard it was.
