### ISSUE TITLE
Not found project files

### ISSUE THREAD

**Issue by LuHugo** [Microsoft/pxt#2747]
I specify the hostname(IP Address) in built/server.js file, then create a project on my target, but in my target projects folder not found any file, where are my project files in ?

**Comment by LuHugo** [comment]
1.In my instance of PXT to specify the  serveOptions.hostname to 192.168.1.107 (default is localhost) in built/server.js 
2.then my target(pxt-sample) link to PXT instance and run serve.
3. visiting my target in the browser and create new project will be success.
4. then open pxt-sample/projects folder and not found any file. 

I  want to change the hostname,but looks like something wrong.
can change the serve options in the pxt config file or other ways?

**Comment by pelikhan** [comment]
" pxt serve"command has options to specify the host name.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LuHugo** [comment]
"pxt serve -h" is working, but in  pxt-sample/projects folder still not found any project file. No main.ts, No main.blocks……
Project file is auto save in other dir or Localstorage?

**Comment by pelikhan** [comment]
Saving to the file system only works on the localhost IP. If you change the host, it uses local storage. Note that “pxt serve” is designed for a local / single dev box scenario, not a web server.

**Comment by LuHugo** [comment]
Thank you for your answer!
