### ISSUE TITLE
Game engine interferes with its own animations

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2748]
Related to https://github.com/Microsoft/pxt-microbit/pull/476 . The animations are showing with low brightness. (Previously, using addScore during a game just flashed the screen briefly, and I didn't realise that wasn't right at the time.)

```
let item = game.createSprite(2, 2)
basic.pause(1000)
game.addScore(1)
basic.pause(1000)
game.startCountdown(10000)

```

**Comment by abchatra** [comment]
If this still exists let me know. I will reopen in pxt-microbit repo.
