### ISSUE TITLE
Flooding the server with requests when gallery page is not found

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#2756]
When one of the gallery pages is not found "Projects", "Examples" in docs. We flood the server with requests, and don't stop causing a large number of failures on the backend. 

<img width="736" alt="screen shot 2017-08-18 at 11 42 17 pm" src="https://user-images.githubusercontent.com/16690124/29484231-189f0b38-846f-11e7-997e-ad2ccc45718d.png">

Marking as P2 as workaround is to resolve the docs issue. Either remove gallery item, or add docs page.

**Comment by pelikhan** [comment]
What's the frequency of requests here?

**Comment by pelikhan** [comment]
``pxt checkdocs`` should validate galleries and fail if needed

**Comment by pelikhan** [comment]
We do check for broken gallery pages.
