### ISSUE TITLE
don't leave {} on same line 

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#276]
I create on-button-pressed event handler block and convert to TS to get:

![image](https://cloud.githubusercontent.com/assets/10767146/18107409/a0dd9dd0-6ebc-11e6-9513-b888cc83a7a4.png)

IMHO, we should never allow { } on the same line unless the user explicitly edits it that way.

**Comment by pelikhan** [comment]
This fix breaks the formatting tests.

    cd libs/format-test; node ../../built/pxt.js format -t

**Comment by mmoskal** [comment]
It blows up code quite a bit. I also think this should be limited to insertion.
