### ISSUE TITLE
 The purple squares are so large in project "Hot and Cold" 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2771]
**Repro Steps:**
• Navigate to https://makecode.microbit.org/beta
• Open Projects -> Projrcts -> Hot or Cold

**Expect Result:**
The purple squares should be more small
**Actual Result:**
 The purple squares are so large 
![1](https://user-images.githubusercontent.com/23466737/29550459-6ce7da84-8740-11e7-8a04-cc62970bf6a2.gif)

**Comment by microsoftsam** [comment]
span.docs.inlinebutton should have a padding 0.2rem 0.4rem.

**Comment by Helen09** [comment]
close as fixed
