### ISSUE TITLE
Pull-down bar disappears after clicking on projects page 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2772]
**Repro Steps:**
• Navigate to https://makecode.microbit.org/beta
• Click Getting Started -> Until the seventh step -> click Finish -> More Tutorials
• Click on the Projects choice page as below .gif

**Expect Result:**
 The pull-down bar should not disappear
**Actual Result:**
 The pull-down bar disappears and when enter this page again form Getting Started, the pull-down bar still disappears
![2](https://user-images.githubusercontent.com/23466737/29551242-678e506e-8744-11e7-88c6-1ee61e2fc0d2.gif)

**Comment by microsoftsam** [comment]
Can't repro anymore. Possibly fixed by a bunch of recent changes to the scrolling logic. Please re-open if you can repro, and please indicate what browser and OS you're seeing this on.

**Comment by microsoftsam** [comment]
Misread the repro steps. I can repro now. Thanks
