### ISSUE TITLE
Dowload Screen Shot - MakeCode - Block shows black LEDs

### ISSUE THREAD

**Issue by microbit-pauline** [Microsoft/pxt#2775]
Micro:bit support ticket 2513 - https://support.microbit.org/helpdesk/tickets/2513

**When I download a screenshot the leds in the block show leds are black instead of red.**

![black leds](https://user-images.githubusercontent.com/29146842/29570519-97f0f81a-874e-11e7-9422-8e3f22e3d539.png)

Is this something that can be corrected?

**Comment by ChrisDorna** [comment]
Problem seems to be solved!

**Comment by microsoftsam** [comment]
Yep, fixed in latest.
