### ISSUE TITLE
Help resource for function is missing/broken

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#2787]
microbit.org-ticket:2564

When right clicking on function block and selecting 'Help' you are taken to https://makecode.microbit.org/types/function/define which displays a page missing error

![pxt link](https://user-images.githubusercontent.com/31242877/29613352-86941d18-87fd-11e7-94de-9bdb1b27ee6e.gif)

**Comment by ganicke** [comment]
Ah, this needs a pick from ``master`` into ``v0`` with https://github.com/Microsoft/pxt/pull/2614.

**Comment by ganicke** [comment]
Function docs added in #2814.
