### ISSUE TITLE
SIgnal strength is always 0

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#2788]
microbit.org-ticket: 1789

Using the `devices`/`signal strength` block always returns the same value. For a program like the one below, where an android phone is correctly paired and connected (the buttons do trigger the other actions), no matter how far away the phone is, the value displayed is always 0.

![microbit-screenshot](https://user-images.githubusercontent.com/29712657/29621840-c10c61e6-8819-11e7-8806-fa5bb0ca7c61.png)

https://makecode.microbit.org/_5ct5tUWa68rY

**Comment by microsoftsam** [comment]
@pelikhan any ideas?

**Comment by pelikhan** [comment]
``signal strength`` applies to the connected phone signal strength. It must be sent by the connected device.

**Comment by microbit-carlos** [comment]
Thanks Peli, are there any known issues why the devices do not send the correct signal strength?

Also it might be nice to clarify in the documentation which signal it represents, as it can be easily mistaken by BT signal strength, I could prepare a very simple PR.

**Comment by pelikhan** [comment]
Which app are you using? You should ask the author of that app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
