### ISSUE TITLE
Blank link and white space in makecode's blog

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt#2789]
On the [blog](https://makecode.com/blog), there is a blank clickable link.

Also I think that the "Published by Microsoft" should stay at the bottom of the screen and the side bar must  be dark until the bottom of the page.

![capture](https://user-images.githubusercontent.com/3747805/29625259-11ff2abe-87e0-11e7-9b9c-30c00f885c6a.PNG)

**Comment by microsoftsam** [comment]
Want to look into this @veler. I can't repro the clickable link, but I agree it should be black all the way. I'm okay with the published by Microsoft being at the bottom of the sidebar list (wherever that ends). There's already a Powered by Microsoft, and Microsoft at the bottom of the page anyway.

**Comment by veler** [comment]
Alright I will take a look
