### ISSUE TITLE
generate strings.json from API signatures

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#28]
To complete the localization story, we need to:

- [x] extract all commands from the various shim definition files in a target (Michal)
- [x] generate a "strings.json" file that can be localized (Michal)
- [x] package the localized "strings.json" file tree produced by the localization tool (Peli)
- [x] load target specific strings into the web editor (Peli)

**Comment by mmoskal** [comment]
@pelikhan you could take a look at reference.md generation and use the same logic?
