### ISSUE TITLE
bad target identifier compiler bug

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#2819]
"bad target identifier" error when using object destructuring and you rename the field being used.

Repro: 
1. Add an onDataReceived block from the microbit editor 
2. Click on the receivedNumber field and change it to use item instead

Error occurs.

According to @riknoll this is a compiler bug.

**Comment by abchatra** [comment]
Can you share the program? I don't understand _change it to use item_

**Comment by microsoftsam** [comment]
use the dropdown to change the variable being used from receivedNumber to item.

**Comment by microsoftsam** [comment]
Can't seem to repro anymore.
