### ISSUE TITLE
Decompilation issue when converting Game.LedSprite back to blocks

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#283]
Open Javascript Editor and type: 
let item: game.LedSprite = null
input.onButtonPressed(Button.A, () => {
    item = game.createSprite(2, 2)
})

This is the same as: 
![image](https://cloud.githubusercontent.com/assets/16690124/18149896/04ab57e0-6f98-11e6-99bb-b6ba19d755f8.png)

However when converting back to blocks, it fails to convert.

**Comment by tballmsft** [comment]
@microsoftsam - assign any issues with Blocks -> TS and TS -> BLocks to @riknoll - thanks.
