### ISSUE TITLE
The contents are out of border after click the "play icon" that provided in "Hint"

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2835]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Click "_?_" and choose "_JavaScript_"
- Click "_Sequencing_" and scroll down to "_Hint_"
- Click "_play icon_" provided in Hint

**Expected result:**
All content should be within the given border.

**Actual result:**
<img width="345" alt="screen shot 2017-08-29 at 5 11 21 pm" src="https://user-images.githubusercontent.com/17866936/29813613-235b4f70-8cdd-11e7-8658-1fb4a3e2287d.png">

**Comment by abchatra** [comment]
I can repro on edge

**Comment by Emma-sunny** [comment]
The same issue still exists on other page. When navigating to the document of "Serial", the content of Hint also are out of border.Details are as following:
["?"-->"Hardware"-->"Serial communication"]
![outofborder](https://user-images.githubusercontent.com/17866936/34708209-797c6706-f509-11e7-8674-4b2294d9d58d.PNG)

**Comment by Helen09** [comment]
The first issue is not repro, the second issue still repro on Edge, chrome, IE
![7](https://user-images.githubusercontent.com/23466737/37320884-c03ef61e-266d-11e8-8a9f-7f9d2f9ffb64.PNG)
New issue: "?"->"Hardware" (Edge, chrome&IE)
![6](https://user-images.githubusercontent.com/23466737/37320918-f7b9dca8-266d-11e8-9910-efd4e08daf3e.PNG)
