### ISSUE TITLE
There are some inconsistent fonts.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2836]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Click "_?_" and select "_Statements_"
- Scroll down to the "_Labelling statements_"

**Expected result:**
"Labelled statement" should be written as "**Labelled** statement"
<img width="324" alt="screen shot 2017-08-29 at 5 17 27 pm" src="https://user-images.githubusercontent.com/17866936/29813869-fb4324bc-8cdd-11e7-938c-a73f5809d93c.png">

**Actual result:**
"Labelled statement" doesn't be written as "**Labelled** statement"
<img width="330" alt="screen shot 2017-08-29 at 5 18 14 pm" src="https://user-images.githubusercontent.com/17866936/29813904-158733a4-8cde-11e7-95a0-4e7f908774e5.png">

**Comment by Emma-sunny** [comment]
Compare with other statements, "Labelled" isn't keyword. It represent a kind of labeled although it is not used directly in code. So I thought that the "Labelled statement " should be written as "**Labelled** statement".

**Comment by ganicke** [comment]
'Labelled' is not the actual literal so that's why it wasn't styled the same as the others. I agree, it looks odd and presents a consistency problem. Fixed in #2827.
