### ISSUE TITLE
'score' blocks can cause the BBC micro:bit hardware to freeze

### ISSUE THREAD

**Issue by microbit-rosslowe** [Microsoft/pxt#2837]
The 'game->score' blocks can cause the BBC micro:bit hardware to freeze sometimes. However, this doesn't occur if there is a 'pause' following the block - if there is a short delay (e.g. 100ms), the device still freezes, but a longer pause (e.g. 500ms) stops the device from freezing and allows the code to run as per usual.

Minimum example to replicate: https://makecode.microbit.org/_EPXFp6K4bJ3X

![29820180-85b24092-8cbb-11e7-8c78-b2b0d456e1b4](https://user-images.githubusercontent.com/30410608/29827754-bf9a8a14-8cd2-11e7-864b-1f3e4cd4877f.png)

For context: https://github.com/microbit-foundation/microbit-support/issues/24

**Comment by microbit-mark** [comment]
Any update on this one @abchatra ?

**Comment by abchatra** [comment]
@pelikhan  any clue what might be the issue here?

**Comment by abchatra** [comment]
We have moved OnStart before forever in the latest bits. I am not sure if that helps here.

**Comment by microbit-carlos** [comment]
The issue occurs with the "change score by" block, which is running on the "forever" loop already, when OnStart has finished running already.

**Comment by abchatra** [comment]
This is fixed.
