### ISSUE TITLE
Press and hold buttons (A/B) fails in simulator when using servo

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#2848]
When using the servo block, press and hold in the simulator results in the '~0' value being selected rather than the button being pressed. This also happens elsewhere in that part of the editor window.

![makecode](https://user-images.githubusercontent.com/31242877/29926738-35d22356-8e5c-11e7-9cee-4c7a2ede21b7.gif)

Tested in chrome on 
Samsung Galaxy Tab S2  SM-T713  Android OS 7.0
Samsung Tab 4   SM-T230    Android  4.4.2
Samsung Galaxy S5  PHONE SM-G900F

**Comment by abchatra** [comment]
@microsoftsam can you take a peek?

**Comment by microsoftsam** [comment]
Just like we don't support breadboarding in the mobile view, we shouldn't really support servo. The issue you see here is because Blockly is stealing all the touch events, the microbit should use the bottom section dedicated to it only, and not bleed out into the editor.

**Comment by abchatra** [comment]
I am closing this in favor of redesigning the tablet and mobile simulator view. We have that on the backlog.
