### ISSUE TITLE
Get brightness

### ISSUE THREAD

**Issue by ZanderBrown** [Microsoft/pxt#2849]
There is a function to set the brightness of an LED:
`led.plotBrightness(x, y, b)` / `plot [x] [y] brightness [b]`

However there isn't a function to retrieve that value:
`led.getBrightness(x, y)` / `get brightness [x] [y]`

**Comment by samelhusseini** [comment]
Transferred to pxt-microbit: https://github.com/Microsoft/pxt-microbit/issues/742
