### ISSUE TITLE
ButtonEvent.DoubleClick and ButtonEvent.Hold issues on Adafruit.

### ISSUE THREAD

**Issue by sheamusburns** [Microsoft/pxt#2855]
`ButtonEvent.DoubleClick` works in sim, but not when downloaded to the Circuit Playground Express. 
`ButtonEvent.Hold` does not work in sim, and only fires once after running on actual CPE. If you try to hold the button a second time, event does not fire. 

I'm not sure if these bugs are supposed to go here or on the pxt-adafruit repository. I've put them in both for now.

**Comment by abchatra** [comment]
Dupe https://github.com/Microsoft/pxt-adafruit/issues/311
