### ISSUE TITLE
Slow-mo executes basic.forever as soon as it's declared

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#2856]
microbit.org-ticket: 2622

When the slow-mo option is used, the code inside the anonymous function argument for things like `basic.forever()` is executed as soon as it is declared. So in cases where we have variables initialised in the "on start" block, they will be undefined at that point and cause a `Program Error: r.isRef is not a function` error.

The program below is a simple example illustrating this issue:

```typescript
let dot: game.LedSprite = null
basic.forever(() => {
    dot.move(1)
})
dot = game.createSprite(0, 0)
```

![microbit-screenshot](https://user-images.githubusercontent.com/29712657/30002207-5048d374-909b-11e7-8266-a5a52cdea1c7.png)

https://makecode.microbit.org/_cyRWqFU6Jbmp

**Comment by abchatra** [comment]
@riknoll interesting bug. Looks like slow-mo is changing the execution order.

**Comment by riknoll** [comment]
Totally possible. We might need to revisit how we instrument the code. Right now it just inserts pauses at breakpoints

**Comment by abchatra** [comment]
@riknoll this is fixed right. Resolved.
