### ISSUE TITLE
It doesn't support "i--" in "for" loop.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2858]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Create a new project and switch to "_{}JavaScript_"
- Copy the following code to content panel:

```
    basic.forever(()=>{
       for(let i=4;i>=0;i--){
           for(let k=0;k<=4;k++){
               led.plot(i,k);
               basic.pause(2000);
           }
       }
    });
```

- Switch back to "Blocks"

**Additional information:**
Only repro on Safari [10.1.2(11603.3.8)]

**Expected result:**
<img width="430" alt="screen shot 2017-09-05 at 3 05 22 pm" src="https://user-images.githubusercontent.com/17866936/30049077-ae967fba-924b-11e7-9f73-e92fd356bf4d.png">

**Actual result:**
Once change "_for(let i=0;i<5;**i++**){}_" to "_for(let i=4;i>=0;**i--**){}_", it doesn't work on "Blocks".
<img width="372" alt="screen shot 2017-09-05 at 3 05 49 pm" src="https://user-images.githubusercontent.com/17866936/30049093-c078e1f0-924b-11e7-855b-94e78b605a69.png">

**Comment by microsoftsam** [comment]
Tried this on Safari 11. and it works fine. 
It's weird to me that this is a browser specific issue.

**Comment by Emma-sunny** [comment]
Closed as Not Repro
