### ISSUE TITLE
The conditional expression of "for" loop is changed automatically.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2859]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Switch to "_{}JavaScript_" 
- Create list and use "_for_" loop to traverse the list,such like this:
_let list=[2,3,4,5,6];
for(let i=0;i<list.length;i++){
basic.showNumber(list[i]);
}_

- Switch back to "Blocks" and then switch to "_{}JavaScript_" again

**Expected result:**
The code should not be changed when switch "_{}JavaScript_" to "_Blocks_".

**Actual result:**
![sep-05-2017 15-43-52](https://user-images.githubusercontent.com/17866936/30050466-370c415e-9251-11e7-9f06-d6e075e3de7c.gif)

**Comment by abchatra** [comment]
This is how the decompiler works. for loop in blocks runs from 0 to limit including the limit. When you go back to blocks and code, you will see the code altered.  Ther is no 1-1 mapping between blocks and javascript.
