### ISSUE TITLE
Different response for putting block "show image item at offset 0" on "forever"

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2862]
**Repro step:**

- Navigate to [https://makecode.microbit.org/beta](url)

- Drag block "_show image item at offset 0_" to "forever"

- Then delete block "_show image item at offset 0_" from "_forever_" and then repeat the step2 again

**Expected result:**
As long as using the block incorrect, it should display the error message. No matter how many times you use it.

**Actual result:**
_The using result of the first time is different from the second time._
![sep-05-2017 16-05-19](https://user-images.githubusercontent.com/17866936/30051330-36590a00-9254-11e7-82a6-94ee29cdbc52.gif)

**Comment by abchatra** [comment]
I am not sure why we see the error at the first time

**Comment by abchatra** [comment]
It is an error, But the sim is in an error state and doesn't restart

**Comment by Helen09** [comment]
The error message shows differently on different browsers:
On **Edge:**
![1](https://user-images.githubusercontent.com/23466737/38236409-951d6a72-3713-11e8-8ea4-4a44819374b6.png)

On **Firefox, IE, Chrome:**
![2](https://user-images.githubusercontent.com/23466737/38236425-9fa75322-3713-11e8-8794-98fbf5c3a5fd.png)
