### ISSUE TITLE
Docs out of date with editor - acceleration strength

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2863]
The help for acceleration does not include the 'strength' option.

![screen shot 2017-09-05 at 10 39 06](https://user-images.githubusercontent.com/25079586/30055165-773e78f8-9226-11e7-96cb-e8190aa0b658.png)

https://makecode.microbit.org/reference/input/acceleration

Please could you explain in the docs update, in simple terms, what the 'strength' option actually measures, so that it can be used by teachers and children with knowledge of what it means - i.e. does it return a value in the range of 0 to (what) and what does that value mean? Does it 'filter out' the static acceleration due to gravity (i.e. will it always be 0 if you are not moving).

**Comment by DavidWhaleMEF** [comment]
Looks like this returns 1023 when not moving. Also if I tilt the micro:bit and hold it steady, it returns a higher number - so it's not measuring movement, it's probably measuring the sum of the squares of the x y and z readings? sqrt(x*x + y*y + z*z)?? Can you make sure that you document exactly what it does in the docs update, so that people can understand how they might use it to build things with? 

I guess it's not a tuneable replacement for on-shake, because it has no delta filtering involved in it.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/blob/master/libs/core/input.cpp#L246

**Comment by ganicke** [comment]
Strength enum value added in https://github.com/Microsoft/pxt-microbit/pull/527.
