### ISSUE TITLE
Squiggle start line is off by 1

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#2867]
Try any error in TS and you'll see that squiggles start 1 line early. Very confusing.
**
![image](https://user-images.githubusercontent.com/4175913/30124758-130ab20a-92eb-11e7-8e9a-ed3d5f8822d1.png)
**

**Comment by pelikhan** [comment]
Completly destroys the JS editing experience IMO.

**Comment by riknoll** [comment]
I'll take a look today
