### ISSUE TITLE
microbit editor does not load on android firefox

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2869]
Trying to load makecode.microbit.org using firefox app on android only loads partially. Ill try to add a screenshot.

**Comment by nielsswinkels** [comment]
![tmp_18045-screenshot_20170907-18193746945390](https://user-images.githubusercontent.com/5718354/30173786-2c78e572-93f9-11e7-86a6-15ac26b24d8d.png)

**Comment by abchatra** [comment]
This is fixed.
