### ISSUE TITLE
microbit javascript, bacspace doesn't work

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2870]
On android using chrome, i can't remove text when coding microbit in javascript mode. Pressing bacspace does not do anything. (And yes i have my cursor active in the text)

**Comment by abchatra** [comment]
@nielsswinkels Does this happen in /beta as well? We have bunch of fixes in beta for Monaco editor and I am wondering if this is fixed.

**Comment by nielsswinkels** [comment]
Beta has the same problem

**Comment by microsoftsam** [comment]
Android issues are very specific to the version of Chrome, Android version and Keyboard you are using. Any information regarding the above would be very helpful.

**Comment by microsoftsam** [comment]
Also, has this ever worked for you, ie: is this a regression?

**Comment by nielsswinkels** [comment]
I don't usually use android, and specially not javascript text mode, so I don't know if the problem existed before.

Now I updated to chrome 60.0.3112.116 and the problem is gone 👍 I'm using google's Gboard.

**Comment by microsoftsam** [comment]
Do you remember what versions of the above you were on?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nielsswinkels** [comment]
Oh... No idea.. and i don't think i can find that anymore
