### ISSUE TITLE
Blocks categories broken after roundtrip to javascript

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#2876]
- open new script https://makecode.microbit.org/beta
- switch to javascri[pt
- click on various categories
- switch back to blocks
- click on categories

![image](https://user-images.githubusercontent.com/4175913/30219717-d11c528a-9471-11e7-80e6-65b0126c8d89.png)

**Comment by microsoftsam** [comment]
Dupe of #2723

**Comment by microsoftsam** [comment]
This has been fixed. #3132
