### ISSUE TITLE
Microbit Simulator: text is undefined when digital write to pin > 2

### ISSUE THREAD

**Issue by mhldr** [Microsoft/pxt#2894]
If I try a digital write to pin 8 (or any pin greater than 2) then I get a program error.
Firefox = Program Error: text is undefined
Chrome = Program Error: Cannot read property 'textContent' of undefined

The minimal javascript code for this is:
```
pins.digitalWritePin(DigitalPin.P8, 0)
```
or in blocks
on start{
    digital write pin P8 to 0
}

This code works fine on my micro:bits and happily drives my chickbots about.

**Comment by pelikhan** [comment]
Need to be more defensive when accessing text items for pins

**Comment by pelikhan** [comment]
Fixed.
