### ISSUE TITLE
Serial communication requires recent firmware; please update docs

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt#2896]
I had this version of firmware on my micro:bit (from details.txt):
![image](https://user-images.githubusercontent.com/6453828/30251564-b6cb5ab0-9616-11e7-92b2-9fb2a70b1ecf.png)

I was unable to read or write from the device using the serial APIs. I tried unplugging, re-plugging the board many times, rebooting the computer, ejecting the USB device, nothing worked. The COM port didn't appear on the device manager at all. (I could see the USB storage device.)

After I followed the directions here (https://support.microbit.org/support/solutions/articles/19000019131-how-to-upgrade-the-firmware-on-the-micro-bit) to upgrade the firmware, I was then immediately able to see the COM port and communicate with the device.

Could the docs here (https://makecode.microbit.org/reference/serial) have a note that the serial drivers may need to be updated? Better yet, the exact version or date needed would be very helpful.

My system:
Windows 10 

Happy to provide more information on this issue.

Cheers,
Daryl

**Comment by ganicke** [comment]
Note for the firmware update added in https://github.com/Microsoft/pxt-microbit/pull/538.
