### ISSUE TITLE
There is blue border in selected item

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#2898]
**Repro steps:**
•	Navigate to https://makecode.microbit.org/beta 
•	Click on Projects/Share/?/More...

**Additional info:**
1. The sub-Items are also has blue border when selected on them
2. In firefox, when selected on ?/More…, there is blue border on the selected item and dropdown list.
![border1](https://user-images.githubusercontent.com/23447632/30260761-df304b1a-96fb-11e7-9c02-cfab5e12ad56.PNG)

**Expect Result:**
Background color changed on selected item, but without blue border
![border2](https://user-images.githubusercontent.com/23447632/30260800-0ad90fa4-96fc-11e7-9eae-ff471b1eb2a1.PNG)
**Actual Result:**
There is blue border on selected item
![border](https://user-images.githubusercontent.com/23447632/30260814-1d4cdec2-96fc-11e7-9236-53a6ace52ece.PNG)

**Comment by abchatra** [comment]
This is a accessibility change and by desgn
