### ISSUE TITLE
The simulator couldn't display when open the example project "Game of Life"

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2919]
Repro steps:
• Navigate to https://makecode.microbit.org/beta
• Click "Projects" in the Menu bar
• Click the "Examples"
• Select the project "Game of Life" to open

Expected result:
 The simulator could display
 Actual result:
 The simulator couldn't display

![example-game-of-life](https://user-images.githubusercontent.com/11880996/30316730-b1bca04a-97da-11e7-99eb-4a0399345256.gif)

**Comment by microsoftsam** [comment]
Another issue with decompilation @riknoll.

**Comment by yanlxu** [comment]
close as not repro
