### ISSUE TITLE
Change position of "." in string

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#2935]
Right now "." shows up at position 2,3.  This is annoying some teachers who want it located at the bottom where a decimal or period would actually show up.  Reported by a teacher through our email.

![decimalperiodposition](https://user-images.githubusercontent.com/22108954/30385827-265e6b5e-985d-11e7-9f5e-6683ea4faa9f.PNG)

**Comment by samelhusseini** [comment]
Transferred to pxt-microbit: https://github.com/Microsoft/pxt-microbit/issues/740
