### ISSUE TITLE
Make control.runInBackground nestable

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#2939]
This is more a proposal than it is an issue. `control.runInBackground` can safely be nested in other event handlers because the fiber it creates terminates (unlike `forever`) and it doesn't override any event handlers (unlike `onButtonPressed` etc.). We can make it so that you can [nest that block](https://github.com/Microsoft/pxt/pull/2660), but it is a minor breaking change because `control.runInBackground` will no longer be allowed as a top-level block. Existing scripts using that block will see it greyed out in their project when the editor loads and they will need to drag it into on start to achieve the same behavior.

We also could potentially patch the scripts so that they aren't broken, since the fix is pretty simple.

@jaustin @pelikhan @abchatra

**Comment by pelikhan** [comment]
We could allow runInBackground to be a top level block as well. This, non breaking change but minor version bump.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by riknoll** [comment]
Then what happens when you connect a block to the top or bottom of `runInBackground` while it's top level?

**Comment by pelikhan** [comment]
Good point. So it is a breaking change. We need to determine how many scripts use this block.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
Instead of a breaking change, we can introduce a new block that is nestable (and deprecate 'runInBackground'). ``control.fork`` anyone?
