### ISSUE TITLE
implement Editor.highlighStatement in monaco

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#294]
When you run this program: https://codethemicrobit.com/bgnedtdsxv (on the latest dev version) you will see a red notification "Error: PANIC 40".

In blocks you will see the crashing block highlighted, but in JavaScript there is no highlight, as the `highlightStatement()` method isn't implemented.

**Comment by microsoftsam** [comment]
@mmoskal let me know what you think of the highlighting colors. 
![image](https://cloud.githubusercontent.com/assets/16690124/18255981/3397d7de-7364-11e6-92a4-324d94edd560.png)

**Comment by pelikhan** [comment]
IMO Red is too alarming - the user might think they broke something. Use a glowing yellow background instead.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by mmoskal** [comment]
Yeah, I think yellow bg is enough

**Comment by microsoftsam** [comment]
Fixed. 62af8a60cae10d8b49537a73b005a7548671b623 
![image](https://cloud.githubusercontent.com/assets/16690124/18258272/61af9e0e-7387-11e6-918d-0a542adf1b46.png)
