### ISSUE TITLE
Getting started Tutorial does not start in non-English languages

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#2943]
![dutch](https://user-images.githubusercontent.com/31242877/30425435-242bdfd0-9941-11e7-8c19-6dccb12b620a.gif)

Steps to reproduce:

1) Change language (tested french, japanese, dutch)
2) Click on Getting Started

**Comment by abchatra** [comment]
@microsoftsam Can you take a look? This looks like a blocking bug.

**Comment by microsoftsam** [comment]
Fixed, and have verified fix is live.

**Comment by abchatra** [comment]
Thanks @microsoftsam
