### ISSUE TITLE
Heap corruption 030 when using array.removeAt() in radio receive

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2947]
I'm nose up to the wall getting a resource/demo finished, but wanted to note this here for now. Will try to build a repro case soon. But my workaround was to use array.removeElement() instead.

If I use array.removeAt() of a known index, in a radio receive handler, inside a custom namespace function, it seems to mess up the garbage collection somewhere. I get a panic 030. I also sometimes get 3 LEDs on very bright (which means the micro:bit has completely crashed as the display driver is no longer updating presumably interrupts have stopped?)

Will repro as soon as I can, but wanted to lodge this here so people know it's a problem, and know there is a workaround.

**Comment by abchatra** [comment]
@DavidWhaleMEF Can you share your program?

**Comment by abchatra** [comment]
No repro
