### ISSUE TITLE
How to detect error in conversion in parseInt

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2957]
There are no docs for parseInt() currently.

How would we detect a parse error if a non numeric value was passed to parseInt?

**Comment by abchatra** [comment]
https://github.com/Microsoft/pxt/blob/339364648f980b4de1fc9c172372da015c26e97d/common-docs/reference/text/parse-int.md

**Comment by abchatra** [comment]
We will update the link to documentation.
