### ISSUE TITLE
monaco build process intermetently modify editor.main.js

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#296]
VSCode is constantly flagging "editor.main.js" as modified, then it dissapears.

![image](https://cloud.githubusercontent.com/assets/4175913/18214103/1caab3cc-7100-11e6-957f-79ea0f225903.png)

**Comment by mmoskal** [comment]
All generated files should sit under built/

The webserver and upload process will happily combine contents of webapp/public and built.
