### ISSUE TITLE
"Search box" is not selected completely on Firefox&IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2963]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta on Firefox&IE
• Click on Search box

**Expected result:**(chrome,Safari)
 When "search box" is foucused, "search box" should like below picture
![2](https://user-images.githubusercontent.com/23466737/30581790-eed9bf16-9d53-11e7-94f6-91787d3d8bd5.png)

 **Actual result:**
  When "search box" is foucused, "search box" likes below picture on Firefox&IE，Edge
![1](https://user-images.githubusercontent.com/23466737/30581830-1bbd5128-9d54-11e7-9061-36aa48a36dff.png)

**Comment by samelhusseini** [comment]
Won't fix.
