### ISSUE TITLE
Simulator can't display when opening example "Radio Dashboard"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2964]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Projects" in the Menu bar
• Click the "Examples"
• Select the project "Radio Dashboard" to open

**Expected result:**
 The simulator could display
 **Actual result:**
 The simulator couldn't display
![1](https://user-images.githubusercontent.com/23466737/30583292-3c225ddc-9d59-11e7-8749-f8efc52033ea.gif)

**Comment by microsoftsam** [comment]
The example works fine if it's loaded in JS, but breaks when its converted to Blocks.
This is problematic @riknoll. Something in that example is causing the clients array to lose it's const declaration
