### ISSUE TITLE
Projects can't be loaded successfully

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2965]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Projects" in the Menu bar
• Click the "Projects"
• Select the one project for example "Smiley Buttons" to open

**Expected result:**
 This project should be opened successfully
**Actual result:**
 This project can't be loaded 
![2](https://user-images.githubusercontent.com/23466737/30584020-199391c6-9d5b-11e7-8462-75399c81298b.gif)

**Comment by microsoftsam** [comment]
Can't repro.

**Comment by Helen09** [comment]
It still repro on every browser. After choosing project "Flashing heart", it will navigate to the "Getting Started" page rather than open project on the right-page.

**Comment by microsoftsam** [comment]
Sounds like you're describing a different thing. 

Some projects, are now "tutorials". Tutorials open up in tutorial mode, similar to the getting started. That is by design.
