### ISSUE TITLE
Simulator scrolling text different from hardware

### ISSUE THREAD

**Issue by Dealerpriest** [Microsoft/pxt#2968]
When using the "show number" block to show numbers with more than one digit, the behaviour is different between the simulator and the microbit hardware. On the microbit there is a space added after the scrolling number which makes it easier to spot the start and end of the number. This is not the case in the simulator. Instead the number just scrolls in a steady stream. 
### Example
Want to show the number 1234 on the screen.
On the simulator the following will scroll by: "123412341234123412341234..."
On the microbit hardware the following will scroll by: "1234 1243 1234 1234 1234 1243..."

Note that it works fine when using the "show string" block.

**Comment by nielsswinkels** [comment]
https://makecode.microbit.org/_6MsfihCqtPfw

**Comment by samelhusseini** [comment]
Transferred to pxt-microbit: https://github.com/Microsoft/pxt-microbit/issues/741
