### ISSUE TITLE
Not all blocks have icons (low priority issue)

### ISSUE THREAD

**Issue by Carlborg** [Microsoft/pxt#2969]
The top left of most blocks show the corresponding block category icon.
Some blocks don't show this however. For instance in the category "Basic", all blocks except the "on start"-block have an icon. Other categories that have blocks without icons are: loops, logic, variables, math, functions, arrays and text.

**Comment by microsoftsam** [comment]
Thanks for bringing this up.
Built-in blocks don't have icons associated with the block. In general, we have found that adding the icon on the block doesn't help in the understanding of what the block does, and that the color is a good enough link to associate a block with it's category. 
We have found the icons tend to clutter the block, and distract students from the real description of what a block is, which is the text. 
In future releases we plan to shy away from blatantly adding icons on blocks, and only adding them on there if they help in the description of the block.

**Comment by nielsswinkels** [comment]
So will you remove them instead on the ones that have it now? There doesn't seem to be much logic behind why some have it and some don't

**Comment by microsoftsam** [comment]
I believe the answer to that question is a no, since it breaks many screenshots that have already been taken of the micro:bit editor, primarily books. 
I'll defer to @jaustin and @pelikhan to determine if there is something that can be done here.

**Comment by samelhusseini** [comment]
Closing, now tracking microbit issues at https://github.com/Microsoft/pxt-microbit
