### ISSUE TITLE
Slow mo highlighting highlights the entire stack

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#2978]
![screen shot 2017-09-19 at 4 36 20 pm](https://user-images.githubusercontent.com/16690124/30620214-d6012fa6-9d58-11e7-9a40-10c320650f70.png)

**Comment by microsoftsam** [comment]
@pelikhan @Jaqster @abchatra should it highlight a single one, or do we like this behaviour?

**Comment by pelikhan** [comment]
It should only highlight the current block IMO.

**Comment by abchatra** [comment]
It should only highlight the block. Otherwise I can't image how execution of the if\elseif blocks looks like

**Comment by microsoftsam** [comment]
There's some implementation detail the scratch-blocks rendering here. We're calling stack glow when we want to highlight a block which glows the entire blockly stack, in Blockly that means highlighting a block and all it's nested blocks inside of it. (so the behaviour we're seeing makes sense above). 
The fix is a little tricky, say we move the filter being applied back to how Blockly did it, on the block itself and not the entire stack we would get something that looks like this: 
<img width="284" alt="screen shot 2017-09-24 at 12 05 32 pm" src="https://user-images.githubusercontent.com/16690124/30784332-4c1c1acc-a121-11e7-9ba2-ae5baba0c63b.png">
<img width="288" alt="screen shot 2017-09-24 at 12 05 24 pm" src="https://user-images.githubusercontent.com/16690124/30784331-4c1be0a2-a121-11e7-9b30-caa7274e197b.png">

As you can see above, blocks are stacked in order and it's not possible to re-order them (ie: a z-index won't fix this), but you can see that the higher order blocks limit what you can see behind it, and when a block is highlighted behind it, it blocks part of the highlight (as seen on the bottom of the repeat block above)

This was also somewhat true for Blockly, but not to the same degree. See: 
<img width="389" alt="screen shot 2017-09-24 at 12 12 06 pm" src="https://user-images.githubusercontent.com/16690124/30784351-a381bf06-a121-11e7-86fb-fe045f195f2e.png">
You can see part of the bottom if statement's stroke is showing above the top if statement's highlight stroke.

In scratch-blocks the rendering of the blocks by-design hides away part of the other block to make it fit better. For example, a repeat statement inside of an if statement in scratch-blocks shows only the stroke border of the repeat block, and not the if statement around the edges that they meet: 
<img width="453" alt="screen shot 2017-09-24 at 12 18 15 pm" src="https://user-images.githubusercontent.com/16690124/30784401-778efdea-a122-11e7-81a4-428e51a4bf57.png">
whereas in blockly you see both:
<img width="683" alt="screen shot 2017-09-24 at 12 18 41 pm" src="https://user-images.githubusercontent.com/16690124/30784404-87ec5336-a122-11e7-9ae7-339bd77903a1.png">

So.. not sure what to do here, expect for setting the highlight on the Block only and being okay with the fact that part of the highlight is hidden.

Here's what that looks like on the Chibi:
![highlighting](https://user-images.githubusercontent.com/16690124/30784519-8d720452-a124-11e7-9193-db1a27920030.gif)

**Comment by Jaqster** [comment]
Yeah, I think this works - clearly shows what block is being called/executed.

**Comment by abchatra** [comment]
We will keep this issue open

**Comment by abchatra** [comment]
![slowmo](https://user-images.githubusercontent.com/6107272/30897811-2856912e-a30d-11e7-96fa-12f85d6834dc.gif)

**Comment by abchatra** [comment]
@riknoll if you are done with your P1 issues can you take a look. @microsoftsam has other P1's to address. 
This is P2 and I would ship craft without it, but would like to see if there is any way around it.

**Comment by pelikhan** [comment]
Slow-Mo is P3 IMO. What are the usage statistics on that feature?

**Comment by abchatra** [comment]
Slow-mo is low usage. But this is giving a low quality vibe to the editor whoever tries this. Talking to Richard, I think we should decide to keep this broken kind of behavior or go back to original proposal from @microsoftsam to keep scratch block highlighting the entire stack. Let us take this up in the design meeting today.

**Comment by pelikhan** [comment]
This is the kind of non-trivial fixes that involves messing around with the block layout algorithm. We are better spending time finishing a proper debugging experience.

**Comment by abchatra** [comment]
Lets keep this for now
