### ISSUE TITLE
excessive parens in blocks for prefix ops

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#299]
PR #297 always puts parenthesis around argument of !, even when not needed. It would be better to modify `flatten()` function to handle prefix operators and only add parens when needed. For example:

```
!foo
!foo.bar
!(foo == bar)
```

See also https://codethemicrobit.com/fwbhxfgcpg

This is far from critical though :-)

CC @pelikhan

**Comment by abchatra** [comment]
Closing as this is not something we will take up anytime soon
