### ISSUE TITLE
Can't translate some blocks

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2992]
We can't find where to translate the blocks you see when you click on the gear icon on an If-statement:

![microbit-skarmbild](https://user-images.githubusercontent.com/5718354/30633349-a5b181aa-9deb-11e7-8b72-2f424adfca61.png)

Also missing is where to translate the default name of a function "doSomething".

Also I can't find where to translate "on radio received" and all the variables that belong to that one:
![microbit-skarmbild2](https://user-images.githubusercontent.com/5718354/30633722-028cd2ca-9ded-11e7-8092-a33d76cd4fa9.png)

Same thing for "value" on "create new array" :
![microbit-skarmbild3](https://user-images.githubusercontent.com/5718354/30634041-02e04cce-9dee-11e7-90f1-d58af0b1161b.png)

Same thing for "join" and "item" on "join" (text):
![microbit-skarmbild4](https://user-images.githubusercontent.com/5718354/30634298-e09a8eee-9dee-11e7-8acf-3308b73ce963.png)

"Parse to integer" (text)

A bunch in the game category:
![microbit-skarmbild5](https://user-images.githubusercontent.com/5718354/30634304-e5e34f62-9dee-11e7-9dde-0907660632fe.png)

A few in the Images category:
![microbit-skarmbild6](https://user-images.githubusercontent.com/5718354/30634339-13b04134-9def-11e7-9ca4-738a91ac8d4d.png)

And the "raise event" and "on event" in the controll category.

**Comment by nielsswinkels** [comment]
Found another one: the "more..." on the category Math does not get translated, while all other ones are. So I guess that's just a bug.

**Comment by abchatra** [comment]
@pelikhan Can you take a look?

**Comment by nielsswinkels** [comment]
Any news on this?

**Comment by pelikhan** [comment]
Sorry this bug is fixed and ready in beta.

**Comment by nielsswinkels** [comment]
Cool, so that means it should come up soon? Looking forward to that :)

**Comment by pelikhan** [comment]
It is on crowdin already. We're planning to do an update soonish for the mbit.

**Comment by abchatra** [comment]
try https://makecode.microbit.org/beta

**Comment by nielsswinkels** [comment]
I just realized that "shake" in the simulator isn't translated either. Is that translatable in crowdin?

**Comment by nielsswinkels** [comment]
Please re-open this issue. It still isn't fixed.

**Comment by abchatra** [comment]
I have opened a tracking bug for this in pxt-microbit: https://github.com/Microsoft/pxt-microbit/issues/907
Add anything else you don't see localization there.
