### ISSUE TITLE
forever execute before onstart is done when running slow motion mode

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#2993]
When running in slowmotion mode the forever loop starts executing before onstart is completed (even if there is no delay in the onstart)

![microbit slowmo bug500x225](https://user-images.githubusercontent.com/5718354/30645607-8784b6ea-9e16-11e7-8c98-dc7c2f38f338.gif)

**Comment by nielsswinkels** [comment]
kind of related: https://github.com/Microsoft/pxt/issues/2385

**Comment by abchatra** [comment]
This is fixed. @riknoll confirm. It will be in the next release of micro:bit
