### ISSUE TITLE
Strings server may not be serving latest strings

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#2998]
According to the "Help translate" page, the translation strings are almost "live" by loading the translation strings files on the fly. But, the translation strings files may not be latest.

For example, the string "pick random 0 to %limit" was translated and approved 4 days ago for Japanese. The translation does not appear for Japanese, but it appears for Swedish (Sweden).

![image](https://user-images.githubusercontent.com/485416/30671221-bd2d0966-9ea0-11e7-930d-f4a0264b18b0.png)

**Comment by pelikhan** [comment]
The editor refuses to use strings where the syntax of the strings has been messed up:

![image](https://user-images.githubusercontent.com/4175913/30680402-3bfcded0-9e54-11e7-8e3d-63c35b84f67e.png)

**Comment by pelikhan** [comment]
I think in your case it is the %1 that messing things up.

**Comment by sgk** [comment]
Thank you and sorry for that. That was messed.

**Comment by pelikhan** [comment]
No worries! We should document how to diagnose these.
