### ISSUE TITLE
microbit images method not support in blocks.

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#30]
I found those BugblockId annotations. Is this supported?

https://github.com/Microsoft/pxt-microbit/blob/master/libs/microbit/images.cpp#L41

**Comment by mmoskal** [comment]
IT was crashing the block generation.  I guess it's on your side.

**Comment by pelikhan** [comment]
I can’t repro the crash, could you attach the javascript console output?.

It seems that “create()” is never called. You should have it called in the constructor.

**Comment by mmoskal** [comment]
The blocks were not showing in the drawers etc. I guess you've probably fixed it in the meantime. I honestly forgot about it.

**Comment by mmoskal** [comment]
@pelikhan is this still relevant?

**Comment by mmoskal** [comment]
Seems outdated.
