### ISSUE TITLE
r.isRef called on null reference fails

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#302]
The simulator crashes on this snippet.

```
let item: neopixel.Strip = null
item.showColor(neopixel.colors(NeoPixelColors.Red))
```

![image](https://cloud.githubusercontent.com/assets/4175913/18231210/5b69f696-7267-11e6-9a27-d4b1ce96fe28.png)

**Comment by mmoskal** [comment]
What would you expect the simulator to do? The breakpoint message contains the source location where it failed - it should be highlighted in the editor.

**Comment by pelikhan** [comment]
Ok so we need handle this message correctly. Currently shows up as red popup.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by mmoskal** [comment]
It's generated here: https://github.com/Microsoft/pxt/blob/master/webapp/src/simulator.ts#L52

There is a call to the editor to highlight line with the error. I think in both editors we should have a bubble popping up from the line/block in question with the error message. 

See also #294

I'll change the error message.

**Comment by mmoskal** [comment]
The message is now updated. Also note that the simulator now has a hook to do something special when an error occurs (postError()) - in the second commit above I use it to display a sad face, but maybe we want an SVG sad face (or a bug or something)

**Comment by microsoftsam** [comment]
@mmoskal I've implemented hightlightStatement in the editor but it doesn't seem to be called for the above sample statements. 
It works for the sample in #294

**Comment by microsoftsam** [comment]
![image](https://cloud.githubusercontent.com/assets/16690124/18256156/907bbfae-7366-11e6-9c2b-9e03feec1455.png)

**Comment by pelikhan** [comment]
We should be walking the stack up until the first frame of "user code", e.g. frame of code in the current project.

**Comment by abchatra** [comment]
Still repro

**Comment by mmoskal** [comment]
@microsoftsam why can't we highlight `pxt_modules/neopixel/neopixel.ts` ? We do have this file in the editor.  Indeed, it seems the entire backtrace should be highlighted though.
