### ISSUE TITLE
Can't go to "projects", "Reference", "Blocks", "JavaScript", "HardWare" under "?"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3056]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta 
• Navigate to "?"  
• Go to click "projects", "Reference", "Blocks", "JavaScript", "HardWare"

**Expected result:**
All pages should be opened successfully

**Actual result:**
After clicking these options, page all shows starting tutorial... and can't go to page successfully
![1](https://user-images.githubusercontent.com/23466737/30901413-3a005e4a-a39a-11e7-8372-35081a1c517d.gif)

**Comment by pelikhan** [comment]
Broken by https://github.com/Microsoft/pxt/pull/2906
