### ISSUE TITLE
There is a redundant box in documentation

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#3057]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta 
• Drog out "create array with" block in Arrays
• Right click block and click "help"
• Observe the documentation

**Expected result:**
There is no box there or some blocks in the box
**Actual result:**
![blank](https://user-images.githubusercontent.com/23497626/30911413-615c3da4-a33d-11e7-8175-cd552bee8898.PNG)

**Comment by ganicke** [comment]
Fixed in https://github.com/Microsoft/pxt/pull/3063. Will do a pick down to ``v0``.
