### ISSUE TITLE
Indentation failure when using array indexing

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#3059]
The following code fails to correctly indent the basic.pause() statements when moving from blocks to javascript

```
let ball: Image[] = []
let speed = 0
let index = 0
input.onGesture(Gesture.Shake, () => {
    speed = Math.random(101)
    for (let index2 = 0; index2 <= 3; index2++) {
        ball[3 - index2].showImage(0,50)
basic.pause(speed)
    }
    speed = Math.random(101)
    for (let index3 = 0; index3 <= 3; index3++) {
        ball[index3].showImage(0,50)
basic.pause(speed)
    }
})
index = 0
ball = [images.createImage(`
    . . . . .
    . . . . .
    . . # . .
    . . . . .
    . . . . .
    `), images.createImage(`
    . . . . .
    . . # . .
    . # # # .
    . . # . .
    . . . . .
    `), images.createImage(`
    . . # . .
    . # # # .
    # # # # #
    . # # # .
    . . # . .
    `), images.createImage(`
    . # # # .
    # # # # #
    # # # # #
    # # # # #
    . # # # .
    `)]
```

**Comment by DavidWhaleMEF** [comment]
Also, when I switch back and forth between javascript and blocks, it inserts an array initialiser in the onstart that then makes the program invalid. If I delete that in the blocks view, the program works. If I switch back to javascript then back to blocks, it appears again.

![screen shot 2017-09-27 at 13 19 42](https://user-images.githubusercontent.com/25079586/30913039-abb1c6fa-a386-11e7-8762-97c190e73dd4.png)

**Comment by pelikhan** [comment]
Please open separate issues, it is easier to prioritize.

**Comment by riknoll** [comment]
That second issue will be fixed in the next release

**Comment by abchatra** [comment]
Moved https://github.com/Microsoft/pxt-microbit/issues/914
