### ISSUE TITLE
monaco editor.main.js failing to load in beta

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#307]
I've removed the monaco files from the manifest https://github.com/Microsoft/pxt/commit/f5cc2d5affc815a3cfa17ac5e9afcf9f8d3f2987

Could you update it?

![image](https://cloud.githubusercontent.com/assets/4175913/18295787/36c0c2b8-7459-11e6-8739-181fcbf4d9a9.png)

**Comment by microsoftsam** [comment]
Fixed in this commit: 8e75b947d82ca1b621d511f01cda1d8d9d8a400f
