### ISSUE TITLE
monaco editor auto complete fails to insert code snippet after 2 minutes

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#308]
The reference model used by the typescript language services goes out of sync after 2 minutes of inactivity and in turn the intellisense is unable to insert the code snippet.

We either need an alternative way to look up the signature help items or we need to find a way to restart the model in time so its ready when the resolveCompletionItem is called

**Comment by pelikhan** [comment]
Why is there a timeout?

**Comment by microsoftsam** [comment]
I asked Johannes (from monaco) this a while back and he said it was for a bunch of reasons, but mostly to avoid leakage.

**Comment by pelikhan** [comment]
Is this relevant?

**Comment by microsoftsam** [comment]
Nope, this is fixed when we move to using Typescript 2 in pxt-monaco-typescript.
