### ISSUE TITLE
Code Neopixels - MakeCode error (micro:bit support ticket 2880)

### ISSUE THREAD

**Issue by microbit-pauline** [Microsoft/pxt#3085]
The customer is using  MakeCode website: https://makecode.microbit.org/#
to code some neopixels. They have created some simple code to make all the lights go red.

Comment - "The code is incorrect: I have not changed the variable item to MyLights. 
When I tried to press the A button on the micro:bit simulator I get an useful error "Program Error: r.isRef is not a function" 
![isref](https://user-images.githubusercontent.com/29146842/31010117-a4ef4014-a501-11e7-9538-58c460f71a69.png)

**Comment by abchatra** [comment]
This code has bug. There is no initialization of 'item' variable. Did they mean to use 'MyLights' variable? There is no action on us here?  Error message can be better.

**Comment by jaustin** [comment]
In fact, in this case the report that came into us was about the better error handling not a script bug, sorry. As you said it'd be great for the error message to be something that actually helps the user work out how to fix the issue. 

A message like 
``` 
"item" is not initialised as a programmable lights variable
```
 would be much more appropriate than the mysterious r.isRef!

Do you want me to open a separate issue to track the error being very confusing? Or can we use this for that?

When I use /beta at the moment and use a similar reproducer, it appears to kill the simulator and then even when I reload the page it doesn't come back. Removing the offending block *does* bring the Sim back though

https://makecode.microbit.org/_0d63MbJ6JUFh is an example of a sim-breaking-bug

**Comment by jaustin** [comment]
@abchatra @pelikhan  shall I file a new bug for this?

**Comment by jaustin** [comment]
We've discussed this now with @abchatra so putting an update here:
MakeCode team will look at how to mitigate this with error messaging and improving the messages (the top 10 most common messages are already friendlyized, so this may be an 11th or this may be way down the list.) Some further investigation is required to understand the frequency of this message and also how much info we can provide when it occurs (for example, can we infer the type of variable that was expected?
