### ISSUE TITLE
Scrolling does not work inside block categories on https://minecraft.makecode.com/

### ISSUE THREAD

**Issue by philgolden** [Microsoft/pxt#3086]
If I open https://minecraft.makecode.com/, and click on 'Blocks', I see a list of blocks that extends below the bottom of my screen. When I click the scroll bar it does not work. I have tried this on different machines, and it doesn't work on any of them. 
![scrollingbug](https://user-images.githubusercontent.com/24957105/31018407-dea91b78-a523-11e7-89f3-fb37ef2d2fb9.png)

**Comment by abchatra** [comment]
@philgolden Thanks for filing. We will look into it immediately. Scroll wheel works though

**Comment by philgolden** [comment]
Hey,

When you say scroll wheel, could you be more specific? How can I scroll?

Phil

**Comment by abchatra** [comment]
The middle "wheel" is the scroll wheel.
https://en.wikipedia.org/wiki/Scroll_wheel
