### ISSUE TITLE
Array shift crash on real micro:bit

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#3093]
All the examples in #2462 now work in the simulator. But this example still gives sad face 042 on the real micro:bit. So it seems that was a different issue.

```
let item: game.LedSprite = null
let list = [game.createSprite(0, 0), game.createSprite(1, 0)]
item = list.shift()
item = list.shift()
```

**Comment by pelikhan** [comment]
Ref counting issue.

**Comment by mmoskal** [comment]
It's possible there are some other clones of this code.

**Comment by abchatra** [comment]
Fixed
