### ISSUE TITLE
Radio Dashboard example doesn't run

### ISSUE THREAD

**Issue by elinor-fung** [Microsoft/pxt#3097]
1. Open 'Radio Dashboard' example
**Observe** block editor shows an error at the declaration of the clients variable in the 'on start' block. Simulator fails to run the project.
2. Switch to JavaScript editor
3. Add `const` (or `let`) before `clients: Client[] = []`
**Observe** Simulator now successfully runs the project
4. Switch back to block editor
**Observe** the same error is shown as in (1)
5. Switch back to JavaScript editor
**Observe** the edit from (3) is lost

**Comment by abchatra** [comment]
@riknoll  is this fixed in beta?

**Comment by abchatra** [comment]
This is fixed.
