### ISSUE TITLE
Some blocks cannot be translated

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#3098]
The blocks in the picture below cannot be translated. The music frequency block needs some code improvement to show translated strings (the strings like "Middle C" are already on Crowdin). The base strings for the other blocks are not in strings.json files and not on Crowdin. The extraction process from the source code seems not working properly.

![image](https://user-images.githubusercontent.com/485416/31052452-1a1f6a5c-a6c0-11e7-9198-89a64f29ddb0.png)

**Comment by sgk** [comment]
The array name "list" cannot be translated, too.

**Comment by sgk** [comment]
The latest code deployed yesterday and array related blocks appeared with local strings. The remaining blocks are as in the following picture. The music note frequency block has been translated in half. "Middle" translated to "中央" in Japanese for example. But, "C" should be translated to "ド".

![image](https://user-images.githubusercontent.com/485416/31509004-db78d370-afba-11e7-8ef9-471c69e54ee8.png)

**Comment by sgk** [comment]
This seems already fixed and can be closed.

**Comment by abchatra** [comment]
Fixed

**Comment by abchatra** [comment]
Thanks @sgk
