### ISSUE TITLE
surface runtime errors in code

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#31]
An API that allows the runtime (simulated or hardware) to surface a runtime issue in the code editor. We had a simular feature in TD.
- [x] message passing support for surfacing messages from simulator or debugger interface
- [x] API to report an error
- [x] walk the stack back under the first user frame is found
- [ ] display in javascript editor (Sam)
- [ ] display in block editor (peli)

**Comment by mmoskal** [comment]
We should also consider breaking into a debugger on crash.

**Comment by mmoskal** [comment]
The editor support needs to be added. We may also need some throttling somewhere.

**Comment by tballmsft** [comment]
We have this, sort of, right now, with highlighting of line where error occurred, but it's not optimal.

**Comment by abchatra** [comment]
won't fix for now
