### ISSUE TITLE
losing JavaScript on page reload

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#3100]
Repro:
* create a new project
* switch to JS
* enter some code
* switch to `built/binary.js` in explorer
* reload page
* observe being dropped into blocks and the JS being lost

Is there some way that we could be systematically more careful about not losing user's work?

**Comment by pelikhan** [comment]
Which editor?

**Comment by mmoskal** [comment]
Repros on Adafruit and micro:bit. I assume all of them.

**Comment by mmoskal** [comment]
Another scenario:
* edit JavaScript
* edit `pxt.json` as text
* press JavaScript button on top
* reload page
* JS file replaced with contents of `pxt.json`

**Comment by abchatra** [comment]
Still reproes.
