### ISSUE TITLE
all my projects are called Untitled

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#3101]
It's impossible to find anything. We can do one of the following:
* name them `Untitled 17`
* add some adjective, eg. "amazing bit", see https://github.com/Microsoft/TouchDevelop/blob/master/editor/scriptList.ts#L8876 ; maybe add an animal name (terrific elephant)
* be smarter about generating the name from the contents; maybe in connection with the adjective (glorious buttons, inspiring LEDs, etc)
* ask the user for name when creating (but still need a default name, like above)

**Comment by pelikhan** [comment]
One solution is to keep asking the user to rename their scripts when clicking on "Download".

**Comment by HelenFoster** [comment]
I liked the random names from the previous software.

Maybe also don't allow renaming a script to the same name as another. I've done that by mistake and got confused. Normal files don't let you do it.

> One solution is to keep asking the user to rename their scripts when clicking on "Download".

I've seen children clicking randomly at their 5 or so Untitled, after an hour of work when they haven't downloaded anything yet.
