### ISSUE TITLE
New simulator runtime is sometimes created unexpectedly

### ISSUE THREAD

**Issue by caitlin-hennessy** [Microsoft/pxt#3116]
This causes multiple serial graphs to appear for the same variable.
This is not _caused_ by the serial editor, but it looks really bad in the serial editor.
Possible band-aid solution: drop graphs that have not received data in _x_ milliseconds.

**Comment by pelikhan** [comment]
Add the serial.txt file to the project does trigger a simulator reload. Yes, graphs should be dropped after a certain amount of inactivity (e.g. >5s && >1x time range)

**Comment by pelikhan** [comment]
Changing file in editor triggered a typecheck which restarted the editor

**Comment by caitlin-hennessy** [comment]
Oh, OK.  Is this fixed by https://github.com/Microsoft/pxt/pull/3134?

**Comment by pelikhan** [comment]
Yes. Stil we should come up with a logic to recycle out old charts eventually.

**Comment by caitlin-hennessy** [comment]
Yeah, I filed a separate issue for that.
