### ISSUE TITLE
Add data source info to serial graph/console/buffer

### ISSUE THREAD

**Issue by caitlin-hennessy** [Microsoft/pxt#3121]
Suppose two simulators in the same runtime each write serial data for a variable called "x".  Right now, the serial editor will display two graphs titled "x".  Do we want them to be titled something like "simulator1-x" and "simulator2-x" instead?

**Comment by pelikhan** [comment]
The previous log view used to color the line based on the simulator theme (worked for micro;bit, dubious for others).

**Comment by caitlin-hennessy** [comment]
Part of https://github.com/Microsoft/pxt/issues/3119, then.
