### ISSUE TITLE
More robust regex to test whether serial data is "graph data" or "console data"

### ISSUE THREAD

**Issue by caitlin-hennessy** [Microsoft/pxt#3122]
Right now regex is /[a-z]+:-?[0-9.]+/.  This should be more robust.

**Comment by pelikhan** [comment]
It should be the same regex used to extract data.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/d89f9bb2ebcefe5b04b9c2eb1da8f84962766a2c
