### ISSUE TITLE
comment popup shows outside of screen on long blocks

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3129]
If you have a comment on a block that is long (streches outside the screen) and the top of that block is close to the top of the screen, the comment popup gets opened underneath the block, which is outside the screen. If you then try to navigate there the popup closes. 

Workaround: make sure the top of the block is not too close to the top of the screen when opening the comment.

I assume this is blockly related, but is it fixable is some way?

![microbit-bug-comments1110x500](https://user-images.githubusercontent.com/5718354/31136428-81e4a464-a868-11e7-9951-2d8a4c974500.gif)

**Comment by microsoftsam** [comment]
Yeah Blockly related, and I think the fix for this won't be simple.
I've filed an issue on pxt-blockly to track. 
https://github.com/Microsoft/pxt-blockly/issues/67

**Comment by microsoftsam** [comment]
Thanks for the feedback, closing this here.
