### ISSUE TITLE
Icon name in tooltip shown underneath block

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3130]
In Internet Explorer (11.608) the tooltip showing the names of different icons shows up underneath the block instead of above.

![image](https://user-images.githubusercontent.com/5718354/31139117-d93d02da-a870-11e7-854f-fbd5642a1b91.png)

**Comment by microsoftsam** [comment]
This was fixed in master. Looks like it wasn't integrated to v0. Fixing

**Comment by nielsswinkels** [comment]
I must say I'm so impressed with how fast bugs get handled here <3

**Comment by microsoftsam** [comment]
Thanks!

**Comment by microsoftsam** [comment]
Fixed in /beta
