### ISSUE TITLE
make 'pxt init' ask about adding C++/asm

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#314]
This should fix the problem with missing `shims.d.ts` etc

**Comment by mmoskal** [comment]
@pelikhan - any other ideas what could it ask about?

**Comment by pelikhan** [comment]
In the future, the pxtparts.json file if the code declares a new part.

**Comment by mmoskal** [comment]
Instead of adding queries to 'pxt init' there is now a new 'pxt add', eg 'pxt add asm', so you can decide to add assembly etc later. 'pxt init' displays as message that you can use it when it's done.
