### ISSUE TITLE
Clean up codebase of features that are no longer used

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#3145]
Title says it all, add more to this list of code cleanup.
- [x] Icons on blocks. (https://github.com/Microsoft/pxt/pull/3149)
- [ ] Subcategory support in toolbox (when we completely deprecate it)
- [x] Javascript tooltip on blocks (https://github.com/Microsoft/pxt/pull/3146)
- [ ] Cloud workspace. @pelikhan? Is this something we can cleanup
- [x] CardBrowser? https://github.com/Microsoft/pxt/blob/master/webapp/src/browser.tsx#L22 (https://github.com/Microsoft/pxt/pull/3148)
- [x] Shuffle blocks (https://github.com/Microsoft/pxt/issues/3145)

**Comment by pelikhan** [comment]
Maybe shuffle should go too.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by samelhusseini** [comment]
Closing.
