### ISSUE TITLE
Shadowed variables treated as same variable in blocks

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#315]
Probably low priority, but if you have something like this:

![shadowed](https://cloud.githubusercontent.com/assets/13754588/18323733/c870fb9e-74ed-11e6-8fed-5673a0e89781.PNG)

The variable `i` is shadowed by the variable declared in the `for` loop.  If you try and rename any of the variables, all of them will be renamed.

**Comment by riknoll** [comment]
I think this is less an editor issue, and more a compiler issue. The emitted code should not redeclare `i` in the for loop

**Comment by tballmsft** [comment]
@riknoll - is this fixed now?

**Comment by riknoll** [comment]
Nope, probably requires changes to Blockly

**Comment by abchatra** [comment]
This is fixed.
