### ISSUE TITLE
(docs) Do not translate inside quoted codes

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#3155]
Currently, a single dot `.` is translated to `ピリオド「.」` in Japanese to describe it because such letter does not appear in regular Japanese texts. This translation is applied to not only human readable texts in the documents, but also to the quoted codes embedded in the documents. This results in corruption of such codes like the capture below.

This can be fixed quickly by changing the translation on Crowdin to `.` also in Japanese. However, you should better to change the document rendering system not to translate inside the quoted codes.

![image](https://user-images.githubusercontent.com/485416/31207845-abacda4c-a9bb-11e7-90d6-a89367d41a71.png)

**Comment by pelikhan** [comment]
Correct, code snippets should not be translated.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
If this is a still an issue let me know. I will reopen a tracking bug
