### ISSUE TITLE
Circuit Playground simulator treats button A and pin A1 as the same input

### ISSUE THREAD

**Issue by elinor-fung** [Microsoft/pxt#3156]
1. Add code (or blocks) for handling a click of pin A1:
```
input.pinA1.onEvent(ButtonEvent.Click, function () {
    light.pixels.setAll(Colors.Red)
})
```
2. Click on button A
**Observe** lights turn red (per handler for pin A1)
3. Add a handler for click of button A to the end of the code:
```
input.buttonA.onEvent(ButtonEvent.Click, function () {
    light.pixels.setAll(Colors.Blue)
})
```
4. Click on pin A1
**Observe** lights turn blue (per handler for button A)

Same thing happens with button B and pin A2.

**Comment by abchatra** [comment]
@elinor-fung please file the Adafruit CPX issues on https://github.com/microsoft/pxt-adafruit

**Comment by abchatra** [comment]
Does this happen on the hardware as well?

**Comment by samelhusseini** [comment]
Transferred to pxt-adafruit: https://github.com/Microsoft/pxt-adafruit/issues/683
