### ISSUE TITLE
Remove roundtrip check for decompilation

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#316]
We should instead flag errors where decompilation is not supported and fail immediately.
- [x] Build test suite of programs that should decompile
- [x] Build test suite of programs that should not decompile
- [x] Integrate test suite in build
- [x] Integrate docs test suite in build
- [ ] Remove roundtrip

**Comment by abchatra** [comment]
I am closing this as we don't have work planned here.

**Comment by abchatra** [comment]
Reopening after discussing with Richard. We still need to remove the roundtrip.

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/635
