### ISSUE TITLE
merge error on serial.txt

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#3173]
When using output, the following error happens on localhost
```
merge error for serial.txt: previous content changed...
Error 409
```

**Comment by mmoskal** [comment]
It prevents the sources from being saved (after it happens). This may also happen in apps.

**Comment by mmoskal** [comment]
@abchatra I think this is P1

**Comment by mmoskal** [comment]
This https://github.com/Microsoft/pxt/commit/c85b5d6190e78949085acf58a99d68e18aa49af4 seems to fix it. Feel free to cherry pick on master.

**Comment by mmoskal** [comment]
This should be now fixed.

**Comment by caitlin-hennessy** [comment]
Fixed in both v0 and master.
