### ISSUE TITLE
"icon image" block does not show its options properly

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#3175]
The icons line up vertically and it shows only a part of them even if scrolled. This may not be what you intended.

![image](https://user-images.githubusercontent.com/485416/31307366-1d6c681c-ab9e-11e7-9574-ae0526f28607.png)

**Comment by abchatra** [comment]
I can not repro this. What version of Chrome & OS are your running?

**Comment by sgk** [comment]
Hmm... It's Chrome version 61.0.3163.100 64 bit on Windows 10 Pro version 1703 build 15063.632.

**Comment by carlosperate** [comment]
Looks like an old version of PXT, which had a (now fixed) issue with the Blockly html widget.
Could you check the version in the "About" menu item from the gear icon at the top right?
Do you have a working internet connection in that computer? Is MakeCode not updating itself?

**Comment by sgk** [comment]
Cache problem?

> makecode.microbit.org version: 0.13.20
> Microsoft MakeCode version: 0.13.28
> C++ runtime version: v2.0.0-rc11

**Comment by sgk** [comment]
Cleared the browser cache, but nothing change.

**Comment by carlosperate** [comment]
My mistake, I was confusing the "show icon" block with the "icon image" block (which has the old dropdown).
So maybe the "icon image" block could be updated to use the same dropdown:

![image](https://user-images.githubusercontent.com/4189262/31394450-3e57273a-add6-11e7-898c-c8036a3040ad.png)

**Comment by abchatra** [comment]
I can repro now. Sorry I was looking at show icon block as well.

**Comment by abchatra** [comment]
@microsoftsam can you take a look?

**Comment by sgk** [comment]
Thank you!
