### ISSUE TITLE
URGENT - Projects/ Import File FAILS!! - CAN'T LOAD ANY HEX FILES!!

### ISSUE THREAD

**Issue by harveytwyman** [Microsoft/pxt#3176]
Files can be loaded from the Browser's "Cache" but not from any other location.

Hex Files can be saved to a location but the Import FAILS!

The problem is common to Chrome and Edge Browsers  running Windows 10 and on different laptops.

It was OK a few days ago.

H E L P !! - I can't do any work!!

The problem seems to be with files created from the 26th of September. I save updated versions every 20 minutes or so.

The Hex File Size seems to drop 100K in size even though the 2 files were created just minutes apart.

The larger one works but the smaller file fails.

Further files also seem to be  this 100K smaller as well. From that date,  none of my files will Import.

Is there any way of retrieving my newer hex files into the editor?

I've LOST over 2 weeks of WORK!

**Comment by harveytwyman** [comment]
Is it due to Chrome's Cache Size hitting the limit?

**Comment by harveytwyman** [comment]
I've tried adding a small amount of code to the working version and it FAILS to Import.

THE PROBLEM IS THAT THE PXT EDITOR HAS A LIMITED FILE SIZE.

CAN YOU PLEASE INCREASE THIS LIMIT OTHERWISE I CAN'T DO ANY MORE WORK.

**Comment by harveytwyman** [comment]
I tried a workaround:
create in Blocks then translate to JavaScript.
Copy and Paste text to Notepad++ and save file.
It can be loaded back from the file with another Copy and Paste BUT I'm using the NeoPixel Package.
The JavaScript Package for NeoPixel doesn't have all the facilities as the Blocks version so WILL NOT TRANSLATE back to Blocks.

**Comment by abchatra** [comment]
@harveytwyman can you share your hex file where the import fails?

**Comment by abchatra** [comment]
Also there a share feature to share your program as a workaround until this is fixed.

**Comment by harveytwyman** [comment]
The next comment box contains the JavaScript File that loads and is viewable in Blocks.

**Comment by harveytwyman** [comment]
let halfDelay = 0
let quarterDelay = 0
let doubleDelay = 0
let random = 0
let randomSelect = 0
let delay = 0
let timePeriod = 0
let LEDStrip1: neopixel.Strip = null
let count = 0
let endTime = 0
let index = 0
let startTime = 0
input.onButtonPressed(Button.B, () => {
    endTime = input.runningTime()
    timePeriod = endTime - startTime
    delay = timePeriod / 10
    halfDelay = timePeriod / 20
    quarterDelay = timePeriod / 40
    doubleDelay = timePeriod / 5
    basic.showString("\\")
})
input.onButtonPressed(Button.A, () => {
    startTime = input.runningTime()
    basic.showString("/")
})
input.onButtonPressed(Button.AB, () => {
    while (true) {
        if (Math.randomBoolean()) {
            delay = doubleDelay
            quarterDelay = halfDelay
        } else {
            delay = timePeriod / 10
            quarterDelay = timePeriod / 40
        }
        randomSelect = Math.random(12)
        if (randomSelect == 0) {
            Scene6()
        }
        if (randomSelect == 1) {
            Scene7()
        }
        if (randomSelect == 2) {
            Scene2()
        }
        if (randomSelect == 3) {
            Scene4()
        }
        if (randomSelect == 4) {
            Scene5()
        }
        if (randomSelect == 5) {
            Scene1()
        }
        if (randomSelect == 6) {
            Scene3()
        }
        if (randomSelect == 7) {
            Scene8()
        }
        if (randomSelect == 8) {
            Scene9()
        }
        if (randomSelect == 9) {
            Scene9()
        }
        if (randomSelect == 10) {
            Scene10()
        }
        if (randomSelect == 11) {
            Scene11()
        }
    }
})
function Scene2()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(4, neopixel.rgb(60, 0, 0))
    LEDStrip1.setPixelColor(5, neopixel.rgb(0, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(6, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(0, 0, 60))
    LEDStrip1.setPixelColor(7, neopixel.rgb(0, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(8, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(60, 0, 60))
    LEDStrip1.setPixelColor(9, neopixel.rgb(60, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
}
function Scene4()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(0, neopixel.rgb(60, 0, 60))
    LEDStrip1.setPixelColor(9, neopixel.rgb(60, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(0, 60, 60))
    LEDStrip1.setPixelColor(8, neopixel.rgb(0, 60, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(60, 60, 0))
    LEDStrip1.setPixelColor(7, neopixel.rgb(60, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(0, 60, 60))
    LEDStrip1.setPixelColor(6, neopixel.rgb(0, 60, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(4, neopixel.rgb(60, 0, 60))
    LEDStrip1.setPixelColor(5, neopixel.rgb(60, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
}
function Scene5()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(4, neopixel.rgb(60, 0, 0))
    LEDStrip1.setPixelColor(5, neopixel.rgb(0, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(60, 60, 0))
    LEDStrip1.setPixelColor(6, neopixel.rgb(60, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(0, 0, 60))
    LEDStrip1.setPixelColor(7, neopixel.rgb(0, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(0, 60, 60))
    LEDStrip1.setPixelColor(8, neopixel.rgb(0, 60, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(60, 0, 60))
    LEDStrip1.setPixelColor(9, neopixel.rgb(60, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
}
function Scene8()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(4, neopixel.rgb(255, 255, 255))
    LEDStrip1.setPixelColor(5, neopixel.rgb(255, 255, 255))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(255, 255, 255))
    LEDStrip1.setPixelColor(6, neopixel.rgb(255, 255, 255))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(255, 255, 255))
    LEDStrip1.setPixelColor(7, neopixel.rgb(255, 255, 255))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(255, 255, 255))
    LEDStrip1.setPixelColor(8, neopixel.rgb(255, 255, 255))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(255, 255, 255))
    LEDStrip1.setPixelColor(9, neopixel.rgb(255, 255, 255))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(9, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(8, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(7, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(6, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(4, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(5, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.clear()
}
function Scene10()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(0, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(1, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(2, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    basic.pause(delay)
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(1, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(2, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(3, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(4, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(5, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    basic.pause(delay)
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(4, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(5, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(6, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(7, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(8, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    basic.pause(delay)
    basic.pause(delay)
}
function Scene3()  {
    for (let i = 0; i < 10; i++) {
        LEDStrip1.setPixelColor(Math.random(10), neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
        basic.pause(halfDelay)
        LEDStrip1.setPixelColor(Math.random(10), neopixel.rgb(0, 0, 0))
        LEDStrip1.show()
        basic.pause(halfDelay)
    }
    LEDStrip1.clear()
}
function Scene11()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(4, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(5, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(6, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(7, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(8, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(9, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(9, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(8, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(7, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(6, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(4, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(5, neopixel.rgb(0, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.clear()
}
function Scene1()  {
    count = 0
    for (let i = 0; i < 10; i++) {
        random = Math.random(256)
        LEDStrip1.setPixelColor(count + 0, neopixel.rgb(random, random, random))
        LEDStrip1.show()
        basic.pause(quarterDelay)
        LEDStrip1.setPixelColor(count + 0, neopixel.rgb(0, 0, 0))
        LEDStrip1.setPixelColor(count + 1, neopixel.rgb(random, random, random))
        LEDStrip1.show()
        basic.pause(quarterDelay)
        count += 1
    }
    count = 9
    for (let i = 0; i < 10; i++) {
        LEDStrip1.setPixelColor(count + 0, neopixel.rgb(random, random, random))
        LEDStrip1.show()
        basic.pause(quarterDelay)
        LEDStrip1.setPixelColor(count - 1, neopixel.rgb(random, random, random))
        LEDStrip1.setPixelColor(count + 0, neopixel.rgb(0, 0, 0))
        LEDStrip1.show()
        basic.pause(quarterDelay)
        count += -1
    }
}
function Scene6()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(0, neopixel.rgb(60, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(0, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(60, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(60, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(4, neopixel.rgb(0, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(5, neopixel.rgb(0, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(6, neopixel.rgb(0, 60, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(7, neopixel.rgb(0, 60, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(8, neopixel.rgb(60, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(9, neopixel.rgb(60, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
}
function Scene7()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(9, neopixel.rgb(60, 0, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(8, neopixel.rgb(0, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(7, neopixel.rgb(60, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(6, neopixel.rgb(60, 60, 0))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(5, neopixel.rgb(0, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(4, neopixel.rgb(0, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(3, neopixel.rgb(0, 60, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(0, 60, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(1, neopixel.rgb(60, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(60, 0, 60))
    LEDStrip1.show()
    basic.pause(delay)
}
function Scene9()  {
    LEDStrip1.clear()
    LEDStrip1.setPixelColor(9, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(8, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    basic.pause(delay)
    LEDStrip1.setPixelColor(9, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(8, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(0, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(1, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    basic.pause(delay)
    LEDStrip1.setPixelColor(0, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(1, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(7, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(6, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    basic.pause(delay)
    LEDStrip1.setPixelColor(7, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(6, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(2, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(3, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    basic.pause(delay)
    LEDStrip1.setPixelColor(2, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(3, neopixel.rgb(0, 0, 0))
    LEDStrip1.setPixelColor(4, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.setPixelColor(5, neopixel.rgb(Math.random(256), Math.random(256), Math.random(256)))
    LEDStrip1.show()
    basic.pause(delay)
    basic.pause(delay)
    LEDStrip1.clear()
}
index = 0
LEDStrip1 = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
LEDStrip1.clear()
LEDStrip1.show()

**Comment by pelikhan** [comment]
I can export an dimport no problem. However, I am seeing a terrible slowdown in the LZMA compression path.

**Comment by harveytwyman** [comment]
Could you please explain that comment in simple English. Thanks

**Comment by harveytwyman** [comment]
Yes I can export and import the above code too. However if you ADD a few lines to the Block Editor version you CAN't then export and import, it FAILS.

**Comment by abchatra** [comment]
I can't repro this. It take some time to compile this code but I am able to export.
