### ISSUE TITLE
bluetooth "on data received" block causes an error on simulator

### ISSUE THREAD

**Issue by carlosperate** [Microsoft/pxt#3193]
Steps to reproduce:
* New project
* Add Bluetooth package
* Drag the "Bluetooth on data received" block onto the workspace

![block](https://user-images.githubusercontent.com/4189262/31353952-6619cc28-ad2c-11e7-9c2e-121f37f7b64f.gif)

makecode.microbit.org version: 0.13.20
Microsoft MakeCode version: 0.13.28
C++ runtime version: v2.0.0-rc11

**Comment by birdbraintech** [comment]
I just opened a [similar issue](https://github.com/Microsoft/pxt/issues/3217) where the same error occurred with the serial write buffer block - I did not see this issue before posting, apologies for not referencing it.

**Comment by microbit-mark** [comment]
This looks to be fixed, though the error from https://github.com/Microsoft/pxt/issues/3217 still persists. Is it a similar fix for serial?

**Comment by abchatra** [comment]
Fixed
