### ISSUE TITLE
Icon brightness very dim when sprite is created

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#3196]
microbit.org-ticket: 2918

When a sprite is created it affects the brightness of any icon shown after.

Example program:
```js
let item: game.LedSprite = null
basic.showIcon(IconNames.Happy)
item = game.createSprite(2, 2)
basic.showIcon(IconNames.Sad)
```

![microbit-screenshot](https://user-images.githubusercontent.com/29712657/31384081-5234b1ee-adb5-11e7-8719-faf941afc2da.png)

Effect:

![brightness](https://user-images.githubusercontent.com/29712657/31384180-b28f8546-adb5-11e7-98b4-3194dcb4b8cc.gif)

This brightness setting cannot be changed, even if the brightness block is used before the icon is displayed:
```js
let item: game.LedSprite = null
basic.showIcon(IconNames.Happy)
item = game.createSprite(2, 2)
led.setBrightness(255)
basic.showIcon(IconNames.Sad)
```

![microbit-screenshot 1](https://user-images.githubusercontent.com/29712657/31384095-5fa33ff8-adb5-11e7-8fe4-5ae95b397702.png)

Versions:
makecode.microbit.org version: 0.13.27
Microsoft MakeCode version: 0.14.1
C++ runtime version: v2.0.0-rc11

**Comment by microbit-carlos** [comment]
Btw, this is not an emulator only issue, it can also be seen in the micro:bit.

**Comment by pelikhan** [comment]
The game engine turns on "greyscale" mode for rendering. It should probalby only do that when rendering sprits. Also icons should encode 255 per LED instead 1 to get full brightness in greyscale mode.

**Comment by microbit-mark** [comment]
Can you add Microbit Foundation tag @abchatra @pelikhan

**Comment by pelikhan** [comment]
Fixed in beta.

**Comment by microbit-carlos** [comment]
Thanks for the quick fix @pelikhan!
