### ISSUE TITLE
SystemTimer microseconds

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#3198]
Is there a way to access this DAL function from within MakeCode, it surfaces the micro-seconds value of the system timer. 

https://github.com/lancaster-university/microbit-dal/blob/master/source/core/MicroBitSystemTimer.cpp#L145

We see a lot of projects where people use the 'wait microseconds' block to implement software bit-bashed protocols, and they tend to be quite brittle.  I saw a great IR driver on hackster today, but they use wait_us and hand calibrated/tweaked delay values, and that will be quite brittle.

If this function was accessible as a MakeCode block 'running time microseconds', it would be possible to do non-brittle time horizon style software modulation loops that would be much more resilient to both changes in the underlying code, and the effects of interrupts coming in and out along the way. I'd even be happy for it to be surfaced with a truncation so that it fits into a smaller data type, as typically you only need it to last a second or two before wrapping to be used for time-horizon based software bit-bashing (one would use the running time ms for anything longer anyway).

![screen shot 2017-10-10 at 15 31 17](https://user-images.githubusercontent.com/25079586/31392147-661f3dc6-add0-11e7-952c-7826a69334dd.png)

**Comment by pelikhan** [comment]
We could only surface it as a 32bit integer so it would only work for short horizons.

**Comment by DavidWhaleMEF** [comment]
That's fine - if my maths is correct, a U32 running in 1uS increments would last just over 1 hour. That's more than enough (and if you wanted longer you would use 'running time ms' anyway.

The use case here is for timing short periods of time relatively accurately, so that it is less brittle to timing changes in the underlying code, and also less brittle to interrupt inserted delays. e.g. bit-bashing simple binary interfaces in a way that there is less jitter on the timing (and therefore making them more reliable in practice).

So, for all the scenarios I can think of this would be perfect.

**Comment by pelikhan** [comment]
Fixed in beta.

**Comment by DavidWhaleMEF** [comment]
Thanks @abchatra @pelikhan
