### ISSUE TITLE
generated sims.d.ts missing reference to enums.d.ts

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#32]
Assuming the user has a enum file in the libs, the sims.d.ts should add a reference to it.

**Comment by mmoskal** [comment]
I don't understand the problem - what is the exact scenario that doesn't work?

**Comment by pelikhan** [comment]
In sample, the shims typescript references enums.d.ts. The generated sims.d.ts does not reference enums.d.ts. It does not matter really but creates some squiglies in code.

**Comment by mmoskal** [comment]
I see no squiggles. sims.d.ts shouldn't have to reference enums.d.ts as they sit in the same directory and are part of the same project
