### ISSUE TITLE
Should be able to set start value of 'for loop' in blocks editor

### ISSUE THREAD

**Issue by Geoffree3** [Microsoft/pxt#3201]
The 'for loop' statement is unduly limited in that it can only start at zero. For instance, if we want to plot the LEDs across from right to left then it would be convenient to use 'for xposition = 4 to 0' rather than have to use 'for index = 0 to 4' 'set xposition to 4 - index'   (or the equivalent with index counting from 0 to -4). I cannot see a reason for not being able to set the first value, as in javascript etc. As in this example it does not simplify the code!

I've just noticed that Google Blockly has this  e.g.
<img width="411" alt="blocky for loop" src="https://user-images.githubusercontent.com/3199856/31469555-f360b75a-aed9-11e7-8f3e-66960ad572de.png">

**Comment by abchatra** [comment]
This is a deliberate design choice to keep the block simple. Advanced users have an option to specify the limits in javascript. By design.

**Comment by Geoffree3** [comment]
As with my example the design choice does not simplify the code!
