### ISSUE TITLE
The self-centering blocks editor is annoying!

### ISSUE THREAD

**Issue by Geoffree3** [Microsoft/pxt#3202]
You place a new block to the left of another, at what is the edge of the page, then extra space is added to the left and block on the right.  Any blocks on the right are then off the screen. Same for top and bottom.  The children get confused with the auto positioning as they loose the frame of reference and wonder where blocks have gone.  Often they think they have disappeared and add the blocks again!  Please turn this off!   Also, when editing an existing script, the editor does this auto-thingy, and it doesn't look the same as before, which again is inconsistent and can cause confusion.

**Comment by pelikhan** [comment]
Could you post a video repro?

**Comment by Geoffree3** [comment]
[blocks editor - small.mov.zip](https://github.com/Microsoft/pxt/files/1380085/blocks.editor.-.small.mov.zip)

(it wouldn't accept .mov format so have zipped it)

It shows the rather unexpected behaviour of the Format Code function, the automatic addition of a 'margin' around blocks placed close to the edge and also the switching to another project where the blocks go off the screen.  As I said, the main problem with adding a 'margin' is that, in terms of your frame of reference, all the blocks are shifted across the page, which is unexpected and causes confusion. No doubt it was thought to be helpful, in giving space to put extra blocks but in actual use, I and my students, find it disconcerting and tend to loose blocks!

**Comment by abchatra** [comment]
One workaround you can minimize the simulator to see extra space for blocks works space.
