### ISSUE TITLE
Why does the language menu option always show 'German' as being the current language?

### ISSUE THREAD

**Issue by Geoffree3** [Microsoft/pxt#3205]
Why does the language menu option always show 'German' as being the current language when the menu is opened?   Rather confusing when you are using any other language!
For example when using english the menu opens as:
![language menu](https://user-images.githubusercontent.com/3199856/31470733-37323f00-aedd-11e7-973c-7e9a306331fc.png)

**Comment by abchatra** [comment]
blue cursor indicates focus for selection (for accessibility) and doesn't indicate the language which is selected.
