### ISSUE TITLE
[Enhancement] New 'comment block' to encourage in code documentation

### ISSUE THREAD

**Issue by Geoffree3** [Microsoft/pxt#3206]
It would be helpful, both for students and teachers, to be able to add a comments in the code. This would be easily achieved with a normal 'locking' block, with a text field.  We should teach the children to document their code from an early age.  Adding a comment to an event is useful, but not enough.

**Comment by pelikhan** [comment]
Currently, you can right click and choose "Add Comment' in the context menu.

**Comment by Geoffree3** [comment]
Thanks for the tip.  However, to read the comment, the 'comment' has to be opened which also can obscure other blocks, so this is not ideal.  I was more thinking of an inline 'comment block' with a single line text field.  The block length expands as more text is entered.    As I said, I'm trying to encourage the children to explain what they are doing, which is not always obvious!  Also, when designing/outlining code, the children can add placeholder comments, before they add the actual blocks to achieve that particular task.

**Comment by pelikhan** [comment]
Comments are a built feature in blockly, the library used to represent blocks in the editor. It needs to be fixed upstream.
