### ISSUE TITLE
[Enhancement] Pass parameters to functions in blocks editor

### ISSUE THREAD

**Issue by Geoffree3** [Microsoft/pxt#3207]
I note that parameters can be passed to functions.  This would be a useful feature on the blocks editor, at least passing one value.  It is available in the Radio events.  This would :
a) develop good programming practice
b) avoid the use of global variable (again, good practice)
c) be consistent with other programming languages
d) simplify the code

Again it's in Blockly so why not use it?
<img width="284" alt="max function" src="https://user-images.githubusercontent.com/3199856/31470547-c15c8786-aedc-11e7-99b3-b93fdf908d5c.png">

**Comment by abchatra** [comment]
We have a fork of blockly and enhance it. We don't follow blockly semantics. We don't plan to add parameters in the functions as it is advanced feature. Javascript is the way for advanced
