### ISSUE TITLE
[Enhancement] Return value of a function

### ISSUE THREAD

**Issue by Geoffree3** [Microsoft/pxt#3208]
Returning a value would be easily achieved with a 'return' statement (with one parameter). Functions returning a value would then appear as a block, similar to a variable, and hence be able to be used as such.  As with passing parameters, this would :
a) develop good programming practice
b) avoid the use of global variable (again, good practice)
c) be consistent with other programming languages
d) simplify the code

as #3207

**Comment by abchatra** [comment]
Not planned in blocks editor. Available in javascript.
