### ISSUE TITLE
add destructors?

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#321]
Given that we use ref counting it would be relatively easy to add them (say a special method called `dispose`, `finalize` or `destroy`). While JS doesn't have them, some other high-level runtimes do (.NET,  JVM, node.js with additional modules etc). It's possible we would need them for freeing some resources (pins etc).

CC @tballmsft @pelikhan

**Comment by pelikhan** [comment]
Monaco extensively uses ``dispose``. Sounds like a good idea as we are dealing with very limited resources.

**Comment by tballmsft** [comment]
Agreed

**Comment by mmoskal** [comment]
Any thoughts on naming the method? Note, that it would be still possible to call it manually, and we should avoid surprise if it's called automatically.
