### ISSUE TITLE
blockly files in release manifest seem incorrect/ missing

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#3211]
The list of files in the manifest for blockly is missing cursors and have different sound file extensions. Needs review
```
# blockly
/blb/blockly/blockly_compressed.js
/blb/blockly/blocks_compressed.js
/blb/blockly/msg/js/en.js
/cdn/blockly/media/sprites.png
/cdn/blockly/media/click.mp3
/cdn/blockly/media/disconnect.wav
/cdn/blockly/media/delete.mp3
```

**Comment by abchatra** [comment]
What is the impact?

**Comment by microsoftsam** [comment]
Do we need the cursors in there? I believe Blockly handles the case for when they're not there. As for the other media files, for each sound there's a mp3, wav and ogg format in Blockly. It does a check on load to see whether or not it can play that specific type / if it exists. So we only really need one file cached. 

All other icon files are now data-uri embedded. Is there anything else you were thinking of?

**Comment by pelikhan** [comment]
We have a mix of .mp3 and .wav files. Why aren't we using the same format all accross? 

Blockly tries to load some custom cursors. Could we get rid of those?

![image](https://user-images.githubusercontent.com/4175913/32362588-d33a74ac-c027-11e7-9c03-c3b56ca1feba.png)

**Comment by microsoftsam** [comment]
Almost certain the custom cursors are just for IE. Will need to do a bit of digging to figure out if we can get rid of them.

As for the mix of files, yes all the files that we cache should be the same format. Not sure why we did different files.

**Comment by abchatra** [comment]
I don't understand the impact of this bug. Please reopen with the repro steps.
