### ISSUE TITLE
Serial Write Buffer throws simulator error

### ISSUE THREAD

**Issue by birdbraintech** [Microsoft/pxt#3217]
It appears that the serial write buffer block/function doesn't have a dummy shim function to prevent error messages, so the simulator throws an error when you use it in a program, for example:
![image](https://user-images.githubusercontent.com/5341752/31498451-f0aebdf8-af2f-11e7-852a-b9d3acddb885.png)

The actual function works beautifully. I'm building a library of blocks that build on top of write buffer to communicate from the micro:bit via serial with a daughterboard, and so I'm concerned about people thinking there's something wrong with their program when this error message pops up. 

This is similar to an issue with one of the Bluetooth functions described  here:((https://github.com/Microsoft/pxt/issues/2493))

**Comment by microbit-mark** [comment]
For our reference microbit-support:2982

**Comment by microbit-mark** [comment]
@abchatra @pelikhan Just a nudge to triage this issue.

**Comment by microbit-mark** [comment]
Nudging this for an update

**Comment by microbit-mark** [comment]
Nudging this for an update. https://github.com/Microsoft/pxt/issues/3193 was fixed in a couple of days, is this a similar fix?

**Comment by abchatra** [comment]
There is no shadow block for write buffer. You will need to drop something which produces buffer first in the blocks to fill the gap.

![image](https://user-images.githubusercontent.com/6107272/32789078-bf59e74c-c90f-11e7-8b47-761773b8fcbd.png)

This block is rarely used and the fix is not straight forward. It is low priority for us.

**Comment by birdbraintech** [comment]
I am not actually using the block in my extension, but the underlying javascript function, for example:

cmdBuff = pins.createBuffer(1)
cmdBuff.setNumber(NumberFormat.UInt8LE, 0, 88) // Ascii value of 'X'
serial.writeBuffer(cmdBuff)

I get the same error when writing it in JS as when using the block. That said, I understand if it is a low priority issue - I'm sure not many users are using writeBuffer. Is there a way for a blocks developer to cause the simulator to be inactivated or hidden when loading a blocks package? I am fine if the simulator is non-functional, I just want to have it not throw worrisome errors at the user.

**Comment by pelikhan** [comment]
The simulator shim is missing. It was added in master.

**Comment by abchatra** [comment]
@birdbraintech Thanks for explaining the issue. Your program is a valid program. A valid program should always work in the simulator as it works on the board. We will port the fix to V0.

Sorry, I was confused looking at the snapshot, which is an invalid program. Ideally we should never allow that to happen in the blocks but we have various issues in that front.

**Comment by microbit-mark** [comment]
Have opened in pxt-microbit
