### ISSUE TITLE
don't use std::vector in RefCollection

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#322]
std::vector uses 3 words with any elements, and we could easily do with 2 (pointers, and two 16 bit sizes).

The grow policy is probably also over aggressive given our memory constraints.

**Comment by mmoskal** [comment]
This is for https://github.com/Microsoft/pxt-microbit-core - but no one looks at issue list there

**Comment by abchatra** [comment]
Fixed by Microsoft/pxt-microbit#326
