### ISSUE TITLE
There is a difference between Safari and other browsers in "Projects"

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#3225]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Click "Projects" 

**Safari:**
![31538039-d898b554-b036-11e7-9d5a-a2897604f1ec](https://user-images.githubusercontent.com/23497626/31538935-f227cdc8-afbb-11e7-9af5-d176344b3f54.png)

**Other browsers:**
![screen shot 2017-10-13 at 3 16 21 pm](https://user-images.githubusercontent.com/23497626/31538079-fcf52784-b036-11e7-809c-fe3d69f04fef.png)

**Comment by abchatra** [comment]
@pelikhan does this code still needs to be there on safari?

**Comment by pelikhan** [comment]
This limitation should only activate on mobile Safari. What OS is this?

**Comment by WendyFeng01** [comment]
This issue repro on Mac desktop, OS version is 11.0(12604.1.38.1.7)

**Comment by abchatra** [comment]
Can we get rid of this code as we are redirecting for a while?

**Comment by pelikhan** [comment]
The problem was that on mobile safari input type="file" did not work.

**Comment by WendyFeng01** [comment]
Close as fixed
