### ISSUE TITLE
Some javascript code has no colour on documentation

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#3227]
**Repro step:**

- Navigate to https://makecode.microbit.org/beta
- Click "?Help" and choose "JavaScript"
- Click anyone such as "Functions"

**Except results:**
The keyword and class should be coloured
![capture](https://user-images.githubusercontent.com/23497626/31540108-8c23b286-afbf-11e7-94f4-14d6f4c9cc4a.PNG)

**Actual results:**
They are all black
![capture2](https://user-images.githubusercontent.com/23497626/31540115-90d203a0-afbf-11e7-8762-d085488a89e7.PNG)

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/3253

**Comment by abchatra** [comment]
We decided not to fix this as we there are other issues with the script. They are ok to be this way.
