### ISSUE TITLE
Turn on "High Contrast", many items can't be selected when mouse hovering on

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#3229]
**Repro step:**

- Navigate to https://makecode.microbit.org/beta 
- Click "Setting" -> "High Contrast On"
- Click "Projects" -> "Projects" or "Examples"
- Using the mouse to hover the following items

**Except results:**
![border](https://user-images.githubusercontent.com/23497626/31540958-f2b686a2-afc1-11e7-9f3a-7d60abef6223.gif)

**Actual results:**
![noborder](https://user-images.githubusercontent.com/23497626/31541013-26022796-afc2-11e7-947c-865da4027db7.gif)

**Comment by Helen09** [comment]
Closed as fixed
