### ISSUE TITLE
Code Connection for Minecraft will not work for student accounts

### ISSUE THREAD

**Issue by philgolden** [Microsoft/pxt#3230]
We are having an issue with MakeCode using Code Connection for Minecraft Education. Specifically it will not work for student accounts (subject to web filtering) on the school network. It works perfectly for admin accounts on the school network, or for student accounts on an external network. Failure signature is:
- connection appears to work (get connected to Code Connection server message in Minecraft)
- when we try to execute code, it has no effect in Minecraft (although the command does not give an error)
- when we try to access a MakeCode tutorial, get get a message saying 'having trouble downloading' (see attached) and it will not work
We have worked with the network admin who assures us that ports 19132 and 19131 (mentioned on ME's troubleshooting page) are open, and the web filter log does not show anything being blocked. We are at a standstill, and would massively appreciate help. As a specific question, what websites are we trying to access when downloaded a MakeCode tutorial in Code Connection?

![tutorialerrormessage](https://user-images.githubusercontent.com/24957105/31545992-6bfd30f4-b019-11e7-86ac-39f9613c60c2.jpg)

**Comment by pelikhan** [comment]
Make sure these domains are unlocked: https://minecraft.makecode.com/faq

Could you try to navigate to https://minecraft.makecode.com/, turn on the chrome debugger and start the tutorial? The javascript console output should have useful info.

**Comment by philgolden** [comment]
Peli,

This was brilliant, thanks. The issue seems to be that the school had an
extra level of web filtering that even the head teacher was not aware of,
and it is blocking pxt.io

I have put in a request to the relevant company to have it unblocked, and
hoping this will be implemented tomorrow. I have load of ideas for
Minecraft Makecode, and I can't wait to use it in code club!

Phil

**Comment by pelikhan** [comment]
@mmoskal could we migrate our API call to MakeCode.com? One less domain to validate.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmoskal** [comment]
@pelikhan @abchatra the `/api/*` routing works on any domain that reaches the server, with no redirects. We should probably use the target domain, eg `makecode.microbit.org`.
