### ISSUE TITLE
Embed options

### ISSUE THREAD

**Issue by ricardogo** [Microsoft/pxt#3231]
Hey guys,

Loving all this work, the editor is looking awesome. So awesome I'd love to embed it inline with some tutorials I created.

I was wondering if there are any parameters I can pass through the embed code to customise that gets embedded. For example, I'd like to drop the simulator and just have the code. Did a bit of research and couldn't find any documentation around this.

Thanks!
Ricardo

**Comment by abchatra** [comment]
You can share and embed the program in your editor. Let us know if you encounter any issues.

![image](https://user-images.githubusercontent.com/6107272/31570058-31b752aa-b035-11e7-9981-c4ca22cea2b2.png)


![image](https://user-images.githubusercontent.com/6107272/31570066-40c7a0ce-b035-11e7-811a-91257e9c31f1.png)

**Comment by ricardogo** [comment]
Hi abchatra,
I may not have explained myself correctly on my original post.
I am aware of the embedding capabilities, but was wondering if there are any parameters we can pass to change what gets embedded. For example, hiding the simulator by default.
An example of this implementation is Youtube's embeds, where you can hide controls and customise several features.

Thanks!
Ricardo

**Comment by abchatra** [comment]
We don't have that ability today. Please let us know all the options you would like. We definitely consider adding it in future.

**Comment by ricardogo** [comment]
Gave this a bit of thought. Maybe this is a community thing, as different people will have different needs, but my immediate needs are:
- simulator on or off
- hide all the buttons & UI except the download button (and the "take me to the original URL" button)

Thanks!
R
