### ISSUE TITLE
Stream to Cloud/Live data/Chrome Extension - Serial Driver

### ISSUE THREAD

**Issue by damianburrin** [Microsoft/pxt#3232]
With the Chrome plugin you used to be able to stream to the cloud via the serial port.  But now when i plug the microbit in - even with the serial being picked up and a com port active (Mbed serial driver) Chome no longer picks up the live data from the micro:Bit.

Has something changed or is this a bug?

Thanks

**Comment by abchatra** [comment]
Stream to cloud feature was a prototype which we decided not to support at this moment (for various backend related issues).  

Can you elaborate on your issue? Are you able to see data locally? Also if you let us know your reasons to stream to cloud. This will help us prioritize the feature.

Feature request: Stream to cloud.

**Comment by machinehistories** [comment]
I am excited to stream the data to cloud iot tools such as azure or
adafruit.io. I want the students to be able to visualize the data over
extended periods. I would also like to use iftt. I've noticed a few great
you tube videos showing streaming features. Also at the current time the
serial extension isn't working so it would be great to at least use that in
the meantime. Do you think web Bluetooth will be implemented on the make
code site it seams like a great fit. There are some demos showing the
microbit and web Bluetooth and it works well. Thanks

On Oct 15, 2017 8:07 PM, "Abhijith Chatra" <notifications@github.com> wrote:

Stream to cloud feature was a prototype which we decided not to support at
this moment (for various backend related issues).

Can you elaborate on your issue? Are you able to see data locally? Also if
you let us know your reasons to stream to cloud. This will help us
prioritize the feature.

Feature request: Stream to cloud.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/pxt/issues/3232#issuecomment-336768994>, or mute
the thread

**Comment by abchatra** [comment]
Thanks @machinehistories. Have you tried our Windows 10 app for Adafruit Circuit playground express? https://www.microsoft.com/en-us/store/p/makecode-for- adafruit/9pgzhwsk0pgd
You should be able to stream data locally there. We will have discussion on stream to cloud.

**Comment by damianburrin** [comment]
>Stream to cloud feature was a prototype which we decided not to support at this moment (for various >backend related issues).
>Can you elaborate on your issue? Are you able to see data locally? Also if you let us know your reasons >to stream to cloud. This will help us prioritize the feature.

Thanks for the feedback.  I must be missing something or in the wrong group.  The stream to cloud feature is documented on the website as a feature (https://makecode.microbit.org/streaming) and the plugin V0.70 is on the webstore.  I'm specifically talking about this feature with the BBC Micro:bits implementation of PXT.

The URL shift that happened to makecode in July broke the feature.

Thanks - i'll see if I can find the right group

DAmian

**Comment by machinehistories** [comment]
How about the serial extension, is that fixed for windows 10? Like DAmian
mentioned there are definite issues with the file paths referenced in the
code for the extension. I am really sorry to hear that about not supporting
the stream function with the microbit. Considering the microbit has ble it
is a much better tool for teaching students about IOT applications. It
seams like a missed opportunity. How about a block that enables a webhook
or block that offers a connection to an external cloud service.  - jason

**Comment by machinehistories** [comment]
Can you please let me know if the google serial extension is going to be
repaired to work with the new microbit/pxt site. thanks

**Comment by damianburrin** [comment]
It would be good to havethis back.  I used this in class and was a great demo.  We should be developing the microbit not removing features.Its still a documented feature in the online manual.  Im sure its more complicated but it is interesting this broke when the url moved again.On 21 Oct 2017 21:42, machinehistories <notifications@github.com> wrote:Can you please let me know if the google serial extension is going to be
repaired to work with the new microbit/pxt site. thanks

**Comment by abchatra** [comment]
Couple of different issues are discussed in this thread. 

Update for Micro:bit extension for Chrome:
We are in the process of fixing the existing extension. As this involves a cumbersome release process, it is taking longer than expected. I will update as soon as the update is in the chrome store. 

Installing an extension is still a barrier for lot of teachers. Website works on all devices and browsers.
For a long term design perspective, ideally we want to move to a pure web based solution such as webusb (https://wicg.github.io/webusb/) to access USB device and show serial data.  Although webusb is still in nascent stage and it will take years for the browsers to catch up.

**Comment by damianburrin** [comment]
Great news if tbe extension is being fixed.  It took a while to be 'allowed' this at my school so for it to stop working was frustrsitingOn 24 Oct 2017 19:29, Abhijith Chatra <notifications@github.com> wrote:Couple of different issues are discussed in this thread.
Update for Micro:bit extension for Chrome:
We are in the process of fixing the existing extension. As this involves a cumbersome release process, it is taking longer than expected. I will update as soon as the update is in the chrome store.
Installing an extension is still a barrier for lot of teachers. Website works on all devices and browsers.
For a long term design perspective, ideally we want to move to a pure web based solution such as webusb (https://wicg.github.io/webusb/) to access USB device and show serial data.  Although webusb is still in nascent stage and it will take years for the browsers to catch up.

**Comment by abchatra** [comment]
@damianburrin Just to clarify extension is used for serial data and if we implement WebUSB protocol and the serial data is available to browser natively it would serve your purpose as well right? 

It would be great if you walk us through your usage of extension.

**Comment by machinehistories** [comment]
Exciting and glad to hear it is being fixed.

**Comment by damianburrin** [comment]
I don’t do anything “special” but it’s the stream to cloud native support with Azzure that i use and would really like back.

This is the youtube video that i use to support staff from my CAS hub https://www.youtube.com/watch?v=JQ-adInOCx4&list=PLvZXTXiQDCe7n5k7OqJONYOU6sIBQgHp1&index=15&t=1s and this worksheet i use to do a practical demo to teachers.  http://www.microbitsandbobs.co.uk/projects/Project_26_Making_a_Remote_Sensor.pdf

The tutorial i did for Lee Stott at Microsoft is half-way down this page https://blogs.msdn.microsoft.com/uk_faculty_connection/2016/08/01/getting-started-microbit-microsofts-new-www-codethemicrobit-com-environment/ which is what is use with my students

This feature was really nice as it introduced the idea of interconnectivity.  I tend to move from this to using App inventor with it IOT extension and make a remote temp sensor for my “Fizzy Pop” that sends a message to my phone when its at the optimal temperature.

Thank you for the support in trying to resolve the issues

Damian

**Comment by machinehistories** [comment]
Damian's videos are what really got me excited about the microbit and
motivated me to purchase one. I was planning on using the stream to web
function as an intro to IOT in my class at Art Center College of Design. I
was really let down when I was preparing for my in class demo and realized
it didn't work.  In addition to the serial function being operational in
the microbit extension, I would like to be able to use the stream to web
feature. It just doesn't make sense to take away features preferably we
want to have access to more features not less. The coolest thing about the
microbit is that it can do a variety of things and it can be used a
fantastic inro to many different technologies. Please maintain support for
stream feature since it is just too important a topic to miss out on. -
jason

**Comment by pelikhan** [comment]
Unfortunately, it seems that extensions do not have access to serial anymore. I don't think the Chrome extension can be supported going forward.

**Comment by abchatra** [comment]
Adding on to Peli's reply.

Chrome has removed chrome.serial API for access from extension. It is not possible for the extension to access serial anymore. 

We do think there is a genuine need for the access serial.  Our plan is to concentrate our efforts on webusb going forward. This will take a longer than we expected and will update you on our progress. Thanks for understanding.

**Comment by damianburrin** [comment]
Oh that is a shame.Hopefully the wrbusb will resolve thisOn 31 Oct 2017 18:47, Abhijith Chatra <notifications@github.com> wrote:Adding on to Peli's reply.
Chrome has removed chrome.serial API for access from extension. It is not possible for the extension to access serial anymore.
We do think there is a genuine need for the access serial.  Our plan is to concentrate our efforts on webusb going forward. This will take a longer than we expected and will update you on our progress. Thanks for understanding.

**Comment by machinehistories** [comment]
Now that webusb is working in the beta editor do you think it's possible to put the stream to cloud function back in for testing.

**Comment by abchatra** [comment]
Thanks for the request. Yes, with webusb we have access to serial now and seems to be working well. For streaming to cloud we still need to build a backend infrastructure (it was just a prototype in the past) and it has to be GDPR compliant. Can you please open a feature request on pxt-microbit with the scenario you need? There might be various other ways we could lighten up the scenario.
