### ISSUE TITLE
`on start` block does not translate in the hint dialog of the getting started tutorial

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#3237]
The capture below is the hint dialog of the 1st step of the getting started tutorial. The `on start` block shows in English.

![image](https://user-images.githubusercontent.com/485416/31572432-cb3b9d86-b0e0-11e7-91a2-045b6892e29f.png)

**Comment by sgk** [comment]
Oh, this is just common with help documents.

![image](https://user-images.githubusercontent.com/485416/31572961-66b95a7c-b0ec-11e7-8079-f648ea4e46fd.png)

**Comment by pelikhan** [comment]
"on start" is currently stored in the strings.json file which is not injected in the doc file. Arrays, math and other will have the same issue.

**Comment by sgk** [comment]
It seems to be fixed. Thanks!
