### ISSUE TITLE
Code Connection no longer working for Minecraft 1.2 (Bedrock)

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/pxt#3246]
Channel 9 [demonstrated](https://channel9.msdn.com/Blogs/Seth-Juarez/Announcing-Microsoft-MakeCode-for-Minecraft-Windows-10) Code Connection working with Minecraft for Windows (on the Windows Store). Recently users have been getting this error:

![image](https://user-images.githubusercontent.com/7173984/31590459-99def518-b1de-11e7-9d95-1559dbb64717.png)

The people in the video [claim](https://twitter.com/sethjuarez/status/918987019623137280) the bug is going to fixed sometime this week, but I will add an entry here so the issue can be tracked accordingly.

**Comment by abchatra** [comment]
@rogersachan we are tracking the issue and fix for this is on tracked to be released by mid next week on the Minecraft PE as we speak. I will update the issue as soon as the fix is available.

Thank you very much for reporting.

**Comment by abchatra** [comment]
Fixed in Minecraft Windows 10 v1.2.3
