### ISSUE TITLE
File System package simulator error

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#3250]
In the File System, the `settings save number ["_"] as [_]` causes the following simulator error:
```
Program Error: pxsim.files.createDirectory is not a function
```
![fs](https://user-images.githubusercontent.com/29712657/31603878-77868ab4-b259-11e7-987d-b7131a9c80e4.gif)

Same thing happens with the `settings  read number ["_"]` block.

**Comment by abchatra** [comment]
There is no simulator support for packages today.

**Comment by microbit-carlos** [comment]
Even if that's the case, this errror is still shown in beta:

![image](https://user-images.githubusercontent.com/29712657/42264214-e8568ef2-7f67-11e8-8f1b-a100adbd4f9c.png)

Taking today at these versions:

makecode.microbit.org version: 0.14.42
Microsoft MakeCode version: 0.19.10
C++ runtime version: v2.0.0-rc11


And in alpha:

![image](https://user-images.githubusercontent.com/29712657/42264404-6babb5b6-7f68-11e8-96b9-50d149a97f1f.png)

makecode.microbit.org version:  1.1.32
Microsoft MakeCode version:  3.20.11

**Comment by abchatra** [comment]
I have ported to microbit repo https://github.com/Microsoft/pxt-microbit/issues/923

**Comment by microbit-carlos** [comment]
Thanks @abchatra!
