### ISSUE TITLE
Package approval docs no longer visible 

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#3251]
Hiya,

It looks like since the package writing docs went up a level into the generic MakeCode docs the link to the micro:bit approval process got dropped.

It used to be https://makecode.microbit.org/packages/approval but now https://makecode.microbit.org/packages/build-your-own links to https://makecode.com/packages/getting-started which has a generic approval page.

Could we rectify this so MBF approval doc is still visible please?

**Comment by abchatra** [comment]
@ganicke can you please help here?

**Comment by ganicke** [comment]
Brought back approval with a build package doc.

Added in: https://github.com/Microsoft/pxt-microbit/pull/560
