### ISSUE TITLE
Can edit a function name to be blank in block mode

### ISSUE THREAD

**Issue by brachbach** [Microsoft/pxt#3265]
1. Create a function in block mode
2. Rename the function to blank
3. The function name will show as blank in block mode
4. In text mode, its name will be "_"

Would be better to disallow changing the name to blank in blocks mode

**Comment by microsoftsam** [comment]
Not sure I understand the repro steps, 
If you try and and a function with no name, it will simply not add a function and close the dialog? 

Are you seeing otherwise?

**Comment by brachbach** [comment]
Sorry, my bad, had the wrong repro steps. Just updated the issue name and my original comment.

**Comment by microsoftsam** [comment]
Ah I see. Yes we should fix on the block side.

**Comment by microsoftsam** [comment]
@brachbach I know where to fix this issue. I have a question for you. 
Do you think it would make sense as you're editing the function name, that if you type in an empty field, we return you back to the original value of the function. 
Or 
We replace the function name with "unnamed"

I'm leaning towards the first option.

**Comment by brachbach** [comment]
I agree that the first option is better. I'll check w/ our designers though to make sure they agree.

**Comment by cwest-ww** [comment]
Return user back to original value. Thx.
