### ISSUE TITLE
"else if" conditions don't have shadow blocks

### ISSUE THREAD

**Issue by brachbach** [Microsoft/pxt#3266]
See attached images for expected vs. actual results when you click the + button on an "if" block to add a new "else if" condition

Expected:
<img width="522" alt="expected" src="https://user-images.githubusercontent.com/16952006/31682651-95b6de72-b32f-11e7-8c5d-fae35019c381.png">

Actual:
<img width="498" alt="actual" src="https://user-images.githubusercontent.com/16952006/31682650-959c6d8a-b32f-11e7-90da-883303eaa06e.png">

**Comment by microsoftsam** [comment]
@riknoll I don't think the mutation for this in pxt-blockly is capable of adding a shadow block, it's just in charge of the shape of the block (ie: making sure there's a value field there). 
What are your thoughts on the best way to insert a shadow in that field?

**Comment by IBYuMe** [comment]
@samelhusseini  do you have any thoughts on this issue?

I think we have a currently open issue which is related to these shadow blocks not appearing.
You can see a video of the behavior here: https://drive.google.com/file/d/1wQU0yJ6-OrnFN3kr4yxTQPzqWO4tUNxU/view?usp=sharing

but essentially if there are multiple 'default' (shadow?) true/false block in the parameter of an else statement... and then one else statement is deleted, the shadow blocks for the other if/else statements are deleted as well.


WW issue link: https://makewonder.atlassian.net/browse/ANA-1611
