### ISSUE TITLE
Dropdowns from blocks mode still onscreeen after switching to text mode

### ISSUE THREAD

**Issue by brachbach** [Microsoft/pxt#3267]
1. open a dropdown in blocks mode
2. switch to text mode

<img width="580" alt="screen shot 2017-10-17 at 11 40 53 am" src="https://user-images.githubusercontent.com/16952006/31682845-272b52fc-b330-11e7-9e80-24e1b4dd082d.png">

**Comment by microsoftsam** [comment]
Fixed this recently, in PR: https://github.com/Microsoft/pxt/pull/3234
by closing all flyouts / dropdowns when switching between editors.

**Comment by microsoftsam** [comment]
Closing. Please re-open if you are still seeing this.
