### ISSUE TITLE
links are hardly visible

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#3270]
The links that are not bold are quite hard to distinguish from the black text, not to mention the blue one in a box, see:

-----------------
<img width="476" alt="screen shot 2017-10-18 at 07 26 41" src="https://user-images.githubusercontent.com/10673976/31703760-02eea834-b3d6-11e7-9797-f1c73e2bb182.png">

------------------

<img width="490" alt="screen shot 2017-10-18 at 07 26 56" src="https://user-images.githubusercontent.com/10673976/31703765-06d499f4-b3d6-11e7-985e-2ac07af9ebc3.png">

------------------

Instead of `#004d99` I would suggest something like `#0066dd`

------------------

<img width="368" alt="screen shot 2017-10-18 at 07 35 43" src="https://user-images.githubusercontent.com/10673976/31703957-fbb42ec6-b3d6-11e7-90c7-8f30c28c7264.png">

------------------

<img width="522" alt="screen shot 2017-10-18 at 07 35 07" src="https://user-images.githubusercontent.com/10673976/31704006-424158b4-b3d7-11e7-8a0a-4bd258b8def9.png">

------------------

Also, adding underline on :hover and removing color change on :hover.

CC @microsoftsam

**Comment by microsoftsam** [comment]
Added underline on :hover. 

Changed link color in pxt to ``#4183c4``

I chose that color as that's what GitBooks used for there link color. I'm going off the assumption that they have chosen good link colors for reading document pages.

That link color contrasts gets a contrast ratio of 4 with white and 5.3 with black (to differentiate from other text).

**Comment by microsoftsam** [comment]
Please close if you're happy with that color choice. You won't see the changes reflected until the next time we deploy semantic.css to doccdn.

**Comment by mmoskal** [comment]
Yes, this is much better, thank you! I think good to re-deploy?

**Comment by microsoftsam** [comment]
Yes. I'll re-deploy sometime this week.
I've been deploying from v0, and I want to try and do it from master this week. Previously been deploying from v0 being careful not to break v0 docs.

**Comment by abchatra** [comment]
Is this fixed?

**Comment by samelhusseini** [comment]
Yes
