### ISSUE TITLE
Filesystem: settings read number, add one and save it crashes at 10

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#3272]
microbit.org-ticket: 3006

The following program uses the File system "settings" block to store a number and add one on each reset. After 10 resets my the micro:bit crashes. 

**Code:**

![microbit-screenshot](https://user-images.githubusercontent.com/29712657/31715816-271eb9b6-b3fd-11e7-92c9-0f0492031b36.png)

```
let cal = 0
cal = files.settingsReadNumber("cal")
basic.showNumber(cal)
cal = cal + 1
files.settingsSaveNumber("cal", cal)
basic.showNumber(cal)
```

https://makecode.microbit.org/_iPbajwAA0eT8

**Effect:**

The program reads the value saved, displays it, adds one, saves it, and then displays the number it just saved.
This works fine until it reaches the 9 to 10 transition. The following gif shows:
* 7->8
* reset
* 8->9
* reset
* 9 -> error
* reset, nothing happens
* reset, nothing happens
* reset, nothing happens

![fs_numbers-iloveimg-compressed](https://user-images.githubusercontent.com/29712657/31715605-71df2de2-b3fc-11e7-846b-9e975d0e9930.gif)

This is not explicity to storing the number 10, as if I change the `cal = cal + 1` line with any other value (like `cal = cal + 10`) it still fails after 10 resets.

**Comment by microbit-mark** [comment]
@pelikhan are you able to comment on this issue?

**Comment by microbit-mark** [comment]
nudging again for an update

**Comment by microbit-mark** [comment]
nudging again for an update @abchatra @pelikhan

**Comment by microbit-carlos** [comment]
Moved to https://github.com/Microsoft/pxt-microbit/issues/635.
