### ISSUE TITLE
embedded editor breaks backbutton of browser

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3273]
If you put embed code in a webpage (my case is wordpress blog) it breaks the behavior of the back button of the browser. If you press back it just reloads the embedded editor. (Even if you press it multiple times like a maniac)

This **does not** happen when you embed the **simulator**. It **does** happen when you embed the **code editor.** Example page: http://tiigbg.se/microbit/2017/10/14/fibonacci/
Try going there and then press the back button.

**Comment by jaustin** [comment]
I can't reproduce this in either Firefox or Chrome on mac OS with the link above. Do you have any browser extensions that might be involved?

**Comment by nielsswinkels** [comment]
seems like it does not happen when you have makecode set to english. I guess that in other languages it reloads when it is done loading the language?

**Comment by riknoll** [comment]
I can reproduce this in IE11
