### ISSUE TITLE
Icon display is not clear under "High Contrast On" mode.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3280]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Click "_More..._ " and choose "_High Contrast On_"
- Then click " _?(Help)_ " and choose "_Getting Started_"
- Choose "_step 7_" and click "_Finish_"

**Expected result:**
Under "_High Contrast on_" mode, the icon should shows clear like following picture:
![under_common_module_icon](https://user-images.githubusercontent.com/17866936/31757354-395b8eae-b4db-11e7-9f58-99786297b257.PNG)

**Actual result:**
![icon_not_clear](https://user-images.githubusercontent.com/17866936/31757358-3e83a006-b4db-11e7-9d29-316cb63666f2.PNG)

**Comment by Helen09** [comment]
The issue still repro, for some changes, new **rero steps**:
Click "Projects" -> "Projects" ->"Flashing Heart" ->Click to the seventh step -> click "Finish"

**Comment by samelhusseini** [comment]
Won't fix. Fixing this is non trivial and the icon is aesthetic and not crucial.
