### ISSUE TITLE
"Menu bar" keep the checked state after clicking blank space.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3281]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Click any item such as "_Projects, Share, ?..._ "
- After selected, if it pop out a window, closed it and clicked blank space. if not, just clicked blank space.

**Expected result:**
![0fa18ddb-c7cd-4221-92fe-23285f26b6bd](https://user-images.githubusercontent.com/17866936/31758345-aa1c1dbc-b4df-11e7-8272-ddf480d290be.gif)

**Actual result:**
![8e2a0b49-17b7-4684-a849-af99500b65f9](https://user-images.githubusercontent.com/17866936/31758415-f0684034-b4df-11e7-8583-a1e31e2c54f5.gif)

**Comment by abchatra** [comment]
This is as expected. Menu's retain their selection. Help in itself is a menu item.
