### ISSUE TITLE
The input floats on the page.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3282]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Switch from "_Blocks_" to " _{}JavaScript_" and input " _basic.showNumber([12345].length)_ " and  switch back to "_Blocks_", then
![7b7f46e3-7eb8-47b2-8754-fdc63027d3d9](https://user-images.githubusercontent.com/17866936/31759466-11dff30c-b4e4-11e7-840c-a9a8bf1cdb31.gif)

**Comment by microsoftsam** [comment]
z-index issue. Maybe we should merge the z-index fixes to v0.
