### ISSUE TITLE
There is error message when load the package "Bluetooth-max6675" after load the package "max6675"

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#3284]
Repro steps:
• Navigate to https://makecode.microbit.org/beta 
• Click "Add Package" and input "max" in the InputBox of "search"
• Click the "max6675" in the search result 
• Click "Add Package" and input "max" in the InputBox of "search"
• Click the "Bluetooth-max6675" in the search result

Expected result:
1. The package "max6675" could be loaded
2. The package "Bluetooth-max6675" could be loaded and there is no error message

Actual result:
1. The package "max6675" could not be loaded
2. The package "Bluetooth-max6675" could be loaded, but there is error message

Additional information:
If didn't load the package "max6675"  before loading the package "Bluetooth-max6675", the package "Bluetooth-max6675"could be loaded and there is no error message

![package-max](https://user-images.githubusercontent.com/11880996/31765846-619a10ee-b4f8-11e7-90a7-5165062be423.gif)

**Comment by abchatra** [comment]
This is fixed in alpha. Please validate and let me know.
