### ISSUE TITLE
The package "Code Dojo Olney" could not be searched

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#3285]
Repro steps:
• Navigate to https://makecode.microbit.org/beta 
• Click "Add Package" and input "code" in the InputBox of "search"

Expected result:
 The package "Code Dojo Olney" could be searched
 Actual result:
The package "Code Dojo Olney" could not be searched

![package](https://user-images.githubusercontent.com/11880996/31765986-e192a3c4-b4f8-11e7-8f7c-306a21220c43.jpg)

![package-code](https://user-images.githubusercontent.com/11880996/31766030-0b96af3a-b4f9-11e7-8857-f170d4c8abc0.gif)

**Comment by samelhusseini** [comment]
We use the github API to search for packages. The package name is pxt-olney. You can also try searching CoderDojo and that works.
