### ISSUE TITLE
Serial editor UI enhancements

### ISSUE THREAD

**Issue by cait1inhennessy** [Microsoft/pxt#3287]
![serial_editor](https://user-images.githubusercontent.com/16658549/31960156-b16d201e-b8ab-11e7-8207-75046619bd21.gif)

- [x] Thinner border on chart lines
- [x] Different label text color - something more visible than white
- [x] Add background to console similar to graph canvas - rounded corners, gray background color
- [x] Make preview button look more like a button - shrink background, etc.
- [x] Add animated gif to preview button
- [x] Change text on preview button to "Show data"
- [x] Move editor "go back" button to far left; remove border so it's just an icon
- [ ] Scroll bar in console should be more visible
- [x] Use div instead of span for serial.writeLine
- [ ] Tops of graph lines are cut off

**Comment by mmoskal** [comment]
Maybe use `<div>` not `<span>` for serial console lines - the function on the device is called `writeLine`, would be good if it actually wrote a line.

**Comment by caitlin-hennessy** [comment]
@mmoskal Definitely.  I've added that to the enhancements list and will be pushing the change soon.
