### ISSUE TITLE
javascript autocomplete gives random(4.)

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3292]
In Javascript mode, when using autocompletion/intellisense, Math.random uses default (4.) where the period is weird. Dragging in the code from the menu gives (4) as default.

(Happens no matter which language the editor is set to.)

**Comment by microsoftsam** [comment]
Issue is only on v0. 
There's an extra full stop after the eg on this line: https://github.com/Microsoft/pxt/blob/v0/libs/pxt-common/pxt-core.d.ts#L297

Fix is to remove the dot.

**Comment by microsoftsam** [comment]
Fixed in beta
