### ISSUE TITLE
can't de-compile unused functions

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#3308]
The following code decompiles correctly to blocks:

```
function foo() {
    light.showRing(
    "blue red red red red red red red red red"
    )
}
foo()
```

However, if you remove foo() call (do it in JS), then it stops decompiling.

Tested on https://makecode.adafruit.com/ (master)

**Comment by abchatra** [comment]
Duplicate of https://github.com/Microsoft/pxt/issues/2632
