### ISSUE TITLE
handle unsupported browsers

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#331]
when a user is trying to open PXT on an older browser, the web site looks completely broken. We need to document the list of supported browser and redirect the users as needed.

- [x] build list of supported browser
- [x] document alternative to each old browser
- [x] detect browser in client and redirect to "/browsers" page

**Comment by thomasdenney** [comment]
- [ ] Determine which browsers on the Raspberry Pi actually work. The default is Epiphany, although Firefox can be installed
- [ ] Verify installation instructions for Firefox on Raspberry Pi (IceWeasel has been replaced by Firefox)

**Comment by thomasdenney** [comment]
Currently being worked on in https://github.com/Microsoft/pxt/tree/browser-redirect and https://github.com/Microsoft/pxt-microbit/tree/browser-redirect
