### ISSUE TITLE
Linking Target to local PXT instance

### ISSUE THREAD

**Issue by alexp3d** [Microsoft/pxt#3311]
I have pulled pxt-microbit and pxt and have sucessfully linked the two two together and built with typings install and jake. When I run the server, typescript complains as follows: 

`[serve] cd ../pxt-microbit; node ../pxt/built/pxt.js serve
Using target PXT/microbit with build engine yotta
  Target dir:   /home/ec2-user/microbit/polar3d-microbit/pxt-microbit
  PXT Core dir: /home/ec2-user/microbit/polar3d-microbit/pxt
building node_modules/pxt-core...
[run] cd node_modules/pxt-core; jake
local pxt-core built.
log strings: 63 files; 0 strings -> sim-strings.json
sim/state/misc.ts(70,28): error TS2339: Property 'getLastEventTime' does not exist on type 'EventBus'.
sim/state/misc.ts(74,28): error TS2339: Property 'getLastEventValue' does not exist on type 'EventBus'.
sim/state/misc.ts(90,24): error TS2339: Property 'runningTimeUs' does not exist on type 'Runtime'.
building sim...
[run] cd sim; node ../node_modules/typescript/bin/tsc
^C
[ec2-user@ip-172-31-46-197 pxt]$ ^C
[ec2-user@ip-172-31-46-197 pxt]$ ^C
[ec2-user@ip-172-31-46-197 pxt]$ jake serve
[serve] cd ../pxt-microbit; node ../pxt/built/pxt.js serve
Using target PXT/microbit with build engine yotta
  Target dir:   /home/ec2-user/microbit/polar3d-microbit/pxt-microbit
  PXT Core dir: /home/ec2-user/microbit/polar3d-microbit/pxt
building node_modules/pxt-core...
[run] cd node_modules/pxt-core; jake
local pxt-core built.
log strings: 63 files; 0 strings -> sim-strings.json
sim/state/misc.ts(70,28): error TS2339: Property 'getLastEventTime' does not exist on type 'EventBus'.
sim/state/misc.ts(74,28): error TS2339: Property 'getLastEventValue' does not exist on type 'EventBus'.
sim/state/misc.ts(90,24): error TS2339: Property 'runningTimeUs' does not exist on type 'Runtime'.
building sim...
[run] cd sim; node ../node_modules/typescript/bin/tsc
state/misc.ts(70,28): error TS2339: Property 'getLastEventTime' does not exist on type 'EventBus'.
state/misc.ts(74,28): error TS2339: Property 'getLastEventValue' does not exist on type 'EventBus'.
state/misc.ts(90,24): error TS2339: Property 'runningTimeUs' does not exist on type 'Runtime'.

***
*** Build failed: target build failed: Exit code: 2 from cd sim; node ../node_modules/typescript/bin/tsc
Error: Exit code: 2 from cd sim; node ../node_modules/typescript/bin/tsc
    at ChildProcess.<anonymous> (/home/ec2-user/microbit/polar3d-microbit/pxt/built/nodeutil.js:85:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
***
`
Is this a bug, or did I make a mistake linking my local pxt sources to pxt-microbit?

**Comment by pelikhan** [comment]
Make sure to be on the v0 branch of PXT for the Microbit.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
