### ISSUE TITLE
Add 'Paste' button to TypeScript context menu

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#3315]
To support Mac editing of text.

**Comment by microsoftsam** [comment]
:)

**Comment by microsoftsam** [comment]
No way to trigger paste from an event handler in Edge, Chrome and Firefox. 
Only in IE, which is why the monaco-editor limits it to that browser: 

see: https://github.com/Microsoft/monaco-editor/issues/391

**Comment by pelikhan** [comment]
In that case, could we insert the text in the file buffer and reload in Monaco?

**Comment by microsoftsam** [comment]
Well ultimately its not about being able to edit the buffer, obviously monaco can do that as well. 
It's about having access to the clipboard. I will look into it further.

**Comment by pelikhan** [comment]
I guess there won’t be any copy/paste errors that way!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
