### ISSUE TITLE
Hundres of hidbridge failed to load messages

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#3325]
Hundreds of hidbridge failed to load, Error: No device connected console messages. 
Why is it not getting debounced?

```
hidbridge failed to load, Error: No device connected
51pxtlib.js:1398 hidbridge failed to load, Error: No device connected
pxtlib.js:1398 hidbridge failed to load, Error: No device connected
18pxtlib.js:1398 hidbridge failed to load, Error: No device connected
pxtlib.js:1398 hidbridge failed to load, Error: No device connected
47pxtlib.js:1398 hidbridge failed to load, Error: No device connected
```

**Comment by microsoftsam** [comment]
makes it really hard to debug.

**Comment by microsoftsam** [comment]
Nevermind, seems like a local issue.

**Comment by microsoftsam** [comment]
Actually the setInterval starts out by polling ever 5 seconds, and then all of a sudden ends up in an infinite loop. Maybe it's calling itself?

**Comment by microsoftsam** [comment]
P0 any instance of an editor. The serial polling logic is calling itself.

**Comment by microsoftsam** [comment]
Introduced by this change: https://github.com/Microsoft/pxt/pull/3309/files

@mmoskal what was the reason for adding startHidConnectionPoller inside of initSerial?

**Comment by mmoskal** [comment]
The intention of my change was not to re-start the HID connection in the middle of the flashing.

However it seems I've messed it up. In the #3326 it is now fixed correctly - we run a HID ping operation in a loop and only when this fails we restart the serial poller.

CC @caitlin-hennessy
