### ISSUE TITLE
MakeCode Download shows blank page in iOS11 

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#3334]
From microbit-mark:

I've just tried this in Safari and Chrome on iOS11.0.3

If the micro:bit app is installed, Chrome opens in app and safari asks, but this is hidden by a blank page opening.
![Uploading IMG_0004.PNG…]()

If the app is not installed, chrome opens a blank page and safari "cannot open the page because the address is invalid"

![img_0003](https://user-images.githubusercontent.com/31242877/31899687-3b22248c-b814-11e7-9ed3-a4ad5b18d5b7.PNG)
![img_0002](https://user-images.githubusercontent.com/31242877/31899694-401da7fe-b814-11e7-9c11-c94aec3e7697.PNG)

See related https://github.com/microbit-foundation/microbit-support/issues/32

**Comment by microsoftsam** [comment]
For some reason when this was done 7 months ago we needed to call window.open in this scenario. This created a new tab, but Safari (IOS 9 and 10) still showed the dialog (of a different page mind you) on top of the newly created tab. 
It appears this has been fixed by IOS11 and now the dialog is showing up on the same page. 
I'm tempted to just remove the window.open but I want to understand why it's there?

**Comment by abchatra** [comment]
@microsoftsam Any other update here?

**Comment by martinwork** [comment]
I think the following explains the empty page. This refers to the way things were with Safari in iOS 8/9/10... 

Setting window.location or window.open(url,"_self") is best done in the context of a user click. Then you only have to answer this alert: Open in "micro:bit"?

If window.location is set in another context, the question is: Open this page in "micro:bit"? This is not too bad but it also remembers if you Cancel at all and switches to saying "Cannot Open Page" until the page is refreshed. 

This can be avoided by creating a temporary window with an empty location in the context of the user click, which has its location set later.

http://stackoverflow.com/questions/31891777/ios-9-safari-iframe-src-with-custom-url-scheme-not-working


Hopefully iOS 11 is better behaved and we can just dispense with the temporary window in iOS 11, but I haven't tested that.

**Comment by microbit-mark** [comment]
@abchatra @pelikhan Just to check, this is now fixed in beta?

**Comment by pelikhan** [comment]
Fixed in master.
