### ISSUE TITLE
Can't translate default list var name in some blocks

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#3336]
The default list var name in the following blocks cannot be translated.

![image](https://user-images.githubusercontent.com/485416/32005006-24f5dbd8-b9de-11e7-8de5-f3909bb70c2b.png)

**Comment by sgk** [comment]
The following commits made it possible to translate the default list var name in the three blocks in the picture below.

bc79c8156f1eeb383d18bc42edf8743cb5e97477
725af773fd66b8455575aecc2847dd59583df675
0ac194c69ce8e4e28dea56870c92bfc123b7904b

![image](https://user-images.githubusercontent.com/485416/32005175-995e96d6-b9de-11e7-96c4-ea9085e36edd.png)

**Comment by sgk** [comment]
Does anybody know what code portions set the default list var name `list`? It is a little bit hard to find the location for a PXT newbie like me.

**Comment by wsnook** [comment]
@sgk I am also not a PXT expert, but it's possible this might be the "list" you were looking for:

https://github.com/Microsoft/pxt/blob/master/pxtblocks/blocklyloader.ts#L45

![screen shot 2017-12-25 at 11 26 35 pm](https://user-images.githubusercontent.com/1828676/34347726-3a28c156-e9cb-11e7-856c-c916e7c03260.png)

**Comment by abchatra** [comment]
This is resolved.
