### ISSUE TITLE
JavaScript drag-and-drop using touch not working (micro:bit)

### ISSUE THREAD

**Issue by halspeed** [Microsoft/pxt#3348]
In JavaScript mode, drag-and-drop using touch does not work, but mouse/touchpad does. Confirmed on Windows and iOS, multiple browsers.

**Comment by microsoftsam** [comment]
Yes. The drag and drop in JS uses drag and drop events, and those are only supported on the following browsers: https://caniuse.com/#feat=dragndrop

We should consider using ontouchstart and ontouchend events like Blockly so that it works on browsers that don't support drag events.

**Comment by abchatra** [comment]
Moved to https://github.com/Microsoft/pxt-microbit/issues/916
