### ISSUE TITLE
inlined appTarget.json in all served HTML

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#335]
Currently, we inline the webconfig in the served HTML. Is it possible to include the pxttarget.json information in there as well?

**Comment by mmoskal** [comment]
built/target.json is 400k.

**Comment by mmoskal** [comment]
400k is quite a bit - it could blow my HTML caches and also there a good reason to get this file from geo-distributed CDN and not our cloud server in the US. We could turn it into .js file and download using `<script>` tag if that is any help?

BTW, most of this file is bundled packages, but the inlined logos also take some space - it would be good to just use URLs.

**Comment by thomasdenney** [comment]
For pxt-microbit `build/target.json` can have 3KB shaved off by removing redundant whitespace (not a major optimisation). It contains approximately:

* 134KB of base 64 images (these would be smaller if cached as regular files)
* 196KB of files for `microbit`
* 15KB of files for `microbit-radio`
* 16KB of files for `microbit-devices`
* 11KB of files for `microbit-bluetooth`

**Comment by pelikhan** [comment]
Let's go with turning it into a .js file and add it to the release manifest. Shaving kb won't have much effect compared to loading the typescript 3mb.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
