### ISSUE TITLE
Time stamps not exactly matching up

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#3371]
Not sure why we don't have the same time stamps across data streams.  This is 3 different data streams in the CSV file...

![timestamps](https://user-images.githubusercontent.com/22108954/32127215-1a30fbd6-bb2a-11e7-81e9-b733aae1207a.PNG)

**Comment by pelikhan** [comment]
Data entries are sent sequentially so time stamp don’t match. In fact, different data stream may have radically different time streams.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
By design
