### ISSUE TITLE
Screenshot option should be disabled on UWP edge (v0)

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#3372]
Needs cherry picking: https://github.com/Microsoft/pxt/commit/3f8638f1e2e144f7115a6a98a84d1ef64791c4b2

**Comment by abchatra** [comment]
Download screenshot broken in UWP

**Comment by microsoftsam** [comment]
Yep, so we need to disable that option just like we did in master. This is a v0 only bug.

Or maybe fix the root cause?

**Comment by microsoftsam** [comment]
Fixed.
