### ISSUE TITLE
"No device connected" error, is that necessary?

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#3377]
Do we need to throw an error in BridgeIO.initAsync when we can't connect to a device. 
Can we do something else? It makes debugging a pain. 

"No device connected" error

@mmoskal @caitlin-hennessy

**Comment by microsoftsam** [comment]
I realise I can do a "never pause here" in the Chrome dev tools, so I can work around it, but still?

**Comment by mmoskal** [comment]
I think we can just return `Promise.reject()`?

**Comment by caitlin-hennessy** [comment]
@mmoskal's suggestion seems fine to me.

**Comment by abchatra** [comment]
question answered.
