### ISSUE TITLE
assertion fails (delayLoadXml)

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#3378]
The delayLoadXml assertion in loadEditorFile in blocks.tsx fails everytime you load a project that has instructions (ie: not a tutorial or an example). 

@pelikhan any thoughts?

Repro: makecode.adafruit.com/beta
Load the Magic wand project

**Comment by microsoftsam** [comment]
Looks like loadFileAsync in that case is getting called twice..

**Comment by microsoftsam** [comment]
Probably because the sidedocs is causing the render function to get called a bunch of times, we really need to optimize that side doc. I'll look into it.

**Comment by pelikhan** [comment]
Good use of an assert :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
