### ISSUE TITLE
Microbit Cloud Instance

### ISSUE THREAD

**Issue by alexp3d** [Microsoft/pxt#3381]
I have set up a pxt (targeting microbit) server in AWS. Everything works just fine when hitting the server's public IP. 

But, I assume Makecode is behind a load balancer of some sort (which is something that I would like to have my instance running behind). The load balancer properly serves the microbit editor in my case but will fail post/get attempts (like if you hit the download button) as it is trying to access resources that are not on the load balancer but are on a separate host server.  Are there resources for configuring PXT to handle this scenario? Configurations I have overlooked in pxt and pxt-microbit source code? Again, I assume the current Makecode platform has some kind of load balancer in place.

**Comment by sgk** [comment]
If you want to setup your own web server which serves the micro:bit IDE, just run `pxt staticpkg` and copy the generated files onto any web server. I use AWS S3 and it works fine.

**Comment by pelikhan** [comment]
The web server launched by ``pxt serve`` is not meant to be run for a multiple set of users in the cloud. It is just for local dev purposes.

It requires a local token to access any file storage features. As @sgk mentionned, ``pxt staticpkg`` will generate a set of static HTML to host the editor anywhere you want.

**Comment by alexp3d** [comment]
Thanks for the help. I have set up a static package and can access the site normally. But, some users report compile/download failure. It looks like for some reason (sometimes, on certain systems) microbit is trying to do a host/api/path-to-stuff and sometimes it looks like it may be getting the api from pxt.io/api/...

Is there a way to pull this api information that the server appears to be looking for into the host server? I noticed a command pxt api but am not sure what it is for/how it is used.

**Comment by pelikhan** [comment]
The microbit target is architected to talk to our backend. What are you building?

**Comment by alexp3d** [comment]
I created the static packages for the pxt-microbit target front end. I would like to configure a local instance of pxt to run using those static packages on my own server host.

**Comment by pelikhan** [comment]
This is not a supported scenario.

**Comment by pelikhan** [comment]
@alexp3d are you trying to test your packages?

**Comment by alexp3d** [comment]
@pelikhan I wanted to customize the editor front end and serve it on my own server but still have it communicate as necessary with the makecode backend.

It looks like it makes some API calls including one to /api/compile/extension which I am unable to reach on makecode.com

**Comment by WinEcos** [comment]
@alexp3d  did you have solved your issue ? 
would you like share how to created the static packages on web server ? 

Thanks a lot

**Comment by alexp3d** [comment]
I followed the instructions at: https://makecode.com/cli/staticpkg to create the static package using the command `pxt staticpkg' from within the pxt-microbit folder. 

I then used:
`npm install -g http-server
http-server -c-1 built/packaged`

to run a simple server to serve the web page (as per the documentation). 

But I get client side errors when trying to download the hex when running the server on an instance in EC2 (linux). It appears to be trying to do various post and gets to paths under the /api directory. When I run this exact code and setup locally (serving from my local machine and hitting a local host instead of an EC2 instance)  everything works fine (and it does not appear to be trying to do any posts or gets). 

Can anyone help troubleshoot? I would have thought that the static package would allow any web server to serve the static asset files and then everything should run.

**Comment by alexp3d** [comment]
Does anyone have an answer for the above?

**Comment by WinEcos** [comment]
@alexp3d hi guys , sorry to reply late . and are you used the v0 branch of pxt version ? or others ? 
might be added in discord app to discuss many things . https://discord.gg/wu3uJyA  

Thanks a lot

**Comment by WinEcos** [comment]
@alexp3d  hi alex , have you ever met this problems when yotta build pxt-microbit project ? 
https://github.com/Microsoft/pxt/issues/3726 

Thanks a lot

**Comment by lucas1677** [comment]
@pelikhan I want to test my package locally, what is a better way?
now i'm using pxt serve --cloud to start a local serve, then go to the browser open the microbit WEBIDE, click advanced -> add package, then paste the package github url, add click add, this works fine, but sometimes i got the cache package, that's very bad experience for package dev. 
thanks.
