### ISSUE TITLE
Minecraft Makecode will not work for player who does not create world

### ISSUE THREAD

**Issue by philgolden** [Microsoft/pxt#3383]
Following awesome technical support, we have resolve the internet filtering issues that prevented us using Minecraft Makecode in school. Now it works well for a single player in a world (the one who creates the world). However if anyone else joins the world, Minecraft Makecode will connect for them, but no code will actually run. If the second player instead creates a new world, then Makecode works as expected. I am trying to understand if this is a firewall issue, and if so what I need to ask to have opened.

**Comment by pelikhan** [comment]
most commands like ``fill`` requires ``ops`` right which is automatically given to the local player - the agent requires ``world builder``. Try giving more rights to the joined players.

**Comment by philgolden** [comment]
Will try this tomorrow. Thanks as always Peli.

Phil

**Comment by philgolden** [comment]
Hi Peli,

This worked, thanks very much!

Phil
