### ISSUE TITLE
Micro:bit crashes if serial data received and no receive handler

### ISSUE THREAD

**Issue by halamrose** [Microsoft/pxt#3390]
1st test case: when an attached device sends serial data to micro:bit is this code crashes micro:bit hanging display with only some LEDs 
![image](https://user-images.githubusercontent.com/7300405/32224325-e58f3372-be38-11e7-89be-9fd33ff1a5cf.png)

2nd test case, add receive handler works fine, does not crash.
![image](https://user-images.githubusercontent.com/7300405/32224397-2095b36a-be39-11e7-9d98-5de7d5e836b9.png)

Tested this with @DavidWhaleMEF who confirms the above.

**Comment by abchatra** [comment]
Moved to https://github.com/Microsoft/pxt-microbit/issues/917
