### ISSUE TITLE
Proposals for a better release process

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#3395]
Our current release process has a few issues: 
- We release often just to get something on the beta site, but don't actually want that release to be an actual release candidate (so we end up polluting npm with many releases that aren't really valid candidates that others should take a dependency on)
- We use the same process for local development (jakefile) and released versions. Released versions should be minified. Given the way we do beta and release versions, we're not able to pick and choose when a minification / uglification process should happen on our files
- We are shipping with a development version of React. (For optimum performance we should follow the guides on https://reactjs.org/docs/optimizing-performance.html and uglify and strip out any code run only in development)
- No source maps :(

Proposals: 
- pxt bump adds a -beta to the npm version it creates, unless a --release flag is sent. This way we choose when we want a version to be a Release candidate, and only these versions do we release with.
- if a build is not a beta build (ie the --release flag was passed in), we run a bunch of other release tasks on travis, to minify / uglify assets
- Fix source maps so that we can still debug live sites.

@mmoskal @pelikhan thoughts?

**Comment by pelikhan** [comment]
Sounds useful, let's use tags https://docs.npmjs.com/getting-started/using-tags

**Comment by pelikhan** [comment]
Please don't uglify any of our sources. Minify is ok.
