### ISSUE TITLE
projects window jumps when scrollbar appears and disappears

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3398]
If the browser size and size of the projects popup are just right, the scrollbar appears and disappears all the time, making everything jump up and down.

To reproduce: Don't have many projects saved in your editor. (for example start a private window, then you have none). Open the projects window. Resize the screen to the size when the scrollbar on the right starts to appear. Then it will start freaking out.

Seems to be independent on browser (reproduced on firefox and IE).

![microbit-projects-bug](https://user-images.githubusercontent.com/5718354/32269143-ce27e2c4-bef1-11e7-85b2-42d8a1b94093.gif)

**Comment by microsoftsam** [comment]
Fixed in v0. To be integrated into /beta soon.
