### ISSUE TITLE
Editor appends variable and errors 'packet has no property Serial2'

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#3399]
microbit-support:3179

Re-creating or opening the final code from [Rock Paper Scissors Tutorial](https://makecode.microbit.org/projects/rps-teams) causes a 'packet has no property 'Serial2' error, which it shouldn't as the variable is set as 'Serial'.
 
Looking at the JS code, Serial has been appended with 2, but if I go back to blocks, I can't select it this variable.

When I remove the 2 from the code, it appears in the drop down as Serial2 in blocks and the code runs.

![image](https://user-images.githubusercontent.com/31242877/32270343-7d32c2ac-beed-11e7-969e-e3645a4649d5.png)

This happens in different browsers and when I run the tutorial code and after I clear the cache. I also checked with @carlosperate that the experience is the same for him.

I have a report of a further error of 'Operator == cannot be applied to types 'number' and 'string'', in the same .hex but I can't reproduce without resolving the first error. 

![image](https://user-images.githubusercontent.com/31242877/32270399-b378ccd0-beed-11e7-8d12-e3a73e15c27e.png)

Any ideas what's happening here?

**Comment by abchatra** [comment]
@microbit-mark can you share the program?

**Comment by abchatra** [comment]
Never mind it is the last example of rock paper scissors.

**Comment by abchatra** [comment]
@riknoll decompiler issue?

**Comment by riknoll** [comment]
Nope, this is a Blockly compiler issue. What's happening is that the radio parameter is named `serial`, which conflicts with the `serial` namespace. The Blockly compiler tries to helpfully rename that and ends up breaking the destructuring in the JavaScript code because there isn't a property by that name. I'll take a look.

**Comment by abchatra** [comment]
Rename the variable to something else as a quick fix?

**Comment by microbit-mark** [comment]
I have suggested that and will see if the latter error 'Operator == cannot be applied to types 'number' and 'string'' persists

**Comment by microbit-mark** [comment]
I checked back with the Customer and renaming the variable resolves the issue. Could/Should this be updated in the tutorial?

**Comment by abchatra** [comment]
This is fixed in alpha
