### ISSUE TITLE
Increase in instability in Safari

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#340]
Since the introduction of the Monaco editor I've noticed an increase in the frequency with which I see 'A problem occurred with this web page so it was reloaded' in Safari on OS X, however I've also seen it occur on documentation pages. When this error occur the pages is reloaded and the user sees this a dialog like the following:

![screen shot 2016-09-15 at 10 01 26](https://cloud.githubusercontent.com/assets/20356546/18544183/62b3f2cc-7b2b-11e6-8718-16ef6c0104ef.png)

In this most recent crash the cause was `WTFCrashWithSecurityImplication`, which I suspect is a bug in Safari itself, but we should continue to monitor the causes of crashes.

**Comment by abchatra** [comment]
@microsoftsam Is this still reproducible. If not please close.

**Comment by abchatra** [comment]
I am closing this for now. If you see this again please reopen
