### ISSUE TITLE
Forever loop not getting executed

### ISSUE THREAD

**Issue by simonc8** [Microsoft/pxt#3400]
I've been reading threads about order of fibres, which I haven't completely understood, but this issue may be related.
In the code below the Forever loop never seems to run and the variable light doesn't get incremented, as the display on the microbit continues to show 1. Is this a problem of timing between the Forever loop and On Start?

Grateful for advice.

![forever problem](https://user-images.githubusercontent.com/33280951/32274292-1572a8ec-befe-11e7-8fb2-33f5937ab8c6.png)

**Comment by abchatra** [comment]
Forever loop gets initialized after the OnStart. You have an infinite loop in onStart. So forever doesn't get a chance to get initialized at all.
