### ISSUE TITLE
micro:bit game brightness broken recently

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#3402]
In this program, the two sprites now look the same on the real micro:bit. In the simulator, they appear to have the same brightness but the left one is flickering. I tried on live and beta.
```
let item = game.createSprite(1, 2)
let item2 = game.createSprite(3, 2)
item.set(LedSpriteProperty.Brightness, 1)
```

**Comment by abchatra** [comment]
This is fixed.
