### ISSUE TITLE
Variables are not compiled into shadow blocks

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#3407]
variables_get shadow blocks are not actually shadow and there's an explicit check in createShadowValue to make it a block instead of a shadow. 

You end up with this behaviour:

![variables_shadow](https://user-images.githubusercontent.com/16690124/32312562-b7221378-bf5b-11e7-85e7-0a6aebe480ca.gif)

and thus a syntax error..

Repro steps: 
- Open the Array toolbox and drag a "get array" block onto the workspace
- Click on the variable block that comes with it and drag it out

Issue: you end up with an empty hole. and that causes syntax errors.

Fix: we should make the variable block a shadow block, that way it cannot be dragged out. (As a general rule, everything should have shadow blocks)

**Comment by microsoftsam** [comment]
So I ran into this as I was debugging something else but it turns out Blockly throws an assertion for: 
AssertionError: Assertion failed: Shadow blocks cannot have variable fields.

**Comment by microsoftsam** [comment]
Will investigate why Blockly ensures that doesn't happen.
