### ISSUE TITLE
When changing to another example, the added package disappear.

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#3414]
**Repro steps:**
•	Navigate to https://makecode.microbit.org/beta
•	Click Advanced->Add package, add any package, the package appear in Editor
•	Click Projects in menu bar->Projects, choose any projects
**Expect Result:** The added package is still in Editor
**Actual Result:** The added package is disappear
![package](https://user-images.githubusercontent.com/23447632/32361817-d4fbf5fa-c09e-11e7-9d8f-f28c71438958.gif)

**Comment by abchatra** [comment]
This is per design. Package is associated with project and only the relevant packages will appear.
