### ISSUE TITLE
Browser version support

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#342]
In https://github.com/Microsoft/pxt/pull/336 I added basic detection and redirection for browsers that are unsupported, but I made the assumption that users will be on one of the most recent versions of each browser. In schools this is not necessarily the case.

I firstly examined each PXT dependency to determine what the minimum version of each browser is supported. Officially jQuery and Semantic UI only support the two most recent versions of each browser, but are generally compatible with earlier versions. [Monaco explicitly states that it is not compatible with mobile browsers](https://microsoft.github.io/monaco-editor/), and I found that scrolling the editor was incredibly difficult in Safari on iPad. Of the other dependencies the minimum versions supported are:

| Browser | Version | Date |
| ------- | ------- | ---- |
| Firefox | 29 | April 2014 |
| Chrome | 30 | October 2013 |
| Safari | 6 | July 2012 |
| Internet Explorer | 10 | September 2012 | 
| Opera | 21 | May 2014 |
| Edge | 12 | March 2015 |

Mozilla releases 'extended support releases', which are maintained for a year after release and are targeted for use 'in organisations including schools'. The earliest ESR after Firefox 29 is **Firefox 31** (July 2014). Google Chrome auto-updating can also be disabled by administrators, although Google *strongly* discourages it. In my experience of UK schools, Firefox ESRs and IE11 are by far more the most common browsers.

I then used a combination of [browserstack.com](https://browserstack.com) and local installations to test the closest version that I could find:

| Browser | Version | Tested on | Support |
| ------- | ------- | --------- | ------- |
| Firefox | 31 | Windows 10 | Functional although performance much worse than latest stable version (48) |
| Chrome | 38 | Browserstack | Functional |
| Safari | 6,7,8 | Browserstack | Layout fails in all three versions (Semantic UI issues). I suspect this is related to CSS Flexbox, as this required `-webkit-` prefixes prior to Safari 9 |
| Safari | 9 | OS X 10.11 El Capitan | Functional |
| Internet Explorer | 11 | Windows 10 | Functional. I chose not to test on IE 10 as it doesn't seem worth supporting |
| Opera | 21 | Windows 10 | Functional, with minor layout bugs and poor performance. By this point Opera was based on Chrome, which leads me to believe that Chrome 34+ (the version of Chrome that Opera 21 is based on) should work |
| Edge | 38 | Windows 10 | Functional |

Broken documentation layout in Opera 21:

![opera 21 dodgy](https://cloud.githubusercontent.com/assets/20356546/18587917/30788de4-7c1c-11e6-90f8-2e65f825e58a.PNG)

Issues with layout prior to Safari 9:

![macyos_safari_8 0](https://cloud.githubusercontent.com/assets/20356546/18587950/49220b04-7c1c-11e6-81fd-6a3ddf54285a.png)

These browsers impose these minimum OS requirements:

| Browser | Windows version | OS X version |
| -------- | ----------------- | ------------- |
| Chrome | 7 (2009) | 10.9 (2013) |
| Firefox | XP (2001) | 10.9 (2013) |
| Safari | N/A | 10.9 (2013) |
| Edge | 10 (2015) | N/A |
| IE | 7 (2009) | N/A |
| Opera | 7 (2009) | 10.9 (2013) | 

Should we explicitly require these browser versions (Chrome 34, Firefox 31, Safari 9, Edge, IE11, Opera 21), or just leave the requirements as is (any Chrome, Firefox, Safari, Edge, IE 11, Opera if based on Chrome) on the basis most users will be using a browser released in the last two years? From a security perspective I view it as unlikely that the browser version being used in schools would be any older than a year.

**Comment by pelikhan** [comment]
We should explicitely enforce those requirements otherwise we might the web site might look broken. This is a great in-depth analysic which we should add to our "browsers.md" page: for each browser, point to the latest recommended version and why we support it.
