### ISSUE TITLE
In “Blocks”, help document logo failed to change to unselected status when clicking blank area.

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#3443]
Repro steps:
Navigate to https://makecode.microbit.org/beta
Click “?”->Blocks to show the help document in right. “>” is selected
Click blank area.

Expected Result:
“>” on the help document is unselected after clicking blank area

Actual Result:
“>” is always selected after clicking blank area
![selected](https://user-images.githubusercontent.com/23447632/32591215-2fcfa814-c559-11e7-8aaa-fb6e485815e1.gif)

**Comment by microsoftsam** [comment]
Issue here is that the Blockly canvas is not focusable. This will be resolved when we eventually get to making Blockly fully accessible. Closing for now. You can click anywhere but the Blockly canvas, to lose focus from the Sidebar link.
