### ISSUE TITLE
Add licensing terms at the top of the CS Intro page

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#3446]
https://makecode.microbit.org/courses/csintro

"The following content is freely available under the MIT Open Source license (https://opensource.org/licenses/MIT)"

**Comment by abchatra** [comment]
MIT license is for the entire PXT repo and which this documentation is part of https://github.com/Microsoft/pxt-microbit/blob/master/docs/courses/csintro.md

Why do we need to add another MIT license at the top of the documentation? I do not understand this issue.

**Comment by pelikhan** [comment]
It is not clear from the rendered docs which license they are published under.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
We don't display MIT license on other documentation pages.

**Comment by pelikhan** [comment]
Exactly, we should be clearer about licensing scheme of all our docs – at least when they are open sourced.

**Comment by Jaqster** [comment]
The issue is specifically with the Curriculum - there are a lot of Training organizations and Teacher PD groups who would like to teach this curriculum, but they are not sure if they can due to the licensing.

**Comment by ganicke** [comment]
We're holding on this.....?

**Comment by ganicke** [comment]
We could throw the [MIT Open Source](https://opensource.org/licenses/MIT) link into the footer of the main body container then it's passively visible on each page.

Also, are the offline formats under the same license offering?

**Comment by pelikhan** [comment]
This is something that the server could inject. We should not add a copyright footer in all markdown pages. Let's have a chat to spec the feature.

**Comment by ganicke** [comment]
Triple tick license tagging in the markdown with replacement tokens: `@MIT@` resolves to [MIT Open Source](https://opensource.org/licenses/MIT)

For an individual page -

```
```license
@MIT@
```-
```
For all pages, this node and below -

```
```license-all
@MIT@
```-
```

**Comment by pelikhan** [comment]
It should be added automatically by the server based on the github repo license.

**Comment by pelikhan** [comment]
We can have a placeholder in the doc rendering templates for the license. It should not be part of the markdown.
