### ISSUE TITLE
Lack complete navigation link in examples page 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3451]
**Repro steps:**
• Navigate to https://makecode.microbit.org/examples
• Click links on page one by one

**Expected Result:**
 There should have complete vavigation link for every example
![capture2](https://user-images.githubusercontent.com/23466737/32647840-3d3551d6-c62e-11e7-8d2c-c07959951f7e.PNG)
**Additional info:**
Issue Links: 
https://makecode.microbit.org/examples/egg-and-spoon
https://makecode.microbit.org/examples/stop-watch
https://makecode.microbit.org/examples/radio-dashboard
**Actual Result:**
 When click examples "Egg & Spoon race", "Stop Watch", "Radio Dashboard", there are no complete navigation links on the top.
![capture1](https://user-images.githubusercontent.com/23466737/32647765-e65d019c-c62d-11e7-86e3-97d6cd81cf74.PNG)

**Comment by abchatra** [comment]
@ganicke is this something you can tackle? Or does this require any code change?

**Comment by ganicke** [comment]
The nav path is driven by the summary. This is example page is not included in SUMMARY.md. Including it the summary will add 'population' to the left-nav. I'll update the summary and you can approve if you like.

**Comment by ganicke** [comment]
Fixed in https://github.com/Microsoft/pxt-microbit/pull/567

**Comment by abchatra** [comment]
Thanks @ganicke
