### ISSUE TITLE
When using "Tab" key to access simulator, Button "A"&"B" have been selected on IE

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3454]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Use "Tab" key to access element on the page

**Expected Result:**(**on Edge, Chrome, Firefox)**
 When click “Tab” key on simulator, Button "A"&"B" shouldn't be selected together
![6](https://user-images.githubusercontent.com/23466737/32649136-e62e678c-c633-11e7-98eb-fde0952619a1.gif)

**Actual Result:****(on IE)**
When using “Tab” key to access simulator, Button "A"&"B" have been selected 
![5](https://user-images.githubusercontent.com/23466737/32649140-ef208be0-c633-11e7-8bd9-41687d9dd2b1.gif)

**Comment by microsoftsam** [comment]
I can repro this bug. 
Focusing on any part of the simulator iframe on IE focuses all focusable elements. ie: if you add an A+B button it will also highlight that when the frame is focused. 

Interesting thing though, if you add a light level component, it doesn't.. 

<img width="393" alt="screen shot 2017-11-13 at 9 33 05 am" src="https://user-images.githubusercontent.com/16690124/32739835-e339794e-c855-11e7-844b-29d84e2184d8.png">

**Comment by Helen09** [comment]
New issue:
When using tab key to go to "Help", there is a trap on **IE**
![13](https://user-images.githubusercontent.com/23466737/37324724-ac62c458-2682-11e8-9f4e-9d075eec10f7.gif)
Can't access all elements on **Edge**
![14](https://user-images.githubusercontent.com/23466737/37324734-b4d0f038-2682-11e8-816d-ff8828b4cfc2.gif)

**Comment by samelhusseini** [comment]
Won't fix.
