### ISSUE TITLE
On the home screen selecting a language goes to the editor

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#3459]
If you use the secret tab menu to select a language, the page goes to the editor when it refreshes.

**Comment by abchatra** [comment]
@guillaumejenkins I believe we fixed this. Does this need to be ported to v0?

**Comment by microsoftsam** [comment]
I think @riknoll is referring to the accessibility menu in master. There is no home screen in v0, so nothing to port.

**Comment by abchatra** [comment]
This is with the new language change options at the bottom of home page. Issue makes sense.
