### ISSUE TITLE
Slow loading Editor for traditional Chinese language translation

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#3462]
micro:bit-support: 3355

From customer:

Recently, when loading makecode.microbit.com, the browser takes unexpectedly long to finish (more than 2 minutes). When I look into the "Network" monitor tools in Chrome debug console. I found that a XHR request pointing to:
https://www.pxt.io/api/translations?lang=zh-TW&filename=microbit%2Ftarget-strings.json&approved=true&branch=v0.13.34
takes more than 2 minutes, and responded the JSON data {"message":"no such file"}. 

I am not familiar with the architecture of MakeCode micro:bit, but I guess the problem was caused by this missing language file. Moreover, I found no problems in some of the browsers and computers (i.e. even the language version did not exist, the page responded no such file in less than 200ms. 

 I suspect that the problem was caused by calling the crowdin API with wrong file parameter branch, through the asynchronous translation process pxtlib.js.

I have tried clearing cache and history, and uninstalling Chrome, and using different Internet connections. But still, the long waiting XHR request problem remained. 

Screenshots
https://i.imgur.com/kVRLG0l.png
https://i.imgur.com/hOK1AnY.png

**Comment by pelikhan** [comment]
This is fixed in master.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
Port to v0?

**Comment by pelikhan** [comment]
Someone has to integrate it.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/3466

**Comment by microbit-mark** [comment]
Thanks for prompt follow up : )

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/3479

**Comment by abchatra** [comment]
Fixed
