### ISSUE TITLE
Translation problem in Traditional Chinese version

### ISSUE THREAD

**Issue by oscarlai2383** [Microsoft/pxt#3469]
Date: 13 Nov 2017

A translation problem was found in translating Traditional Chinese **Games (遊戲)** section. A screenshot is attached, where the English version is put side-by-side. 

![image](https://user-images.githubusercontent.com/33643235/32757298-d773183a-c919-11e7-9eb1-33868cbc5d0d.png)

Screenshot: [https://i.imgur.com/2J0HM4V.png](url)

Oscar Lai

**Comment by abchatra** [comment]
@microsoftsam  this should be fixed by new blockly right?

**Comment by microsoftsam** [comment]
Nope this isnt a Blockly issue but an issue with the translation authoring.

**Comment by samelhusseini** [comment]
This was an crowdin language translation bug and has been fixed for Chinese traditional: 

<img width="554" alt="screen shot 2018-01-03 at 10 05 11 am" src="https://user-images.githubusercontent.com/16690124/34533119-aa1e5194-f06d-11e7-92f6-d172a7d7bd8d.png">
