### ISSUE TITLE
Error using radio receivedNumber/String if variable is already declared

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#3472]
microbit-support:3169

If you start your program with an onRadioReceived receivedNumber, and then use the drop down menu to change receivedNumber to receivedString, the variable type is not changed in the JS code, but it appears that it has and results in an operator error. 

![radiobug](https://user-images.githubusercontent.com/31242877/32770259-e322787c-c916-11e7-996e-c5c495988111.gif)

https://makecode.microbit.org/51330-19337-18540-12529

This can only happen if you have already declared receivedString as a variable, but in the classroom it is common practice to start with and extend a previous program/project, so it's becomes a common occurrence.

**Comment by pelikhan** [comment]
We need to remove the option to rename those mutator variables.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microbit-mark** [comment]
Moved to https://github.com/Microsoft/pxt-microbit/issues/627
