### ISSUE TITLE
Invalid mime type for block sounds

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#3473]
In Firefox 57

![image](https://user-images.githubusercontent.com/4175913/32792985-944726b4-c919-11e7-90e1-99f01efb34d6.png)

**Comment by abchatra** [comment]
What is the impact?

**Comment by pelikhan** [comment]
No block sounds in firefox

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
