### ISSUE TITLE
Negative scroll image value does not function on micro:bit

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#3485]
When using a scroll image block with a negative value, the micro:bit does not display the image.  

The same program with a positive number works. 

![screen shot 2017-11-15 at 11 22 58](https://user-images.githubusercontent.com/31242877/32833639-66173f8e-c9f7-11e7-8b71-0c89ec8c842d.png)

Program: https://makecode.microbit.org/_0YRb4xXVjVao
Help: https://makecode.microbit.org/reference/images/scroll-image

**Comment by abchatra** [comment]
AFAIK Negative scroll was never supported. This is an enhancement.

**Comment by microbit-mark** [comment]
This relates to https://github.com/Microsoft/pxt-microbit/issues/626
