### ISSUE TITLE
Remove Adafruit & Sparkfun from micro:bit reseller list

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#3490]
In https://makecode.com/#hardware section, remove Adafruit & Sparkfun.  We should just point to the central https://www.microbit.org/resellers/ list.

Other resellers are asking to be listed here, and it's hard for me to say No when we have Adafruit & Sparkfun here...  want to avoid having a long laundry list of resellers on our page.

**Comment by pelikhan** [comment]
Done.
