### ISSUE TITLE
Grid picker positioning in RTL is offset

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#3492]
Repro steps: 
- Visit makecode.microbit.org?lang=ar
- Drag a show Icon block and try to open the icon picker. 

The icon picker is opened no where near the block.

<img width="862" alt="screen shot 2017-11-15 at 10 46 51 pm" src="https://user-images.githubusercontent.com/16690124/32878465-e847ac10-ca5a-11e7-8bc8-10ceb33bcf30.png">

**Comment by microsoftsam** [comment]
Affects both v0 and master.

**Comment by microsoftsam** [comment]
Another issue here is that the hover tooltip shows up over the user's mouse, so you're not able to click on any of the icons (making it unusable in RTL langs)
