### ISSUE TITLE
Project name can't be translated

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3493]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Projects"->"Projects" to open project "rock paper scissors" 
• Click "Setting"->"Language" and choose Korean

**Expected Result:**
 Project name language should switch from Korean to English
**Actual Result:**
 Project name can't switch from Korean to English and it still shows "rock paper scissors"
![1](https://user-images.githubusercontent.com/23466737/32881267-ae117828-caeb-11e7-8cb3-15e2ec096915.gif)

**Comment by abchatra** [comment]
This is by design. We don't rename existing projects
