### ISSUE TITLE
Element "Publish project" is been selected 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3494]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Share"

**Expected Result:**
"Publish project" shouldn't be selected
**Actual Result:**
 "Publish project" has been selected
![2](https://user-images.githubusercontent.com/23466737/32885928-02acca6e-cafa-11e7-9eb0-91c323d123da.gif)

**Comment by microsoftsam** [comment]
Why shouldn't it be selected? For accessibility reasons we select the first interactable element. Would you expect the close button to be selected instead?

**Comment by Helen09** [comment]
Ok, so the first interactable element is selected by default. I will close this bug. Thanks
