### ISSUE TITLE
Write Servo and melody cannot be used concurrently

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#3497]
micro:bit-support: 2965

This program demonstrates playing a melody and once complete the servo moves 90. waits, then returns back to 180 and wait before looping round.

When inserting the two blocks together there is an interference on the micro:bit device.
Having the melody block on its own is fine.  Have the two servo blocks on its own works fine.

![software screen shot](https://user-images.githubusercontent.com/31242877/32948705-1a900d64-cb98-11e7-887a-9be54e7fb50b.png)

I have confirmed with @finneyj, that PWM shares a single timebase, so servo and audio cannot be used simultaneously. This means the behaviour in the simulator does not reflect the hardware.

**Comment by abchatra** [comment]
This is a bug on DAL. Can't fix from our side.
