### ISSUE TITLE
.hex compilation takes several seconds on slow system

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#350]
On Firefox (Iceweasel) on Raspberry Pi, it takes ~10 sec to get a .hex file. The web site is generally slow but this feels a bit too slow.

**Comment by mmoskal** [comment]
I've seen that on a couple years old Linux laptop running Firefox too.

**Comment by abchatra** [comment]
We will evaluate performance ongoing basis. Closing tracking issues here.
