### ISSUE TITLE
onPinPressed vs. pinIsPressed

### ISSUE THREAD

**Issue by jpiay** [Microsoft/pxt#3509]
I would suggest replacing "onPinPressed" by "onPinClicked" to avoid confusion. Thanks.

![pressed](https://user-images.githubusercontent.com/30749947/32985907-c89a756a-ccc5-11e7-8404-38db79e0aed1.png)

**Comment by microsoftsam** [comment]
Related bugs: 
https://github.com/Microsoft/pxt/issues/2495
https://github.com/Microsoft/pxt/issues/540

**Comment by abchatra** [comment]
@jpiay Good feedback. Though note we don't change API during the school year to keep it constant for the teachers (even if a API name is misnomer).  We will definitely consider the change during the next major release of Micro:bit.

**Comment by jpiay** [comment]
Thanks.
