### ISSUE TITLE
Could functions (made in blocks) have parameters added?

### ISSUE THREAD

**Issue by philgolden** [Microsoft/pxt#3510]
It would be awesome if there was a capability to add a parameter to a function declaration using Makecode for Minecraft blocks. We have some code that is crying out for a parameterized function, however the only way I know how to do this with blocks is to switch to Javascript, add the parameter with type, and then switch back to blocks. The resultant function now appears as a single grey 'block' in an 'On start' block. It would be great if we could simply add a parameter and have the function look 'normal' in blocks. 

PS> Sorry if this is the wrong forum for suggested features

**Comment by abchatra** [comment]
Thanks @philgolden. This is the right forum for suggested features. This is totally feasible. Only design concern is the ease of adding parameters. Can you please elaborate your use case? Like what kind of parameters would like to pass? We have a notion of types and making it intuitive for students is bit hard problem.

**Comment by philgolden** [comment]
Hi Abhijith,

Thanks very much for the reply. Below is my use case: I have my students
using the agent to build structures. We have chosen to create a single
function that builds a wall, and then use parameters and loops to create
different things.

In this case it would be great if the buildwall function could accept a
single integer type argument  ('size'). This would mean we could halve the
number of blocks in the repeat loops below.

Please let me know if this makes sense.

Phil

 [image: Inline images 1]

**Comment by abchatra** [comment]
Yes makes sense. Thanks for the feedback.

**Comment by smartyw** [comment]
+1

**Comment by TAKeanice** [comment]
This seems to have been closed without resolving it. I am curious if this is still a planned feature or not.

**Comment by abchatra** [comment]
Tracked here: https://github.com/Microsoft/pxt-microbit/issues/689
We are actively working on this. ETA end of feb.
