### ISSUE TITLE
can't launch the editor with URL

### ISSUE THREAD

**Issue by WinEcos** [Microsoft/pxt#3513]
hi guys 
I want to build custom the editor of pxt , such as makecode.microbit.org website .
guide to pxt repro steps to init environment (like nodejs / npm / jake / typings,etc.) 
all of done and got the message using 'pxt serve' command as bellow : 

[wsb@localhost data]pxt serve
Using target PXT/microbit with build engine yotta
Target dir:   /data/node_modules/pxt-microbit
PXT Core dir: /data/node_modules/pxt-core
Going to /data/node_modules/pxt-microbit
No sim/tsconfig.json; assuming npm installed package
Starting server in /data/node_modules/pxt-microbit
With pxt core at /data/node_modules/pxt-core
starting local ws server at 3233...
serial: monitoring ports...

To launch the editor, open this URL:
http://localhost:3232/#local_token=355295ae-bb31-410b-8016-e400b4668899&wsport=3233

---------------------------------------------
opening http://localhost:3232/#local_token=355295ae-bb31-410b-8016-e400b4668899&wsport=3233
serial: connecting to /dev/ttyS0 by undefined (undefined)
serial: connecting to /dev/ttyS1 by undefined (undefined)
serial: connecting to /dev/ttyS2 by undefined (undefined)
serial: connecting to /dev/ttyS3 by undefined (undefined)
serial: connected to /dev/ttyS0 by undefined (undefined)

copied and opening the URL above on web browser , it's not working ,
![pic_003](https://user-images.githubusercontent.com/9930176/33167085-636c9140-d077-11e7-8042-ecb4cf2edd71.png)

so , may I mistake somethings ? ? 

Thanks in advance !

**Comment by rsrini7** [comment]
I am facing issue in pxt serve command. Below error occurs in windows 10

I:\Microbit\pxt-microbit>pxt serve
Could not determine target's pxt-core location, falling back to default: I:\Microbit\pxt-microbit\node_modules\pxt-core
Using target PXT/microbit with build engine yotta
  Target dir:   I:\Microbit\pxt-microbit
  PXT Core dir: I:\Microbit\pxt-microbit\node_modules\pxt-core
building sim...
[run] cd sim; node ../node_modules/typescript/bin/tsc
log strings: 63 files; 0 strings -> sim-strings.json
Could not determine target's pxt-core location, falling back to default: I:\Microbit\pxt-microbit\node_modules\pxt-core
building target.json in I:\Microbit\pxt-microbit...
building libs/core
  skip native build of non-project
building libs/radio
  skip native build of non-project
building libs/devices
  skip native build of non-project
building libs/bluetooth
  skip native build of non-project
building libs\blocksprj
*** yotta target bbc-microbit-classic-gcc
INTERNAL ERROR: Error: spawn yotta ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by rsrini7** [comment]
@WinEcos 

Seems only supported in Linux ? not for Windows ? Below your log expects /dev/tty* related to linux. ?


serial: connecting to /dev/ttyS0 by undefined (undefined)
serial: connecting to /dev/ttyS1 by undefined (undefined)
serial: connecting to /dev/ttyS2 by undefined (undefined)
serial: connecting to /dev/ttyS3 by undefined (undefined)
serial: connected to /dev/ttyS0 by undefined (undefined)

**Comment by pelikhan** [comment]
Make sure your system is setup to build yotta projects. See https://www.mbed.com/en/platform/software/mbed-yotta/

________________________________

**Comment by rsrini7** [comment]
@pelikhan Thanks. After download yotta.. lot of changes done to make it work. 
In windows it works..

**Comment by WinEcos** [comment]
@rsrini7  CentOS 7.0

**Comment by WinEcos** [comment]
@pelikhan  haven't yotta for Linux ?

**Comment by pelikhan** [comment]
You'll need to ask ARM for any yotta related questions.
