### ISSUE TITLE
The scrollbar can't be dragged manually.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3514]
**Repro Step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Click "?" to show the instruction which displayed on the right of the page
- Drag the scroll bar manually

**Expected Result:**
The scroll bar should be dragged manually.

**Actual Result:**
The other scroll bar will affect it. Can't drag it manually.
![bcf37f1f-1629-44eb-b919-cfa0d14ade23](https://user-images.githubusercontent.com/17866936/33167791-ae397420-d079-11e7-842e-4cb33fa10335.gif)

**Comment by carlosperate** [comment]
This issue is still present, where the blockly workspace scrollbar sits on top of the iframe scrollbar, making it inaccessible.
Tested in Edge 41, Firefox 57, Chrome 63.

**Comment by Helen09** [comment]
I have moved this issue to https://github.com/Microsoft/pxt-microbit/issues
Please help close it.
