### ISSUE TITLE
when using pxt cli at the first time,  it raise the bug that the hex file is not available.

### ISSUE THREAD

**Issue by macomzzl** [Microsoft/pxt#3517]
when using pxt cli (like:```pxt build```)at the first time, it raise the bug below.
```
{ sha: '891e8d1de39291e987de74fd39e3def559f1b1d3756d49b30abded43b3ab113c' }
pxt_modules/core/dal.d.ts(1,1): error TS9043: The hex file is not available, please connect to internet and try again.
{ Error: getaddrinfo ENOTFOUND www.pxt.io www.pxt.io:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.pxt.io',
  host: 'www.pxt.io',
  port: 443 }
```
And after I connected  Internet, and run```pxt build``` again, It work fine. Then I disconnect Internet, It can still work. 
So my question is why we should connect  Internet for the first time. Is there a way to avoid to connect  Internet for the first time?

**Comment by abchatra** [comment]
We get the default hex file from the internet for the first time. You need it for that.
