### ISSUE TITLE
Servo simulation opposite of actual servo

### ISSUE THREAD

**Issue by zhikaitan** [Microsoft/pxt#3518]
Hi, I've noticed that the servo simulation is opposite of an actual servo when connected to the micro:bit. This means that where it shows it at 180, it should be 0 instead.

**Comment by abchatra** [comment]
Is your servo calibrated as here? https://makecode.adafruit.com/projects/light-monster/make

**Comment by zhikaitan** [comment]
<img width="700" alt="screen shot 2017-11-21 at 3 17 05 pm" src="https://user-images.githubusercontent.com/5276157/33534786-bd403710-d8e4-11e7-913f-5f068ccf5bc5.png">
I have used this code in the test, and as per the video below, you'll see the servo actually turns in the opposite direction.

https://youtu.be/yvxtxoY5ibc

If based on the simulator the notch is the identifying mark, then yea, its opposite, regardless of calibration.

**Comment by pelikhan** [comment]
Thank you for reporting this. The fix will be in the next microbit deployment.
