### ISSUE TITLE
pasted function in JS won't convert to blocks unless call is added

### ISSUE THREAD

**Issue by Geoffree3** [Microsoft/pxt#3519]
I want to paste code (created in a Blocks project) into another Blocks project but copying is not available in Blocks. Using JS should be possible but throws errors when converting back to Blocks. A simple example demonstrates the problem and a possible work around :
![nov-27-2017 10-55-43](https://user-images.githubusercontent.com/3199856/33264260-baded8b2-d364-11e7-9fcd-9b0021f68662.gif)

**Comment by riknoll** [comment]
Need to cherry-pick https://github.com/Microsoft/pxt/pull/3312

**Comment by riknoll** [comment]
BTW thank you for the detailed repro steps and GIF!

**Comment by abchatra** [comment]
Fixed in alpha
