### ISSUE TITLE
Tilt does not work in simulator

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#3525]
microbit-support:5664

Customer reports that on a group of 14 computers, over half of users could not tilt the micro:bit on mouse over.

This image is of an example where the mouse is over the right side of the simulator

https://imgur.com/a/wu4b5

This was tested on several browsers and the output from Firefox is as follows:
Die Anwendungs-Cache-API (AppCache) sollte nicht mehr verwendet werden und wird in Zukunft entfernt.  Bitte versuchen Sie, ServiceWorker für Offline-Unterstützung zu verwenden.
makecode.microbit.org
Download the React DevTools for a better development experience: https://fb.me/react-devtools
main.js:50424:9
unreachable code after return statement
[Weitere Informationen]
main.js:16367:4
Browser: firefox 57.0 on windows
pxtlib.js:1281:13
unreachable code after return statement
[Weitere Informationen]
main.js:16367:4
failed to load localizations for file [object Object]
pxtlib.js:820:118
HTTP-Content-Type "application/octet-stream" wird nicht unterstützt. Laden der Medienressource https://pxt.azureedge.net/commit/fd36730662721acee07256522e18e577e4275806/blockly/media/click.mp3 fehlgeschlagen.
makecode.microbit.org
HTTP-Content-Type "application/octet-stream" wird nicht unterstützt. Laden der Medienressource https://pxt.azureedge.net/commit/fd36730662721acee07256522e18e577e4275806/blockly/media/disconnect.wav fehlgeschlagen.
makecode.microbit.org
HTTP-Content-Type "application/octet-stream" wird nicht unterstützt. Laden der Medienressource https://pxt.azureedge.net/commit/fd36730662721acee07256522e18e577e4275806/blockly/media/delete.mp3 fehlgeschlagen.
makecode.microbit.org
loading live translations for core
pxtlib.js:1281:13
loading live translations for radio
pxtlib.js:1281:13
loading live translations for core
pxtlib.js:1281:13
loading live translations for radio
pxtlib.js:1281:13
block has non matching arguments: on pin %name|pressed vs wenn Pin|%NAME|gedrückt
pxtlib.js:1281:13
block has non matching arguments: ring tone (Hz)|%note=device_note vs Klingelton (Hz)|%note = Device_note
pxtlib.js:1281:13
block has non matching arguments: on pin %name|pressed vs wenn Pin|%NAME|gedrückt
pxtlib.js:1281:13
block has non matching arguments: ring tone (Hz)|%note=device_note vs Klingelton (Hz)|%note = Device_note
pxtlib.js:1281:13
RefCollection id:3 refs:1 len:0 flags:0 d0:undefined
pxtsim.js:3079:13
RefCollection id:6 refs:1 len:0 flags:0 d0:undefined
pxtsim.js:3079:13
RefCollection id:9 refs:1 len:0 flags:0 d0:undefined
pxtsim.js:3079:13

All machines report the following in About:

makecode.microbit.org -Version: 0.13.34
Microsoft MakeCode Version: 0.14.12
C++ runtime Version: v2.0.0-rc11

Not sure if it is related to https://github.com/Microsoft/pxt/issues/679

**Comment by abchatra** [comment]
I can't repro this with firefox version 57.0 (64-bit

**Comment by microbit-mark** [comment]
I can't reproduce either @abchatra, but will try and get further info. Any thoughts on what might prevent tilt in browser?

**Comment by abchatra** [comment]
Likely bug in Firefox version.

**Comment by microbit-mark** [comment]
Had no further response on this so closing
