### ISSUE TITLE
Broken CSS on pxt.io

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#353]
http://pxt.io is not rendering in all browsers at the moment:

![screen shot 2016-09-21 at 10 27 55](https://cloud.githubusercontent.com/assets/20356546/18705411/1583ea60-7fe6-11e6-9f5d-a6eaed6dcec5.png)

The developer tools suggest that various extra HTML files aren't being included.

**Comment by thomasdenney** [comment]
I suspect this is related to https://github.com/Microsoft/pxt/issues/346, but I'm not certain.

**Comment by pelikhan** [comment]
It is related to mangling the paths for electron.

**Comment by pelikhan** [comment]
Fixed by https://github.com/Microsoft/pxt/commit/b8499b3c1b098a0bede0e426603adcf582697e93
