### ISSUE TITLE
set Brightness issue when using alongside show Icon

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#3530]
LED brightness remains at a dimmed level despite declaring the level in the program. This occurs when using a combination of the basic.showIcon and plot.LED functions. I have tried a variety of blocks to reproduce and results are the same.

The LEDs seem to be dimmer than 100.

![kapture 2017-11-30 at 14 47 42](https://user-images.githubusercontent.com/31242877/33437390-af55b966-d5df-11e7-99ca-71c7681cdff6.gif)
<img width="945" alt="screen shot 2017-11-30 at 14 44 28" src="https://user-images.githubusercontent.com/31242877/33437395-b1c168b2-d5df-11e7-9d29-5e7fb45a719c.png">
<img width="953" alt="screen shot 2017-11-30 at 14 43 56" src="https://user-images.githubusercontent.com/31242877/33437396-b1ed1e62-d5df-11e7-85d6-31b7b69c33d0.png">
<img width="911" alt="screen shot 2017-11-30 at 14 42 34" src="https://user-images.githubusercontent.com/31242877/33437397-b2068b0e-d5df-11e7-9f7c-07449f2e021a.png">

This occurs in the simulator and on the hardware and maybe related to https://github.com/Microsoft/pxt/issues/3196

**Comment by pelikhan** [comment]
Our image parser needs to emit 0xff values for on pixels instead of 0x01. Otherwise this happens when switching to grey scale mode.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microbit-mark** [comment]
This has been reported by another user too.

**Comment by nielsswinkels** [comment]
I just ran into what I think is the same bug. It behaves correct on the simulator (firefox) but not on the hardware. Very weird bug to run into.

**Comment by nielsswinkels** [comment]
Even setting a pixel to brightness 255 does not provide a workaround this bug:
[](https://makecode.microbit.org/_F0b1hPKYJPT6)

**Comment by microbit-mark** [comment]
Re opened here https://github.com/Microsoft/pxt-microbit/issues/628
