### ISSUE TITLE
Link "while loop" navigates to the responding page of "do-while loop".

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3539]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Click "_Setting_" and select "_Javascript-->Statements_"
- Click link "_while loop_"

**Expected Result:**
Afte click "_while loop_", it should navigate to [http://devdocs.io/javascript/statements/while](url)

**Actual Result:**
After click "_while loop_", it navigate to [http://devdocs.io/javascript/statements/do...while](url) which is the responding page of "_do-while loop_"

**Comment by ganicke** [comment]
Fixed in #3561
