### ISSUE TITLE
EU Cookie legislation

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#354]
Currently in the footer of the documentation there is a link to [Microsoft's privacy page](https://www.pxt.io/privacy), but does there need to be an additional warning for the first use of the editor? The editor does do tracking - which is what the law tries to restrict - but I'm unclear on whether there needs to be more information or an opt-out.

When you visit https://microbit.co.uk for the first time you see the following warning:

<img width="740" alt="screen shot 2016-09-21 at 10 38 23" src="https://cloud.githubusercontent.com/assets/20356546/18705935/dd21fc46-7fe7-11e6-99cb-dcf59ce065e9.png">

By way of comparison, https://bbc.co.uk usually shows this on the first visit:

<img width="919" alt="screen shot 2016-09-21 at 10 41 47" src="https://cloud.githubusercontent.com/assets/20356546/18706016/1cca9aba-7fe8-11e6-8c6c-1b351895e7e6.png">

**Comment by pelikhan** [comment]
Fix is live now.
![image](https://cloud.githubusercontent.com/assets/4175913/18746638/6a87853e-807d-11e6-8b20-7a0ac73e88c3.png)

**Comment by abchatra** [comment]
Peli: Docs need this

**Comment by OwenBrotherwood** [comment]
https://github.com/Microsoft/pxt/issues/658 
And I was looking what help was wanted, this was the only issue which does not seem to need help.
Other Open Source Projects have a tag that indicates an easy issue if someone wants to submit a patch

**Comment by pelikhan** [comment]
The "easy patch" is a great suggestion! @abchatra we should identify low hanging fruit that someone in the community could pick up.

**Comment by abchatra** [comment]
Closing this, main page has a cookie.
