### ISSUE TITLE
There is no Voice in the Video and the icon "Full Screen" didn't work on FireFox 

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#3540]
Repro steps:
• Navigate to https://makecode.microbit.org/beta
• Click "Projects" ->"Guitar"
• Play the video and click the icon "Full Screen"

Expected result:
 1. There is Voice in the Video
 2. The Video can be played with "Full Screen"

Actual result:
 1. There is no Voice in the Video on FireFox
 2. The Video can not be played with "Full Screen" on Edge, IE, FireFox

FireFox:
![firefox](https://user-images.githubusercontent.com/11880996/33475453-75b5ebba-d6b9-11e7-8677-f982d693491b.gif)

Chorme:
![chrome-guitar](https://user-images.githubusercontent.com/11880996/33475467-81dfce92-d6b9-11e7-862f-f3b802102f06.gif)

**Comment by Helen09** [comment]
There is Voice in the Video on FireFox now, but the Video can not be played with "Full Screen" on FireFox

**Comment by abchatra** [comment]
Move to microbit repo
