### ISSUE TITLE
Function with parameters can't be displayed like a Function without parameters.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3542]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Switch to " _{}JavaScript_" and copy the following code to content panel:
"_let item: string[] = []
function doSomething() {
    for (let index = 0; index <= 7; index++) {
        basic.showArrow(index)
        basic.pause(300)
    }
}
input.onButtonPressed(Button.A, () => {
    doSomething()
    item = ["H", "I", "J", "K", "L", "M"]
    iteratorList(item);
})
function iteratorList(item: string[]) {
    for (let index = 0; index < 4; index++) {
        basic.showString(item[index]);
        basic.pause(500);
    }
}_
"
- Then back to "Blocks" and Run the project

**Expected Result:**
Function "_iterator(item:string[])_ " should display like this:
![function](https://user-images.githubusercontent.com/17866936/33476614-8e38acfa-d6bd-11e7-9b67-a6ab251e8c03.PNG)

**Actual Result:**
After switched back to "Blocks", Function "_iterator(item:string[])_ " displays like following: 
![fucntionerror](https://user-images.githubusercontent.com/17866936/33476708-e712e46c-d6bd-11e7-809e-05c34207b190.PNG)

**Comment by abchatra** [comment]
We don't have support for parameters in functions. We have issues which track enhancement requests. Closing this.
