### ISSUE TITLE
Cannot escape About page if windows banner shows up in the background

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#3546]
The dimmer does go away due to interaction with About and windows banner.

- open the editor in anonymous window, on windows
- click download to pop download dialog
- wait for windows banner to pop up
- close while banner is on

![image](https://user-images.githubusercontent.com/4175913/33499353-716a7e5c-d689-11e7-90ea-84491d8e644d.png)

**Comment by cait1inhennessy** [comment]
This happens for Adafruit too.

**Comment by samelhusseini** [comment]
This has been fixed.
