### ISSUE TITLE
Problem with micro:bit tutorial authoring

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#3547]
Getting started step 5:
![mb_step_5](https://user-images.githubusercontent.com/13754588/33500294-304335dc-d68d-11e7-8300-379008dd3343.PNG)

**Comment by riknoll** [comment]
Also step 6

**Comment by ganicke** [comment]
@microsoftsam - The ``###`` used as a para separator is showing up in the hint view. We need to exclude it from the step text scrape for hints.

**Comment by microsoftsam** [comment]
You need to add a space I think? after the ###

**Comment by ganicke** [comment]
K, lemme try...

**Comment by ganicke** [comment]
Ah, no luck with space, tab before or after.

**Comment by ganicke** [comment]
@microsoftsam , looking at this again, `v0` doesn't have the `newAuthoring` logic to detect the `###`:

```typescript
let stepInfo: editor.TutorialStepInfo[] = [];
tutorialmd.replace(newAuthoring ? /^##[^#](.*)$/gmi : /^###[^#](.*)$/gmi, (f, s) => {
    let info: editor.TutorialStepInfo = {
        fullscreen: s.indexOf('@fullscreen') > -1
    }
    stepInfo.push(info);
    return ""
});
```

**Comment by ganicke** [comment]
This is fixed in https://makecode.microbit.org/beta (an upgrade from pxt - `v0`?).
