### ISSUE TITLE
Editor doesn't launch in private browsing mode in Safari

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#355]
When you are in private browsing mode in Safari (OS X/iOS), the [localStorage API is unavailable](http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st), which means the editor doesn't launch.

I will add `typeof localStorage === 'object'` as a requirement in browser support, and document it in the micro:bit docs.

**Comment by pelikhan** [comment]
In such case, we can simply use the memoryworkspace. I think that s should be already handled. It is important to support that scenario.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
