### ISSUE TITLE
Scrolling an image in a negative direction crashes micro:bit

### ISSUE THREAD

**Issue by thereal-Cryptic** [Microsoft/pxt#3554]
If you try to get an image to scroll in from the left using `image.scrollImage(-1,150)` it will freeze your micro:bit. Scrolling to a negative number works on the simulator but will crash when running on an actually micro:bit.

This example below will scroll to the tick mark on the simulator but will cause a micro:bit to become stuck on the cross.

```javascript
input.onButtonPressed(Button.A, () => {
    images.createImage(`
        . . . . #
        . . . # .
        # . # . .
        . # . . .
        . . . . .
        `).scrollImage(-1, 200)
})
images.createImage(`
    # . . . #
    . # . # .
    . . # . .
    . # . # .
    # . . . #
    `).showImage(0)
```

**Comment by abchatra** [comment]
Moved to https://github.com/Microsoft/pxt-microbit/issues/918
