### ISSUE TITLE
Bitwise NOT not support?

### ISSUE THREAD

**Issue by xmeow** [Microsoft/pxt#3556]
![image](https://user-images.githubusercontent.com/3390845/33538443-5404e864-d8fc-11e7-9615-ccf2e1b061de.png)
here is what I type input microbit makecode editor, but code check output 'unsupported prefix unary operation';

**Comment by CleoQc** [comment]
This was closed without comments. I'm facing the same issue now. Is there another approach?

**Comment by abchatra** [comment]
This is fixed in the later versions of pxt. We have not released the patch etc. It will be released in next couple of months.

**Comment by CleoQc** [comment]
Thanks for coming back to me on this. In the meantime is there a workaround?
