### ISSUE TITLE
There is "wrinkle" on the selected box(IE & Edge)

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3592]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- choose " _?-->JavaScript-->Statements_" and then click any link you like, such as "_const 语句_"

**Expected Result:**
It should display like the following:
![selectedbox](https://user-images.githubusercontent.com/17866936/33706863-72c9557a-db70-11e7-9799-5645f4b3fbab.PNG)

**Actual Result:**
![selectissue1](https://user-images.githubusercontent.com/17866936/33706872-791d1024-db70-11e7-8e7b-e0def756b45b.PNG) 
& 
![selected](https://user-images.githubusercontent.com/17866936/33707516-940a11b4-db72-11e7-96d6-ae4417a52e32.PNG)

**Comment by microsoftsam** [comment]
Won't fix. This is how outlines work, they outline the entire element and if part of the element is larger text, it doesn't form an even rect around.
