### ISSUE TITLE
Documentation for Buffer class?

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#3594]
I can't seem to find any documentation for the Buffer class - is it missing or not linked into the help system? At the moment I seem to need to reverse-engineer the code files to work out how this works?

![screen shot 2017-12-07 at 15 23 58](https://user-images.githubusercontent.com/25079586/33722842-fc43d748-db62-11e7-8669-988b38c5f93e.png)

**Comment by ganicke** [comment]
Buffer topics added in https://github.com/Microsoft/pxt-microbit/pull/601
