### ISSUE TITLE
Floating window appears on the pause(ms) block

### ISSUE THREAD

**Issue by shunzhan** [Microsoft/pxt#3600]
**Repro steps:**
• Navigating to https://makecode.microbit.org/beta
• Choose any Input block and add pause(ms) block under it
• Input a decimal number in pause(ms) block 
• Wait a moment and observe
**Expected Result:**
Floating window shouldn't appears on the pause(ms) block
**Actual Result:**
![edit](https://user-images.githubusercontent.com/34087467/33748655-b6878568-dc04-11e7-88a3-d37566795e5e.gif)

**Comment by abchatra** [comment]
floating point is not supported in micro:bit

**Comment by shunzhan** [comment]
close as by design
