### ISSUE TITLE
Block is deleted when user dragged the block to the space below the simulator

### ISSUE THREAD

**Issue by shunzhan** [Microsoft/pxt#3602]
**Repro steps:**
• Navigating to https://makecode.microbit.org/beta
• Input any one block
• Drag the block to the space below the simulator
**Expected Result:**
Block shouldn't be deleted.
**Actual Result:**
Block was deleted when drag the block to the space below the simulator
![delete](https://user-images.githubusercontent.com/34087467/33754741-aaa23fa8-dc28-11e7-9503-891a3f72d56a.gif)

**Comment by microsoftsam** [comment]
This is the correct behaviour since you dragged the block outside of the Blockly context. Won't fix.
