### ISSUE TITLE
"Show leds" block can display in simulator after dragged out

### ISSUE THREAD

**Issue by shunzhan** [Microsoft/pxt#3603]
**Repro steps:**
• Navigating to https://makecode.microbit.org/beta
• Add blocks like blow picture
• Drag the one block to the simulator and click the buttonA

**Expected Result:**
"Show leds" block should not display in simulator after dragged out
**Actual Result:**
"Show leds" block can display in simulator after dragged out
![move](https://user-images.githubusercontent.com/34087467/33754444-316f6954-dc27-11e7-864f-6cc84602db78.gif)

**Comment by microsoftsam** [comment]
This is because you're still dragging. As you noticed when you dragged back into the workspace, the block was still being dragged. 
You need to make the change before it takes effect.
