### ISSUE TITLE
serial: simulator and real device differ in waiting for newlines

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#3608]
In the following example
https://makecode.microbit.org/_K5q6CuEbyeuw

<img width="588" alt="image" src="https://user-images.githubusercontent.com/147113/33784908-939b0a74-dc5a-11e7-891b-20c356a05ba3.png">
```
let rxString = ""
rxString = ""
basic.showIcon(IconNames.Heart)
basic.forever(() => {
    rxString = serial.readUntil(serial.delimiters(Delimiters.NewLine))
    basic.showString(rxString)
})
```

On the micro:bit device the '❤️' image stays on the screen until a newline is sent over serial

On the simulator, the '❤️' disappears immediately.

Is there some simulated way to send stuff over serial?

**Comment by abchatra** [comment]
There is no simulated way for this.
