### ISSUE TITLE
serial.readbuffer API is confusing/not working properly

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#3614]
The serial.readBuffer(n) API is confusing, or not working as advertised in the documentation. 

makecode.microbit.org version: 0.13.52
Microsoft MakeCode version: 0.14.27
C++ runtime version: v2.0.0-rc11

The docs say that it will return a buffer containing input from the serial port, or empty if no data is available.

![screen shot 2017-12-10 at 10 56 21](https://user-images.githubusercontent.com/25079586/33804262-0c88f1aa-dd99-11e7-9829-9a3ca75d19f5.png)

However, the below program shows that serial.readBuffer is actually a blocking service. If you run this program with no serial data available, the heart is displayed constantly. As soon as you send a single character on the serial port, the cross (X) is displayed indicating that 1 character has been received. The square (null) and the tick (no data) are never seen. Press the A button and the heart is displayed, and it stays there until a new character arrives.

Could you either correct the documentation, or fix the API? Thanks!

```
input.onButtonPressed(Button.A, () => {
    basic.showIcon(IconNames.Heart)
})
let data: Buffer = null
basic.showIcon(IconNames.Heart)
basic.forever(() => {
    data = serial.readBuffer(1)
    if (data ==     null) {
        basic.showIcon(IconNames.Square)
    } else if (data.length != 1) {
        basic.showIcon(IconNames.Yes)
    } else {
        basic.showIcon(IconNames.No)
    }
})
```

**Comment by abchatra** [comment]
fixed
