### ISSUE TITLE
Variables get initialised twice in javascript view

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#3616]
Variables that are initialised at start to a non zero value, get initialised twice. First to zero, then to the user provided value. This looks very confusing when viewing the javascript.

![screen shot 2017-12-10 at 11 16 01](https://user-images.githubusercontent.com/25079586/33804394-a1fc4f50-dd9b-11e7-8dd2-1b481af4fcd2.png)

```
let HOST_CMD_FF = 0
let HOST_CMD_NO_SIGNAL = 0
let HOST_CMD_PAGE1 = 0
let HOST_CMD_PARAM_MASK = 0
let STATE_DATA = 0
let STATE_UNKNOWN = 0
let state = 0
let STATE_PARAM = 0
let STATE_CMD = 0
let HOST_CMD_FOLLOWS = 0
let byte = 0
let data: Buffer = null
HOST_CMD_FOLLOWS = 255
STATE_CMD = 1
STATE_PARAM = 2
STATE_DATA = 3
HOST_CMD_PARAM_MASK = 128
HOST_CMD_PAGE1 = 129
HOST_CMD_NO_SIGNAL = 253
HOST_CMD_FF = 254
HOST_CMD_FOLLOWS = 255
state = STATE_UNKNOWN
basic.showIcon(IconNames.Heart)
```

**Comment by DavidWhaleMEF** [comment]
makecode.microbit.org version: 0.13.52
Microsoft MakeCode version: 0.14.27
C++ runtime version: v2.0.0-rc11

**Comment by abchatra** [comment]
We don't have solution for this today. Can't fix from our end.
