### ISSUE TITLE
Strange locking behaviour observed with serial.readBuffer

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#3617]
makecode.microbit.org version: 0.13.52
Microsoft MakeCode version: 0.14.27
C++ runtime version: v2.0.0-rc11

The following program demonstrates an observed anomaly with how the serial.readBuffer is working.

To reproduce the problem, open a serial terminal and type repeated 'a' and 'z' characters (making sure there is no line buffering enabled in your serial terminal, so that data is sent immediately).

You will see '3' and '4' on the display.

Type faster and faster, eventual the program gets stuck on a single number and no more data is processed.

I had thought the micro:bit had locked (as per a related problem with MicroPython), but I added in a button press handler. Press the button when it has locked and you see the heart, after the delay expires from the heart, you then get a run of receive characters again and '3' and '4' is displayed very quickly on the display, finally it is back to normal again.

```
input.onButtonPressed(Button.A, () => {
    basic.showIcon(IconNames.Heart)
})
let data: Buffer = null
let byte = 0
basic.showIcon(IconNames.Heart)
basic.forever(() => {
    data = serial.readBuffer(1)
    byte = data.getNumber(NumberFormat.UInt8LE, 0)
    byte = byte / 28
    basic.showNumber(byte, 0)
})
```

**Comment by DavidWhaleMEF** [comment]
So, @finneyj I have a random hunch this is something going wrong with the event queue?

However, I get similar serial port locking behaviour in MicroPython, so I wonder if this is mbed related?

Here is the MicroPython issue (my bit is further down) https://github.com/bbcmicrobit/micropython/issues/472

**Comment by DavidWhaleMEF** [comment]
Firmware version
DAPLink Firmware - see https://mbed.com/daplink
Version: 0234
Build:   Oct 12 2015 14:39:34

**Comment by pelikhan** [comment]
Could you try 0241 as well?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
