### ISSUE TITLE
Windows 10 App hang

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#3618]
Install https://www.microsoft.com/store/apps/9pjc7sv48lcx

1. Change the language to Japanese in the windows 10 App
2. Reset in the app
3. App hangs

![image](https://user-images.githubusercontent.com/6107272/33810040-7e1cebd0-ddb4-11e7-89ff-e099c3e090dd.png)

**Comment by pelikhan** [comment]
The problem is that escape all non-latin characters from the default project name at https://github.com/Microsoft/pxt/blob/v0/pxtwinrt/winrtworkspace.ts#L181 . As a result, we fail to create the new project.

**Comment by abchatra** [comment]
We resolve when it is fixed in beta.
