### ISSUE TITLE
Give an option to chose the seperator for the csv file exported from console editor.

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#3619]
Following is the feedback from the microbit foundation slack
--------------
-@abchatra the .csv exported data use a comma to separate value, would it be possible to choose the separator ? In france, a semicolon is often used. Even if we can use research and replace function of a text editor, it would be easier for pupills if they get directly their data.

Indeed, in the countries in which the comma is used for the decimal separator, we often feel left aside with educational resources that default to comma when exporting to csv, when the default separator for these countries is the semicolon. If you use Excel, you cannot just double click on the file. You have to use the import functionality (Data-Get External data- from text) and choose the comma as separator, which is a little bit more difficult to explain to kids than just simply double-click...

**Comment by pelikhan** [comment]
I think we can use the \t tab character instead.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
