### ISSUE TITLE
Zoom broken if a user zooms in via Ctrl+Scroll as well as Ctrl+Plus

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#362]
If I zoom in using Ctrl+Scroll and then try to zoom in using Ctrl+Plus, the zooming behaviour is broken.

**Comment by microsoftsam** [comment]
Microsoft/monaco-editor#154

**Comment by abchatra** [comment]
@microsoftsam This doesn't repro for me. If it doesn't repro for you can you close?

**Comment by microsoftsam** [comment]
Yes, still repro's. Waiting for the Monaco editor to expose EditorZoom.

**Comment by abchatra** [comment]
Fixed?

**Comment by microsoftsam** [comment]
Nope, and this won't be fixed until the monaco editor exposes the EditorZoom object. 
I would say we either: live with having this bug around, and knowing that it only really repros if you do both of Zoom with Mouse and Zoom with Keyboard.
or alternately we disabled Zoom with Keyboard, since we already have Zoom buttons on the screen.

**Comment by microsoftsam** [comment]
Looks like the monaco editor team doesn't plan to expose the EditorZoom object, closing as won't fix.
