### ISSUE TITLE
ERROR: the arm gcc program arm-none-eabi-gcc could not be found

### ISSUE THREAD

**Issue by WinEcos** [Microsoft/pxt#3628]
hi guys 
i want to build own editor of micro:bit via pxt-microbit project and then git clone repro it 

but ,when i using 'npm install' and to execute 'pxt serve' command , i got the error message as bellow
![pic_001](https://user-images.githubusercontent.com/9930176/33869714-4874c420-df45-11e7-9162-2c8210e99f91.png)

i'm 100% sure that  arm-none-eabi-gcc has installed as bellow
![pic_002](https://user-images.githubusercontent.com/9930176/33869827-efd03510-df45-11e7-8e60-ecc4506f406f.png)

**My questions are** 
1, the pxt-microbit project is working fine ?? 
2,  i 'm learning the README.md methods to build pxt-microbit , failed ~.. there are no working fine version for pxt-microbit ? 

thanks a lot

**Comment by riknoll** [comment]
Make sure you have added arm-none-eabi-gcc to your path

**Comment by WinEcos** [comment]
@riknoll  need to add arm-none-eabi-gcc to /usr/bin/ or other path ? sorry , i'm not sure where it . would you like help to point out  ? 

thanks a lot.

**Comment by pelikhan** [comment]
Make you sure you follow the ARM yotta toolchain installatio ninstructions .

**Comment by WinEcos** [comment]
@pelikhan  thanks peli , as i said above(screenshot #2) , arm-none-eabi-gcc have installed , not sure that what does means you said the ARM yotta toolchain installation , would you like share more details for links or other info ? 

thanks a lot

**Comment by riknoll** [comment]
It needs to be on your unix/linux path. If you type `arm-none-eabi-gcc` into bash (just that, not the full path like in the second screenshot) do you get an error? If you see an error, you need to add a line to your `~/.profile` file. This might help: https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix

**Comment by WinEcos** [comment]
@riknoll  Thanks so much ,buddy , i've solved this issue !
