### ISSUE TITLE
Ctrl+Scroll to zoom on a mac should be Cmd+Scroll

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#363]
Ctrl should be Cmd on a mac in Blockly & Monaco editor.

**Comment by microsoftsam** [comment]
Microsoft/vscode#12477

**Comment by pelikhan** [comment]
There is also code in blocks to handle Ctrl+scroll... Both editors should behave the same.

**Comment by microsoftsam** [comment]
@pelikhan commit b02eb10a29d354cac7518e71204be7a050f54ce8 should have fixed the code in blockly to handle Cmd+Scroll, and I have a PR out in vscode for fixing that in monaco. Is there anywhere else that needs to handle this?

**Comment by pelikhan** [comment]
Nope.
