### ISSUE TITLE
The scrollbar is displayed differently in Firefox

### ISSUE THREAD

**Issue by shunzhan** [Microsoft/pxt#3642]
**Repro steps**:
• Navigating to https://makecode.microbit.org/beta
• Click "LED" and choose any one block
• Change data and observe the scroll bar that appears 
**Expected Result**: 
![safari](https://user-images.githubusercontent.com/34087467/34037521-0b299e0c-e1c4-11e7-8a2b-9b563ca6125d.png)
**Actual Result**:
The scrollbar is displayed differently in Firefox than safari and chrome
![firefox](https://user-images.githubusercontent.com/34087467/34037528-115a222e-e1c4-11e7-877b-df71734912a1.png)

**Comment by Helen09** [comment]
On **chrome&Safari on mac** show as:
![34037521-0b299e0c-e1c4-11e7-8a2b-9b563ca6125d](https://user-images.githubusercontent.com/23466737/37271651-a5b9690c-25cb-11e8-8bd6-3b5785dbf7a4.png)
On **chrome, edge, IE and firefox on windows** show as:
![34037528-115a222e-e1c4-11e7-877b-df71734912a1](https://user-images.githubusercontent.com/23466737/37271687-cbb1c582-25cb-11e8-9d96-01c4db21ab6b.png)
