### ISSUE TITLE
Block can't be deleted when run end

### ISSUE THREAD

**Issue by shunzhan** [Microsoft/pxt#3643]
**Repro steps**:
• Navigating to https://makecode.microbit.org/beta
• Input a running programs and add a "delete" block
• Delete "delete" block when programs running end
**Expected Result**:
Block should be deleted.
**Actual Result**:
Block can be deleted before run, and can't be deleted after operation
![can delete](https://user-images.githubusercontent.com/34087467/34037502-f69ab188-e1c3-11e7-88e0-e645426587ba.png)

**Comment by abchatra** [comment]
Wont' fix. This is an incorrect use of game block library API.
