### ISSUE TITLE
Clicking slow-mo without the check box in high contrast on mode

### ISSUE THREAD

**Issue by shunzhan** [Microsoft/pxt#3644]
**Repro steps**:
• Navigating to https://makecode.microbit.org/beta
• Click "High Contrast On "
• Click slow-mo button and observe
**Expected Result**:
![chrome](https://user-images.githubusercontent.com/34087467/34037481-ddfa6b82-e1c3-11e7-8f59-0b2da3a15e26.png)
**Actual Result**:
The check box does not appear on slow-mo when user click it
![other site](https://user-images.githubusercontent.com/34087467/34037490-e5364006-e1c3-11e7-9e27-616e3a971795.png)

**Comment by abchatra** [comment]
Can't repro . What browser is this?
