### ISSUE TITLE
"hint" on tutorial avatar bleeds out in other locales

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#3659]
"Hint" works in English because it is just 4 character but it gets much large in other locales, like "suggerimento" in Italian. We should use an icon instead.

**Comment by kumaran-14** [comment]
Can i do this?

**Comment by pelikhan** [comment]
You are welcome to send us a PR, yes!

**Comment by kumaran-14** [comment]
Which files do i need to change? Can you guide me in the right direction.
