### ISSUE TITLE
ReferenceError: Blockly is not defined ???

### ISSUE THREAD

**Issue by WinEcos** [Microsoft/pxt#3664]
![pic_001](https://user-images.githubusercontent.com/9930176/34245399-aeb2312a-e664-11e7-93a0-d416bd7bad23.png)

as you saw , i perform the 'pxt staticpkg' command and generated the HTML files , it's not working online .
so what's happened ? 

Thanks a lot

**Comment by pelikhan** [comment]
staticpkg is not functional for PXT-core v0 (branch that Microbit is using).

________________________________

**Comment by WinEcos** [comment]
@pelikhan yes , ‘pxt staticpkg’ command i used under the branch of pxt-microbit . 
so , would you like share more details that how to build the website of pxt-microbit ? 

thanks a lot

**Comment by WinEcos** [comment]
@pelikhan  would you like added discord discussion group ? here's link : [https://discord.gg/wu3uJyA](url)  . thanks

**Comment by abchatra** [comment]
We don't have support for staticpkg in v0. There is no plan to add at this moment of time.

**Comment by WinEcos** [comment]
@abchatra  which one branch to use staticpkg ? or if i'm used the v0 branch , how to build the working environment of pxt-microbit ? thx

**Comment by abchatra** [comment]
Staticpkg is a feature built on master. Microbit uses v0 which doesn't have this feature and we will have to wait until microbit moves to master. If you have bandwidth feel free to build staticpkg into v0 and give us a pull request.

**Comment by WinEcos** [comment]
@abchatra  thanks so much and how to generator files (HTML,ect.) with v0 of pxt to build same as pxt-microbit ?
