### ISSUE TITLE
INTERNAL ERROR: TypeError: Cannot read property 'replace' of undefined ??

### ISSUE THREAD

**Issue by WinEcos** [Microsoft/pxt#3665]
not sure property 'replace' of undefined what does mean with 'pxt staticpkg' command.
![pic_001](https://user-images.githubusercontent.com/9930176/34287685-d0e4ae70-e723-11e7-9657-b850fcc8ce8b.png)

**Comment by WinEcos** [comment]
@abchatra  why closed this issue ? i'm not found any solutions ~~

**Comment by abchatra** [comment]
I assumed this is same as staticpkg on v0 which is not supported. If not let me know.
