### ISSUE TITLE
Import C/C++ and convert to JavaScript / Blocks

### ISSUE THREAD

**Issue by smartyw** [Microsoft/pxt#3669]
I'm currently, painstakingly converting a working micro:bit C/C++ program into JavaScript / Blocks. I don't use any APIs except for micro:bit APIs and the only issues I've encountered so far concern the lack of support for decimal values. I think it would be possible to automate this conversion via an "Import your C/C++" facility within MakeCode. It wouldn't ever handle all possible C/C++ code but I think a good success arte could be achieved. You could designate it "Beta" and leave it at that status forever.

It would certainly save me lots of time. Maybe it's just me, though? :-)

**Comment by microsoftsam** [comment]
It would be great to understand your scenario. Why are you converting the C/C++ into blocks? Are you trying to surface some driver / functionality to blocks? 

Check out the PXT cli: https://makecode.com/cli
It might save you some pain. After setting up a project locally, you can go ```pxt add cpp``` to add a cpp file to your project. From there you can incorporate whatever cpp library you have into a project (and make use of it in blocks / JS).

**Comment by smartyw** [comment]
Hi @microsoftsam 

no, I usually write examples of the same functionality in both MakeCode and C/C++ and create tutorials for each or at least publish the code for people to use. I always start in C/C++ because I know I will be able to accomplish whatever I want in that language (and I'm somewhat old school as well!).

See http://www.bittysoftware.com/tutorials.html#data_logger for an example of what I do.

Cheers

Martin

**Comment by hnwangkg-ezio** [comment]
Hello, I was doing the same with you recently. I hope to drive my 1.8-inch LCD with my micro:bit. The distress is that my c++ uses Arduino to drive the LCD and use it on the micro:bit. When I clicked on the download, I didn't respond for a long time. Then I was able to remove the library. This made me very annoyed.

**Comment by hnwangkg-ezio** [comment]
I wrote the program on my ubuntu and then uploaded it to github so that when I use micro:bit official website programming can be down to my computer, this time click on the download, no response, I doubt what the problem , but the check is quite troublesome.

**Comment by pelikhan** [comment]
The first time you include c++, it probably needs to generate the compiled image. This takes 1 minute.

________________________________

**Comment by luqmaanb** [comment]
I have a similar issue whereby pressing download doesn't respond. After pressing download 10min later its still trying to download. How do I fix this? On another note, how is the shim.d.ts and enum.d.ts files generated? Is there a specific command to generate them?
