### ISSUE TITLE
'unknown type for new' error when creating instance of a class

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#3671]
Creating a class that implements an interface cannot be instantiated in the return statement like so:

```
function create(): Character {
    return new MChar();
}
interface Character {
}
class MChar implements Character {
} 
```

The only way to get around this error is to create an interim variable that creates the specialized class instance and return that variable like so: 

```
function create(): Character {
        const char = new MChar();
        return new MChar();
    }
```

@tballmsft @riknoll  is this known? Thoughts?

**Comment by tballmsft** [comment]
This should work. Is it giving a type error?

**Comment by tballmsft** [comment]
The problem can be reduced to:
```
class MChar {
}

interface Character {
}

function create(): Character {
    return new MChar();
}
```
It is the presence of the explicit return type that causes the error:
```
unknown type for new
```
The cast of the class to interface should be OK.  

-- Tom
