### ISSUE TITLE
There is an project error

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#3675]
Repro steps:
• Navigate to https://makecode.microbit.org/beta
• Drag some blocks like the followed picture
• Click button "Refresh" under the simulator
![block](https://user-images.githubusercontent.com/11880996/34353178-a518f148-ea61-11e7-810c-bcb6672ac41a.png)

Expected result:
There is no project error

Actual result:
There is an project error: "Program Error: leds.copyTo is not a function"

![program error](https://user-images.githubusercontent.com/11880996/34353970-198f7fde-ea66-11e7-83ca-7277659db74e.gif)

**Comment by abchatra** [comment]
item is an uninitialized variable. This is a user code error.
