### ISSUE TITLE
Editor skips main.ts decompiling

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#3677]
In pxt-microbit

Repro steps: 
- Open project settings and edit settings as text. 
- From the explorer menu click on main.blocks 

The editor skips decompiling and opens the previous main.blocks file, thus overriding your project with a perhaps "very old" version of your code.

No way to recover from that.

**Comment by WinEcos** [comment]
@microsoftsam hi sam , would you like to see this issue for your project : pxt -holidays ? https://github.com/microsoftsam/pxt-holidays/issues/3

Thanks a lot

**Comment by abchatra** [comment]
Explorer actions are P3. Closing as Wont Fix.
