### ISSUE TITLE
no code highlighting on function with "strange" characters

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3678]
If you use an ö, ä, å or similar in the name of a function it does not get the blue color highlight.

![image](https://user-images.githubusercontent.com/5718354/34424057-d6a1b482-ec20-11e7-80c8-63781017d69c.png)

**Comment by samelhusseini** [comment]
The bug here is that doSomething is highlighted in the first place. 
Function names are not meant to be highlighted, so what you're seeing with the strange characters, you'll see with any other function name.

**Comment by nielsswinkels** [comment]
ah. True that.
