### ISSUE TITLE
Prototype stripping blocks from the toolbox for a "limited" view

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#368]
It would be good to have a "limited" view of the toolbox that contains only the relevant blocks needed for a specific tutorial. 
The idea is to have a section in the readme.md or tutorial.md that contains the blocks that are needed for a particular exercise. The app would then only show the blocks needed in the toolbox.

**Comment by abchatra** [comment]
We completed the prototype and I am closing this issue.
