### ISSUE TITLE
Tuple generates a compiler error

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#3683]
This gives a proper error message, saying * unsupported type: [number, number] 0x2000 *
```
let x: [number, number];
x = [10, 10];
```

However, when written like so: 
```
let x: [number, number] = [10,10]
```
we get a * Cannot read property 'flags' of null*
(compiler error)

**Comment by microsoftsam** [comment]
We should spit out a better error message.

**Comment by abchatra** [comment]
We don't support explicit type annotation as we have single type array only. Following is the annotation for number array:

```javascript 
let x: number[];
x = [10, 10]
```
