### ISSUE TITLE
Defining both radio received string and received number does not work

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3684]
In block mode, there exist both "on radio received string" and "on radio received number". But dragging out both makes one grayed out. This is difficult to understand in block mode why they collide.

![radio-confusing](https://user-images.githubusercontent.com/5718354/34455363-f7d10122-ed7d-11e7-827f-c221a49a064c.png)

**Comment by pelikhan** [comment]
Could you share the script?
