### ISSUE TITLE
The 'Help' button is not available under Serial block "serial read string"

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#3687]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Advanced" and then right click "serial read string"
• Click 'Help' to look documentation

**Expected result:**
The 'Help' can be clicked and the block in help document is displayed in right
**Actual result:**
![serial02](https://user-images.githubusercontent.com/23497626/34478036-6237b03e-ef53-11e7-9ebc-eb94198519af.gif)

**Comment by ganicke** [comment]
Fixed in https://github.com/Microsoft/pxt-microbit/pull/609
