### ISSUE TITLE
The result of block "led.plotBarGraph" are different

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3689]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Switch to "_{}JavaScript_" and copy following code into content panel:
_radio.onDataPacketReceived( ({ receivedNumber }) =>  {
    led.plotBarGraph(
    receivedNumber,
    1023
    )
})
radio.sendNumber(input.acceleration(Dimension.X))_
- Swicth back to "_Blocks_" and change the acceleration

**Expected result:**
**Issue 1:**
It should work like following while changing the value of acceleration:
![2058bdf7-4deb-475c-b7bf-05b9a3c39ec8](https://user-images.githubusercontent.com/17866936/34478903-75cb6f06-efde-11e7-8b78-1a82d2c74d9c.gif)
**Issue 2:**
After enable "_Slow-Mo_", it should work as following:
![expectedresult](https://user-images.githubusercontent.com/17866936/34479081-8bbf5786-efdf-11e7-89b3-bf68faa4a89e.PNG)

**Actual Result:**
**Issue 1:**
![3b96d124-ac73-419c-8334-edb2ebc0eb19](https://user-images.githubusercontent.com/17866936/34478942-bbfbd952-efde-11e7-84d0-a4ae046104a9.gif)

**Issue 2:**
After enable "_Slow-Mo_", only one simulator show the result of plotting:
![simulator](https://user-images.githubusercontent.com/17866936/34479035-4bdcd3dc-efdf-11e7-9045-2f5817676a02.PNG)

**Comment by abchatra** [comment]
There is a bug in the user script. It sends data only on "On start" and not in "forever" in your screenshot. Please fix that and verify.
