### ISSUE TITLE
Execute jake command and got a lot of error in pxt project!

### ISSUE THREAD

**Issue by WinEcos** [Microsoft/pxt#3691]
i've used the branch v0 of pxt
see as bellow the screenshots
![pic_001](https://user-images.githubusercontent.com/9930176/34507925-ba48e3d8-f075-11e7-81a2-e6b8bc550b7e.png)

anybody else know how to solve it ? 

Thanks a lot

**Comment by tballmsft** [comment]
you need to do 'typings install' on the v0 branch
