### ISSUE TITLE
pxt-sample not working with 3.0

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#3695]
Hi Richard,

I've been working on javascript-only targets recently and encountered a bunch of problems in simshim.ts. The first is that TypeScript uses absolute paths now for filenames (rather than relative). I have a fix for this in  the simshim branch of pxt.   I've modified pxt-sample in branch pxtv3 and am now getting the following error:

*** Build failed: target build failed: turtle::forwardAsync doesn't return a promise
Error: turtle::forwardAsync doesn't return a promise

I've encountered some others errors as well in simshim.ts (in another target) which relies on TSC, but I am blocked with the one above.

-- Tom

**Comment by BradChan** [comment]
I have the same issue. How to solve it
