### ISSUE TITLE
The full link cannot be read directly.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3700]
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Click "?"(help) and choose Hardware
- Then click "_LEDs_" which in "_The red lights are LEDs(light emitting...)..._" and scroll down

**Expected Result:**
The link should be fully displayed.

**Actual Result:**
The instruction of "_led.enable_" have the same issue.
![capture1](https://user-images.githubusercontent.com/17866936/34707743-07429e50-f507-11e7-99fb-379e5ebb66b9.PNG)

**Comment by ganicke** [comment]
Needs a different ``display:`` style for render in the slider. Both for the `"green message"` and the `"href"`

![image](https://user-images.githubusercontent.com/27789908/35171479-c9124b3e-fd18-11e7-99c9-fc59507a1128.png)

**Comment by Helen09** [comment]
The first issue is not repro and it shows as below on **chrome, Edge and IE**
![2](https://user-images.githubusercontent.com/23466737/37270251-06b407fe-25c6-11e8-84e2-95a4194a61c6.PNG)

**On firefox:**
![3](https://user-images.githubusercontent.com/23466737/37270261-0b348e20-25c6-11e8-910d-d3000c4e3ed6.PNG)
