### ISSUE TITLE
The blocklyPiano covers the block: "play tone ’Middle C‘ for 1 beat".

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3701]
**Repro Step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Drag "_play tone 'Middle C' for 1 beta_" into content panel
- Put it into "_on start_", then change the value "_Middle C_"

**Expected result:**
After changed "_Middle C_" to other value, the blocklyPiano should not cover the block "_play tone 'Middle C' for 1 beta_".

**Actual Result:**
Block "_ring tone(Hz) 'Middle C'_" and "_Middle C_" have the same issue.
![coveredissue](https://user-images.githubusercontent.com/17866936/34710383-fa7cf4f2-f512-11e7-81ef-d8035536c643.gif)

**Comment by abchatra** [comment]
This by design, letting users to experiment with their note. Click needs to be outside of the piano to select it
