### ISSUE TITLE
 The math operation "1 / 0" was allowed.

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#3703]
Repro steps:
• Navigate to https://makecode.microbit.org/beta
• Drag blocks like the followed picture
![math](https://user-images.githubusercontent.com/11880996/34712326-5b5a7194-f51a-11e7-8884-7e3267463147.png)

Expected result:
 The math operation "1 / 0" should not be allowed.
 Actual result:
 The math operation "1 / 0" was allowed.

![math](https://user-images.githubusercontent.com/11880996/34712439-b9f62d38-f51a-11e7-9b8e-11d2935cbdef.gif)

**Comment by riknoll** [comment]
Yep! This is a deliberate choice. Easier for novice programmers to understand.
