### ISSUE TITLE
 There is no instruction for the math operation "^" in the "help" document.

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#3704]
Repro steps:
• Navigate to https://makecode.microbit.org/beta
• Drag blocks like the followed picture
• Right click the block to open the "help" document

![operation](https://user-images.githubusercontent.com/11880996/34712515-f6f730a6-f51a-11e7-941e-4976edfcfeeb.png)

Expected result:
 There should be instruction for the math operation "^" in the "help" document.
Actual result:
 There is no instruction for the math operation "^" in the "help" document.

![operation](https://user-images.githubusercontent.com/11880996/34712747-dc9756c2-f51b-11e7-8a3d-02ff09a69e62.gif)

**Comment by pelikhan** [comment]
We should use ** instead of ^.

**Comment by ganicke** [comment]
Might be in my "power" to add this one.

**Comment by pelikhan** [comment]
Richard is working on pow right now.

**Comment by ganicke** [comment]
Going from caret power to star power?

**Comment by riknoll** [comment]
Yep. https://github.com/Microsoft/pxt/pull/3717 moves to using `**` instead of `^` in the block. The compiled TS will now be `1 ** 2` instead of `Math.pow(1, 2)` as well

**Comment by ganicke** [comment]
Added exponent operator section #3873
