### ISSUE TITLE
Code connection can cause multi player world to crash

### ISSUE THREAD

**Issue by philgolden** [Microsoft/pxt#3720]
Hi,
I am having an issue when I try to use code connection with multi-player Minecraft Education worlds. Specifically the worlds crash very often when using code connection. The problem is far less (almost non existent) if I:
- Create a multi player world without using code connection
- Create single player world with code connection
I am pretty sure that the issue is with our network at the school, but I am trying to understand what the root cause is. I know that our incoming internet connection is not great (20Mbit/s, with up to 30 simultaneous users), and also that our network switches are quite old and have been linked to wireless connectivity issues. 
I am trying to understand what 'network' code connection is using so I can link the crashes to a root cause (e.g. could a slow internet connection cause this behaviour?)
Sorry if this is a dumb question.
Phil

**Comment by samelhusseini** [comment]
Thanks for reaching out Phil. Please post your question on the Minecraft EE tech support pages: https://education.minecraft.net/technical-support
