### ISSUE TITLE
Project names allow seperators

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt#3724]
micro:bit-support:4086
Makecode allows you to use a ',' seperator in the name of your project (project settings). The resulting .hex file that is downloaded cannot then be flashed to the micro:bit. Could the the use of a separator be prevented in the project name, fixed in the download or can users be advised of this in documentation?

**Comment by abchatra** [comment]
If this is not fixed in alpha. Please reopen in pxt-microbit.

**Comment by abchatra** [comment]
I have kept a tracking bug to validate: https://github.com/Microsoft/pxt-microbit/issues/906

**Comment by abchatra** [comment]
# #
