### ISSUE TITLE
Save button not showing in Mobile View

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#3725]
From customer "It appears the lower menu is a bit cramped on an iPod.  We were having trouble saving the filename.  Is there a way to clear the project?  It seems to use an old name."
![ipadscreen1](https://user-images.githubusercontent.com/22108954/34886618-67984e4e-f778-11e7-9aa4-89c9a49b0dc3.png)
![ipadscreen2](https://user-images.githubusercontent.com/22108954/34886625-6dabdfb2-f778-11e7-9093-8e8fb183e6a9.png)

**Comment by abchatra** [comment]
We need a redesign of tablet view and I am closing this in favor of that.
