### ISSUE TITLE
Any way to allow users to enter Hex value in UI?

### ISSUE THREAD

**Issue by jdarling** [Microsoft/pxt#3727]
Building a custom package around the PXT9685 and all of the documentation gives values as hex values.  In the TypeScript files you can enter 0x40 (as an example) and it will nicely convert it to the decimal version (64).  When you try this in the editor though it won't accept the value and instead clears the field back to 0.  Is there a way to make the input accept (or better show and accept) hex values?

Also, I noticed that the approval process for micro:bit talks about micro:bit only hardware, are generic device drivers allowed or does this mean you can't "publish" a generic driver like the PCA9685.  Since the Sonar uses the SR04 generically I'd think you could do generic packages for other parts as well.

**Comment by abchatra** [comment]
Please provide screen shot. If you are referring blocks, input kinds are restricted in favor of less errors to students.

**Comment by jdarling** [comment]
I am referring to blocks.  I agree that input kinds should be restricted, but when dealing with I2C addresses it isn't common to give them in decimal values, almost everyone provides hex values.  So it would be nice if the UI would allow the user to enter hex values "0x40" as an example and it would convert those behind the scenes to integer values (64 in this case).
