### ISSUE TITLE
Long lists of enums are not scrollable

### ISSUE THREAD

**Issue by jdarling** [Microsoft/pxt#3728]
I have a long list (26 items) in one of my enum values, when you open the list in the editor it scrolls off of smaller screens but there is no way to scroll the list of values, so you can't get to any value that isn't on the screen.

**Comment by abchatra** [comment]
Please provide screen shots and repro.

**Comment by jdarling** [comment]
I'll have to break it again as I just created a helper function to take hex values and convert them to integers then provided that instead of worrying about the long list of possible addresses.  Give me a day or two and I'll cobble together an example.

**Comment by samelhusseini** [comment]
It sounds like this is related to https://github.com/Microsoft/pxt-microbit/issues/666

**Comment by samelhusseini** [comment]
Please re-open if not.
