### ISSUE TITLE
support for other languages?

### ISSUE THREAD

**Issue by The-Alchemist** [Microsoft/pxt#3729]
Hi there! 

I'm interested in adding support for another language besides Javascript to the editor.

I'm wondering if:
* it's feasible?
* is there an abstraction in the code for different languages?
* any examples in the code already?

I'm specifically interested in the Logo language.

**Comment by abchatra** [comment]
Entire codebase is typescript. Compilation to blocks to typescript and uses typescript intellisense and Monaco editor. Compiler tool chain is also specific to static typescript.
It is architected to support another language.

But in theory you can add support, just need the entire tool chain written for a new language or have an option to convert blocks to Logo and then to static typscript to make use of compiler toolchain.
