### ISSUE TITLE
The list dialog of variables displayed above the layer of document

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#3732]
Repro steps:
• Navigate to https://makecode.microbit.org/beta
• Drag blocks like the followed picture
• Click the list of variables and open the document
![blockexample](https://user-images.githubusercontent.com/11880996/35022915-3ec295ea-fb30-11e7-8ce3-52385d062ce3.png)

Expected result:
The list dialog of variables should display under the layer of document
Actual result:
The list dialog of variables displayed above the layer of document

![document layer](https://user-images.githubusercontent.com/11880996/35023079-00723a74-fb31-11e7-9558-d24023bf7a12.gif)

**Comment by samelhusseini** [comment]
We should call hideChaff when we open the sideDocs.

**Comment by Helen09** [comment]
I have moved this issue to https://github.com/Microsoft/pxt-microbit/issues
Please help close it
