### ISSUE TITLE
The "Add Comment" couldn't be chosen on IE

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#3733]
Repro steps:
• Navigate to https://makecode.microbit.org/beta on IE
• Drag blocks like the followed picture
• Right click the block to open the list dialog
![blockexamplecomment](https://user-images.githubusercontent.com/11880996/35023793-2536fb4e-fb34-11e7-8e23-d89b9cd81cfe.png)

Expected result:
The "Add Comment" should work
Actual result:
The "Add Comment" couldn't be chosen

![blockexamplecommentie](https://user-images.githubusercontent.com/11880996/35023767-019689ca-fb34-11e7-9fcf-c5e47654c6f5.png)

**Comment by samelhusseini** [comment]
Comments are not supported on IE.
