### ISSUE TITLE
micro:bit Windows 10 app - Downloading program doesn't erase the file system

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#3736]
On the Windows 10 app for micro:bit, when a program is downloaded to the micro:bit the file system is not erased.

This might be done by design, but it's possible users are expecting flash to be erased, as this is the default behaviour of downloading a program from the web app.

![filesystem](https://user-images.githubusercontent.com/29712657/35059504-41fdcce2-fbb3-11e7-869f-1c9d79ddee3c.gif)

**Comment by abchatra** [comment]
Please let me know if this still reproes. I will move it to pxt-microbit repo.
