### ISSUE TITLE
Text join mutator "item" tooltip missing

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#3742]
http://makecode.microbit.org/beta
makecode.microbit.org version: 0.14.2
Microsoft MakeCode version: 0.14.34
C++ runtime version: v2.0.0-rc11

When using the text joing block, and opening the mutator, the tooltips for the "item" blocks are missing and showing "BKY_TEXT_CREATE_JOIN_ITEM_TOOLTIP":

![tooltip](https://user-images.githubusercontent.com/29712657/35146898-775e4806-fd04-11e7-9c95-b48910f68c82.gif)

**Comment by samelhusseini** [comment]
Transferring to pxt-microbit: https://github.com/Microsoft/pxt-microbit/issues/737
