### ISSUE TITLE
Removing item from mutator can leave behind shadow blocks

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#3744]
http://makecode.microbit.org/beta
makecode.microbit.org version: 0.14.2
Microsoft MakeCode version: 0.14.34
C++ runtime version: v2.0.0-rc11

In some conditions when a item is removed from an array or text join, it can leave a "unclickable" shadow block behind:

![mutator_shadow](https://user-images.githubusercontent.com/29712657/35151710-4cf0cda6-fd17-11e7-9b1b-127e4e9a6406.gif)

**Comment by riknoll** [comment]
This looks like a Blockly upstream bug

**Comment by microbit-carlos** [comment]
Should this be cross-posted to https://github.com/Microsoft/pxt-blockly/issues and upstream Blockly?

**Comment by riknoll** [comment]
We should verify before posting a bug on them, I'll take care of that. Thanks!

**Comment by abchatra** [comment]
I am closing this as we are moving away from mutator in v1 and this bug doesn't exist there.
