### ISSUE TITLE
Empty array conversion from blocks to javascript fails.

### ISSUE THREAD

**Issue by jpiay** [Microsoft/pxt#3753]
If I declare an empty array in javascript, I can add this empty array to my 2d array in blocks. 
But if I declare it in blocks, I can't do that because the conversion from blocks to javascript "fails". 
JavaScript replaces "number[][]" by "Array[]".
As far as I can remember, this is happening since the "create an empty array" separate block was removed from the Arrays pane.

[microbit_empty_array_isssue.zip](https://github.com/Microsoft/pxt/files/1654920/microbit_empty_array_isssue.zip)

**Comment by abchatra** [comment]
@jpiay  Please also share the program.

Following will help us a lot:
1. Script program shared either plain text or URL got from 'Share' feature
2. Video of the issue. (already attached here). If you can capture GIF instead of the video, that is great as github has a native support for gif.
