### ISSUE TITLE
Block "Serial write string" can't write string right now

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3755]
**Repro step:**
• Navigate to https://makecode.microbit.org/beta
• Open the below project
https://makecode.microbit.org/_FdKJce3eCCsD

**Expected Result:**
 When clicking "Show data", it should show string "JUMBO" right now

**Actual Result:**
 It can't show string "JUMBO" for a long time
![1](https://user-images.githubusercontent.com/23466737/35266778-1fe00cac-001c-11e8-9417-3b9133b67b9b.gif)

**Comment by carlosperate** [comment]
This also happens when using the serial connection on the Windows 10 app, the data is not flushed very often and can be a bit confusing if a stream of data arrives in blocks, or when data is sent with a button press and only appears after a few presses.

**Comment by Helen09** [comment]
I have moved this issue to https://github.com/Microsoft/pxt-microbit/issues
