### ISSUE TITLE
 When there is one "serial write line", the string only writes once

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3756]
**Repro step:**
• Navigate to https://makecode.microbit.org/beta
• Drag block "serial write line" and make the below program

**Expected Result:**
The output should like below .gif , the string should write few times
![125](https://user-images.githubusercontent.com/23466737/35267532-840f78e6-001e-11e8-96c1-513f6c11d2fe.gif)

**Actual Result:**
 When there is one "serial write line", the string only write once
![12](https://user-images.githubusercontent.com/23466737/35267539-8c1fec28-001e-11e8-95ef-683e2738af06.gif)

**Comment by cait1inhennessy** [comment]
This is by design - in order to avoid flooding the text area, we collapse duplicate messages and prefix them with a counter.
