### ISSUE TITLE
The scroll bar in the comment can not be dragged to the top

### ISSUE THREAD

**Issue by shunzhan** [Microsoft/pxt#3757]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta on Edge and Chrome
• Drag a block and right-click mouse
• Add long comment in the block
• Drag the scroll bar up
**Expected result:**
The scrollbar in the comment can be dragged to the top
**Actual result:** (Edge Chrome)
The scroll bar will return to the bottom when user drags it to the top
![comment](https://user-images.githubusercontent.com/34087467/35270801-15a00d44-0028-11e8-80e7-97ea5c7f6fb4.gif)

**Comment by samelhusseini** [comment]
Closing in favour of https://github.com/Microsoft/pxt/issues/3974
