### ISSUE TITLE
JavaScript-to-Blocks conversion renames index in for loops using the same index name.

### ISSUE THREAD

**Issue by jpiay** [Microsoft/pxt#3758]
JavaScript-to-Blocks conversion renames index in for loops using the same index name.

**Comment by abchatra** [comment]
Please share the program

**Comment by jpiay** [comment]
Hi, I'm sending attached a video showing the issue. Hope it helps.
[microbit_for_index_issue.zip](https://github.com/Microsoft/pxt/files/1659191/microbit_for_index_issue.zip)
