### ISSUE TITLE
Feedback on maker.makecode.com

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt#3762]
1. The breadboard blends in with the background. I think it's more clear when there's a distinction:
![image](https://user-images.githubusercontent.com/6453828/35349459-d4110464-00ef-11e8-9d2f-7ea796b08257.png)
vs.
![image](https://user-images.githubusercontent.com/6453828/35349535-092f2ad6-00f0-11e8-9d59-3951f815425b.png)

2. The +/- "zoom" buttons in the bottom right only zoom the blocks. I would have expected them to at least zoom the simulator. The breadboard especially is helpful to zoom since there's a lot of detail there (whereas with the microbit simulator, the detail isn't as small.)

**Comment by abchatra** [comment]
@darzu Please open the bug in Maker repo. Thanks.

**Comment by abchatra** [comment]
https://github.com/Microsoft/pxt-maker/issues/5

**Comment by darzu** [comment]
Thanks!!
