### ISSUE TITLE
problem on Mac OS X after update

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#3774]
https://twitter.com/mobluse/status/957309828053028866

@MSMakeCode https://makecode.microbit.org  shows only a black screen with moving white logo forever in #Safari in Mac OS X El Capitan (both most updated today) & never starts. Do I need to upgrade to macOS High Sierra for #MakeCode to work? #microbit BBC micro:bit

**Comment by samelhusseini** [comment]
We only support Safari 9 and above. It's likely they were running an older version of Safari.
