### ISSUE TITLE
There is an error of "Control->reset" example

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#3781]
**Repro step:**
• Navigate to https://makecode.microbit.org/beta
• Click Advanced->Control->reset, go to Help of "reset"
• Copy the example code for reset, such as follows:
***********************************************************************
```typescript
let item = 0;
basic.showNumber(item);
input.onButtonPressed(Button.A, () => {
    item = item + 1;
    basic.showNumber(item);
});
input.onButtonPressed(Button.B, () => {
    control.reset();
});
```
************************************************************
**Expected Result:**
 When clicked the B button, the variable 'item' will be reset.
**Actual Result:**
When clicked the B button, there is an error.
![reset](https://user-images.githubusercontent.com/23497626/35558105-0ff8c6c0-059f-11e8-987f-d2a8d9518d72.PNG)

**Comment by pelikhan** [comment]
Please 3 back tick to fence your code snippets in bug reports.

**Comment by ganicke** [comment]
Add simulator note to topic....https://github.com/Microsoft/pxt-microbit/pull/616
