### ISSUE TITLE
Every gray block has the same document Help

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#3782]
**Repro step:**
• Navigate to https://makecode.microbit.org/beta
• Copy the follow code to {}JavaScript:
• Switch to Blocks, go to Help of "basic.ShowNumber()"
*****************************************************
input.onButtonPressed(Button.A, () => {
    num += 1
})
let num = 0
control.inBackground(() => {
    while (true) {
        basic.showNumber(num, 150)
basic.pause(100)
    }
})
******************************************************
**Expected Result:**
 There is a document about how to use "basic.ShowNumber()"
**Actual Result:**
Every gray block has the same document, and there is no document about how to use this block
![show](https://user-images.githubusercontent.com/23497626/35558866-0de65d46-05a1-11e8-9cd1-8862c82e51ae.PNG)

**Comment by samelhusseini** [comment]
By design.
