### ISSUE TITLE
Block "john" example error

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3783]
**Repro step:**
• Navigate to https://makecode.microbit.org/beta
• Click "Advanced" -> "Text" -> "join" and then right click to look its help document 
• Copy the follow example to javascript panel
![1](https://user-images.githubusercontent.com/23466737/35559663-2864ea00-05a3-11e8-90ad-21ac08f8f615.gif)
**Except result:**
This example should have two different parameter names
**Actual result:**
This example shows error that two parameters have the same name
![capture1](https://user-images.githubusercontent.com/23466737/35559748-612b1c7e-05a3-11e8-9c97-b60791887ba9.PNG)

**Comment by ganicke** [comment]
Fixed in https://github.com/Microsoft/pxt/pull/3791.
