### ISSUE TITLE
simulator does not restart after neopixel error

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3798]
If you create a neopixel, stored in a variable with a custom name, and then drag out a neopixel block, this will crash the simulator. This is because those blocks have the default variable name selected. That's understandable so far. But if you then change the neopixelblock to use the right variable name, it does not restart the simulator, it stays in crashed mode. That's confusing, because at that point the code is correct.

![microbit_neopixel_bug](https://user-images.githubusercontent.com/5718354/35630355-808986ec-06a1-11e8-885b-71d3646a8561.gif)

**Comment by nielsswinkels** [comment]
Any updates about this? I'm writing a guide on this at the moment, and right now I'm considering using the default variable name to not run into this error. But I think giving it a proper variable name is a much better style.

**Comment by abchatra** [comment]
This is fixed in alpha

**Comment by abchatra** [comment]
This is not fixed.
