### ISSUE TITLE
clear ref-counted locals vars when out of scope

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#38]
For example:

```
if (...) {
  let x = "a" + "b"
  ...
  // implict 'x = null' here
}
```

This can free significant amount of memory, especially if 'x' happen to be outside of any function.

**Comment by abchatra** [comment]
@mmoskal  is this still valid?

**Comment by mmoskal** [comment]
Yes. It requires some live variable analysis. We could also re-use global and local variable slots. It's not critical but certainly in the nice-to-have category.
