### ISSUE TITLE
for element of value tooltip missing

### ISSUE THREAD

**Issue by machinehistories** [Microsoft/pxt#3807]
This node doesn't have the floating tooltip in makecode for microbit.
![for](https://user-images.githubusercontent.com/26831444/35772515-3ea9702e-08f5-11e8-8f38-55ba791751cf.PNG)

**Comment by samelhusseini** [comment]
We don't show a tooltip if the block is disabled. Try attaching it to an event (eg: on start or forever) and you should see a tooltip.
