### ISSUE TITLE
comments - panel tool option

### ISSUE THREAD

**Issue by machinehistories** [Microsoft/pxt#3809]
The current comment capability is helpful but it is limiting. It would be really helpful to have a generic panel tool that can be placed onto the canvas like a note pad sticky. I know this image is from a different program (grasshopper3d) but their panel tool really helps so you can add in notes to remember what is happening in the script and to insert in some psuedocode. I really feel this would greatly improve learning and sharing since when opening another users hex file you could quickly see and read their notes and better understand their work.
![panelproblem](https://user-images.githubusercontent.com/26831444/35774571-6dbef324-0928-11e8-965f-da8fd09792cc.jpg)

**Comment by abchatra** [comment]
We have new comment already checked into master based on sticky notes. This will be addressed for microbit after fall update
