### ISSUE TITLE
Windows 10 MakeCode BETA - not canceling download

### ISSUE THREAD

**Issue by Lorrainbow** [Microsoft/pxt#3813]
This is using the Windows 10 MakeCode BETA app 

1. Create a project
2. Do not give it a name,, leave it as untitled
3. Select the save icon next to the project name
4. In the window "Rename your project" select Cancel 

Result: The Rename your project window closes as expected. 
BUG: The Save As window appears
Expected result: I expect when I press Cancel that saving the project will cancel.

**Comment by pelikhan** [comment]
@Lorrainbow please open micro:bit related bugs in https://github.com/Microsoft/pxt-microbit . Thanks for reporting this issue!

**Comment by microbit-mark** [comment]
This has been reported on pxt-microbit so can be closed on pxt https://github.com/Microsoft/pxt-microbit/issues/625

**Comment by samelhusseini** [comment]
Closing
