### ISSUE TITLE
Simulator hide transition exception (caused by upgrade of pxt-core to jquery 3.0?).

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#3821]
The exception is below. To trigger hide the simulator.

_main.js:12033 Uncaught TypeError: $(...).transition(...).error is not a function
    at Object.removeElement (main.js:12033)
    at SimulatorDriver.hide (pxtsim.js:4588)_
    ...

I believe the issue is that this function was removed in jquery 3.0.

In `removeElement` in /webapp/src/simulator.ts the error handler should be changed from

```javascript
}).error(() => {
```

to

```javascript
}).on('error', () => {
```

Description of this change is on jquery.com [here](https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed).

**Comment by pelikhan** [comment]
Thanks for reporting!

________________________________

**Comment by matthewtebbs** [comment]
Nice! Thanks for the quick fix. I verified with pxt-core@3.2.9.
