### ISSUE TITLE
"Neopixel" has different displays in different browsers.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3827]
**Repro Step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- Add package "_Neopixel_" and switch to "_{}JavaScript_"
- copy the following code into content panel:
_let item: neopixel.Strip = null
item = neopixel.create(DigitalPin.P0, 24, NeoPixelMode.RGB)
item.showColor(neopixel.colors(NeoPixelColors.Red))_
- Switch back to "_Blocks_"

**Actual result:**
_Safari:_
![safari](https://user-images.githubusercontent.com/17866936/35850449-c60424be-0b1c-11e8-9801-aebdc218578c.gif)

_Edge_:
![edge](https://user-images.githubusercontent.com/17866936/35850680-8cc50d98-0b1d-11e8-9799-0ff976e57730.gif)

_Chrome_:
![chrome](https://user-images.githubusercontent.com/17866936/35850471-dc9a3bc8-0b1c-11e8-9430-7b9e4712dd89.gif)

_Firefox_:
![firefox](https://user-images.githubusercontent.com/17866936/35850482-ed83d390-0b1c-11e8-9c99-8fa8895117ac.gif)

**Comment by samelhusseini** [comment]
Transferring to pxt-microbit: https://github.com/Microsoft/pxt-microbit/issues/738
