### ISSUE TITLE
Extended choice of languages

### ISSUE THREAD

**Issue by marekmansell** [Microsoft/pxt#3829]
Hi everyone!

A week ago I opened an Issue on the microbit pxt branch [#617](https://github.com/Microsoft/pxt-microbit/issues/617). As no one from the developers have replied, I suppose this might be a better place to discuss the issue (besides the fact this repo is more active, It seems that the core functionality, which also includes language changes, is developed here)

**Ideas from the original Issue comments:**
The microbit blockly strings have been translated on crowdin to many other languages besides the 12 ones which are displayed in the top right menu of the app (https://makecode.microbit.org/). Is there a friendlier way of opting for one of these other languages besides the process of changing your browser's page language settings, deleting your cookies and refreshing the site? If not, this is a feature many would appreciate.

Possible ways to implement this:

1. https://makecode.microbit.org/sk for the Slovak language (easy to remember, clean URL)
2. https://makecode.microbit.org/?lang=sk_SK (including language code in the query string) -- advantage: could be appended to any URL, so it would be useful for forcing a specific language for embeds etc.

If you come up with something even better, please leave a comment.

**Comment by nielsswinkels** [comment]
They write on that repo in the readme:
"All issue tracking for this repo happens at https://github.com/Microsoft/pxt, see you there!"

But it seems you still got your answer there already.

**Comment by samelhusseini** [comment]
Closing in favour of #617.
