### ISSUE TITLE
Auto-generation of library files for new target with no sims.d.ts doesn't happen.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#3830]
It may be by design but if the _corepkg_ does not contain a _sims.d.ts_ then it will not be auto-generated due to this code in _./cli/cli.ts_.

```javascript
let fn = "libs/" + s + "/" + filename
if (fs.readFileSync(fn, "utf8") != cont) { // <- exception thrown here
    pxt.debug(`updating ${fn}`)
    fs.writeFileSync(fn, cont)
}
```

_Error: ENOENT: no such file or directory, open 'libs/core/sims.d.ts'
    at Object.fs.openSync (fs.js:646:18)_

It's not immediately obvious what's going on. Well at least to me it wasn't :)

It would be useful to capture the NOENT exception and fall through to the same path of writing out a 'fresh' _sims.d.ts_ for those new to PXT and bootstrapping up a new target.

**Comment by samelhusseini** [comment]
@pelikhan error message, docs, or always generate?

**Comment by matthewtebbs** [comment]
Seems to me you'd want to always generate OR not fail silently. No-one reads the docs :)

My personal preference would be to either create (new case), or update (existing case), if you have declarations to write out.
