### ISSUE TITLE
serial monitor and serial show data combined

### ISSUE THREAD

**Issue by machinehistories** [Microsoft/pxt#3845]
I would like to request that the serial workflow in the app is twofold. While I really like the option of clicking the show data button and getting a visual of the data I also like the immediacy of seeing the terminal window displayed on the main page such as in previous versions.

![35772449-c3eecbbe-08f3-11e8-9f3f-cae49ba6a500](https://user-images.githubusercontent.com/26831444/36013361-9166a6fc-0d18-11e8-8f78-5341ee471ec1.PNG)

Perhaps on the main page you can have the small terminal along with an additional show simulator button placed alongside it if in fact you needed to visualize the data. My main objection to the current interface which only has the show data is it simply lacks the immediacy of having the terminal on display at all times as in previous versions.

**Comment by cait1inhennessy** [comment]
This is a good idea, adding it to the serial improvements list.

**Comment by machinehistories** [comment]
Just checking in on this. I am using a version from october that still has the terminal frame on the main page because I need to see the incoming serial message and (I know I am being nit picky) it is inconvenient to jump to the show data page.

**Comment by abchatra** [comment]
Enhancements are captured here: https://github.com/Microsoft/pxt/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement
