### ISSUE TITLE
stream to cloud on windows app

### ISSUE THREAD

**Issue by machinehistories** [Microsoft/pxt#3846]
Is there was a way for you all to reinstate the stream to cloud function in the windows app. While I know there were issues using it with the chrome extension, running it in the windows app should be able to work without the need for the extension. With the addition of the maker boards in beta I really think it is essential to have some mechanism for easily incorporating some sort of IOT streaming, data logging, type workflow since it is so essential. Maybe some sort of generic API KEY and AUTH TOKEN block would be great. It can be used to access various tools such as evostudio or adafruit.io or other such cloud related tools.

**Comment by abchatra** [comment]
We don't have a plan for this in near future.
