### ISSUE TITLE
documentation menu is not responsive

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#385]
should transform into hamburger menu on mobile devices

**Comment by abchatra** [comment]
@pelikhan Can you elaborate this issue? I can't see the documentation menu on my iphone.

**Comment by pelikhan** [comment]
Try PXT.microbit.org/about

**Comment by abchatra** [comment]
I meant I can't see the documentation issue on my iPhone.

**Comment by pelikhan** [comment]
Try the https://pxt.microbit.org/about page. You will see that the menu bleeds out the page.
![image](https://cloud.githubusercontent.com/assets/4175913/19712039/56c03848-9aef-11e6-8c28-15083dc1d716.png)
