### ISSUE TITLE
Block "Map" example issue

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3864]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Navigate to "Advanced" -> "Pins" -> right click block "map from low ..." and click help
• Copy this block example code to "JavaScript" pane

**Except results:**
When changing map value, the location of plot light also has a change
![2](https://user-images.githubusercontent.com/23466737/36129948-b5c3b50e-101e-11e8-8885-894c80e8ed8e.gif)

**Actual results:**
When changing "P0" value, the location of plot light doesn't have any change
![1](https://user-images.githubusercontent.com/23466737/36129951-bb55feaa-101e-11e8-8e4b-53577430d897.gif)

**Comment by pelikhan** [comment]
On start runs only once.

________________________________

**Comment by pelikhan** [comment]
Use forever instead of on-start
