### ISSUE TITLE
Block 'Map' issue

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3865]
**Repro steps:**
• Navigating to https://makecode.microbit.org/beta
• Drag blocks as below .gif
• Change value of map few times and observe simulator

**Except results:**
There should have a correct standard for 'from low' and 'from high', 

**Actual results:**
For example: when map is 0-255, plot (0,0)
                      when map is 256-511, plot (0,1)
                      when map is 512-767, plot (0,2)
                      when map is 768-1022, plot (0,3)
                      when map is 1023, plot (0,4)  
So only when 'map' number is 1023, plot (0,4)
![3](https://user-images.githubusercontent.com/23466737/36135075-8b1b061c-103d-11e8-9730-8a34d10bb192.gif)

**Comment by samelhusseini** [comment]
No floating points, I'd imagine it's a rounding error.
