### ISSUE TITLE
investigate downcast type safety

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#387]
Following scenarios need investigating:
- [ ] explicit downcast as in `foo as Derived` (or `<Derived>foo`)
- [ ] implicit downcast due to bivariant function types: [TS FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)
- [ ] covariant arrays
- [ ] indexing types without explicit indexer

I think we could introduce some runtime checks for the above - upon explicit casting, entry into a lambda function, and upon assigning to arrays.

We cannot really support union types (there is currently no way to distinguish at runtime between a number and a reference for example). Intersection types are I think only compile-time feature.

**Comment by mmoskal** [comment]
CC @tballmsft

**Comment by tballmsft** [comment]
forget about union/intersection types, say I.

**Comment by tballmsft** [comment]
New type checker disallows downcasts, bivariance. Closing for now
