### ISSUE TITLE
There is no closing pop-window button

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3874]
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta
• There is a pop-window on the page

**Except result:**
There should have 'Agree' and 'Not agree' button on the pop-window
**Actual result:**
There is no 'Agree' and 'Not agree' button on the pop window, so user don't know how to close it
![ud](https://user-images.githubusercontent.com/23466737/36186184-2acd1c5e-10f2-11e8-9e20-e474f07dc283.png)

**Comment by pelikhan** [comment]
This is the standard behavior for cookie pop up on Microsoft sites.

________________________________

**Comment by abchatra** [comment]
This is as per Microsoft policy
