### ISSUE TITLE
allow skipping blockId

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#388]
We could auto-generate this from API name. I understand things will break if the API name changes, but (a) the JS code will also break in that case (so it's best avoided), and (b) if someone renames an API they could add a blockId= explicitly with what was auto-generated before.

**Comment by abchatra** [comment]
This is the request for auto generation of block id in here
```js
    function injectBlockDefinition(info: pxtc.BlocksInfo, fn: pxtc.SymbolInfo, attrNames: Map<BlockParameter>, blockXml: HTMLElement): boolean {
        let id = fn.attributes.blockId;
```

**Comment by pelikhan** [comment]
Enforcing a blockId provides a nice app compat feature: in case of a TypeScript name, the blockId stays the name. IMO, not worth fixing.

**Comment by abchatra** [comment]
Closing as this is not worth fixing.
