### ISSUE TITLE
monaco zooming confused when using keyboard bindings

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#3896]
Trying zooming with crtl+wheel, then use the buttons, mayhem.

**Comment by samelhusseini** [comment]
Theres already a bug filed on this, it is 2 years old. Monaco issue limiting us to do anything about it besides disable keyboard zoom

**Comment by pelikhan** [comment]
One of the keyboard binding triggers this too and I find myself having to refresh the browser. It’s really broken.
