### ISSUE TITLE
"Powered by Microsoft" image/watermark

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#390]
- [x] watermark in embedded editor (sandbox)
- [ ] watermark in screenshots 
- [x] with link back to codethemicrobit.com

**Comment by microsoftsam** [comment]
what should the watermark look like in a screenshot?
Powered by Microsoft? or just Microsoft?
overlayed or its own section underneath

**Comment by pelikhan** [comment]
Let's start by overlaying the organization image + product image on each lower corners. Similarly to our YouTube vids for BBC

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microsoftsam** [comment]
We're going to drop the branding in the screenshot for now, as it might be a bit over the top at this point. Most content creators wanting to add screenshots on their site would already be linking to our site in some way.
