### ISSUE TITLE
yellow selection not correct around string block

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#3925]
When I have a block where I set a variable to a text string, and select the red variable block, the yellow selection only goes around that one, and not around the string block, even though that also is selected and gets copied.

![image](https://user-images.githubusercontent.com/5718354/36751038-4e92854e-1bff-11e8-90ee-06bb01c5e75b.png)

**Comment by samelhusseini** [comment]
Yeah this is standard Blockly selection behaviour. What get's copied is the entire stack, selection is not meant to indicate the stack but the currently selected block (at least this is the design in Blockly). 
I'll keep this in mind for any future discussions around this feature. Thanks
