### ISSUE TITLE
The help document covers the block selection menu on "{ } JavaScript" mode

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3948]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• On "Blocks" page and open project document on the right-page and blcok selection menu together
• Click "JavaScript" and then switch to "{ } JavaScript" page
• Open project document on the right-page and blcok selection menu together again

**Expect result:**
 Only open/close help document button floating on the block selection menu
![2](https://user-images.githubusercontent.com/23466737/37010843-60727ffe-20e5-11e8-99dd-7575153d6694.gif)

**Actual result:**
After switching to "{ } JavaScript" page, the help document covers the block selection menu
![compare](https://user-images.githubusercontent.com/23466737/37010849-6827d212-20e5-11e8-8eac-a64cc5125c32.png)

**Comment by samelhusseini** [comment]
z-index issue. maybe we should move the zindex (global file architecture) to v0.

**Comment by Helen09** [comment]
I have moved this issue to https://github.com/Microsoft/pxt-microbit/issues
