### ISSUE TITLE
implement pxsim.control.eventValue and pxsim.control.eventTimestamp in the simulator

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#395]
Currently the simulator build complains about it, and we have blocks using this.

**Comment by microsoftsam** [comment]
Reverted the change.

**Comment by caitlin-hennessy** [comment]
Resolved by https://github.com/Microsoft/pxt/pull/2615 and https://github.com/Microsoft/pxt-microbit/pull/484.
