### ISSUE TITLE
Why I wrote C++ project, microbit can't download?

### ISSUE THREAD

**Issue by hnwangkg-ezio** [Microsoft/pxt#3972]
I am an engineer from China, and now I have some technical questions that I hope can be solved.
Under my ubuntu and established PXT, and I can upload. Ts, and in the micro: bit add  package can be used, and now I want to transplant LCD to micro: bit, I use c + = written, and in the check there are no mistakes,
Here's what I did:
Create a file: LCD1in8, then PXT init, create a PXT project, execute PXT add CPP.
Then I transferred my c++ project, added the corresponding file under pxt.json, uploaded it to github, and finally couldn't download it. I found the following error in the execution of make in the project:
PXT deploy
Using target PXT/microbit with build engine yotta.
Target dir: / home/ezio/microbit/node_modules/PXT - microbit
PXT Core dir: / home/ezio/microbit/node_modules/PXT - Core
INTERNAL ERROR: SyntaxError: Unexpected token:
At the Object. The parse (native)
The at MainPackage. Package. ParseConfig (/ home/ezio/microbit/node_modules/PXT - core/built/PXT. Js: 55938:28)
The at/home/ezio/microbit/node_modules/PXT - core/built/PXT. Js: 55968-75
The at tryCatcher (/ home/ezio/microbit/node_modules/bluebird/js/release/util. Js: shew forth)
The at Promise. _settlePromiseFromHandler (/ home/ezio/microbit/node_modules/bluebird/js/release/Promise. Js: 512:31)
The at Promise. _settlePromise (/ home/ezio/microbit/node_modules/bluebird/js/release/Promise. Js: 569:18)
The at Promise. _settlePromiseCtx (/ home/ezio/microbit/node_modules/bluebird/js/release/Promise. Js: 606:10)
At Async. _drainQueue (/ home/ezio/microbit/node_modules/bluebird/js/release/Async. Js: 138:12)
At Async. _drainQueues (/ home/ezio/microbit/node_modules/bluebird/js/release/Async. Js: 143:10)
At the Immediate. Async. DrainQueues [as _onImmediate] (/ home/ezio/microbit/node_modules/bluebird/js/release/Async. Js: immediately)
The at processImmediate [as _immediateCallback] (timers. Js: 383:17)
The Makefile:7: recipe for target 'deploy' failed.
[deploy] Error 20.
I made a comparison and found a project that could be used by micro: bit.
PXT deploy
Using target PXT/microbit with build engine yotta.
Target dir: / home/ezio/microbit/node_modules/PXT - microbit
PXT Core dir: / home/ezio/microbit/node_modules/PXT - Core
Package built;Written to binary. Hex;Size: 581384
Cannot find any drives to deploy to.

**Comment by pelikhan** [comment]
Looks like PXT.json has a syntax error. If you use Visual Studio Code, the editor will flag the error.

________________________________

**Comment by hnwangkg-ezio** [comment]
Thanks, according to your prompts, I have eliminated this error, but there have been new mistakes. Will there be similar C++ to JavaScript tutorials and the like, I read the https://makecode.com/simshim document here, but it does not give me much inspiration

**Comment by hnwangkg-ezio** [comment]
I found a new problem, even if I create a new project, execute pxt add cpp, then execute make, there are errors：
ezio@ubuntu:~/microbit/projects$ mkdir test
ezio@ubuntu:~/microbit/projects$ cd test
ezio@ubuntu:~/microbit/projects/test$ pxt init
Using target PXT/microbit with build engine yotta
  Target dir:   /home/ezio/microbit/node_modules/pxt-microbit
  PXT Core dir: /home/ezio/microbit/node_modules/pxt-core
name [test]: test
description []: tset
license [MIT]: MIT
skipping download of local pkg: file:.
Package initialized.
Try 'pxt add' to add optional features.
ezio@ubuntu:~/microbit/projects/test$ pxt add cpp
Using target PXT/microbit with build engine yotta
  Target dir:   /home/ezio/microbit/node_modules/pxt-microbit
  PXT Core dir: /home/ezio/microbit/node_modules/pxt-core
Added extension.cpp to files in pxt.json.
Wrote extension.cpp.
Added extension.ts to files in pxt.json.
Wrote extension.ts.
Added shims.d.ts to files in pxt.json.
Wrote shims.d.ts.
Added enums.d.ts to files in pxt.json.
Wrote enums.d.ts.
ezio@ubuntu:~/microbit/projects/test$ make
pxt deploy
Using target PXT/microbit with build engine yotta
  Target dir:   /home/ezio/microbit/node_modules/pxt-microbit
  PXT Core dir: /home/ezio/microbit/node_modules/pxt-core
*** yotta target bbc-microbit-classic-gcc
INTERNAL ERROR: Error: spawn yotta ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Makefile:7: recipe for target 'deploy' failed
make: *** [deploy] Error 20

**Comment by pelikhan** [comment]
You will need to install the yotta toolchain.

________________________________

**Comment by hnwangkg-ezio** [comment]
Hello, is there any problem with the macro definition like mine?Because I found that when I replaced the back with space, I uploaded it to github and downloaded the Windows explorer, but I couldn't download any program to my micro: bit.：
#define LCD_CS   &uBit.io.P16
#define LCD_RST  &uBit.io.P7
#define LCD_DC   &uBit.io.P6

#define SET_PIN_1(pin_name) \
  MicroBitPin *pin = pin_name; \
  pin->1

#define SET_PIN_0(pin_name) \
  MicroBitPin *pin = pin_name; \
  pin->0
  
//LCD
#define LCD_CS_0		SET_PIN_0(LCD_CS)
#define LCD_CS_1		SET_PIN_1(LCD_CS)

#define LCD_RST_0		SET_PIN_0(LCD_RST)
#define LCD_RST_1		SET_PIN_1(LCD_RST)

#define LCD_DC_0		SET_PIN_0(LCD_DC)
#define LCD_DC_1		SET_PIN_1(LCD_DC)

**Comment by hnwangkg-ezio** [comment]
thanks,i got it
