### ISSUE TITLE
There lacks a  scroll bar to open the bottom projects

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3973]
**Repro Steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Projects" -> "Projects" ->"Flashing Heart" -> Click "7" to go to the seventh step -> "Finish" -> "More Tutorials"
• Observe this page

**Expect result:**
There should have a scroll bar so user can open any project
**Actual result:**
There lacks a  scroll bar to open the bottom projects
![12](https://user-images.githubusercontent.com/23466737/37320218-8d2bf7d4-266a-11e8-9427-0576b32fe518.gif)

**Comment by Helen09** [comment]
I have moved this issue to https://github.com/Microsoft/pxt-microbit/issues

**Comment by abchatra** [comment]
Moved
