### ISSUE TITLE
Comment can't be selected on Edge&Chrome&Safari

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3974]
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Drag block "show number" and right-click to add some commet
• Try to select part of comment and then to delete it

**Expect result(Firefox):**
Comment should be selected 
![15](https://user-images.githubusercontent.com/23466737/37325291-333e73da-2685-11e8-87a9-cf4b47f9d060.gif)

**Actual result(Chrome&Edge):**
Comment can't be selected 
![16](https://user-images.githubusercontent.com/23466737/37325283-2b586ff4-2685-11e8-9978-92c1d92204fb.gif)

**Comment by samelhusseini** [comment]
Fixed by new comments. Will follow up soon.

**Comment by abchatra** [comment]
This fixed in alpha
