### ISSUE TITLE
There is no package "microturtle" on Docs > Packages

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3975]
**Repro steps:**
• Navigate to https://makecode.microbit.org/packages to look all packages

**Except result:**
There should show all packages

**Actual result:**
There is no package "microturtle"
![18](https://user-images.githubusercontent.com/23466737/37330016-9eeab078-2697-11e8-8e4b-a325ef7dff9e.gif)

**Comment by samelhusseini** [comment]
@pelikhan how do we decide what shows on that page? is it a manual step?

**Comment by Helen09** [comment]
Closed as fixed
