### ISSUE TITLE
Menu Bar Glitches when scrolling

### ISSUE THREAD

**Issue by irrationalRock** [Microsoft/pxt#3976]
Hi, I don't know if this is the right place to discuss this but when scrolling down on https://makecode.com/ it glitches the menu bar.

Example:
![broken website](https://user-images.githubusercontent.com/16523071/37415378-accee660-2781-11e8-9595-97dd0cff93a2.gif)

Chrome Version: 65.0.3325.162 
OS: Windows 10

**Comment by samelhusseini** [comment]
Closing as this no longer appears to be happening.
