### ISSUE TITLE
Block outputs do not support connecting to block inputs that take a base type of that output type.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#3981]
While Blockly supports providing an array of connection types, the PXT Blockly loader only ever provides a single return type (from SymbolInfo::retType) when initializing block output options. There is inheritance type information captured (from SymbolInfo::extendsTypes) but this information is not used to configure the allowable connection types to the block outputs. That's too bad as the Static TypeScript Monaco editor understands type inheritance. 

An example use case is a system to support authoring a 3D environment in MakeCode using PXT. These environments tend to provide objects such as lights, cameras, meshes, where there is a base 3d object type that all these types inherit from and which provides 3d space information.

**Comment by abchatra** [comment]
Fixed by the change.
