### ISSUE TITLE
Regression in getBlocksInfo() w.r.t. handling of qualified names with no block nor block id.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#3988]
The function

`export function getBlocksInfo(info: ApisInfo): BlocksInfo {...}`

changed substantially between 3.5.4 and 3.5.7 of pxt-core. I believe the change was to support the `%blockCombine` attribute.

I'm finding name information for symbols of kind 'Module' are now no longer being pruned out.

The old code filtered out qualified names which did not have an associated block and blockId is below.

```javascript
const blocks = pxtc.Util.values(info.byQName).
    filter(s => !!s.attributes.block && !!s.attributes.blockId &&
    (s.kind != pxtc.SymbolKind.EnumMember));
```

The effect I'm seeing is that the filtered block information derived from the compiler's qualified name set includes items that are not blocks with categories and therefore fail later on when creating the Blockly toolbox, specifically those of symbol kind 'Module'.

These I believe are compiled from the following kind of declaration in my 'lib/core'.

```typescript
//% color=0 icon="\uf1fc" block="Design" weight=100
declare namespace design { /* paint-brush icon */
}
```

It's unfortunate as the end result is no toolbox shown although of course the loaded project runs just fine.

**Comment by matthewtebbs** [comment]
FWIW I added a check to filter out modules as well as enums.

**Comment by matthewtebbs** [comment]
} else if (!!s.attributes.block
                && !s.attributes.fixedInstance
                && s.kind != pxtc.SymbolKind.EnumMember
                && s.kind != pxtc.SymbolKind.Module) {
                if (!s.attributes.blockId)
                    s.attributes.blockId = s.qName.replace(/\./g, "_")

**Comment by pelikhan** [comment]
Also impacts editor in non-english moe.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/3989

**Comment by samelhusseini** [comment]
I believe this is fixed. Closing.

**Comment by matthewtebbs** [comment]
FWIW worked for me.
