### ISSUE TITLE
After right-clicking on block, there shows "Create 'get index'" 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3990]
**Repro Steps:**
• Navigate to https://makecode.microbit.org/beta
• Navigate to "Loops" -> right click on blcok "for index from 0 to 4"

**Expect result:**
There should only show help
![1](https://user-images.githubusercontent.com/23466737/37691680-73dba33c-2cab-11e8-8ff3-444876deedd2.png)

**Actual result:**
After right-clicking on this block, there also shows "Create 'get index'" 
![1](https://user-images.githubusercontent.com/23466737/37691645-3dda5422-2cab-11e8-9dcc-5f5154a8af2b.gif)

**Comment by samelhusseini** [comment]
Blockly feature. by design.

**Comment by samelhusseini** [comment]
Filed a Blockly bug, and fix in PR.

**Comment by Helen09** [comment]
Closed as fix in PR
