### ISSUE TITLE
support direct binding to C++ class methods

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#40]
They have different calling convention.

**Comment by abchatra** [comment]
@mmoskal is this still valid?

**Comment by mmoskal** [comment]
Yes. This for something along the lines of:

```
class Foo {
public:
  //% ...
  void bar() { ... }
}
```

**Comment by tballmsft** [comment]
@mmoskal - still valid?

**Comment by mmoskal** [comment]
I think we won't be able to do it, at least for classes with virtual methods, as we need to force a specific binary header. Closing.
