### ISSUE TITLE
Move to TypeScript 2.8.1 (nice to have)

### ISSUE THREAD

**Issue by matthewtebbs** [microsoft/pxt#4012]
Nice to have as the new support for granular control on mapped type modifiers in the standard libs is not compatible with the pxt-core's current typescript version of 2.6.1, i.e. the compiler fails on the 2.8 lib syntax for this.

Potential breaking changes with this move are:-

- 2.7 -> 2.8 **Unused type parameters are checked under --noUnusedParameters**
Unused type parameters were previously reported under –noUnusedLocals, but are now instead reported under --noUnusedParameters. You can read more on issue #20568

- 2.7 -> 2.8 **HTMLObjectElement no longer has an alt attribute**
Such behavior is not covered by the WHATWG standard. You can read more on issue #21386

- 2.6 -> 2.7 **Fixed Length Tuples**
Tuples of different arities are no longer assignable to each other.

**Comment by abchatra** [comment]
Fixed
