### ISSUE TITLE
Default theme hardcodes need for 'Powered-by-Microsoft-logo[-small].png' files.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4016]
It'd be nice to have this style conditionally included based on the existence of the logo file and/or a variable that a client could define say '@beta' or '@external' or '@thirdparty' or some such.

As an example, the **pxt-sample** project will output the following. Any client of pxt-core that doesn't have the Microsoft logo images in their _/docs/static/logo_ folder will.

```
Skipped data-uri embedding of ../docs/static/logo/Powered-By-Microsoft-logo-small.png because file not found
Skipped data-uri embedding of ../docs/static/logo/Powered-By-Microsoft-logo.png because file not found
... repeated many times ...
```

**Comment by samelhusseini** [comment]
Fixed by https://github.com/Microsoft/pxt/commit/65b83939241a07b3a836a355e9dd61033b9cfc28
