### ISSUE TITLE
Loading from hex files is not working

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#402]
Dragging and dropping a hex file seems to be broken right now. When a file is dropped in the window the UI freezes for a while and eventually an error appears in the console saying that Blockly received an invalid XML tree.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/3f9dbf7b0b6e5bf3a68d067435d61d7f9c853f3f#commitcomment-19236157

**Comment by pelikhan** [comment]
Fixed by https://github.com/Microsoft/pxt/commit/ec298470e4f89da5fdcf9fb637d61192179ec815
