### ISSUE TITLE
Cookie banner hides MakeCode logo on Safari

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#4020]
The cookie banner hides the Microsoft MakeCode title on makecode.com

<img width="1324" alt="screen shot 2018-03-27 at 11 53 05 pm" src="https://user-images.githubusercontent.com/16690124/38013474-14d91af8-321a-11e8-81fd-b001f8d795d4.png">

**Comment by samelhusseini** [comment]
On other browsers the banner just hides when you scroll (ie: it is not fixed positioned). Is that okay @riknoll?

**Comment by riknoll** [comment]
This is also a bug in IE, the scrolling behavior is expected. Other MSFT sites do the same thing.

**Comment by riknoll** [comment]
See https://www.xbox.com/fr-fr

**Comment by samelhusseini** [comment]
Okay cool.
