### ISSUE TITLE
Toolbox categories sorted differently between Blockly and Monaco views

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4022]
Two repro' cases here.

1) To see this look at the [Adafruit editor](https://makecode.adafruit.com/#editor). The Advanced categories 'Arrays' and 'Text' flip order between Blockly and Moaco editing views.

2) In my target's case I've noticed that if you don't assign a weight to your category it will be sorted differently between the two editing views, specifically a non-weighted category, will weight after built-ins in the Advanced group in the Blockly toolbox view, and before them in the Advanced group in the Monaco view.

Two fixes here. I have a PR that I'll attach.

1) Advanced categories are not assigned weights in the Monaco category view code; unlike their non-advanced counterparts.
Fix: to assign them weights in the snippet.

2) During insertion of the Blockly category an equal weighting will force insertion after an existing category, e.g. lower, in the list while in the Monaco category sort it will cause the new category order to be left as is.
Fix: to explicitly sort equal weightings after in the list as per the Blockly category insertion sort.

Tested with the Adafruit target and my own.

**Comment by matthewtebbs** [comment]
[PR 4023](https://github.com/Microsoft/pxt/pull/4023)

**Comment by samelhusseini** [comment]
Fixed. Thanks @matthewtebbs
