### ISSUE TITLE
How should I install yotta

### ISSUE THREAD

**Issue by hnwangkg-ezio** [Microsoft/pxt#4026]
How should I install yotta?
I encountered the following problems during installation:
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-w2BjnN/semantic-version/setup.py';f=getattr(tokenize, 'open', open )(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install - -record /tmp/pip-Rlxkpz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-w2BjnN/semantic-version/

**Comment by hnwangkg-ezio** [comment]
I have solved and forgot to add sudo

**Comment by pelikhan** [comment]
See http://docs.yottabuild.org/reference/cheatsheet.html

**Comment by hnwangkg-ezio** [comment]
Thanks, I got it, and now I'm researching how to display the downloaded image.
I put a 300 * 200 pixel image in the root directory, can not appear in the picture, I am not missing any important steps?

**Comment by pelikhan** [comment]
I am not sure what you are referring to.

**Comment by hnwangkg-ezio** [comment]
https://github.com/hnwangkg-ezio/LED
Add icon.png for package dialog
I added it in this directory. Pgn picture
I want to use "add package" in makecode
