### ISSUE TITLE
From ts to c++, the function parameters can only be up to four?

### ISSUE THREAD

**Issue by hnwangkg-ezio** [Microsoft/pxt#4033]
I have a new question:
From ts to c++, the function parameters can only be up to four?
When I pass five, an Assertion failed

E.g：
in ts:
    //% blockId=Draw_Line
    //% block="Draw Line |Xstart %Xstart |Ystart %Ystart |Xend %Xend |Yend %Yend |Line_width %Line_width |Color %Color"
    //% Xstart.min=0 Xstart.max=160 Ystart.min=0 Ystart.max=128
    //% Xend.min=0 Xend.max=160 Yend.min=0 Yend.max=128 
    //% Line_width.min=1 Line_width.max=4
    //% Color.min=0 Color.max=65535
    //% shim=LEDs::Draw_Line
    //% weight=197
    export function Draw_Line(Xstart: number, Ystart: number, Xend: number, Yend: number, Line_width: number, Color: number): void{
        return;
    }

in c++:
    //%
    void Draw_Line(int Xstart, int Ystart, int Xend, int Yend, int Line_width, int Color) {
        dis->GUI_DrawLine(Xstart, Ystart, Xend, Yend, Line_width, Color);
    }
Will happen：
 pxt_modules/core/dal.d.ts(1,1): error TS9200: Assertion failed
When I reduce a parameter normally...
Is it my wrong judgment?

**Comment by hnwangkg-ezio** [comment]
i got it

**Comment by zjuxumang** [comment]
> i got it

I still have the same problem now, isn't it fixed?

I'm using microbit target v1.3.5 with pxt-core v5.5.15
