### ISSUE TITLE
pxtsim class EventQueue is generic, but the EventBus class which uses it is not.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4041]
Easy opportunity here to let clients send event values of other than the `number` type.

The `EventBus` class is restricted to queuing events with values of type `number`. Internally it uses queues of type `EventQueue<number>`. It'd be a useful enhancement to have the current `EventBus` be an alias for type `EventBusGeneric<number>` for backward compatibility while `EventBusGeneric<T>` is basically a generic version of the current `EventBus` code with the template parameter being passed through as `EventQueue<T>`.

_(granted I suspect the reason for just supporting the simple `number` type of bus event values is the heritage of pxtsim from micro controller buses)_

**Comment by matthewtebbs** [comment]
Update:

Actually it's easier using default values for the generic type argument so no need for the interim EventBusGeneric<>.

e.g. 

```typescript
export class EventBus<T = number> {
...
}
```

:) I'm going to submit a PR.

**Comment by matthewtebbs** [comment]
PR [4043](https://github.com/Microsoft/pxt/pull/4043).

(alas had to go with the `EventBusGeneric<T>` approach given the need to keep backward compatibility and pass zero as the value when no value is provided for `EventBus` of type `number`)

**Comment by samelhusseini** [comment]
Thanks for fixing this @matthewtebbs

**Comment by matthewtebbs** [comment]
Np. I’m using it to give me more flexibility on defining events. Actually I can now have a single ‘board’ bus: EventBusGeneric<EventValue> and party on it.
