### ISSUE TITLE
When moving cursor on "Support", it shows "Help"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#4042]
**Repro Steps:**
• Navigate to https://makecode.microbit.org/beta
• Click "Help" and then move coursor on "Support", "Getting started"... one by one

**Expect result:**
When moving cursor on "Support", it should show "Support"
**Actual result:**
When moving cursor on "Support", it shows "Help"
![18](https://user-images.githubusercontent.com/23466737/38181060-340e9e0c-3620-11e8-9012-5663937b4207.gif)

**Comment by samelhusseini** [comment]
Fixed.

**Comment by Helen09** [comment]
Closed as fixed
