### ISSUE TITLE
Program too large - error

### ISSUE THREAD

**Issue by teenne** [microsoft/pxt#4074]
I get "Program too large"-error in MakeCode, when switching between block-editor and JS editor. My code is over 1000 blocks and 848 lines of JS code in total. 

https://makecode.com/_PpAMzTgADh28 

Browser: Chrome version 65.0.3325.181 (64-bit)
OS: Windows 10 Enterprise

**Comment by samelhusseini** [comment]
@riknoll maybe the 1000 block limit is a little on the low end?

**Comment by abchatra** [comment]
This we have fixed now.
