### ISSUE TITLE
Corrupt file when downloading screenshot in MakeCode

### ISSUE THREAD

**Issue by teenne** [microsoft/pxt#4075]
When I try to download screenshot in MakeCode, I get a corrupt file. Link added. 
When working on bigger project the generated screenshot-file could be pretty large if it contains all code. Maybe an option for downloading screenshot of highlighted function or a single block, or what is visible on the screen. 

Browser: Chrome version 65.0.3325.181 (64-bit)
OS: Windows 10 Enterprise
Link to project: https://makecode.com/_PpAMzTgADh28

**Comment by abchatra** [comment]
This is likely fixed.
