### ISSUE TITLE
Black background on Download Screenshot

### ISSUE THREAD

**Issue by teenne** [Microsoft/pxt#4078]
When downloading Screenshot in MakeCode, the background color get black. To make the feature usable so it can be used in education material like presentations, tutorials, documentations etc, the images needs editing to remove the black coloring. 

I would suggest making the png transparent so the black background color would be replaced with transparency or white at least. Transparent would be prefferable

Browser: Chrome version 65.0.3325.181 (64-bit)
OS: WIndows 10 Enterprise

**Comment by pelikhan** [comment]
It should have been transparent...

________________________________

**Comment by samelhusseini** [comment]
Is it possible it is transparent but Windows shows a black background when opening a transparent image in whatever the default image viewer is these days?

**Comment by teenne** [comment]
It was the default image viewer that did not handle it. :) Yes, it's transparent.
