### ISSUE TITLE
New function appears at top of the project desktop

### ISSUE THREAD

**Issue by teenne** [microsoft/pxt#4084]
When a "new function" is created in MakeCode, it appears at the top of the project desktop, so the user has to scroll all the way to the top to locate it. It would make more sense and would be more user friendly that it appears somewhere on the visible screen - like it does on "duplicate block".

**Comment by samelhusseini** [comment]
Agreed it should show somewhere the user can see.

**Comment by abchatra** [comment]
This is fixed.
