### ISSUE TITLE
Connecting Simulator with outside APIs?

### ISSUE THREAD

**Issue by sophiaveksler** [Microsoft/pxt#4090]
Hi,
I am doing a project where I am trying to have the micro:bit interact with the adafruit.io API (https://github.com/adafruit/io-api - I am using the node version). I've come up with a few blocks, and I'm wondering if there's any way that I can make the simulator send requests to the API using node. I'm currently not worrying about the hardware functionality - that will come later. I just want to see if I can send requests to the API using the simulator.

For example, if I have a "send data" block, and I have it configured to run every time I press button A, I'd like it to send a request to adafruit to create data. By doing this, I'm hoping to make it easier for people to create feeds with data from their IoT devices.

Please let me know if there is any way to do this already, or where I could potentially inject code if possible. Also, if you'd like me to provide more information about using the adafruit node API, I'd be happy to do so.

**Comment by matthewtebbs** [comment]
**Async function blocks**
https://makecode.com/async

The TS-node version of the io-api that you can generate from swagger returns bluebird based promises that are fulfilled upon the completion of the REST call so you can return those promises from your block implementation. I think. Never done it.

And then within the simulator function implementation of the block just go call the appropriate io-api function. You'll of course need to include the generated io-api _api.ts_ file in your sim compilation. For the hardware target I suspect you could just implement these same block functions using an io=api cpprest client instead - but I have NO experience of doing that so it's just a guess.

**Comment by matthewtebbs** [comment]
https://gitter.im/makecode-community/Lobby is a better place for questions btw.

**Comment by pelikhan** [comment]
There is facilities to issue HTTP requests or inject javascript from the simulator -- so you would not be able to talk to AdafruitIO from the editor. 
You could use the console.log to mirror the message so that the user could see what's going on?
