### ISSUE TITLE
Code snippets are not created for properties, e.g. those block combined.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4097]
The culprit is this check in the beginning of the function below in the emitter service.

```typescript
export function getSnippet(n: ts.SignatureDeclaration, attrs?: CommentAttrs): string {
    if (!ts.isFunctionLike(n)) {
        return undefined;
    }
    ...
```

I'm working on a PR to fix this as well as allow for block combined properties not of the number type.

**Comment by abchatra** [comment]
Gitter is a better place for these kind of discussions.
