### ISSUE TITLE
direct edit of package

### ISSUE THREAD

**Issue by machinehistories** [Microsoft/pxt#4160]
I notice there is an lock icon in the code explorer. When one is developing a package is there a way to unlock a file to make immediate edits. Currently I am referencing my newly edited changes through the served package on github. I often find that even after deleting a package and reloading the newly edited package and clicking on the update icon it will still somehow pull the previous package. I suppose it has the old info in cache but it can get really frustrating to get it load the most current package from github and I'm not sure why. It would be cool to just be able to internalize the package and then be able to freely edit it. Maybe there is a better way to test packages and if so please let me know.

**Comment by abchatra** [comment]
Free editing is not in our immediate plan. Thanks for the feedback
