### ISSUE TITLE
Emitted code for property shim does not work as expected for declared interface

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4163]
For a running example of this go to the MakeCode target at [pxt-Test](https://muddytummy.github.io/pxt-Test) and open up the Test project in examples. The code is [here](https://github.com/muddytummy/pxt-Test).

Running this test project will result in the error '_globals.bnumber___50.b is not a function_' being thrown from the generated code. The emitter for the declaration of kind `PropertySignature` (property `b` on interface `BNumber`) generated a method call on an instance of `BNumberImpl` hence the error.

I'd expect for non-native, continuation-style JavaScript, the code generation to emit the same expression form as for the declaration of kind `PropertyDeclaration` (property `a` on `ANumber`).

I'm trying to use a declared interface like this to provide my target pxt-Target with greater implementation abstraction, for example a WebGL material could be implemented by either BabylonJS or ThreeJS and the simulator need not know.

The PXT attribute annotated declaration file is below,

```typescript
//% blockNamespace=test
declare class ANumber {
    //% blockCombine
    //% shim=.a property
    public a: number;
}

//% blockNamespace=test
declare interface BNumber {
    //% blockCombine
    //% shim=.b property
    b: number;
}

//% color=270 weight=96 icon="\uf128"
declare namespace test {
    //% blockId=test_create_a_number
    //% block="create ANumber"
    //% shim=test::createANumber
    function createANumber(): ANumber;

    //% blockId=test_create_b_number
    //% block="create BNumber"
    //% shim=test::createBNumber
    function createBNumber(): BNumber;
}
```

The simulator implementation is simple,

```typescript
namespace pxsim {
    export class ANumber {
        constructor(public a: number) {}
    }

    export class BNumberImpl implements BNumber {
        constructor(public b: number) {}
    }
}

namespace pxsim.test {
    export function createANumber(): ANumber {
        return new ANumber(1234);
    }

    export function createBNumber(): BNumber {
        return new BNumberImpl(5678);
    }
}
```

The code snippet in pxt-core that makes the decision to emit one expression form vs. the other in _pxtcompiler/emitter/emitter.ts_,

```typescript
if (decl.kind == SK.PropertySignature || decl.kind == SK.PropertyAssignment) {
    return emitCallCore(node, node, [], null, decl as any, node.expression)
    /*
    if (attrs.shim) {
        callInfo.args.push(node.expression)
        return emitShim(decl, node, [node.expression])
    } else {
        throw unhandled(node, lf("no {shim:...}"), 9236);
    */
} else if (decl.kind == SK.PropertyDeclaration) {
    if (isStatic(decl)) {
        return emitLocalLoad(decl as PropertyDeclaration)
    }
    let idx = fieldIndex(node)
    callInfo.args.push(node.expression)
    return ir.op(EK.FieldAccess, [emitExpr(node.expression)], idx)
} 
```

**Comment by matthewtebbs** [comment]
@mmoskal would love some guidance here. I can provide a PR if I understand what needs to be done, or the context of this more.

**Comment by mmoskal** [comment]
It does indeed seem like a bug. I wonder if we ever rely on it...

It seems that if `attrs.property && attrs.shim && attrs.shim[0] == "."` we should go the the `ir.op(EK.FieldAccess, ...)` even if `decl.kind == SK.PropertySignature || decl.kind == SK.PropertyAssignment`

**Comment by matthewtebbs** [comment]
From what I can tell I’ve only managed to get property signatures on a declared interface by hand-coding the declaration file.

 

If you go the auto-generation route you’ll only get a declared interface for fixed instances and not one with properties that are defined the same.

They are defined with shims that map to functions on namespaces, e.g. namespace::property rather than inteferface.property.

 

Does existing code rely on this behavior? You got me ☺

 

-Matthew
