### ISSUE TITLE
Regression in emitted code from compileEvent from version 3.8.18 to 3.10.1.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4165]
I'm seeing a regression where input variable names for callbacks are getting garbled in the generated TypeScript.

See the Block and Monaco code views below.

![image](https://user-images.githubusercontent.com/1424775/38968143-137b3e9e-433f-11e8-9346-e8e80830c458.png)

![image](https://user-images.githubusercontent.com/1424775/38968149-19b0d530-433f-11e8-8008-e9dc4169247d.png)

This appears to be caused by a change in Blockly between pxt-core releases 3.8.18 and 3.10.1.

Blocky used to define `Blockly.FieldVariable.getValue()` As this,

```javascript
Blockly.FieldVariable.prototype.getValue = function() {
    return this.getText()
}
```

And not it defines it as this,

```javascript
Blockly.FieldVariable.prototype.getValue = function() {
    return this.variable_ ? this.variable_.getId() : null
}

Blockly.FieldVariable.prototype.getText = function() {
    return this.variable_ ? this.variable_.name : ""
}
```

Which means the code below in pxt-core now emits field variable ids and not field variable names.

```typescript
if (stdFunc && stdFunc.comp.handlerArgs.length) {
    stdFunc.comp.handlerArgs.forEach(function(arg) {
    var varName = b.getFieldValue("HANDLER_" + arg.name); /* <-- ISSUE HERE */
    if (varName != null) {
        trackLocalDeclaration(escapeVarName(varName, e), arg.type);
    }
}
````

Certainly it's bad that Blockly introduced a potentially breaking change like this BUT perhaps pxt-core was incorrectly using Blockly.FieldVariable.getValue() in the first place. A fix for this line would be,

```typescript
    var varName = b.getField("HANDLER_" + arg.name).getText(); /* <-- ISSUE HERE */
```

There may be others with the same pattern.

**Comment by pelikhan** [comment]
I think Richard fixed this one in 10.3

________________________________

**Comment by matthewtebbs** [comment]
Coolio.

**Comment by matthewtebbs** [comment]
Ah yes, https://github.com/Microsoft/pxt/pull/4164 and tagged for 3.10.8.

**Comment by samelhusseini** [comment]
Fixed.
