### ISSUE TITLE
end-to-end compilation test suite

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#417]
- [ ] build a micro test framework for PXT where the result of assertions is communicated via serial. Each test should communicate the result success/passed to the test harness via serial. The harness should have an expect output file.
- [ ] migrate compiler test suite to use test framework
- [ ] setup a physical machine with connected micro:bit to run tests

The goal of this work is to have an end-to-end test suite that runs the generated code on the device itself.

**Comment by tballmsft** [comment]
We can also do basic regression testing of the assembly generation and hex file generation.

**Comment by mmoskal** [comment]
The current lang-test0,1 tests already print to serial. These are compiler tests, they do not tests the APIs much though. There are also "samples" in `tests/`, but these do not do any asserts etc.

**Comment by pelikhan** [comment]
We need to have versions test suites to test backward compat.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Won't fix for now.
