### ISSUE TITLE
Jump to help from top-right button of help drawer does nothing on Firefox 59 on macOS

### ISSUE THREAD

**Issue by matthewtebbs** [microsoft/pxt#4183]
On Chrome 66 it launches to a new browser window on the help page URL.
On Safari 11.1 launches to a new browser window also.
On Firefox 59 it does not.

Both tested on macOS.

Tested on released pxt-core, e.g. microbit and adafruit targets and pxt-core 3.10.10.

See image below for the help launch button I'm referring to.

![image](https://user-images.githubusercontent.com/1424775/39079947-8c9a1cc8-44d9-11e8-8938-6c6de8dfb063.png)

**Comment by abchatra** [comment]
This should be fixed now
