### ISSUE TITLE
Request to provide option to deploy minified versions of PXT JS files.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4202]
@samelhusseini is doing performance work w.r.t. image sizes, volume (count and length) of JavaScript files to load into the browser memory.

Why not minify the JS files?

**Comment by samelhusseini** [comment]
I'm investigating minifying JS on publish to the cloud.
As for static package deployment, the option to minify is already there.

**Comment by matthewtebbs** [comment]
Oh, looking at the code now I do see '--minify'. The docs are a bit sparse w.r.t documenting the pxt staticpkg switches. Cool.

**Comment by matthewtebbs** [comment]
Closing this out.
