### ISSUE TITLE
Move tests to one location

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#422]
Currently we have tests in the following locations:

```
test/
tests/
test-errors/
libs/lang-test0
libs/format-test
```

We should move them to one place and name them a little more clearly.

**Comment by pelikhan** [comment]
Yes!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Closing. Important issue but need not be tracked as a issue
