### ISSUE TITLE
array insertAt BUG.

### ISSUE THREAD

**Issue by dailinyang** [Microsoft/pxt#4248]
The code below is correct in the browser, but after download and save into microbit, the result is wrong.
It seems inserting at the end of array, the old data will be replace with the new data instead of inserting, and a NULL char will be append in it.

The code
-------------
let a = ['A']
function dump() {
    for (let i = 0; i < a.length; i++) {
        serial.writeString(a[i])
    }
    serial.writeLine("")
    serial.writeLine(a.length + "")
}
input.onButtonPressed(Button.A, () => {
    a.insertAt(0, 'a')
    dump();
})

The output in MU REPL window
-------------------------
![image](https://user-images.githubusercontent.com/11917566/39574597-5b146fc4-4f0a-11e8-8d9e-bc0b68f8f69b.png)

**Comment by abchatra** [comment]
@dailinyang please file microbit issues in github.com/microsoft/pxt-microbit
