### ISSUE TITLE
User can't navigagte between different category items using keyboard

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#4260]
**Repro step:**
• Navigate to https://makecode.microbit.org/beta
• Click in the Search box
• Navigate between different category items using the keyboard 

**Expected result:**
User can navigate between different category items using keyboard
**Actual result:**
User can't navigagte between different category items using keyboard
![1](https://user-images.githubusercontent.com/23466737/39697415-6740d390-51e0-11e8-9a6b-bc6403de204d.gif)

**Comment by abchatra** [comment]
Please file microbit issues in github.com/microsoft/pxt-microbit
