### ISSUE TITLE
Make a variable dialog does not default focus to name box

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4271]
Chrome: 66.0.3359.139 (64-bit)
pxt-core: 3.12.26

May happen on other browsers and other pxt-core versions. I didn't check.

**Comment by samelhusseini** [comment]
Could you check latest. I've added the autoFocus attribute on that input, and I know Chrome supports it so it should be focusing.

**Comment by samelhusseini** [comment]
Actually I think I know what the issue may be. It works the first time, but doesn't on subsequent times. We might need to destroy the input as it only autofocuses on mount. I'll look into it.
