### ISSUE TITLE
npm audit results should be reviewed

### ISSUE THREAD

**Issue by matthewtebbs** [microsoft/pxt#4273]
Report attached. Obviously hoek != 4.2.1 or != 5.0.3 is still being referenced as one.

- Run `npm install less@3.0.4` to resolve 4 vulnerabilities.
- Run `npm update sshpk --depth 7` to resolve 1 vulnerability.
- Run `npm update fill-range --depth 7` to resolve 1 vulnerability.

There are others that need to be manually resolved.
[report.txt](https://github.com/Microsoft/pxt/files/1985407/report.txt)

Personally as well as less I'd like to see semantic-ui-less updated also but there's some backward compat reason, that I can't remember, why we don't do that.

**Comment by matthewtebbs** [comment]
I guess v3.x of semantic-ui-less had an updated font awesome with glyphs that were wider than the old ones, e.g. console.

**Comment by matthewtebbs** [comment]
Updating less should be a no-brainer no?

**Comment by samelhusseini** [comment]
semantic ui less has compat issues with newer less. so we'd need to upgrade both. New version of less broken semantic a while back hence why we snapped them both. we just need to go through and update both at this point, surely by now they've fixed the issue.

**Comment by abchatra** [comment]
Fixed
