### ISSUE TITLE
Exception when clicking on "pins" in maker

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#4294]
![image](https://user-images.githubusercontent.com/4175913/39954240-fea6e9ac-5570-11e8-8032-1fa8474bcb03.png)

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/39954581-06ac8d4a-5577-11e8-9e91-3542713b5f82.png)

**Comment by samelhusseini** [comment]
Yeah fix is here: https://github.com/Microsoft/pxt/pull/4296

**Comment by pelikhan** [comment]
The issue is that ''b'' is undefined.

**Comment by samelhusseini** [comment]
haha peli check the PR!

**Comment by samelhusseini** [comment]
issue is that b is a list with an undefined item.
