### ISSUE TITLE
serial.readLine issue on raspberry pi

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#430]
"
Unfortunately, I am having a lot of trouble with serial.readline() in your application. I can see the data is being received by the Bit by the blinking tx/rx light, but no matter what I try I am unable to process any data that I enter through the terminal. 

To confirm that I have the terminal setup correctly, I'm able to read serial.writeline in the terminal whenever I exclude anything to do with readline. It appears to be blocking or stuck on the readline. 

I was wondering if you might be able to get someone to fix this? It would make a tremendous difference to me if you could.

I apologize for the email out of the blue, but since I discovered codethemicrobit from our profile page, I thought you might be the best person to contact.
"

Note: this is probably due to line-endings characters.

Here's the code:

```
let saj = ""
basic.forever(() => {
    serial.writeLine(saj)
    saj = (serial.readLine())
    serial.writeLine(saj)
    if (saj == "l") {
        serial.writeLine("Servo to 180")
        pins.servoWritePin(AnalogPin.P0, 180)
    } else if (saj == "r") {
        serial.writeLine("Servo to 0")
        pins.servoWritePin(AnalogPin.P0, 0)
    } else {
    }
    input.onButtonPressed(Button.A, () => {
        serial.writeLine("Servo to 180")
        pins.servoWritePin(AnalogPin.P0, 180)
    })
    input.onButtonPressed(Button.B, () => {
        serial.writeLine("Servo to 0")
        pins.servoWritePin(AnalogPin.P0, 0)
    })
})
```

**Comment by Saj37uk** [comment]
Following up on this - any progress on getting this fixed? 

This problem is not limited to the Raspberry Pi - Sending serial commands to the Microbit from a PC also does not appear to work. Would really appreciate a solution.

**Comment by pelikhan** [comment]
Please try using the serial.readUntil function and provide a custom separator string. It might unblock you.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
