### ISSUE TITLE
Minor warning in Chrome - pxtapp.js:17979 allow attribute is overriding 'allowfullscreen'

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4300]
```typescript
frame.allowFullscreen = true;
frame.setAttribute('allow', 'autoplay; fullscreen');
```
_pxtapp.js:17979 allow attribute is overriding 'allowfullscreen'.
SimulatorDriver.createFrame @ pxtapp.js:17979_

I suspect setting the `allowFullscreen` property set is superfluous.

**Comment by samelhusseini** [comment]
Yeah, maybe we just stick to the old way "allowfullscreen" for old browser compatibility and only use the 'allow' attribute for autoplay.
