### ISSUE TITLE
playTone on start loses ALL subsequent simulator audio (likely due to Chrome autoplay policy changes)

### ISSUE THREAD

**Issue by nbogie** [Microsoft/pxt#4318]
In Chrome, loading a project with a "play tone" music block placed "on start" effectively loses the simulator's audio for all subsequent uses of play tone (at least) until it is reloaded.  There is no feedback to the user why the audio is not working.

Microbit, circuit playground, and mindstorm simulators all exhibit the same issue.

Simplest reproducible test case:
* In Google Chrome (0.66)...
* Visit https://makecode.microbit.org/_cq05vqF81CiV
* Press button A after it has loaded

Expected behaviour:
* musical note is sounded by simulator on load (ideal)
* subsequent presses of button A should sound notes, *even if the on-start music fails*.

Observed behaviour:
* No note sounded on start
* No notes sounded on subsequent presses of button A
* Error appears (once) in console: "The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu"

Platform:
* Observed in Google Chrome 66.0.3359.139 on OSX 10.13.4
* Works fine in safari 11.1 on same OS

The observed behaviour may be affected by the site's "engagement index".  In google chrome (0.66) ensure that the url https://makecode.microbit.org/ in `chrome://media-engagement/` has a score of 0 (or at least is not rated high (a high rating would permit it to autoplay stuff under the new autoplay policy and would hide the issue).

Hypothesis:
Recent Chrome autoplay policy changes* prevent the audio context being available to the simulator on autoplay on load (and I'd speculate that perhaps the simulator doesn't try to acquire the context again after this happens so that it can play future sound events, where perhaps it should try again to acquire it.)
* https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

Testing the hypothesis:
I loosened chrome's autoplay-policy by setting the Chrome flag "Autoplay Policy" to "No user gesture is required" at `chrome://flags/#autoplay-policy` and then reloaded the above test project (after necessarily restarting chrome).  I then got the expected behaviour: the simulator plays music at start and subsequently.
If I then turn the policy back to "default", the issue reappears.

Misc thoughts:
Ideally, Chrome's "Media Engagement Index" of https://makecode.microbit.org/ would be very high after all the user's interaction with the site, permitting autoplay by the site for frequent users. But even were that the case for frequent users, for newcomers the above issue would persist, so the simulator should be robust in the face of having its attempted autoplay rejected, and seek to recover quickly.

I initially reported this as [an issue with pxt-microbit](https://github.com/Microsoft/pxt-microbit/issues/766) but it looks like it is common to all of the simulators.  (I'll close it there if it is accepted here.)

**Comment by abchatra** [comment]
Thanks for reporting the issue. Please open user facing issues of microbit in pxt-microbit. I have ported this issue there.
