### ISSUE TITLE
Localized hint covers text

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#4328]
![image](https://user-images.githubusercontent.com/4175913/40148297-1f4a4c4e-5922-11e8-9ba1-2387678c9eea.png)

I propose using a "?" instead of "hint". It can get really long (allusione in italian)

**Comment by abchatra** [comment]
Please move it pxt-minecraft.

**Comment by pelikhan** [comment]
This is a PXT issue.

**Comment by abchatra** [comment]
We are tracking all user facing issues in their target

**Comment by pelikhan** [comment]
All targets are impacted by this bug.

**Comment by abchatra** [comment]
Moved to https://github.com/Microsoft/pxt-minecraft/issues/566
