### ISSUE TITLE
Need to save projects in different location

### ISSUE THREAD

**Issue by eduardobcastro** [Microsoft/pxt#4338]
Projects are saved on local storage and users are unable to get their content from another computer unless they share the project on makecode.com.
My suggestion is that it could be possible to configure an endpoint URL to save to and load from.

**Comment by eduardobcastro** [comment]
We are building a website where users can use different coding platforms. We'd like users could see what they did on each platform in just one place.

**Comment by abchatra** [comment]
We don't support posting to custom URL. There are privacy issues with this and we don't have plan to support this in near future.
