### ISSUE TITLE
makecode.com security headers could be tightened up

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4344]
Ran makecode.com through https://securityheaders.com/.

Some headers could be added to make the site more secure.

**Content-Security-Policy**
Content Security Policy is an effective measure to protect your site from XSS attacks. By whitelisting sources of approved content, you can prevent the browser from loading malicious assets.

**X-Frame-Options**
X-Frame-Options tells the browser whether you want to allow your site to be framed or not. By preventing a browser from framing your site you can defend against attacks like clickjacking. Recommended value "x-frame-options: SAMEORIGIN".

**Referrer-Policy**
Referrer Policy is a new header that allows a site to control how much information the browser includes with navigations away from a document and should be set by all sites.

**Comment by abchatra** [comment]
Thanks for the report.

We allow X-Frame-Options for embedding scenario.
Referrer-Policy - It is fine for the browser to provide additional information about our site for referral. 
CSP - Majority of the case this doesn't provide any additional security. See this [paper](https://dl.acm.org/citation.cfm?id=2978363)

If you check google.com it also violates these 3.  Microsoft.com violates 2 but doesn't allow embedding. So I am assuming they are not as bad as they look. These are won't fix from our side.

If you believe you have found a security issue in PXT, please share it with us privately following the guidance at the [Mcrosoft Security TechCenter](https://technet.microsoft.com/en-us/security/ff852094) porting it via this channel helps minimize risk to projects built with PXT.

**Comment by matthewtebbs** [comment]
Will do re: reporting via Microsoft Security TechCenter. Good call. Thx.
