### ISSUE TITLE
trouble in using pxt staticpkg command.

### ISSUE THREAD

**Issue by lucas1677** [Microsoft/pxt#4355]
@pelikhan when i use pxt staticpkg command to generate webpages. 
and then .I got this.
![image](https://user-images.githubusercontent.com/20339198/40358672-9a5e9744-5df2-11e8-8d38-19559ec9ada7.png)
I'm running it in pxt-microbit project.

**Comment by pelikhan** [comment]
staticpkg is not well supported in PXT v0 (which is the Branch Microbit is using).

_____________________________
