### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by d1runberg** [Microsoft/pxt#4360]
I followed the instructions and got this error when running `pxt install`

Using target microbit with build engine yotta
  target: v1.1.15 /Users/Derek/node_modules/pxt-microbit
  pxt-core: v3.15.6 /Users/Derek/node_modules/pxt-microbit/node_modules/pxt-core
skipping download of local pkg: file:.
Error: package this is missing pxt.json

Any help would be much appreciated!

**Comment by d1runberg** [comment]
OK updated version of PXT and installs cleanly and runs, but now I get just the PXT logo in browser forever. When I open the browser inspector... I get this error...

`TypeError: undefined is not an object (evaluating 'pxt.appTarget.simulator.headless')`

**Comment by lucas1677** [comment]
@d1runberg what are you trying to do?
if you are trying to build pxt-microbit project you should use v0 branch.

**Comment by abchatra** [comment]
Fixed

**Comment by d1runberg** [comment]
I am trying to build an install image for a raspberry pi to host makecode
on it for offline uses at a boyscout camp.
