### ISSUE TITLE
Adafruit Crikit Hardware and makecode.adafruit.org  version 1.1.21

### ISSUE THREAD

**Issue by victorgithubvv** [Microsoft/pxt#4407]
Greetings;
I am a newbie. Is this the location to post the following statement,
I have a Adafruit Circuit playground Express and Adafruit Crickit hardware. When I go to makecode.adafruit.org using Google Chromium on a Raspberry Pi , I receive this error.  "Cnnot load package: Package Crickit requires target version 1.1.21 (you are running 1.1.9). 

When I go to makecode.adafruit.org using Google Chrome on a Windows 7 i7 Dell computer, I receive this error.  "Cnnot load package: Package Crickit requires target version 1.1.21 (you are running 1.1.9). 

Do I use Microsoft Edge or IE? Or how can I update makecode.adafruit.org  from 1.1.9 to 1.1.21 ?

**Comment by pelikhan** [comment]
Use https://MakeCode.adafruit.com/beta for now...

_____________________________

**Comment by abchatra** [comment]
Beta will be released to live soon
