### ISSUE TITLE
MakeCode playground samples

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt#4421]
https://makecode.com/playground

# Samples:

## Basic
- [x] Hello world
- [x] Namespace color
- [x] Namespace icon
- [x] Groups
- [x] Weights
- [ ] Gaps
- [x] Types of blocks
- [x] Enumerations
- [x] Default values
- [x] min/max
- [x] Inputs (inline/external)
- [ ] JSDoc -> help text

## Field editors
- [x] Color fields
- [x] Dropdowns
- [x] Toggle @samelhusseini
- [x] Note picker @samelhusseini
- [x] Grid picker @guillaumejenkins 
- [ ] Image and images fields @samelhusseini
- [ ] Speed and turn ratio @samelhusseini
- [ ] Sprite editor @riknoll 
- [ ] Custom fields (passing options, decompileLiterals, etc.) @riknoll + @samelhusseini 

## Language Features
- [ ] Instance methods @riknoll
- [ ] Handlers @riknoll
- [ ] Handlers with arguments @riknoll
- [ ] Optional parameters (expandable blocks) @riknoll
- [ ] Setters/getters
- [ ] Enum dropdowns
- [ ] Shim blocks
- [x] Blocks that create enums @riknoll
- [ ] Tagged templates @riknoll

## Other
- [ ] Fixed instances @riknoll 
- [ ] Styles for block text @riknoll
- [ ] Pause Until and Forever
- [ ] Variable block?
- [ ] image resources 
- [ ] sprite sheet resources
- [ ] search in grid picker

# Instructions:
Here are instructions on how to add a sample: https://github.com/Microsoft/pxt/blob/master/docs/static/playground/samples/README.md

**Comment by pelikhan** [comment]
@ganicke

**Comment by abchatra** [comment]
Not tracking as a bug.
