### ISSUE TITLE
Block re-ordering not working for OO 

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#4434]
Given this example of array_push: 

```
    //% blockId="array_push" block="add $item to $this" blockNamespace="arrays"
    push(item: T): void;
```

You would expect it to show add VALUE to THIS but it shows "add to THIS"

<img width="210" alt="screen shot 2018-06-06 at 5 06 44 pm" src="https://user-images.githubusercontent.com/16690124/41071342-097335bc-69ac-11e8-83aa-b58822064f2d.png">

**Comment by samelhusseini** [comment]
Let's also add playground samples for this when you get a chance.

**Comment by abchatra** [comment]
I don't understand this bug. Please provide exact repro steps.
