### ISSUE TITLE
staticpkg command does not generate proper /compile/extension setup

### ISSUE THREAD

**Issue by andybru** [Microsoft/pxt#4461]
Athough yotta now is running and all the 'pxt staticpkg' runs 'fine' and
'without' bugs the download button in calliope and mircrobit targets
in the static versions is without function -> "POST /compile/extension" Error(404):"Not found".

I believe something is not 'published' properly.

![nodehttpservertrace](https://user-images.githubusercontent.com/30912461/41217483-4eb06208-6d58-11e8-9df7-cc57ba22f392.png)
 

(The hassle with python version rollbacks for a running yotta was fixed with downgrading:
    **downgrade pip** to demand lower cryptography version ->
        C:\yotta\python\python.exe -m pip install pip==9.0.3,

    .. yotta 0.18.5 has requirement cryptography<2.2,>=2.1.4, but you'll have cryptography 2.2.2 
   which is incompatible. .

   **downgrade cryptography** for yotta ->
        C:\yotta\python\python.exe -m pip install cryptography==2.1.4

   .. pkg_resources.ContextualVersionConflict: (cryptography 2.1.4 (c:\yotta\python\lib\site-packages),
     Requirement.parse('cryptography>=2.2.1'), set(['pyOpenSSL'])) ..

 **downgrade pyopenssl** to be less demanding against cryptography->
    C:\yotta\python\python.exe -m pip install pyopenssl==17.5.0

)

And with some content in #'pxt-calliope\docs\js\inference.md'
pxt staticpkg run trough and completed and generated
a mainly functional directory with all the content.

Thanks for consideration.

**Comment by abchatra** [comment]
Please move questions to Discord server https://aka.ms/makecodecommunity  or stackoverflow
