### ISSUE TITLE
makecode.com public documentation pages have vertical scroll bar problems

### ISSUE THREAD

**Issue by andybru** [Microsoft/pxt#4463]
On most pages of MakeCode documentation scrolling down is nearly impossible!

The vertical scroll bar changes its focused state only in the topmost 25% of the 
grey bar usually be grabbed everywhere with the mouse left click and drawn down.

I.e.
https://makecode.com/contact
https://makecode.com/js/editor
https://makecode.com/docs

show all the same behaviour with

Edge, Chrome and Firefox.

**Comment by andybru** [comment]
Also if you grabed the right/vertical scroll bar slider,
move it down on a page to the very last content and
release it (release left-clicked mouse button) you can
not grab it again.
It stays light-grey and does not focus any more.

This is valid from different locations on mainly tested with windows 10.

**Comment by pelikhan** [comment]
Two finger scroll works but it's impossible to grab the scroll bar.

**Comment by abchatra** [comment]
This is fixed. @andybru Please validate and let us know.
