### ISSUE TITLE
Can only print one page in docs

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#4466]
In the docs, you can only print 1 page worth of content. 

Repro steps: 
Go to any long documentation page such as 
https://makecode.microbit.org/blocks/javascript-blocks

Try to print. 
You'll notice it only allows you to print the first page. 
![screen shot 2018-06-12 at 3 55 44 pm](https://user-images.githubusercontent.com/16690124/41321498-19ecbd6c-6e59-11e8-8cba-a28b49c78b8e.png)

**Comment by samelhusseini** [comment]
@pelikhan FYI

**Comment by pelikhan** [comment]
Weeeeiiiiirrrddd
