### ISSUE TITLE
Use the local installation of openocd in place of the old one of the arduino package

### ISSUE THREAD

**Issue by nedseb** [Microsoft/pxt#4483]
# Feature request
Yesterday, I need to debug a program for an STM32L4 board. The version 
of openocd in the arduino package is a bit old and don't support this board.  

During the finding of openocd, if the local installation could be considered, I think thats a good first solution.

**Comment by abchatra** [comment]
@nedseb What product are you using?

**Comment by abchatra** [comment]
fixed
