### ISSUE TITLE
add label (/beta) in pxtConfig

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#451]
- [ ] add to pxtConfig served by web server
- [ ] add to mixpanel super properties (peli)

**Comment by mmoskal** [comment]
You want the current label in pxtConfig? Or is it for nagging?

**Comment by pelikhan** [comment]
To differentiate people using beta vs app vs app

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mmoskal** [comment]
What’s wrong with looking at the URL?

**Comment by pelikhan** [comment]
Will do.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
