### ISSUE TITLE
Visibility change of browser causes simulator restart.

### ISSUE THREAD

**Issue by matthewtebbs** [Microsoft/pxt#4520]
For example minimize, or maximize, or change the desktop active window, and the PXT simulator is restarted. What's the reason for this? Can it be avoided?

**Comment by pelikhan** [comment]
Simulator can be a hog, we stop it when swapping windows.

**Comment by pelikhan** [comment]
Swapping tabs...

**Comment by matthewtebbs** [comment]
For an in-browser PXT game I suspect it will be annoying. I'll spend some cycles seeing if I can add a pause notion that is backward compatible with existing sims.

**Comment by abchatra** [comment]
This is by design.
