### ISSUE TITLE
Collapsible function blocks would be an awesome feature for MakeCode Minecraft Block Editor

### ISSUE THREAD

**Issue by philgolden** [microsoft/pxt#4526]
It would be great to have a button on function definition blocks that allow them to be 'collapsed' and 'expanded', i.e. so that we could choose not to see all of the blocks in the code in the function (just the function name). Then all functions could be compactly grouped together on screen. 
Right now a large program can become very hard to manage due to the sheer number of blocks. Creating functions is very useful for managing code and making it readable, however it doesn't necessarily reduce the number of blocks (unless the function is called more than once). Having said that, the nature of a function is that it is self contained, i.e. typically one is created and then subsequently called without necessarily considering all of the functions contents. This jibes with the proposed feature, i.e. once we create a function we should then be able to put this code to the side (& collapse it), and focus on the code calling the functions. 
Please let me know if this request is unclear, hopefully it is not too difficult to implement and would be game changing for large programs.

**Comment by abchatra** [comment]
Implemented and will come in the next release.

**Comment by philgolden** [comment]
Thanks so much for doing this!!!!
