### ISSUE TITLE
Tab opens instead of page dropping to defined header

### ISSUE THREAD

**Issue by ashaltu** [Microsoft/pxt#4534]
When creating a .md file and referencing a header later on in the file, a new tab is opened and then it goes down to the header instead of automatically scrolling down on the same tab

![openedtab](https://user-images.githubusercontent.com/10238372/42398403-94175480-811e-11e8-9f06-a89d742e5cba.gif)

**Comment by DoctaCloak** [comment]
Working on this ticket.

**Comment by DoctaCloak** [comment]
Any idea where I should be looking in the codebase for this?  @ashaltu

**Comment by riknoll** [comment]
@DoctaCloak I think you want `pxtlib/docsrender.ts`

**Comment by DoctaCloak** [comment]
Thank you!  @riknoll  😃
