### ISSUE TITLE
Microbit Update Blog Post

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#4545]
Hi Galen,

Can you prep a blog post for me?  Would like to release this week.  
All files are located here: https://1drv.ms/f/s!AmMIW5Hxi0RtgZEk7l1tOG8WhWDEow 

Need the following to happen before posting:

- [x] Change URL from **https://makecode.microbit.org/v1** to **https://makecode.microbit.org/beta**
- [x] Create a banner (reuse app banner) on the current editor advertising and linking to beta ("Try the MakeCode Beta update!")

**Comment by abchatra** [comment]
Waiting for https://github.com/Microsoft/pxt-microbit/issues/956

**Comment by abchatra** [comment]
Done
