### ISSUE TITLE
Setting Brightness of Sprites only works after plotting any led with a brightness != 255

### ISSUE THREAD

**Issue by gerhofer** [Microsoft/pxt#4549]
**Describe the bug**
Setting Brightness of Sprites only works after plotting any led with a brightness != 255

**To Reproduce**
1. Go to https://makecode.microbit.org/_DzwiTUbCeJHo
2. Select the function brightnessDoesNotWork 
3. The Sprite still has brightness 255.
4. Select the function brightnessDoesNotWorkEither. 
5. The Sprite still has brightness 255. 
6. Select the function brightnessDoesWork. 
7. The Sprite now has brightness 10. 

**Expected behavior**
Setting brightness of a sprite requires only the Sprite.setBrightness block.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by abchatra** [comment]
Microbit bugs needs to be filed against https://GitHub.com/Microsoft/pxt-microbit. This is an incorrect repo. Please open the issue there.
