### ISSUE TITLE
load apptarget via javascript file

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#456]
We load the appTarget information via a REST call to the API ( https://github.com/Microsoft/pxt/blob/60b6e7646edd9789a77b82eb133f56ed0d165fbc/webapp/src/package.ts#L19 ). To enable better offline support, we should load the apptarget via a target.js file.

- [ ] update buildtrg command to generate target.js alongside with target.json. target.js should be equivalent to setupAppTarget
- [ ] include target.js in index.html, run.html, docs.html. 
- [ ] update embed.js file list
- [ ] remove setupAppTarget
- [ ] add target.js to app manifest

**Comment by abchatra** [comment]
@guillaumejenkins - FYI

**Comment by pelikhan** [comment]
This is done.
