### ISSUE TITLE
Requesting to contribute

### ISSUE THREAD

**Issue by DoctaCloak** [Microsoft/pxt#4584]
Hi pxt team, I spoke briefly with @pelikhan and he suggested that I open an issue here. 

I am new to the project and was wondering if there was a particular area that could use some loving?

Particularly for good-first-issue PRs.

**Comment by riknoll** [comment]
Hey @DoctaCloak we welcome contributors! I've just created a "Good First Issue" label and added it to a few issues on this repo so feel free to check those out.

**Comment by riknoll** [comment]
Also, if at any point you find gaps in our developer documentation (and there are quite a few) we would really appreciate it if you open an issue or a PR to fix it. You can find those docs at makecode.com/docs

**Comment by DoctaCloak** [comment]
Awesome, I'm on it.  Thank you @riknoll !
