### ISSUE TITLE
The iframe in controller.html cannot be loaded

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/pxt#4609]
**Describe the bug**
The iframe in container.html cannot be loaded.

**To Reproduce**
1. Run the commands below
```
git clone https://github.com/Microsoft/pxt.git
git clone https://github.com/Microsoft/pxt-microbit.git
cd pxt
npm install
npm run build
cd ..
cd pxt-microbit
git checkout v1
npm link ../pxt
npm install
pxt serve
```
2. Go to controller.html

**Expected behavior**
The index page is displayed in the iframe

**Screenshots**

![pxt-controller-black](https://user-images.githubusercontent.com/8416067/44390722-8ca70680-a560-11e8-94ee-2872e365ffd2.png)

**Desktop:**
 - OS: Windows 10 1803 / Ubuntu 18.04 / macOS‎ 10.13.6
 - Browser: Microsoft Edge / Google Chrome

**Comment by riknoll** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/4614
