### ISSUE TITLE
Problem reading out analogue Values from Pin 3, 4 and 10

### ISSUE THREAD

**Issue by fd0cwp** [Microsoft/pxt#4642]
Hi all, 
I am not sure if this is the right location / way to get help for getting reliable analogue inputs from the pins 3, 4 and 10 of the micro:bit using Python. So I just post my problem and hope for answers. 😊
I would like to measure temperatures at different locations at the same time. So I bought the micro:bit starter kit where the temperature sensor TMP 36 is included to gain some knowledge. It went well so I bought 5 more pieces of this temperature sensor and planned to read them out via the analogue input pins 0, 1, 2, 3, 4 and 10. For the pins 0, 1 and 2 it is working quite well now but the pins 3, 4 and 10 return wrong values. I know that these pins are also used for the display somehow, so I switch off the display at the beginning and then continuously read out the pins in a loop and convert the return values to voltages and then to temperature values.
When I have a look at the voltage, for the first thee pins the read out and converted voltage values fit to the values which I can measure directly at the TMP sensor pins. Unfortunately, the last three pins return a lesser voltage. Surprisingly, when I measure it, it is the same as available on the 3V pin (about 3.3V).
When I just measure the voltage at the micro:bit pins without having anything connected to it, the first three pins show about 1.6V. But the other three show about 3.3V. So something is different there. 
I wanted to play around a little bit with the pull up / down resistors, but it seems that Python does not give access to it. Also, I found no way to specify that these pins are now used for input to ensure that they do not output a voltage.
When I similarly implement it in MakeCode as blocks / JavaScript it seems to work correctly. But I cannot use this as I want to make many temperature measurements, collect them and later evaluate them e.g. with MS Excel. For this purpose, I create a file on the micro:bit with open(fileName, 'w') and write the read out and converted values into it to later copy the file to a computer.
Thank you in advance for your feedback!
Best regards, 
Christoph

**Comment by abchatra** [comment]
This is not the right place for microbit issue. @fd0cwp please open the issue in Microsoft/pxt-microbit which repro steps and screen shots.

**Comment by fd0cwp** [comment]
Hi abchatra, Thank you for the quick feedback! I submitted an issue in the other location.
