### ISSUE TITLE
pxt bump introduces additionalFilePaths field

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#4666]
Introduced by https://github.com/Microsoft/pxt/blame/8d89d6aca16759de93a7718b5387ecbd510e309e/cli/nodeutil.ts#L283

**Comment by abchatra** [comment]
This bug needs more information. What is the impact? Is this cleanup issue?

**Comment by pelikhan** [comment]
pxt bump because pxt.json gets modified if it is missing this field.

**Comment by mmoskal** [comment]
Yeah, it just needs to be removed before saving. Will do.
