### ISSUE TITLE
Subdirectory files destroyed with github editing

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#4667]
When editing the pxt-neopixel package, which contains package localization files, we lost all the translations. These files live under _locales/LOCALE/...

This is due to https://github.com/Microsoft/pxt/blob/6e006d120842b2bb8d77818cae16d69438746755/webapp/src/workspace.ts#L531 which deletes all nested files.

**Comment by mmoskal** [comment]
There must be another reason. It's designed, so that the PXT editor only has a subset of files, and it should not overwrite other files. I believe this works for files, but probably not directories.

Will look into this.

**Comment by mmoskal** [comment]
Oh, actually these files are part of `pxt.json`. So I guess the problem is github integration doesn't understand nested files.

**Comment by mmoskal** [comment]
Nah, I will fix it.
