### ISSUE TITLE
Allow for tutorials to begin with blocks already placed 

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/pxt#4682]
When writing multiple tutorials, it can get quite repetitive when you need the same code to start each one. A specific example is creating a sprite that moves around the screen in Arcade. It's about 3 steps to do this and I don't think it needs to be in every tutorial. 

It would be nice if you could insert code that would be placed into the editor automatically when the tutorial starts, similar to how the examples work.

I can see that having code be placed into the tutorial might defeat the purpose of the tutorial, but it would be nice to have the option to place basic code that the user manipulates.

**Comment by abchatra** [comment]
We allow this now.
