### ISSUE TITLE
Comments in an on start block do not appear in javascript

### ISSUE THREAD

**Issue by kevinjwalters** [microsoft/pxt#4684]
Comments can be added to an on start block but they do not appear when converting/flipping to the javascript view.

Reproduction:
1. Make an **on start** block.
2. Put anything in it to ensure it generates some code.
3. Add a comment.
4. Hit the javascript button.
5. Observe absence of comment.

Tested on makecode.adafruit.com (running 3.18.28) and makecode.microbit.org (running 0.19.13) in Firefox 62.0 and Chrome 69.0.3497.92

**Comment by abchatra** [comment]
This is fixed
