### ISSUE TITLE
renderblocks in controller does not work

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/pxt#4709]
**Describe the bug**
TypeScript embedded in a `renderblocks` message and passed from the controller to MakeCode is not rendered in the Block editor.

**To Reproduce**
1. In a pxt target, run `pxt staticpkg` then `http-server -c-1 built/packaged`
2. Open `http://localhost:8080/controller.html`
3. Press "renderblocks"

**Expected behavior**
`while(true){ }` is transformed to blocks, which are then added to the Block editor

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser: Edge, Chrome 69, Firefox 62

**Comment by abchatra** [comment]
Closing old bugs. If this still reproduces please reopen.
