### ISSUE TITLE
Javascript code lost by editor switching modes unprompted

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#471]
This is a difficult case to track down because I haven't yet reproduced it. I'm sticking a report here in the hope that someone realises what was going on.

I had 2 tabs open in my browser when I finished work last night
* Script1 - Blocks
* Script2 - Javscript
* Script3 - Blocks

I shut my computer. On restarting work this morning (computer was sleeping, not shut down), initially things were okay, but after activating the tab for Script3 (I *think* thats what caused it....) *it* loaded in JS mode, and when I returned to script2, it reactivated in Blocks. 

I saw the green 'Project Loaded' notification
![image](https://cloud.githubusercontent.com/assets/147113/19304091/493b6990-9063-11e6-9c32-0df854ebaef1.png)

As a result, functions in Script2 were 'lost' when returning to JS mode. Furthermore I couldn't retrieve saved versions of the script because the 'latest' code had overwritten the older code in my 'saved' program.

Unlike when trying to manually switch between modes, I *did not* see a dialogue warning me about this. 
![image](https://cloud.githubusercontent.com/assets/147113/19304149/76710faa-9063-11e6-86df-ae1f1f62669e.png)
^ This was never shown, but somehow the project rendering still changed.

There are two things here

1) The mode shouldn't ever switch magically (though I can't reproduce it yet, I'm sorry)
2) Even if the mode does switch, I should be able to recover the last 'JS' version.

**Comment by pelikhan** [comment]
@microsoftsam started working exactly this yesterday.

**Comment by abchatra** [comment]
@microsoftsam This change is merged right? If yes close.

**Comment by microsoftsam** [comment]
I haven't managed to reproduce this data loss yet. The issue I fixed that @peli was referencing is in now we load the editor, allowing us to load the JavaScript editor when the code was written in that editor. I suspect the fix would solve some of the problems that lead to data loss, but not necessarily what @jaustin is describing. 
Closing for now, until we get a repro.
