### ISSUE TITLE
Pxt target icon in docs page after staticpkg is not displayed properly

### ISSUE THREAD

**Issue by dwaw18** [microsoft/pxt#4716]
**Describe the bug**
Icon for custom pxt target in docs page is not displayed properly ("GET /docs/reference/docs/static/logo.svg" Error (404): "Not found")

**To Reproduce**
1, Make sure there is defined **docsLogo** property in **appTheme** section of pxtarget.json file.
2. Run pxt staticpkg and http-server -c-1 built/packaged in custom pxt target
3. Go to http://localhost:8080/docs/blocks/loops/repeat.html
4. Icon on top bar of page is not present.

**Expected behavior**
Icon of target in docs page should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/40686407/45943569-2a21aa00-bfe7-11e8-863d-37e472f1f687.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 69.0.3497.100

**Additional context**
pxt-core version: 4.0.5

**Comment by abchatra** [comment]
Closing old bugs. If this still reproduces please reopen.
