### ISSUE TITLE
Radio only receives 5 events unless you consume data from the event

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#472]
The following script will only ever receive 5 micro:bit radio events. It will continue to operate (can be tested by using button A to decrement the number).

![image](https://cloud.githubusercontent.com/assets/147113/19306293/e4091bee-906c-11e6-8f9a-f1c252369503.png)

On the other hand, adding something that consumes the received data:
![image](https://cloud.githubusercontent.com/assets/147113/19306333/0f6781cc-906d-11e6-818c-441125916a0c.png)

allows the receipt of data to continue indefinitely.

My guess is that this is a buffer getting full. Should we be throwing away old data at the end of the handler?

**Comment by jaustin** [comment]
Also note: pxt doesn't simulate this '5 event limit'

**Comment by riknoll** [comment]
I don't know what the buffer limitations are, but my first thought would be that the "on data received" block should consume that data. That would be more in line with the block I proposed in #465

**Comment by abchatra** [comment]
@riknoll Does your radio changes address this issue?

**Comment by riknoll** [comment]
Sort of. My change does not affect the size of the buffer, but `onDataReceived()` is now deprecated and its replacement, `onDataPacketReceived()`, does consume packets so you shouldn't run into the same issue with the code above. The buffer is part of the DAL, so I don't think we can control how big it is easily.

**Comment by pelikhan** [comment]
It does partially solve it because it guarantees to consume at least 1 event.

You can run into the issue of loosing packets if you onDataPacketReceived handler consumes packets slower than they are filled up. In essense, you could be the victim of a DoS attack like.

To be correct, a student would have to poll "get next packet" multiple times within the "on data received" event to consume the queue but that's quite confusing.

**Comment by jaustin** [comment]
I think it's acceptable to drop packets when you're consuming more slowly
than the buffer is filling up, so I believe the fix here is acceptable.

Furthermore, guaranteeing that the data consumed inside the handler is the
data associated with the packet that caused the handler to be triggered (IE
by making them available as named variables, rather than as the return
value of functions that could be called multiple times) avoids a common
failure mode.
