### ISSUE TITLE
How to create the final executable?

### ISSUE THREAD

**Issue by ColinEberhardt** [Microsoft/pxt#4734]
OK, this is probably a dumb question, but I'm struggling to work this out. I'd like to use PXT to create simple workflows that I intend to execute on AWS (as a lambda function).

Following the instructions, I have the pxt-sample up and running and can see how to add my own APIs, and construct a simulator. However, how do I go about executing the projects people create within the 'real' environment?

Or is this something that is outside of the scope of what PXT is designed to do?

**Comment by abchatra** [comment]
Can you elaborate what do you mean real environment? There are two pipeline for the code created by user. One gets compiled to arm assembly and runs on the microcontroller. Other gets converted to javascript bytecode which runs on the simulator which understands these special bytecode.

**Comment by ColinEberhardt** [comment]
OK, happy to clarify. To provide more information, I'm looking to create an online editor that allows people to define workflows based on HTTP webhooks, with the goal being to allow people to create complex automations.

For example, when the outside temperature drops below 10degrees, send me an email, and tweet a message.

I'd appreciate any pointers - it does feel like this is a little incompatible with PXT. Although I'd be happy if I can use some of the pieces. One option would be to just use Blockly, but your TypeScript support is something I'd love to have :-)

**Comment by pelikhan** [comment]
We are working on being able to compile code down to node.js script. Would that be something useful for you?

**Comment by ColinEberhardt** [comment]
Yes that would be really useful.

Just FYI, I've changed my approach to use Blockly directly. Although I certainly miss the TypeScript support!

**Comment by pelikhan** [comment]
I'll close this but we'll keep the scenario in the back of our minds.
