### ISSUE TITLE
Makecode + EV3 File Transfer Issues

### ISSUE THREAD

**Issue by grahamict** [Microsoft/pxt#4737]
**Describe of issue**
We have Lego Mindstorms EV3 robots, and we have just updated the firmware to V1.10E
We normally connect these robots to OSX, Windows and Chromebooks using the EV3 Software
I wanted to try makecode as I like the interface and it seems easy judging by the available tutorials
However
After a program has been made and downloaded using makecode (I have tried with OSX, Windows and Chromebook), then dragged and dropped to the brick using Finder/Explorer/File Manager, the first thing that happens is the EV3 disconnects. It then reconnects after about 10 seconds, the file is present on the device (when looking through Finder/Explorer.
However
The file does not appear when searching for it on the brick itself.

What am I doing wrong?

![screenshot1](https://user-images.githubusercontent.com/43617985/46100771-9f84aa80-c1a0-11e8-844b-e49e3de7156e.png)
![screenshot2](https://user-images.githubusercontent.com/43617985/46100772-9f84aa80-c1a0-11e8-94fe-83b0b4952d83.png)

**Comment by abchatra** [comment]
@grahamict When you copy the .uf2 file brick is automatically flashed with that program. In the above program if you press enter does the motor run. If yes program is already flashed and it is currently running. 

Also you should see your program (Untitled) in BrkProg_SAVE folder.  Do let us know if I have answered your question.

**Comment by grahamict** [comment]
Hi @abchatra For an inexplicable reason it started to work today.

The files now show up on the brick, and they are able to run!

Thanks for getting back to me.

**Comment by abchatra** [comment]
Thanks for confirming

**Comment by mcquaid1981** [comment]
I am now having this same issue. No programs show up on the brick and it says the ev3 has been disconnected.

**Comment by abchatra** [comment]
@mcquaid1981 Can you elaborate your issue?

**Comment by abchatra** [comment]
Also ev3 issues are filed here: https://github.com/microsoft/pxt-ev3

**Comment by mcquaid1981** [comment]
So I am using the website makecode.com to program. I get an uf2 file, and
drag it into the ev3 which immediately indicates that the ev3 has been
improperly ejected. Nothing shows up on the brick itself.
Thanks for the quick response,
Rob

**Comment by abchatra** [comment]
Please give information on Operating System, browser, firmware version.
Write a simple one block program
![image](https://user-images.githubusercontent.com/6107272/64445989-8d87d900-d08c-11e9-9c9c-d8810c6df5e7.png)
After eject does ev3 brick have this program (a.k.a show the smiling face)?

**Comment by pelikhan** [comment]
By default the program does not display anything, maybe try to add a Show image block in on start to make sure it is running.
Could you share your program?

________________________________

**Comment by mportsmo** [comment]
I am having the same issue on my MacBook Pro MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) running 10.15.4 and my MacBook Pro (Retina, 13 inch, Late 2013) running 10.12.6. 

I drag lego-test.uf2 to the EV3 and the EV3 disconnects and goes to a blank screen.  Upon hitting the back button it reconnects but the lego-test file isn't there and MakeCode can't download. 

I have tried two different EV3 bricks (both updated using EV3 Device Manager to 1.10E.  

Any suggestions welcome!

**Comment by abchatra** [comment]
@mportsmo Can you see if your files still in the files explorer in the ev3? 

MakeCode runs the file as soon as you flash it. So you can add an mood block and see if you see this on the screen?
![image](https://user-images.githubusercontent.com/6107272/82528449-9ec72780-9aed-11ea-878c-46cd09b39103.png)
