### ISSUE TITLE
Greenscreen feature

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#4738]
![greenscreen](https://user-images.githubusercontent.com/4175913/46113062-c1caf800-c1a1-11e8-8074-3f0d771426fc.png)

## Description

Green screen overlays the video stream of a web cam in the code editor. It allows to do a live hardware demo and show the code at the same time.

## How to enable it?

Go to the gearwheel menu and press "Green Screen On"

If you cannot see that button and you editor supports this experiment, go to **About**, then click **Experiments** and **Green Screen**. If you cannot see this card, your editor does not support yet this feature.

## Feedback

Do you use this feature? Is there something you'd like to change? Did you encounter issues? Please drop a comment on this issue to send us your feedback.

**Comment by CleoQc** [comment]
the green screen feature is zoomed in and I can't see how to control it.
For example, here's what I'm getting:
![noroomtomove](https://user-images.githubusercontent.com/4965628/47531404-8f351d80-d87b-11e8-9bea-7d6ff7158c7e.png)
On my biggest screen, I get:
![biggestres](https://user-images.githubusercontent.com/4965628/47531420-9a884900-d87b-11e8-8992-f36a44541b32.png)
This is what the camera actually sees outside of makecode:
![outsideofmakecode](https://user-images.githubusercontent.com/4965628/47531436-a6740b00-d87b-11e8-83f1-b3d7dd911ae1.png)

Note the image reversion too and the focus is good here. (Not in makecode)

**Comment by abchatra** [comment]
This is the editor now.
