### ISSUE TITLE
Print Code feature

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#4740]
![print](https://user-images.githubusercontent.com/4175913/46114834-3eada000-c1a9-11e8-92f6-27a77657203d.png)

## Description

Print the blocks or JavaScript from the current project.

## How to enable it?

Click on the gearwheel and click "Print Code"

If you cannot see that button and you editor supports this experiment, go to **About**, then click **Experiments** and **Print Code**. If you cannot see this card, your editor does not support yet this feature.

## Feedback

Do you use this feature? Is there something you'd like to change? Did you encounter issues? Please drop a comment on this issue to send us your feedback.

**Comment by martinwork** [comment]
Typo: grearwheel

**Comment by abchatra** [comment]
implemented

**Comment by abchatra** [comment]
Enabled in most of our editors.
