### ISSUE TITLE
"Popped out" documentation page does not print

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#4743]
**Describe the bug**

A documentation that was opened by poping the sidebar is not allowed to print.
![image](https://user-images.githubusercontent.com/4175913/46156627-bd005580-c22e-11e8-809e-e9d4016cba27.png)

Copy pasting the URL into a new tab fixes the issue.

**To Reproduce**
1. Go to block editor
2. Click on Reference
3. Click on pop out
4. Click on print icon

**Expected behavior**
It prints

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 69

**Comment by abchatra** [comment]
Should be fixed in the latest
