### ISSUE TITLE
Show console when rendering the simulator in documentation

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/pxt#4779]
When showcasing code, it would be helpful to be able to use the console to show how the code is running.

With similar functionality to with the editor in that the console would only show if something was going to be logged.

The current work around at least for arcade is to use game.splash, but that can get messy with long strings and multiple function calls. That also only works for arcade. I imagine if Script courses are developed for other pxt targets, it would be very helpful to show the console.

**Comment by abchatra** [comment]
Won't fix
