### ISSUE TITLE
platformio instead of yotta

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#479]
platformio

**Comment by mmoskal** [comment]
The build machine is Linux. Not sure what's the story there.

**Comment by tballmsft** [comment]
https://www.arduino.cc/en/Guide/Linux

**Comment by tballmsft** [comment]
Still investigating: http://playground.arduino.cc/Learning/CommandLine

**Comment by tballmsft** [comment]
platformio looks like the way to go - I am working with it now - more later.

**Comment by mmoskal** [comment]
Good! We need flashing and compilation. Also, the flashing we will probably want to rewrite in node.js (it's usually some simple protocol).

**Comment by pelikhan** [comment]
I believe Lancaster has done work there already.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
@mmoskal Did we move to platformio with the new backend?

**Comment by mmoskal** [comment]
the backend supports both yotta and platformio; we do not use platformio for microbit though

**Comment by tballmsft** [comment]
Thanks, Michal.
