### ISSUE TITLE
Show round and hexagonal blocks in documentation

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/pxt#4791]
It would be nice to be able to showcase specific functions and values in documentation without having to put in a whole line of code/block.

For example:
Instead of having to do
![feature-request-before](https://user-images.githubusercontent.com/13285164/46635056-f4f97980-cb07-11e8-9768-2e0ddc4d67dd.png)

allow for 

![feature-request-after](https://user-images.githubusercontent.com/13285164/46635070-fb87f100-cb07-11e8-8455-f3c88e461c8b.png)

Probably not a huge priority, but it would be nice.

**Comment by pelikhan** [comment]
We used to have a “block” fenced code section that would display a single expression. Might be broken.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jwunderl** [comment]
That is still there I think: \`[game.splash("hello")]\` works. It only seems to work if the value would become a full block, though; this is asking for \`[true]\` and \`[0]\` to become a hexagonal true and round 0 blocks instead of a grey javascript block.

**Comment by pelikhan** [comment]
I think decomposing expressions for docs broke when we introduced grey blocks. We should fix this.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
Closing old bugs. If this still reproduces please reopen.
