### ISSUE TITLE
Add event for mixpanel

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#485]
Any edit (block or typescript)

**Comment by Jaqster** [comment]
[ ] test that a “edit” tick is in place and working (across both editors)
[ ] test that we don’t accidentally log an “edit” event when initialize the editor (or even worse double count)
Ultimately, want to count number of 'active sessions' = sessions with at least 1 edit event

**Comment by abchatra** [comment]
We do have edit event for both block or typescript.

**Comment by pelikhan** [comment]
We have autorun which also bundles the current editor that triggered the autorun. Logging indiviual "edits" is too expensive.
