### ISSUE TITLE
Tutorials start in a different pane

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#4960]
If you go to https://maker.makecode.com, the tutorial popout a new page.

Regression from https://github.com/Microsoft/pxt/commit/1e281b0ee2928d0695f8d83056ec495ba642dc0d

**Comment by samelhusseini** [comment]
Accidentally committed instead of PR'd. Here's the fix: https://github.com/Microsoft/pxt/commit/fa5e38e2dce5505a3351ff5169c337d4f3f5487b

**Comment by pelikhan** [comment]
Cool thanks
