### ISSUE TITLE
docs images not showing after setup

### ISSUE THREAD

**Issue by johnstonmatt** [microsoft/pxt#5021]
**Describe the bug**
Installing this repo and dependencies, then packaging them and hosting them as a static bundle  results in images not loading. The markdown in `codecard` s points to `/static/mb/....` but all of those paths need prefixing with `/docs` to point to the correct images.

**To Reproduce**
1. clone and install
2. run `pxt staticpkg` 
3. host the `built/packaged` directory
4. See images not showing in browser

**Expected behavior**
Visible thumbnails

**Screenshots**

![screen shot 2018-11-16 at 7 07 47 am](https://user-images.githubusercontent.com/5455542/48618015-667de080-e96e-11e8-9dea-3eb18f38e748.png)

the 'heart' thumbnail has a path prefixed with /docs, and it loads properly

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 70

**Comment by samelhusseini** [comment]
It's interesting that the first one shows up.

**Comment by FranklinWhale** [comment]
This issue also affects images used by the simulator.

**Comment by sunt89** [comment]
I have the same problem. Is there a solution now?

**Comment by dr-data** [comment]
> this is still a problem, I will attempt to solve it, and report back with results

Any feedback?

**Comment by abchatra** [comment]
This is fixed.
