### ISSUE TITLE
Dismiss cookie banner when interacting with blocks

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#5023]
Open any shared script in an incognito window and interact with the shared blocks. 
You can: 
- select them 
- drag them around
- edit fields

and the cookie banner won't be dismissed..

**Comment by abchatra** [comment]
This is by design. Only drag of new block dismisses cookie. Done intentionally to avoid more ways to dismiss cookie. 

Shouldn't be a big issue as users see cookie once (in home screen) and new project clears it.
