### ISSUE TITLE
Project Manager feature

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt#5061]
## Description

The feature lets you manage your projects. You can select one or a group of projects, and complete the following actions: 
- Delete (supports multi-select)
- Duplicate a project
- Edit / Open a project

You can view your projects in a grid view or a list view, and can sort them either by name or last modified (ascending and descending).

## Try it out

The feature is currently only enabled on a few of the editors. Try it out on Arcade: 
Go to: https://arcade.makecode.com/
then click on **My Projects**.

## Known issues

N/A

## Feedback

Do you use this feature? Is there something you'd like to change? Did you encounter issues? Please drop a comment on this issue to send us your feedback.

**Comment by pelikhan** [comment]
It would be nice to support the usual keyboard shortcut / combos. Ctrl+select, Shift+select, up/down keys.

**Comment by pelikhan** [comment]
In mobile view, show smaller cards

**Comment by samelhusseini** [comment]
Currently it supports Ctrl + select and Shift + select (clicks) but not keyboard up / down keys to select multiple using a keyboard.

**Comment by ChaseMor** [comment]
It would be nice if GitHub repos showed the GitHub logo like they do in the carousal.

**Comment by ChaseMor** [comment]
It would also be nice if you could rename projects without opening them.

**Comment by abchatra** [comment]
This is in the editor now.
