### ISSUE TITLE
Statement blocks as inputs to reporter-style blocks

### ISSUE THREAD

**Issue by NoobDoesMC** [microsoft/pxt#5092]
![screenshot 2018-12-13 at 02 38 17](https://user-images.githubusercontent.com/29206206/49912470-33057780-fe82-11e8-99e2-3af1a50b9a00.png)
![screenshot 2018-12-13 at 02 43 30](https://user-images.githubusercontent.com/29206206/49912471-339e0e00-fe82-11e8-9c3c-a594c720913f.png)

```ts
//% blockId=gargle block="return one"
export function setBlock(sink: RefAction): number {
  return 1;
}
```

I am expecting it to look something more like Berkeley's (Snap):

![screenshot 2018-12-13 at 02 50 49](https://user-images.githubusercontent.com/29206206/49912517-4f091900-fe82-11e8-998e-b27dba505525.png)
![screenshot 2018-12-13 at 02 51 22](https://user-images.githubusercontent.com/29206206/49912518-4fa1af80-fe82-11e8-80e6-f1acfedd94ce.png)

**Comment by abchatra** [comment]
We have return statement in the PR.
