### ISSUE TITLE
clicking on a opened category name should close it.

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#511]
Somehow unintuitive that categories don't close when clicking on the name again. Reported by Joe.
- click on "basic"
- click again
  expected: should be closed.

**Comment by abchatra** [comment]
I believe the current experience is better. If not it will become hard to discover. We need designer to validate the proposal. I am closing this for now as we have no plans to change the behavior.

**Comment by pelikhan** [comment]
This

**Comment by pelikhan** [comment]
All other menu items in the web app behave in that way (click toggles). We should fix this.

**Comment by abchatra** [comment]
Fixed
