### ISSUE TITLE
touchdevelop generated hexfile not importing into PXT

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#515]
Repro: 

1. Get script /xjuzjz from www.microbit.co.uk and compile to hex file 
2. Drag and drop hex file to codethemicrobit.com

**Comment by mmoskal** [comment]
I did some investigation (David Whale was asking about this). The file is converted correctly, but the .ts file in the project is not overridden. Also, the import should not create main.blocks file, or at least take the user to the .ts file after import.

**Comment by pelikhan** [comment]
Fixed.
