### ISSUE TITLE
Attach to the right touch events in pointer event utils

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/pxt#5205]
We're currently attaching to mouseup for up, and touchend for leave in out pointer event util.
This works most of the time, but when an interaction is cancelled you don't get a mouseup event on touch devices according to https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent

I think the solution is to use touchend for up, and touchcancel for leave. 
I tried tracing this back, but it looks like it's been there for when the util was introduced in https://github.com/Microsoft/pxt/commit/e73516a2c51dcb72c35ce9b26cc1332e072786e0

In Blockly we use touchend and touchcancel for mouseup, so someone should investigate this, but I think the root cause is somewhere in this code. 

https://github.com/Microsoft/pxt/pull/5203 is just one example that we ran into where we've had to hack it to subscribe to the correct events.

**Comment by abchatra** [comment]
Fixed
