### ISSUE TITLE
pxt-ev3 repo -> public?

### ISSUE THREAD

**Issue by jononi** [Microsoft/pxt#5217]
is https://github.com/Microsoft/pxt-ev3/ ever going to be public in the future?

**Comment by abchatra** [comment]
Yes going open source is the intent of the MakeCode team. I don't have a timeline at this point of time. What is your use case?

**Comment by jononi** [comment]
- make changes and improvements to the ev3 package (current files can be accessed but not edited)
- write code and compile it outside of a browser
- use cli or even better vscode to build uf2 files and store them locally on disk

**Comment by Kurtoid** [comment]
Definitely want to try the steps here: https://makecode.mindstorms.com/offline

But dead link to ev3-pxt

**Comment by abchatra** [comment]
If you are interested in offline: Here is the offline app: https://makecode.mindstorms.com/offline-app

**Comment by jononi** [comment]
thanks @abchatra  for the offline app, but we are still waiting for the local building option, using VSCode for example. The link posted by @Kurtoid  refers to that option but doesn't mention that's it's still not publicly available.
