### ISSUE TITLE
Step-by-step instruction how to install MakeCode for midstorms ev3

### ISSUE THREAD

**Issue by mav1** [Microsoft/pxt#5222]
Hello. Can't find instruction how to install own webserver-based MakeCode for ev3, as it is at https://makecode.mindstorms.com/

I have downloaded PXT and Node, than run (inside of a pxt directory):

_npm install
npm run build
npm install -g pxt_

Then i run command "pxt serve" and all i can see is:

https://ibb.co/k2Jh0F2

But how can i use MakeCode for ev3?

**Comment by abchatra** [comment]
PXT is for EV3 is not public yet. You can't do this today. What is your use case?

**Comment by mav1** [comment]
I want to compile stand-alone version of Make Code for ev3, to use it on my computer without internet connection
