### ISSUE TITLE
Changing installed packages to make PXT compatible with Node 10.

### ISSUE THREAD

**Issue by muruges95** [microsoft/pxt#5249]
# Feature request template

**Is your feature request related to a problem? Please describe.**
As of now, the recommended Node environment to build PXT in is Node 8.x. We are upgrading all of our tools built around PXT from Node 6.x, because, Node 6.x ends-of-life in April 2019. The available LTS versions out there are 8.x and 10.x. Since Node 8.x ends-of-life in December 2019, ideally we would like to move to Node 10.x LTS. 

The problem now is that upon carrying out `npm install` while in a Node 10.15 LTS environment in the pxt root directory, we are experiencing a number of errors in the execution of the command. In particular, there seems to be problem with installing the `sqlite` and the `leveldown` packages with Node 10. The same errors occur if we attempt to run `npm link ../pxt` in our target. In addition, there are a couple of deprecated packages that show up as warnings during the install process.

**Describe the solution you'd like**
We would appreciate it if the packages used could be changed to work with Node 10.x LTS so that we could change our build environment to Node 10.x. We would also appreciate it if the deprecated modules could be upgraded in case they were patched for greater performance or improved security.

**Describe alternatives you've considered**
The alternative would be to just make a smaller jump and move to Node 8.x. However, given that it is also going to end-of-life this year, we feel that it is not worth the effort to revamp our build process twice within such a short span of time. 

**Additional context**
These are some of the error messages we observe on doing `npm install` or `npm link ...`:
![image](https://user-images.githubusercontent.com/14848271/52088177-09063280-2560-11e9-8e9e-32777f003f9d.png)
![image](https://user-images.githubusercontent.com/14848271/52088211-24713d80-2560-11e9-9aa1-e83c0a2bbdb2.png)
![image](https://user-images.githubusercontent.com/14848271/52088033-c3496a00-255f-11e9-8eff-9b93a7da6017.png)

**Comment by pelikhan** [comment]
@darzu FYI

**Comment by abchatra** [comment]
Closing old bugs. If this still an issue let us know.
