### ISSUE TITLE
Is there a way to initialize a Serial interrupt with arbitrary strings and not just the available delimiters?

### ISSUE THREAD

**Issue by bsuwal** [Microsoft/pxt#5252]

**Comment by pelikhan** [comment]
It only supports single ASCII letter delimiters currently.

**Comment by bsuwal** [comment]
Thanks a lot! How do you add custom delimiters to the list?

**Comment by pelikhan** [comment]
You can pass a number and cast it to “delimiters”

**Comment by pelikhan** [comment]
What delimiters do you need and for what editor?
