### ISSUE TITLE
broken link: "Get Minecraft: Education Edition >" link on Getting Started page leads to 404

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt#5268]
Repro:
1. Go to https://www.microsoft.com/en-us/makecode/get-started?activetab=pivot1:primaryr4
2. Click on "Get Minecraft: Education Edition >" (links to https://education.minecraft.net/how-it-works/tech-specs/)
3. notice that resolves to "https://education.minecraft.net/error"

**Comment by Jaqster** [comment]
Thanks for reporting Daryl!  Awesome testing, and you haven't even started yet :-)
Just reported to the Web Team.

**Comment by abchatra** [comment]
fixed
