### ISSUE TITLE
Compiling C++ code never succeeds

### ISSUE THREAD

**Issue by xobs** [Microsoft/pxt#5286]
I'm trying to make modifications to `pxt-chibitronics`, but the page just sits there shaking its head at me, giving me the message `Compiling (this may take a minute)...`.  This process never finishes.

To make sure it wasn't a problem with `pxt-chibitronics`, I checked out `pxt-microbit` and made a small change: I modified `pause(int ms)` to add 5 to the sleep:

```c++
    /**
     * Pause for the specified time in milliseconds
     * @param ms how long to pause for, eg: 100, 200, 500, 1000, 2000
     */
    //% help=basic/pause weight=54
    //% async block="pause (ms) %pause" blockGap=16
    //% blockId=device_pause icon="\uf110"
    //% pause.shadow=timePicker
    void pause(int ms) {
      fiber_sleep(ms + 5);
    }
```

After making this change, the `pxt serve` command gets stuck at `polling C++ build https://makecode.com/compile/32b1f6c2c7205acc05d9b725a9857b1fb0a6ebac89291615f6aaf756fbaa155d.json`

The `README.md` file suggests that I add `-yt` to turn on compilation for local files, but that doesn't work (see https://github.com/Microsoft/pxt-chibitronics/issues/243)

**Comment by JeffBrilliantLabs** [comment]
Same thing happening to us as of week of Feb 18th... working with the microbit target and where we've successfully added many cpp files in past as of last week after we add the files to pxt.json we can never get passed the polling of this file: 

https://makecode.com/compile/71f384ebc95a66a7701d5cabfd61d7f800c2a60c3e6e43efbc4032d89c03a13c.json

Nothing builds because of this, even a new blank cpp file added to pxt.json will prevent building locally or for the web.

**Comment by titimoby** [comment]
I wanted to explore local setup for pxt-arcade.
I followed Readme instructions and ended up with the same king of issue, in my case:
`polling C++ build https://makecode.com/compile/7909d2b19177d00803f4095f2a6b7a83d087be019e6e10fda3ee549710ae4e2b.json
`

**Comment by titimoby** [comment]
To be more precise, I'm working with Pxt-arcade.
https://github.com/Microsoft/pxt-arcade

When following the "Local Dev setup" involving 3 folders with link, I ended with the polling loop.

If I follow the "Local server setup" with only pxt-arcade project cloned, it works.

**Comment by abchatra** [comment]
@xobs This should be fixed now. Can you please try and let me know?

**Comment by JeffBrilliantLabs** [comment]
Awesome stuff!  Thank you :) :) :) I was just about to share that it didn't work as the first polling of C++ build https://makecode.com/compile/589009bbb6244d6397adc3e71084e19f4ced7600862d90e21745c789a4b5856e.json took a very long time and then it tried polling a second time and after a total of maybe 20-25 seconds it finally succeeded!

Thanks again!

**Comment by xobs** [comment]
@abchatra I'm able to run `pxt serve` again now.  Thanks for the fix.

**Comment by JeffBrilliantLabs** [comment]
Is anyone else having issues this evening with this again?

**Comment by xobs** [comment]
@JeffBrilliantLabs You're right, it's not working again.

Also, would it be possible to enable non-cloud compilation, so we don't have this problem in the future?  (See https://github.com/Microsoft/pxt-chibitronics/issues/243)

**Comment by pelikhan** [comment]
In the latest pxt builds, you can do “pxt buildtarget —local” to get a local build

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xobs** [comment]
@pelikhan That generates a local .hex file, but that file doesn't get used by `pxt serve`.  However, there does appear to be a command `pxt serve --local` (maybe an undocumented alias for `pxt serve --localbuild`?) that does work.

The documentation should be updated to mention this flag.

**Comment by pelikhan** [comment]
Right this is an older version of the CLI and might not have all the aliases.

**Comment by zjuxumang** [comment]
I have been stuck on this issue for a whole day, and yesterday (February 28) seems to be normal. There are no results in polling for a few minutes, and the network communication message shows an error 404 when connecting to makecode.com. Local compilation is stuck on the mbed-classic package, and the connection is broken each time it is halfway through. Hope to solve this soon,thanks a lot!

**Comment by abchatra** [comment]
compile service is not for active C++ development. Please use local build instructions for local builds. It can't handle large amount of requests. It should be back up now.
