### ISSUE TITLE
support for (...args: number[]) arguments

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#529]
Functions which variable numbers of argument should use the mutators in blocks. This feature is important for CSV support in the micro:bit file system.

**Comment by tballmsft** [comment]
@pelikhan @riknoll -  is this still needed?

**Comment by pelikhan** [comment]
Would be nice for log-like apis variable args but we can use "join" now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
Won't fix for now.
