### ISSUE TITLE
Style new docs header

### ISSUE THREAD

**Issue by toledoal** [microsoft/pxt#5290]
Hello! Here is the new proposed style for the Docs header.    

In the sample image we can see icons to the right (we will set a placeholder for up to 4 icons) even though we will not put any icons right now. 

![image](https://user-images.githubusercontent.com/704682/53453473-ccf0b100-39e9-11e9-803b-21cb1e5b0681.png)

The idea is to modify the following files to achieve this: Docfiles/docs.html​, Docsfiles/header.html and theme/themes/docs.less

**Comment by pelikhan** [comment]
- what will it look like in mobile?
- what about the current table of contents?

**Comment by toledoal** [comment]
For mobile we are still designing a proposal mainly because of the space of the "breadcrumb" control. 

![image](https://user-images.githubusercontent.com/704682/53453980-61a7de80-39eb-11e9-95ab-a5725a9e270f.png)

For the TOC this is how it will look like. 

![image](https://user-images.githubusercontent.com/704682/53454050-961b9a80-39eb-11e9-8952-1ae0323be09d.png)

(Notice the filter box is actually the current search box). 

Let me prepare a new set of clean design screenshots and I'll add those here. :)

**Comment by toledoal** [comment]
Hello! Here is an update on the Docs Design. 

This one is the desktop version: 

* We are proposing a main header that unifies the experience in Docs and in Editor
* Since the Search box gives results globally and not only about docs we are currently proposing placing the box in the top right. 
* Even though we are not placing a filter box for the TOC content we might consider it later. 
* The Print and Language buttons are placed in what we call an action "area" or right "row" where we could place other content actions like "share" 
* The logo and accent color still be defined in "appTheme" configuration. We can discuss later if we would need other configuration options, like a color palette or "target" specific styles.

<img src="https://user-images.githubusercontent.com/704682/53532749-b61b8e80-3abd-11e9-9627-8d3302d6fb99.png" width="700">

Now, the next set of images are the proposed mobile "responsive" experience.

<img src="https://user-images.githubusercontent.com/704682/53533047-e152ad80-3abe-11e9-9c00-537e2c663380.png" width="300">
The breadcrumb control is scrollable when the width doesn't fit the device.
<br />
&nbsp;
&nbsp;

<img src="https://user-images.githubusercontent.com/704682/53533048-e152ad80-3abe-11e9-8bb4-a91179857009.png"  width="300">
The hamburger menu displays the TOC.
<br />
&nbsp;
&nbsp;

<img src="https://user-images.githubusercontent.com/704682/53533049-e152ad80-3abe-11e9-87e9-3ec7c5329600.png"  width="300">
The search box "lives" in the hamburger menu.
<br/>
&nbsp;
&nbsp;
&nbsp;

<img src="https://user-images.githubusercontent.com/704682/53533050-e152ad80-3abe-11e9-9dd8-d5e537c93c99.png"  width="300">
When we choose language we have a selection dialog appearing.
<br/>
&nbsp;
&nbsp;
&nbsp;


These last pdfs have other Explorations. Please, feel free to comment and propose other explorations.

[Makecode - Documentation  (Mobile) - Breadcrumb.pdf](https://github.com/Microsoft/pxt/files/2912842/Makecode.-.Documentation.Mobile.-.Breadcrumb.pdf)
[Makecode - Documentation  (Mobile).pdf](https://github.com/Microsoft/pxt/files/2912843/Makecode.-.Documentation.Mobile.pdf)

**Comment by toledoal** [comment]
While we were exploring the language picker we found that's rendered by react lang.tsx. What do you think about recreating this with vanillajs/jquery/semantic-ui in a new file docfiles/controls/langPicker.js
The idea is to use appTheme.selectLanguage and appTheme.availableLocales to get the same options as in the editor. There is a const 'allLanguages' in lang.tsx we could replicate that one or figure a way to refactor that object to be able to get it from docs. Also for the look and feel the idea is to make both pickers look the same.
