### ISSUE TITLE
While Loop Based on Running Time Disables All Button Events

### ISSUE THREAD

**Issue by shagerott** [Microsoft/pxt#5322]
Below are two example programs.  The first cannot respond to button presses and the second can respond to button presses.  Both programs utilizes a while loop based on running time and there are no operations performed in the while loop.  To fix the program, a basic.showIcon command is inserted before and after the while loop.  This addition fixes the issue.  This seems to be a different problem from ignoring events while in a while loop because there are no operations added within the while loop.  In the broken case, even the simulator reproduces the lack of response to button presses.

**Broken:**

```
let starttime = 0
let score = 0
let highscore = 0
input.onButtonPressed(Button.AB, function () {
    score = 0
    starttime = input.runningTime()
    while (input.runningTime() - starttime <= 5000) {
        
    }
    if (score > highscore) {
        highscore = score
    }
})
input.onButtonPressed(Button.A, function () {
    score += 1
})
input.onButtonPressed(Button.B, function () {
    score += 1
})
input.onGesture(Gesture.Shake, function () {
    basic.showNumber(highscore)
})
highscore = 0

--------------------------------
**Works:**
let starttime = 0
let score = 0
let highscore = 0
input.onButtonPressed(Button.AB, function () {
    score = 0
    starttime = input.runningTime()
    basic.showIcon(IconNames.Yes)
    while (input.runningTime() - starttime <= 5000) {
        
    }
    basic.showIcon(IconNames.No)
    if (score > highscore) {
        highscore = score
    }
})
input.onButtonPressed(Button.A, function () {
    score += 1
})
input.onButtonPressed(Button.B, function () {
    score += 1
})
input.onGesture(Gesture.Shake, function () {
    basic.showNumber(highscore)
})
highscore = 0
```

**Comment by pelikhan** [comment]
Don't do a while loop to pause, instead do "pause(5000)". Or add "pause(1)" in the while look to allow events to run.

**Comment by shagerott** [comment]
Thanks for the tip. Yes, I've already switched our program over to call
pause instead. Are there the button and other event interrupts just too low
of a priority to get serviced during the main loop?

**Comment by pelikhan** [comment]
You need to have an api that pauses somehow to allow the event queue to flush events. Right while loop are problematic and generally should avoided as they are very inefficient :)

**Comment by shagerott** [comment]
Understood. Thanks!
