### ISSUE TITLE
Microbit Curriculum blog post

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#5324]
Hey Galen,
Can you prep this blog post about the new Educator Materials for the Micro:bit Curriculum?  Feel free to edit.
Files uploaded here: https://1drv.ms/f/s!AmMIW5Hxi0RtgZlWcV8e38x9111pFQ
Thanks!
Jacqueline

**Comment by ganicke** [comment]
Soitenly!

**Comment by Jaqster** [comment]
Hey Galen, can you merge?
