### ISSUE TITLE
Download via WebUSB feature

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#5344]
## Description

Automatically use WebUSB to download your code to the device via WebUSB

## How to use it?

In **Chrome**, click on **Download** to initiate the download and follow the pairing instructions.

If you cannot see that button and you editor supports this experiment, go to **About**, then click **Experiments** and **Download WebUSB**. If you cannot see this card, your editor does not support yet this feature.

## Feedback

Do you use this feature? Is there something you'd like to change? Did you encounter issues? Please drop a comment on this issue to send us your feedback.

**Comment by kcomain** [comment]
i am using the latest firmware version( 0250), it works on the normal version, but not the /beta version.

**Comment by kcomain** [comment]
Oh, and the "console" function does not work properly
I saw it could sync with my device but in reality, no.

**Comment by abchatra** [comment]
Editor supports this now.

**Comment by pelikhan** [comment]
@abchatra  Remove experiment from experimet.ts when closing these.
