### ISSUE TITLE
Language Picker in Docs

### ISSUE THREAD

**Issue by toledoal** [microsoft/pxt#5347]
I did a first pass on implementing the language picker in docs.
I'm basically trying to replicate "lang.tsx" picker but using js.

I see two challenges
1. How to use the same list of allLanguages available in lang.tsx (Maybe we could have a list available in pxt)
2. We have two constants in lang.tsx we could also have globally available
 
const langCookieExpirationDays = 30;
const pxtLangCookieId = "PXT_LANG";

Please take a look at this commit
https://github.com/pixelspace-dev/pxt/commit/4d52884f5915e0e1252adcca15230f2ec41a4894

**Comment by abchatra** [comment]
Fixed
