### ISSUE TITLE
pxt build error

### ISSUE THREAD

**Issue by houcy** [microsoft/pxt#5356]
I used below commands, but the build failed.
> git clone https://github.com/Microsoft/pxt
> cd pxt
> npm install
> npm run build
The last step failed with below errors:
----------------------------------------------------------

```
jake aborted.
TypeError: task.fail is not a function
    at ChildProcess.ch.on (/root/scratch3.0/makecode/pxt/jakeutil.js:110:18)
    at ChildProcess.emit (events.js:189:13)
```

My node verions is v10.15.3
Anything I'm missing that caused this error? Please help me, thanks!

**Comment by pelikhan** [comment]
We do not support node v10 yet, still on the good old v8.

**Comment by houcy** [comment]
> We do not support node v10 yet, still on the good old v8.

Okay, thanks for your response!

**Comment by abchatra** [comment]
Closing old bugs. If this still reproduces please reopen.
