### ISSUE TITLE
Static Python Feature

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#5390]
## Description

Convert Blocks and JavaScript to Static Python and back.

## How to use it?

Click on the **Python** tab in the language selection toggle above the editor.

![py3](https://user-images.githubusercontent.com/4175913/54951490-080ad500-4f01-11e9-86ed-0f2f31fb4774.gif)

If you cannot see that button and you editor supports this experiment, go to **About**, then click **Experiments** and **Static Python**. If you cannot see this card, your editor does not support yet this feature.

## Feedback

Do you use this feature? Is there something you'd like to change? Did you encounter issues? Please drop a comment on this issue to send us your feedback.

**Comment by pelikhan** [comment]
- [ ] use 4 spaces instead of 2
- [ ] auto-indent

**Comment by codinggirl** [comment]
Where is my editor?

**Comment by codinggirl** [comment]
Is there any live samples?

**Comment by pelikhan** [comment]
In arcade.makecode.com, go to about -> experiments -> Static Python.
In maker.makecode.com, enabled by default. Looking forward your feedback.

**Comment by pokon549** [comment]
Hi, all.
I've met some strange problems reported by the Static Python editor, but I actually write no codes inside the textarea. Is that a bug?
The Arcade version is 0.13.20.
![深度截图_20190805174056](https://user-images.githubusercontent.com/51010793/62455106-3ef2d080-b7a8-11e9-9b6d-312edd1ad250.png)

**Comment by darzu** [comment]
Hi, yes these are known issues will be fixed in: https://github.com/microsoft/pxt/pull/6167

I'm going to close this issue as it is too broad. We're tracking individual Python issues with the "python" label in the pxt, pxt-arcade, and pxt-minecraft repo.

Thanks for your feedback. Major work is being done on the Python support now (we have lots of issues we know about) and over the next few months we'll likely have something more stable that we'd love to get more community feedback on.

**Comment by danielbloy** [comment]
Just some feedback guys and a big thumbs up. I've been using MakeCode arcade in my code clubs for around 6 months now and the children (around 10 years old) and have been confined to Blocks as the children really struggle with JavaScript. They do respond better to Python as it looks less scary and I'm currently writing new material for them in Python. So far it's been fairly easy as I can navigate between Blocks and Python and use the generated results to guide my materials but it would be really useful to have a more comprehensive guide to the API in Python.
