### ISSUE TITLE
Array join() drops zero values as nulls

### ISSUE THREAD

**Issue by ganicke** [Microsoft/pxt#5396]
Values of `0` are omitted from the text rows on output. Seems that ``array.join()`` treats values of `0` as `null` and drops them out of the result string. See below:

```typescript
let testRows: number[][] = []
testRows = [[23, 9, 56], [87, 0, 45], [75, 0, 0], [0, 32, 45]]
for (let row of testRows) {
	console.log(row.join(','))
}
```

result:

```
23,9,56
87,,45
75,,
,32,45
```

**Comment by jwunderl** [comment]
For completeness;

https://github.com/Microsoft/pxt-arcade/issues/311 is a blocker on fixing this, as it seems like all ``null``s and ``undefined``s in arrays are being stored as just 0s no matter the type (e.g. https://makecode.com/_DTuJb5Ts44F5 and below). https://github.com/jwunderl/pxt/tree/arrjoin is a fix for this issue when that is fixed.

```typescript
let myNumArr = [0, 1, 2, 3, undefined, null];
let myBoolArr = [true, false, undefined, null];
let myStringArr = ["he", null, undefined, " ", "123"];

console.log("nums: " + myNumArr.join(","));
console.log("bools: " + myBoolArr.join(","));
console.log("str: " + myStringArr.join(","));
```

results in

```
nums: 0,1,2,3,0,0
bools: true,false,0,0
str: he,0,0, ,123
```
