### ISSUE TITLE
"Text from char code" crashes the simulator

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#541]
Dragging the Math block "Text from char code" into the editor causes an error to display and the simulator to crash. The only way to restart the simulator is to refresh the page.

**Comment by riknoll** [comment]
@abchatra was this fixed by your ref counting fix?

**Comment by abchatra** [comment]
Yes this is fixed by the same. Verified.

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/545
