### ISSUE TITLE
Microbit Beta blog post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#5439]
Hi Galen,
Can you create this blog post?  And go ahead and publish when your done.
Trying to get this posted today.
All the files are here: https://1drv.ms/f/s!AvnYExTCocXPiWIZ30LI2C8sGHk6
Thanks!
Jacqueline

**Comment by Jaqster** [comment]
Oh, also the Micro:bit folks wanted to link here from the Blog post: https://microbit.org/testing/

**Comment by Jaqster** [comment]
Hey Galen - can you add this text at the top of the blog post?  https://makecode.com/blog/microbit/2019-beta

"Update:  We have a date!  We plan to release this Beta into production on Friday June 14th!"

**Comment by ganicke** [comment]
Release notice added in #5619.
