### ISSUE TITLE
Conditional generation of config.json content for bluetooth

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#544]
I'd like to be able to create a block which determines some of the content of config.json files, according to the value of the block's properties. As I understand it, currently one static config.json file only is available and always included unchanged in the resultant C/C++ and build process. Can we change this so that the config.json file could have (say) symbols in it that can be substituted with variable data or something along those lines?
To make this more concrete and less abstract;
The microbit-dal now supports Bluetooth Just Works pairing or the original Bluetooth passkey pairing (or not pairing at all) as a config option. At the time of writing, the config selection is made by changing a header file but I just submitted a pull request which exposes this setting as a config.json property. I'd like to create a pairing mode block that lets the user decide which type of pairing, including no pairing at all, they want their hex file to require. We could perhaps default to Just Works pairing.
See lancaster-university/microbit-dal#223 
Thanks

**Comment by abchatra** [comment]
Ported from https://github.com/Microsoft/pxt-microbit/issues/271

**Comment by bluetooth-mdw** [comment]
Just to add another concrete example of why we need this.... recently, partial support for Eddystone beacons was added to the DAL by another contributor. I'm now extending it to give more complete support. This allows a micro:bit to be used as a Bluetooth beacon.... physical web and all that. But.... to use your micro:bit as a beacon requires a flag setting in config.json as well as some run time code in your application. So if we wanted a "PXT beacon block" (which we do!) then the block would need to both generate C/C++ fragments *and* modify the content of config.json.

**Comment by pelikhan** [comment]
We should do this feature. Requiring to use packages for C++ defines is not going to scale long term.

**Comment by bluetooth-mdw** [comment]
There's now support for Eddystone beacons in the DAL. Documentation is in the process of being updated. Seehttps://github.com/lancaster-university/microbit-docs/pull/38

Video: https://www.youtube.com/watch?v=mZlwxIOYxPE&spfreload=5

So I'd like to be able to create a Bluetooth Beacon block and a Pairing Configuration block, both of which need the ability to substitute dynamically selected values in config.json

Cheers

Martin
