### ISSUE TITLE
Shared QR Code Feature

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#5456]
## Description

Generates a QR Code with the shared project URL. This allows to scan the QR Code from a phone.

## How to use it?

Click on the **Share** button and share your project. You should see the QR Code next to the shared url.

![image](https://user-images.githubusercontent.com/4175913/55966371-1eb56980-5c2d-11e9-9185-835744f366e8.png)

If you cannot see that button and you editor supports this experiment, go to **About**, then click **Experiments** and **Shared QR Code**. If you cannot see this card, your editor does not support yet this feature.

## Feedback

Do you use this feature? Is there something you'd like to change? Did you encounter issues? Please drop a comment on this issue to send us your feedback.

**Comment by winecos** [comment]
Cool feature!

**Comment by abchatra** [comment]
All editors support this now.
