### ISSUE TITLE
ShowString after addScore is not showing the string 

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#552]
When running this code, the string "WINS:" does not show. It seems to happen due to the "addScore" because if you take out the addScore part and just show a set number in the "showNumber" it works fine.
Repro:
input.onButtonPressed(Button.A, () => {
game.addScore(1)
basic.showString("WINS:")
basic.showNumber(game.score())
})
*\* Notice - doesn't show "WINS:"

Ported from pxt-microbit repo: https://github.com/Microsoft/pxt-microbit/issues/177

**Comment by nielsswinkels** [comment]
I'm having issues with if you have both addScore and a sprite in your code. The animation of the addScore seems to not run the way it should.

Minimal example:
`let item = game.createSprite(2, 2)
input.onButtonPressed(Button.A, () => {
    game.addScore(1)
})
`
In this example the animation of the addScore is not shown properly. In a more elaborate program I made the addScore stopped the screen from updating until the gametimer ran out.

**Comment by chmora** [comment]
The reason for these issues is that game.addscore is Async and is killing the current enqueue animations, which messes with showString and ShowNumber (both methods attempting to play an animation).

The intended way this method was meant to be used is like so: 
```
basic.forever(() => {
    basic.showString("Hello!")
})

input.onButtonPressed(Button.A, () => {
    game.addScore(1)
})
```
This way the addScore can interrupt any animations playing and show it's little flash animation.

**Comment by microsoftsam** [comment]
The game package needs to be reworked. This is an issue with the underlying design of the package.
