### ISSUE TITLE
Round-trip python decompilation and compilation of all doc code snippets

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt#5538]
The "pxt checkdocs" CLI command runs a number of tests on all the code snippets in a target. Currently we can decompile without error all ~700 snippets in the pxt-minecraft target, but other targets have not been tested. Furthermore, today we just test if decompilation succeeds (a test of ts2py), not if compilation of the result .py succeeds (a test of py2ts).

One challenge here is how to determine if the round trip compilation worked. Even if compilation succeeds, the runtime semantics may have been affected. My proposed solution for this is to do a syntax comparison between the old and new .ts code with allowances for function names and other differences that are simple to allow. Below I have code that does this and succeeds for 388/656 of minecraft snippets.

The remaining work here is mostly in small tweaks to py2ts and ts2py to ensure that round-tripping code ends up the same. E.g. some work that has already been done in this area: re-inline functions used just once; emit loop iteration as "i++" (most common) not "++i" (less common).; etc. 

Once this is done, we can use pxt checkdocs on all of our most popular targets to verify we can decompile all snippets. This will give us a large amount of confidence that our Python implementation is up to the task of supporting all targets and common scenarios.

**Comment by darzu** [comment]
Working on this in the dazuniga/pysnippets branch

**Comment by abchatra** [comment]
Closing old bugs. If this still reproduces please reopen.
