### ISSUE TITLE
Implement more Python features & align with Python3 semantics

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt#5539]
Ideally we should implement py2ts & ts2py features necessary to run all the test cases in pxt/tests/runtime-trace-tests/cases/*. Files with the "TODO_" prefix are disabled and represent a checklist of unimplemented features.

This includes:
- [ ] handling generic console.log/print (that accepts string and numbers)
- [ ] implementing proper variable capture semantics.
  - [ ] Currently our python uses typescript capture semantics. In real python, we'd need to use the "nonlocal" and "global" keywords to allow use of variables outside the function scope.
- [ ] handle union types
- [ ] handle tuple assignment
- [ ] align with python3 semantics on callback argument cardinality
- [ ] detect variable manipulation inside for-loops
  - [ ] currently we compile `for (let i = X; i < Y; i++) {}` into `for i in range(Y):`. Technically this isn't safe if "i" is modified during the loop. We need to detect cases like this and instead compile to a different loop format.

**Comment by abchatra** [comment]
Closing old bugs. If this still reproduces please reopen.
