### ISSUE TITLE
Assembly generation when micro:bit is in 'Play' mode

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#554]
When developing JavaScript or block based programs for the micro:bit the Assembly file is generated and shown in the 'built' folder when you press the Compile button. However, when the editor is in 'Play' mode this file appears and then disappears shortly afterwards.
Steps to reproduce:
Create a new project and leave it empty
Click More, Show Files
Click 'built'
Click 'Compile' and then 'Done'
The .asm file is present in the 'built' folder
Click 'Play'; the .asm and .hex files immediately disappear
Click 'Compile' and 'Done' again; the .asm and .hex files are restored to the 'built' folder
Switch out of the tab, add or block, or do some other operation that changes the state
The .asm and .hex files are both absent

Ported from pxt-microbit repo: https://github.com/Microsoft/pxt-microbit/issues/159

**Comment by riknoll** [comment]
No longer repros

**Comment by abchatra** [comment]
Michal fixed this.
