### ISSUE TITLE
Dutch translation of 'comment'

### ISSUE THREAD

**Issue by editicalu** [Microsoft/pxt#5542]
The Dutch translation used for the word 'comment' is strange. It's translated as 'reactie', which is a comment in the sense of a reaction (as in a reply to something).

While this might technically be a correct translation for 'comment', it would be better to use the 'commentaar' translation, which is 'comment' as in a note or remark.

It really bother me, because I'm writing a Dutch course and it's very strange.

I'll open a PR.

**Comment by abchatra** [comment]
This needs to be fixed in Crowdin.
