### ISSUE TITLE
JS Docs has out of date images and innfo

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt#5562]
https://github.com/Microsoft/pxt/blob/master/docs/js/editor.md has 

- outdated images of the micro:bit editor 
- and user reports the info on colouring is incorrect.

> Coloring
The Editor automatically colors each of function and its respective namespace to match the colors of the respective block in the Block Editor.

For any of the LOOP functions, while the blocks are GREEN, the JS Code is BLUE or PURPLE (can't quite make it out). These are the colors of the MATH and FUNCTIONS blocks.

The observed color  is the same both in the current Editor and in the BETA.
Below is a screen shot of the LOOP blocks arbitrarily placed on screen to show  JS Mode Color issue: Blocks are GREEN but JS Code is BLUE.

![xsaUNbfUZfPj8e19MBEGy6JsMJUKAGIDCA](https://user-images.githubusercontent.com/31242877/57691751-f01c1b80-763c-11e9-8dad-a980b5290fe2.png)

image

**Comment by abchatra** [comment]
@ganicke  Can you take a look? Is this a documentation issue?

**Comment by ganicke** [comment]
1. The blocks image for the editor topic is updated.
2. The color of base JS language keywords is blue. The other colors are black for vars and the blue-green for literals. Functions from namespaces will have the namespace color. Loops is somewhat of a pseudo-namespace really so loop statements are language features.
