### ISSUE TITLE
Download screenshot doesn't work in Edge & IE11

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#557]
Try to download screenshot in  Edge & IE11. Does nothing
![image](https://cloud.githubusercontent.com/assets/6107272/19631574/280eb2ba-9953-11e6-8701-8e9954395098.png)

**Comment by pelikhan** [comment]
This is due to CORS. To solve this, we would have to render the SVG via JavaScript or prompt the user to try another browser.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
