### ISSUE TITLE
Adding bluetooth package in IE11 doesn't work as intendend

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#558]
Add Bluetooth package in IE11 browser. Nothing happens. UI continuous to display IE11.

![test](https://cloud.githubusercontent.com/assets/6107272/19631616/94662e20-9953-11e6-8fef-6af8a6e456a3.gif)

**Comment by chmora** [comment]
It works fine for me. Could you check again if the problem is already fixed?

**Comment by microsoftsam** [comment]
@abchatra could you please check if you can still repro this.

**Comment by abchatra** [comment]
I can't repro either.
