### ISSUE TITLE
Blockly mutator on onDataPacketReceived (and similar) is broken

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt#5586]
This mutator is broken. E.g. the Packet block isn't draggable. 
![image](https://user-images.githubusercontent.com/6453828/57973447-d2f98c80-795d-11e9-8303-7a811598f735.png)

We could remove the gear. Old code would continue to work.

Blocks that use this mutator are:
- onInfraredPacketReceived
- onCablePacketReceived
- onDataPacketReceived [deprecated]
- onChatCommand

**Comment by abchatra** [comment]
Lets remove the mutator

**Comment by abchatra** [comment]
We have removed the mutator

**Comment by agustindev** [comment]
Whats the replacement of mutators now? For example Im trying to create a new block, like array plus/minus, but with a table structure. I know I can create an Editor with a custom plus/minus row/column functionality, but this way I only can create inputs for text and not able to create connectors to another inputs that returns string type.
