### ISSUE TITLE
Going to "Home" while loading a project can delete the project's code

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt#5707]
Affects all editors but easiest to see in Arcade.

Repro:
1. Open Falling Duck in Arcade
2. Repeatedly open Falling Duck and as soon as you can click the Home button
3. Eventually your code will be gone

This can happen very easily if a user accidentally opens the wrong project and wants to go back to the home page. This also happens more often since our home page rearranges projects based on last usage, so the projects might switch positions from the last time the user saw them.

**Comment by darzu** [comment]
This was seen on microbit.makecode.com and arcade.makecode.com live sites

**Comment by abchatra** [comment]
Closing this as we there is tracking bug in microbit to track code loss.
