### ISSUE TITLE
browser trying to load monaco js map files

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#572]
![image](https://cloud.githubusercontent.com/assets/4175913/19667958/0411deee-9a09-11e6-980d-149efbcd3088.png)

**Comment by microsoftsam** [comment]
The Chrome dev tools requests these source maps, we can either get and host the source maps, or ignore this error. It's only an issue when the dev tools are open. 
see: http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found
