### ISSUE TITLE
Teams Assignment Blog post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#5726]
Hi Galen,

Can you post this on our blog?  Files located here: https://microsoft-my.sharepoint.com/:f:/p/jacqchen/EmVzaneOimtErkV_3JYFfuIBpxJ6tcdZlzrCOCLfO_pGxg?e=Z89o6x

Thanks!
Jacqueline

**Comment by ganicke** [comment]
Yes!

**Comment by Jaqster** [comment]
Hey Galen, can you substitute this new video link in the blog post?  https://youtu.be/oBarPukXXXQ
There were some edits requested by the Teams team.
Thanks!

**Comment by ganicke** [comment]
@Jaqster - Got your new link in #5736
