### ISSUE TITLE
Custom blocks: Enums are displayed incorrectly in block if there's a whitespace in the first enum's name

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt#5796]
I'm making a custom block. If the first enum has a space in its block name, this is the outcome:

```javascript
enum system {
    //% block="SYSTEM 1"
    SYSTEM1,
    //% block="SYSTEM 2"
    SYSTEM2,
    //% block="SYSTEM 3"
    SYSTEM3
}

namespace myBlocks {
    //% block="activate %sys"
    export function test(sys: system) {}
}
```
![Screenshot_1](https://user-images.githubusercontent.com/5204369/62540647-5f7a6380-b858-11e9-8005-f17e7104d92c.png)

If the first item's whitespace is replaced with an underscore, things look more like I'd expect:

```javascript
enum system {
    //% block="SYSTEM_1"
    SYSTEM1,
    //% block="SYSTEM 2"
    SYSTEM2,
    //% block="SYSTEM 3"
    SYSTEM3
}

namespace myBlocks {
    //% block="activate %sys"
    export function test(sys: system) {}
}
```

![Screenshot_2](https://user-images.githubusercontent.com/5204369/62540691-7620ba80-b858-11e9-9707-76c288bf13ec.png)

**Comment by kristianpedersen** [comment]
I think it might be intentional. Things look fine if the enums have different names before the number:

```javascript
enum system {
    //% block="SYSTEM 1"
    S1,
    //% block="SYSTE 2"
    S2,
    //% block="SYST 3"
    S3
}

namespace myBlocks {
    //% block="activate %sys"
    export function test(sys: system) {}
}
```

![Screenshot_1](https://user-images.githubusercontent.com/5204369/62604334-2265ae00-b8f8-11e9-9c94-72ae981aa656.png)

**Comment by abchatra** [comment]
This is intentional. If all the enums hare common prefix they are hoisted out.
