### ISSUE TITLE
Local Translations for Tutorials

### ISSUE THREAD

**Issue by baradaran** [microsoft/pxt#5797]
# There is no locales for Tutorials

**User created tutorials cannot be locally translated**
It would be great to be able to locally create translations for the tutorials. Currently it is always downloaded from Crowdin. 

It is already possible to translate extensions,  [localization](docs/extensions/localization.md). My suggestion is to have localization also in tutorials

**Comment by abchatra** [comment]
Can you elaborate on your issue with crowdin? This is your custom tutorial?

**Comment by baradaran** [comment]
Yes, same as custom blocks, i want to be able to add custom tutorials in different languages. This will help the most when creating custom targets. 

Besides, I just noticed that the download screen (Download and save to microbit drive pop up) does not translate when changing languages and remains engish.

**Comment by abchatra** [comment]
There is ability now to translate custom tutorials and add translations similar to extensions. This is implemented.
