### ISSUE TITLE
PXT on MS Windows iot core: Raspberry Pi

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#581]
This is a marker for the interest in running PXT  on MS Windows iot core: Raspberry Pi and active effort that is "Help Needed".

PXT can run on localhost, as long as a version of node is used that is stated in requirements:  the present v6.9.1 LTS works for me and is a good choice for Windows 10 and probably other OS.

Problem:
- Obtaining and Installation of a node and npm on core that supports PXT: the rest should be small problems.

---

The possible benefits are that a local PXT server on a Raspberry Pi can help some situations in using customised versions of PXT to suit individual group/project needs with the least amount of time used for installation and investment.
The internet based PXT is a one size fits many: local PXT can help where the size does not fit or one needs to have something in a group/project environment. 
Even a classroom environment may benefit: try and see if the size fits

**Comment by OwenBrotherwood** [comment]
https://developer.microsoft.com/en-us/windows/iot/samples/helloworldnode.htm 
Shows the "Hello World" example: it results in a simple "Hello World" with node.
However, the "node" available is a dll
Of course, the modules are already collected in the visio projekt, so no real nead for npm.

The PXT does need the "node compiler" (forgotten it's name g something): this could be done in visio.

However "the best" would be a node.exe and npm.exe so as not to make things overly complicated at the start, maybe returning to a visio solution latter

---

<img width="478" alt="visioexample" src="https://cloud.githubusercontent.com/assets/866122/19725588/a7382794-9b86-11e6-957e-063048c456db.PNG">

**Comment by OwenBrotherwood** [comment]
https://github.com/ms-iot/node with vcbuild chakra nosign arm results in the enclosed.

**OK: now I need help.
How do I get npm and gyp to work ...?**

```
C:\nodeall>node --version
v7.0.0-pre

C:\nodeall>dir
 Volume in drive C is MainOS
 Volume Serial Number is 6C08-8720

 Directory of C:\nodeall

10/26/2016  05:54 AM    <DIR>          .
10/26/2016  05:54 AM    <DIR>          ..
10/26/2016  05:47 AM           558,592 cctest.exe
10/26/2016  05:47 AM           184,645 cctest.exp
10/26/2016  05:47 AM           304,470 cctest.lib
10/26/2016  05:47 AM         1,539,291 cctest.map
10/26/2016  05:47 AM         8,777,728 cctest.pdb
10/26/2016  05:52 AM    <DIR>          lib
10/26/2016  05:49 AM         4,402,176 node.exe
10/26/2016  05:48 AM           657,337 node.exp
10/26/2016  05:48 AM         1,070,218 node.lib
10/26/2016  05:49 AM         4,374,192 node.map
10/26/2016  05:49 AM        18,485,248 node.pdb
10/26/2016  05:54 AM    <DIR>          obj
10/26/2016  05:47 AM         1,681,920 openssl-cli.exe
10/26/2016  05:47 AM         2,295,610 openssl-cli.map
10/26/2016  05:47 AM        11,726,848 openssl-cli.pdb
              13 File(s)     56,058,275 bytes
               4 Dir(s)     274,743,296 bytes free



```

**Comment by OwenBrotherwood** [comment]
Currently fails on serial: Work in progress

**Comment by OwenBrotherwood** [comment]
serialport: No platform support for Pi ...?
https://www.npmjs.com/package/serialport#platform-support

**Comment by pelikhan** [comment]
gyp works just fine on Raspbian.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by OwenBrotherwood** [comment]
Errr I have a Microsoft mobile as well, so I have outlook :)

**Comment by OwenBrotherwood** [comment]
https://github.com/ms-iot/node/issues/13#issuecomment-256755055

**Comment by OwenBrotherwood** [comment]
With the kind help of MS participants, the new npm for ptx-core has an optionalDependancy for serialport.
It is now possible to do pxt serve on the Pi.

The next problem is to find out how to create the system described here:

> As a teacher, I would like to setup a cheap local server that does not change as http://pxt.io develops and changes are under my control so that the course material does not need to be revised all the time

---

A localhost solution to pxt has been made for Windows 10 core on the Pi3.
However, I do not have a browser for the Pi so the localhost scenario hits a problem when the pxt server url is attempted by an external device as the server binds to locahost, 127,0,0,1
https://github.com/Microsoft/pxt/blob/51e0424190c51f5b8f839e56802bef0e2295ec7a/cli/server.ts#L495

I will now see it it is possible to create a "cloud" solution on the Pi as per:
https://www.pxt.io/cli

**Comment by OwenBrotherwood** [comment]
Having now an electron app working on Windows 10 ...Windows Core?

**Comment by OwenBrotherwood** [comment]
Status from me:
I have now decided that the Windows 10 core is just a "keep the flag" while Microsoft and Canonical do a mac os9 to osX 
I start using canonical IoT on Pi and watch developements.
ie no immediate plans from myself to implement pxt electron on core

**Comment by OwenBrotherwood** [comment]
At the present time frame, there is no visible effort to support the zero W which could have been "interesting"
A requirement of the manufacturer to support the board in Windows IoT core context.

https://social.msdn.microsoft.com/Forums/en-US/a143bc57-910a-4a04-a1c5-eafcbe2292ce/raspberry-pi-zero-w-does-not-support-windows-iot-core-image?forum=WindowsIoT

**Comment by pelikhan** [comment]
This request is not for PXT. Closing.
