### ISSUE TITLE
Documentation menu incomplete in languages other than English

### ISSUE THREAD

**Issue by sorskoot** [microsoft/pxt#5812]
**Describe the bug**
I just ran into an issue with the documentation in different languages. In the [English version](https://minecraft.makecode.com/docs/?lang=en) the menu of the documentation shows tutorials, references and a lot more than for example [Dutch](https://minecraft.makecode.com/docs/?lang=nl). At first I thought 'Dutch' was broken, but I tried French, German, and Spanish as well and none of these show the full menu.

**To Reproduce**
By changing the last 2 characters of the URL (https://minecraft.makecode.com/docs/?lang=en) you can switch the language. Notice that in English (`en`) the menu is different than in Dutch (`nl`), French (`fr`) or Spanish (`es`).

**Expected behavior**
The menu should contain the same content, preferably localized in each language.

**Screenshots**
English version, correct
![image](https://user-images.githubusercontent.com/2283621/62937528-2cdae880-bdcd-11e9-874d-c2702cd9cefb.png)

Dutch version, incorrect
![image](https://user-images.githubusercontent.com/2283621/62937538-35332380-bdcd-11e9-9540-605e3f940e31.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge, Chrome

**Comment by abchatra** [comment]
This is fixed.
