### ISSUE TITLE
compilation broken when using radio apis

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#586]
Not completely sure what's the root cause of this.

![image](https://cloud.githubusercontent.com/assets/4175913/19754001/487ef5d8-9bbe-11e6-8fe5-23295b384cb8.png)

**Comment by pelikhan** [comment]
Looks like the webworker does not have access to the target info.

![image](https://cloud.githubusercontent.com/assets/4175913/19754138/9d1a2292-9bbf-11e6-9f6d-501be666049b.png)

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/commit/128146967d255bc5a0acef9ea31bab41dd65faa1

**Comment by riknoll** [comment]
How do you repro this? The beta site and my local build work fine for me.

**Comment by pelikhan** [comment]
Fixed that one yesterday.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
