### ISSUE TITLE
integrate live translations

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#589]
As discussed I have added the following APIs:
- https://www.pxt.io/api/translations/langs  - list of available languages
- https://www.pxt.io/api/translations/files - list of available files with version number
- https://www.pxt.io/api/translations?lang=fr&filename=microbit/bluetooth-strings.json - fetching specified file

If you need a json file that combines all available files, I can also do that. The API calls are cached server side, so we should be good wrt crowdin throttling. The "info" (i.e., revision numbers) is refetched every 5 minutes (if used)

**Comment by mmoskal** [comment]
See implementation at https://github.com/Microsoft/pxt-backend/commit/e534680e4903335dddfebb5412a6af9ee2bf8594

**Comment by abchatra** [comment]
Done?
