### ISSUE TITLE
simulator 'play' button

### ISSUE THREAD

**Issue by sehodges** [Microsoft/pxt#59]
The text label on the simulator 'play' button doesn't always change to 'stop' when the simulator is running. No repro yet, sorry :-(.

**Comment by pelikhan** [comment]
Take a screenshot - it helps and capture the javascript console.
Also, will need browser, OS info etc...

**Comment by sehodges** [comment]
Yes, sorry, screenshot would have been useful with hindsight.

What do you mean by javascript console?

Should I be putting feature requests into github or is that spamming you? E.g. I think the A+B button should appear in the simulator if your code uses ‘A’ in one place and ‘B’ in another, even if it never uses ‘A+B’ – you still might want to test what happens on a simultaneous button press.

Thanks,

Steve

**Comment by pelikhan** [comment]
Keep piling issues in github. It’s much more tractable for me. We can have the conversation there.

**Comment by pelikhan** [comment]
No repro.
