### ISSUE TITLE
User project erased on tab switch

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt#5900]
This happened to Richard in Arcade where he had two tabs open, one with TS one with Blocks and for some reason when switching back to the TS project the page switched into blocks mode and erased his TS.

I've also seen project state loss when opening and exiting a project very quickly.

In general we seem to loose user code too often. Maybe we need to rearchitect our project state handling a little bit to make it more robust.

**Comment by abchatra** [comment]
Tracking bug in microbit.
