### ISSUE TITLE
Issues related to break and continue blocks

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/pxt#5913]
**Describe the bug**
After #5908 and #5910, if `breakBlock` and `continueBlock` are not defined under `runtime` in `pxtarget.json`,

1. There will be 2 black unusable blocks under the Loops block menu, and
2. If JavaScript code contains any `break` or `continue` statement, the code cannot be converted to blocks.

**Expected behavior**
If the properties are not defined, default options should be used.

**Screenshots**
![image](https://user-images.githubusercontent.com/8416067/65113248-17cd2700-da15-11e9-8dd9-b2274d894356.png)
![image](https://user-images.githubusercontent.com/8416067/65113304-4519d500-da15-11e9-80f5-667be7e3f622.png)

**Additional context**
I am really happy to see blocks for `break` and `continue` statements in MakeCode! I think microsoft/pxt-microbit#2324 may be closed after the PXT version is bumped there.

**Comment by pelikhan** [comment]
Thanks!

**Comment by abchatra** [comment]
fixed
