### ISSUE TITLE
Fail to convert break and continue statements to blocks

### ISSUE THREAD

**Issue by FranklinWhale** [microsoft/pxt#5922]
**Describe the bug**
While the first issue in #5913 is fixed, the second issue, namely code that contains `break` or `continue` statement failing to convert to blocks, still persists.

The error occurs regardless of whether `breakBlock` or `continueBlock` is specified in pxtarget.json.

According to the error reported in the Developer Tool, `pxt.appTarget.runtime` is `undefined` when `checkStatement` in decompiler.ts is executed.

**To Reproduce**
1. Open the Developer Tool of browser
2. Switch to JavaScript
3. Paste the code below to the editor
```ts
let breaking = true;
for (let i = 0; i < 4; i++) {
    if (breaking) {
        break;
    }
}
```
4. Switch to Blocks
5. See error

**Expected behavior**
If `breakBlock` is set in `pxtarget`, the new break block should be used. Otherwise, the grey block should be used.

**Screenshots**
![image](https://user-images.githubusercontent.com/8416067/65211718-42c98080-dad2-11e9-9bc1-c8126f926e89.png)

**Desktop**
 - OS: Windows 10 1903
 - Browser: Google Chrome 77.0.3865.90 (Official Build) (64-bit)

**Comment by pelikhan** [comment]
Thanks for reporting. Looking into this.

**Comment by pelikhan** [comment]
Fixed.

**Comment by FranklinWhale** [comment]
Confirmed fixed. Thanks!
