### ISSUE TITLE
Dropdowns are not disabled in readonly mode (blockly)

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#5932]
The css query needs to account for .blocklyNonEditableText as well.

https://github.com/microsoft/pxt-blockly/blob/6dc75f02c7b1891b1f4d9a81615934b2aa76b2d5/core/css.js#L458

**Comment by pelikhan** [comment]
This issue is still present.
![image](https://user-images.githubusercontent.com/4175913/68436267-6c1d9900-0172-11ea-916c-45879ea3081e.png)

**Comment by abchatra** [comment]
I see drop downs disabled but highlighted in the share.  What is the issue?
