### ISSUE TITLE
Should stop button go away after the script has executed?

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/pxt#60]
Create Block Script
Play
Result: Stop remains
![image](https://cloud.githubusercontent.com/assets/15837908/15409909/d3d67410-1dcb-11e6-9a1a-6d2253635c78.png)

Note: If you move to other browser tab, then the button will change to play

**Comment by pelikhan** [comment]
We technically don't know when the script logic stops so stop stays there.

When changing tabs, we automatically stop the simulator to avoid waiting cycles in the background.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________
