### ISSUE TITLE
playground-runner not loading

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt#6023]
# Bug Template

**Describe the bug**

**To Reproduce**
1. Go to 'https://makecode.com/playground'
4. Playground runner does not load in iframe on the right of the page or in an external tab https://makecode.com/playground-runner

Console
![7E26E634-6155-4307-955E-B1B263ED2376](https://user-images.githubusercontent.com/31242877/66307400-46476f00-e8fc-11e9-9c85-10a3b2057b92.jpg)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome/Firefox

**Additional context**

**Comment by abchatra** [comment]
@riknoll  can you take a peek?

**Comment by abchatra** [comment]
fixed
