### ISSUE TITLE
Namespace coloring leads to invisible text

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#6034]
Our logic to turn namespace colors into text color is really spotty. There are many namespaces that are invisible. We should (1) turn off this feature or (2) fix the algorithm to guarantee a certain level of luminance.
![image](https://user-images.githubusercontent.com/4175913/66431261-8710b800-e9d0-11e9-92bb-6ad39808fb39.png)
![image](https://user-images.githubusercontent.com/4175913/66431138-4749d080-e9d0-11e9-9022-210664eeca91.png)

- [ ] microbit (light editor)
- [ ] adafruit (inverted editor)

**Comment by jwunderl** [comment]
Re: https://github.com/microsoft/pxt-microbit/issues/2271

I think I'd personally have to lean towards just dumping the behavior, the color would be meaningless if it doesnt match the block color (which would be result of improving algorithm to pick better colors) and changing block colors is a high bar with existing material / its a bit hard to properly change and still have all the blocks be distinguishable from each other. Also kind of damages normal syntax highlighting usage as the colors are each individually less meaningful.

@Jaqster

**Comment by Jaqster** [comment]
No, no, no!  We need the color coding in text.

**Comment by pelikhan** [comment]
Monaco provides standardized colors for typescript keywords. Current behavior leads to (near) invisible text.

![image](https://user-images.githubusercontent.com/4175913/66431138-4749d080-e9d0-11e9-9022-210664eeca91.png)

**Comment by abchatra** [comment]
This is done.
