### ISSUE TITLE
local workspaces get published to github

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt#6136]
Scenario:

- I have a github extension E
- I have a script S using E; S also is backed by github.
- Both S and E are loaded into my local cache, so there is a local "workspace" reference from S to E
- If I commit S to github, it will persist the workspace reference to E in the pxt.json

Instead, the workspace reference should be replaced by a github reference.

Related issue: if I modified E then E should be committed and pushed before S. This applies recursively.

**Comment by pelikhan** [comment]
What happens if you have uncommited changes in E, and commit fails? I think we should tell you to commit all dependent libraries before allowing S to be pushed.

**Comment by pelikhan** [comment]
Fixed.
