### ISSUE TITLE
Can't disable compileService if compile.hasHex is enabled

### ISSUE THREAD

**Issue by wryun** [microsoft/pxt#6165]
**Describe the bug**
If you remove compileService from `pxtarget.json`, a subsequent assert will fail if compile.hasHex is true.

**To Reproduce**
1. Checkout pxt-microbit
2. Remove compileService
3. Run `pxt staticpkg`
4. See assert error

**Expected behavior**
It should be possible to disable compileService so I can build a version of pxt-microbit that will not attempt to make requests to `compile/extension`.

(I think this is what this is supposed to do - mostly just guessing here. Please let me know if there's some other way to stop these requests)

**Additional context**

Even if I'm completely confused about what this is supposed to do, this series of conditions seems strange:

https://github.com/microsoft/pxt/blob/7a2f76aee965c687813743ea09ea6fffb1ca2c85/pxtlib/cpp.ts#L179
https://github.com/microsoft/pxt/blob/7a2f76aee965c687813743ea09ea6fffb1ca2c85/pxtlib/cpp.ts#L197
https://github.com/microsoft/pxt/blob/7a2f76aee965c687813743ea09ea6fffb1ca2c85/pxtlib/cpp.ts#L863

The last one is particularly interesting to me. How is this 'overridden on the build server'?

**Comment by wryun** [comment]
@abchatra what was the reason for closing this issue?

**Comment by abchatra** [comment]
I am not sure I understand this bug. Is this a bug or a question? Question should go to forum (forum.makecode.com)
