### ISSUE TITLE
Building with staticpkg -m generates broken documentation

### ISSUE THREAD

**Issue by wryun** [microsoft/pxt#6166]
**Describe the bug**
If you build with `pxt staticpkg -m`, the generated output has broken documentation.

**To Reproduce**
1. Checkout pxt-microbit (either master or stable2.0)
1. `pxt staticpkg -m`
2. Serve files in built/packaged
3. Click on (?) then 'Reference'
4. Spin indefinitely

**Expected behavior**
The behaviour should be equivalent to `pxt staticpkg`

**Additional context**
Error in console about attempting to load `cdn/blockly.css` (404 - unclear where this path is from).

**Comment by wryun** [comment]
@abchatra what was the reason for closing this issue?

**Comment by abchatra** [comment]
Is this still a issue? I assumed this was fixed. We have staticpkg running successfully in master.

**Comment by wryun** [comment]
@abchatra sorry for the delayed response - I missed this. It's still blowing up in exactly the same way for me on stable6.0

Note that staticpkg works for us - it's just that -m doesn't (or rather, it does but breaks the blocks).
