### ISSUE TITLE
Custom target: Raspberry Pi

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#617]
An issue to hold an enhancment.
It is probable that the linux target is under way "somewhere" and it is hoped that the Windows 10 Core can also be targetted.
https://www.pxt.io/target-creation

**Comment by OwenBrotherwood** [comment]
https://github.com/Microsoft/pxt/issues/581#issuecomment-273983955

**Comment by abchatra** [comment]
Wont fix for now. Feel free to provide a pull request.
