### ISSUE TITLE
Unable to convert back to blocks

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/pxt#62]
I have a script that I created a few hours ago. 
I displayed the code and left opened for a couple of hours.
Trying to "Show Blocks" shows error:
Something went wrong trying to convert your code

![image](https://cloud.githubusercontent.com/assets/15837908/15412613/d6d01218-1ddd-11e6-94c2-9455aa6a7983.png)

**Comment by pelikhan** [comment]
Please add JavaScript console output

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by RickGMSR** [comment]
var ts;
(function (ts) {
    var pxt;
    (function (pxt) {
        var Util;
        (function (Util) {
            Util.debug = false;
            function assert(cond, msg) {   <<<<<<<<<<<Stopped Here
                if (msg === void 0) { msg = "Assertion failed"; }
                if (!cond) {
                    debugger;
                    throw new Error(msg);
                }
            }

![image](https://cloud.githubusercontent.com/assets/15837908/15437964/bb9971f0-1e7e-11e6-9bbb-cc79ae5fde50.png)

Will add more once I can repro the problem

**Comment by pelikhan** [comment]
Please show all output and copy the content as text in the bug repro for the next occurence.

**Comment by pelikhan** [comment]
Fixed now.
