### ISSUE TITLE
Running pxt on other interfaces than localhost

### ISSUE THREAD

**Issue by mschlenker** [microsoft/pxt#6201]
I am currently extending pxt-maker for a new target. This works quite well and I am able to generate UF2 files when running with pxt serve --rebundle via localhost. Now I want others in the local network to test the configuration.

When running with 

`pxt serve --rebundle --hostname 10.76.23.5`

the board preview does not load. Firefox' web console says:

```
error: pxt_modules/base/pxt-core.d.ts(1,1): error TS9043: The hex file is not available, please connect to internet and try again.
2 pxtapp.js:2105:21
Error: "Bad HTTP status code: 403 at /api/compile/extension; message: Error 403"
    requestAsync http://10.76.23.5:3232/blb/pxtapp.js:1187
    c http://10.76.23.5:3232/blb/main.js:330
    _settlePromiseFromHandler http://10.76.23.5:3232/blb/main.js:330
    _settlePromise http://10.76.23.5:3232/blb/main.js:330
    _settlePromise0 http://10.76.23.5:3232/blb/main.js:330
    _settlePromises http://10.76.23.5:3232/blb/main.js:330
    _drainQueue http://10.76.23.5:3232/blb/main.js:330
    _drainQueues http://10.76.23.5:3232/blb/main.js:330
    drainQueues http://10.76.23.5:3232/blb/main.js:330
pxtapp.js:2109:21
Object { sha: "47983b95e54ee2542345ba05a2d2f1aa7927ef173941d00d63a2f0540589dd3e" }
pxtapp.js:2113:29
error: pxt_modules/base/pxt-core.d.ts(1,1): error TS9043: The hex file is not available, please connect to internet and try again.
pxtapp.js:2105:21
```
Did I miss a command line option or configuration entry, or is there just no intended way to run the development server on other interfaces than localhost?

**Comment by pelikhan** [comment]
pxt serve is intended to run as a development server only. it is not meant to serve the editor. If you want to host your editor, look at ``pxt staticpkg`` which generates a packaged version of the editor suitable for hosting.

**Comment by mschlenker** [comment]
Thanks! This is what I did the last hour or so. Currently, some static images are missing, but after looking at the logs, this should be easy to fix. At least we can test this way before finally submitting our board. I'll close tomorrow when I figured out which paths I need to manually copy.

**Comment by mschlenker** [comment]
OK, paths to images and docs not being configured as implied by CLI arguments seems to be either a minor bug or a documentation/configuration issue in pxt-maker. It can be easily solved with bind mounts or proper configuration of mod_alias. I'll add a few paragraphs to the documentation over there and do a pull request.
