### ISSUE TITLE
CLI uploading unwanted files

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#6241]
The new logic to pull files from common packages is uploading "junk" files into microbit. As a result, translations are lost https://github.com/microsoft/pxt-microbit/issues/2527

https://travis-ci.org/microsoft/pxt-microbit/jobs/613599901#L2051

Mitigation:
- [x] disabling crowdin upload in master (we should do that for all released editors / flag added https://github.com/microsoft/pxt/pull/6242)
- [x] bumping pxt-microbit in stable2.0 to restore translation. If not enough, manually revert versions in crowdin.
- [x] adding test mode to ``pxt uploadtrgtranslations --test``. It goes through all the files but fakes the call to crowdin.

**Comment by pelikhan** [comment]
This is probably the problem: https://github.com/microsoft/pxt/commit/351f1ea83e2c55c1601455974b61f4c4a7e15b80#diff-87390c8316b0230db07feb98ebca1fc0

**Comment by pelikhan** [comment]
Post mortem: we need to restrict crodwin uploads to stable branches -- or -- use more branches in crowdin. Let's have a meeting to avoid this in the future.

**Comment by pelikhan** [comment]
docs recovery still in progress https://travis-ci.org/microsoft/pxt-microbit/builds/614017441#L1821

**Comment by jwunderl** [comment]
Well presumably the problem would be in https://github.com/microsoft/pxt/pull/6206, so should revert that to start?

**Comment by pelikhan** [comment]
Yes revert for starter

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt/pull/6243

**Comment by pelikhan** [comment]
I will add a test mode

**Comment by pelikhan** [comment]
@jwunderl you can use ``pxt uploadtrgtranslations --test`` to see which files get uploaded and where in crowdin.
