### ISSUE TITLE
Possibly inconsistent state when working in multiple tabs: "trying to access outdated session"

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt#6276]
Repro:
1. open two tabs of arcade.makecode.com
2. in each one, open the debug tools
3. open a new project in each one
4. notice the "trying to access outdated session" assert (or warning) fires

It looks like the local storage code was written with the assumption that only one tab would be accessing it. This is definitely not true for many of our users. We should ensure the property consistency is implemented.

**Comment by abchatra** [comment]
I believe @pelikhan fixed this.
