### ISSUE TITLE
PXT load perf fixes

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#628]
- [x] Lazy load the doc page
- [x] Hide the doc page by default, have it in a sidebar drawer, that a user can expand
- [ ] Play an animation while the simulator is loading

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/634

**Comment by abchatra** [comment]
Closing this as we addressed most of these. Simulator loads quick for me as well after recent fixes by Sam.
