### ISSUE TITLE
Can only print one page in docs

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#6283]
Reported by Mike Dianovsky - 

Your print feature in your MakeCode Docs only lets you print the first page of the document and not the entire document :  https://arcade.makecode.com/courses/csintro2/functions/intro 
Is there a way to print the complete document?  I provide the link above as an example to show that only page 1 will print.

Also, I noticed that Print is broken completely in Edge.

**Comment by jwunderl** [comment]
multi page printing be fixed when we next release arcade as I fixed that in the new docs:

<img width="1415" alt="Screen Shot 2019-12-03 at 1 48 31 PM" src="https://user-images.githubusercontent.com/5615930/70092674-aa707180-15d3-11ea-9014-f63cdfa19142.png">

Not sure on edge printing; it looks better on edge, but had a few quirks still (https://arcade.makecode.com/concepts w/ new docs is only printing the first 6 boxes on edge, where it's printing everything properly on chrome). Will take a look

**Comment by abchatra** [comment]
This is fixed in Arcade and will be released as part of the next release. ETA end of month.
