### ISSUE TITLE
getters/setters are broken

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt#6376]
https://makecode.com/_7frFgwauY5yo

yields error messages in arcade beta:

error: main.ts(17,1): error TS9211: cannot use method as lambda; did you forget '()' ?
error: main.ts(19,9): error TS9211: cannot use method as lambda; did you forget '()' ?

**Comment by jwunderl** [comment]
swap the order (get then set) https://github.com/microsoft/pxt-arcade/issues/491

**Comment by mmoskal** [comment]
Duplicate of https://github.com/microsoft/pxt-arcade/issues/491
