### ISSUE TITLE
finish up testing and features for basic AVR code gen

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#639]
There are a number of things to finish off in code gen (feature and test):

- [x] test user-defined functions (and potentially use registers instead of stack to pass args)
- [x] add single-instruction cases (see simpleInstruction - the emitter makes use of single ARM instructions for many cases).
- [x] shifting  (x >> y) not taking amount y into account
- [x] arithmetic right shift not working
- [ ] initialization of globals not taking place (let/const) properly
- [x] get langtest0 passing
- [ ] add tests to pxt/microbit
- [ ] optimize call into rcall when range allows
- [ ] refactor indirect addressing to separate stack access from other

**Comment by abchatra** [comment]
Closing this as we are at a logical point of AVR code generation.
