### ISSUE TITLE
pxt target microbit fails in a cascade of errors

### ISSUE THREAD

**Issue by IowaDave** [microsoft/pxt#6396]
**First**, check if this repo is the right one to file the bug report.

I hope this repo is the right place to report a discrepancy with instructions that are given in this repo.

# Bug Template

**Describe the bug**
The instructions for setting up a workspace (as given on url: https://makecode.com/cli) fail at the following step:

"pxt target microbit"

Failure is a lengthy cascade of warnings and error messages. Console output is provided in the attached file: 
[pxt_Install_Failure.txt](https://github.com/microsoft/pxt/files/3992775/pxt_Install_Failure.txt)

**To Reproduce**
1. Follow the instructions *exactly* as given at [https://makecode.com/cli](https://makecode.com/cli).
2. Witness the avalanche of warnings and error messages

**Expected behavior**
Expected pxt to install.

**Screenshots**
None. However, the entire error log is provided in this attached file: 
[2019-12-22T17_37_13_601Z-debug.log](https://github.com/microsoft/pxt/files/3992783/2019-12-22T17_37_13_601Z-debug.log)

**Desktop (please complete the following information):**
 - OS: Linux (Raspbian version of Debian Buster)
 - Browser: Chromium
 - Version 74.0.3729.157 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Smartphone (not applicable):

**Additional context**
Node.js 8.17.0. 
Raspberry Pi 4, 2Gb, fully updated

**Comment by kbm-ky** [comment]
I had a similar problem on my Raspberry Pi 3.  I had problems installing the pxt-microbit dependencies with the `npm install` step.  Installing the libudev development package solved my issue:
`sudo apt update`
`sudo apt install libudev-dev`

After that, libudev.h was available in /usr/include for the libusb build to complete.

Hope this helps.

**Comment by abchatra** [comment]
Only Mac or Windows development supported. Linux is untested. Feel free to send PR if you are able to figure out the issues.
