### ISSUE TITLE
Arcade Announcement Blog Post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#6416]
Galen, can you post this to the blog on Monday?
Thanks!
Files located here - https://microsoft-my.sharepoint.com/:f:/p/jacqchen/ElLMNzAIOBdPsdkR_khczwwB_-4sHdRNvT-BxZKRf_TJ8A?e=6vBmYO

**Comment by pelikhan** [comment]
Close or reuse this https://github.com/microsoft/pxt/pull/6373

**Comment by ganicke** [comment]
OK, I'll put this in today. I'll close #6373 and re-start with this draft.
