### ISSUE TITLE
GitHub editor

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#6419]
## Description

Review, commit and push changes to a GitHub repository.

## How to use it?

Click on the GitHub button next to the save button.

## Details

* https://makecode.com/blog/github-packages
* https://makecode.com/blog/github-extensions-episode-2
* https://makecode.com/blog/makecode-with-github

## Feedback

Do you use this feature? Is there something you'd like to change? Did you encounter issues? Please drop a comment on this issue to send us your feedback.

**Comment by abchatra** [comment]
Supported int the editor now.
