### ISSUE TITLE
clearer error condition when non-ascii characters are used as variables

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#652]
Enhancement: clearer error condition when non-ascii characters are used as variables
Very much "up" is the translation process of pxt.
And some are even using non-ascii for variables: why not?
Of course, the "backend" doesn't like it.

This is a true example from the real world of teaching: the old block editor did not protest and the sim ran. The program did not run on the micro:bit.

Example screen dump of todays pxt (possibly a few comitts behind.
![variables](https://cloud.githubusercontent.com/assets/866122/19936262/35f2efe6-a11d-11e6-9d43-b1eca71668d6.jpg)

**Comment by pelikhan** [comment]
A triangle poped up on the set ... til block, it should have opened up when selecting the block.

**Comment by OwenBrotherwood** [comment]
It gets worse, sorry
I continued with show string (where there was no triangle) 
and added value, then triangle came on show string
<img width="310" alt="value ae" src="https://cloud.githubusercontent.com/assets/866122/19942729/0495497c-a135-11e6-8df6-3362bbcb562c.PNG">

**Comment by OwenBrotherwood** [comment]
The error: text is too long

![image](https://cloud.githubusercontent.com/assets/866122/22137858/e11dabba-dedd-11e6-9c19-0309b5211ff9.png)

**Comment by OwenBrotherwood** [comment]
Add show string to canvas
Add variable "æøå" to show string
"Unable to convert" dialog
There is no blue triangle
![image](https://cloud.githubusercontent.com/assets/866122/22137919/45d7b870-dede-11e6-80e5-0cdacd7f5dfc.png)

**Comment by OwenBrotherwood** [comment]
heads up to me when need for tests so that the issue can be closed

**Comment by OwenBrotherwood** [comment]
I have some test ready when "this" is available in /beta
