### ISSUE TITLE
display of "we use cookies" in non-browser environments

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#658]
display of "we use cookies" in non-browser environments

This may soon be noticed in downstream projects that use pxt as the fundament for encapsulating pxt in apps that do not require internet and the laws of the display for cookies used is not relevant.

The importance of projects that do not require internet to program the micro:bit should not be underestimated.

- It may be something that can only be fixed in pxt.

An example of a non-browser environment
<img width="593" alt="cookies" src="https://cloud.githubusercontent.com/assets/866122/19942195/3a812d50-a133-11e6-9f1d-d8e271b5b99c.PNG">

**Comment by abchatra** [comment]
I am closing this for now. The pxt-microbit-electron repo is just a prototype and there is no immediate release plan.

**Comment by OwenBrotherwood** [comment]
ok

**Comment by OwenBrotherwood** [comment]
@abchatra 
Please consider reopening this issue
The reference to the ptx-microbit-electron was because it was a "near" microsoft project, however, other projects can and will be affected by the way Microsoft treats the "pxt community"
/ cc @pelikhan

**Comment by OwenBrotherwood** [comment]
https://github.com/Microsoft/pxt/issues/433

**Comment by titimoby** [comment]
I concur on all @OwenBrotherwood said.
We are a lot of people around the world organizing non profit workshops for kids in places without Internet.
I guess the comment on how community will be treated has a strong meaning in a place like Github.
OpenSource project does not mean only push the source and forget about it.
Please, be open on at least discussion: I thought Pxt project was something to prove me Microsoft has made a true turn on Open Source.

**Comment by OwenBrotherwood** [comment]
I suggest a title change and an enhancement label: the issue is then catagorised allowing MS to concentrate on the pxt to ensure the base code is stable and can fullfill mircrobit.org goals in the near future.

**Comment by OwenBrotherwood** [comment]
@titimoby if the issue is reopened, then I would like the comments after the close to be removed to ensure a clean sheet for this momentary lapse which is undoubtedly a product of delivery of the pxt so that it then becomes non-beta @ microbit.org

**Comment by OwenBrotherwood** [comment]
opening comment rephrased to be acceptable

**Comment by OwenBrotherwood** [comment]
@abchatra /cc  @pelikhan 
All perceivable negative reactions to the closing of this issue are removed from this issue and slack.
Please consider the reopening of this issue with new title and as an enhancement label

**Comment by OwenBrotherwood** [comment]
@abchatra /cc @pelikhan 
Please consider reopening this issue with label "enhancement"

Note: 
- that the title and text have been changed
- All percievable and otherwise, negative reactions to the closing of this issue are removed from this issue and from https://microbit-community.slack.com/messages/pxt/ by myself and Thierry.

There is still an issue open at microbit.org support about the concerns we have for support for the micro:bi offline.

This comment will be removed after reopening of the issue so as not to cloud the issue.

**Comment by abchatra** [comment]
@owen_brotherwood. Pxt does have a strong desire to address the offline scenario for microbit. Most important aspect of offline scenario is ability to patch security issues and not leave users vulnerable. Electron app is the solution for offline scenario or not depends on how our prototype goes. I will reopen this issue once electron app moves beyond prototype. Keep your feedback coming. Thank you.

**Comment by abchatra** [comment]
Opening the issue after further discussion with @pelikhan

**Comment by OwenBrotherwood** [comment]
Use of --no-browser, to indicate no need for cookie warning.
NB: do not use electron as this is an implementation og not a type
`
    pxtMicrobit.pxtCore.mainCli(targetDir, ["serve", "--no-browser", "--electron"]);
`

**Comment by pelikhan** [comment]
Until we have an installer with a proper dialg to accept the terms of use, the notification has to stay.

**Comment by OwenBrotherwood** [comment]
At @pelikhan 's option, this issue can probably be closed.

As the present encapsulation apps require internet to access documentation, it can be still termed as requiring cookie accept.

Note:
I will be trying to encapsulate the documentation, such that documentation is available locally as I believe the internet documentation is generated from a repro ...(?)

**Comment by abchatra** [comment]
fixed?
