### ISSUE TITLE
"pxt init" doesn't work normally

### ISSUE THREAD

**Issue by lookUMA** [microsoft/pxt#6605]
![screenshot](https://user-images.githubusercontent.com/37033755/74601737-3c205300-50dc-11ea-83ea-3c2a1866265d.png)
i use “pxt init” to initialize a microbit extension project，but，it doesn't work normally, as the screenshot shows.What's the reason??

**Comment by pelikhan** [comment]
Fixed. Run npm install again and run pxt init again.
