### ISSUE TITLE
Chrome Extension is broken due to change to pxt.microbit.org from codethemicrobit

### ISSUE THREAD

**Issue by bennytheshap** [Microsoft/pxt#662]
The Chrome Extension is no longer able to receive data from the micro:bit via USB. Per @pelikhan, this is a regression due to the domain name change to pxt.microbit.org.

**Comment by pelikhan** [comment]
Update in progress.

**Comment by abchatra** [comment]
@pelikhan any update here?

**Comment by pelikhan** [comment]
Fixed.

**Comment by bennytheshap** [comment]
@pelikhan You sure this is fixed? I still can't make it work on Chrome on Mac.

**Comment by bennytheshap** [comment]
@pelikhan We are in a workshop with teachers and they *really* want this feature. Can you please prioritize fixing this? It would be so helpful for science and math teachers. Thank you!

**Comment by bhuangSFE** [comment]
Yes. This is a really important feature for educators and classroom use!

**Comment by abchatra** [comment]
Chrome extension is not a supported scenario from us today. 

I am interested to hear use cases. @bennytheshap @bhuangSFE Can you elaborate your scenario?
What do you do with chrome extension which can't be done with the web browser? Also what platform do you use (windows10\windows7\iOs\android\Linux\Mac)?

**Comment by pelikhan** [comment]
Chrome extension gives access to serial.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bhuangSFE** [comment]
@abchatra  -- There are several scenarios that come to mind. Here are a few:

* Debugging and feedback. We want to be able to quickly see data being gathered or not gathered on the micro:bit. Having a serial read-out within MakeCode is very helpful. Currently, we can use serial and then open a terminal (Serial Monitor in Arduino) to do this.
* Graphing and visualization. Math & Science teachers want to quickly be able to visualize the change in data vs. time. Basically the Serial Plotter feature that is in Arduino presently. These features were in MakeCode / PXT for a brief moment, but appear to be gone now. Can we revive this?

**Comment by bennytheshap** [comment]
@pelikhan it used to but hasn't worked for me in almost a year. Happy to do a screen share with you to demo/test.

**Comment by abchatra** [comment]
@bhuangSFE what platform you need it (OS)?

**Comment by bennytheshap** [comment]
@abchatra we have teachers on Windows, MacOS, and ChromeOS

**Comment by machinehistories** [comment]
is there any update on this I still am unable to use the chrome extension to stream serial to https://makecode.microbit.org/#. I think the path the extension points to might be incorrect.
