### ISSUE TITLE
update python docs

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#6644]
The first hit on "makecode python" goes to https://makecode.com/js/python which is outdated.

**Comment by ganicke** [comment]
Current search rank for "MakeCode Python":

**Bing**

![image](https://user-images.githubusercontent.com/27789908/75618847-88ca4c00-5b28-11ea-9599-e6f3dcd7a3dd.png)

**Google**

![image](https://user-images.githubusercontent.com/27789908/75618850-9384e100-5b28-11ea-94cd-e08f451e5e47.png)

**Comment by ganicke** [comment]
Python "landing" page is at https://makecode.com/python from #6646.
