### ISSUE TITLE
Documentation on logging in to GitHub

### ISSUE THREAD

**Issue by yjsoon** [microsoft/pxt#6666]
The [documentation on logging in to GitHub](https://github.com/Microsoft/pxt/blob/master/common-docs/github/getting-started.md) doesn't seem to work. It states to "Click on the GitHub button next to the Save button", which doesn't exist. The only way I've logged in so far has been through Extensions > Login to GitHub at the bottom of the page. Is this correct? I can create a pull request if so.

**Comment by yjsoon** [comment]
I should clarify, context is when seen on micro:bit MakeCode page: [Getting started with GitHub](https://makecode.microbit.org/github/getting-started)

**Comment by pelikhan** [comment]
Try makecode.microbit.org/beta

**Comment by abchatra** [comment]
Feature available in beta and will be released to live later.
