### ISSUE TITLE
WebUSB pairing UI is unwieldy

### ISSUE THREAD

**Issue by Geoffree3** [microsoft/pxt#6724]
Why does it requires 5 clicks in different parts of the screen to pair a micro:bit?
1) why do we have to be shown the "First time here" message a 1000 times? [solution: use a cookie to record if message has been shown]
2) why cannot a double-click on the micro:bit in the list connect (without having to press 'connect')? [solution: trap double-click]
3) if there is only 1 in the list (which appear to me to be the case all the time) connect automatically without have to select at all.

 - MacOS 10.14.6 
 - Chrome 
 - Version 80.0.3987.132

**Additional context**
This is exacerbated by the lack of maintaining multiple pairings (another issue)

**Comment by abchatra** [comment]
This is not a repo for microbit.
