### ISSUE TITLE
maintaining multiple connections with WebUSB

### ISSUE THREAD

**Issue by Geoffree3** [microsoft/pxt#6725]
When, creating or setting up projects which require multiple micro:bits (e.g. controller & receiver for a buggy) it would be reasonable to expect MakeCode/WebUSB to remember these. Currently, pairing more than one is inconsistent - sometimes I can keep up to 3 paired, for a while but often have to pair again (which requires 5 clicks in different parts of the screen and gets annoying as in issue #322!)

 - MacOS 10.14.6 
 - Chrome 
 - Version 80.0.3987.132

**Comment by abchatra** [comment]
This repo is not for microbit.

**Comment by Geoffree3** [comment]
sorry, I moved to pxt but forgot to delete.
