### ISSUE TITLE
Online Learning page

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#6749]
Love the Online Learning page!!! 🥇 
Here are a few things to fix:

[ ] Include Mixer and YouTube channel link.  "All videos will be live streamed on [Mixer ](https://mixer.com/MakeCode) and available for viewing later in the [MakeCode YouTube Channel](https://youtube.com/microsoftmakecode)".

[ ] Fix broken links:
         https://aka.ms/makecodearcadestreamcommunity doesn't go anywhere - suggest just pointing to https://www.twitch.tv/mr_isaacs/
         https://aka.ms/makecodeadafruitstream doesn't go anywhere either - change to https://aka.ms/makecodecpxstream

[ ] I might also suggest adding links to the video titles in the descriptions 
![image](https://user-images.githubusercontent.com/22108954/77357196-ff600100-6d04-11ea-8728-743955db0c02.png)

[ ] In the Educator Resources section, can we make the hyperlinked text a different color?  Right now it's a bit hidden.

**Comment by abchatra** [comment]
Fixed?

**Comment by Jaqster** [comment]
[ ] Remove Steve Isaacs from the Schedule and Stream Description
![image](https://user-images.githubusercontent.com/22108954/77956286-7efe4a80-7286-11ea-9535-551d96211a87.png)
![image](https://user-images.githubusercontent.com/22108954/77956363-99382880-7286-11ea-8be8-f11ba21490bc.png)

[ ] Add sub-headers under Live Video Streaming section for "Schedule" and "Description"

**Comment by Jaqster** [comment]
Using this same issue for another change request to add the Microsoft Stores "Digital All-Stars" stream.

[ ] Add a 2nd paragraph in the Live Video Streaming section: "Microsoft Stores is proud to host a MakeCode stream with all-star athletes passionate about technology and connecting with their communities.  This week, join Brandon McManus from the Denver Broncos as he helps you build your very own football arcade game with Microsoft MakeCode Arcade!"

[ ] Update the Mixer offline image to include the Digital All-Stars video series
![image](https://user-images.githubusercontent.com/22108954/78291733-c41aba80-74da-11ea-8994-f0d547a80dac.png)

[ ] Add a row for the Digital All-Stars stream to our schedule: use the link https://aka.ms/makecodeDASstream
![image](https://user-images.githubusercontent.com/22108954/78292389-ccbfc080-74db-11ea-8185-00da0c30edc2.png)

[ ] Under Available Streams, add a row for Digital All-Stars:
[Digital All-Stars](https://aka.ms/makecodeDASstream) 
12 PM PST / 3 PM EST
Join your favorite all-star athletes as they use MakeCode Arcade to code games with you at home!
Use this image - 
![Digital_Skills_Program_Star_RGB_R3_Overall_4x](https://user-images.githubusercontent.com/22108954/78293064-dac21100-74dc-11ea-8951-92d3b8e1e910.png)

**Comment by abchatra** [comment]
@ganicke

**Comment by Jaqster** [comment]
Hi there.  I got some good feedback from the advertising media team about our Online Learning landing page.  We're going to be driving page views as the primary metric, and Mixer + YouTube Playlist views as secondary metrics, so we need to make these CTA's a bit clearer.  
[Online Learning landing page v2.pptx](https://github.com/microsoft/pxt/files/4478365/Online.Learning.landing.page.v2.pptx)
![Microbit Playlist](https://user-images.githubusercontent.com/22108954/79285508-a0f4f100-7e72-11ea-9a9e-b63fbcbd93d7.png)
![Minecraft Playlist](https://user-images.githubusercontent.com/22108954/79285515-a7836880-7e72-11ea-9944-da06a924d0db.png)
![Arcade Playlist](https://user-images.githubusercontent.com/22108954/79285528-b0743a00-7e72-11ea-865a-6c81575b986a.png)
![Arcade Advanced Playlist](https://user-images.githubusercontent.com/22108954/79285532-b4a05780-7e72-11ea-9658-4351a5370765.png)
![MakeCode in the Kitchen Playlist](https://user-images.githubusercontent.com/22108954/79285545-bf5aec80-7e72-11ea-932f-61386ae98546.png)
![DreamSpace Playlist](https://user-images.githubusercontent.com/22108954/79285561-c71a9100-7e72-11ea-9f1b-3ee046924678.png)
Let me know if we can make these changes...

**Comment by shakao** [comment]
i'll do a pass!

**Comment by Jaqster** [comment]
Add John Park under the Video Playlist section.
[MakeCode with Adafruit's John Park](https://aka.ms/makecodejpstream)
Join Adafruit’s John Park as he builds a MakeCode project each week. Covers fundamental concepts and techniques using real-world projects in his studio.
![John Park Playlist](https://user-images.githubusercontent.com/22108954/79919846-02254300-83e4-11ea-9ad3-1286ab3a0606.png)

**Comment by Jaqster** [comment]
Requesting another update to the Online Learning Page - remove the Mixer link and iframe.
Does Twitch have an api/iframe we can use to embed the schedule or live videos?

Also, can we add the WeCodeMakeCode stream?
Title: WeCodeMakeCode
Link: aka.ms/makecodeWCMCstream
Description: Learn how to build cool Minecraft mods like Snoman vs. Monsters, and Arcade games like Hungry Snake with WeCodeMakeCode! For intermediate to advanced level.
Image: 
![WeCodeMakeCode playlist](https://user-images.githubusercontent.com/22108954/85963145-2b74c900-b969-11ea-9606-9514ee42c85d.png)

**Comment by pelikhan** [comment]
Yes they do. We can add it next week.

________________________________

**Comment by ganicke** [comment]
This is all pretty old. I think this was the 'tracking' issue for the effort at the time.
