### ISSUE TITLE
Open project shows packages

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#675]
https://github.com/Microsoft/pxt/issues/new
![image](https://cloud.githubusercontent.com/assets/6107272/20018585/86b96036-a285-11e6-94de-cc5357cbb06b.png)

**Comment by pelikhan** [comment]
microbit-cppsample is now gone.

**Comment by pelikhan** [comment]
Our search does not use the organization field yet.

**Comment by abchatra** [comment]
Fixed
