### ISSUE TITLE
Cookie banner in Teams

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#6757]
I still see the cookie banner appearing in the Teams iframe.  I thought we had taken this out?

![image](https://user-images.githubusercontent.com/22108954/77464097-e36f6480-6dc3-11ea-9e35-d28ce8684730.png)

**Comment by abchatra** [comment]
LEGO is not updated for long time

**Comment by abchatra** [comment]
Fixed in PXT but lego is in older builds
