### ISSUE TITLE
JavaScript functionality not matching Blocks

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#680]
We need to decide what we want to do here.  There are JavaScript functions we surface via intellisense, like basic.plotLeds, that aren't supported in Blocks.  Right now we give them the option to Discard, or stay in JavaScript.  Personally, I think we should always show the Blocks editor, and just grey out areas of the program that can't be displayed.

**Comment by pelikhan** [comment]
The "remove blocks file" option is gone.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Jaqster** [comment]
we chatted about this more, I think we're going to explore adding block support for functions and strings. we also discussed the ability to show a read-only grey block of code in the Blocks editor.  Need to discuss more and do some user testing here...

**Comment by pelikhan** [comment]
Ø  I think we're going to explore adding block support for functions and strings

This increases the complexity of the block editor. Is it worth it? If so, are Text and Functions going under “Advanced”?

**Comment by abchatra** [comment]
This is done.
