### ISSUE TITLE
Hex files downloaded from docs samples are annoyingly named

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#683]
They seem to be named `microbit-microbit-i.hex` where `i` is the index of the example in the current sidebar pane. Really, they should probably get named with the name of the project. We do include the project name in the `.hex` itself, so re-loading the project displays the correct name. However, it is confusing when you download a bunch of project files and they all have the same name in your downloads folder.

**Comment by abchatra** [comment]
Closing old issues. If this is still an issue please reopen.
