### ISSUE TITLE
Fixed Block Editor width/height

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#686]
do we want to set a fixed width/height for the block editor?  Just thinking that someone could get themselves in trouble with infinite workspace where they have parts of their program scattered all over the place (i.e. if you zoom out a lot, then zoom in).  Also, I'm not sure why there's no Top to the editor… I think people like to feel like there are boundaries to their workspace...
[enhancement]

**Comment by pelikhan** [comment]
We want to use as much screen estate as possible. The simulator is anchored to the left specifically to avoid "loosing" it to the far right.

**Comment by abchatra** [comment]
Closing this as we have plans to redesign the UI
