### ISSUE TITLE
AppCache is set to be depricated.

### ISSUE THREAD

**Issue by alexistbell** [microsoft/pxt#6870]
In Chrome I am receiving this warning:

> [Deprecation] Application Cache API use is deprecated and will be removed in M82, around April 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.

 This seems to be the code causing the warning:

`    function initAppcache() {
        if (typeof window !== 'undefined' && window.applicationCache) {
            if (window.applicationCache.status === window.applicationCache.UPDATEREADY)
                reload();
            window.applicationCache.addEventListener("updateready", function () {
                if (window.applicationCache.status === window.applicationCache.UPDATEREADY)
                    reload();
            });
        }
    }`

Whatever caching is needed will probably need to be handled by a service worker since this will stop working at least in Chrome in the near future.

 - OS: Mac 10.15.3
 - Browser Chrome 81.0.4044.113

Interestingly I didn't see this error when we had our an autogened service worker created by [workbox's webpack plugin](https://developers.google.com/web/tools/workbox/guides/generate-service-worker/webpack) however we couldn't fully load in pxt. We would get the start block, but the try with blocks would not load when running our app as a PWA. I'm not positive this caching strategy is what's causing our issues in the PWA, but everything loads fine when we are not caching with our service worker, and stops working when we add a service worker.

**Comment by jwunderl** [comment]
service workers added in https://github.com/microsoft/pxt/pull/6634 for the most part, but that does seem to be missing

@riknoll was there a reason I'm forgetting for https://github.com/microsoft/pxt/blob/master/webapp/public/run.html#L145 ? needs to be changed over / deleted I suppose

**Comment by abchatra** [comment]
@alexistbell we have service worker in latest PXT. Check #6634. App cache code is only for legacy browsers.

**Comment by alexistbell** [comment]
Thanks, I still saw the app cache code so I didn't realize a service worker had also been added. Looks like any remaining issues are my own.
