### ISSUE TITLE
Microbit 2020 Release blog post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#6925]
Hey Galen,
Can you start getting this blog post staged?
Files are here: https://1drv.ms/u/s!AmMIW5Hxi0RtgZt-YVpActBXQ2DoEg?e=jDIVuX
Thanks!
Jacqueline

**Comment by ganicke** [comment]
OK, woking on it: #6926

**Comment by Jaqster** [comment]
Can we publish this blog post today?

**Comment by pelikhan** [comment]
We can publish it during the show :)
