### ISSUE TITLE
Question: can I use makecode.com with minecraft JE on osx?

### ISSUE THREAD

**Issue by artemave** [microsoft/pxt#6959]
I have latest Minecraft JE and Code Connect For Minecraft on OSX Catalina, but there seem to be no `/connect` command available.

Am I doing something wrong, or is it just that osx users have been left out?

Thank you.

**Comment by abchatra** [comment]
Code connection only supports Minecraft Education Edition and Minecraft Windows 10 edition. It doesn't support JE edition.
