### ISSUE TITLE
pxt build repeatedly polling

### ISSUE THREAD

**Issue by luqmaanb** [microsoft/pxt#6979]
I've been developing extensions locally using .cpp files for a while and as of today `pxt build` repeatedly polls non stop. The .cpp file only contains a commented line.
![image](https://user-images.githubusercontent.com/38786673/81217993-c393a900-8fdd-11ea-90d2-98045b9cdb31.png)

pxt.json
```
{
    "name": "CS11",
    "version": "0.0.0",
    "description": "",
    "dependencies": {
        "adafruit-metro-m0-express": "*"
    },
    "files": [
        "README.md",
        "main.blocks",
        "main.ts",
        "sdmm.cpp"
    ],
    "testFiles": [
        "test.ts"
    ],
    "public": true,
    "supportedTargets": [
        "maker"
    ],
    "preferredEditor": "blocksprj"
}
```

sdmm.cpp
`//`

Yes, in the file is just a comment.
main.ts is empty and all other files generate with `pxt init` is default.

What's wrong?
Thanks

**Comment by abchatra** [comment]
Thanks for pointing out. This should be fixed. Though remove .cpp files if doesn't have any code. Typescript doesn't require cloud compile.
