### ISSUE TITLE
language choice in project settings

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#699]
Language choice in project settings: the name of the language should be in the form used by the language

- Currently, a browser link choice (that should be retained)
- Language choice should be "live", allow flip/flop between language choice without incurring too long a change in the project being worked on.

- As an englishman living abroad, l would like to choose a language that is not based on the default language of the browser.
- As a teacher, I would like to follow the english examples of block programs 
- As a child, I would like to easily use my primary language
- As a student, I prefer english in order to follow other examples and advance my skills

Almost forgot, the setting will then support language choice in non-browser versions of pxt

**Comment by OwenBrotherwood** [comment]
Getting critical as half translations aren't good with no obvious switch to pure english

![image](https://cloud.githubusercontent.com/assets/866122/22039043/f09c8778-dcfd-11e6-85c0-caf37f9c5a29.png)

**Comment by OwenBrotherwood** [comment]
@whaleygeek this should not be an enhancement in context to RC for foreign countries. Some more comments on pxt slack

**Comment by OwenBrotherwood** [comment]
https://pxt.microbit.org/beta/?lang=da may be the switch, or some well-known (but for my brain cells) forgotten switch with a lang identity to be able to choose between english and some other language.

In current context, the use of the foreign language ability (if still present) can be useful for introduction, but for a teacher reading internet articles which are based on English blocks, the efforts required to translate into what they may see on their screen due to default language is not "nice".

I can make an effort to find a pure danish Windows 10, but I am english, living in denmark, which gives a non standard setup which is "bad" to give qualified feedback.
ie: the screen dump at top of issue is my understanding of what will be seen on a pure danish Windows 10 (or other OS) machine if the current beta is still "international" with either a correct translation of all blocks (start and forever are not danish) or a removal of all international lang efforts for RC.

An RC with the current perceived implementation of lang isn't "good"

**Comment by OwenBrotherwood** [comment]
This is a forced german version: danish doesn't seem to be available with lang=da or lang=dk despite being available in January

**THIS IS NOT A FEATURE REQUEST FOR DANISH.**
Rather a clear method to ensure that teachers are able to relate to examples of pxt that are written in english to their own browser environment that is often international: ie not-english

Without some switch that is intuitive, then there are extra burdens on the teachers.

![image](https://cloud.githubusercontent.com/assets/866122/23161314/f62940c2-f829-11e6-8209-889937918e65.png)

**Comment by abchatra** [comment]
+1 for this. We need an option to change the language. We will prioritize this.

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/1993  Will be available in beta soon.
