### ISSUE TITLE
Only simulated data in simulator

### ISSUE THREAD

**Issue by damianburrin** [Microsoft/pxt#70]
I have the serial driver installed am running Chrome over Windows 10 and following the Seismograph demo to ensure i'm not being silly.  

I only see the simulated data, the second live data from the microbit doesn't appear on screen.  Is this not functioning or am i being daft.

Thanks
Damian

**Comment by pelikhan** [comment]
Installing the driver is not enough, unfortunately. Currently, to get serial data in the browser, you would need to do one of the following:

- install PXT locally and run through the local node.js server
- compile the Windows 10 (under /windows) and run this app locally
- install the Chrome extension (https://chrome.google.com/webstore/detail/extension-for-bbc-microbi/cihhkhnngbjlhahcfmhekmbnnjcjdbge?hl=en-US)

**Comment by damianburrin** [comment]
Ah that's a bummer

I have the driver and already had the extension installed – however i’ve not got PXT installed locally.  This makes it a no go for me i guess as i’m developing lessons to use at school and we have to use the vanilla web based versions – no local installs.

The docs/lesson online might need an update to reference that this needs a local install too.  (unless i’m misunderstanding what your saying)

**Comment by pelikhan** [comment]
Hold on, if you have the Chrome extension installed it should work (famous developer words). It might well be that the extension does not support yet m.pxt.io. It was designed for microbit.co.uk.

**Comment by damianburrin** [comment]
Yes definitely have the chrome extension installed - I just tried and couldn't get the flipping thing to work via the microbit website either so I guess i'm doing something wrong somewhere.
Does it require a specific chrome version i'm running 50.0.2661.102 m but will update and test again

**Comment by pelikhan** [comment]
The chrome extension needs to be updated, so hold on until i update this bug.

**Comment by pelikhan** [comment]
The addin now works with m.pxt.io. Please make sure you are running **0.4.0**.

**Comment by damianburrin** [comment]
Cheers Peli,

Just testing this and i must be doing something wrong as it just doesn’t work for me.

This is my setup
Current version of chrome
Serial mbed driver installed and running on com8 (9600,8,N,1) (i have tried at other speeds)
extension installed and confirmed at 0.40

I’m only getting the simulated data – no live data at all.

Any ideas greatly appreciated.

Thanks
Damian

**Comment by damianburrin** [comment]
Ah right found a solution.

The serial port must be the first available port.  Forced it to change to COM3 and working.

Damian

**Comment by pelikhan** [comment]
Are you using
https://chrome.google.com/webstore/detail/extension-for-bbc-microbi/cihhkhnngbjlhahcfmhekmbnnjcjdbge?hl=en-US

?

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by damianburrin** [comment]
Yes – but think it’s resolved now.  You seem to have to make sure you use the first availalbe com port.  Forcing Com3 give me data and works.

Thank you

Damian

**Comment by pelikhan** [comment]
That's what I am confuse avoid. The add on should take care of those details. Are you running another serial monitor?

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by damianburrin** [comment]
>Are you running another serial monitor?

Nope – nothing else at the moment.  I think it gets confused as I have several Micro bits and everyone has a different driver and comes up as a separate com port yet I only have one plugged in at a time.

Damian
