### ISSUE TITLE
Scrollbars too thick on Touch devices

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#702]
See screenshot
![screenshot_20161105-171834](https://cloud.githubusercontent.com/assets/16690124/20034506/122e9b20-a37d-11e6-8880-e3cb289196c4.png)

**Comment by clowrey** [comment]
Related to this is having a button to hide/disable the simulator while in mobile would be helpful as it can take up too much screen space.

**Comment by microsoftsam** [comment]
Blockly issue.

**Comment by microsoftsam** [comment]
Also repro's on all touch devices.

**Comment by carlosperate** [comment]
I realise this issue was opened a long time ago, but could we keep them at the current size for the reasons mentioned in https://github.com/Microsoft/pxt/issues/702 ? (small scrollbar is hard to use)

**Comment by microsoftsam** [comment]
Yeah thinking more about it, I tend to agree with your Carlos.

**Comment by abchatra** [comment]
Current behavior seems ok for me.
