### ISSUE TITLE
support for data files

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#708]
The possiblity of data files that can be used by a program 
Probably something that should be given thought to as to how to create a general solution.

**Comment by abchatra** [comment]
Is this same as the request for the filesystem? We have a repo https://github.com/microsoft/pxt-filesystem, If not, please add complete details.

**Comment by abchatra** [comment]
Can you please add additional information for this issue so it is actionable?

**Comment by pelikhan** [comment]
This is copied from slack: Jonny suggested to be able to add data files in the project (e.g. Text file) and we would automatically pre-populate the filesystem with those files when flashing the device.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by OwenBrotherwood** [comment]
I will review pxt-filesystem and come with some use cases to make actionable and at MS option, create the use case/issue in pxt-filesystem so this issue can be closed. 
Pelikan can close if he believes that pxt-filesystem should be used.

**Comment by pelikhan** [comment]
Please move this issue to Microsoft/pxt-filesystem.
