### ISSUE TITLE
Can't add a block from extension to Math category

### ISSUE THREAD

**Issue by abegel** [microsoft/pxt#7138]
When I create an extension in MakeCode Arcade that defines a new block in the 'math' namespace, I expect the block to appear in the pre-existing Math category. Instead, MakeCode creates a new category with the same name "Math" with my new block in it, and displays it right after the pre-existing Math category. 

It should just add my extension's block to the pre-existing Math category.

**Comment by MKleinSB** [comment]
Did you lowercase math? Name it: namespace Math

**Comment by MKleinSB** [comment]
`namespace Math {

    //% blockId=emptyfunction block="empty"
    export function empty(): void {
    }

}
`

**Comment by abegel** [comment]
I had lowercased the Math namespace because I had to lowercase other namespaces when I added blocks to them (e.g. Sprites and Scene). Changing it to uppercase fixed the problem. 
So now the real problem is the inconsistency between namespaces, I guess.

**Comment by riknoll** [comment]
The name has to match the name of the namespaces in code. Math is the only uppercase one because it's uppercase in JavaScript, the rest are lower case by convention.
