### ISSUE TITLE
.hex not cached in web app

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#733]
The beta version still downloads .hex files from the cloud, triggering a compilation.

![image](https://cloud.githubusercontent.com/assets/4175913/20139653/02d6a2be-a63c-11e6-8a83-460e81dcc128.png)

**Comment by abchatra** [comment]
Is this electron app scenario?

**Comment by pelikhan** [comment]
Web editor.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
default .hex files are now part of the web manifest.
