### ISSUE TITLE
Arcade Update blog post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#7338]
Hi Galen,
Can you prep this Blog Post for the Arcade update release?
Files are here - https://1drv.ms/u/s!AmMIW5Hxi0RtgZ0okT1MpP3XrK7A3w?e=7jcEXF
Not sure if the "Magic Code Snippets" feature is in or out...  ask the rest of the team to review/edit.
Thanks!
Jaq

**Comment by ganicke** [comment]
Sorry I didn't see this until this morning. I'll have to finish it up in this evening since I have to grab a flight to Wisconsin on COVID Airlines in about an hour.

https://github.com/microsoft/pxt/tree/arcade-update-blogpost
