### ISSUE TITLE
Some doc pages open in new tab instead of side panel

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt#7377]
This isn't a comprehensive list, but here are a few that open in a new tab instead of in the side doc panel:

**Functions**

* return block
* created function blocks

**Text**

* join

**Comment by ganicke** [comment]
Pushing this back on the bug stack ...

Seems that the help requests for some of the built-ins is different than others. The CDN based requests open in the sidedocs while the direct doc links open in a new page. Not sure if this is something related to the info set in ``installBuiltinHelpInfo()``? I didn't get as far as to debug what was happening with the requestor.

Context help request for **text.join**:

`https://arcade.makecode.com/reference/text/join`

Context help request for **text.substr**:

`https://pxt.azureedge.net/api/md/arcade/reference/text/substr?targetVersion=1.1.5&cdn=20200807`
