### ISSUE TITLE
Compiling C++ code never succeeds

### ISSUE THREAD

**Issue by philipphenkel** [microsoft/pxt#7435]
It looks like the C++ build service is down again. Since yesterday polling for C++ builds has not been successful.
Like in #5286 the system is continuously polling for the C++ build.

I'm working on a tiny extension called [pxt-serial-read](https://github.com/philipphenkel/pxt-serial-read). Neither the local "pxt test" completes nor does MakeCode ever finish the compilation. 

`polling C++ build https://makecode.com/compile/c7c754b68aa09d9d9bc66bf25033c01edb2c5ea23511e38b24f0a33f812e5d85.json`

![Screenshot 2020-08-28 at 21 47 51](https://user-images.githubusercontent.com/828416/91609710-30a9c080-e978-11ea-8b4c-67b5fd6ecf05.png)

**Comment by abchatra** [comment]
We are taking a look at this issue. Fix will be up by Monday. 

Meanwhile you can do the local setup for compilation.

**Comment by philipphenkel** [comment]
@abchatra It's still consistently failing. 
Will the build be cached on your servers when it is working again? Would one compile be used to serve different users/MakeCode clients through that cache?

**Comment by abchatra** [comment]
This is fixed. Yes we cache the build after compilation.

**Comment by philipphenkel** [comment]
Thanks a lot. It works like a charm now.
