### ISSUE TITLE
shared loop variable not reinitialized properly

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#744]
Here is a repo. The assert triggers
```
let k = 0;
for (var i = 0; i < 1; ++i) {
    k = i;
}
for (var i = 0; i < 1; ++i) {
    k = i + 5;
}
basic.showNumber(k);
control.assert(k == 5);
```

**Comment by abchatra** [comment]
Seems like the initialization in the second loop is peeped out. I will take a look. Works fine with 'let' instead of var though as it introduces a separate scoped variable for each let instance.

**Comment by mmoskal** [comment]
The problem is that all `i` share node-id except for the second `var` which is different. If TS introduces a new node id for the second `var` they should also resolve the following references to it.  Maybe this is fixed in more recent TypeScript. Should we try to merge 2.1?

**Comment by abchatra** [comment]
In JavaScript var is not block scoped and both var refer to the same var. Redeclaration is no-op.

**Comment by mmoskal** [comment]
Sure. Which is why all the node-ids should be the same.

**Comment by abchatra** [comment]
Yes makes sense.. Though I do want to remove 'var' and just allow 'let' for language semantics perspective.

**Comment by pelikhan** [comment]
As long as we have a nice error message saying "change 'var' to 'let'"

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/780
