### ISSUE TITLE
Path following and distance between sprites

### ISSUE THREAD

**Issue by Dahbix** [microsoft/pxt#7541]
Hello again! I stumbled over another issue! I was working on my game and I wanted to use the distance between 2 sprites for this:
Kill Range ( Not having to overlat to kill) (works perfectly fine)

There is red (me) and green (enemy). Green is the killer. If I am in a certain radius then Green should follow me. If not he should follow his path. But here is the problem: He does follow me when I am in range and he stops following me when I am not in range, but he just stops and does not follow his path... 
This is the code piece (path is already set)
![image](https://user-images.githubusercontent.com/73031484/96608301-8015c880-12f9-11eb-8fa7-82f91a4a264e.png)
Hope you can help me
Thanks!!

**Comment by abchatra** [comment]
Incorrect repo. Arcade issue tracker is here:  [Microsoft/pxt-arcade](https://github.com/microsoft/pxt-arcade/issues/new?labels=bug&template=bug_report.md).
