### ISSUE TITLE
Colors and Sound efffects

### ISSUE THREAD

**Issue by Dahbix** [microsoft/pxt#7543]
Hello!
A part of making a game is making the game look very nice. But it is hard because you only have 15 colors. And making pixelart is not that easy anyway and without colours to make shadows and stuff it is really hard. Please add more colors to the programm! Please also add oppacity for them! So you can make see through glass and slight shaddows as well as clouds and rain!
Here are some examples for colors:
Dark red
Dark yellow/ orange
Different grey tones
Different green tones and
Light skin tone

And another thing! Sound effects! (they dont have to sound realistic just arcade style) For example:
Different walking sounds (on hard ground or stuff like grass)
Customizable Win/Loose sounds
Alarm sounds
Breaking sounds (glass, rock...)

I will keep on posting my ideas and issues!
Thanks!

**Comment by abchatra** [comment]
Incorrect repo. Arcade issue tracker is here:  [Microsoft/pxt-arcade](https://github.com/microsoft/pxt-arcade/issues/new?labels=bug&template=bug_report.md).
