### ISSUE TITLE
[identity] Backend: Renew refresh token

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt#7631]
- [x] Wait for email responses to "Proposal for handling small async tasks in the MakeCode backend"
- [x] Schedule meeting to discuss
- [x] 1 day time box Service Bus prototype
  - see: https://github.com/microsoft/pxt-backend/tree/dazuniga/service_bus
- [ ] cost estimate work

**Comment by eanders-MS** [comment]
this is done!
