### ISSUE TITLE
Blocks in docs rendering cut off

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#765]
[Edge] Repro: Resize browser window to size where the sidebar content pane just disappears.  Open Smiley Project, then pull screen size out so content pane appears.
![docs cutoff](https://cloud.githubusercontent.com/assets/22108954/20232417/2f231e00-a81d-11e6-8172-c9ec0213dbe6.PNG)

**Comment by microsoftsam** [comment]
Does this still repro? @abchatra

**Comment by abchatra** [comment]
Does not repro for me
