### ISSUE TITLE
Compiling C++ code never succeeds (3rd) 

### ISSUE THREAD

**Issue by philipphenkel** [microsoft/pxt#7651]
It looks like the C++ build service is down again. Since yesterday polling for C++ builds has not been successful.
It's a recurring issue every couple of months: Like in #7435, #5286 the system is continuously polling for the C++ build.

This my project that is currently failing and I have not done any updates to the native dependencies since weeks:
https://makecode.microbit.org/_1T1dTVYyY3zY

**Comment by abchatra** [comment]
This is fixed.

**Comment by philipphenkel** [comment]
@abchatra Thanks for the quick fix.
