### ISSUE TITLE
The blog is translated by default

### ISSUE THREAD

**Issue by thepian** [microsoft/pxt#7673]
I went to the blog to read more information, and it comes up as German. I can read it, but that's horrible. Written by an American and translated into a language that is painful to read, why? Why is there no way to shut off this horrible idea.

**To Reproduce**
1. Go to https://makecode.com/blog/one-chip-to-flash-them-all when you are in a non-english speaking IP.
2. Try to skim through the post, good luck.

**Expected behavior**
The original article in English please.

**Screenshots**
![Bildschirmfoto 2020-12-01 um 16 04 44](https://user-images.githubusercontent.com/72638/100757749-05a79080-33ef-11eb-9448-d9e10c0c67ed.png)

**Comment by pelikhan** [comment]
@Jaqster FYI, disable translations for the blog?

**Comment by Jaqster** [comment]
I don't understand, why is the Blog automatically translated but our pages (like HoC) are not?  We should be consistent in how we localize content.  Ideally I'd like to see a language menu in the header of all our content pages so people could read in whatever language they prefer.  Adding @abchatra and @ganicke

**Comment by pelikhan** [comment]
Thanks for reporting. Fixed.
