### ISSUE TITLE
CS Ed Week Blog post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#7680]
Hey Galen, 
Can you help me prep a Blog Post for CS Education Week?
Would like this to go out on Friday if possible.
Files are here: https://1drv.ms/u/s!AvnYExTCocXPigwmiSQRbxP8awsG?e=NOOAhD
Let me know if you have any questions.
Thanks!
Jacqueline

**Comment by ganicke** [comment]
I can, doin' it now...
