### ISSUE TITLE
building a string to send over serial

### ISSUE THREAD

**Issue by damianburrin** [Microsoft/pxt#77]
Not really a fault just can't figure out if this can be done in pxt

When you want to send data over serial so you can log it via azure (very cool)  if I want to send two or more pieces of data I do have to do something like    
 serial.writeNumber(input.temperature()); or  serial.writeValue("temp", input.temperature()); followed by an identical line for say the accelerometer and then any other sensors I want to stream out. 

This means in the excel file you get the temp and acc data on alternate lines with a null value between them as they are written seperatly and not as a single output.

In python or C i'd build a string for each line to send out as a csv file so both pieces of data get written at the same time and then appear in the same row of the CSV/Excel file.

Is there a way I can build a string in a similar way using the blocky so I have more control over the way the data appears in the excel file?

Thanks
Damian

**Comment by pelikhan** [comment]
We are working on adding "Text" category to the block editor. Stay tuned.

**Comment by abchatra** [comment]
This should be address by https://github.com/Microsoft/pxt/issues/531. Closing this as duplicate
