### ISSUE TITLE
constantly crashes when connecting Minecraft Bedrock to CodeConnection and running any of MakeCode tutorials

### ISSUE THREAD

**Issue by kochede** [microsoft/pxt#7738]
Just bought Minecraft Bedrock for PC, running on Windows 10 with all latest updates, latest Minecraft version 1.16.201, downloaded latest CodeConnection. 
- Start CodeConnection, start Minecraft, execute "/connect 192.168.1.153:19131" in Minecraft chat, connects ok
- click any tutorial in CodeConnection (e.g. "Flower Trail"), use MakeCode/Blocks language, put the simple code for tutorial and click Play button (triangle)
- go to Minecraft and try to use the code from the tutorial
- it will run for ~30 seconds and then Minecraft crashes and closes silently. Every time, no exclusions. Tutorials that don't continuously execute code (e.g. a 1-time action call) - may work (if they run shorter than ~30sec)

**Comment by abchatra** [comment]
@kochede does this still repro? We are unable to reproduce this problem.

**Comment by MicahM-MSFT** [comment]
We've been using code connection pretty regularly over the last month due to https://dev-mc.visualstudio.com/Minecraft/_workitems/edit/442147 and haven't seen this bug.

**Comment by kochede** [comment]
Yes it still crashes and not only for me - please see this Mojiang bugtracker issue: https://bugs.mojang.com/browse/MCPE-113355
"Community confirmed", multiple people reported the same.

**Comment by MicahM-MSFT** [comment]
Thanks for the link. I've been replying to a thread in Teams about this bug - sorry for not updating this item, we did find a bug in "on player moved" which will be fixed in the next Minecraft Bedrock release. The linked MCPE seems to be much more widespread than what we saw, so we are investigating that now.

**Comment by ducktalesAWWOOOWOO** [comment]
@MicahM-MSFT Any approximate date for next bedrock release to see this bug fixed which is affecting makecode please?

**Comment by MicahM-MSFT** [comment]
@ducktalesAWWOOOWOO @kochede - Update 1.16.210 was released yesterday and includes this fix.

**Comment by kochede** [comment]
> @ducktalesAWWOOOWOO @kochede - Update 1.16.210 was released yesterday and includes this fix.

Thanks for the update!
