### ISSUE TITLE
missing microbit maqueen extension feature

### ISSUE THREAD

**Issue by Jocoder2** [microsoft/pxt#7741]
I was using the microbit maqueen extension at https://makecode.microbit.org/#editor when I noticed its RGB lights on the underside of the unit are not available on the makecode editor. I am using this for compatibility via radio with another microbit, but the loss of this feature from mind+ to makecode is disappointing, and means for projects where using makecode is not essential, i will use mind+, despite makecode's significantly better ease of programming.

**Comment by abchatra** [comment]
@Jocoder2 you need to contact maqueen extension developers for this. This is not an issue on MakeCode AFAIK
