### ISSUE TITLE
Radio transmit/receive sometimes does not work

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#776]
microbit.org-ticket:276
pxt.microbit.org version: 0.6.13
tested: 15 NOV 2016 10:35

A simple radio transmit and radio receive between two micro:bits does not seem to work any more.

TX.hex looks like this

![screen shot 2016-11-15 at 10 31 29](https://cloud.githubusercontent.com/assets/4086785/20302521/884dbc10-ab1f-11e6-807f-b80d09b48491.png)

RX.hex looks like this

![screen shot 2016-11-15 at 10 32 23](https://cloud.githubusercontent.com/assets/4086785/20302536/97af6b18-ab1f-11e6-8ab7-ecf6a970c5eb.png)

Zip of hex files TX RX and also a 'radio-ping-pong' that still works if loaded into both micro:bits.

[files.zip](https://github.com/Microsoft/pxt/files/591678/files.zip)

**Comment by pelikhan** [comment]
Are these used as separate files? The group is autoamatically set based on a hash of the program so it might have worked by luck unless "set group" was used.

**Comment by whaleygeek** [comment]
Yes, they are separate files. That makes sense @pelikhan I was wondering why some scripts worked and some did not. It also explains some very strange behaviour we were seeing with teleporting ducks a few weeks ago, where some radio interactions worked and some did not.

I see that this fact is indeed documented in the official PXT documentation.

https://pxt.microbit.org/reference/radio/set-group

**Comment by martincottrell** [comment]
Does the set group block exist in the block editor. It vanished a while ago?

Sent from my iPhone

On 15 Nov 2016, at 11:49, David Whale <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, they are separate files. That makes sense @pelikhan<https://github.com/pelikhan> I was wondering why some scripts worked and some did not. It also explains some very strange behaviour we were seeing with teleporting ducks a few weeks ago, where some radio interactions worked and some did not.

I see that this fact is indeed documented in the official PXT documentation.

https://pxt.microbit.org/reference/radio/set-group

-

**Comment by whaleygeek** [comment]
Yes, it's still there, it's in the ADVANCED bit underneath radio

![screen shot 2016-11-15 at 12 11 59](https://cloud.githubusercontent.com/assets/4086785/20305300/bf49d412-ab2c-11e6-837f-08c6520ca55e.png)
