### ISSUE TITLE
Docs issue: broken links in `docs/writing_docs` area

### ISSUE THREAD

**Issue by skfd** [microsoft/pxt#7797]
Theses pages have broken links:
* https://github.com/microsoft/pxt/tree/f12637e112e46acda74e76248755f15ee0ff18aa/docs/writing-docs/user-tutorials.md
* https://github.com/microsoft/pxt/tree/f12637e112e46acda74e76248755f15ee0ff18aa/docs/writing-docs/tutorials.md
* https://github.com/microsoft/pxt/tree/f12637e112e46acda74e76248755f15ee0ff18aa/docs/writing-docs/testing.md

They are missing `docs/` prefix and sometimes `.md` ending for individual files. There might be more files with broken links, this is not a complete list

**Comment by Jaqster** [comment]
Hmmm... @ganicke can you take a look?
