### ISSUE TITLE
Hover Text / Help window for blocks are not correct

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#78]
Looked at help text which shows as hover text and the Help Window on all the blocks. These are not correct (probably copy / paste errors) or could be improved.
- [x] Input -> "On Shake" -- saying "on screen up" but default is "on shake". Maybe more of a generic message is needed instead
- [x] Input -> "compass heading" -- duplicate "compass" in the text
- [x] Input -> "rotation" -- only mentions "pitch". Similar to "on shake" .. maybe should also mention "roll"?

**Comment by abchatra** [comment]
This is fixed and merged.
