### ISSUE TITLE
Arcade Jan Release Blog Post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#7818]
Hey Galen,
Can you get this blog post prepped and ready to go for tomorrow?
I still want to record a short demo video for animations to include too, but I'll send that to you later.
All the files should be posted here: https://microsoft-my.sharepoint.com/:f:/p/jacqchen/EkGWC0qv5MtDqKYsqNXB6VIB4X4m9awlZOlQuG_KS-AEUA?e=liq5ye
Let me know if you have any issues accessing.
Thanks!
Jacqueline

**Comment by ganicke** [comment]
OK, but I don't think you have enough images in there yet.
