### ISSUE TITLE
"open with ..." and "logo" are not clearly different and leads to user confusion

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#782]
In sandbox mode, we have 2 buttons in the corner that lead to different places. Attendees were confusing and though it was a single button.

Propose solution: have 1 single purpose which is reopen in the full editor.

![image](https://cloud.githubusercontent.com/assets/4175913/20331918/5c66417e-ab5d-11e6-8e8c-614fa8999bb3.png)

**Comment by abchatra** [comment]
Yes makes sense
