### ISSUE TITLE
AP CS Principles landing page

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#7830]
Hi Galen,
Can you post this landing page for the new curriculum that's coming out?
Thinking to put it here: http://makecode.com/csp 
Once the curriculum materials are done, we can add the link for the downloads.
Content files for the landing page are here: https://microsoft-my.sharepoint.com/:f:/p/jacqchen/Ep-LqBN5cKBLiEE8b92dbf4BnY0aNtbRGb33nslxbYxC3w?e=rK8OzW
Let me know if you have any questions.
Thanks!
Jacqueline

**Comment by ganicke** [comment]
Thanks @jwunderl! :relieved:
