### ISSUE TITLE
Scroll image with unexpected result on actual device (Calliope)

### ISSUE THREAD

**Issue by thinkberg** [Microsoft/pxt#788]
This code should show "Ich /Heart scrolling/ IT!"
It does work in the Simulator, however, on the actual device the heart is not scrolled, but simply pops in quickly scrolled away by "IT!"

```
let Herz = images.createBigImage(`
    . # . # . . . . . .
    # . # . # . . . . .
    # . . . # . . . . .
    . # . # . . . . . .
    . . # . . . . . . .
    `)
basic.forever(() => {
    basic.showString("Ich")
    Herz.scrollImage(1, 200)
    basic.showString("IT!")
    basic.pause(1600)
    basic.clearScreen()
    basic.pause(1000)
})
```

**Comment by abchatra** [comment]
Ported to calliope as well https://github.com/Microsoft/pxt-calliope/commit/566326ea17b9fdb909f285ff630a46ca90a01815
