### ISSUE TITLE
opposite of parseInt(x)

### ISSUE THREAD

**Issue by damianburrin** [Microsoft/pxt#79]
Hi,

parseInt(x) takes a value in string form and converts it to an in. Is the an equivalent that casts and int back to a string.  I thought String() did this in Javascript but this doesn't seem to work.

Thanks
Damian

**Comment by pelikhan** [comment]
Try ``basic.showString(123 + "")`` in javacsript.

**Comment by damianburrin** [comment]
Thanks. Will look again but im not trying to show the string im trying to build a single string i can send via serial.
Will keep looking tho
Thanks
Damian
On 8 Jun 2016 15:09, Peli de Halleux <notifications@github.com> wrote:Reopened #79.

**Comment by pelikhan** [comment]
serial.sendString(123 + “”)

**Comment by damianburrin** [comment]
Yeah, looks like that should work.  I can certainly send what i want to a serial port and putty.  The problem now is the chrome app/azure link is so flaky i can’t actually get it to work reliably .

Will keep trying but getting to the point where it’s to frustrating and I’d not be able to trust it to work in a school environment and kids.

Thanks anyway
Damian

**Comment by damianburrin** [comment]
>serial.sendString(123 + “”)
This works with sending data to the serial port but the chrome app/azure refuses for upload data sent in this format.

I must be looking at this the wrong way, al i'm trying to do is generate an upload stream to azure that looks something like

Timestamp   temp   direction
date/time       21       280
date/time       21       275

You can't do this as two separate write statements otherwise you get something like
Timestamp   temp   direction
date/time       21       null
datetime       null        280
datetime       21         null
datetime      null        275

**Comment by mmoskal** [comment]
Will make `String(42)` work

**Comment by thomasdenney** [comment]
@mmoskal Nope, that doesn't compile to blocks or ARM

**Comment by mmoskal** [comment]
In fact it's quite complicated to do this, as it requires turning `namespace String` into `var String: ...`. I will instead present a reasonable error message for this.

For reference, here's a patch that starts to implement the `var String` change.

[newString.patch.txt](https://github.com/Microsoft/pxt/files/360983/newString.patch.txt)

**Comment by thomasdenney** [comment]
Perhaps parseInt and toString methods could be added as part of a series of Text blocks, as suggested is in development [here](https://github.com/Microsoft/pxt/issues/18).

**Comment by mmoskal** [comment]
Sounds good. I think we can use `(42).toString()` in translation, or even expose the radix parameter of `toString()`. I think different base systems are part of what students are supposed to learn, so it would be fitting.
