### ISSUE TITLE
Streamer support for Skill Map

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#7903]
The Microsoft Stores Team love Streamer, and want to use it to present their online workshops and summer camps which will be using the Skillmap.
Could we add Streamer support for Skillmap?
Right now we pop the Skillmap experience out into another tab...

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/pxt/pull/7904

**Comment by pelikhan** [comment]
@Jaqster tell me if this is enough.

**Comment by Jaqster** [comment]
Good for now, thanks Peli, didn't see the Skillmap option.  I think we should re-think the navigation to the Skillmap experience, but that's not a Streamer issue.

**Comment by pelikhan** [comment]
Just added :)
