### ISSUE TITLE
Blog Post - Arcade Spring Update

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#7987]
Hey Galen,
Can you prep this blog post for the Arcade spring update?
I'm just waiting to hear back about whether to include a quick video demo of Immersive Reader.
Files here - https://1drv.ms/u/s!AmMIW5Hxi0RtgZ54Arm5NGmT1IlvpA?e=gz9pTP
Thanks!
Jacqueline

**Comment by ganicke** [comment]
On it now.
