### ISSUE TITLE
Right Click>> Help: Missing Page - Control

### ISSUE THREAD

**Issue by RickGMSR** [Microsoft/pxt#8]
Add Create Big Image
Right Click on the control
Click Help
Result: Page not found
![image](https://cloud.githubusercontent.com/assets/15837908/13883697/da00f9f6-ece7-11e5-9128-6408225d4f9f.png)

**Comment by thomasdenney** [comment]
I no longer get a 404 for [this page](https://codethemicrobit.com/reference/images/create-big-image) this issue can be closed.
