### ISSUE TITLE
Space in project name is invalid. Why?

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#802]
and if so, can we auto fix, by adding an underscore. 
Or at the very least doing some minor client side validation when editing the project name. 

![screen shot 2016-11-22 at 4 41 09 pm](https://cloud.githubusercontent.com/assets/16690124/20547680/a2275f84-b0d2-11e6-88ee-4946d6221887.png)

**Comment by abchatra** [comment]
Sam: This is only localhost issue
