### ISSUE TITLE
Error loading a project leads to data loss

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#803]
I was finally able to repro an issue where we crash and clear the main.ts file losing the user's data. 

Repro steps: 
1. Create a project. 
2. Change the project name to an invalid name (something with a space) 
3. Reload the page. Pxt will complain about unable to load the file. 
4. Reload the page again. Pxt will clear all your data and even if you change the file name to something valid again, your script is lost.

**Comment by pelikhan** [comment]
Is this a "localhost" only problem? I can rename the project with space without issues.

**Comment by microsoftsam** [comment]
Yeah it appears so.
