### ISSUE TITLE
Some blocks don't have a reference doc

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#805]
We need to make a pass at our functions and ensure we have reference docs for all blocks:
To name a few: 

Math pick random true or false block 
Math pick random 0 .. X block 
Math text from char code
Math absolute of 

and for those that we don't want to support reference docs for, we need to remove the button click on their help cards. Similar to what we do with many of the "game" blocks.

**Comment by microsoftsam** [comment]
Math’s block don’t have explanation in the “?help” either.

**Comment by ganicke** [comment]
Doc pages added or help enabled for missing topics in:

* https://github.com/Microsoft/pxt-microbit/pull/530
* https://github.com/Microsoft/pxt/pull/2781
* https://github.com/Microsoft/pxt/pull/2846
* https://github.com/Microsoft/pxt/pull/2872
