### ISSUE TITLE
location of projects folder

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#806]
Is it possible to dictate the location of the projects folder in a --non-browser scenario?
The placement may be the cwd of the process starting the pxt(-microbit) and this may not allways be writable by the user in a --non-browser scenario.

From: https://www.pxt.io/cli
> If you have created a PXT project from the web browser, you can go to its folder (it will sit under myworkspace/projects but feel free to move it up one level) and use the CLI to build and deploy it.

https://github.com/Microsoft/pxt/issues/807

**Comment by abchatra** [comment]
Answered
