### ISSUE TITLE
Copy-pasting code into a Python editor sometimes adds indents.

### ISSUE THREAD

**Issue by SquareFingers** [microsoft/pxt#8086]
**Describe the bug**

Copy-paste into the Python editor mode adds indentation to some lines.

**To Reproduce**

1. Go to https://makecode.microbit.org/ or https://minecraft.makecode.com/ or https://arcade.makecode.com/ (or, I imagine, any other makecode where Python is an option)
2. Open a Python editor
3. Paste the following into the editor:
```
letters = ["A",
    "B",
    "C",
    "D"]
numbers = ["1",
    "2",
    "3",
    "4"]
```
4. See an extra indent on the line in the middle:
```
letters = ["A",
    "B",
    "C",
    "D"]
    numbers = ["1",
    "2",
    "3",
    "4"]
```

**Expected behavior**

What the system pastes into the editor is what ends up being in the editor.

**Additional context**

After pressing ctrl-V and getting the result described, if I press ctrl-Z once, the unsolicited and unwanted indent disappears!  It appears the ctrl-V causes two events, first, the code is properly deposited in the window, and second, the bug indent is added.  Pressing ctrl-Z once appears to undo the second event.

Also reported in https://github.com/microsoft/pxt-microbit/issues/3936, but since it's not just in micro:bit makecode but also in other makecode sites, I figured here's a good place to raise the issue.

**Comment by abchatra** [comment]
I am closing this as duplicate #3936. Once we fix there it will propagate to all other editors.

**Comment by SquareFingers** [comment]
... Have you looked at https://github.com/microsoft/pxt/pull/3936 ?

**Comment by abchatra** [comment]
microsoft/pxt-microbit#3936,

**Comment by SquareFingers** [comment]
Aha.  That makes more sense.
