### ISSUE TITLE
Compile steps dialog is confusing

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#81]
When you hit "Compile" button a dialog pops up that actually causes confusion.

It has these steps on it.
1) Connect USB
2) Save hex to computer
3) Copy hex file to microbit drive
4) Wait until Yellow LED is done blinking

Some things about this:
- [ ] Doesn't really say where in the process the compile is actually happening. Closer inspection that this dialog is about moving code to device AFTER the compile. We should put a line that says "Compile is done! Now time to put it on the device."
- [ ] Step 2 might have the user looking for a way to save hex in the UI. In reality, the user is getting it from the downloads folder
- [ ] Maybe Step 2 and Step 3 could be combined into a "copy hex from downloads folder to microbit drive"
- [ ] For step 4 ... I was looking for a yellow blinking light on the UI. I have done this process many times so I know the yellow light is on the device so I know better but still made me confused. I then realized, "oh ... the yellow LED on the device". We should state to wait for the yellow blinking LED on the microbit to stop

**Comment by pelikhan** [comment]
Step 2: in many browsers, saving requires a manual step form the user (save confirmation dialog). This could be optimized per browser.

**Comment by pelikhan** [comment]
Step 4: "We should state to wait for the yellow blinking LED on the microbit to stop" Isn't that what we are saying?

Note that this is a balance between trying to explain the process and having kids not reading dialogs.
