### ISSUE TITLE
Help for scrollImage goes to showImage

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#812]
pxt.microbit.org version: 0.6.13

Hover box for scroll image looks like this...
![scroll_image](https://cloud.githubusercontent.com/assets/4086785/20667270/50d714fc-b560-11e6-887b-235f58635c9b.png)

Click on it, and I get the showImage page:
![goes_to_show_image](https://cloud.githubusercontent.com/assets/4086785/20667280/5e12ff1e-b560-11e6-8476-7e6714d94d92.png)

Should go to this page instead:
![actual_scroll_image](https://cloud.githubusercontent.com/assets/4086785/20667285/68d9a682-b560-11e6-8b5b-133adc43434e.png)

**Comment by pelikhan** [comment]
Fixed by https://github.com/Microsoft/pxt-microbit/commit/77003b30f2dcb96fa835e084d24f87f59b735427
