### ISSUE TITLE
Negative scroll does not seem to work

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#813]
microbit.org-ticket: 384

Help says this:

![actual_scroll_image](https://cloud.githubusercontent.com/assets/4086785/20667327/92df3226-b560-11e6-9e87-ef00d666ab39.png)

Attached hex file, I can't get button B to scroll when pressed. If I change the offset to 1, it scrolls in the normal direction. If I change the scroll offset to -1, the screen stays blank.

[microbit-ticket_384.hex.zip](https://github.com/Microsoft/pxt/files/616130/microbit-ticket_384.hex.zip)

**Comment by abchatra** [comment]
Yes, negative scroll is not yet implemented in both simulator and backend. Negative scroll may be bit confusing to the user as this requires left to right animation. Note strings always scroll right to left.

**Comment by whaleygeek** [comment]
Thanks @abchatra - although the documentation (screen shot included above) states that negative scroll is supported, I think the users were just following the documentation, to be honest. Thanks!

**Comment by abchatra** [comment]
Yes @whaleygeek , either documentation needs update or we need to support left to right scrolling. I will keep this open until one of those are fixed.

**Comment by jaustin** [comment]
Negative scroll is supported in DAL and we do have cases of users trying it and finding it not working, so I'd much prefer restoring this behaviour.
