### ISSUE TITLE
Download button gets lost when using small screen and microbit radio/serial

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#814]
Using pxt on a smaller screen (say, a school laptop), using the radio causes another micro:bit to show up in the simulator.

This pushes the download button off the bottom of the scree, but there's no visible scrollbar.

**Comment by jaustin** [comment]
![image](https://cloud.githubusercontent.com/assets/147113/20676955/749cbd96-b589-11e6-9a45-3decd20f81a4.png)

Here's an example of a problematic case.

**Comment by microsoftsam** [comment]
@jaustin, What browser is this on?

**Comment by jaustin** [comment]
Originally observed it in IE (not sure of the version and I'm not there any
more) but my screenshot is from Chrome on macOS Sierra.

**Comment by microsoftsam** [comment]
The issue here is that macOS Lion + hides scrollbars when not in use. We can override this functionality with some css trickery.

**Comment by microsoftsam** [comment]
This is still occurring on Edge.
