### ISSUE TITLE
Couple changes to the toolbar button

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#82]
One of the first things that people will do after they try the sample is to create a new project. The tool bar space should be reserved for things that people will do more often. 
- [ ] New Project should be on the tool bar - brand new users won't look in "more" for this
- [ ] I think Open Project should be on the tool bar too ... kind of goes with New
- [x] Embed should be moved to the "More" menu.

**Comment by darrenge** [comment]
Looking at "Embed" ... I see that also covers "Publish". Maybe it should be on toolbar but it is just confusing that is where you publish something

**Comment by pelikhan** [comment]
Needs to be discussed.

**Comment by mmoskal** [comment]
I don't mind either way.

**Comment by abchatra** [comment]
We have moved the Open Project on the toolbar and kept the new Project inside the more menu. Closing this.
