### ISSUE TITLE
Music only available on P0

### ISSUE THREAD

**Issue by jamesadevine** [Microsoft/pxt#823]
Could an advanced block be exposed to change the Pin for music?

**Comment by abchatra** [comment]
I am not sure blocks are the right place. Typescript API needs this for sure.

**Comment by pelikhan** [comment]
You can control the music output via an advanced block ``pins.analogSetPitchPin``.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-microbit/pull/309
