### ISSUE TITLE
Nested for loops in TypeScript

### ISSUE THREAD

**Issue by jamesadevine** [Microsoft/pxt#825]
I made these loops in blocks, and converted to Javascript, note the iterator name: 
![screen shot 2016-11-30 at 13 45 33](https://cloud.githubusercontent.com/assets/4742697/20754543/4c1bad3e-b703-11e6-8c3b-76631deaf3f7.png)

**Comment by jamesadevine** [comment]
Note, fixes itself when you convert back and forth

**Comment by abchatra** [comment]
@jamesadevine 'let' is block scoped for the for loop and hence there is no function issue here right?

**Comment by jamesadevine** [comment]
Right, from a C/C++ background this is invalid. I guess my point here is that although this is valid typescript, for loops in other languages would reject this syntax. As PXT is meant to provide support for learning programming, it would be great if it taught core concepts in a way that is transparent across languages.

What are your thoughts @abchatra ?

**Comment by abchatra** [comment]
@jamesadevine Yes agree, it is better to simplify by specifying a different iterator name.
