### ISSUE TITLE
Micro:bit 2021 Release Blog Post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#8273]
Hi Galen,
Can you get this blog post prepped for release?
Hoping to release tomorrow (Friday 6/25)
All files here - https://1drv.ms/u/s!AmMIW5Hxi0RtgZ8Sz5hMvcR4ND8kdg?e=0wcNBP
Thanks!
Jacqueline

**Comment by ganicke** [comment]
Sure, I'll to it this afternoon.
