### ISSUE TITLE
Blocks sometimes move when switching between Blocks/JS even with no editing

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#828]
If I start with a simple blocks programme, go to look at the Typescript and then switch back to the blocks, the blocks change from being specifically arranged to being all 'in a row' 

This doesn't *always* happen - sometimes you can switch back and forth and things stay in place.

The following procedure seems to reliably cause things to rearrange:

Start a new script
Drag in an 'on radio received' block and *don't* dock it with the default 'forever' loop:
Click 'Javascript'
Click 'Blocks'

Your blocks will be rearranged
Before JS
![image](https://cloud.githubusercontent.com/assets/147113/20766499/a0b0f31a-b72e-11e6-9547-393711c5b8fd.png)

After JS
![image](https://cloud.githubusercontent.com/assets/147113/20766516/aa3222e2-b72e-11e6-98c4-ec9a2651f2c6.png)

I've noticed that if the event handlers have things in them they're less likely to move around

**Comment by pelikhan** [comment]
When decompiling blocks from JS, we loose position and grouping. This is what you are seeing. In most cases, people do not make changes to the JS and we are able to reuse the version of the blocks that still have positioning in them.

The flow for converting JS to blocks is as follows:
- decompile JS to blocks
- recompile decompiled blocks to JS
- if both javascript output are the same, use previous version of the blocks that still contains positions.
- else use new decompiled blocks.

**Comment by jaustin** [comment]
Based on your explanation, I think the blocks shouldn't re-arrange in the case I described because the JS code hasn't changed - IE the round-trip should result in something identical.

Even without that bug, It would also be really nice in the long run for there to be a bit more granularity in the process, so that if I change one 'group of blocks' that might lose the location information, but others would I stay. From what you've said, that would certainly involve changing the way you currently do things, but possibly not with too much difference. For example, having some comment in JS that 'located' a block would allow people to code nice blocks arrangements in JS and still publish them, etc.
