### ISSUE TITLE
Makecode Streamer - Cameras Off

### ISSUE THREAD

**Issue by sgiles009** [microsoft/pxt#8284]
Hi Team, 
Hope I am in the right place. We were wondering if you would be able to switch off the cameras in Makecode Streamer, to allow the full screen to be seen and worked with, with no camera on?

Thank you in advance.

**Comment by pelikhan** [comment]
You'll find an icon in the tools to disable the webcam 
![image](https://user-images.githubusercontent.com/4175913/125442015-af213148-641a-4417-bd28-985da1f39d11.png)

**Comment by sgiles009** [comment]
Legend!
