### ISSUE TITLE
Getting Started button does nothing in IE11

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#841]
This is going to be blocker for beta->release. IE11 is our second most user base.

**Comment by abchatra** [comment]
@microsoftsam Can you please take a look?

**Comment by microsoftsam** [comment]
Ill take a look tonight.

________________________________

**Comment by microsoftsam** [comment]
IE has the "light" pxt option switched on, which means there is no side docs. 
The getting started button was implemented only for the side doc.
We have two options here: 
- Remove the getting started button in IE. 
- Support opening the getting started docs in a new page

**Comment by pelikhan** [comment]
Ø  Support opening the getting started docs in a new page
+1 on that. Sidedocs were put under the “light” mode to help with startup time. It might not be relevant anymore. However, we still have the problem of smaller screen used in schools (can we get this data from App Insights?). I suspect a lot of school still running on low-res screens.

**Comment by abchatra** [comment]
+1 for the _Support opening the getting started docs in a new page_
Though in long term we need a solution for IE11.
