### ISSUE TITLE
UX Design Exploration: First-time user experience for the MakeCode ecosystem

### ISSUE THREAD

**Issue by soniakandah** [microsoft/pxt#8454]
Why should our users use MakeCode over our competitors? What is our hook? 

We need to understand our top user personas as well as 

- Their top pain points 
- What they are most looking for? And are we providing it?
- What are some unarticulated goals/wishes they might have that we can infer? 
- What is the ideal first user experience for MakeCode, Arcade, Micro:Bit, and Minecraft?

@BeckHaru for visibility

**Comment by unthinkmedia** [comment]
@soniakandah  is this a dup of https://github.com/microsoft/pxt/issues/8475
