### ISSUE TITLE
show string with double slash // displays backslash \ on micro:bit

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#846]
When using show string block with either pxt.io or newest github, text with `//` is shown as backslash `\`
Example
`a\\c`
gives
`a/c`

---

Found while debugging eddystone beacons
https://github.com/Microsoft/pxt-microbit/pull/315

**Comment by abchatra** [comment]
Simulator works fine. Microbit shows a/c for a\\c

**Comment by microsoftsam** [comment]
Microbit shows \ for // in showString

**Comment by microsoftsam** [comment]
Looked into this and this is a bug in the DAL.

**Comment by microsoftsam** [comment]
lancaster-university/microbit-dal#258
