### ISSUE TITLE
PXT not descheduling on pause() ?

### ISSUE THREAD

**Issue by finneyj** [Microsoft/pxt#847]
Guys,

When working with some schoolkids, noticed a semantic difference between a 'forever' loop in Blocks and a 'while true' containing a 'pause' block when using micro:bit. The former deschedules a fiber, whereas the latter seems to busy wait... 

See attached HEX file for repro case. (Event handler on button press never fires). This behaviour is observable on both simulator and micro:bit hardware.

[microbit-Spintest.zip](https://github.com/Microsoft/pxt/files/631637/microbit-Spintest.zip)

**Comment by pelikhan** [comment]
Indeed, forever spins up a new fiber. It should be equivalent to 
```
control.runInBackground(() => {
    while(true) {
           f()
           basic.pause(20)
})
```

See https://github.com/Microsoft/pxt-microbit/blob/master/libs/core/basic.cpp#L117

**Comment by finneyj** [comment]
Right... and I think I wouldn't expect this code to busy wait (i.e. spin such that other fibers can't get in)... I would expect the pause() to yield control to other runnable fibers:

```
 while(true) {
           f()
           basic.pause(20)
}
```

This doesn't seem to be the current behaviour.

**Comment by pelikhan** [comment]
spin test:
```
while (true) {
    basic.pause(100)
    if (input.buttonIsPressed(Button.A)) {
        led.plot(0, 0)
    } else {
        led.unplot(0, 0)
    }
}
input.onButtonPressed(Button.B, () => {
    basic.showLeds(`
        . # . # .
        . # . # .
        . . . . .
        # . . . #
        . # # # .
        `)
})
```

**Comment by finneyj** [comment]
@pelikhan of course - so the event handler is never registered in this case... Interesting.

This looks fine for TypeScript, but feels counter intuitive in Blocks as moving the physical position of the blocks on the screen changes semantics. i.e. if the event handler block is to the left/above the while loop, the behaviour is different...

**Comment by pelikhan** [comment]
The BBC blocks compiler used to compile the event handlers "before" the code in "main" to handle this very common scenario.

**Comment by riknoll** [comment]
I agree that we should move top-level "floating" event handlers to the top. We should still allow non-floating handlers like this to remain intact:
![non-floating](https://cloud.githubusercontent.com/assets/13754588/20898897/f8670d54-badc-11e6-9687-b348d677745a.PNG)
