### ISSUE TITLE
Confusing behaviour when two event handlers are provided

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#850]
![image](https://cloud.githubusercontent.com/assets/147113/20894312/cc2a3ace-bb0c-11e6-8b36-acc42ef83e9a.png)
This program: only 'X' is ever printed
..but in this program
![image](https://cloud.githubusercontent.com/assets/147113/20894373/0c78bd26-bb0d-11e6-9066-59095b0ac2ed.png)
only 'yes' is ever printed.

Aside from the discussion in #849 , we could perhaps grey out the handler that isn't going to fire?

![image](https://cloud.githubusercontent.com/assets/147113/20894460/7d90aa32-bb0d-11e6-9f6c-a0056cdaaf9b.png)
Ideally we should also explain why it isn't firing!

**Comment by pelikhan** [comment]
This feature is live.
