### ISSUE TITLE
Tutorial update Blog post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#8519]
Hey Galen,
Are you back?  Saw some activity from you earlier...
Let me know if you can help with this blog post.  
https://1drv.ms/u/s!AmMIW5Hxi0RtgZ8shIqL5jX5WbWucw?e=tSEaWH 
No worries if not, I can get it posted.
Let me know.
Thanks!
Jacqueline

**Comment by ganicke** [comment]
I'd like to work on it. Might have to crash nap in between doing all of it. You get these sudden fatigue attacks and your brain stops working. Ha.

**Comment by abchatra** [comment]
Glad you are doing better than before @ganicke  Take care

**Comment by ganicke** [comment]
Thanks @abchatra, doing really good today. No fevers for about 3+ days now. Really thankful for that!
