### ISSUE TITLE
Change in simulator size lead to catastrophic blinking

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#853]
![bugreport](https://cloud.githubusercontent.com/assets/4175913/20898806/8d0c3b6a-badc-11e6-81da-84195655f7c7.gif)

For some reasons the scrollbar decide to appear and dissapear constantly. It might be due to intermediate react changes messing up the scroll.

**Comment by microsoftsam** [comment]
Can you try and see if this repro after the the fix for #814

**Comment by pelikhan** [comment]
Cannot repro for now.
