### ISSUE TITLE
colorized prettyprint of JS in PXT docs

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#86]
Let's make the JS look very nice in the docs. This is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/10767146/16075998/4ff1eb76-32bf-11e6-8d7a-ef4d22f0faeb.png)

**Comment by thomasdenney** [comment]
Resolved as of [this commit](https://github.com/Microsoft/pxt/commit/b62a9dc3b8f102d92835e83a445a144e9839fb8b). Syntax highlighting is done with the [highlight.js](https://highlightjs.org) library and is done server side. The colouring scheme is the same as Visual Studio.
