### ISSUE TITLE
Switching back to blocks after adding textspeed parameter drops the parameter

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#864]
On the PXT beta

Steps to reproduce:
Go to pxt.microbit.org/beta
Click 'Javascript', add the following code
```javascript
input.onButtonPressed(Button.A, () => {
    basic.showString("Hello!", 500)
})
```
Verify that this runs in the simulator and the text scrolls fast
Click 'blocks'
Notice that the script now looks like this:
![image](https://cloud.githubusercontent.com/assets/147113/20924820/5c066278-bbab-11e6-82f9-114f7d2f4d38.png)

Click "Javascript" again. The scroll speed parameter has been dropped
```javascript
input.onButtonPressed(Button.A, () => {
    basic.showString("Hello!")
})
```
We should never lose data when switching between blocks and JS!

**Comment by jaustin** [comment]
Happens on 'vanilla' (non-beta) pxt.microbit.org too

**Comment by riknoll** [comment]
I see three options:

1. Check the block definition and bail out if a parameter isn't used
2. Store the parameter in a mutation for the block to persist it across the roundtrip (block would look the same but behave differently than it normally would)
3. Mutate the block to add a field for the duration

I think I prefer option 1, but the other two are pretty easy to implement as well.

**Comment by pelikhan** [comment]
let's start with 1 and add instrumentation to see if users frequently hit this limitation.

**Comment by jaustin** [comment]
As well as the fix for this (thanks!), is there also a more general 'check
we didn't mess things up' process that could happen?

For example after converting to blocks but before throwing away the current
JS buffer do a final blocks-->JS conversion and check the code is the same?
We'd need to think through user flows if this check FAILs but I'd say any
user flow we come up with is better than silently losing data.

This would be 'insurance' against other bugs/subtleties that might creep in
and cause people to lose code.

J

**Comment by pelikhan** [comment]
We use to do this double-rountrip but it also problematic, specially around variable declarations and code indentation. We have a decompiler test suite that we should beef up over time.
