### ISSUE TITLE
Linking yotta target @ github

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt#8650]
**Describe the bug**
As of the deprecation of yotta I had to link `yottaTarget` ind `pxtarget.json` to GitHub.
I changed it from `calliope-mini-classic-gcc` to `calliope-mini-classic-gcc@https://github.com/calliope-mini/target-calliope-mini-classic-gcc#v1.2.0-yotta`. 

The compilation works, but pxt is adding the GitHub url to the path when it tries to link the CXX executable:
```
*** Build failed: target build failed: ENOENT: no such file or directory, open 'built/yt/build/calliope-mini-classic-gcc@https://github.com/calliope-mini/target-calliope-mini-classic-gcc#v1.2.0-yotta/source/pxt-microbit-app-combined.hex'
Error: ENOENT: no such file or directory, open 'built/yt/build/calliope-mini-classic-gcc@https://github.com/calliope-mini/target-calliope-mini-classic-gcc#v1.2.0-yotta/source/pxt-microbit-app-combined.hex'
```

Placing a symlink to meet the path requirement is not possible.
I also tried to first compile, then change the `yottaTarget` back and run PXT again in hope that it will not compile again. But that does not work. ~~The PXT CLI Manual is mentioning the parameter `nur` to serve without building, but when I tried to use it, PXT claims it does not know this parameter: https://makecode.com/cli/serve~~ (Edit: found out it was translated, the correct parameter is `just`. But does not help either.)

**To Reproduce**
1. Download V4 Branch from https://github.com/calliope-edu/pxt-calliope/tree/V4
2. `npm i`
3. Change `yottaTarget` in `pxtarget.json` to `calliope-mini-classic-gcc@https://github.com/calliope-mini/target-calliope-mini-classic-gcc#v1.2.0-yotta`
4. `export PXT_NODOCKER=1`
4. `pxt serve --local`

**Expected behavior**
PXT should try to open `built/yt/build/calliope-mini-classic-gcc/source/pxt-microbit-app-combined.hex` instead of `built/yt/build/calliope-mini-classic-gcc@https://github.com/calliope-mini/target-calliope-mini-classic-gcc#v1.2.0-yotta/source/pxt-microbit-app-combined.hex`

**Desktop**
 - OS: Linux and windows

**Additional context**
I did not use Docker, since Yotta was not able to access the public repositories from GitHub. For windows and Linux I had to add `YOTTA_GITHUB_AUTHTOKEN` to the env variables. 

This issue is related to https://github.com/lancaster-university/microbit-targets/issues/6

**Comment by abchatra** [comment]
@riknoll can you take a peek here? Related to the new way of fetching the yotta packages?
