### ISSUE TITLE
Projects and "More" don't show a tooltip

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#866]
The Projects and "More" dropdown in the main menu don't show a tooltip. 

![screen shot 2016-12-06 at 10 18 49 am](https://cloud.githubusercontent.com/assets/16690124/20937825/6fb82cd8-bb9d-11e6-9124-57544c406540.png)

**Comment by pelikhan** [comment]
Not using the Semantic tooltips for those. It had rendering issues. We should stick to simple "title" tooltips.
