### ISSUE TITLE
Language menu says JavaScript while TypeScript is used

### ISSUE THREAD

**Issue by Markos-Th09** [microsoft/pxt#8666]
**Describe the bug**
The languages switcher has two languages, python and "javascript". In reality the javascript option is typescript.

**To Reproduce**
1. Go to any makecode page
2. Use the programming language switcher
3. Choose JavaScript
3. Write some invalid TypeScript which is valid JavaScript
4. Realize that the JavaScript option is really TypeScript 

**Expected behavior**
It should either be pure javascript or the JavaScript option should be replaced with TypeScript

**Screenshots**
<img width="791" alt="Editor" src="https://user-images.githubusercontent.com/87304130/150685326-3a7b0517-98e5-4cbc-a1fb-b02780a5d432.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 97

**Comment by abchatra** [comment]
Our language specification is here: https://makecode.com/language
It is subset of typescript known as static typescript optimized and compiled to run on tiny hardware.

No teacher or student knows about typescript. It is easier for us to communicate the language as JavaScript (typescript is superset of JavaScript anyway). Usually, students learn text coding by transition from the blocks and we do two-way translation from blocks to text and text back to blocks to help with the same.

**Comment by Markos-Th09** [comment]
> Our language specification is here: https://makecode.com/language
> It is subset of typescript known as static typescript optimized and compiled to run on tiny hardware.
> 
> No teacher or student knows about typescript. It is easier for us to communicate the language as JavaScript (typescript is superset of JavaScript anyway). Usually, students learn text coding by transition from the blocks and we do two-way translation from blocks to text and text back to blocks to help with the same.  
> 
> 

It is just confusing to students to need to learn about typing.

**Comment by Markos-Th09** [comment]
I understand why it needs to be statically typed.
