### ISSUE TITLE
There is no way to remove or hide a sprite in blocks on microbit

### ISSUE THREAD

**Issue by gingemonster** [Microsoft/pxt#870]
If you create a sprite using the game module there is no way to hide or remove it from the block editor.

in Javascript you can do:

sprite..off()

but that doesn't convert back to blocks.

**Comment by pelikhan** [comment]
Try this. Agreed that "delete" should be available in blocks.
![image](https://cloud.githubusercontent.com/assets/4175913/20949622/28ed2646-bbcf-11e6-8480-ffcb28b4d83d.png)

**Comment by pelikhan** [comment]
![image](https://cloud.githubusercontent.com/assets/4175913/21019010/f14bb7ce-bd23-11e6-93fa-e888f61f8fe3.png)

**Comment by dulwichcollegeit** [comment]
I have just tried this and the delete block doesn't delete the sprite. I have changed the JavaScript to sprite.off() and this works as expected.

**Comment by pelikhan** [comment]
Did you try this in beta?

**Comment by dulwichcollegeit** [comment]
I have only tried this at https://pxt.microbit.org/

**Comment by pelikhan** [comment]
Please try it at https://PXT.microbit.org/beta it should have the fix

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dulwichcollegeit** [comment]
Thanks Peli, yes it works fine in beta. Is there a schedule for moving beta into production?
