### ISSUE TITLE
Skateboard arcade

### ISSUE THREAD

**Issue by mrbotts** [microsoft/pxt#8714]
Just wanted to share skateboard arcade that my students are developing.  
![D7EA996B-13AF-476A-931C-38693CC2736C](https://user-images.githubusercontent.com/52546557/154202243-5c7fd463-7922-421b-872b-457de972f880.jpeg)
![327F9834-F1E6-4A76-831E-28A6B1162D52](https://user-images.githubusercontent.com/52546557/154202257-567bf00e-5a0f-4078-b75c-e38d9d98b10a.jpeg)
![63CF1D0C-54BD-40AA-8547-02364F3E23CD](https://user-images.githubusercontent.com/52546557/154202266-0bd72cdf-7478-4efd-b693-6fcc3ece9641.jpeg)

**Comment by Jaqster** [comment]
Wow @mrbotts !  This is incredible work!!  Would you be interested in sharing on our Forum?  I know a lot of our community would love to see this :-)  https://forum.makecode.com/c/share-your-arcade-projects-here/5
