### ISSUE TITLE
Python String split()

### ISSUE THREAD

**Issue by bsiever** [microsoft/pxt#8752]
**Describe the bug**

MakeCode doesn't support `split()` on Python strings. 

**To Reproduce**

The Python approach does not work as expected:

```
text = "these are words with spaces between"
words = text.split(" ")
# Should print 6
serial.write_number(len(words))
serial.write_line("")
# Should print "these"
serial.write_line(words[0])
```
It prints 0 and a blank line. 

(https://makecode.microbit.org/_adM289RVYT0c)

**Expected behavior**

The above is expected to print 6 and "these".  
Hopefully it would work nearly the same as the JavaScript/TypeScript version:

```
let text = "these are words with spaces between"
let words = text.split(" ")
// Should print 6
serial.writeNumber(words.length)
serial.writeLine("")
// Should print "these"
serial.writeLine(words[0])
```

(https://makecode.microbit.org/_DJtKae3MMbie)

**Additional context**

This issue has been reported by multiple users on the MakeCode micro:bit forum:  https://forum.makecode.com/t/am-i-missing-something/4659/6

The `py_string_split` seems to be un-implemented: https://github.com/microsoft/pxt/blob/200f402518d66e4fecccc6e044916bbe6779495b/libs/pxt-python/pxt-python-helpers.ts#L149

There are differences in the Python string `split()` behavior vs. JavaScript's string `split()`:
* JavaScript's behavior: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split
* Python's behavior: https://docs.python.org/3.3/library/stdtypes.html#str.split

Perhaps the basic behavior (valid separator) could be supported initially and variations would result in an error?  I believe that behavior is consistent between the two, so `py_string_split` could just use the JavaScript/TypeScript `split`.

**Comment by riknoll** [comment]
Fixed in live
