### ISSUE TITLE
Unable to add a comment to a block on IE

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#88]
IE specific as works on Chrome.

The "Add Comment" option is grayed out. Maybe there is a technical reason it is disabled on IE. Usually you want to disable something in a manner that there is a way to enable it and in this case it isn't clear. 

Repro:
* IE
* Right click on a block
** Notice - add a comment is grayed out

**Comment by pelikhan** [comment]
Not supported by blockly.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by darrenge** [comment]
It works on Chrome ... odd it doesn't work on IE. Not big fan of just leaving it grayed out without the user knowing what to do with it. However, not a big deal and will close this out.

**Comment by pelikhan** [comment]
The blockly team does not have windows so they don’t really test for IE support.
