### ISSUE TITLE
User feedback: Where does initialization code go?

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#883]
Hour of Code, 07/12/16, Darrington HS

Students struggled with understanding what order the disjoint blocks would run in, and where to add initialization code.
I found that students had a tendency to have code blocks in their workspace that they didn't need to use, but didn't want to delete. (more for reference).

We need: 
- A better way to conceptualize where code initialization goes. Maybe a start / begin block. Where code starts. Event handlers can still go anywhere in the workspace, but all initialization code starts at "start"
- A good way for students to have code in their workspace but not run, ie: ability to disable code blocks. I know we used to have this feature, and maybe we can think of a better way of disabling code than 'disable' in the context menu.

Let's discuss.

**Comment by abchatra** [comment]
👍

**Comment by jaustin** [comment]
I think this is probably very related to #849 and #850 too. The ability to have code that doesn't run is great too, would love to see some more visual confirmation that the code won't run!

**Comment by EdNutting** [comment]
Maybe just show disconnected blocks in a translucent version when they're not connected to a section of code which will run? (ie a forever block or event handler) I like the idea of a begin block.

**Comment by abchatra** [comment]
We have a On Start block now.
