### ISSUE TITLE
User feedback: Better game interface

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#884]
Hour of Code, 07/12/16, Darrington HS

The game interface is bad. It's confusing for kids to wrap their head around OO programming within PXT. 
If we want to keep that. The create block should atleast come coupled with a "Set variable to" block, as you're always going to want to do that. 

Also, game sprites are super buggy when working together with LED plot blocks.

Interesting feedback: HS students want to make games!

**Comment by pelikhan** [comment]
Feel tree to rewrite a new game package so that we can sunset the existing APIs.

**Comment by abchatra** [comment]
Won't fix for now.
