### ISSUE TITLE
User Feedback: Saving, Duplicating and Projects

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#886]
Hour of Code, 07/12/16, Darrington HS

Saving projects isn't intuitive to many kids even though there's a big download button. To them the "Download" button is used for getting a file onto the microbit. The file is of a not so familiar type (.hex) to them, and so they don't quite make the jump that the file includes the source and can be shared / saved. 

We should have a card in the "projects" menu that allows them to save their project as a file. Could be .zip or .pxt. 

Also, it would be nice to have the ability to duplicate projects.

**Comment by jaustin** [comment]
@microsoftsam do people understand 'save' and 'save as' do you think? That's the thing that's most natural to me but 'save' and 'duplicate' might be more sane to kids. 

I really agree with this one too!

**Comment by abchatra** [comment]
+1 zip file format so that there is no multiple prompts for various files.

**Comment by pelikhan** [comment]
Kids know "remix" from scratch which effectively is duplicate. Importing a file is also always duplicating.

**Comment by pelikhan** [comment]
We already have LZMA. It's fairly easy to compress the entire project files into a JSON payload. Bringing zip would further fatten the IDE.

**Comment by pelikhan** [comment]
We can use https://www.npmjs.com/package/jszip

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt/pull/890

**Comment by pelikhan** [comment]
Save button will be surfaced in this change: https://github.com/Microsoft/pxt/pull/1052

**Comment by abchatra** [comment]
Original issue of request of save is completed. Any format other than .hex is reserved for future.
