### ISSUE TITLE
Replace all links to Curriculum materials with GitHub Edu Verification gating

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#8888]
Need to go through and replace all the OneDrive links with Edu Teacher gating.
https://microsoft.github.io/makecode-csp/
For example - 
![image](https://user-images.githubusercontent.com/22108954/172229516-91a22fab-24b2-42e4-8b27-d9eb7e920032.png)

RE: https://github.com/microsoft/makecode-csp/issues/65#issue-1240392356 Task 3

**Comment by ganicke** [comment]
What's the auth gate URL and format for doing this?

**Comment by Jaqster** [comment]
@jwunderl knows...

**Comment by Jaqster** [comment]
Actually, hold off on this Galen.  I want to talk to Kelli first...

**Comment by Jaqster** [comment]
Okay, closing this issue.  Talked to Kelli, and it's fine to point to the individual files - there should be no solutions keys in there.
