### ISSUE TITLE
Default for HSL (L=100) always generates white

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#889]
microbit.org-ticket: 456

Customer has reported that having a default value of 100 for L, means that the RGB equivalent is always white (as opposed to HSV which does not suffer this side effect). The UX of this is therefore slightly strange, because changing H or S does nothing with the default value for L=100.

Could I suggest perhaps setting default L=50 so that then any change to any of the 3 parameters will make a visible change to the output?

![screen shot 2016-12-08 at 15 27 00](https://cloud.githubusercontent.com/assets/4086785/21015937/afbcbb86-bd5b-11e6-8945-b7fb29378b0f.png)

**Comment by whaleygeek** [comment]
Also the colour swatches for HSL on this page, make it obvious that this is indeed the case for L=max:
(under heading Swatches/HSL)

https://en.wikipedia.org/wiki/HSL_and_HSV

**Comment by pelikhan** [comment]
Fixed in 0.2.5. https://github.com/Microsoft/pxt-neopixel/commit/af3a651b8e20b39316512532e7097e0cfc5748d6

**Comment by whaleygeek** [comment]
Great, thanks very much for your help, I'll let the customer know, they will be pleased!
