### ISSUE TITLE
Adding comment has a few issues with the layout and interaction

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#89]
Could put them into separate bugs but decided to just put them all in one as it is kind of a GUI issues with the comments.

Issues:
- [ ] Clicking on "Add comment" should automatically open the comment block. It currently just adds the "?" to that block
- [ ] The right edge of the comment block does not have a border. If you size the block bigger, the right border comes up
- [ ] Clicking on anything other than the comment block should close it. Currently, you can only close it by clicking on the "?".

![noborder](https://cloud.githubusercontent.com/assets/3943962/16100243/d2e53d88-3311-11e6-9738-99fbf6fedc5d.jpg)
Excel has a good example of comments and how expect interaction

Repro:
* Right click on a block
* Add comment

**Comment by pelikhan** [comment]
These are all blockly issues. The only viable fix is to remove comments all together.

**Comment by darrenge** [comment]
That's too bad as it is quite clunky. I guess it is better than nothing ...barely.

**Comment by darrenge** [comment]
Closing this out.
