### ISSUE TITLE
Microbit 2022 Release Blog Post

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#8921]
Hey Galen,
Can you get this blog post prepped and ready to post for our release tomorrow?
Files should all be here - https://1drv.ms/u/s!AvnYExTCocXPiiuRkVFkUiZkCPlk?e=ygeg5c

One note - I'm pointing to the Data Logger reference documentation in the blog post, but it's a bit slim...  could you also take a look?  https://github.com/microsoft/pxt-microbit/issues/4752 

Thanks!

**Comment by ganicke** [comment]
I'll have the blog and the datalogger page up tonight. The individual API ref pages have been there for some time already.
