### ISSUE TITLE
Y acceleration is wrong way round in simulator

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#893]
from twitter: https://twitter.com/EdNutting/status/806896359588634624
pxt-ver: pxt.microbit.org version: 0.6.13

The Y acceleration moves in the opposite direction on the simulator, compared to the real micro:bit.

Reproduced in attached .hex file

[microbit-pxt_tilt_bug.hex.zip](https://github.com/Microsoft/pxt/files/640370/microbit-pxt_tilt_bug.hex.zip)

**Comment by EdNutting** [comment]
Also, (let me know if you'd like this as a separate bug report) but it appears that in the currently online BETA Micro:bit PXT editor, Input->Rotation blocks treat both Pitch and Roll options always as Pitch. So Roll (i.e. left/right rotation) does not work.

**Comment by pelikhan** [comment]
@EdNutting, separate bugs are best.

**Comment by pelikhan** [comment]
Thanks for pointing out those issues. Fix coming up in https://pxt.microbir.org/beta in a few minutes.
