### ISSUE TITLE
Micro:bit PXT - Rotation block Roll treated as Pitch

### ISSUE THREAD

**Issue by EdNutting** [Microsoft/pxt#897]
Hi,

The Roll option of Rotation blocks is ignored/treated as the Pitch option. Roll also returns different magnitude of values to Pitch. This appears to be a simulator issue not a compiler issue.

The attached code executes correclty on the Microbit, moving the code from 1,1 to 1,2, 2,1 and 2,2 according to the angle of the physical board. The simulator incorreclty displays only at 0,2 and 2,1.

Cheers,
Ed

[microbit-pxt_rotation_bug.zip](https://github.com/Microsoft/pxt/files/640486/microbit-pxt_rotation_bug.zip)

**Comment by pelikhan** [comment]
Copy paste issue. See https://github.com/Microsoft/pxt-microbit/commit/3d0523a29869b484643432d160b7c5fed895352a

**Comment by EdNutting** [comment]
Yep, that also explains the magnitude difference.

**Comment by pelikhan** [comment]
In this build: https://travis-ci.org/Microsoft/pxt-microbit/builds/182392477
