### ISSUE TITLE
PXT Microbit: Roll magnitude is wrong compared to physical microbit

### ISSUE THREAD

**Issue by EdNutting** [Microsoft/pxt#898]
v0.6.33

Input->Rotation Roll is producing values in the range -180 to +180 degrees, where as the physical Micro:bit produces values in the range -90 to +90 (Pitch correctly produces values in the range -90 to +90, as per the physical device).

Attached file demonstrates the issue. Only LEDs 1,1, 1,2, 2,1 and 2,2 should light up. The simulator also allows LEDs in column 0 and 3 to light up.

[microbit-pxt_rotation_bug.zip](https://github.com/Microsoft/pxt/files/640521/microbit-pxt_rotation_bug.zip)

**Comment by pelikhan** [comment]
The simulator code maps the DAL runtime code. If you bring Z to zero, eg microbit standing vertically, you should see value ranging in the 180 for roll.

**Comment by EdNutting** [comment]
Okay, just about. The simulator makes it look like the board has only rotated by about 45 degrees though, which is confusing. The simulator board ought to rotate more to show this? And why is it not possible for pitch to rotate through the same distance? Hardware sensitivity issue?

The documentation says the value returned is from 0 to 360 degrees. But it's actually from -180 to 180 degrees. I guess that'll be another issue to submit haha.

**Comment by pelikhan** [comment]
It gets really hard to use the simulator when it tilts the full 90%, you can't see anything on it. Maybe we should be displaying x,y,z somewhere to make it obvious about the values. We do that in the microbit.co.uk simulator.

**Comment by EdNutting** [comment]
Agreed, 90 degrees would be impossible. But surely 60 or 70 would still be visible and make it obviously different from pitch? Or are they supposed to be in a similar range? I can't tell.

Displaying the values would be good too. The microbit.co.uk editor actually displays some very odd values that are not clamped to -180 to +180 : appears to be directly related to cursor x/y coordinates producing values in the range -1000 to +1000 (possibly larger if I had a bigger screen).

**Comment by jaustin** [comment]
@pelikhan showing the values is also good for an informal "what's the range I'm interested in" and helping people understand that more intuitively which axis is which when testing.

**Comment by abchatra** [comment]
Closing old issues. If this is still an issue please reopen.
