### ISSUE TITLE
PXT Micro:bit Way to switch off the documentation 'card'?

### ISSUE THREAD

**Issue by EdNutting** [Microsoft/pxt#899]
Hi,

It'd be nice to have a button on the UI to disable the Documentation Card when selecting blocks. It's distracting for children trying to do a worksheet, loads slowly on slow laptops (i.e. every laptop in use in schools I've ever worked in - about 8 around Bristol in the last 2 months) and lastly, it get's in the way - it takes up a lot of space and covers up code which confuses children. 

Attached screenshot shows that it hasn't sized-down to the smaller view on my laptop but does take up ~1/6 of the editing area.

Cheers,
Ed
![doc-card-size](https://cloud.githubusercontent.com/assets/1746336/21026825/4232df3e-bd86-11e6-9e62-b87f4881ef26.png)

**Comment by pelikhan** [comment]
For now, add ``?light=1`` to enable a lightweight mode for slower machines.

**Comment by pelikhan** [comment]
PR: https://github.com/Microsoft/pxt/pull/987

**Comment by microsoftsam** [comment]
Code card removed. Closing the issue.
