### ISSUE TITLE
Update web site to remove any references to PXT URL

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt#90]
Will add more if I find more, but this is a good place holder if need it. Also, a reminder just to scan the code for PXT.io and replace.

- [ ] "Houston we have a problem" page has "You can go back to pxt.io or contact us." -- repro: https://codethemicrobit.com/Darren

**Comment by thomasdenney** [comment]
I've searched the source code and there are still about a dozen references to pxt.io (excluding the numerous copies in the localisation directory). I can't find where the 404 page is generated in the code base; when you run in `localhost` it sends back a text/plain 404 document:

![404](https://cloud.githubusercontent.com/assets/20356546/16834150/7a395bd8-49aa-11e6-9a89-a616a27706db.PNG)
