### ISSUE TITLE
string compare works differently in simulator/on target

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#901]
microbit.org-ticket: 459
pxt.microbit.org version: 0.6.13

See attached script.

In the simulator it shows -1,   0   1
On the micro:bit it shows -20   0   5

[microbit-pxt-string-compare.hex.zip](https://github.com/Microsoft/pxt/files/641885/microbit-pxt-string-compare.hex.zip)

**Comment by abchatra** [comment]
Script in question. 

```js
let item = "fred"
basic.showLeds(`
    . . . . .
    . # # # .
    . # . # .
    . # # # .
    . . . . .
    `)
basic.pause(100)
basic.showNumber(item.compare("z"))
basic.pause(500)
basic.showNumber(item.compare("fred"))
basic.pause(500)
basic.showNumber(item.compare("a"))
```

**Comment by abchatra** [comment]
DAL uses C++ strcmp and its return value is as stated below. Relying on the exact values is not a good idea. 

http://en.cppreference.com/w/c/string/byte/strcmp
```c++
int strcmp( const char *lhs, const char *rhs );

Return value

Negative value if lhs appears before rhs in lexicographical order.
Zero if lhs and rhs compare equal.
Positive value if lhs appears after rhs in lexicographical order.
```

**Comment by chmora** [comment]
We shall align with Typescript / Javascript and change what the cpp compare method returns.
