### ISSUE TITLE
reset does not seem to work as expected

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#902]
New project: smiley block
add "nose" led on
Hamburger menu: Reset
>You are about to clear all projects. Are you sure? This operation cannot be undone.

OK

The smiley appears, also with nose led on

Expected: clears all projects, also the one being worked on
Version: the latest from github "just now"

**Comment by pelikhan** [comment]
@abchatra your archnemesis resetor is back

**Comment by abchatra** [comment]
Does this repro in beta pxt.microbit.org/beta?

**Comment by OwenBrotherwood** [comment]
I tried @  pxt.microbit.org/beta "just now"
Reset gave expected behaviour: no nose after reset

**Comment by OwenBrotherwood** [comment]
Tested once again from github: 
Reset gave unexpected behaviour: nose after reset
Additional:
Reset performed with  Blocks showing
Reset gave unexpected behaviour: showed Javascript after reset

**Comment by abchatra** [comment]
We don't delete files on the localhost as this involves deleting the files on the disk. We could do it, but localhost is for testing for devs only. I don't see the need.

**Comment by OwenBrotherwood** [comment]
Of course: that is the answer.
My bad: behaviour noted

**Comment by OwenBrotherwood** [comment]
Oops: forgot 

> Additional:
> Reset performed with Blocks showing
> Reset gave unexpected behaviour: showed Javascript after reset
> 

pxt.microbit.org/beta: reset shows expected behaviour

**Comment by abchatra** [comment]
Localhost is not a priority. Feel free to give pull request.

**Comment by OwenBrotherwood** [comment]
No need for PR: you have given the reason for behaviour.
And the "Additional" unexpected behaviour is not present  at pxt.microbit.org/beta

Result of Issue:
- behaviour noted in localhost scenario: but is electron taken account of ? /cc @guillaumejenkins 
- I use more extensive use of pxt.microbit.org/beta to document found issues.

Issue closed from my side with possible reopen from Microsoft electron side.

**Comment by abchatra** [comment]
Thanks! Yes we will architect it right for electron app.
