### ISSUE TITLE
Project settings are not applied

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt#9028]
# Bug Template

**Describe the bug**
The Project settings seem not to update immediately. At https://makecode.calliope.cc/beta we have user settings which are resulting in different file sizes for the hex file. However, the file size does not change when the user changing the settings. 

**To Reproduce**

1. Open https://makecode.calliope.cc/beta#editor
2. Download file, notice, that the file size is ~643 KB
4. Open project settings and choose “32K RAM”
6. Download file, notice, that the file size is still ~643 KB
7. Reload Browser trough Browser UI
8. Download again, notice, that the file size is now ~651 KB

**Expected behavior**
The file size in step 2 is right for 16 KB setting.
In Step 6 the file should already be compiled with 32K settings and therefore have ~651kb. This is only possible by a user reload.

In the attached Video, you can see, that there is a message “compiling…”, which only appears after the browser was manually refreshed.

In my local build, I added a `location.reload();` into the `save()`-Function and that solves the issue (however, the user has to experience a reload). I'm not sure what would actually solve the issue in the correct way, but having this as a workaround would be better than the current state.
Since the save-function is not exported, I cannot hook it from within the calliope target.

**Screenshots**

https://user-images.githubusercontent.com/77313133/187469447-f1a6ebb6-1290-4676-bd42-8c858dbb8b92.mp4
- First download: Right size
- Second download: Too small
- Third download (after refreshing the browser): Right size, notice the message “compiling” before the download is served
- Fourth download: Too big
- Fifth download (after reloading again): right size.

**Additional context**
I think this is a long existing issue, since we experienced issues regarding the BLE settings long ago, but it is always hard to tell what settings are applied to the hex. So I guess this issue might also appear in other targets.

This bug is currently blocking us from releasing our new version, since the user have to be able to choose the right setting corresponding to their device. 

Since we are using v7.0 in our target, we would need a potential issue or workaround back ported.

The Issue at our target can be found here: https://github.com/microsoft/pxt-calliope/issues/161

**Comment by abchatra** [comment]
@riknoll can you take a look at this issue when you are back in office?

**Comment by riknoll** [comment]
looking at this now!
