### ISSUE TITLE
bluetooth advertise url show https://pxt.io micro:bit transmits ttps:\pxt.io

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#911]
The url written in the bluetooth advertise url block or javascript function is not transmitted correctly due to similiar bug as https://github.com/Microsoft/pxt/issues/846

Difference this.bug to 846.bug is that the leading character removed.

It should be noted, that the micro:bit DAL cpp is NOT at fault for this.bug as I have checked by:
- changing code pxt-microbit bluetooth.cpp: override the url presented to the advertis function
- compiled DAL cpp example code

---

Related bug

https://github.com/Microsoft/pxt/issues/846: show string with double slash // displays backslash \ on micro:bit

**Comment by microsoftsam** [comment]
microbit-DAL issue: lancaster-university/microbit-dal#258

**Comment by OwenBrotherwood** [comment]
Can be closed :)
![image](https://cloud.githubusercontent.com/assets/866122/21907537/3394feee-d910-11e6-9004-e62c99b92cbc.png)

**Comment by microsoftsam** [comment]
Awesome
