### ISSUE TITLE
Compilation slowing down

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#912]
It takes a few seconds to compile this sample.

https://gist.github.com/pelikhan/f08425a122914a3a66465aa11064db65

**Comment by abchatra** [comment]
How do I load this in pxt. https://pxt.microbit.org/#pub:gh/gists/f08425a122914a3a66465aa11064db65 didn't work for me

**Comment by pelikhan** [comment]
Just copy paste the TS Code for now. Our import feature does not handle well missing PXT.json right now.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abchatra** [comment]
I see lot of cpu cycles spent in simulator `NeoPixel.prototype.setRgb`. Likely culprit is DOm event setAttribute in there.

**Comment by abchatra** [comment]
won't fix
