### ISSUE TITLE
"Make a variable" item would be better as something other than a block

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#915]
The "Make a Variable" block is not really a block, in that you can'd drag it into your program

So instead, it would make more sense as a button

![image](https://cloud.githubusercontent.com/assets/147113/21076292/8f197ba6-bf1f-11e6-9d4d-571265b6af71.png)

Or at least, something else different from the blocks.
![image](https://cloud.githubusercontent.com/assets/147113/21076316/1e2d46d8-bf20-11e6-98dc-cff1e136521f.png)

**Comment by pelikhan** [comment]
Agreed. This is a new blockly feature. We will see about skinning it.

**Comment by OwenBrotherwood** [comment]
I do not understand the issue.
On a practical point, the two pictures: the one above is the present one @ https://pxt.microbit.org/beta and shows what I believe is a button ie probably not a block so the Make a variable _is_ somthing other than a block now?

The next point, is not a practical point: 
When do I need a button or block or anything that comes out of the Variables side bar menu?
I pull out an object, perhaps throw a variable at it and then maybe change it's name _when_ it is on the canvas.

I have never seen children preparing a variable as we would do when writing javascript ....

**Comment by OwenBrotherwood** [comment]
"Make a new variable" is not doing what is expected:
let me = "owen" makes a new string variable
Make a new variable is doing
let me

**Comment by abchatra** [comment]
+1 for @jaustin request.

**Comment by jaustin** [comment]
Here's a picture of how Python did it
<img width="245" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21774660/114b02d4-d68b-11e6-9967-bccd174855d2.png">

**Comment by microsoftsam** [comment]
The python screenshot is default blockly, we've already skinned it to have the same color as the other blocks in the Variables category. If we'd like we can change it back to the default color.
As for making it take up the whole space (@jaustin's initial suggestion), that'd going to be difficult as Blockly is in control of the specific coordinates and dimensions of that button.

@jaustin @pelikhan what color do you think that button should be? The default blockly grey?

**Comment by pelikhan** [comment]
The button should look like a button - same color as the current theme, same corners, etc...

**Comment by jaustin** [comment]
Agree with Peli, looking like a button and not like the other blocks is key.
