### ISSUE TITLE
MakeCode/Code Connection not supported anymore on non-Education Minecraft versions

### ISSUE THREAD

**Issue by AndreiCsibi-msft** [microsoft/pxt#9226]
**Describe the bug**
The ```Code Connection``` to Minecraft seems not to be supported anymore on versions that are not Education, even if the documentation [Minecraft Minecode Setup](https://minecraft.makecode.com/setup) says that they should be.
<img width="887" alt="MakeCodeGetSetup" src="https://user-images.githubusercontent.com/48303052/201443662-b18f8118-676c-44ac-8658-d375efcba390.png">

**To Reproduce**
1. Install Code Connection from either the Microsoft Store or https://minecraft.makecode.com/setup/minecraft-windows10 
2. Install Minecraft regular edition from the Microsoft Store, but not the Education version.
3. Open Minecraft and create a regular world (not on realms).
4. Open Code Connection for Minecraft and copy the regular text from the popup that says "Please enter the following command in Minecraft: Education Edition". I assumed that this is incorrect because the documentation shows that the non-Education editions are supported (see bug title).
5. Paste the code in Minecraft and you'll get "Connection Established for server".
<img width="409" alt="MinecraftConnectionEstablished" src="https://user-images.githubusercontent.com/48303052/201443658-8c3c4524-a953-4680-aef9-689d30f8f190.png">
6. However you'll get an error in the "Code Connection for Minecraft" window saying "Please update this application to the latest version https://education.minecraft.net/get-started/download".
<img width="671" alt="CodeConnectionError" src="https://user-images.githubusercontent.com/48303052/201443660-2521a7fd-e1b2-4e65-9321-a45d5b4c4a49.png">

**Expected behavior**
This looks like a regression as until recently Minecraft could connect to MakeCode/Code Connection on a non-Education version.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2

**Additional context**
It would be unfortunate to drop support for regular versions of Minecraft.

**Comment by AndreiCsibi-msft** [comment]
Note that some of the links in the Bug template are incorrect, returning 404 not found:
- https://education.minecraft.net/en-us/download
- https://education.minecraft.net/en-us/technical-support

**Comment by abchatra** [comment]
@AndreiCsibi-msft can you also post an issue on the Minecraft here:
https://educommunity.minecraft.net/hc/en-us/community/topics/360001721951-I-have-a-technical-problem

@Jaqster - FYI

**Comment by AndreiCsibi-msft** [comment]
@abchatra : There's already a thread about this issue here: https://educommunity.minecraft.net/hc/en-us/community/posts/5757924107284-Code-connection-error, with over 50 replies. Can this feedback help prioritize this work?

Also, shouldn't the link that you mentioned be part of the bug template?

**Comment by abchatra** [comment]
>> _Can this feedback help prioritize this work

Unfortunately, this is not an issue on MakeCode code, it is on the Minecraft code.  We are in the same company; however 
 sometimes teams' priority differs.

**Comment by Jaqster** [comment]
The Minecraft Team is aware of the issue and have a fix pending release.  Should be out in the next couple weeks...  @MicahM-MSFT

**Comment by AndreiCsibi-msft** [comment]
Sounds good! Thank you all!

**Comment by Felina-Lain** [comment]
> The Minecraft Team is aware of the issue and have a fix pending release. Should be out in the next couple weeks... @MicahM-MSFT

I'm gonna guess this got pushed down on the priority list, because it's been a loooot more than "a couple weeks" and it's still not fixed

**Comment by Vegz78** [comment]
> The Minecraft Team is aware of the issue and have a fix pending release. Should be out in the next couple weeks... @MicahM-MSFT

Yes, a very long couple of weeks, @Jaqster... ;-)

-Exactly 17 months and 8 days today since this bug first appeared with the release of Berock v1.18.30.

**Comment by Vegz78** [comment]
Code connection officially discontinued:
https://forum.makecode.com/t/bedrock-edition-no-longer-working-with-makecode-super-disappointing/22597/20?u=vegz78

**Comment by Jrr-CODER-GUY** [comment]
It won’t let me download it on the Microsoft Store. Could someone create a download link to the 
.msi? I really love computers and coding and I would just be so disappointed if I can’t connect them. Thanks

**Comment by abchatra** [comment]
@Jrr-CODER-GUY Unfortunately Code Builder for Bedrock is discontinued. If you have Minecraft Education Edition, code builder is integrated.
