### ISSUE TITLE
Resolution requirements for screen resolution

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#928]
Is there a stated minimum screen resolution?
At 800x600, it is not possible to access + due to sim

![image](https://cloud.githubusercontent.com/assets/866122/21164278/52072724-c198-11e6-98de-ad95acfeb25e.png)

**Comment by abchatra** [comment]
@OwenBrotherwood what device is this? Also is it in full screen mode?\

**Comment by OwenBrotherwood** [comment]
A virtual machine set in 800x600 mode full screen
Other resolutions above 800x600 mode full screen do not have a problem ie 1024x768 and up.

**Comment by OwenBrotherwood** [comment]
full screen mode === max window in chrome, with waste space for chrome tabs and "go" url

**Comment by OwenBrotherwood** [comment]
As I wrote, should have taken a full screen shot: and also ensured the shot was of beta
Bows head in shame

![image](https://cloud.githubusercontent.com/assets/866122/21174722/1f34aeb0-c1df-11e6-9519-04fff1b618b2.png)

**Comment by abchatra** [comment]
Virtual machines are not the mainline case for us. But we will look into this in future.

**Comment by OwenBrotherwood** [comment]
@abchatra The same problem is on a virtual machine.
The term "virtual machine" is the usage of a host os to support another host os such that changes in the virtual machine in terms of development do not disrupt production usage of the host os.
Please do not degrade the level if the degrading is because the word "virtual machine" is unknown in Microsoft

**Comment by OwenBrotherwood** [comment]
Please find a screen dump from a machine showing the problem of inability of using the + and @ button.
What is the designed minimum requirement for screen resolution such that it possible to use pxt.
The screen dump is from beta as of "now"

![image](https://cloud.githubusercontent.com/assets/866122/21195925/2002f520-c236-11e6-8651-08f3dce5c542.png)

**Comment by OwenBrotherwood** [comment]
The full screen shot shown is from a Laptop at full resolution, it shows "typical usage": coding the micro:bit while reading getting started.
It is not possible to access the reload button in this use case

![image](https://cloud.githubusercontent.com/assets/866122/21197410/aa059444-c23b-11e6-9c6b-bf2c28f85a59.png)

**Comment by OwenBrotherwood** [comment]
![image](https://cloud.githubusercontent.com/assets/866122/21202131/e4110210-c24d-11e6-9aa9-bf0fd6a00468.png)

**Comment by pelikhan** [comment]
Removal of code card: https://github.com/Microsoft/pxt/pull/987

**Comment by microsoftsam** [comment]
Editor toolbox: #1052

**Comment by riknoll** [comment]
Fixed with new responsive design

**Comment by OwenBrotherwood** [comment]
I take another look at the issue 
Thanks for the work
