### ISSUE TITLE
dragging a 'js block' just highlights

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#929]
(using /beta on Chrome on macOS 10.12)
Given the way the block editor trains users to 'drag' blocks, I can imagine that many people will try to 'drag' the "JS blocks" (JS snippets in toolbelt) into their code somewhere.

I guess this has two parts
1) Should this work? (I think it probably should in the long run, maybe that's a separate issue/enhancement)
2) Even if it doesn't, let's do something better than highlighting text (highlighting isn't expected when there's a finger icon anyway)

Just an example of what I mean by highlighting:
![image](https://cloud.githubusercontent.com/assets/147113/21164645/5fbde5c0-c192-11e6-875c-693881da01bb.png)
To reproduce
* click on an item in the toolbar to reveal the 'JS blocks'
* click and drag on a block, dragging down (as if towards middle of code)
...notice that the other blocks get highlighted

**Comment by pelikhan** [comment]
Yes, long term is to support drag and drop of those blocks in the javascript editor. Still working out the details with the monaco editor.

**Comment by pelikhan** [comment]
@sam, need to update CSS of toolbox items to prevent text selection.

**Comment by pelikhan** [comment]
Fix for text selection https://github.com/Microsoft/pxt/commit/c459172bd7a2e31e6877012756dfa59809ede59a

**Comment by microsoftsam** [comment]
Fixed with the latest version of the monaco editor. Drag and drop support.
