### ISSUE TITLE
String variables in .PXT

### ISSUE THREAD

**Issue by kenyoncoder** [Microsoft/pxt#938]
https://pxt.microbit.org/reference/types/string(url)

describes how to create and asign a value to a string variable.

Specifically it says:

_Click Variables (in the Block drawer).
Type a name for your new string variable by clicking the down arrow, then click New Variable. Then type the variable name “salutation”
**Drag a string block** on the right side of the operator.
Click "Hello" and then type a string like hello._

I can't see a string block to drag.

Where am I going wrong?

**Comment by abchatra** [comment]
Documentation is incorrect. We don't have string block. You can type a new string in-place without dragging a new block.

**Comment by kenyoncoder** [comment]
Thanks @abchatra 

Please forgive me if I'm a little slow, but the only opportunities I can see for typing a new string in-place are string literals.

I cannot see any way to **_programmatically_** assign a value to a string variable, unless I use JavaScript, as indicated in issue #531 - thanks @OwenBrotherwood - to fudge the creation of a true string variable.

I appreciate the concerns about string variables, as expressed in issue #531 and am personally happy to use the JavaScript method as a workaround.

A further point is that the documentation at : https://pxt.microbit.org/blocks/variables/assign
is potentially misleading.

**Comment by pelikhan** [comment]
We are planning to expose string functions as a separate package that you would be importing through the (+) package button (also for arrays and so forth)

**Comment by kenyoncoder** [comment]
thanks @pelikhan 

Any idea of timescale?

**Comment by nielsswinkels** [comment]
This can be closed now that string blocks have come to pxt?

**Comment by abchatra** [comment]
Thanks for pointing. Closing.
