### ISSUE TITLE
Input Method does not work properly on "Rename..."

### ISSUE THREAD

**Issue by sgk** [Microsoft/pxt#946]
Every key strokes will be input into the Name field before the input method works properly. In Japanese, "ka ki ku ke ko" should be transformed to "かきくけこ", but the Name field looks like "ｋあｋいｋうｋえｋお". This issue is confirmed on Chrome and Edge.

![image](https://cloud.githubusercontent.com/assets/485416/21285551/f0cccb14-c47e-11e6-8f8d-992180b90d2f.png)

**Comment by pelikhan** [comment]
This seems to be a bug in semantic - https://github.com/facebook/react/issues/3926
