### ISSUE TITLE
ts.pxt.... clashes with pxt....

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#95]
In general, we should avoid using "pxt" as a subnamespace, it creates naming clashes that cannot be resolved in TypeScript.

**Comment by mmoskal** [comment]
I have now renamed `ts.pxt` to `ts.pxtc`; there is also a top-level `pxtc` alias. ('c' is for compiler)

@tballmsft - I have merged master into your avr branch, make sure to git pull

**Comment by tballmsft** [comment]
thanks
