### ISSUE TITLE
Array read in double loop causes "Program Error: sim: check failed"

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt#953]
The following program consistently causes the editor to produce a "Program Error: sim: check failed" error.

```
let a: number[] =[]
a[0] = 1;
while (true) {
    while (true) {
        let foo = a[0];
    }
}
```

From my experience at making this minimum test case, it only seems to happen when it's a double loop and array read from an array that is populated after declaration.

**Comment by abchatra** [comment]
This is really a bad bug. SetAt array fails as it can set only if there are already elements in place. I plan to revisit the entire array implementation soon.

**Comment by darzu** [comment]
Thanks for looking into this! So would a suitable work around be to always initialize an array with at least one element?

**Comment by abchatra** [comment]
As of today set works only if there is an existing item in there. So you will need to initialize all the elements before you can set on them.  We are going to fix it soon.

**Comment by abchatra** [comment]
This is fixed now by https://github.com/Microsoft/pxt-microbit/issues/326
