### ISSUE TITLE
event handlers with options should be error-free (as possible)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#955]
With the new semantics of event-handlers as top-level only, we have the problem that if I drag "on-button-pressed" twice to the canvas, I get an error on the second handler, because the default value (button A) is the same as the first handler.

We should be smarter and recognize this situation, changing the option value of the newly added block (if possible) to a value not already present in the program.

**Comment by pelikhan** [comment]
This won't work for some events that do not have parameters. We could highlight the "other block" when showing the warning.

**Comment by pelikhan** [comment]
Note that this is not an error, it is just a warning. The program still compiles but the handler is ignored.

**Comment by OwenBrotherwood** [comment]
In general, and specific, these warnings cause "concern" for the kids and stop the flow of creation and cause a hand up to ask the teacher.
This happened for me this evening with a kid becoming unsure, and raising his hand: quickly fixed but ...

**Comment by OwenBrotherwood** [comment]
The warning text "This event is already used" does not relate for the kids: the button is already used is something they can relate to

**Comment by pelikhan** [comment]
We could simply not show any kind of warning in that case.

**Comment by OwenBrotherwood** [comment]
Simply not showing "This event is already used" is one solution that would remove a warning that the kids do not relate to.

**Comment by pelikhan** [comment]
Remove warning https://github.com/Microsoft/pxt/pull/986

**Comment by pelikhan** [comment]
Similarly to dangling statement, duplicate events are simply disabled. Please reopen if this is not satisfactory.
