### ISSUE TITLE
Ability to create images with more than two frames

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#956]
Feedback from community users: We have a lot of scripts that have a significant number of multi-frame images, mostly written by children. What we see is that they zoom out to such a level that it is impossible to see the program any more. For example, one script has about 50 images in it.

It is only possible to create a 2-frame image maximum.

Touch develop, for example, has a nice feature where you can edit a framed image with any number of frames, and then it collapses that down into a sequence with ... at the end in the real editor. This is a great feature, because of the limited size of the micro:bit display, the best apps use animations rather than scrolling text.

Related to this *might* be other tickets that refer to adding a feature for decomposing into functions - so it might be possible to alternatively offer a facility to build functions with large images/animations in them, and then just call those functions, as an alternative way of solving this issue with one fix.

We have a collection of touch develop scripts in a PR that demonstrate typical multi-frame animations that make great use of the limited size of the micro:bit display:

https://github.com/Microsoft/pxt-microbit/pull/283

**Comment by abchatra** [comment]
Closing this in the pxt repo. This is part of backlog.
