### ISSUE TITLE
Howto add custom code snippets from my packages?

### ISSUE THREAD

**Issue by nevergone** [microsoft/pxt#9592]
I would like some custom snippets in my micro:bit code packages. Please document, how can I do this.

Please see attached screenshot.
![23cf2f2f88b52e815e9b5ec33dc8809e9805ac3f](https://github.com/microsoft/pxt/assets/240642/a0aedd43-3aee-4fd3-8489-f18ed75ae5c3)

**Comment by abchatra** [comment]
@nevergone are you planning to write an extension? 
Here are the details: https://makecode.com/extensions/getting-started
