### ISSUE TITLE
Serial Redirect

### ISSUE THREAD

**Issue by jez-chaplin** [Microsoft/pxt#961]
Hi, I'm trying to write out from the microbit to the sparkfun serial logger (openlog) - I can do this fine in micropython but via PXT it seems the 'serial redirect to' block is not altering the pinouts as specified, or of course I'm not doing it right....

Has anyone else observed this behaviour?

Thanks.

**Comment by pelikhan** [comment]
The ``serial.redirect`` function maps directly to this DAL calls (https://github.com/Microsoft/pxt-microbit/blob/395f482f11d007961036ae550b74fcddb054c2f7/libs/core/serial.cpp#L94)

```
    void redirect(SerialPin tx, SerialPin rx, BaudRate rate) {
      uBit.serial.redirect((PinName)tx, (PinName)rx);
      uBit.serial.baud((int)rate);
    }
```

**Comment by jez-chaplin** [comment]
Just confirmed that this works as expected also:

    uBit.init();
    uBit.serial.baud(9600);
    uBit.serial.redirect(MICROBIT_PIN_P0, MICROBIT_PIN_P1);
    uBit.serial.send("A\r\n");

Just see your reply pelikhan, thanks, but not sure that that helps given my attempt above?

**Comment by pelikhan** [comment]
And the DAL reference: https://lancaster-university.github.io/microbit-docs/ubit/serial/#redirect

**Comment by jez-chaplin** [comment]
Are the pin mappings correct then?  Or should this be passed the actual pin references instead?

**Comment by pelikhan** [comment]
```
enum SerialPin {
    P0 = MICROBIT_ID_IO_P0,
    P1 = MICROBIT_ID_IO_P1,
    P2 = MICROBIT_ID_IO_P2,
    P8 = MICROBIT_ID_IO_P8,
    P12 = MICROBIT_ID_IO_P12,
    P13 = MICROBIT_ID_IO_P13,
    P14 = MICROBIT_ID_IO_P14,
    P15 = MICROBIT_ID_IO_P15,
    P16 = MICROBIT_ID_IO_P16
};
```

**Comment by jez-chaplin** [comment]
I see you've labelled it as a bug... is there an issue here then?

**Comment by pelikhan** [comment]
don't know yet, maybe.

**Comment by jez-chaplin** [comment]
ok, thanks, will leave it with you & appreciate the help.

**Comment by pelikhan** [comment]
Try again in https://pxt.microbit.org/beta . Watch out, there is a breaking change (on start) in the beta, so I would recommend using an anonymous window.

**Comment by jez-chaplin** [comment]
Thanks pelikhan, that now works as I would expect.  Appreciate the quick response!

**Comment by jez-chaplin** [comment]
Somewhat unrelated, but I raised this issue here re the pxt-filesystem implementation - https://github.com/Microsoft/pxt-filesystem/issues/3 - that problem presents itself still, and in the beta site you just provided.  Did I log this in the wrong place?

**Comment by pelikhan** [comment]
File it in the microsoft/pxt repo.

**Comment by jez-chaplin** [comment]
Thanks, pls ignore, went to reproduce so that I could provide more logging info and it's started working again.

**Comment by pelikhan** [comment]
I just bump the file system to slurp a fix :)
