### ISSUE TITLE
Type Mismatch Errors with @types/react and TypeScript in PXT-Microbit Project

### ISSUE THREAD

**Issue by emoltz** [microsoft/pxt#9619]
**Describe the bug**
When trying to build the PXT-Microbit project, a series of TypeScript errors occur related to the @types/react package. The errors indicate that subsequent property declarations must have the same type, which seems to be a mismatch between the types defined in the @types/react package.

**To Reproduce**

Clone the pxt repo
run `npm i`
run `npm run build`
Here you should get the type mismatch errors. I went around this by adding a `@ts-ignore` but the problem persisted when I did the following:

Clone the PXT-Microbit repository (https://github.com/microsoft/pxt-microbit).
Run npm install to install the necessary packages.
Run pxt serve to build and serve the project.
See the TypeScript errors related to @types/react.
Expected behavior
The project should build without any TypeScript errors and serve locally for development.

**Desktop (please complete the following information):**

OS: MacOS
Node.js Version: LTS
TypeScript Version: 4.4.3
@types/react Version: 17.0.5

**Additional context**
I've tried several solutions to resolve these errors, including updating the @types/react package to the latest version, deleting the node_modules directory and reinstalling the packages, and adding "skipLibCheck": true to the tsconfig.json file. Unfortunately, none of these solutions have resolved the issue

**Comment by jwunderl** [comment]
@emoltz could you run `node -v` and get the version of node.js you are running?

**Comment by emoltz** [comment]
18.17.0, but I tried it with 20.5.0 and v14 via nvm

**Comment by emoltz** [comment]
This is also affecting the build of the pxt repo, i.e. when I run `npm run build` I get an error related to a type mismatch with the `Provider` component. This issue seems to extend to all pxt-related repos.
