### ISSUE TITLE
Unable to convert with side problem of warning triangle

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#963]
Attached a gif of my screen showing using beta from today.
- unable to convert shown blocks (to javascript ..?)
- warning triangle does not remain visible after unable to convert message

![wormy](https://cloud.githubusercontent.com/assets/866122/21366593/b2c17936-c6fa-11e6-88d0-858bf76a4aac.gif)

**Comment by OwenBrotherwood** [comment]
Follow up:
This code runs in sim, but cannot be shown in blocks
```
let dead = 0
let alive = 1
let worm = alive
input.onButtonPressed(Button.A, () => {
    worm = alive
})
basic.forever(() => {
    if (worm === alive) {
        basic.showLeds(`
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            # # # # #
            `)
    } else {
        basic.showLeds(`
            # # . . .
            . . # . .
            . # . . .
            . . # # .
            . . . . #
            `)
    }
})
input.onButtonPressed(Button.B, () => {
    worm = dead
})
```

**Comment by OwenBrotherwood** [comment]
Note the trailing worm = true in this version
```
let worm = false
input.onButtonPressed(Button.A, () => {
    worm = true
})
basic.forever(() => {
    if (worm) {
        basic.showLeds(`
            . . . . .
            . . . . .
            . . . . .
            . . . . .
            # # # # #
            `)
    } else {
        basic.showLeds(`
            # # . . .
            . . # . .
            . # . . .
            . . # # .
            . . . . #
            `)
    }
})
input.onButtonPressed(Button.B, () => {
    worm = false
})
worm = true
```

![image](https://cloud.githubusercontent.com/assets/866122/21367071/f0f215a6-c6fc-11e6-9e7d-be2d656411a4.png)

**Comment by pelikhan** [comment]
The first issue is that `===` and `!==` are not supported. Fixed in https://github.com/Microsoft/pxt/commit/fed308d8fccf7a7bd565d68ff134bb1f2818c64c.

**Comment by OwenBrotherwood** [comment]
"Error: I can only compare strings, booleans and numbers"

![image](https://cloud.githubusercontent.com/assets/866122/21397956/f798a894-c7a5-11e6-8302-031d086f1187.png)

**Comment by pelikhan** [comment]
Could you post the javascript source of this sample?
