### ISSUE TITLE
help text inhibits access to block

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#965]
Unable to access block due to help text.
The child has to start moving blocks around or use +/-
![image](https://cloud.githubusercontent.com/assets/866122/21367440/77361e22-c6fe-11e6-9e27-9d1a9bec216e.png)

**Comment by pelikhan** [comment]
What is the resolution on this screen?

**Comment by OwenBrotherwood** [comment]
Same type of issue with "Getting Started" both with full screen 1920x1080
![image](https://cloud.githubusercontent.com/assets/866122/21368580/7139c7d0-c703-11e6-9556-36a3f9d46d4f.png)

**Comment by pelikhan** [comment]
PR https://github.com/Microsoft/pxt/issues/965

**Comment by microsoftsam** [comment]
PR #1033
