### ISSUE TITLE
MICROBIT_ACCELEROMETER_EVT_8G is not implemented in accelerometer on dropdown

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#966]
MICROBIT_ACCELEROMETER_EVT_8G is not implemented in accelerometer on dropdown.
ie no choice for 8g

**Comment by pelikhan** [comment]
Fixed in https://github.com/Microsoft/pxt-microbit/commit/3141e12f4cf42824fac9eba1e649b16e28543e78
