### ISSUE TITLE
Add documentation page for Home Page content requests

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt#9666]
I feel like it would be good for us to add some documentation on how and what we need to add new cards and banners to the Home Page.  I keep getting this question...

Maybe put it under "Miscellaneous" under a "Home Page Content" page?
![image](https://github.com/microsoft/pxt/assets/22108954/19146005-6d05-4fb1-afe9-5ff1c69170b7)

Here's a start - 

If you have a tutorial, project, lesson or full course that you would like to share with others, we're happy to list it as a resource on the Home Page.  Please read the information below to learn more about the request process.

**Criteria**
- Your content should be open source and free to use
- The instructions should be well written and easy to follow
- It should not include any personally identifiable information
- Content will be reviewed and approved by the MakeCode Team

**What you need to submit**
- For a tutorial, a link to a complete tutorial (see https://makecode.com/writing-docs/tutorials for more details)
- For a lesson or course, a link to a public website with the materials
- An image of <insert dimensions and/or resolution here>
- A name and short description - see below as an example
![image](https://github.com/microsoft/pxt/assets/22108954/fb6bb65c-d12e-4b8a-97e6-3a7208aca3dc)

**Process**
- File a GitHub issue requesting your content to be listed
- Include all the relevant information listed above
- For micro:bit, please follow the instructions for submitting a tutorial to the Micro:bit Foundation for approval [here](https://support.microbit.org/support/solutions/articles/19000054952-makecode-extension-and-tutorial-approval)

For requesting a featured space in the Home Page banner carousel, we require a link, a short description and an image of <insert dimensions and/or resolution here>.  Please note that banner space is very limited, and therefore highly selective.

**Comment by Jaqster** [comment]
@abchatra to review too, and I'm not actually sure what image format/dimensions we need

**Comment by abchatra** [comment]
@ganicke would know more on image format/dimensions. I will review the content.
