### ISSUE TITLE
Implementation of a switch block

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#968]
Implementation of a switch block to allow for state.

https://github.com/Microsoft/pxt/issues/849#issuecomment-265831839

**Comment by pelikhan** [comment]
Please provide more details.

**Comment by OwenBrotherwood** [comment]
The current implementation for if then else does not cater for a large if then else if then else stack.
It would be appropriate to examine the implementation of the switch statement in terms of understandability/readability

The use of if then else chains or switch aid in ensuring a state machine for to support the https://github.com/Microsoft/pxt/issues/849#issuecomment-265831839

/cc @EdNutting

https://en.wikipedia.org/wiki/Switch_statement

**Comment by OwenBrotherwood** [comment]
>The current implementation for if then else does not cater for a large if then else if then else stack.
Incorrect: using the cog wheel on the if, a vertical if then else if that is acceptable for screen use.
Just not very readable/convenient compared to switch

**Comment by abchatra** [comment]
We use blockly and current if\else experience is based on that. Won't fix for now.
