### ISSUE TITLE
Remove scaling when hovering over the button to exit debug mode

### ISSUE THREAD

**Issue by THEb0nny** [microsoft/pxt#9684]
I suggest removing the scaling when hovering over the button to exit debug mode, because... this is not visually beautiful... the size of the button increases so much that it extends beyond the right side of the screen, and visual bugs also appear in the editor. It seems to me that changing the color of the button will be sufficient.

@kimprice what do you think of this proposal?

![2023-09-17_21-05-29](https://github.com/microsoft/pxt/assets/13646226/da0ab726-20f4-4aeb-9ef7-4cd39be59c17)

**Comment by kimprice** [comment]
yes, I agree.

**Comment by THEb0nny** [comment]
> yes, I agree.
All other buttons do not have such a scaling animation, only a color change.

**Comment by THEb0nny** [comment]
> > yes, I agree.
> > All other buttons (similar) do not have such a scaling animation, only a color change.
