### ISSUE TITLE
true / false hard to find 

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#969]
true / false hard to find 
As with string, true and false are not easy as Variables seems to have focus on integer
true and false are under logic, at the bottom and can be at time hard to remember where they are and also one needs to scroll on lower resolution screens

**Comment by pelikhan** [comment]
Removed the 3 if statement, should be better now.

**Comment by OwenBrotherwood** [comment]
The true/false is still a scroll to object
full screen 1920x1080
![image](https://cloud.githubusercontent.com/assets/866122/21397242/50f61474-c7a3-11e6-847a-1abdc584152b.png)

**Comment by OwenBrotherwood** [comment]
Could also be a case for true false being available in Variables

(The whole Variables, visualization usage strings etc is quite an issue)

**Comment by OwenBrotherwood** [comment]
Not sure if MS wants to close this or keep open
