### ISSUE TITLE
pxt cli: `uploadtrg` does not work with webapps

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt#9699]
For instance: running `pxt uploadtrg --rebundle` in the pxt-arcade folder will publish the main editor to a test target, but not kiosk, multiplayer, etc.

**Comment by jwunderl** [comment]
I did an uploadtrg earlier to double check multiplayer loc change and it seemed to work fine, never tried --rebundle on an uploadtrg though / didn't realize it was an option. (Or, possibly an issue with only running gulp --no-webapps or something similar? I had run a full gulp just before uploadtrg ing as well)

**Comment by eanders-ms** [comment]
Oh it was user error. I needed to rerun gulp :/. Thanks.
