### ISSUE TITLE
How to unpublish a project

### ISSUE THREAD

**Issue by calebfoss** [microsoft/pxt#9705]
I'm an instructor using MakeCode for Adafruit Playground Express in class.

After publishing a project, how can a user remove it from the cloud? Surely publishing isn't a permanent irrevocable decision, and the UI/documentation does not say that it is. But I'm not seeing a way to remove or change published projects. Thanks!

**Comment by Jaqster** [comment]
Hi @calebfoss!  Thanks for your question.  There isn't a way to remove or change published projects.  In MakeCode for Adafruit we have no log-in support, so all those project Share links are anonymous and encrypted (we do this for security/privacy reasons).  If you lose a share link, there's no way to get it back - you just have to share your project again.  And we do not maintain state - the Share link is just a snapshot of your project at that time.  If you make changes to your project, you'll have to create a new Share link.  Also, this Share link is not published anywhere except to you, so if you don't actually post it anywhere or send it to anyone, then it's not public.  Hope this helps.  In the future, any questions like this, feel free to post to the Forum - https://forum.makecode.com.
