### ISSUE TITLE
sim disappears when accessing block menu choice

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#971]
When selecting a block menu, the sim disappears.
Two things happening, where one is related to the action, the appearance of blocks whilst the other is a screen change that has no relation to the action but is a distraction

![image](https://cloud.githubusercontent.com/assets/866122/21369504/91cd8b2c-c707-11e6-97b3-a4708f3eeca0.png)

**Comment by pelikhan** [comment]
Please post a gif video of the issue. I do not understand.

**Comment by OwenBrotherwood** [comment]
![simmenu](https://cloud.githubusercontent.com/assets/866122/21369929/a72590f8-c709-11e6-9276-1f5f4cb8c553.gif)

**Comment by pelikhan** [comment]
What is the screen resolution?

**Comment by OwenBrotherwood** [comment]
full screen 1920x1080

**Comment by OwenBrotherwood** [comment]
The disappearing behaviour of the screen is probably due to supporting sim in a window (smaller screen?) scenario
LHS/MID/RHS related where the sim is being kept LHS but where there is good reasons to keep RHS with a possibility of auto-hide

![simmenu-windowed](https://cloud.githubusercontent.com/assets/866122/21370643/fb96ea9e-c70c-11e6-94a5-a782196aa043.gif)
windowed 1920x1080

**Comment by OwenBrotherwood** [comment]
Issue has Needs Additional Information.
I think it was only screen res, answered @ https://github.com/Microsoft/pxt/issues/971#issuecomment-268378646

**Comment by OwenBrotherwood** [comment]
Seems ok with tests of current beta
