### ISSUE TITLE
undo do not undo shuffle blocks

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#976]
undo do not undo shuffle blocks

![shuffle-undue gif](https://cloud.githubusercontent.com/assets/866122/21399859/babd6b00-c7ad-11e6-8c30-ee3dbb0235ee.gif)

**Comment by OwenBrotherwood** [comment]
https://github.com/Microsoft/pxt/pull/1168#issuecomment-273987024

**Comment by OwenBrotherwood** [comment]
The solution seems to be a warning for cannot undo which is ok for me

**Comment by microsoftsam** [comment]
Cutting the feature altogether

**Comment by OwenBrotherwood** [comment]
Yep: let's get RC done
You are up early :) or late dependent on time zone
