### ISSUE TITLE
Chrome extension doesn't see serial data on Mac

### ISSUE THREAD

**Issue by bennytheshap** [Microsoft/pxt#977]
LED graph plotting of data from a micro:bit over USB doesn't work when using Chrome on the Mac with the micro:bit extension. 
When I connect a micro:bit, it does show up as /dev/cu.usbmodem1422, but streamed data does not make it into the browser (testing with screen on the command line is fine). 

Here's a screenshot of a program that will demonstrate the problem:
![screen shot 2016-12-21 at 11 12 48 am](https://cloud.githubusercontent.com/assets/122056/21400667/7d3c8d36-c76e-11e6-9334-b66404d89200.png)

**Comment by samelhusseini** [comment]
The Chrome extension has been deprecated. Closing bug.
