### ISSUE TITLE
initialisation of variable to integer consideration

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#978]
One form for pupil task could be arrange a program that had previously been created and then had a "shuffle blocks".
In the following, the worm has been shuffled but note the behaviour.
worm-is-alive starts as an integer due to pre-defined initialisation.
however, worm-is-alive is desired to be boolean (could be string as another type example)
If a pupil starts the puzzle with an immediate consideration of the worm being dropped, worm-is-alive=false, warnings occur.
The warnings repeat until the initialization of variable worm-is-alive is changed from integer to boolean.

It is left up to the reader to decide if this is ok

![shuffle-puzzle](https://cloud.githubusercontent.com/assets/866122/21400647/77c0ca0a-c7b1-11e6-96b2-60187810e26c.gif)

**Comment by OwenBrotherwood** [comment]
The Life of worm: full version solution

![wormgame](https://cloud.githubusercontent.com/assets/866122/21408455/7af06d7e-c7d5-11e6-92da-e6f3b2789760.gif)

**Comment by abchatra** [comment]
Share the javascript code if possible please.

**Comment by pelikhan** [comment]
This issue seems to have been resolved by https://github.com/Microsoft/pxt/pull/1046. Please share JS to repro.

**Comment by OwenBrotherwood** [comment]
I lost the code and missed the comments: I will build the code up again
