### ISSUE TITLE
add forever on new project

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#981]
Having discovered that "on start" is a new project object, I began thinking what else caught the eye.
I did a new project ("on start" block was there and "it was good") and then it occurred to me that it would be "nice" if the "forever" block was also present, a natural start and gives structure to a new project (or at least as much as "on start" does)

For consideration.

---

Edit:  I failed in finding out the necessary in order to makea PR with "forever" block :(

https://github.com/Microsoft/pxt/pull/945/commits/efd25c65d9d12b5bf9e8da8df47953e3471d0062

**Comment by abchatra** [comment]
Fixed. Forever block is part of new project
