### ISSUE TITLE
javascript initialisation of variables

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#983]
The following shows some unexpected results in javascript/blocks from a simple start of 
let item = 9 
and other let's
![variableresults](https://cloud.githubusercontent.com/assets/866122/21432904/e58fabfc-c86d-11e6-8aca-dd845e30a617.gif)

**Comment by OwenBrotherwood** [comment]
The writing of let with pauses still gives unnecessary warnings 
![image](https://cloud.githubusercontent.com/assets/866122/22402653/893ec1b2-e5ff-11e6-86c6-f24fc8c420fe.png)
![image](https://cloud.githubusercontent.com/assets/866122/22402656/9dfca196-e5ff-11e6-9ce9-5f5123c29f77.png)
with popups about not being able to run the program
![image](https://cloud.githubusercontent.com/assets/866122/22402658/c3055ce4-e5ff-11e6-8fc9-9ec84932bc02.png)
However, this javascript is ok when switching blocks<->javascript
let b = 2
let a = 1
where switch adds
let b = 0
let a = 0
a = 1
b = 2

**Comment by abchatra** [comment]
The microbit issues have moved to https://github.com/Microsoft/pxt-microbit repo. 
If this is still an issue please open the issue in that repo or let us know, we will reopen in that repo.
