### ISSUE TITLE
artifact on reset 

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#984]
A strange artifact appears after reset
![variableresults](https://cloud.githubusercontent.com/assets/866122/21434285/f6a59338-c873-11e6-89de-adb9c4528f28.gif)

**Comment by pelikhan** [comment]
Fix at https://github.com/Microsoft/pxt-microbit/commit/03c2df327703cf0ec61cf4bf887fdf42a6febcde

**Comment by OwenBrotherwood** [comment]
https://pxt.microbit.org/beta PXT version: 0.7.6 OK

**Comment by sgk** [comment]
Is this what you intended?

https://pxt.microbit.org/beta
pxt.microbit.org version: 0.7.6
PXT version: 0.7.9

![image](https://cloud.githubusercontent.com/assets/485416/21454309/ccfb55ee-c95a-11e6-8b74-95f3f64ea76d.png)

**Comment by pelikhan** [comment]
yes on start should be visible.

**Comment by sgk** [comment]
And, no smiley :) blink example. Right?
