### ISSUE TITLE
better documentation for block help plumbing in extension

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt#9880]
Extension authoring docs are way out-of-date with respect to block help. Richard's extensions for pxt-arcade show the way:

https://github.com/microsoft/arcade-character-animations

**Comment by Jaqster** [comment]
Just to add a bit more context here.  When you click on an extension block and select "Help", you would expect the side docs to open a reference article (just like they do for mainline blocks).
<img width="461" alt="image" src="https://github.com/microsoft/pxt/assets/22108954/031846e5-1fef-49b0-8ca5-55a31e7c2286">
But instead you get redirected to the extension's readme - https://makecode.microbit.org/pkg/microsoft/pxt-neopixel

**Comment by ganicke** [comment]
This all works due to the magic of the `github:` prefix in the jsDoc `%help` attribute. I will add some info discussing this in that page.

```
//% help=github:arcade-character-animations/docs/set-character-state
```
