### ISSUE TITLE
faq: Supported language features in connection with blocks

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#989]
https://pxt.microbit.org/js/faq contains some indications to a line where supported contra not to be supported/unsupported features.

Is there a set of supported languages that are supported in the script language that will probably not be supported in blocks.

The question's context was functions with lexical scoping and recursion
 which is, as yet, not in blocks

Edit
In general, if one just writes script, and then try blocks, one can risk a non-support in blocks contra scripts

**Comment by pelikhan** [comment]
* In Scratch and most most block-based language, all variables are global.
* Functions might be introduced in the future as a separate package.

**Comment by OwenBrotherwood** [comment]
There could be a case for a faq for blocks, like faq for script: with general outline of support for, possible support and never will support.
Causes a new problem, 2 faq's may be inconvenient, but can cross reference each other as a good substitute for one one.

Luckily, the kids I have are not asking: but other's will probably begin asking "why isn't ...something or other a block" (like switch)

**Comment by abchatra** [comment]
Question answered
