### ISSUE TITLE
Docs point to nonexistent samples for targets

### ISSUE THREAD

**Issue by dragonx** [Microsoft/pxt#991]
I'm trying to create a target, but I can't find this sample.

[sample target sources](https://github.com/microsoft/pxt-sample)

I'm trying to start with the microbit target, but I'll likely end up with just a pure JS implementation, so hopefully I won't need some of the cpp core components in the microbit target.

**Comment by abchatra** [comment]
For microbit you can always clone the pxt-microbit repo. Sample target sources were not maintained and hence removed.

**Comment by abchatra** [comment]
Also we will update the docs

**Comment by dragonx** [comment]
@abchatra Thanks.  I'm trying to create my own target from scratch for some of our robots.  Is there a simpler target to start from other than microbit?  We won't need the hex compiler, and setting "hashex":false in pxtarget.json seems to cause a bunch of things to fail in pxt-microbit.

**Comment by pelikhan** [comment]
The pxt-sample repo is now public.
