### ISSUE TITLE
Show simulator without showing code/blocks

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#993]
On microbit.co.uk, it is possible to shrink a window so that the simulator runs full screen.

We have teachers asking to return this 'feature' to PXT because it allowed them to show a completed program on the screen without revealing the code behind it. This is used as a way to set challenges for the class.

So, though it doesn't need to be implemented the same way in PXT as it was in blocks/TD, it would be great to allow users to show *just* the simulator fullscreen.

**Comment by microsoftsam** [comment]
Fixed by #1120
