### ISSUE TITLE
"Add package" has no obvious indication of other packages available

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#995]
Add package shows a selection of the available packages.
Pressing Search, with no Search text, does not give a full list (expected behaviour) it just shows what is already shown.
It is possible to Search "package" and obtain a list.

**Comment by OwenBrotherwood** [comment]
While I am at it, what about a ? in the icon that shows the package so one can quickly access it's use?

**Comment by carlosperate** [comment]
I've found the same issue with finding packages, any chance there could be a simple way to discover all available packages?

**Comment by pelikhan** [comment]
@jaustin

**Comment by jaustin** [comment]
@OwenBrotherwood is your main aim to see all possible packages? Or all supported?

**Comment by OwenBrotherwood** [comment]
@jaustin Supported, ie those which can appear in a search.
At the moment, one has to use vowels to find packages.
Packages should not appear if not supported.
Easier method for finding supported packages.

Unsupported are out of scope: of course interesting if how to use if not supported and with some appropriate marking if appear in search (even if guessing with vowels)

**Comment by abchatra** [comment]
+1 we will prioritize this feature.
