### ISSUE TITLE
sim "click" on P0-2 has area of click issue 

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#997]
"click" on P0-2 has area of click issue
There seems to be an area of click issue with where on the connector one can click to change color.
The enclosed gif should help in understanding.
Basically, click at bottom is ok: other areas are not
![kitronikbuggylinefollower](https://cloud.githubusercontent.com/assets/866122/21494010/bde3a6ea-cc0e-11e6-8b9f-a1923be35a0c.gif)

**Comment by OwenBrotherwood** [comment]
For completeness, the following is also available
The click issue plus other issues with the sim causes skepticism for the usage of the sim as a logic test for programs involving hardware

pin colors for p8/16 do not follow inputs from p0/1
![image](https://cloud.githubusercontent.com/assets/866122/22137524/e66a0188-dedb-11e6-9407-601a96e6c340.png)

basic.forever(() => {
    pins.digitalWritePin(DigitalPin.P8, pins.digitalReadPin(DigitalPin.P0))
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P16, pins.digitalReadPin(DigitalPin.P1))
    basic.pause(100)
})

**Comment by OwenBrotherwood** [comment]
The issue is still present

**Comment by abchatra** [comment]
The microbit issues have moved to https://github.com/Microsoft/pxt-microbit repo. 
If this is still an issue please open the issue in that repo or let us know, we will reopen in that repo.
